### ISSUE TITLE
"r_wadtextures 1" Couldn't saved from console command 

### ISSUE THREAD

**Issue by Gazername79** [FWGS/xash3d-fwgs#1001]
I played with different textures pack for half life 1 with halflife.wad pack, but couldn't load the wad textures automatically after i starting the game, so i type on console command "r_wadtextures 1" to enabled and it work, but then it goes back to original half life textures after i quit the game.

Xashdroid apk 32bit 0.20.1 build: ac05acf(i used)

**Comment by a1batross** [comment]
`r_wadtextures` is not supposed to be saved. GoldSrc don't save it either.

**Comment by Gazername79** [comment]
> `r_wadtextures` is not supposed to be saved. GoldSrc don't save it either.

So is not a bug, okay then
