### ISSUE TITLE
Увеличить лимит MAX_INIT_MSG

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1007]
Столкнулся с вылетом на большой карте (своей) где довольно много звуков. Выяснилось, что после загрузки сейва все активированные по ходу прохождения звуки отсылаются мессагой.
Думаю лимит нужно увеличить, тем более для прайма в будущем.
Цитата Дяди Миши:
"Signon-буффер переполнился. Когда декалей много, тоже может случится. Я обычно увеличивал его размер
engine\common\net_ws.h
#define MAX_INIT_MSG 0x20000 // max length of possible message
Вот здесь двойку поменять на тройку, что даст буффер на 192 килобайта. Должно хватить.
На совместимость с сетевым протоколом это не влияет."
Спасибо заранее!

**Comment by SNMetamorph** [comment]
Может имеет смысл размер буфера увеличить сразу до 1 мегабайта?

**Comment by a1batross** [comment]
Плюсую совет Дяди Миши, до 192 килобайт поднять и норм. Не пойдет, понимаем тройку на четверку.

**Comment by Aynekko** [comment]
Ксаш поддерживает вроде бы 4096 декалей, плюс в прайме еще декали на моделях есть. Я думаю стоит поднять с запасом.
Буду очень признателен, если сделаете в ближайшее время, т.к. пока получается тестить карту только с отключенными декалями(

**Comment by a1batross** [comment]
Поднял лимит повыше. @Aynekko проверяй

**Comment by Aynekko** [comment]
> Поднял лимит повыше. @Aynekko проверяй

Все отлично. Теперь сейвы грузятся. И по килобайтам под конец моей карты набралось около 125 кб (Signon network traffic:  124.479 Kb from server, 459 bytes to server). Так что хватит с лихвой. А тот сейв что вылетал - писал что там было 113 кб, хотя лимит был 128. Ну наверное там еще что-то досылалось.
