### ISSUE TITLE
Help with dissabling Texture filtering in OpenGl renderer

### ISSUE THREAD

**Issue by GelgoogJager** [FWGS/xash3d-fwgs#1009]
So after trying to find some answers online I still haven´t figured out how to dissable that godawfull texture filtering in Opengl renderer. I tried all the possible methods that work in steam copy, but had no luck so far with xash3d version.
I also tried software renderer but the graphics there look bugged, for example the lightning is bugged as are some primary collors like orange which renders as purple.
Could you tell me how to turn texture filtering off or show me some documentation with console commands that would allow the game look as close to software renderer as possible?
Thank you

**Comment by Vladislav4KZ** [comment]
gl_texture_nearest 1

**Comment by GelgoogJager** [comment]
> 

Thanks a bunch, I´m not sure what I was doing wrong before as I´ve also tried inputing similiar commands into the console. Is there some documentation, where I can look up other console commands, or are they basicaly the same as Steam half life?

**Comment by Vladislav4KZ** [comment]
You can type ``makehelp`` in console, to create a help.txt with all console commands and cvars with their descriptions.

**Comment by GelgoogJager** [comment]
Thanks a bunch
