### ISSUE TITLE
Half-Life Opposing Force CTF. При подборе флага игроков видна собственная модель

### ISSUE THREAD

**Issue by DENCHIKTEAM** [FWGS/xash3d-fwgs#1011]
### Карта op4ctf_dam, команда Opposing Force, моделька recruit. ###
https://ibb.co/NZmKWCT **флаг захвачен**
https://ibb.co/567bCKW **флаг доставлен**

### Та же карта, команда Black Mesa, моделька cleansuit scientist. ###
https://ibb.co/mDYBKNL **флаг захвачен**
https://ibb.co/D5kS6y1 **флаг доставлен**

### Флаг потерян. ###
https://ibb.co/0GpPshJ

**Comment by Vladislav4KZ** [comment]
Дубликат: https://github.com/FWGS/xash3d-fwgs/issues/415
