### ISSUE TITLE
How to read DLL in xash3d for Android

### ISSUE THREAD

**Issue by stephen-cusi** [FWGS/xash3d-fwgs#1014]
Xashds Android version has stopped development in 2017. Is there any plan to support the function of simulating x86 DLL on Android version in the future?

**Comment by Velaron** [comment]
https://github.com/FWGS/dllemu probably

**Comment by stephen-cusi** [comment]
> [https://github.com/FWGS/dlllemu](https://github.com/FWGS/dllemu)可能

Yes, but no release build
