### ISSUE TITLE
Краш после появления титра "Half-Life" на карте c0a0, в случае выключённой консоли.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#1015]
![image](https://user-images.githubusercontent.com/96422615/187207143-d13beb76-d405-47a5-b450-6829d9975f90.png)

**Comment by Vladislav4KZ** [comment]
Интересно, у меня этот баг не воспроизводится...

**Comment by Velaron** [comment]
> Интересно, у меня этот баг не воспроизводится...

Точно запускаешь без -dev и -console?

**Comment by Vladislav4KZ** [comment]
При запуске тренировочной карты, то же самое. Крашится.

**Comment by Vladislav4KZ** [comment]
> Точно запускаешь без -dev и -console?

Да, вообще без каких-либо аргументов

**Comment by Velaron** [comment]
> Баг воспроизводится только когда начинаешь игру, перед этим не запустив мультиплеерную

А потому что консоль и соответственно вывод в неё почему-то работает в мультиплеере всегда, даже если её не включать

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/4b05cf43995b62784f6dc76843262cdc4f671021
