### ISSUE TITLE
[MOD: Half-Life Delta] Неправильно работает фонарик

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1017]
Когда играешь в этот мод на Xash3D FWGS 0.20.1, фонарик освещает пространство вокруг игрока, а не светит туда, куда указывает прицел.

**Xash3D FWGS 0.20.1**
![hldelta_flashlight_xash3d.png](https://user-images.githubusercontent.com/22411953/187377396-bcd17301-a4ca-4ce6-a84b-d933631c44f7.png)

**GoldSource**
![hldelta_flashlight_goldsrc.png](https://user-images.githubusercontent.com/22411953/187377446-f400702f-3adf-4168-ba14-94100c57d927.png)

Баг воспроизводится как с ``gl_vbo 0``, так и с ``gl_vbo 1``.

**Comment by stephen-cusi** [comment]
Change the renderer, try it?

**Comment by Vladislav4KZ** [comment]
> Change the renderer, try it?

Same thing in software renderer.

**Comment by Vladislav4KZ** [comment]
Прикрепляю сохранение, для быстрой проверки работы фонарика в вентиляции
[ventflashlight.zip](https://github.com/FWGS/xash3d-fwgs/files/10368850/ventflashlight.zip)

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите:
https://github.com/FWGS/xash3d-fwgs/commit/962f88d31bc4dd792d8c9fc78fa363394b27eb1b
