### ISSUE TITLE
Есть подозрения, что вместо tga текстур для скайбокса загружаются bmp текстуры.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#1018]
Ибо на текстурах скайбокса стали заметны градиенты, как при 8-битном bmp.
Есть подозрения, что началось это после этого коммита https://github.com/FWGS/xash3d-fwgs/commit/87ce35b32d1d7101b5322b4b409e0d47c277365f.
![image](https://user-images.githubusercontent.com/96422615/187443360-1e2d90df-93db-4999-b810-fe3c2b6c49c0.png)

**Comment by nekonomicon** [comment]
Нужно как-то переделать загрузку изображений так чтобы сначала искались изображения всех форматов в приоритетной директории, иначе будут пляски от бага к багу.

**Comment by nekonomicon** [comment]
Но в принципе это всех ресурсов касается.
В данный момент движок грузит ресурсы приоритетного формата откуда может, но это не корректное поведение.

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/f29a9f5f589b8cdfe9b0c33266ded0418b7eb670
