### ISSUE TITLE
How to turn off the information displayed in the upper left corner

### ISSUE THREAD

**Issue by stephen-cusi** [FWGS/xash3d-fwgs#1019]
![30cdae8de20a4cc2](https://user-images.githubusercontent.com/111830109/187645320-804d45b2-2925-4625-aaea-2935857cff74.png)
How can this information display be turned off? Using - console will still display.

**Comment by Vladislav4KZ** [comment]
con_notifytime -1

**Comment by stephen-cusi** [comment]
> con_notifytime -1

Желаю тебе счастья
