### ISSUE TITLE
В voice_codecinfo отображается странный битрейт

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1021]
```
Encoder:
     Bitrate: 1857035.250 kbps
     Complexity: 180405396
```

**Comment by Vladislav4KZ** [comment]
И при каждом вводе этой команды, значение Complexity меняется.

**Comment by a1batross** [comment]
`voice_codecinfo` удалён, так как с custom мы не можем получать какую-либо информацию от Opus.

Возможно это баг, надо зарепортить. 🤷🏽
