### ISSUE TITLE
искажения звука

### ISSUE THREAD

**Issue by hypeq** [FWGS/xash3d-fwgs#1024]
при игре звук искажается как-будто при низком фпс, фантомный треск и повторения. с последним билдом появилось

**Comment by a1batross** [comment]
Когда? Где? Какая ОС? Как повторить? Это связано с войсчатом? Это
происходит в мультиплеере или в сингле? На какой карте? Какой конкретно
звук? Какой формат файла звука?

Если пишите багрепорты, пишите их подробно.

вс, 4 сент. 2022 г., 01:28 hypeq ***@***.***>:

**Comment by hypeq** [comment]
в текстовом формате я никак вам не обьясню, любые wav, звук выстрела из гаусса например. ос debian 11, звук напоминает треск как в войсе

**Comment by hypeq** [comment]
https://user-images.githubusercontent.com/95980101/188292270-8f3f62cb-762e-4705-b517-aa83ccccf8f9.mp4

в конце видео слышно то самое повторение

**Comment by hypeq** [comment]
в мультиплеере начинается ад кствти

**Comment by a1batross** [comment]
Can't reproduce

**Comment by hypeq** [comment]
проблема решилась сама собой
