### ISSUE TITLE
TE_TAREXPLOSION and TE_EXPLOSION2 inconsistency with GoldSource

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#1027]
TE_TAREXPLOSION in GoldSource creates yellow-orange particles and also plays an explosion sound.
![scripttest0000](https://user-images.githubusercontent.com/5596503/188617484-7766b8a8-9d9a-4c26-baa1-85bec75f2cb8.png)

In xash3d-fwgs it creates red particles and doesn't play a sound
![scripttest_0000](https://user-images.githubusercontent.com/5596503/188617606-28c96108-ac88-47f8-a23d-8b0ad84846bb.png)

TE_EXPLOSION2 in GoldSource ignores its parameters (starting color and number of colors) and always creates yellow-white particles.
![scripttest0001](https://user-images.githubusercontent.com/5596503/188617777-8df9278b-342a-437b-bbc0-bf6d21b072c8.png)

In xash3d-fwgs it takes the parameters into account. Sending 0 as color produces black particles.
![scripttest_0001](https://user-images.githubusercontent.com/5596503/188617899-ee19345a-51d1-4713-970e-8f156b418163.png)

TE_EXPLOSION2 plays a sound on both engines as expected.

The inconsistency is demonstrated with the help of `env_quakefx` entity from Spirit of Half-Life.

**Comment by Velaron** [comment]
Where can I get the map and which version of SoHL do I use?

**Comment by FreeSlave** [comment]
[quakefx.bsp.zip](https://github.com/FWGS/xash3d-fwgs/files/9507290/quakefx.bsp.zip)
Here's the test map
I tested it on sohl1.2, but I think it's the same on any latter version.

You can also see that tarexplosion particles move differently on Xash3d and GoldSource.

**Comment by a1batross** [comment]
Fixed in two last commits. Thanks for provided map.

@FreeSlave can you check pls?

**Comment by FreeSlave** [comment]
@a1batross yep, works for me too.
