### ISSUE TITLE
Неработает выключение освешения

### ISSUE THREAD

**Issue by Elinsrc** [FWGS/xash3d-fwgs#1028]
Свет включен 
![on](https://user-images.githubusercontent.com/99191833/188923020-c54baf40-9f7e-4bc2-a854-61f81ebd5202.png)
Свет выключен 
![off](https://user-images.githubusercontent.com/99191833/188923223-a0c234df-75f1-4f82-9605-93e57ea0ccd9.png)

Должно выглядить так 
![19](https://user-images.githubusercontent.com/99191833/188924387-43ee5953-2266-44e7-81be-962683fca26f.png)

**Comment by Elinsrc** [comment]
Если vbo включен, то выключение работает.

**Comment by Vladislav4KZ** [comment]
Лучше ещё приложить саму карту, и описать где это происходит (ОС, видеокарта, какие драйвера на неё стоят или что-то ещё). И по твоим словам в дискорде это происходит только с выключенным VBO ``gl_vbo 0``.

У меня на Windows такой баг не воспроизводится. Как с ``gl_vbo 0``, так и с ``gl_vbo 1``.

У меня NVIDIA GeForce 9500 GT, дрова последней версии 342.01

**Comment by Elinsrc** [comment]
Сама карта https://elinserver.ru/fastdl/maps/crossfire_src.bsp
Проверил на Windows работает с выключенным gl_vbo 0 и gl_vbo 1, до этого запускал на linux ubuntu 22.04

**Comment by a1batross** [comment]
Как в неё легально попасть-то?

**Comment by a1batross** [comment]
noclip-ом пролетел, попереключал, работает.

**Comment by Elinsrc** [comment]
Я нашел проблему , уменя почему-то стояло r_dynamic 0, я включил его обратно и все стало нормально.
