### ISSUE TITLE
64 bit dylib of hl causes the program to freeze on startup.

### ISSUE THREAD

**Issue by KayvK** [FWGS/xash3d-fwgs#1034]
Symptoms: upon launching the executable (./xash3d) a process shows up but it is forever stuck that way.
Loading up the log shows it gets about this far before it shits itself:

[03:47:12] Console initialized.
[03:47:12] FS_LoadProgs: filesystem_stdio successfully loaded
[03:47:12] IN_TouchInit()

by deleting the file hl_amd64.dylib, it loads up, but without the option to select a new game, since no hl library is present.

I recompiled the SDK and the engine on _**three different computers**_ with various different settings to no avail.
It compiles successfully, but it still doesn't work.
I've wasted a lot of my time on this and I'd love it if someone could help me get over this one stupid bug.

Thanks,
-KK

**Comment by stephen-cusi** [comment]
Old version

**Comment by KayvK** [comment]
> Old version

I'm using the latest SDK and engine source code.
If you're asking I try compiling the old version, I tried but I can't get the CMake compiler to recognize the 64-bit only flag.

**Comment by KayvK** [comment]
I stand corrected. Turns out the CMake flags were in the cachefile and it now builds successfully and runs. Thank you!

The bug still applies in the new version, though, and that'll still drive me crazy.

**Comment by a1batross** [comment]
We don't support OSX. #61

**Comment by KayvK** [comment]
I also tried swapping the new xash3d binary for the old engine binary, and it works, but if I replace the old libxash.dylib as well, the problem returns. 
Unless the binaries are identical, I think it's a bug with the new libraries compiled. I'll try some more.

**Comment by a1batross** [comment]
It's better not mix old xash3d-fwgs binaries with new ones, because some internal structures and API function were changed.

Run the engine with GDB and look where it stuck. Nobody from FWGS have any computers with macOS, so we can't debug it.

Old engine was debugged through virtual machine, but it's very complicated process and time-consuming for such unpopular and useless platform as Apple's operating systems.

**Comment by KayvK** [comment]
> It's better not mix old xash3d-fwgs binaries with new ones, because some internal structures and API functions were changed.
> 
> Run the engine with GDB and look where it stuck. Nobody from FWGS have any computers with macOS, so we can't debug it.
> 
> Old engine was debugged through virtual machine, but it's very complicated process and time-consuming for such unpopular and useless platform as Apple's operating systems. I just stopped using any macOS VMs after switched to Ryzen.

Ok, now I am VERY confused.
Running xash3d regularly doesn't work.
But if I select it in gdb and then type run, it magically boots to life. HOW?

**Comment by KayvK** [comment]
Here's the log of it working under gdb, by the way:
`iMac-2:newengine kk$ sudo gdb xash3d
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin16.7.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xash3d...
(gdb) run
Starting program: /Users/kk/Documents/newengine/xash3d 
Note: this version of macOS has System Integrity Protection.
Because `startup-with-shell' is enabled, gdb has worked around this by
caching a copy of your shell.  The shell used by "run" is now:
    /Users/kk/Library/Caches/gdb/bin/sh
[New Thread 0x1a03 of process 55785]
[New Thread 0x1d03 of process 55785]
[New Thread 0x1e03 of process 55785]
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSApplicationDelegate' in minsymtab
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSObject' in minsymtab
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSTextInputClient' in minsymtab
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSDraggingDestination' in minsymtab
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSObject' in minsymtab
warning: can't find symbol 'l_OBJC_PROTOCOL_$_NSWindowDelegate' in minsymtab
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLArgument.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCommandBuffer.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCommandQueue.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCompilerCache.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCompilerConnection.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLCompilerShared.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLComputePipeline.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLDebug.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLDebugCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLDepthStencil.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLDevice.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLError.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLFunctionConstantValues.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelBlitCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelBuffer.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelCommandBuffer.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelCommandBufferStorage.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelCommandQueue.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelComputeCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelDebugCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelDevice.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelDeviceShmem.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelDeviceShmemPool.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelError.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelMemoryInfo.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelParallelRenderCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelPooledResource.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelRenderCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelResource.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelResourcePool.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLIOAccelTexture.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLLibrary.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLParallelRenderCommandEncoder.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLPixelFormat.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLRangeAllocator.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLReflection.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLRenderPass.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLRenderPipeline.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLResource.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLResourceList.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLResourceListPool.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLSampler.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLStageInputOutputDescriptor.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLStatistics.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLTexture.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/Metal/Metal-87.18~133/TempContent/Objects/Metal.build/Framework.build/Objects-normal/x86_64/MTLVertexDescriptor.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRAssetCatalogParser.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRAssetCatalogSet.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRDataConverter.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRDataInfo.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRDataScaler.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRDefaultBuffer.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRDeferredDataInfo.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRError.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRFastDataConversion.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRFileDataSourceProvider.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRImageIndependent.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXROptions.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRParserImageIO.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRParserKTX.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRPixelFormatInfo.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRSlowDataConversion.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TXRTexture.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/TextureIO/TextureIO-2.8~14/TempContent/Objects/TextureIO.build/TextureIO-OSX.build/Objects-normal/x86_64/TextureIO_vers.o': can't open to read symbols: No such file or directory.
[New Thread 0x1a1f of process 55785]
[New Thread 0x1f03 of process 55785]
[New Thread 0x2003 of process 55785]
[New Thread 0x2103 of process 55785]
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/BookmarkCommon.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/BookmarkData.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CFURLAliasInteroperability.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CFURLBookmark.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CFURLBookmarkFile.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CFURLBookmarkProperties.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CFURLBookmarkResolution.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/CoreServicesInternal_vers.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/ExternalProvider.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/FileURL.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/FileURLEnumerator.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/FileURLReplaceObject.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/PlatformUtils.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/ScopedBookmarksClient.o': can't open to read symbols: No such file or directory.
warning: `/Library/Caches/com.apple.xbs/Binaries/CoreServicesInternal/CoreServicesInternal-276.2~3/TempContent/Objects/CoreServicesInternal.build/CoreServicesInternal.build/Objects-normal/x86_64/ftsattr.o': can't open to read symbols: No such file or directory.
[New Thread 0x224b of process 55785]
[New Thread 0x2287 of process 55785]
[New Thread 0x230b of process 55785]
[New Thread 0x241b of process 55785]
[New Thread 0x2553 of process 55785]
[New Thread 0x2603 of process 55785]
[New Thread 0x2703 of process 55785]
[New Thread 0x2803 of process 55785]
[New Thread 0x290b of process 55785]
[New Thread 0x2a03 of process 55785]
[New Thread 0x2b03 of process 55785]
[New Thread 0x2c23 of process 55785]
[New Thread 0x2d03 of process 55785]
[Inferior 1 (process 55785) exited normally]
(gdb) exit
`

**Comment by KayvK** [comment]
Neither sh nor bash got it to work. Code signing the binary didn't work either.

By running xash3d and then attaching gdb to the PID, it returned this:
`0x00007fffc1687966 in ?? () from /usr/lib/system/libsystem_kernel.dylib`

**Comment by KayvK** [comment]
Through some manual debugging, I figured it out: It doesn't crash, sv_main.c gets stuck in the while loop at line 3136.

Here's the code:

while( start - base > INT_MIN )
		{
			void *mapptr = mmap((void*)((unsigned long)start & ~(pagesize - 1)), arrlen, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_PRIVATE, 0, 0 );
			if( mapptr && mapptr != (void*)-1 && mapptr - base > INT_MIN && mapptr - base < INT_MAX )
			{
				ptr = mapptr;
				break;
			}
			if( mapptr ) munmap( mapptr, arrlen );
			start -= arrlen;
		}

**Comment by KayvK** [comment]
Wow. Another very strange occurance: I had a process that was stuck that I forgot to close, and it appears to have escaped the dreaded `while` loop, as it started the game.

**Comment by KayvK** [comment]
@a1batross do you know what the purpose of the loop is?

**Comment by a1batross** [comment]
@KayvK yeah, it's important. And there are too many layers to that.

There is a 32-bit datatype called `string_t` exists in the gamedlls. In the Quake engine, it was meant to hold the descriptor to Quake's virtual machine string pool. Unfortunately for us, in Half-Life, it holds the pointer difference between some base address and string literal. We can't extend `string_t` without breaking compatibility.

Instead, we added a hack in Half-Life SDK to replace the macro by a smarter function that will use engine string pool if `string_t` was overflowed. 

Still, the engine needs to allocate the strings the way so simple adding to string base will yield a valid pointer. That's how this hack was born, by this we're trying to allocate the string pool closer to the server library, so the array will fit within the 32-bit range.

**Comment by a1batross** [comment]
You can disable `USE_MMAP` macro, and it will apparently work with OSX.

Old engine commit: https://github.com/FWGS/xash3d/commit/725fd84b5ba8d405979d63df7a906feb1bc87d51

**Comment by a1batross** [comment]
Try again with latest commit.

**Comment by KayvK** [comment]
> Try again with latest commit.

Confirmed running on Mac OS 11.6.8. Thanks for your help & for digging up that old commit!

**Comment by mittorn** [comment]
It is intended to force string pool to be placed near server library code. It's needed for old amd64 hlsdk builds, otherwise MAKE_STRING macro generates crash. Our hlsdk branch has workaround for this
