### ISSUE TITLE
[bug] Disappearing parts of interface.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#1039]
Idk how to reproduce it, happens randomly:
![Скриншот 14-09-2022 013849](https://user-images.githubusercontent.com/34350690/190480651-c931ccb3-8adb-42fa-b774-d5f81bb122e2.png)

**Comment by Vladislav4KZ** [comment]
Duplicate of: https://github.com/FWGS/xash3d-fwgs/issues/416
