### ISSUE TITLE
Аналог cue points для mp3

### ISSUE THREAD

**Issue by CASPERX69XSOFT** [FWGS/xash3d-fwgs#1042]
Древняя проблема, что без меток в wav, невозможно сделать зацикленный звук, так как ксаш понимает и другие форматы, в них эти метки сделать нельзя, это в целом усложняет разработку модификаций под движок. Любой звук для цикла нужно обрабатывать в Cool Edit 2000, который не бесплатен

Больше информации про это:

https://twhl.info/wiki/page/VERC%3A_Looping_custom_ambient_generic_sounds

**Comment by Vladislav4KZ** [comment]
Cue метки можно делать не только в Cool Edit 2000, в GoldWave и SoundForge тоже можно. Только они тоже не бесплатные.

GoldWave полностью бесплатен только для Android, а для ПК есть пробная версия.

Пока ещё не нашёл бесплатных аудиоредакторов с этой функцией, так что ничего посоветовать не могу.

**Comment by SNMetamorph** [comment]
Надо добавить флажок Loop в энтити, связанные с воспроизведением звуков. Только вот у функции для проигрывания звуков нет подобного параметра. Т.е. нужно добавлять какой-то флаг для этих функций

**Comment by nekonomicon** [comment]
Зацикливание предусмотрено в PrimeMusicStream на клиенте.

**Comment by a1batross** [comment]
@nekonomicon про CUE он тем не менее прав. Сейчас нет возможности указать какой фрагмент аудиофайла нужно ~~залупливать~~зацикливать

**Comment by a1batross** [comment]
Да и эти же cue points похоже и правда не поддерживаются даже Audacity.

**Comment by 0x4E69676874466F78** [comment]
Это же просто тег. 
ID3v2 chapters
https://id3.org/id3v2-chapters-1.0
https://id3v2-chap-tool.sourceforge.net
В audacity это называется Audacity labels https://manual.audacityteam.org/man/creating_and_selecting_labels.html
Вот скрипт для экспорта https://gist.github.com/Bios-Marcel/7f6a44ac324d955e4ee04b9346f318ed

**Comment by a1batross** [comment]
@0x4E69676874466F78 тогда надо и этот тег читать.

Сейчас движок ищет в WAV файле недокументированный чанк `cue `, который и правда похоже умеет создавать только одна программа.

**Comment by 0x4E69676874466F78** [comment]
@a1batross 
> Сейчас движок ищет в WAV файле недокументированный чанк cue , который и правда похоже умеет создавать только одна программа.

https://en.wikipedia.org/wiki/Broadcast_Wave_Format
EBU Tech 3285 Supplement 2: Capturing Report (includes Quality and Cue-sheet data) 
https://tech.ebu.ch/docs/tech/tech3285s2.pdf

**Comment by 0x4E69676874466F78** [comment]
https://github.com/PRX/prx-wavefile#add-cue-points-to-files

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/extensions/mp3-loops.md
