### ISSUE TITLE
vgui.x is missing in linux appimage and windows 7z

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/xash3d-fwgs#1044]
Title say all

**Comment by AruMoon** [comment]
You should take that library from steam version

**Comment by TheKingFireS** [comment]
> You should take that library from steam version

Doesn't work for linux appimage.

**Comment by Vladislav4KZ** [comment]
> You should take that library from steam version

Half-Life in Steam is 32bit

**Comment by Vladislav4KZ** [comment]
> > You should take that library from steam version
> 
> Doesn't work for linux 32bit appimage.
> "Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory"
> ![image](https://user-images.githubusercontent.com/71936968/190852156-a7d43826-532b-48b2-bf93-4ab71d9ea9c5.png)
> 

Where did you get the client that requires vgui?

**Comment by TheKingFireS** [comment]
> > > You should take that library from steam version
> > 
> > 
> > Doesn't work for linux 32bit appimage.
> > "Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory"
> > ![image](https://user-images.githubusercontent.com/71936968/190852156-a7d43826-532b-48b2-bf93-4ab71d9ea9c5.png)
> 
> @TheKingFireS Where did you get the client that requires vgui?

from steam...

**Comment by Vladislav4KZ** [comment]
> from steam...
@TheKingFireS Are you trying to run a 32bit client on a 64bit OS?

You need to build the 64bit client and server libraries from this repository https://github.com/FWGS/hlsdk-portable

**Comment by TheKingFireS** [comment]
> > from steam...
> 
> @TheKingFireS Try to build the client and server libraries from this repository (without VGUI) https://github.com/FWGS/hlsdk-portable

well i run 32bit appimage before and it worked like fine, i will dig old commits.

**Comment by TheKingFireS** [comment]
fd152e8 commits is only actually worked

**Comment by Vladislav4KZ** [comment]
> fd152e8 commits is only actually worked

I seem to understand that the vgui.so/vgui.dll file is missing in the engine package since the vgui_support folder was moved, but the build scripts did not specify a new path to the folder

**Comment by Vladislav4KZ** [comment]
I fixed it in the PR https://github.com/FWGS/xash3d-fwgs/pull/1045, now vgui.dll and vgui.so are present in the engine files, both for Windows and Linux

**Comment by TheKingFireS** [comment]
> I fixed it in the PR #1045, now vgui.dll and vgui.so are present in the engine files, both for Windows and Linux

It's worked right now.
