### ISSUE TITLE
В режиме наблюдателя иногда не срабатывает анимация перезарядки MP5 (9mmAR)

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1048]
Баг воспроизводится как на Android, так и на  Windows

**Comment by nekonomicon** [comment]
C оригинальными библиотеками HL?
На GoldSource как?

**Comment by Vladislav4KZ** [comment]
> Смог только сейчас проверить, там так же.


Точнее, там вообще ни разу не воспроизвелась анимация перезарядки. На ксаше хоть иногда её видно.
