### ISSUE TITLE
crash launcher xash3d

### ISSUE THREAD

**Issue by melomansky** [FWGS/xash3d-fwgs#1050]
![Screenshot_20220923_091034](https://user-images.githubusercontent.com/94536394/191901382-03508015-d27f-4b2a-9714-e56c7d181f4d.jpg)

crashes on 32/64 bits, xash3d version 0.20.1

**Comment by a1batross** [comment]
Is it new @Velaron port?

Port from GitHub releases is probably will be gone as new port will take its place soon.

**Comment by hypeq** [comment]
he dont have access to new beta velaron port

**Comment by hypeq** [comment]
it is maybe continuos build

**Comment by Vladislav4KZ** [comment]
In Google Play, the new beta of Xash3D FWGS 0.21 is now in early access for everyone.

**Comment by melomansky** [comment]
Uploading VID_20220923_121105_488.mp4…

**Comment by melomansky** [comment]
https://user-images.githubusercontent.com/94536394/191928820-257a1d88-ccdf-4bfc-a4ac-0afde68ddd7f.mp4

**Comment by Velaron** [comment]
Жди обнову, дам знак как только можно пробовать

**Comment by melomansky** [comment]
> Это новое@Velaronпорт?
> 
> Порт из релизов GitHub, вероятно, исчезнет, ​​так как новый порт скоро займет его место.



> Это новое@Velaronпорт?
> 
> Порт из релизов GitHub, вероятно, исчезнет, ​​так как новый порт скоро займет его место.



> Is it new @Velaron port?
> 
> Port from GitHub releases is probably will be gone as new port will take its place soon.

this is the port that is from the play market 0.20.1(early access)

**Comment by a1batross** [comment]
Ничего не ясно. То что ты выложил не ясно откуда взялось (похоже на где-то закоррапченную память) и при каких условиях не работает. Минимум информации, чтобы тут все сидели и гадали.

Новый порт пока не доделан до конца, его необязательно было ставить. Вопрос был чисто убедиться.

**Comment by melomansky** [comment]
> Is it new @Velaron port?
> 
> Port from GitHub releases is probably will be gone as new port will take its place soon.

this is the port that is from the play market 0.20.1(early access)

**Comment by melomansky** [comment]
> Ничего не ясно. То что ты выложил не ясно откуда взялось (похоже на где-то закоррапченную память) и при каких условиях не работает. Минимум информации, чтобы тут все сидели и гадали.
> 
> Новый порт пока не доделан до конца, его необязательно было ставить. Вопрос был чисто убедиться.

it doesn't even let me select a directory.

**Comment by a1batross** [comment]
Да пиши уже на русском если он тебе понятен, зачем переводить. Для багрепортов принимаются оба.

**Comment by melomansky** [comment]
> Да пиши уже на русском если он тебе понятен, зачем переводить. Для багрепортов принимаются оба.

Good

**Comment by Alprnn357** [comment]
@melomansky 
Xash3D 0.21 Google Play version checks this  directory: `/data/data/su.xash.engine/files/`

- If you have root access, you can move half life game data to it.

- If it's non-root, you **HAVE TO** use Android File Manager (com.android.documentsui) which is preinstalled in every android device. It's usually used for giving SD Card access to the app. Open the app > Left sided menu > Xash3D FWGS, xGB free. Move the data to here.

**Comment by Alprnn357** [comment]
> @melomansky Xash3D 0.21 Google Play version checks this directory: `/data/data/su.xash.engine/files/`
> 
> * If you have root access, you can move half life game data to it.
> * If it's non-root, you **HAVE TO** use Android File Manager (com.android.documentsui) which is preinstalled in every android device. It's usually used for giving SD Card access to the app. Open the app > Left sided menu > Xash3D FWGS, xGB free. Move the data to here.

Make an activity shortcut if the android file manager app isn't exist. **DON'T USE THIRD PARTY FILE MANAGER APP**

**Comment by Alprnn357** [comment]
Make an activity shortcut if the android file manager app isn't exist. **DON'T USE THIRD PARTY FILE MANAGER APP**

**Comment by TheKingFireS** [comment]
just got google play xash3d running, but it just launch straight into Half-Life instead of good old options

**Comment by a1batross** [comment]
@TheKingFireS it's all in development.
