### ISSUE TITLE
Когда конектишся к серверу кнопки запускаются во время загрузки на сервер

### ISSUE THREAD

**Issue by melomansky** [FWGS/xash3d-fwgs#1054]
xash3d version 0.21(google play market) in game half life 1

**Comment by EternalCringe** [comment]
Так было и в ранних версиях 0.20, так что не вижу смысла писать это в issues

**Comment by melomansky** [comment]
> Так было и в ранних версиях 0.20, так что не вижу смысла писать это в issues

а фикс будет?

**Comment by a1batross** [comment]
Я вообще ничего не понял. @melonmansky ты можешь описывать проблему максимально подробно? Нет, видео загружать не надо, от прошлого я от стыда чуть не умер.

Если имеешь проблемы как с русским, так и английским языком, к сожалению мы не поймём друг друга.

**Comment by melomansky** [comment]
> Я вообще ничего не понял. @melomansky ты можешь описывать проблему максимально подробно? Нет, видео загружать не надо, от прошлого я от стыда чуть не умер.
> 
> Если имеешь проблемы как с русским, так и английским языком, к сожалению мы не поймём друг друга.

когда заходишь на сервер, ждешь загрузку ище не зашёл на сервер, а кнопки запущены

**Comment by a1batross** [comment]
Какие кнопки? Куда запущены?

**Comment by erfty125** [comment]
Скорее всего про это он говорил  https://user-images.githubusercontent.com/98973867/193429065-672e14d5-5728-45fc-8c9f-664482695e69.mp4
