### ISSUE TITLE
Как сменить порт на новом движке?

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1056]
На Xash3D FWGS 0.19.2 есть квар ``port`` который соответственно меняет порт, и можно запустить несколько экземпляров серверов.

На Xash3D FWGS 0.20/0.21 нет такого квара. Я нашёл только ``hostport`` и ``ip_hostport`` но они все только для чтения.

**Comment by a1batross** [comment]
`-ip` и `-port` в аргументах командной строки.

**Comment by Vladislav4KZ** [comment]
Спасибо, всё работает.
