### ISSUE TITLE
[MOD: Team Fortress Classic] Проигрывается звук боли когда медик из вражеской команды лечит своего союзника

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1057]
Проверено на оригинальном клиенте TFC для Windows

**Comment by a1batross** [comment]
Эх, а говорили как комарик укусит :(

**Comment by Vladislav4KZ** [comment]
Запустил сервер с ботами на оригинальном HLDS, и там когда бот лечит союзника воспроизводится звук лечения.

Так что с уверенностью могу сказать что этот баг есть только в ксаше.
