### ISSUE TITLE
Крашится сервер при попытке передать файлы

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1058]
Когда клиент подключается к серверу где не настроен FastDL, то сервер крашится с этой ошибкой
```
Mem_Alloc: out of memory (alloc at D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\net_chan.c:542)
```

**Comment by SNMetamorph** [comment]
Такой вот стектрейс при вылете
![изображение](https://user-images.githubusercontent.com/25657591/206693556-bfe1815d-a515-4591-8f57-ab69d875c579.png)

**Comment by a1batross** [comment]
Может оно запросило слишком большой буфер?

Кстати крашиться от ENOMEM не стоит, а лучше корректно обрабатывать ситуацию когда памяти нет. Ну и не загружать файл :)

**Comment by SNMetamorph** [comment]
> Может оно запросило слишком большой буфер?
> 
> Кстати крашиться от ENOMEM не стоит, а лучше корректно обрабатывать ситуацию когда памяти нет. Ну и не загружать файл :)

Есть у меня кое какие догадки. Сама по себе структура `fragbuf_t` весит как минимум 65 кБайт (и так ВСЕГДА), притом что размер самого фрагмента может быть как 60+ кБайт, так и несколько сотен байт. И вот все данные делятся на фрагменты, коих в первом случае получается немного, а во втором очень много, и памяти соответсвенно выделяется тоже туча, притом она не используется.

**Comment by SNMetamorph** [comment]
```
typedef struct fragbuf_s
{
	struct fragbuf_s	*next;
	int		bufferid;
	sizebuf_t		frag_message;
	byte		frag_message_buf[NET_MAX_FRAGMENT]; // здесь 65535 байт
	qboolean		isfile;
	qboolean		isbuffer;
	qboolean		iscompressed;
	char		filename[MAX_OSPATH];
	int		foffset;
	int		size;
} fragbuf_t;
```

**Comment by a1batross** [comment]
Да нет, больше похоже на то, что пытаясь передать через фрагменты огромные файлы, они сначала копируются в память (разбиваясь на фрагменты), а памяти не хватает на такие приколы.

**Comment by SNMetamorph** [comment]
> Да нет, больше похоже на то, что пытаясь передать через фрагменты огромные файлы, они сначала копируются в память (разбиваясь на фрагменты), а памяти не хватает на такие приколы.

Большие - это сколько? У нас в тестах нет файлов размером больше пары мегабайт

**Comment by SNMetamorph** [comment]
Поправил в #1158
