### ISSUE TITLE
[MOD: Sven Coop 4.5] Баг с лучом от егона

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1060]
Воспроизводится только на выделенном сервере XashDS (неважно захостил ли ты его у себя на компьютере или на удалённом сервере).

У егона может отсутсвовать луч, или может рисоваться только в одном месте, либо вообще может отображаться двойной луч.

https://www.youtube.com/watch?v=qONVYLYaDpQ

**Comment by Vladislav4KZ** [comment]
Баг случается и на локальном сервере, но редко

**Comment by xWhitey** [comment]
Скорее баг самого мода, ибо там настолько вырвиглазно реализован егон в свене так и сама реализация луча сделана будто на коленке.

**Comment by a1batross** [comment]
Probably got fixed by 76d0608ee1d95aa8582ef7831f2166b631d3f71a
