### ISSUE TITLE
[MOD: Sven Coop 4.5] Ошибка загрузки звуков на карте they11

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1062]
В консоли появляются такие ошибки:
```
cl:  FMOD - Error loading sound at runtime: SvenCoop/sound/
```

Соответственно из-за них отсутствуют некоторые звуки в игре, например нет звуков выстрелов зомби-копов, не звука удара зонтом и т.д.

**Comment by romulasry** [comment]
So is it still not working?

**Comment by Vladislav4KZ** [comment]
Этот баг больше не воспроизводится.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3376
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/c73fa3d7a63b95bbfae01c358d6171c82100d3d7
Ветка: master
