### ISSUE TITLE
Дёрганная анимация движения NPC на coop серверах

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1065]
Все ишшуи с репортом об этом баге позакрывали, но сам баг то всё ещё остался.
https://youtu.be/L7hOD6dSMig (видео старое, но оно было записано на момент когда сделали "фикс" этого бага)

Такая проблема есть и на серверах на новом движке, я запускал Sven Coop 4.5 на новом ксаше, там баг тоже присутствует.

**Comment by Vladislav4KZ** [comment]
Вчера проверял анимацию движения NPC на тестовом сервере в Half-Life на новом движке, там она не дёргается. Но анимация поворота всё же подлагивает.

**Comment by a1batross** [comment]
Must be fixed in https://github.com/FWGS/xash3d-fwgs/commit/c2447d86343c01be5e136561b08481e4004bb8e1

and in https://github.com/FWGS/xash3d-fwgs/commit/f031c31b77ab3f122a2cd0402034dd66a2a985e5

**Comment by Vladislav4KZ** [comment]
Поставил последний билд движка, дёргания NPC всё ещё остались, хоть уже и не такие сильные.

**Comment by a1batross** [comment]
@Vladislav4KZ мне интересно не дёрганные ли это анимации в принципе.

Потому что отлаживал я напрямую смотря origin и angles -- в них ничего странного нет.

**Comment by SNMetamorph** [comment]
Ну я когда давно ковырялся с этим багом, подозревал что дело также может быть где-то в рендере студиомоделей

**Comment by a1batross** [comment]
В любом случае, как я выяснил, эти баги прекрасно воспроизводятся на демках. Более того, они ещё и работают с sys_timescale, что дает хотя бы возможность остановить исполнение в нужный момент.

Так что если встретите ещё подобное -- лучше записать демку и запостить новый багрепорт.

**Comment by SNMetamorph** [comment]
Я бы вот что сказал. В старом и новом движке этот баг есть. Но наиболее жестко он проявляется если с нового движка играть на старом сервере. Сейчас погляжу как теперь всё работает, если и клиент и сервер 48 протокол имеют.

**Comment by a1batross** [comment]
Если что коопмод был сломан из-за идиотского MOVETYPE_TOSS.

вс, 31 дек. 2023 г., 16:10 Vladimir ***@***.***>:

**Comment by SNMetamorph** [comment]
В общем поглядел, как себя ведут NPC в мультиплеере (не в кооп-моде). По большей части всё норм, но какие-то дёрганья все таки периодически проскакивают. Этот поганый баг как то с течением времени меняется, и теперь его воспроизвести труднее, чем это было ранее. Но то что я еще давно выяснил, это то, что он затрагивает все энтити с MOVETYPE_STEP. Коим также является флаг из TFC. Когда подбираешь вражеский флаг, он начинает нещадно мерцать. А еще если его где-то выкинуть в комнате, потом куда-то уйти чтобы та комната пропала из PVS, а потом быстро вернуться - у флага еще где-то 20 секунд idle анимация будет дёрганной. И спустя это время она нормализуется.

**Comment by SNMetamorph** [comment]
Записал и прикрепил демо с лагами флага в TFC. Сначала показал что флаг мигает когда прикреплён к игроку, потом ушёл в другую зону карты, вернулся и показал что у флага дёрганная idle анимация, и через несколько десятков секунд она стабилизировалась, прямо перед самым концом демо.
[tfc_flag_bugging1.zip](https://github.com/FWGS/xash3d-fwgs/files/13801299/tfc_flag_bugging1.zip)

**Comment by mittorn** [comment]
В coop есть хак, подменяющий movetype при отправке на клиент. Он некорректен, но на старом движке позволяет npc плавно двигаться. Не нужно пытаться исправить это со стороны клиента на новом движке. На новом движке coop всё равно не будет работать, как минимум нужно разрешить saverestore для мультиплеера в дедике (а может и в клиенте, но там есть сложности с сохранением состояния локального клиента), но в  целом можно было бы сделать автодетект новых клиентов и автодетект нового движка.

**Comment by a1batross** [comment]
Подобный хак изначально не должен был существовать. 

Посмотри последние коммиты, там специально включается интерполяция под старый протокол.
