### ISSUE TITLE
постоянно svc bad на old engine серверах

### ISSUE THREAD

**Issue by hypeq** [FWGS/xash3d-fwgs#1067]
![image](https://user-images.githubusercontent.com/95980101/193404979-75d90f17-4282-4c66-9a71-3347fd6749ee.png)
достаточно лишь немного пингануть как тут же тебя выкидывает.
движок не обновлял потому что там врятли это исправили

**Comment by unnamed9** [comment]
Дубликат https://github.com/FWGS/xash3d-fwgs/issues/502.

**Comment by a1batross** [comment]
@unnamed9 по логу не похоже на смену карты. Просто битый или неправильно прочитанный пакет.

**Comment by unnamed9** [comment]
@a1batross Это одна и та-же ошибка, что в упомянутом мной issue, что тут - отвал из-за битого пакета.

**Comment by a1batross** [comment]
@unnamed9 а причина разная. :)

**Comment by a1batross** [comment]
Если ещё воспроиводится, то можно переоткрыть или запостить новый багрепорт.

Желательно прикреплять демку.
