### ISSUE TITLE
[Android] упростить работу  с touch.cfg

### ISSUE THREAD

**Issue by erfty125** [FWGS/xash3d-fwgs#1068]
предлагаю так : если в тач.кфг будет замечен .tga файл то он сразу будет преобразовываться в .png или вовсе убиралось расширение файла конечно это не первостепенная задача ноо удобство перехода на новый движок добавляет

**Comment by nekonomicon** [comment]
Расширение не должно меняться, потому что кнопки могут быть в форматах bmp, tga или png.
Но указание явного расширения это косяк.
