### ISSUE TITLE
Bundle game resources into apk?

### ISSUE THREAD

**Issue by MoeMod** [FWGS/xash3d-fwgs#107]
On newer Android, external storage access can be really painful and not everyone knows where to put the resources. Why not just bundle the valve folder into apk, and make it playable out-of-box?

We can get a full copy of HLDS by SteamCMD without purchasing Half-Life. Just make a CI script to download them from valve and zip it.

**Comment by MoeMod** [comment]
Sample CI script from CSMoE:
```
    before_script:
      - git clone --recursive https://github.com/MoeMod/CSMoE-GameDir
      - git clone --recursive https://github.com/dgibbs64/HLDS-appmanifest
      - curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -o steamcmd.zip
      - unzip -o steamcmd.zip -d SteamCMD
    script:
      - mkdir -p CSMoE-Full/steamapps
      - cd SteamCMD
      - ./steamcmd.exe +login anonymous +force_install_dir ../CSMoE-Full +app_update 90 +app_set_config 90 mod cstrike validate +quit || echo "First attempt... (0x10E expected)"
      - cp -f ../HLDS-appmanifest/CounterStrike/*.acf ../CSMoE-Full/steamapps/
      - ./steamcmd.exe +login anonymous +force_install_dir ../CSMoE-Full +app_update 90 +app_set_config 90 mod cstrike validate +quit || echo "Second attempt...(success expected)"
      - rm -f ../CSMoE-Full/steamapps/*.acf
      - ./steamcmd.exe +login anonymous +force_install_dir ../CSMoE-Full +app_update 90 +app_set_config 90 mod cstrike validate +quit || echo "Third attempt..."
      - cd ..
      - cp -r CSMoE-GameDir/csmoe CSMoE-Full/
      #- zip -r CSMoE-CD-GameDir-Full.zip CSMoE-Full
      #- tar czvf CSMoE-CD-GameDir-Full.tar.gz CSMoE-Full
      - 7z a -t7z -r CSMoE-CD-GameDir-Full.7z CSMoE-Full
```

**Comment by a1batross** [comment]
... 

It's not legal, you know?

**Comment by a1batross** [comment]
Well, don't close it, @MoeMod, there is a way to workaround this and I planned to do so a long ago.

There is a project that reverse-engineering Steam network protocol. They've succeded to make their own steamcmd alternative. It's called SteamKit and DepotDownloader.

If you're familiar with dotnet and Android, you can bundle it and ask user for Steam credentials, downloading games into app directory.

**Comment by HowToDoThis** [comment]
> Well, don't close it, @MoeMod, there is a way to workaround this and I planned to do so a long ago.
> 
> There is a project that reverse-engineering Steam network protocol. They've succeded to make their own steamcmd alternative. It's called SteamKit and DepotDownloader.
> 
> If you're familiar with dotnet and Android, you can bundle it and ask user for Steam credentials, downloading games into app directory.

Is this method **legal way** to do it? If yes, I think we need to port DepotDownload to android platform.

**Comment by a1batross** [comment]
@HowToDoThis I don't think using reverse-engineered steam protocol is actually legal but at least it solves the problem with getting game files. Many gamers don't even have PC to download anything from Steam.

**Comment by HowToDoThis** [comment]
As your mention, maybe this is the only solution of downloading or getting resources from steam via their own account or anonymous account.

If we see @MoeMod scripts and according to [SteamDB](https://steamdb.info/app/90/subs/), I think that using anonymous account download Half-life dedicated server with cstrike are valid.

If ValveSoftware doesn't have any source code about SteamCMD or port to SteamCMD, the only way we want download in **"legal way"** only have port out from DepotDownload or SteamKit2.

Then, @MoeMod can done with this method.

**Comment by HowToDoThis** [comment]
Because as his main of the question, he wants to use a easier way to solve people that are new to people or asking without reading instructions.

But if we pack together, apk size became the problems.

**Comment by a1batross** [comment]
A long ago I've worked on OBB support for Paranoia game. I wanted to make it an example of Xash3D FWGS without Half-Life dependency. I didn't finished but I plan to release it someday. :)

Oh and yeah, HL content depot is accessible from anonymous access. I think Valve doesn't care. :)

**Comment by HowToDoThis** [comment]
> A long ago I've worked on OBB support for Paranoia game. I wanted to make it an example of Xash3D FWGS without Half-Life dependency. I didn't finished but I plan to release it someday. :)

Woah, good project.
> Oh and yeah, HL content depot is accessible from anonymous access. I think Valve doesn't care. :)

Yea prob.

**Comment by MoeMod** [comment]
Anyway, SteamCMD is just a console application... Can it run with x86 translators? Just like xashds

**Comment by mittorn** [comment]
It already was:
https://github.com/FWGS/xash3d-android-project/blob/master/unused/SteamService.java
https://github.com/FWGS/xash3d-android-project/blob/master/unused/SteamActivity.java
Try fix it with modern android selinux rules and actual steamcmd. I think, it is possible, but not easy. But it is very slow because steam uses compression and translator cannot handle it fast enough. Maybe try translator from box86 project, which may use native libraries? But running steamcmd is harder than just loading some x86 library.

**Comment by mittorn** [comment]
https://github.com/ptitSeb/box86

**Comment by nekonomicon** [comment]
I think It would be more easy to write and to integrate simple https-client with bearssl into engine to use steam api than use emulation or downloader written in C#.
