### ISSUE TITLE
cl_dlls/client_amd64.so not found - again

### ISSUE THREAD

**Issue by aznlir88** [FWGS/xash3d-fwgs#1070]
Reopening as still not solved I suppose. In original thread it was said that README file was updated according to this problem but there is no solution.

I built from source on Linux x64 machine, target CPU was also x64 so guess all options was correct. I built without problems and installed it to custom directory, copied valve dir contents from Steam version of the game.

Still getting this error.

ps. btw. why many issues are posted in Russian or similiar language? For people not to understand what they are all about? I assume in english more people would be able to find problems they have and not ask twice.

**Comment by a1batross** [comment]
You need to compile HLSDK as well because the game consists of two parts: the engine (that hosted here) and actual game code (that is HLSDK).

The README explicitly says about that:
>If your CPU is NOT x86 compatible or you decided build 64-bit version of engine, you may want to compile [Half-Life SDK](https://github.com/FWGS/hlsdk-xash3d). This repository contains our fork of HLSDK and restored source code for some of the mods. Not all of them, of course.

**Comment by a1batross** [comment]
>why many issues are posted in Russian?

That's a deliberate choice because Xash, and its community, originated from native Russian speakers. Unfortunately, not all of them know English language.
