### ISSUE TITLE
Прерывистый звук при воспроизведении voice_input.wav в голосовом чате

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1073]
Когда подключен к удалённому серверу (на локальном такой проблемы нет) и воспроизводишь звук с файла в голосовом чате при 60 фпс, слышен прерывистый звук.

Даже при 100 фпс есть проблемы с воспроизведением звука.

Звук идеально воспроизводится только когда у игрока 200 фпс.

При записи звука с микрофона такой проблемы нет.

**Comment by a1batross** [comment]
Я наблюдаю проблемы в 20 FPS, будто он не успевает отправить.

В 60 всё хорошо.

**Comment by Vladislav4KZ** [comment]
> Я наблюдаю проблемы в 20 FPS, будто он не успевает отправить.
> 
> В 60 всё хорошо.

А с sv_voicequality 5? На моём сервере выставлено максимальное качество для голосового чата, и там прерывистый звук даже при 60 фпс.

**Comment by Vladislav4KZ** [comment]
> Я наблюдаю проблемы в 20 FPS, будто он не успевает отправить.
> 
> В 60 всё хорошо.

С ``cl_updaterate 60`` лучше, но иногда всё же голосовой чат подлагивает.

Когда стоит ``cl_updaterate 102``, лаги в голосовом чате в 60 fps проявляются сильнее.

**Comment by a1batross** [comment]
Fixed in 305b2579
