### ISSUE TITLE
Нет курсора мыши в главном меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1074]
При запуске игры, курсор в главном меню виден.

А когда запустил/подключился к серверу и открыл меню, курсора нет.

**Comment by a1batross** [comment]
Должно быть исправлено.

И скорее всего будет ещё ворох багов, ибо вычистил кучу костылей с состоянием курсора мыши.

**Comment by Vladislav4KZ** [comment]
Да, теперь исправлено.
