### ISSUE TITLE
Getting this Xash Error when I run

### ISSUE THREAD

**Issue by LukaTV939** [FWGS/xash3d-fwgs#1076]
![image](https://user-images.githubusercontent.com/55237683/197386928-75fb5edd-678c-43b8-96d8-54b2144bded6.png)
I'm getting this error on both amd64 and i386 versions of the engine. I copied the original valve folder from cs warzone (which is ofc base half-life) and has extras.pk3 in it. I've searched for solutions, but they are all in Russian or not helpful and I'm also using the latest pre-release available in this repo.

**Comment by a1batross** [comment]
You need Steam version of the game, which has unencrypted binaries.

Also for them you better download i386 engine as Valve never released
64-bit ports.

вс, 23 окт. 2022 г., 13:32 LukaTV939 ***@***.***>:

**Comment by mittorn** [comment]
Is it some illegal dostributuon? You need to get half-life from Steam, old encrypted clients not supported

**Comment by Vladislav4KZ** [comment]
Counter-Strike 1.6 is not supported by Xash3D FWGS, since it uses VGUI2 interface.
