### ISSUE TITLE
Если активна карта-бэкграунд, то курсора нет.

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1077]
Билд движка 2757.

**Comment by a1batross** [comment]
Клиент с VGUI?

**Comment by Aynekko** [comment]
Без вгуи. Но проблема наблюдается на стим-халфе и прайме.

**Comment by Aynekko** [comment]
На билде 2705 проблемы нет.

**Comment by SNMetamorph** [comment]
> На билде 2705 проблемы нет.

@Aynekko какое значение квара `host_ver` на этом билде?

**Comment by Aynekko** [comment]
> @Aynekko какое значение квара `host_ver` на этом билде?
"host_ver" is "2705 0.20 win32 i386 f633b3d" ( "2705 0.20 win32 i386 f633b3d" )

**Comment by huigrunt** [comment]
На двигле 2714 тоже нет проблемм с курсором
"host_ver" is "2714 0.20 win32 i386 e6bb9d9" ( "2714 0.20 win32 i386 e6bb9d9" )

**Comment by Vladislav4KZ** [comment]
@Aynekko эта проблема ещё актуальна? У меня данный баг не воспроизводится на последнем билде движка на Windows 10.

**Comment by Aynekko** [comment]
> эта проблема ещё актуальна?

Нет. Закрываю.
