### ISSUE TITLE
Xash3D-FWGS (New Engine)(Android Version) about half life expansions and counter-strike

### ISSUE THREAD

**Issue by Cruzejer123** [FWGS/xash3d-fwgs#1078]
Half-Life on new engine Android version is fine but when it comes to expansions and Counter-Strike 1.6 the application crashes whatever it tries to load anything other than the original half life I try to do any version but it does not want to accept it and it always crashes when I try to load the expansions in Counter Strike please fix this in the future when you can thank you.

**Comment by Cruzejer123** [comment]
Plz read this.

**Comment by a1batross** [comment]
🤷🏽
