### ISSUE TITLE
crash whilst changing map on coop servers 

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1079]
everything i could get:
![image](https://user-images.githubusercontent.com/55242111/198072222-2f0bda29-d7f9-4060-ac1f-b1d2844b63b8.png)

**Comment by xWhitey** [comment]
![image](https://user-images.githubusercontent.com/55242111/198073228-f0a1d208-90db-48d2-8eb5-8de049e46a62.png)
it's crashing here
![image](https://user-images.githubusercontent.com/55242111/198073280-680f3c72-3c75-438f-b4e8-ae548511f238.png)
&(eax+0x2F0) is probably pointing to unmapped memory or just causes sigsegv (addresses after 0x7FFFFFFF) (perhaps xmm0 may be nullptr too)

**Comment by xWhitey** [comment]
btw sometimes it crashes after "Spooling demo header" otherwise it crashes instantly after "reconnecting..."

**Comment by xWhitey** [comment]
with pdbs: 
![image](https://user-images.githubusercontent.com/55242111/198078162-55871c6a-0f18-4ab6-b284-3a0faf6281ff.png)

**Comment by xWhitey** [comment]
the crash happens here: https://github.com/FWGS/xash3d-fwgs/blob/305b2579ebf36c91770925c3fc510294899da931/engine/client/cl_parse.c#L258

**Comment by xWhitey** [comment]
> This line doesn't look suspicious. 🤔
> 
> The line above that could be, we have few bugs where clgame.entities can be NULL.

Maybe host doesn't share features field sometimes? Perhaps I saw host couldn't share server name & players' score, so server name was just blank (even not "empty") and players did not have score. (This happens really often btw, i can record it if you're interested.)

**Comment by a1batross** [comment]
That shouldn't happen either.

`host.features` is just an integer field, I doubt copying it can lead to
crash. Except if `&host` got overwritten somehow.

чт, 27 окт. 2022 г., 01:45 static final ***@***.***>:

**Comment by xWhitey** [comment]
Even if oldmovevars line is commented, the game still crashes.
![image](https://user-images.githubusercontent.com/55242111/198873178-88ec8237-4b0d-4b4d-ad4c-917a118d04a4.png)
![image](https://user-images.githubusercontent.com/55242111/198873187-8ff567cb-3ad2-4306-ac0f-e4be3cf3d25f.png)
But now it says that the crash is on 259 line. (funni?) 
![image](https://user-images.githubusercontent.com/55242111/198873201-142e8bb6-ee70-4e92-96d3-a20bef971246.png)
btw it's still movss shit
6B85CD2B  movss       dword ptr [eax+2F0h],xmm0

**Comment by xWhitey** [comment]
uh oh i forgot to show FPU
this is message from crash handler: 
![image](https://user-images.githubusercontent.com/55242111/198873235-61c9b55f-28ab-4fc5-a8db-b79fe9477dd0.png)

**Comment by xWhitey** [comment]
FPU: 
![image](https://user-images.githubusercontent.com/55242111/198873416-8453b9ba-21e3-47f3-882c-7769955c9dd6.png)

**Comment by xWhitey** [comment]
The only working way I found is just by replacing movss to nop's.
Seems like compiler fault.
![image](https://user-images.githubusercontent.com/55242111/198875598-8c453bc1-cd4c-4984-bc35-089687b4b5a9.png)

**Comment by a1batross** [comment]
Probably fixed in 4cf87c2c235d8082ae0452abb64f9ac0b08d4343
