### ISSUE TITLE
Inability to build xash using waf.

### ISSUE THREAD

**Issue by xWhitey** [FWGS/xash3d-fwgs#1082]
Upon I run "py -x waf configure --enable-static-binary --single-binary --enable-lto --enable-poly-opt --enable-utils --enable-all-renderers --disable-werror -T debug --sdl2=C:\SDL2-2.24.1 --skip-sdl2-sanity-check" it fails with 
`['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\CL.exe', '/Fd:C:\\Users\\xWhitey\\Desktop\\xash3d-fwgs\\build\\conf_check_045246ad0357e076430542805789cb8d\\testbuild\\test.cpp.1.pdb', '/nologo', '/nologo', '/D_USING_V110_SDK71_', '/Zc:threadSafeInit-', '/MT', '/Zc:__cplusplus', '/Od', '/ZI', '/GL', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\ATLMFC\\include', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\include', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\ucrt', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\shared', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\um', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\winrt', '/I..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\cppwinrt', '/I..\\..\\..\\3rdparty\\vgui_support\\vgui-dev\\include', '/DSTDINT_H="pstdint.h"', '/DXASH_GAMEDIR="valve"', '/DXASH_BUILD_COMMIT="c1ca2c1"', '/DXASH_LOW_MEMORY=0', '..\\test.cpp', '/FC', '/c', '/FoC:\\Users\\xWhitey\\Desktop\\xash3d-fwgs\\build\\conf_check_045246ad0357e076430542805789cb8d\\testbuild\\test.cpp.1.o']
err: cl : Command line error D8016 : '/ZI' and '/GL' command-line options are incompatible
`

**Comment by xWhitey** [comment]
![image](https://user-images.githubusercontent.com/55242111/198843393-d20118aa-53a9-41e7-a03a-25ca779e1eec.png)

**Comment by xWhitey** [comment]
-T debug is the reason of this shit. -T release is fix

**Comment by a1batross** [comment]
Why do you want so many options enabled? Link Time Optimization and debug mode is incompatible.

**Comment by xWhitey** [comment]
I was just playing with your build system.
TBH I just added "append" command that does Cbuf_AddText and nothing more.

**Comment by a1batross** [comment]
@xWhitey oh, good hacking then! :)

**Comment by xWhitey** [comment]
thank you!
