### ISSUE TITLE
Beams are pointing into the sky

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1083]
![image](https://user-images.githubusercontent.com/55242111/198884722-bf653cdb-7b5c-4eab-b79a-527ba8753293.png)(any TDM server has this bug on crossfire map, whilst old engine and Nov 2021 commit engine doesn't act like this.)

**Comment by Vladislav4KZ** [comment]
Про этот баг уже писали: https://github.com/FWGS/xash3d-fwgs/issues/832

**Comment by a1batross** [comment]
Fixed in 76d0608e
