### ISSUE TITLE
Unable to join any server after exiting singleplayer.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1085]
3777 0008 svc_time
3777 0013 svc_clientdata
3777 0016 svc_deltapacketentities
3778 0008 svc_time
3778 0013 svc_clientdata
3778 0016 svc_deltapacketentities
3779 0008 svc_time
3779 0013 svc_clientdata
3779 0016 svc_deltapacketentities
3780 0008 svc_time
3780 0013 svc_clientdata
3780 0016 svc_deltapacketentities
3781 0008 svc_time
3781 0013 svc_clientdata
3781 0016 svc_deltapacketentities
3782 0008 svc_time
3782 0013 svc_clientdata
3782 0016 svc_deltapacketentities
3783 0008 svc_time
3783 0013 svc_clientdata
3783 0016 svc_deltapacketentities
3784 0008 svc_time
3784 0013 svc_clientdata
3784 0016 svc_deltapacketentities
3785 0008 svc_time
3785 0013 svc_clientdata
3785 0016 svc_deltapacketentities
3786 0008 svc_time
3786 0013 svc_clientdata
3786 0016 svc_deltapacketentities
3787 0008 svc_changing
BAD:   70:svc_serverdata
Host_Error: CL_EDICT_NUM: clgame.entities is NULL
Server was killed

**Comment by Vladislav4KZ** [comment]
Не воспроизводится у меня на Windows 10.

Да и ещё автор этой issue удалил свой аккаунт, так что подробностей или новостей по поводу этого мы не узнаем.
