### ISSUE TITLE
Reason for removing CMake build support

### ISSUE THREAD

**Issue by Troll338cz** [FWGS/xash3d-fwgs#109]
May i ask what is reason for removing CMake support in release v0.20?

**Comment by nekonomicon** [comment]
1. cmake too buggy and too complex.
2. some windows programmers has troubles with cmake. They didn't undestand how to use this build system with MSVC.
3. waf is more stable and flexible(but required knowledge of python)

**Comment by nekonomicon** [comment]
https://github.com/FWGS/hlsdk-xash3d/issues/105

**Comment by Troll338cz** [comment]
Ok i understand and thank you for response.
