### ISSUE TITLE
VGUI интерфейс отрисовывается не полностью 

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1104]
![SS_HQ_f3_0000.png](https://user-images.githubusercontent.com/22411953/201616467-daa7bcb3-5967-4829-8e01-451ce7935434.png)![SS_HQ_f3_0001.png](https://user-images.githubusercontent.com/22411953/201616579-4340871e-9ef7-4b9d-acb6-db64c8f409bb.png)

Как видно на скриншотах, нижняя часть VGUI окон не дорисована.

Баг появился в последних билдах ксаша.

**Comment by SNMetamorph** [comment]
Подтверждаю
![изображение](https://user-images.githubusercontent.com/25657591/201747652-f8713114-84ad-4738-a692-4381254b75db.png)

**Comment by a1batross** [comment]
Fixed in a894ca60c603881f6e1b61f02d6d8ec82ef24e8f
