### ISSUE TITLE
muzzle flash bug and player model shuttering 

### ISSUE THREAD

**Issue by Yoshimitsu021** [FWGS/xash3d-fwgs#1109]
When i shoot shoot auto there's a muzzle flash bug appear when i stop shooting this bug rarely appeared it's annoying please fix it, and the player model shuttering/flickering when they are walking this is annoying too, and some command is not working well like corpstay 600 is not working, and gunsmoke only in ak 47 works, please fix this bugs it's annoying i want to experience playing cs1.6 on Android like on pc, thank you

**Comment by a1batross** [comment]
New engine fixed that bug. Wait for update.

**Comment by Yoshimitsu021** [comment]
Xash old engine you mean?

**Comment by Yoshimitsu021** [comment]
Also fix map slow loading on android 11 to 12, it takes 2 to 3 minutes to load maps 😭

**Comment by a1batross** [comment]
It's not possible to fix completely.
