### ISSUE TITLE
Map slow loading on android 11 to android 12 

### ISSUE THREAD

**Issue by Yoshimitsu021** [FWGS/xash3d-fwgs#1110]
It takes 2 to 3 minutes to load maps in cs 1.6 android but i use my phone android 10 it takes 3 to 4 seconds, please fix this issue, thank you

**Comment by Vladislav4KZ** [comment]
Did you even try the New Engine from Play Store?

Perhaps there this problem is fixed, since the game files are installed in the Android/data/su.xash.engine folder for New Engine (Xash3D FWGS 0.21)

**Comment by Yoshimitsu021** [comment]
No, i mean the old engine that can run cs16 and cscz

**Comment by Yoshimitsu021** [comment]
Maybe you didn't pay attention to the old engine that's why you don't notice that there are many bugs

**Comment by TheKingFireS** [comment]
that's why it's called old engine

**Comment by Yoshimitsu021** [comment]
does the new engine only support halflife? or there will be cs1.6/cscz soon?

**Comment by TheKingFireS** [comment]
if you talking about google play version, yes only half-life
mod supports is broken

**Comment by Yoshimitsu021** [comment]
> that's why it's called old engine

Yeah and old engine is better, but there's a lot of bugs and also more optimize

**Comment by TheKingFireS** [comment]
and github version, only supported mods that's used vanilla half-life library

**Comment by Yoshimitsu021** [comment]
> if you talking about google play version, yes only half-life mod supports is broken

How about cs1.6/cscz?

**Comment by TheKingFireS** [comment]
also cs16/cscz required launcher

**Comment by TheKingFireS** [comment]
not integrated in engine

**Comment by Yoshimitsu021** [comment]
> again? they told you it's not supported

I mean will they have a plan to support cs1.6/cscz soon?

**Comment by TheKingFireS** [comment]
In future. no ETA

**Comment by Yoshimitsu021** [comment]
> also cs16/cscz required launcher

Yeah I know, I'm only asking if you still have plans to update or fix the bugs in the old engine

**Comment by Yoshimitsu021** [comment]
> In future. no ETA

I'm hoping

**Comment by TheKingFireS** [comment]
> > also cs16/cscz required launcher
> 
> Yeah I know, I'm only asking if you still have plans to update or fix the bugs in the old engine

i am not developper of cs16/cscz, i am just normal guy

**Comment by Yoshimitsu021** [comment]
Ohh fvck i thought you are the moderator, sorry man

**Comment by TheKingFireS** [comment]
don't worry

**Comment by Vladislav4KZ** [comment]
> Yeah and old engine is better, but there's a lot of bugs and also more optimize

The old engine is not better than the new engine. Comparing them on a PC with Windows, the new engine works better, supports more mods and has new features. Old bugs are fixed, but new ones may appear.

Most of the problems are related to Android version of the new engine, but recently they began to redo it, and at least a couple of bugs were eliminated.

**Comment by Yoshimitsu021** [comment]
> > Yeah and old engine is better, but there's a lot of bugs and also more optimize
> 
> The old engine is not better than the new engine. Comparing them on a PC with Windows, the new engine works better, supports more mods and has new features. Old bugs are fixed, but new ones may appear.
> 
> Most of the problems are related to Android version of the new engine, but recently they began to redo it, and at least a couple of bugs were eliminated.

How about cs1.6/cscz it is included?

**Comment by Vladislav4KZ** [comment]
> How about cs1.6/cscz it is included?

Counter-Strike 1.6 and Condition Zero doesn't work even on Old Engine for PC due requirement of VGUI2 for rendering the in-game interface.


I'm also not developer of Xash3D FWGS, I'm just tester and I say that I myself experienced.

**Comment by Vladislav4KZ** [comment]
CS16Client was officially released only for Android and is currently only supported by the old engine.

**Comment by Yoshimitsu021** [comment]
Ohh sad to know that
