### ISSUE TITLE
Нельзя выбрать декаль pldecal из spraypaint.wad

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#1120]
spraypaint.wad содержит декаль c названием PLDECAL.BMP, но в игре в меню multiplayer->customize ee выбрать нельзя.
Содержимое spraypaint.wad:
```
  8BALL1.bmp
  ANDRE.bmp
  CAMP1.bmp
  CHICK1.bmp
  CHUCKSKULL.bmp
  DEVL1.bmp
  GUN1.bmp
  LAMBDA.bmp
  PLDECAL.bmp
  SKULL.bmp
  SMILEY.bmp
  SPLATT.bmp
  TIKI.bmp
  V_1.bmp
```

Этой проблеме подвержен и GoldSource: https://github.com/ValveSoftware/halflife/issues/925

**Comment by unnamed9** [comment]
Это потому что такой декали нету в папке logos, а именно оттуда грузит спреи Steam версия халфы и Ксаш.
Спреи из spraypaint.wad грузит только WON версия халфы.
Исправлять эту декаль так.
https://github.com/ValveSoftware/halflife/issues/925#issuecomment-15863577

**Comment by Vladislav4KZ** [comment]
@unnamed9 какая именно версия WON? Я проверил Half-Life WON 1.0.1.6 и 1.1.1.0 там такого лого не было.

И в тех версиях лого лежат не в папке valve/logos, а в папке logos которая лежит в корневой папке игры.

**Comment by Vladislav4KZ** [comment]
Тоже самое и в Half-Life 1.0, самая первая версия от 1 ноября 1998 года.

Лого лежат в папке logos которая в корневой папке игры. А spraypaint.wad видимо так никогда и не использовался.

PLDECAL нету в папке logos, и в игре его невозможно выбрать.

**Comment by Vladislav4KZ** [comment]
Ошибся с датой, дата изменения файлов игры варьируется от 30 октября и 3 ноября, а сама игра вышла 19 ноября.

**Comment by nekonomicon** [comment]
В таком случае, возможно может быть полезно расширить функционал добавив чтение содержимого spraypaint.wad

**Comment by a1batross** [comment]
Не вижу смысла вообще этим заниматься. В wad паковать никто ничего не будет, а про то что папка logos используется для собственно выбора этих декалей все знают.
