### ISSUE TITLE
Добавить поддержку новых форматов для пользовательских спреев

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1127]
- [x] PNG
- [ ] GIF (по возможности)

**Comment by nekonomicon** [comment]
> GIF (по возможности)

Лучше APNG тогда.

**Comment by a1batross** [comment]
Вот анимированные добавлять не сильно много желания. Очень легко это
абьюзить, в Source это буквально к порнографии приводило.

сб, 26 нояб. 2022 г., 10:57 nekonomicon ***@***.***>:

**Comment by nekonomicon** [comment]
Пару лет назад ты был другого мнения вроде.
А так может для анимированных картинок в самом меню пригодится.

**Comment by SNMetamorph** [comment]
> Вот анимированные добавлять не сильно много желания. Очень легко это абьюзить, в Source это буквально к порнографии приводило
Я думаю, для таких случаев можно просто сделать клиентский квар на отключение воспроизведение анимации у спреев, или же серверный квар на запрет анимированных спреев.

**Comment by Velaron** [comment]
Не думаю что особо большая разница вылезет ли порнография на спрее сразу, иди чуть с задержкой)

**Comment by a1batross** [comment]
PNG is supported now.
