### ISSUE TITLE
blu shift map : ba_maint has "very dark zone"

### ISSUE THREAD

**Issue by sixcentgeorge** [FWGS/xash3d-fwgs#113]
the map has some very dark zones that looks cuted from the map in the very dark area in the middle of the map : i mean like some hole  while previous release render it well .
bug is in the 2.0 release 
![ba_maint_001 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/72243783-12f83880-35ed-11ea-9188-614a7a191315.jpg)
![ba_maint_002 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/72243784-1390cf00-35ed-11ea-8d75-6de057645ba3.jpg)
![ba_maint_000 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/72243785-14296580-35ed-11ea-957b-b3e960d52c36.jpg)
first image is made with 0.9 that shows well the place

**Comment by a1batross** [comment]
VBO is not recommended to use, and it was disabled by default.
