### ISSUE TITLE
Игра падает после смены спрея на 24/32-битный BMP при выходе из меню настроек

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1130]
Такое ощущение будто оно где-то пишет мусор в память, и при выходе из меню это взрывается

**Comment by a1batross** [comment]
У меня всё в порядке.

**Comment by SNMetamorph** [comment]
> У меня всё в порядке.

Попробуй вот с этим файлом
https://disk.yandex.ru/i/jC2bqV7O5akyZg

**Comment by SNMetamorph** [comment]
У меня зависло сразу же как только я нажал Done в меню

**Comment by SNMetamorph** [comment]
Я нашёл в чем причина бага, и исправил
![изображение](https://user-images.githubusercontent.com/25657591/204977296-3aca6a3f-aee7-474a-9a89-d09d12dba3da.png)

**Comment by SNMetamorph** [comment]
Разобрался в чём была проблема. Внутри функции `CBMP::LoadFile` происходит копирование файла в буфер, размер которого меньше размера самого файла (это происходит, если в целевом BMP файле заголовок новой версии). Пофиксил это я следующим образом.
Нужно добавить в класс `CBMP` конструктор:
```
CBMP( void *bufferAddr, int bufferSize )
{
        data = new byte[bufferSize];
        memcpy( data, bufferAddr, bufferSize );
}
```
Затем, в `CBMP::LoadFile` сделать такую правку:
![изображение](https://user-images.githubusercontent.com/25657591/204982660-5d10867d-b10d-4444-94ac-406796c396be.png)

**Comment by a1batross** [comment]
Fixed
