### ISSUE TITLE
sys_timescale позволяет ускоряться в мультиплеере

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1131]
Этот квар можно использовать как спидхак.
При повышении значения которого, игрок может носиться со скоростью света.

**Comment by a1batross** [comment]
Ну как бы :D

**Comment by unnamed9** [comment]
Кажется, проблема более серьёзная, чем кажется.
Ибо при -dev 1 и выше я могу менять состояние любых cheat protected кваров в мультиплеере, даже, например, r_drawentities.
Причём баг тянется со старого Ксаша, ибо такими методами пользовались некоторые читеры со старого Ксаша.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/d9a245dcb55c082e75117362878e25d7ba2b7ef5
