### ISSUE TITLE
What is Host_Error: Mod_FindModelOrigin: EOF Without Closing Brace and Others Like It?

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#1133]
In my attempts to cross over NPCs into Typical Disaster and making them hostile, I copied the "MyClass 4" attribute and pasted it into one of the monstermaker entities that will spawn an NA Slave, but once I tried that, the game will boot me out of the level with an error saying "Host_Error: Mod_FindModelOrigin: EOF Without Closing Brace."

I was basically using New BSPGuy by Unreal in order to achieve what I am doing, for some reason it doesn't work unless I remove MyClass 4, which I really don't want to do because I need to make the NA Slave evil. I know for a fact that this MyClass 4 attribute had worked with the NA Agent, but it doesn't even work here. I need some help, and is there a way to prevent and remedy this issue?

**Comment by a1batross** [comment]
Errors like this means there is a syntax error in entities lump inside of a map.

**Comment by ToxicHolyGrenade** [comment]
[Part 1.zip](https://github.com/FWGS/xash3d-fwgs/files/10142408/Part.1.zip)
[Part 2.zip](https://github.com/FWGS/xash3d-fwgs/files/10142410/Part.2.zip)
[Part 3.zip](https://github.com/FWGS/xash3d-fwgs/files/10142412/Part.3.zip)

**Comment by a1batross** [comment]
You could just post BSP file

**Comment by ToxicHolyGrenade** [comment]
I pasted the part ZIP files just to emulate what I am experiencing, but I can also provide the BSP maps for you.

**Comment by ToxicHolyGrenade** [comment]
[Maps.zip](https://github.com/FWGS/xash3d-fwgs/files/10142428/Maps.zip)

**Comment by ToxicHolyGrenade** [comment]
@a1batross So, what do you think?

**Comment by a1batross** [comment]
It looks like there is an entity "monster_na_slave" with key "MyClass" but the problem is that at the end of the key, there is a NULL terminator (basically "MyClass\0", which then makes entities list parser think that it's where EOF is.

It's probably a bug of newbspguy if it allows pasting such data or inserts it with a bug.

**Comment by UnrealKaraulov** [comment]
@a1batross @ToxicHolyGrenade yes this issue is emitted by new imgui(imgui cpp wrapped added null bytes to std::string) it fixed in latest releases. Извеняйте за проблемку:)
