### ISSUE TITLE
Incorrect fade color.

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/xash3d-fwgs#1134]
Xash3D FWGS Windows i386 2808 commits 9fa4de6:
![image](https://user-images.githubusercontent.com/71936968/205398588-8c8dd385-21d8-471c-b5ea-814d5d44bff4.png)

Steam Goldsrc: This is supposed to be corrected fade color.
![image](https://user-images.githubusercontent.com/71936968/205398605-04090a7c-2948-4dc4-b918-b8c092d0d65a.png)

map link:
https://twhl.info/vault/view/6681

here engine.log if you need:
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/10144721/engine.log)

**Comment by a1batross** [comment]
I want to get this fixed just because I don't like how this map looks currently. Like a piss.

**Comment by a1batross** [comment]
Fixed in a4865fd2
