### ISSUE TITLE
Please fix the Android build

### ISSUE THREAD

**Issue by stephen-cusi** [FWGS/xash3d-fwgs#1136]

**Comment by TheKingFireS** [comment]
A1batross will not because of https://github.com/FWGS/xash3d-fwgs/issues/1112

**Comment by stephen-cusi** [comment]
> A1batross 不会因为#1112

　　 　 　　　　 　 |＼＿/| 
　　 　 　　　　 　 | ・x・ | 
　　 ＼＿＿＿＿＿／　　　 |
　　 　 |　　　 　　　　　| 
　　　　＼　　　　　  　ノ　 
　（（（　(/￣￣￣￣(/ヽ)

**Comment by Srandista** [comment]
@stephen-cusi you can find slightly older Android release here:
https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous-internal_vgui_support_rework
