### ISSUE TITLE
No Underwater Distortion control

### ISSUE THREAD

**Issue by Flintastic** [FWGS/xash3d-fwgs#1138]
The **r_underwater_distortion** cvar from the original Xash3D (edit: "Old Engine" FWGS) is missing. The effect cannot be adjusted or disabled (for vanilla look) in "New Engine" FWGS.

**Comment by unnamed9** [comment]
This cvar is not even in the original Xash.
![image](https://user-images.githubusercontent.com/96422615/205489761-877f4f73-a1a6-475d-a0c9-4e5c3f4dce46.png)

**Comment by Architector4** [comment]
I don't know about the cvar in the original Xash, but I support having an option to disable it.

**Comment by Flintastic** [comment]
It's in the source of the original Xash3D: 

https://github.com/FWGS/xash3d/blob/master/engine/client/vid_common.c?plain=1#L873

https://github.com/FWGS/xash3d/blob/master/engine/client/gl_rmain.c?plain=1#L840

Interestingly, it's also mentioned in the release notes for FWGS 0.19.1.

![image](https://user-images.githubusercontent.com/66497936/205491430-aa1dab78-64bc-4455-a303-a9ca923d66d0.png)

**Comment by a1batross** [comment]
@Flintastic sorry for confusion, this repo isn't the "original" Xash3D, it was just named that way. It's our fork too, but we usually refer to this code base as "old engine".

As of feature request, I think it's better to disable distortion in normal mode and enable back for Quake-compatible, than have yet another undocumented cvar.

**Comment by Flintastic** [comment]
No worries. Sounds good.

**Comment by Flintastic** [comment]
Thanks!
