### ISSUE TITLE
Mouse stops for a split second if moved too fast

### ISSUE THREAD

**Issue by The-Nate** [FWGS/xash3d-fwgs#114]
I'm using the current stable build from December 2nd (because I can't compile for jack, honestly) and there's this very annoying bug in which mouse movement stops for a split second if I move my mouse too fast. Here's a video:

https://streamable.com/zdnp9

I am using this mouse:

https://www.amazon.com/PICTEK-Programmable-Breathing-Ergonomic-Computer/dp/B01FZ3BR5S/ref=sr_1_5?keywords=easterntimes+tech+mouse&qid=1570564079&s=electronics&sr=1-5

I have tried changing resolutions, changing to windowed, enabling m_enginemouse, changing m_enginemouse's sensitivity, enabling and disabling mouse smoothing, and enabling and disabling vsync.

**Comment by wirke** [comment]
Similar problem

**Comment by a1batross** [comment]
Nobody can reproduce it. No info was given whatsoever. Closing, maybe it got magically fixed with #470 too? :)
