### ISSUE TITLE
[MOD: Crack-Life: Campaign Mode] В тренировочном курсе, инструктор Шарп не произносит свою первую фразу

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1142]
В консоли появляется такая ошибка
```
Error: SV_StartSound: !0 not precached (0)
```

Следом за ней пишется
```
Playing sentence !DR_DRILL1 (6.0)
```
DR_DRILL1 это и есть самая первая строка в sentences.txt, указывающая путь к звуковому файлу с фразой которая не воспроизводится из-за ошибки указанной выше.

**Comment by Vladislav4KZ** [comment]
Да, дело именно в первой строке из sentences.txt

Для проверки я переместил строку HOLO_INTRO на первое место в sentences.txt из Half-Life, и голограмма тоже перестала проговаривать свою первую фразу из-за такой же ошибки.

**Comment by a1batross** [comment]
Fixed in cd813bbf
