### ISSUE TITLE
sv_cheats 1 + god = bug in health

### ISSUE THREAD

**Issue by sixcentgeorge** [FWGS/xash3d-fwgs#115]
when i was playing blu-shift , i was very low at heath so for not dying i turned on god mod..
then i used a health recharger and saw my health was not increasing...so i disabled god and health was getting points.. i saw it happens also with health pack..
last thing , that happened to me while playing some blu-shift maps [ i think coming from a won cdrom ] ; i also was able to see that the scientist that is dying in a office and talk about rosenberg to barney.. ; changes at end of demo when he dies.. the scientist looks like not hd model..
![ba_yard3a_0000 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/73076575-acadc880-3ebe-11ea-8b10-844080267fad.jpg)
![ba_yard3_0000 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/73076577-addef580-3ebe-11ea-8fb6-e90562d8185b.jpg)
![ba_yard3_0001 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/73076581-addef580-3ebe-11ea-8b1b-5b875ead0158.jpg)
![ba_yard3_0002 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/73076582-af102280-3ebe-11ea-8d91-417c7a84d638.jpg)
![ba_yard3_0003 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/73076586-b0414f80-3ebe-11ea-95bc-875bd63c6c6a.jpg)

**Comment by nekonomicon** [comment]
>i also was able to see that the scientist that is dying in a office and talk about rosenberg to barney.. ; changes at end of demo when he dies.. the scientist looks like not hd model..

Why do you use Opposing force libraries and models with Blue Shift maps?

Do you know about difference into scientists models between Opposing Force and Blue Shift?

It has different skin count.

**Comment by sixcentgeorge** [comment]
i am making a new mod that use a lot of maps from different mods..it is an half-life extended..story ;']..
i use opposing force because it has a lot of models : friendly or not.. plus the dll is very well programmed.. for the models .. i had not much troubles with milkshape and using those made from the hd pack ..
i edit the qc files and care about the smds.. there are not so much "animations" because they are very hard to create without expensive tools and hardware..
i like a lot xash3d that has a cool spawning system.. [ that i would like to see in some coop hl2 mods... ] if the maps have no info landmarks then it use the info_start place..but it does not transfer health and weapons.. . i am making some test to and edit of map entities to have all maps playable then i will create a page at moddb : when i ll be sure to be able to finish the mod.. do you want to help ? may be you can join me.. i do this one for hl & i expect it will have a lot of fans..i hope to port it to hl2 or 3..

**Comment by nekonomicon** [comment]
Look at code:
https://github.com/FWGS/hlsdk-xash3d/blob/master/dlls/scientist.cpp#L613

HL&BS scientist models has 4 head skins:
https://github.com/FWGS/hlsdk-xash3d/blob/master/dlls/scientist.cpp#L30

But OF scientist models has 6 head skins:
https://github.com/FWGS/hlsdk-xash3d/blob/opfor/dlls/scientist.h#L20

And such trouble is possible if your scientist model has wrong head skins count:
>also was able to see that the scientist that is dying in a office and talk about rosenberg to barney.. ; changes at end of demo when he dies.. the scientist looks like not hd model..

**Comment by sixcentgeorge** [comment]
i like you a lot Nekonomicon ..and i did also some mods port : with azure and they hunger : https://steamcommunity.com/app/225840/discussions/0/2803982773098842396/
then this : https://www.moddb.com/mods/sven-co-op
check my two mods.. plus the coming one : https://hl2-beta.ru/index.php?topic=28890.msg32883#msg32883
i would like you to help me by programming the dll of the mod.. i want something "simple" with most of the monsters from opposing force , plus some from sweet half-life.. i want player to be gordon freeman or an alien like in pov.. [ of course i agree removing weapons.. and others things.. ] 
i think you mean this part of the qc file :  
$bodygroup "heads"
{
studio "dc_sci_(head_NERD)"
studio "dc_sci_(head_EINSTEIN)"
studio "dc_sci_(head_LUTHER)"
studio "dc_sci_(head_ROSENBERG)"
studio "SCI_clipboard"
studio "SCI_stick"
studio "dc_sci_(head_SLICK)"
}
that i can select if i use the parameter : body
like this : 
"body" "3"
//"classname" "monster_rosenberg"
"classname" "monster_scientist"
or like this 

//"model" "models/scientist.mdl"
//"classname" "monster_generic"
"classname" "monster_scientist"

monster_rosenberg exist in blue-shift and decay.. but is mostly doing scripted action..
as in blue shift or decay : it uses the scientific model with head 3 .. i moved the head..
studio "SCI_stick" is the scientific playing with a woodstick and a headcrab in of1a1..

reediting the smd and adding them in others models [ like the hd ] is not always perfect because they are differents in shape.. so models low definition are working while new in hd are not "always" .. i think i was the first to make a mod : opposing life2life ; with low def and high def models [ beside the blue-shift /opposing force / valve hd models pack . ] 
i hope to have time to create the two folders system for low def and high def models /sound/sprite..
may be with two others new one : maps_sp and maps_coop : so my two already made mods plus the latest become one mod..with singleplayer and coop multiplayer...  
i tested using old hlmv and also this new one that re-use its code : https://github.com/SamVanheer/HL_Tools
 & bugs .. : https://github.com/SamVanheer/HL_Tools/issues
this tools also has bad rendering of the models..when i change the animation the display shows only one quarter of the screen , the rest is not updated..[ i have to make a video of the desktop to show it clearly.. it is on my todo things.. and as this programmer seems to have gone .. it is not at top...]
one of the best model rendering i saw , updated recently : https://richwhitehouse.com/index.php?content=inc_projects.php&showproject=91 ..[ problem is that is shows all anims.. without choice.. good for testing models ..][he is an old pro ..]
so i repeat i ll be happy to see if wee can work together on your or mine projects ..i have a lot of free time : like you i search well paid jobs ;'] i also dream of visiting russia from st petersburg to vladivostok..and china plus korea and japan.. ["8

**Comment by sixcentgeorge** [comment]
i found playing xen that if i stay in the water that increases health power of the player and turn off god mode at the console , then the health of player makes a jump like from 5 to 70 and then get to 100 one by one ..
i am still searching someone able to program the dlls of my mod.. : i need something simple a la opposing force with sweet half-life monsters .. of course may be few others thing that could have a great impact or some of your ideas...  try to reply any time soon..thank you

**Comment by nekonomicon** [comment]
>i found playing xen that if i stay in the water that increases health power of the player and turn off god mode at the console , then the health of player makes a jump like from 5 to 70 and then get to 100 one by one

Create one issue per bug

>i am still searching someone able to program the dlls of my mod..

It's not modding/programming forum.

**Comment by sixcentgeorge** [comment]
i read you wrote a dll for your opposing force...with another guy : maillortie.. with some sources codes here.. i help you to spot bugs and give ideas .. at hlfx.ru forum .. so you can think of giving back ..  may be you ll be rewarded for that work sooner or later..? ??

**Comment by nekonomicon** [comment]
>i read you wrote a dll for your opposing force...with another guy : maillortie.. with some sources codes here..

You didn't right. Originally It was written by lostgamer with some code parts from unfinished mod "Raven City", Spirit of Half-Life V1.9 - Opposing-Force Edition, HL:Enhanced and mallortie's recreation.
Currently, we have clean branch with some FreeSlave's work. And FreeSlave currently working on own mod "Soldier Adventure" with opposing force entities and helping us.

Anyway you can make with source code from github what you wish, but we can't help you with your mod.

**Comment by The1Freeman** [comment]
> i read you wrote a dll for your opposing force...with another guy : maillortie.. with some sources codes here.. i help you to spot bugs and give ideas .. at hlfx.ru forum .. so you can think of giving back .. may be you ll be rewarded for that work sooner or later..? ??

I'm not one to comment on issues this often (especially as this derails the original issue to begin with), but this really sounds like a case of "choosing beggers" to me.

Why not, instead of trying to suck off from the developers of Xash3D, who are already putting so many hours into improving the engine as much as they can, attempt to learn C++ yourself, read docs and study the code?
> so you can think of giving back, maybe you'll be rewarded for that work sooner or later???
And comments like these just show what kind of person you really are.

**Comment by sixcentgeorge** [comment]
i do not know.. but by now .. after few hours of using.. i found a lot of bugs.. 
it is like for my dlls.. i am not a programmer but i have good ideas "easy to reuse" by programmers...
without being here or in some forum begging for my "forgotten" credits...
i was more thinking that programing some dlls of a twenty years old game ... is a real easy job.. and not some : "cia jobs" where some nuclear weapons have to be handled and destroyed without anybody knowing that was it : the cia.. like with the 11/09/2001 day..
so i hope you ll give me a friend email that can do it for me.. i can give the amount valve asks at steamwork : $100 for that job .. and a little more if i get the hl2 files working with hls..

https://steamcommunity.com/app/70/tradingforum/1744518386135231173/

**Comment by The1Freeman** [comment]
Congratulations, you missed the point @nekonomicon and I have been talking about, good job on that part!
This really is no modding forum or something of the sort, please ~~beg~~ ask somewhere else.

**Comment by sixcentgeorge** [comment]
why are you here "free-woman wanting dick in her ass" .. this a bug i reported .. i can ask for help.. things are not working "in one way only"...or i ll be no longer reporting bugs but begging like sheep : my credits.. my credits...

**Comment by a1batross** [comment]
we... need... more... three... dots...

**Comment by nekonomicon** [comment]
>this a bug i reported .. i can ask for help.. things are not working "in one way only"

In OpenSource community nobody owes you anything.
And if you are user of some software - It's a normal to report bugs to vendor of this software.
If you found a bug you have a choice - to report bug to vendor or to fix bug by yourself.

**Comment by sixcentgeorge** [comment]
i wonder how you understand "open source" i think you really miss the point to its "opposite" 
i can proove it [ Again.. hi Mr XaeroX]
you wrote above mine : you are a user ...report bugs to the VENDOR ..VENDOR..
and it is funny you find it "normal" .. 
i think the open source laws like the gpl .. start applying to those who use the code to make software..
the user of softwares made using it are not aware of what is the code or bugs.. for them software works or is too buggy..  your "way" of thinking looks like the one of nvidia or google or M$ or Apple.. all of them makes billions of profits using free code.. and they never give a $ to the open source community..  it is a way of thinking and doing..  you can code whatever you want.. if you have no maps to play nor mods with models.. your works mean nothing..  if you want to make money with contracts [ that is normal for me ] you still need to be known and had made good products before..  not every body is john carmack or gabe newel .. they made games that sold millions of copies and are billionnaires like the one that made minecraft..  ..i think my project is a rocket to get in this space full of money and i try to find the right partners..i am even ready to give / share a little amount of money : if that can help ..  first i test if i can be "friend with eyes closed" ... and i do nothing to "force" people working / teaming with me.. so make up your mind Nekonomicon .. i have so much things to do..

**Comment by a1batross** [comment]
Ok, this nonsense was very fun to read, thanks sixcentgeorge.

Restricting to collaborators only.
