### ISSUE TITLE
[Windows] Крашится при открытии меню Touch buttons

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1155]
Когда только запускаю движок, и захожу в меню сенсорных кнопок, я могу видеть что список сенсорных кнопок пустой, или может отображаться какой-то мусор в полях с командой и текстурой для тач кнопки, либо вообще движок может крашнуться.

Если при первой попытке входа в меню сенсорных кнопок (Touch buttons) движок не крашнулся, то при повторном открытии этого меню, все тач кнопки нормально отображаются, с правильными названиями, командами и текстурами.

Вот лог с крашем
```
Sys_Crash: address 6EC147E3, code C0000005
Exception: D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\ItemsHolder.cpp:460:20
PC: D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\ItemsHolder.cpp:460:20
 0 6EC147E3 CMenuItemsHolder::AddItem (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\ItemsHolder.cpp:460:20) (menu.dll)
 1 6EC3F2CC CMenuTouchButtons::_Init (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\menus\TouchButtons.cpp:452:0) (menu.dll)
 2 6EC151A8 CMenuItemsHolder::Init (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\ItemsHolder.cpp:217:0) (menu.dll)
 3 6EC14188 CMenuFramework::Init (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\Framework.cpp:90:0) (menu.dll)
 4 6EC10908 CMenuBaseWindow::Show (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\controls\BaseWindow.cpp:34:0) (menu.dll)
 5 6EC05EB7 CEventCallback::operator() (D:\a\xash3d-fwgs\xash3d-fwgs\3rdparty\mainui\EventSystem.cpp:69:0) (menu.dll)
 6 6EC1027C CMenuBaseItem::_Event(menu.dll)
 7 6EC17F(menu.dll)
 8 6EC158(n()Host_WriteGLConfig()
```
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/10175326/engine.log)

**Comment by Velaron** [comment]
мусор в памяти скорее всего

**Comment by Velaron** [comment]
touch.cfg дефолтный?

**Comment by Vladislav4KZ** [comment]
> touch.cfg дефолтный?

У меня выбран тач профиль который я сохранял для проверки работоспособности сохранения тач профилей в ксаше. Он по сути вообще без изменений, разве что, может отсутствовать кнопка для рисования спрея.

**Comment by Vladislav4KZ** [comment]
И да, путь к текстурам для тач кнопок не содержит расширения .tga

**Comment by Vladislav4KZ** [comment]
Полностью удалил папку touch_profiles и файл touch.cfg, падение движка всё ещё может воспроизводиться.

**Comment by Velaron** [comment]
вылетает если перед этим зайти в touch options если я правильно понял

**Comment by Vladislav4KZ** [comment]
> вылетает если перед этим зайти в touch options если я правильно понял

Нет, я сразу захожу в Touch buttons и через раз ловлю краш

**Comment by Vladislav4KZ** [comment]
Исправлено: https://github.com/FWGS/xash3d-fwgs/commit/5098e24806d14848c806fb0eee7630c75f6a2db6
