### ISSUE TITLE
Какой-то вылет в меню, если отсутствует папка logos

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1163]
![image](https://user-images.githubusercontent.com/70335841/206928839-16edfa06-1b7c-48b9-8777-bee05c582c19.png)

**Comment by a1batross** [comment]
Fixed in [0966971](https://github.com/FWGS/mainui_cpp/commit/096697124fcb7cc9720c348352b716232f80fa90)
