### ISSUE TITLE
Console var for completely turning off rcon protocol on server

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1164]
If this cvar enabled, then server just ignores all incoming rcon packets. This is useful for security reasons, you can just turn off rcon in case you are not using it and won't caring about protecting it anymore.
For example it can be named `rcon_disable`

**Comment by a1batross** [comment]
Fixed in e1431e10.

New cvar is rcon_enable.

**Comment by a1batross** [comment]
Sorry, I didn't noticed you suggested rcon_disable name for it. :)
