### ISSUE TITLE
Вылет при обновлении списка серверов

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1167]
![изображение](https://user-images.githubusercontent.com/25657591/207449468-b50ffa94-110e-4e9e-80cc-06df55e1a3db.png)

**Comment by Vladislav4KZ** [comment]
Это же когда ты держал полосу прокрутки во время автообновления списка серверов?

Я писал про подобную проблему здесь: https://github.com/FWGS/mainui_cpp/issues/86

**Comment by SNMetamorph** [comment]
Эта проблема уже пофикшена?

**Comment by SNMetamorph** [comment]
Не помню когда и как, но уже пофикшено

**Comment by Vladislav4KZ** [comment]
> Не помню когда и как, но уже пофикшено

Видимо нет, я держал полосу прокрутки в списке серверов и ждал автообновления списка.

После обновления списка, так же как и раньше, всплыла ошибка Assertion failed!

**Comment by SNMetamorph** [comment]
Перепроверил, действительно поймал вот такой assert
![изображение](https://github.com/FWGS/xash3d-fwgs/assets/25657591/5c4db875-f0e7-4129-81f5-a677b7fbb08a)

**Comment by a1batross** [comment]
Исправил в https://github.com/FWGS/mainui_cpp/commit/757ace3d4e7c318faaf90ea0510a327f762f3f4a

Но, возможно, есть ещё способы вызвать этот ассерт.
