### ISSUE TITLE
TFC works flawless aside from Sniper Rifle animation/sound

### ISSUE THREAD

**Issue by BaronKrause** [FWGS/xash3d-fwgs#117]
Just tested TFC again in the latest 0.20 release as a mod in Xash32 FWGS on Windows and it works pretty great.

Everything seems to work fine aside from the sniper rifles fire. It has that unique functionality where it needs to be held down to charge and the gun lifts up and displays the red dot on the target. In Xash3d FWGS it behaves weird, the gun animation doesn't go up all the way, and its sound is wrong too, almost like a tranq dart sound, that or that's a minor sound that plays along with the normal one, and now thats all you hear in its absence (i remember hearing that sound along with the normal firing sounds of other weapons for instance). It doesn't leave a mark on the wall where you shot either.

It does work though, testing with 2 simultaneously running clients in a LAN it still insta gibs on headshot so it not totally busted. Its just weird.

Everything else works perfect so i'm hoping it's some very minor tweak, if that's even something anyone wants to look at considering it is a mod (although an official one).

Its using the same steam version of half life as a base that it normally runs fine in. When running using the hl.exe instead of the xash_vc.exe in that same installed folder, the sniper rifle functions correctly, so it must be a quirk with the way Xash3d is handling that 1 weapon right?

The result is the same when using the linux build of Xash3d/Half-Life/TFC.

**Comment by a1batross** [comment]
Должно быть исправлено после ea5937bce0541fdf2f10995f122f5b4ab4011a54

Must be fixed after ea5937bce0541fdf2f10995f122f5b4ab4011a54
