### ISSUE TITLE
Cheat Idea

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#1170]
ENG

Before I can share this idea, this is only something that I would expect at a certain later point, as I do understand there are other things that are presumably in higher priorities.

The idea is creating a cheat code that gives the player infinite ammunition, and can also function with weapons that aren't within the main Half-Life campaign (e.g. Afraid of Monsters: Director's Cut). What do you think eh? 😁

RUS

Прежде чем я смогу поделиться этой идеей, это всего лишь то, что я ожидаю на определенном более позднем этапе, поскольку я понимаю, что есть другие вещи, которые предположительно имеют более высокий приоритет.

Идея заключается в создании чит-кода, который дает игроку бесконечные боеприпасы, а также может работать с оружием, которого нет в основной кампании Half-Life (например, Afraid of Monsters: Director's Cut). Как вы думаете, а? 😁

**Comment by xorusr** [comment]
А самому слабо???

**Comment by ToxicHolyGrenade** [comment]
@unnamed9 I wouldn't say impossible, but it would be semi-impossible. The reason why, is that the source code for this cheat can be also shared, and anyone can add in custom weapons by doing so. In other words, they can even upload the edited source code variants for any mod they come across. Even if there's so many mods out there, we shall all work together to get as many mods as possible done with.

That's the specialty of team work.

**Comment by erfty125** [comment]
> А самому слабо???

рил , по факту

**Comment by erfty125** [comment]
> ENG
> 
> Before I can share this idea, this is only something that I would expect at a certain later point, as I do understand there are other things that are presumably in higher priorities.
> 
> The idea is creating a cheat code that gives the player infinite ammunition, and can also function with weapons that aren't within the main Half-Life campaign (e.g. Afraid of Monsters: Director's Cut). What do you think eh? 😁
> 
> RUS
> 
> Прежде чем я смогу поделиться этой идеей, это всего лишь то, что я ожидаю на определенном более позднем этапе, поскольку я понимаю, что есть другие вещи, которые предположительно имеют более высокий приоритет.
> 
> Идея заключается в создании чит-кода, который дает игроку бесконечные боеприпасы, а также может работать с оружием, которого нет в основной кампании Half-Life (например, Afraid of Monsters: Director's Cut). Как вы думаете, а? 😁

реализовать бесконечные патроны будет не очень сложно а вот с оружием из модов нужно будет либо их предварительно добавить в игру , либо писать отдельную систему для оружий. но я думаю это не особо нужно ибо ты в том же моде можешь пострелять с оружия или добавить его в свой мод. также для оружий из модов хл характерна уникальность и это может усложнить процесс разработки.....

**Comment by ToxicHolyGrenade** [comment]
@erfty125 Напротив, у меня есть такая чит-идея не только для определенного будущего обновления в более поздний момент, но она также служит более прогрессивным и эффективным для использования, чем импульс 101.

**Comment by erfty125** [comment]
> @erfty125 Напротив, у меня есть такая чит-идея не только для определенного будущего обновления в более поздний момент, но она также служит более прогрессивным и эффективным для использования, чем импульс 101.

скорее всего нужно будет создавать скриптовую систему с интерпритатором , и это  сложно. Например такая система есть в гмод.

**Comment by ToxicHolyGrenade** [comment]
It is difficult, but it is still worth trying out.

**Comment by ToxicHolyGrenade** [comment]
No worries, this is just an idea I had been thinking.

**Comment by xorusr** [comment]
> > @erfty125 Напротив, у меня есть такая чит-идея не только для определенного будущего обновления в более поздний момент, но она также служит более прогрессивным и эффективным для использования, чем импульс 101.
> 
> скорее всего нужно будет создавать скриптовую систему с интерпритатором , и это сложно. Например такая система есть в гмод.

Блять эрфти, ливни нахуй с гитхаба

**Comment by erfty125** [comment]
> > > @erfty125 Напротив, у меня есть такая чит-идея не только для определенного будущего обновления в более поздний момент, но она также служит более прогрессивным и эффективным для использования, чем импульс 101.
> > 
> > скорее всего нужно будет создавать скриптовую систему с интерпритатором , и это сложно. Например такая система есть в гмод.
> 
> Блять эрфти, ливни нахуй с гитхаба

нэт
