### ISSUE TITLE
Crossing Over Content (Mods, Goldsrc Engine games, etc.)

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#1189]
Much to me being a crossover freak, I am pretty sure there are others who do as well. While I do understand it is incredibly hard to do presumably, I have some ideas to make that possible.

Giving XASH 3D FWGS the capability of using more than one client DLL, and same goes with the main DLLs (e.g hl.dll). Those same DLL files contains all the stuff necessary to have a specific game/mod to function, especially the content. If XASH 3D FWGS can have the ability of using more than one DLL, that can add much more content to the mod/game in question.

If I where to crossover content of Afraid of Monsters: Director's Cut, I will copy over its DLL and client DLL files over to... They Hunger for example, and have the NPCs, weapons, items, etc, in the mod, and vice versa.

The way this idea works exactly though, is through editing the liblist.gam as usual. The part where it says "gamedll" to gamedll_linux," will say gamedll2, 3, and so on.

gamedll# "dlls\nameofdll.dll"
gamedll_linux# "dlls/nameofso.so"
clientdll "client\client.dll
clientdll# "dlls\nameofclient.dll"
gamedll_linux# "dlls/nameofso.so"

**Comment by nekonomicon** [comment]
I think you need something like [BotMixer 5000](http://hpb-bot.bots-united.com/botmixer.html) or plugin system like metamod.

**Comment by ToxicHolyGrenade** [comment]
That may be so, but to be honest, and you are free to correct me on that, but it seems there are no other alternatives to BotMixer 5000, and that's why I am in favour of having XASH 3D FWGS having the same thing, or like I had discussed before, having the XASH 3D FWGS engine to have the ability to use more than one dll.

**Comment by ToxicHolyGrenade** [comment]
If that's so, then there needs to be ways around that, even it its extremely hard.

**Comment by erfty125** [comment]
> If that's so, then there needs to be ways around that, even it its extremely hard.

you can make interpreter system with lua(or other language) like in gmod

**Comment by ToxicHolyGrenade** [comment]
To be honest, I am just a layman; I am not an expert on programming and all that, I am just only sharing ideas that comes to my mind, and sharing them around.

**Comment by erfty125** [comment]
> To be honest, I am just a layman; I am not an expert on programming and all that, I am just only sharing ideas that comes to my mind, and sharing them around.

i recomend you close this issue because nobody will make it

**Comment by nekonomicon** [comment]
Anyway, such things can be implemented in external modules.
And there no reason to touch engine.
You can try to make metamod plugin or proxy between engine and gamedll.

**Comment by ToxicHolyGrenade** [comment]
> > To be honest, I am just a layman; I am not an expert on programming and all that, I am just only sharing ideas that comes to my mind, and sharing them around.
> 
> i recomend you close this issue because nobody will make it

To be honest, the reason why I won't is because, in case there _are_ Goldsrc-based programmers, this very discussion will be kept open, once it comes to a time some would come along.

**Comment by ToxicHolyGrenade** [comment]
> Anyway, such things can be implemented in external modules. And there no reason to touch engine. You can try to make metamod plugin or proxy between engine and gamedll.

To be honest, would there have been a Metamod plugin similar to what I have in mind already, and care to explain the proxy thing?

**Comment by a1batross** [comment]
Wontfix

**Comment by erfty125** [comment]
> > > To be honest, I am just a layman; I am not an expert on programming and all that, I am just only sharing ideas that comes to my mind, and sharing them around.
> > 
> > i recomend you close this issue because nobody will make it
> 
> To be honest, the reason why I won't is because, in case there _are_ Goldsrc-based programmers, this very discussion will be kept open, once it comes to a time some would come along.

play gmod))))))))
