### ISSUE TITLE
map 's own entity file update is not checked at reload...

### ISSUE THREAD

**Issue by sixcentgeorge** [FWGS/xash3d-fwgs#119]
i saw that when i edit the map entity file using bspedit and then relaunch the map using the console .. xash3d does not check if the file has been modified and reload what is in memory with the previous reading..
if i want to see the change i made while the opengl windows was down , i have to load an other map.. then reload the map that has an updated ent file .
with an example to be clear and sure to be understood : if i load map A00 then want to change something like a spawn.. so i use alt-tab to go back to desktop and open A00 with bspedit . change the location of the spawn and save it..  if i use alt tab and reload A00 THEN I SEE NO CHANGE.. if i load B00 and after A00 then i see the update applied .

**Comment by a1batross** [comment]
How do you restart? You can shut down server(by calling disconnect if you are in local for example) and load map again.

**Comment by sixcentgeorge** [comment]
by now ...i used only a listen server ...and command map in console ..
then i use the arrow keys to get the typed previous map cmd ...[ like doskey.com at msdos prompt ]

i made topics at hlfx.ru ... take time to read them...& write that i am active here..  to help my karma  ...
some members are not having or sharing the same large view of what is a mod .. like most people : they find black mesa or decay pc mod are real creations.. but when others : like me make something as new and big and beautiful as the eiffel tower or the canals of suez & panama... they are " counterfeiters " or SO.. thanks .. i would not like to stop using xash3d and reporting bugs....here
