### ISSUE TITLE
Не работает режим выделенного сервера, если сервер запускается без параметров -dev 2 и -log.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1190]
При попытке запустить выделенный сервер, если в параметрах запуска не указано -dev 2 и -log, то сервер аварийно останавливается с этими ошибками:
```
Warning: NET_UDPSocket: port: 27015 bind6: WSAEADDRNOTAVAIL
Host_InitError: Couldn't allocate dedicated server IP port 27015.
```
Если указать -dev 2 и -log в параметры запуска, то выделенный сервер запускается как положено.

**Comment by Vladislav4KZ** [comment]
Судя по ошибкам, у тебя занят порт 27015 (например, запущен listenserver в ксаше) и в это же время ты пытаешься запустить XashDS

**Comment by Vladislav4KZ** [comment]
Режим разработчика и логгирование тут не причём. С ними тоже при первой попытке запуска карты, появляется ошибка Couldn't allocate dedicated server IP port 27015.

Когда запускаю карту со второго раза, сервер запускается успешно.

**Comment by Vladislav4KZ** [comment]
Проверил с разными аргументами запуска:
``-dedicated``, ``-dedicated -dev`` ``-dedicated -log``, ``-dedicated -dev -log`` и ``-dedicated -dev 1 -log`` – сервер не запускается с первого раза.

А с ``-dedicated -dev 2 -log`` сервер успешно запускается с первого раза.

**Comment by a1batross** [comment]
Фикс написал, но ещё не коммитил.
