### ISSUE TITLE
CI-failing for android and motomax

### ISSUE THREAD

**Issue by strikersix23** [FWGS/xash3d-fwgs#1192]
it seams like the ci is failing due to missing sdl2 libs for android, any solutions for this

**Comment by strikersix23** [comment]
may i get a link to this new ports source or download/info page?

**Comment by TheKingFireS** [comment]
> may i get a link to this new ports source or download/info page?

https://play.google.com/store/apps/details?id=su.xash.engine

**Comment by strikersix23** [comment]
thank you appreciate it I'm going to close this issue

**Comment by lewa-j** [comment]
@strikersix23
https://github.com/Velaron/xash3d-fwgs/tree/android

**Comment by a1batross** [comment]
motomagx port is gcc 3 and I look into it last.

Android won't be touched unless we merge new SDL2 based port.
