### ISSUE TITLE
Scaled HUD Artifacting

### ISSUE THREAD

**Issue by Flintastic** [FWGS/xash3d-fwgs#1193]
There is a lot of artifacting when scaling the HUD with cvar hud_scale.

As seen below, every single HUD element has visible outlines of their boxes.

(Please zoom in)

![t0a0_0004](https://user-images.githubusercontent.com/66497936/209987829-ecbb83d0-ea61-4daa-8cca-b65bd49a7a01.png)

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/e5b32fe8ac5058559b9320e85f13d0f6ae878b01

Fixed. It will be a bit crusty now but don't have these artifacts

**Comment by Flintastic** [comment]
That will do nicely. Thanks!
