### ISSUE TITLE
Gamepad Issues

### ISSUE THREAD

**Issue by Flintastic** [FWGS/xash3d-fwgs#1194]
There are several issues with Gamepad support, all related to basic movement (forward/backward/strafe). The effects vary by whether Xinput or Dinput is in use.

**1. Cannot climb ladders.**
     [Xinput]: Cannot climb ladders at all.
     [Dinput]: Can only strafe up/down ladders.

**2. Moving with Gamepad breaks keyboard movement inputs.**
     [Xinput]: Keyboard movement inputs are completely broken (impossible to finish games with ladders).
     [Dinput]: Only strafing works with keyboard.

**3. Movement controls do not work when bound to a Gamepad's buttons or dpad.**
     [Xinput]: Movement does not work at all.
     [Dinput]: Only strafing works with buttons/ dpad.

On a side note, I think the default deadzones for pitch/yaw being 0 is potentially problematic. I experienced a lot of drifting. I think setting the defaults to at least 800 is safer, especially since these settings are not in the options menus.

**Comment by kloptops** [comment]
I had the same ladder issue, to fix it you have to set the deadzone on joy_forward_deadzone to “10000” (which is 10%). Hopefully this fixes it for you too.

**Comment by a1batross** [comment]
I wonder if it's SDL2 breaking gamepads for us again? Try to test your gamepad with `-sdl_joy_old_api`.

**Comment by kloptops** [comment]
I tried that but it just made everything worse all around. If I didn’t have a deadzone set the movement velocity would be clamped to 0 when on a ladder.

![7C2CC8E9-BA66-46EF-8691-4086D623BB66](https://user-images.githubusercontent.com/4617076/210329908-388cb849-fbb7-4f2d-ae04-33b65513e5f1.png)

**Comment by mmillar-bolis** [comment]
Is `-sdl_joy_old_api` the old buggy controller API that is also in Steam/GoldSrc? It appears to function the same and prevent me from mapping additional axis.

I am using an Xbox 360 controller in my setup. I can confirm that if `joy_forward_deadzone` is set below a value of `10`, the player will still attach to the ladder, but will no longer accelerate up it. However, the value is set to `10` or above, it appears that the player can consistently climb the ladder each time.

In my further testing, I found that if `joy_forward_deadzone` was set to `1`, they would attach to the ladder but be unable to accelerate, the same as a default value of `0`. Setting it from `2` ~ `9` generally resulted in the same problem, unless the player was in the air with a velocity greater than 150, in which case they will accelerate up the ladder roughly every third try.

---

I was previously on build `2743` from October. I am now testing build `2834` (latest build) and there are definitely some major differences in input scaling, movement sensitivity, and smoothing. These were my previous settings:

```
joy_enable 1
joy_axis_binding "sflpyr"
joy_forward 0.90
joy_side 0.90
joy_yaw 35
joy_pitch 50
joy_forward_deadzone 8192
joy_side_deadzone 8192
joy_yaw_deadzone 4096
joy_pitch_deadzone 4096
joy_rt_threshold 8192
joy_lt_threshold 8192
look_filter 0
sensitivity 3 (mouse sensitivity affects joystick looking)
```

In prior builds, `joy_forward` and `joy_side` appeared to be equally sensitive to each other. This was also true of `joy_yaw` and `joy_pitch`. In build `2834`, `joy_forward` and `joy_yaw` are more sensitive, even when they have the same values as `joy_side` and `joy_pitch`.

---

What is interesting to me is that in *both* build `2743` and `2834`, my velocity when moving at full speed shows as `360` (movement speed of 400 minus deadzone of 0.9 or 10%). *However* when I time my movement from one object to another, I am moving more slowly in build `2834`, despite my velocity reading the same at `360`.

An easy way to test this is to make a standard config to use between both builds, stand at the back of the elevator in the Hazard Course and walk forward to the holopanel. In build `2743` with my velocity at `360`, this would take me roughly 1.5 seconds, playing back 4 footstep sounds. In build `2834`, this same movement takes closer to 2 seconds and creates only 3 footstep sounds.

The movement scaling may be more accurate to GoldSrc, I'm not sure. I merely noticed that movement is now different and slightly slower, looking is smoother but more sensitive, and Y-axis values are more sensitive than X-axis values now.

Thank you for all of your wonderful and hard work! Xash3D-FWGS is my preferred way to play. :)

**Comment by Flintastic** [comment]
All issues were fixed.

**Comment by Flintastic** [comment]
All issues were fixed.
