### ISSUE TITLE
[MOD: Half-Payne] Краш Ксаша при попытке загрузить этот мод.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1195]
При попытке запустить мод Half-Payne в Ксаше, Ксаш крашится с ошибкой "Abnormal program termination."

**Comment by TheKingFireS** [comment]
On latest commit Xash3D, it doesn't crash anymore. I think you can close it now.

**Comment by Vladislav4KZ** [comment]
> On latest commit Xash3D, it doesn't crash anymore. I think you can close it now.

The author of this issue deleted his account :)

I'll re-check it now and close it.

**Comment by Vladislav4KZ** [comment]
@TheKingFireS This mod still crashes for me.

How did you run it, and what version?

**Comment by Vladislav4KZ** [comment]
I tried to run this version: https://www.moddb.com/mods/half-payne/downloads/half-payne-august-4th-2022

And it crashes.

**Comment by Vladislav4KZ** [comment]
Wait, I reinstalled this mod version and it started.

**Comment by TheKingFireS** [comment]
@Vladislav4KZ
Copy and pasted latest Half-Payne mod to xash directory
Run Half-Payne via shortcut ``xash.exe -dev 5 -log -game half_payne``
It crashed on first run
Now it doesn't crash on second run, but lagging for ~5 seconds

Xash3D FWGS v49/0.20
Branch: master
Commit: [7a469fb](https://github.com/FWGS/xash3d-fwgs/commit/7a469fb481d9bdb62923868f1acdff65d9058e6e)
Build number: 3399
Build type: win32-i386

**Comment by Vladislav4KZ** [comment]
Yes, it's actually working.
After I reinstalled this mod.

So I'll close it then.

**Comment by Vladislav4KZ** [comment]
@TheKingFireS By the way, the maximum level of developer mode is **2**. **3** or more don't make sense.
