### ISSUE TITLE
Краш при попытке развернуть Ксаш из панели задач после его сворачивания, в случае включенного fullscreen'а.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#1197]
При попытке развернуть Ксаш из панели задач после его сворачивания, в случае включенного fullscreen'а, появляется окно с ошибкой, которое говорит, что что-то не так с контентом игры и просит его переустановить.

**Comment by Vladislav4KZ** [comment]
Эта проблема появилась только недавно? Потому что у меня никогда такого не было. Я даже на самом последнем билде успел уже несколько раз сворачивать-разворачивать игру, и никаких ошибок не было.

**Comment by a1batross** [comment]
А может прислать хотя бы скриншот ошибки? По описанию я нихуя не понял.

**Comment by a1batross** [comment]
Ровно тот же факт, почему вы что-то делаете с SDL2, без перекомпиляции.

**Comment by a1batross** [comment]
> А может прислать хотя бы скриншот ошибки? По описанию я нихуя не понял.

Было бы шикарно и платформу

**Comment by a1batross** [comment]
Это я такое писал?.. Руки бы себе оторвать.

**Comment by Vladislav4KZ** [comment]
> Это в общем из-за нового SDL2, я его отдельно от Ксаша обновил до самой последней версии (2.26.1) когда-то давно и забыл про это, когда как в комплекте с Ксашем поставляется версия 2.0.14.

Попробовал заменить SDL2.dll на ту же версию, про которую ты писал, и такой проблемы нет.

У меня Windows 10 Pro x64 22H2

**Comment by Vladislav4KZ** [comment]
> Это я такое писал?.. Руки бы себе оторвать.

@a1batross Это вообще строка из hlsdk-portable
```
hlsdk-portable/cl_dll/hud.cpp:579:          const char *msg = "There is something wrong with your game data! Please, reinstall\n";
```

У меня такой ошибки не было, так как я использую оригинальные стимовские библиотеки.

**Comment by Vladislav4KZ** [comment]
Как я и говорил в другой issue, У меня такой проблемы нет.
На виртуалке с Windows 11, с SDL2 2.26.1 и либами с hlsdk-portable не появляется такая ошибка при разворачивании ксаша с панели задач в полноэкранном режиме.
