### ISSUE TITLE
Не работают кастомные карты с серверов после их загрузки из FastDL.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1199]
После загрузки кастомных карт из FastDL, движок их не видит, из-за чего коннект обрывается с Host_Error и ошибкой, типа карты нету, кастомные карты с FastDL даже через консоль невозможно загрузить.
Однако если перезапустить движок, кастомные карты загружаются корректно, что через консоль, что при подключении к серверу.
Например, такая проблема есть на сервере Tyabus DM.

**Comment by Vladislav4KZ** [comment]
Зашёл на сервер тябуса, оттуда скачалась карта xbounce и я успешно подключился к серверу.

**Xash3D FWGS 0.21 build 2834 win32-i386**
**Windows 10 Pro x64 22H2**

Проблемы связанные с загрузкой с FastDL на старых серверах я ни разу не замечал. Были проблемы с ним только на новых серверах.

**Comment by Vladislav4KZ** [comment]
Проблема появилась после удаления папки downloaded.

Оно помимо карты ещё и модели качало. А когда у меня была папка downloaded с уже скачанными моделями, карта качалась и запускалась успешно.
