### ISSUE TITLE
Краш при попытке выставить hud_scale в 2 и выше и сделать restart.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#1202]
Помимо этого, движок перестаёт вовсе запускаться, крашаясь с той-же ошибкой, что и ниже, помогает только удаление квара hud_scale из config.cfg через любой текстовый редактор.
![nnamed](https://user-images.githubusercontent.com/96422615/210768730-f7e8c976-053a-4028-82ab-2a968c0c2b4e.png)

**Comment by Vladislav4KZ** [comment]
У меня ксаш при смене hud_scale не требует перезапуска карты, и не вылетает с ошибкой.

Единственное что заметил, и хотел ещё пару дней назад зарепортить, но пишу только сейчас, это то что VGUI окна неправильно масштабируются на нестандартном hud_scale
![crossfire_0000.png](https://user-images.githubusercontent.com/22411953/210771504-426e87af-ed3c-49f8-bd85-80ffc0e13b01.png)

**Comment by Vladislav4KZ** [comment]
Насчёт масштабирования VGUI окон при изменении hud_scale: думаю это проблема самого VGUI, т.к. она решается перезапуском ксаша. На голдсурсе же ведь при смене разрешения перезапускается движок.

Такая же проблема с масштабированием окон VGUI происходит не только при изменении hud_scale, но и при смене разрешения экрана.

**Comment by Vladislav4KZ** [comment]
Баг связан с использованием библиотек из https://github.com/FWGS/hlsdk-portable

Я использовал оригинальные стимовские client.dll и hl.dll, и там такого бага нет.

**Comment by Vladislav4KZ** [comment]
> Баг связан с использованием библиотек из https://github.com/FWGS/hlsdk-portable

Завтра попробую поставить эти либы и проверить у себя.

**Comment by a1batross** [comment]
УМВР.

**Comment by a1batross** [comment]
Duplicate of #1197

**Comment by Vladislav4KZ** [comment]
> УМВР.

Тоже. Поставил библиотеки с репозитория hlsdk-portable и SDL2 версии 2.26.1.0

Ошибок нет как при сворачивании-разворачивании игры в полноэкранном режиме, так и при смене hud_scale и рестарта карты, которые были у unnamed9

**Comment by a1batross** [comment]
Не воспроизводится. ¯\_(ツ)_/¯
