### ISSUE TITLE
Random game crashing on macOS 64bit

### ISSUE THREAD

**Issue by kotleni** [FWGS/xash3d-fwgs#1203]
**Description:** Random game crashes with an error.
**Error:** `Mem_Free: not allocated or double freed (free at /xash3d/engine/common/model.c:2763)`
**OS:** macOS Ventura 13.2
**Device:** MacBook Air M1 (2020)
**Game version:** Actual steam version for macOS
**Engine version:** v48/0.19.3 build 2747 de8ab25c Apple-aarch64 (compiled it myself)
**Proofs:** <a href="https://pasteboard.co/HHKdlNijT6mY.png">image</a>

**Comment by a1batross** [comment]
We do not support any of Apple devices.

**Comment by a1batross** [comment]
Also, put 0.19.x into the trash bin. It's outdated for years now. 

There were somebody who built latest version from this repo, but it's again, it's unsupported.

**Comment by kotleni** [comment]
@a1batross thx
