### ISSUE TITLE
Выкидывает из команды scientist в spectator обнуляя счет, если в fullscreen'е свернуть и развернуть игру.

### ISSUE THREAD

**Issue by DENCHIKTEAM** [FWGS/xash3d-fwgs#1206]
Играл на локальном сервере XashDS (потому что командная игра не запускается через клиент) и при сворачивании игры в fullscreen'е обнаружил что меня из команды scientist перекинуло в spectator и обнулило счет. Я еще решил проверить что происходит если сделать тоже самое в стимовской версии игры и такого недочета там нет. Видео записи игры на Xash3d и GoldSrc версии игры прилагаются.

### GoldSrc: https://youtu.be/GNrj4mhkMGY

**Comment by Vladislav4KZ** [comment]
Уже писали про это: https://github.com/FWGS/xash3d-fwgs/issues/791

Баг тот же, что с командным режимом что с дезматчем

**Comment by Vladislav4KZ** [comment]
> командная игра не запускается через клиент

Про подобное я писал тоже: https://github.com/FWGS/xash3d-fwgs/issues/509

**Comment by Vladislav4KZ** [comment]
> при сворачивании игры в fullscreen'е обнаружил что меня из команды scientist перекинуло в spectator и обнулило счет.

@DENCHIKTEAM Должно быть исправлено в: https://github.com/FWGS/xash3d-fwgs/commit/6232e288e12831ef39e5d704181873a26ab5731d

У меня такой баг больше не воспроизводится.

**Comment by a1batross** [comment]
Думаю, можно закрыть. Если баг появится снова, можно будет просто завести свежий репорт.

**Comment by DENCHIKTEAM** [comment]
Все проверил, бага больше нет, спасибо.
