### ISSUE TITLE
gfx.wad и fonts.wad в пак-файле имеют приоритет над теми, что просто лежат в папке

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1213]
```"host_ver" is "2845 0.20 win32 i386 fbedbdc" ( "2845 0.20 win32 i386 fbedbdc" )```
Собственно, ишшуй. С другими файлами не проверял.

**Comment by a1batross** [comment]
Судя по FS_AddGameDirectory, мы просто перечисляем все файлы в геймдире, сортируем по имени и добавляем по порядку.

Тот кто добавился последний, тот и имеет приоритет.

**Comment by a1batross** [comment]
Похоже это виноват я, потому что раньше там было три отдельных прохода.

**Comment by a1batross** [comment]
Fixed in f27817bb

**Comment by a1batross** [comment]
Вернул прежний порядок. Теперь приоритет такой: PAK -> PK3 -> WAD.
