### ISSUE TITLE
Отсутствие сглаживания у спрайтов ХУДа

### ISSUE THREAD

**Issue by huigrunt** [FWGS/xash3d-fwgs#1214]
Заметил что в свежих билдах на спрайтах худа пропало сглаживание. Как скоро это исправят?

**Comment by a1batross** [comment]
@huigrunt можно пример, где хотелось бы иметь сглаживание?

**Comment by huigrunt** [comment]
у меня в моде

**Comment by huigrunt** [comment]
сейчас скину скрины

**Comment by huigrunt** [comment]
1 скрин без сглаживания
![Metro2031 2023-01-15 18-57-32-409](https://user-images.githubusercontent.com/90998299/212613061-ba6e38a7-d42f-4699-a980-381d7861d004.jpg)
второй с ним
![Metro2031 2023-01-15 18-56-46-396](https://user-images.githubusercontent.com/90998299/212613070-f2c1fe5e-53fb-4710-8519-9c696ff01f25.jpg)

**Comment by a1batross** [comment]
И это без hud_scale?

**Comment by huigrunt** [comment]
c ним

**Comment by huigrunt** [comment]
hud_scale "1.6"

**Comment by a1batross** [comment]
Не уверен что тогда лучше в этой ситуации делать.

Либо полоски, либо пиксели.

Можно модом в принципе высокие разрешения нативно, примерно так же, как это
делает халфа с 320hud и 640hud.

**Comment by huigrunt** [comment]
Так а сглаживания не будет больше что ли?

**Comment by a1batross** [comment]
Я повторюсь: либо полоски,
![изображение](https://user-images.githubusercontent.com/3213697/212673207-bfbd9a59-0a69-45df-82ac-77c73195aca1.png)


либо пиксели.

**Comment by huigrunt** [comment]
![Metro2031 2023-01-23 13-55-00-061](https://user-images.githubusercontent.com/90998299/213963914-11054a09-81e3-4c20-aa53-dbe69513a47f.jpg)
Под правил худ и эти полоски стали больше в глаза бросаться. Я конечно могу скачать крайний билд, но не хочу без сглаживания работать играть

**Comment by a1batross** [comment]
Вернул обратно. Частично обошел проблему сдвинув текстурные координаты на полтекселя.
