### ISSUE TITLE
Broken FFADE_STAYOUT?

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1215]
High chances after this commit https://github.com/FWGS/xash3d-fwgs/commit/a4865fd2fcaab9671fe5c94d101a17daec2e50de

**Comment by a1batross** [comment]
Probably fixed with https://github.com/FWGS/xash3d-fwgs/commit/5313dc94756756d8d36a79889568d873a536cd4d

**Comment by Aynekko** [comment]
Yes, fixed.
