### ISSUE TITLE
When i try to open bshift it crashes.

### ISSUE THREAD

**Issue by NukeThief** [FWGS/xash3d-fwgs#1218]
![image](https://user-images.githubusercontent.com/81801547/213537424-04443321-aa80-4960-bc3e-c8eff0342d8f.png)
thats what it says

**Comment by TheKingFireS** [comment]
https://github.com/FWGS/hlsdk-portable/actions/runs/3550827717

**Comment by NukeThief** [comment]
thanks! it worked. but i think that the stuff should come with fwgs itself.

**Comment by TheKingFireS** [comment]
> thanks! it worked. but i think that the stuff should come with fwgs itself.

What do you mean?

**Comment by NukeThief** [comment]
that the dlls in the bshift folder come with fwgs in its zip i mean.
