### ISSUE TITLE
сатчелы и weaponbox

### ISSUE THREAD

**Issue by erfty125** [FWGS/xash3d-fwgs#1219]
я при игре заметил , что c weaponbox ты можешь кинуть больше 5 сатчелов. Допустим ты кидаешь свои 5 сатчелов и подбираешь ещё 5 из weaponbox и также их кидаешь. Так можно кинуть сколько угодно сатчелов и взорвать их одновременно. Конечно это не критический баг но на картаэ с большим кол-вом weaponbox он может быть критическим и так можно будет крашнуть игру. Работает на новом и старом ксаше. На goldsrc не тестил.

**Comment by a1batross** [comment]
Not a bug
