### ISSUE TITLE
MP5 Texture looks Off

### ISSUE THREAD

**Issue by OpenRift412** [FWGS/xash3d-fwgs#1221]
I was testing out Xash3D today when I noticed that for whatever reason, the MP5's textures look off, especially around the top. Here's a comparison.

Steam:
![20230120234132_1](https://user-images.githubusercontent.com/29780788/213843791-75d24610-fff1-4b2b-b8f7-9d8affd85fb6.jpg)

Xash3D:
![crossfire_0000](https://user-images.githubusercontent.com/29780788/213843804-91f57e65-c893-4bb1-944a-f444c159b11b.png)

Is this caused by a certain render setting?

**Comment by a1batross** [comment]
It's not, it's a bug.

But I don't see any difference in GoldSrc and Xash handling chrome textures.

**Comment by OpenRift412** [comment]
> It's not, it's a bug.
> 
> But I don't see any difference in GoldSrc and Xash handling chrome textures.

Well _something_ must be handling it different, right?

**Comment by a1batross** [comment]
I inverted texture coordinates, and now it looks identical to GoldSrc. 

```diff
@@ -2407,7 +2403,7 @@ static void R_StudioDrawPoints( void )
                else
                {
                        if( FBitSet( g_nFaceFlags, STUDIO_NF_CHROME ))
-                               R_StudioDrawChromeMesh( ptricmds, pstudionorms, s, t, shellscale );
+                               R_StudioDrawChromeMesh( ptricmds, pstudionorms, -s, -t, shellscale );
                        else if( FBitSet( g_nFaceFlags, STUDIO_NF_UV_COORDS ))
                                R_StudioDrawFloatMesh( ptricmds, pstudionorms );
                        else R_StudioDrawNormalMesh( ptricmds, pstudionorms, s, t );
```

You can try it but disable r_studio_drawelements, or apply same inversion to branch above.

**Comment by a1batross** [comment]
I don't want to apply this, because I'm still not sure what _exactly_ causes this bug.
