### ISSUE TITLE
Menu sprite glitches for Decay

### ISSUE THREAD

**Issue by OpenRift412** [FWGS/xash3d-fwgs#1222]
Upon loading up Decay, I noticed some weird glitches around the menu graphics when each item is highlighted.

![image](https://user-images.githubusercontent.com/29780788/213844107-0626e077-18b3-4ca1-94c4-126758d41f4e.png)

**Comment by a1batross** [comment]
This should be investigated. Can you post btns_main.bmp file? It must be in gfx/shell folder.

**Comment by OpenRift412** [comment]
Here you go.

[btns_main.zip](https://github.com/FWGS/xash3d-fwgs/files/10472648/btns_main.zip)
