### ISSUE TITLE
[MOD: The Conspiracy in Shadow | Remod] Сломался шрифт из-за последних обновлений движка

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1225]
Проблема появилась начиная с этого коммита: https://github.com/FWGS/xash3d-fwgs/commit/c481e52558d23e120bba4f22dc7c9ffe0e573a9b
![tcis0a8_0001](https://user-images.githubusercontent.com/22411953/215049495-170457bb-2702-4b64-a4f6-1792a818b24e.png)

А до того коммита, всё нормально отображалось:
![tcis0a8_0002](https://user-images.githubusercontent.com/22411953/215049716-3295257c-4515-40ca-babd-189a4b978fb7.png)

**Comment by Vladislav4KZ** [comment]
После удаления gfx.wad, буквы стали нормально отображаться.

Вот сам gfx.wad из этого мода:
[gfx.zip](https://github.com/FWGS/xash3d-fwgs/files/10517307/gfx.zip)

**Comment by Vladislav4KZ** [comment]
Ту же проблему заметил и в моде Snow War

**Comment by a1batross** [comment]
39fd30a4
