### ISSUE TITLE
Надпись LOADING... не находится в центре экрана

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1227]
Такой баг появился начиная с этого коммита: https://github.com/FWGS/xash3d-fwgs/commit/84c14b32ec72e9614173efbd235923cbdbc8bec0

![New Engine Screenshot 2023.01.28 - 13.09.17.48.png](https://user-images.githubusercontent.com/22411953/215252498-36949d15-2254-448c-9af2-44ae4c27da13.png)

**Comment by Vladislav4KZ** [comment]
То же самое с надписью PAUSED

**Comment by a1batross** [comment]
Забыл про него совершенно. Исправил. https://github.com/FWGS/xash3d-fwgs/commit/6282acc82563ae67576d56ff07bfde74fefd82f8
