### ISSUE TITLE
Can't initialize cl_dlls/client_amd64.dll: Failed to find library cl_dlls/client_amd64.dll

### ISSUE THREAD

**Issue by solarite1797** [FWGS/xash3d-fwgs#1230]
Hello, this is my first time attempting to use Xash3D FWGS, but apparently when i run the game, it gives me this error:

![image](https://user-images.githubusercontent.com/118111762/215767932-cfbd5496-466e-471c-b123-aec0d7f22e67.png)
I also copied the `valve` folder to the xash3d directory, and i even tried compiling HLSDK, specifically the [updated one by SamVanheer](https://github.com/SamVanheer/halflife-updated).

Note that i am using the steam version, not the WON build.

Help will be appreciated.

**Comment by nekonomicon** [comment]
You need to use 32-bit version of Xash3D FWGS or to compile 64-bit libraries from [hlsdk-portable](https://github.com/FWGS/hlsdk-portable).

**Comment by a1batross** [comment]
Use i386 build. halflife-updated doesn't support amd64, only hlsdk-portable does. We're probably going to revise 64-bit ABI and then propose to other modders.
