### ISSUE TITLE
[MOD: Team Fortress Classic] Сломался шрифт в консоли и HUD в последнем обновлении движка

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1232]
![New Engine Screenshot 2023 02 03 - 20 21 41 19](https://user-images.githubusercontent.com/22411953/216627202-7edcecd3-9365-4d4d-86e5-d0e8a389dc9e.png)
![New Engine Screenshot 2023 02 03 - 20 21 28 26](https://user-images.githubusercontent.com/22411953/216627626-e106aa76-0677-4c49-9aed-0bc973b5fcd4.png)

**Comment by Vladislav4KZ** [comment]
Баг воспроизводится на шрифтах с поддержкой кириллицы.
Вот оба файла: gfx.wad и fonts.wad
[cyrillic_fonts.zip](https://github.com/FWGS/xash3d-fwgs/files/10579759/cyrillic_fonts.zip)

**Comment by a1batross** [comment]
Забыл что нельзя в вадах по какой-то причине использовать Open. Лучше не буду исправлять в ФС, мало ли что от этого зависит.

Исправил в a19d3403
