### ISSUE TITLE
[MOD: Team Fortress Classic] Текст уведомлений в HUD не выравнивается по верхнему правому краю экрана

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1233]
### Было
![New Engine Screenshot 2023 02 04 - 12 15 08 50](https://user-images.githubusercontent.com/22411953/216752290-857ab798-288d-4704-8e13-52a52b5b2725.png)

### Стало
![New Engine Screenshot 2023 02 04 - 12 05 10 65](https://user-images.githubusercontent.com/22411953/216752310-0f7e7dbc-bc68-42b6-b34a-9135fe736842.png)

**Comment by Vladislav4KZ** [comment]
Баг воспроизводится только с русификатором
https://github.com/Vladislav4KZ/tfc-russian/releases/download/latest/TFCRusFull.pk3

С текстом на английском языке такой проблемы нет.

**Comment by a1batross** [comment]
Должно быть пофикшено в последнем коммите.

**Comment by Vladislav4KZ** [comment]
> Должно быть пофикшено в последнем коммите.

Да, исправлено.
