### ISSUE TITLE
[Opposing Force] Seargent in Intro's voice line doesn't play when falling out of the aircraft

### ISSUE THREAD

**Issue by OpenRift412** [FWGS/xash3d-fwgs#1234]
Was testing out Opposing Force when I noticed that the seargent in the intro (soldier standing to your left) doesn't play his voiceline as he falls out of the aircraft.

**Comment by a1batross** [comment]
With original libraries? Not any kind of reimplementation?

**Comment by Vladislav4KZ** [comment]
Duplicate of: https://github.com/FWGS/xash3d-fwgs/issues/940

**Comment by OpenRift412** [comment]
> With original libraries? Not any kind of reimplementation?

Using the Steam version's gearbox folder.

**Comment by a1batross** [comment]
Fixed in 8293bc91
