### ISSUE TITLE
Making the Expansion Packs Truly Compatible

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#1235]
At least for the PC specifically. The DLLs from the Focal Point file that has been provided peacefully, just only replaces the DLLs for Opposing Force. Also considering that the Press Demo of Opposing Force had been archived and preserved, I have this idea in my mind that I would love to play the prototype on XASH 3D FWGS, but doesn't work.

That's also the reason why I had been thinking of this, especially for other XASH 3D FWGS users. Interested?

**Comment by TheKingFireS** [comment]
use Uncle mike's Xash3D, designed for some WON games series.

**Comment by ToxicHolyGrenade** [comment]
What? And where is it downloaded?

**Comment by TheKingFireS** [comment]
> What? And where is it downloaded?

Nvm, doesn't work with Prototype Opposing forces due to old client.dll and hl.dll
Uncle Mike's Xash3D targeted version HL 1.1.1.0
Anyway, here download : https://www.hlfx.ru/forum/attachment.php?s=b77408ec3079ae956175e7281342d870&postid=179023 for engine
https://www.hlfx.ru/xash/xash_extras.7z for Extras(gfx/shell for menu and other stuffs)

**Comment by a1batross** [comment]
> use Uncle mike's Xash3D, designed for some WON games series.

Don't. We didn't drop compatibility with WON.

**Comment by a1batross** [comment]
Let me make a clarification about these prereleases, alpha, beta, gamma, omega, and other unreleased builds of Half-Life and it's mods.

Run these only on engine builds they're provided with. These builds are so old, that they really don't work well in any of the later GoldSrc releases, not even Xash. And don't even tell me that original Xash can run them, we didn't broke compabitility. If FWGS can't run it, then it's our bug and it must be reported.

In case, if you're really sure that GoldSrc build of that unreleased game matches some released version, then provide a full description of what you're trying to do and what you've got: logs, stack traces, etc. In other words, make this bugreport worthy of investigation than telling me "ayy it doesn't work pls fix".

**Comment by Velaron** [comment]
GoldSrc has been updated a lot over the years with lots of breaking changes, and if Valve can't keep compatibility with old mods, we won't too.

**Comment by ToxicHolyGrenade** [comment]
That's pretty cynical if you ask me. Just because Valve does it doesn't mean we have to too.
