### ISSUE TITLE
Это всё ещё происходит "No sound Debian 10 amd64 with Appimage 32 bit"

### ISSUE THREAD

**Issue by Konstantin749** [FWGS/xash3d-fwgs#1242]
If this still happens, reopen pls.

_Originally posted by @a1batross in https://github.com/FWGS/xash3d-fwgs/issues/149#issuecomment-1013674296_

**Comment by a1batross** [comment]
Ну теперь уж точно пофикшено :)

shared pulseaudio я включил, а хедеры положить забыл.
