### ISSUE TITLE
Dedicated NAT сервер не отображается в сервер-браузере у другого игрока

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1246]
Если я создаю сервер прямо из игры (Internet games -> Create -> NAT[x] -> Start), то игрок видит мой сервер.
Если создаю через dedicated (конкретно ввожу: sv_nat 1, map mapname), этот же игрок сервер не видит.

**Comment by a1batross** [comment]
А если public 1 дописать?

public 1; sv_nat 1; map crossfire

**Comment by Aynekko** [comment]
facepalm jpg. Да, теперь виден. Я и не знал про такой нюанс. Может стоит по-умолчанию сделать этот паблик 1. В таком случае ишшуй можно закрывать.
