### ISSUE TITLE
Overbrights

### ISSUE THREAD

**Issue by Matthaiks** [FWGS/xash3d-fwgs#1249]
https://github.com/FWGS/xash3d/issues/181

@a1batross, what's happened to gl_overbright? It's absent in this fork and r_lighting_modulate does not give the same effect.

**Comment by a1batross** [comment]
It's gone.

Probably will be reworked after gamma implementation would match GoldSrc

пт, 24 февр. 2023 г., 01:24 Matthaiks ***@***.***>:

**Comment by dedok17** [comment]
Что думаете насчет этого?
https://hlfx.ru/forum/showthread.php?s=&threadid=6019&postid=215682#post215682

<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/1df4bc35-ef19-45ad-b7a1-1e36331cf82f" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/294af98e-3455-4bfd-b1b6-4d747750879e" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/5218b54c-ab7c-46ea-a8d2-cae5f880dc29" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/9a698ea4-d0f2-4807-a101-c82a81db2037" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/8f08e3b3-da11-48c8-af8c-5426f89cce49" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/e91f49c2-8890-4159-80bf-27c1de9c4625" width=25%>

**Comment by OpenRift412** [comment]
Any updates on this, since they were restored in the anniversary update?

**Comment by OpenRift412** [comment]
@a1batross so I found some source code that should restore overbrights to Xash, you might want to take a look:
https://www.moddb.com/engines/xash3d-engine/downloads/original-looking-lightmaps-and-textures

**Comment by a1batross** [comment]
Yeah, I already made a diff a while ago: https://github.com/FWGS/Xash3DArchive/commit/9d989ede3a07744cdc82c370f0192904efd2933c

**Comment by OpenRift412** [comment]
> Yeah, I already made a diff a while ago: [FWGS/Xash3DArchive@9d989ed](https://github.com/FWGS/Xash3DArchive/commit/9d989ede3a07744cdc82c370f0192904efd2933c)

I take it there are some issues with this fix that need ironing out before it can be implemented?

**Comment by a1batross** [comment]
I already implemented it my own way

**Comment by OpenRift412** [comment]
> I already implemented it my own way

Is it in any of the existing branches? Or is it just in the Archive repo for now?

**Comment by a1batross** [comment]
@OpenRift412 Yes, it is now!

Check the SourceHut thread: https://lists.sr.ht/~a1batross/xash3d-fwgs/patches/48370
or GitHub PR: https://github.com/FWGS/xash3d-fwgs/pull/1563

Builds should be available soon too.
