### ISSUE TITLE
IOS New Game locked

### ISSUE THREAD

**Issue by DrCoomerPhD** [FWGS/xash3d-fwgs#1252]
![Screenshot_20230227-122338_Xash3D FWGS](https://user-images.githubusercontent.com/110489194/221564319-72d2cc14-3707-470c-b460-1c2a4787244c.jpg)
Locked. Cant click it. Idk what to say

**Comment by a1batross** [comment]
We do not support Cisco IOS.

Nonetheless, you're probably missing some game libraries, and as it usually happens with mods, they're Windows only.

**Comment by DrCoomerPhD** [comment]
Its IOS (International Online Soccer), Sorry for not telling it. "Windows Only", The Game? Also happend with cs 1.6, new game locked. Idk if importing the mod skipped some files.

**Comment by a1batross** [comment]
CS1.6 won't work. It's client.dll uses VGUI2 which is undocumented GoldSrc feature, and it's not yet implemented in Xash.

The mod is indeed Windows only, for 32-bit. It won't work on other platforms like Linux or 64-bit Windows.

**Comment by a1batross** [comment]
Next time, don't crop the screenshot. Version and build information printed on the bottom right corner is important.
