### ISSUE TITLE
xash3d-fwfs2 / half life 2?

### ISSUE THREAD

**Issue by romulasry** [FWGS/xash3d-fwgs#1256]
Any chance on supporting  the source engine?

**Comment by TheKingFireS** [comment]
It's source 1 engine, no. Anyway you can check Nillerusr's github profile, he ported source 1 engine games (not all, obviously) to android and other unsupported platforms.

**Comment by a1batross** [comment]
![no-nope](https://user-images.githubusercontent.com/3213697/223808423-c473dbf0-74c4-4167-a1fb-303fc299f32b.gif)
