### ISSUE TITLE
Не получается собрать на Windows 7

### ISSUE THREAD

**Issue by dotnixd** [FWGS/xash3d-fwgs#126]
Лог:
`C:\Users\pie\sources\xash3d-fwgs>waf configure -T release --sdl2=c:\Users\pie\sources\SDL2-2.0.10-win32-x64 --prefix=c:\Users\pie\Executables\xash3d
Active code page: 1252
Using python
Setting top to                                          : C:\Users\pie\sources\xash3d-fwgs
Setting out to                                          : C:\Users\pie\sources\xash3d-fwgs\build
Build type                                                : release`
После этого больше ничего не выводит, начинает дико жрать память (ПК ребутнулся).
Visual Studio установлен, Git и Python тоже.
Все делаю по мануалу на главной странице.

**Comment by a1batross** [comment]
Запусти с ключом -vvv

**Comment by OverPie** [comment]
`C:\Users\pie\sources\xash3d-fwgs>waf configure -T release --sdl2=c:\Users\pie\so
urces\SDL2-2.0.10-win32-x64 --prefix=c:\Users\pie\Executables\xash3d -vvv
Active code page: 1252
Using python
Setting top to                                          : C:\Users\pie\sources\xash3d-fwgs
Setting out to                                          : C:\Users\pie\sources\xash3d-fwgs\build
Build type                                              : release
10:52:48 runner ['C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe', '-products', '*', '-legacy', '-format', 'json']
10:52:48 runner_env kw={'shell': False}
10:52:48 msvc detected versions ['msvc 16.4']
10:52:48 msvc detecting 'msvc 16.4' - ['msvc 16.4']
10:52:48 msvc get_msvc_version: 'msvc' '16.4' 'x86'
10:52:48 runner ['cmd.exe', '/E:on', '/V:on', '/C', 'C:\\Users\\pie\\sources\\xash3d-fwgs\\build\\waf-print-msvc-1.bat']
10:52:48 runner_env kw={'shell': False}
`

**Comment by a1batross** [comment]
Probably got fixed after a bunch of MSVC/Win32 fixes for waf and waf.bat.

**Comment by SNMetamorph** [comment]
@a1batross я думаю в waf.bat стоит по дефолту прописать кодировку chcp 65001 (т.е. UTF-8)

**Comment by a1batross** [comment]
@SNMetamorph надо убирать, да, потому что судя по комментарию это добавилось из-за второго питона, который как бы конечно существует, но поддерживать его никто не будет. :)

Сможешь протестировать и заслать патч?

**Comment by SNMetamorph** [comment]
> @SNMetamorph надо убирать, да, потому что судя по комментарию это добавилось из-за второго питона, который как бы конечно существует, но поддерживать его никто не будет. :)
> 
> Сможешь протестировать и заслать патч?

Я уже тестил, все работало прекрасно, в том числе кириллица. И сообщения об ошибках MSVC выдаёт тоже в UTF-8 по умолчанию.

**Comment by a1batross** [comment]
@SNMetamorph только одну строчку поменять?

**Comment by SNMetamorph** [comment]
@a1batross да
