### ISSUE TITLE
The configuration failed

### ISSUE THREAD

**Issue by hiwoshixiaoyu** [FWGS/xash3d-fwgs#128]
windows7,I try to build.But has some probliems

Checking for header tgmath.h
not found
Checking for library user32
not found

**Comment by hiwoshixiaoyu** [comment]
- 
![problem](https://user-images.githubusercontent.com/26665341/74918402-fd540b00-5403-11ea-82ac-875976a91610.png)

**Comment by hiwoshixiaoyu** [comment]
I want to build on my PC .windows7 -64

I download SDL2,but I don not understand 
```
waf configure -T release --sdl2=c:/path/to/SDL2 --prefix=c:/path/to/any/output/directory
```
'c:/path/to/SDL2 ' is the SDL's path ? and '--prefix' is output path can every path?

I try this, but failed.
the problem is 

Checking for header tgmath.h
not found
Checking for library user32
not found

**Comment by mittorn** [comment]
check config.log

**Comment by hiwoshixiaoyu** [comment]
from F:\aa_workspace\xash3d-fwgs: Test does not build: Traceback (most recent call last):
  File "F:\aa_workspace\xash3d-fwgs\waf3-2.0.18-45bdcf161ace43d7f7e3693c4d99c86b\waflib\Configure.py", line 599, in run_build
    bld.compile()
  File "F:\aa_workspace\xash3d-fwgs\waf3-2.0.18-45bdcf161ace43d7f7e3693c4d99c86b\waflib\Build.py", line 359, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 2 (run with -v to display more information)

**Comment by kyokyoknutt** [comment]
Sorry for bump, but having same problem.
![image](https://user-images.githubusercontent.com/4120915/106675543-e6f28100-657a-11eb-9ebd-c7f955670e3b.png)
https://pastebin.com/TjWmnXn3
Am I doing something wrong? Thank you!

**Comment by a1batross** [comment]
I think we don't support MSVC6 anymore.

**Comment by kyokyoknutt** [comment]
I wonder why it's trying to default to MSVC6? Weird.

**Comment by a1batross** [comment]
I fixed this problem in Waf, when it picks up older version of MSVC.
