### ISSUE TITLE
Support running from a read-only directory.

### ISSUE THREAD

**Issue by vs49688** [FWGS/xash3d-fwgs#1280]
I'm packaging Xash3d-fwgs for NixOS, and it's required to run from a read-only directory (including the gamedirs).

This, of course, doesn't entirely work. The game runs, but I've run into some issues:

* `gameinfo.txt` creation
    - Not a huge issue, I pre-generate it and comment out the writing code. More of an annoyance, than anything else.
* `Error: FS_WriteFile: failed on .fontcache/Trebuchet MS_36_500_font.bmp`
* `Error: FS_WriteFile: failed on .xash_id`
* `Error: couldn't open temporary header file.`
* Can't write anything in `save/`

Interestingly, every time there's a level change, the player ends up either stuck in a wall, or dead. Not entirely sure if related, but I thought I'd mention it.

Suggestion:

Add a command-line flag (e.g. `-readonly`), or a compile-time flag, that when specified, changes the behaviour to write things relative to [SDL_GetPrefPath()](https://wiki.libsdl.org/SDL2/SDL_GetPrefPath) instead of the game directory. Possibly like `SDL_GetPrefPath("xash3d-fwgs", "<gamedir>")`. I had a brief glance at `engine/server/sv_save.c`, but unfortunately the change appears to be nontrivial.

**Comment by a1batross** [comment]
It's supported already, and there are a multitude of ways to control this behavior.

`XASH3D_BASEDIR` environment variable can be used to set the writable directory. Xash always moves to writable directory as working directory, but if nothing is passed, won't change it and use current working directory.

Read-only directory can be set through `-rodir` command line switch or `XASH3D_RODIR` environment variable.

If read-only directory is set, Xash will automatically create all needed directories in writable path, so you don't have to create anything or supply additional files. It's actually quite useful even in non-sandboxed environments, as I can just share Half-Life installation between Steam and Xash.

As an example, you can look into Flatpak's run script: https://github.com/FWGS/xash3d-fwgs/blob/master/scripts/flatpak/run.sh

**Comment by a1batross** [comment]
As you're packaging for NixOS, don't forget to supply `extras.pk3` archive, which has additional WON-style graphics. It's optional but without it the main menu won't look as pretty :)

There are two environment variables to pass extras archives: `XASH3D_EXTRAS_PAK1` and `XASH3D_EXTRAS_PAK2`. PAK1 is usually used for engine extras file, but PAK2 can be used for mods, mostly used on Android.

**Comment by nekonomicon** [comment]
> Interestingly, every time there's a level change, the player ends up either stuck in a wall, or dead. Not entirely sure if related, but I thought I'd mention it.

It's related.
On changelevel engine writes some data into save folder and reads on the next map.

**Comment by vs49688** [comment]
> It's supported already, and there are a multitude of ways to control this behavior.
> 
> `XASH3D_BASEDIR` environment variable can be used to set the writable directory. Xash always moves to writable directory as working directory, but if nothing is passed, won't change it and use current working directory.
> 
> Read-only directory can be set through `-rodir` command line switch or `XASH3D_RODIR` environment variable.
> 
> If read-only directory is set, Xash will automatically create all needed directories in writable path, so you don't have to create anything or supply additional files. It's actually quite useful even in non-sandboxed environments, as I can just share Half-Life installation between Steam and Xash.
> 
> As an example, you can look into Flatpak's run script: https://github.com/FWGS/xash3d-fwgs/blob/master/scripts/flatpak/run.sh

Ahh, I saw `-rodir` but misunderstood its purpose. Спасибо, setting both `XASH3D_RODIR` and `XASH3D_BASEDIR` fixes the problem!


> As you're packaging for NixOS, don't forget to supply `extras.pk3` archive, which has additional WON-style graphics. It's optional but without it the main menu won't look as pretty :)

Yeah, I saw that. This was going to be my next task :) I'll use `XASH3D_EXTRAS_PAK1`, thanks!

**Comment by a1batross** [comment]
This is a very old feature and not documented properly. Sorry for that :)

**Comment by a1batross** [comment]
By the way, if possible I recommend to use relative paths.

There is one stupid check in FS_Open which is a legacy we derived from Uncle Mike, and nobody remembers exactly why it was added, that checks for leading slashes and skips them.

It can conflict with absolute paths used as read-only or writable directories. It's kinda works for now, but can potentially break.

**Comment by vs49688** [comment]
> This is a very old feature and not documented properly. Sorry for that :)

Всё хорошо) Этот флатпак скрипт будет полезен. Я буду оставить ссылку здесь, когда закончу.
(sorry, I rarely get a chance to practice my Russian)



> By the way, if possible I recommend to use relative paths.
> 
> There is one stupid check in FS_Open which is a legacy we derived from Uncle Mike, and nobody remembers exactly why it was added, that checks for leading slashes and skips them.
> 
> It can conflict with absolute paths used as read-only or writable directories. It's kinda works for now, but can potentially break.

Ah damn, that makes things...annoying. I was simply going to do:
```
      makeWrapper $out/lib/xash3d/xash3d $out/bin/xash3d \
        --set XASH3D_RODIR $out/lib/xash3d \
        --set XASH3D_EXTRAS_PAK1 $out/share/xash3d/valve/extras.pk3
```
which gives
```
#! /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash -e
export XASH3D_RODIR='/nix/store/nhd51mrh63hpi56rvlhawgfm905wydyi-xash3d-fwgs-unstable-2023-03-02/lib/xash3d'
export XASH3D_EXTRAS_PAK1='/nix/store/nhd51mrh63hpi56rvlhawgfm905wydyi-xash3d-fwgs-unstable-2023-03-02/share/xash3d/valve/extras.pk3'
exec "/nix/store/nhd51mrh63hpi56rvlhawgfm905wydyi-xash3d-fwgs-unstable-2023-03-02/lib/xash3d/xash3d"  "$@" 
```

but I can probably rejig that to use relative paths if it's easier.

**Comment by a1batross** [comment]
Absolute paths are used in flatpak script but I don't test it myself too
often and who knows what could go wrong in mods.

If it's not possible, well, we'll have to do something about this check
anyway. :)

**Comment by vs49688** [comment]
I've tested it with absolute paths, and it seems to work. I'll leave it for now.

Here's the current result:
https://github.com/vs49688/nix-repo/blob/xash3d/pkgs/xash3d-fwgs/default.nix

Thanks for your help!
