### ISSUE TITLE
[BUG?] Half-Life WON Main Menu Background Not Showing

### ISSUE THREAD

**Issue by brad86m** [FWGS/xash3d-fwgs#1289]
I updated xash for the first time in about a year, and I have noticed the main menu background for HL does not show up. It is working correctly for Blue-Shift, OF, and many mods I have, just not the original game.

I have re-ripped and updated the game on my Win98 machine before transferring to my Win11 PC to make sure it wasn't my files, and I get the same result. I'm not sure why it wouldn't be showing, as it does work on a really old version of xash from around a year ago.
![xash3d_2023_03_15_17_46_07_155](https://user-images.githubusercontent.com/84683672/225397666-cf1dd948-cba7-40c7-9b81-fa30bf95dda2.png)

**Comment by a1batross** [comment]
Does gfx/shell/splash.bmp exists?

Or resource/BackgroundLayout.txt?

**Comment by a1batross** [comment]
In `valve` directory

**Comment by brad86m** [comment]
It does not, no.

**Comment by brad86m** [comment]
I will check my Windows 98 machine. Not sure why it wouldn't be here, if it is on there.

**Comment by TheKingFireS** [comment]
try extract all gfx/shell from *.pak.

**Comment by brad86m** [comment]
> try extract all gfx/shell from *.pak.

I do not know how, but these pack files work fine on an older version of xash so they are perfectly fine, it seems.

**Comment by nekonomicon** [comment]
Probably engine loads splash.bmp from extras.pak

**Comment by a1batross** [comment]
@nekonomicon extras.pak have no splash.bmp.

splash.bmp doesn't have to be inside PAK at all but it should be fine as well.

@brad86m yes please check them on your older machine.

**Comment by brad86m** [comment]
I need to remove the splash from extras PAK ?

**Comment by TheKingFireS** [comment]
> I need to remove the splash from extras PAK ?

Try remove extras.pak or extras.pk3.

**Comment by a1batross** [comment]
> > I need to remove the splash from extras PAK ?
> 
> Try remove extras.pak or extras.pk3.

If you won't stop recommending harmful actions, I will have to ban you from this and other FWGS repositories.

**Comment by TheKingFireS** [comment]
> > > I need to remove the splash from extras PAK ?
> > 
> > 
> > Try remove extras.pak or extras.pk3.
> 
> If you won't stop recommending harmful actions, I will have to ban you from this and other FWGS repositories.

Alright then.

**Comment by a1batross** [comment]
@brad86m you can open extras.pk3 with any ZIP archive program (like 7-Zip) and try deleting splash.bmp from there.

It shouldn't actually take precedence, that could be a bug.

**Comment by brad86m** [comment]
> @brad86m you can open extras.pk3 with any ZIP archive program (like 7-Zip) and try deleting splash.bmp from there.
> 
> It shouldn't actually take precedence, that could be a bug.

Going to try that now

**Comment by brad86m** [comment]
DONE! Deleted splash from the pk3 and everything is fine.

Thanks for the help guys :)

**Comment by a1batross** [comment]
@brad86m it has some additional files, like default touch buttons textures, WON graphics and fonts.

In the future, it could also have translation files for UI.

**Comment by NTeditor** [comment]
> СДЕЛАННЫЙ! Удалил сплеш из пк3 и все нормально.
> 
> Спасибо за помощь, ребята :)

Hello, could you send "extras.pak" with "splesh.bmp" removed, since none of my archivers could open this file.

Email to send: niko290210@gmail.com
