### ISSUE TITLE
[MOD: Day of Defeat Beta 1.3] Не играет музыка в начале игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1290]
В консоли появляется такая ошибка
```
cl_dodmusic is a privileged variable
```

При вводе в консоль ``cl_filterstuffcmd 0`` музыка начинает играть в начале игры.

**Comment by Vladislav4KZ** [comment]
В этой версии сделано так:
``cl_dodmusic 2`` - воспроизводит музыку из меню выбора команды и класса
``cl_dodmusic 3`` - воспроизводит музыку после спавна игрока


``cl_dodmusic 0`` и ``cl_dodmusic 1`` - не воспроизводит никакую музыку вообще.

**Comment by Vladislav4KZ** [comment]
``cl_dodmusic 2`` - воспроизводит музыку бесконечно, а ``cl_dodmusic 3`` - воспроизводит её один раз, и при её остановке меняет значение квара ``cl_dodmusic`` на ``0``

**Comment by a1batross** [comment]
gamedir у него dod?

**Comment by a1batross** [comment]
Нашел какой-то установщик, там "dod_31".

**Comment by Vladislav4KZ** [comment]
> Нашел какой-то установщик, там "dod_31".

Не путай версии 1.3 и 3.1

Все версии имели когда-то gamedir с названием dod

В установщике DoD Beta 3.1 папку переименовали в dod_31 потому что очевидно, чтобы не заменять файлы в стимовской версии Day of Defeat (ну и чтобы игроки не пытались заходить на сервера имеющие последнюю версию Day of Defeat, когда у игрока стоит другая версия)

**Comment by a1batross** [comment]
В DoD Beta 3.1 квар не контроллируется на сервере, так что добавил только для dod, т.к. установщик для 1.3 найденный с геймбананы устанавливается в папку dod.

https://github.com/FWGS/xash3d-fwgs/commit/8c80d3b85de6f7bd13990b1b0f08d3c989251cb0

В этот массив можно кстати добавлять квары, если они конфликтуют с cl_filterstuffcmd. Я считаю что фильтр stuffcmd нужен в любом случае, так что исключения это наименьшее зло по усложнению движка (который вообще не должен знать о таких вещах), но и сохранению безопасности для клиента.

**Comment by Vladislav4KZ** [comment]
Day of Defeat Beta 1.3 я нашёл и скачал с gamebanana, установщик установил мне в папку ксаша папку с названием **dod**

У меня имеется несколько версий Day of Defeat, названия папок которых я переименовал вручную

Что-то типа dodb13, dodb21, dodb30 ну и dod_31

Возможно ли сделать список исключений для кваров, значения которых может изменять сервер при ``cl_filterstuffcmd 1``?

**Comment by Vladislav4KZ** [comment]
Только написал, и уже увидел что ты уже сделал подобное.

**Comment by Vladislav4KZ** [comment]
А нет, не совсем разглядел, там только для геймдира с названием dod

**Comment by a1batross** [comment]
Пока фильтр захардкожен внутри движка, поэтому с переименованными папками он работать не будет.

Вообще внести бы какой-нибудь конфигурационный файл, который мог бы лежать в basedir, и через него настраивать общие параметры для движка и в том числе этот фильтр. Тем более вопрос такого конфига уже поднимался с @SNMetamorph. Но это что-то новое придётся изобретать. Это стоит обдумать несколько раз, перед тем как такое дело вносить. Механизм extras.pak кстати тоже дофига не надёжный.

**Comment by SNMetamorph** [comment]
> Тем более вопрос такого конфига уже поднимался с @SNMetamorph. Но это что-то новое придётся изобретать. Это стоит обдумать несколько раз, перед тем как такое дело вносить. Механизм extras.pak кстати тоже дофига не надёжный.

Я не очень помню, что ты имеешь ввиду

**Comment by a1batross** [comment]
Я тоже уже не помню. :(
