### ISSUE TITLE
[Build] Проблемы с компиляцией.

### ISSUE THREAD

**Issue by Reemiel** [FWGS/xash3d-fwgs#1304]
Здравствуйте. Второй день я пытаюсь скомпилировать исходный код, но натыкаюсь на проблемы, которые решить не получается.
Всё сделал по инструкции, как и написали. 
Первая проблема: SDL2 not availiable! If you want to build dedicated server, specify --dedicated. Ни 32-битная, ни 64-битная версия не могла обойти ошибку. Эту проблему я обошёл командой --skip-sdl2-sanity-check.
Вторая проблема: Can't find opus submodule. Run `git submodule update --init --recursive`. Написал в Git, но проблема не решилась. На ней я как раз и застрял. Имеются какие-нибудь способы решить её?
ОС: Windows 11, Версия 22H2 (22622.607). Программа: Microsoft Visual Studio 2022.
Прикрепляю лог
[config.log](https://github.com/FWGS/xash3d-fwgs/files/11026389/config.log)

**Comment by nekonomicon** [comment]
Репозиторий клонирован с флагом `--recursive`?
К SDL2 путь указывали?

**Comment by Reemiel** [comment]
> Репозиторий клонирован с флагом `--recursive`? К SDL2 путь указывали?

Репозиторий клонирован, к SDL2 путь указан.

**Comment by a1batross** [comment]
Хорошо было бы разобраться для начала почему не проходит проверка SDL2.

**Comment by a1batross** [comment]
Попробуйте запустить конфигурацию без него, и отослать config.log.

**Comment by Reemiel** [comment]
Хорошо, сейчас.

**Comment by lewa-j** [comment]
`['С:\\SDL2\\include', 'С:\\SDL2\\include\\SDL2']`
`Не удается открыть файл включение: SDL.h: No such file or directory`

**Comment by Reemiel** [comment]
> `['С:\\SDL2\\include', 'С:\\SDL2\\include\\SDL2']` `Не удается открыть файл включение: SDL.h: No such file or directory`

Я подозреваю, что это возникает из-за проблем с правами администратора. Попробую переместить папку в другую директорию.

**Comment by Vladislav4KZ** [comment]
@reemiel а в папке ``C:\SDL2`` случаем не лежит папка с названием SDL2-x.xx.x?

В пути, которого указываешь ты должна лежать папка include

Т.е. в аргументе ты указываешь путь до ``C:\SDL2-2.26.4``, а в самой папке ``C:\SDL2-2.26.4`` должна быть папка include, где лежит ``SDL.h`` и прочие заголовочные файлы.

Чтобы не гадать, не мог ли бы ты сделать скриншот, и показать каким образом и куда ты распаковал пакет SDL2 для разработчиков?

**Comment by Vladislav4KZ** [comment]
Также убедись, что ты скачал именно пакет SDL2 для **Microsoft Visual Studio**

https://github.com/libsdl-org/SDL/releases/download/release-2.26.4/SDL2-devel-2.26.4-VC.zip

Т.е. при сборке на Windows тебе надо скачать архив с названием SDL2-devel-x.xx.x-**VC**, где **VC** означает Visual C

С обычным SDL2-2.26.4.zip это не прокатит, будет ошибка при конфигурации.

**Comment by Reemiel** [comment]
> @Reemiel а в папке `C:\SDL2` случаем не лежит папка с названием SDL2-x.xx.x?
> 
> В пути, которого указываешь ты должна лежать папка include
> 
> Т.е. в аргументе ты указываешь путь до `C:\SDL2-2.26.4`, а в самой папке `C:\SDL2-2.26.4` должна быть папка include, где лежит `SDL.h` и прочие заголовочные файлы.
> 
> Чтобы не гадать, не мог ли бы ты сделать скриншот, и показать каким образом и куда ты распаковал пакет SDL2 для разработчиков?
> 
> Путь к SDL2.dll указывать **НЕ НАДО**
> 
> > Может мне нужно скачать Half-Life SDK?
> 
> Нет

![изображение](https://user-images.githubusercontent.com/128381960/227630559-b9e97586-b0b5-44a6-907f-aeb61706fce7.png)

**Comment by Reemiel** [comment]
> Также убедись, что ты скачал именно пакет SDL2 для **Microsoft Visual Studio**
> 
> https://github.com/libsdl-org/SDL/releases/download/release-2.26.4/SDL2-devel-2.26.4-VC.zip
> 
> Т.е. при сборке Xash3D FWGS для Windows тебе надо скачать архив с названием SDL2-devel-x.xx.x-**VC**, где **VC** означает Visual C
> 
> С обычным SDL2-2.26.4.zip это не прокатит, будет ошибка при конфигурации.

То есть, использовать нужно исключительно devel версию?

**Comment by a1batross** [comment]
devel. В нём уже есть всё, что нужно. Но SDL2.dll скопируешь в папку куда будешь делать install.

А зачем вам вообще собирать движок из исходников, тем более на самую неочевидную для разработки ОС? У нас уже есть автоматические сборки.

**Comment by Reemiel** [comment]
> devel. В нём уже есть всё, что нужно. Но SDL2.dll скопируешь в папку куда будешь делать install.
> 
> А зачем вам вообще собирать движок из исходников, тем более на самую неочевидную для разработки ОС? У нас уже есть автоматические сборки.

Дело в том, что один из модов недавно перевели на этот движок, а я заинтересован ею и хочу протестировать, а вот насчёт автоматических сборок - если честно, я не знал об этом.

**Comment by a1batross** [comment]
Заходишь сюда https://github.com/FWGS/xash3d-fwgs/actions?query=branch%3Amaster 
Выбираешь последнее из списка
Прокручиваешь в самый низ
Скачиваешь файл artifact-win32-i386

**Comment by Reemiel** [comment]
> Заходишь сюда https://github.com/FWGS/xash3d-fwgs/actions?query=branch%3Amaster Выбираешь последнее из списка Прокручиваешь в самый низ Скачиваешь файл artifact-win32-i386

Спасибо. Необходимость в компиляции отпала. Тему закрываю.
