### ISSUE TITLE
[MOD: OpenAG] Исчезает курсор при переключении рендерера в меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1309]
В меню Configuration -> Video -> Video modes при переключении рендерера, исчезает курсор. Проявляется на последнем билде движка скачанного с артефактов сборки GitHub Actions.

**Comment by Vladislav4KZ** [comment]
Проблема решена в коммите: https://github.com/FWGS/xash3d-fwgs/commit/3ccbc7a28cdfcd08981ac583eb1895886e18e647

**Comment by a1batross** [comment]
Баг возможно ещё будет присутствовать при смене разрешения или фуллскрина,
оконного режима.

сб, 25 мар. 2023 г., 10:14 Владислав Сухов ***@***.***>:

**Comment by Vladislav4KZ** [comment]
> Баг возможно ещё будет присутствовать при смене разрешения или фуллскрина,
> оконного режима.

Да, что-то такое было и раньше, но я пока не репортил.
