### ISSUE TITLE
how to build for freebsd?

### ISSUE THREAD

**Issue by hoo694** [FWGS/xash3d-fwgs#131]
i cannot find the so called http downloader for using this on freebsd

**Comment by nekonomicon** [comment]
The same way as for linux.

**Comment by a1batross** [comment]
What do you mean? Can you send waf logs? 

If you're stuck with building, you can look into .cirrus.yml which is used for FreeBSD build testing.

**Comment by nekonomicon** [comment]
@a1batross, I didn't see fontconfig and freetype in .cyrrus.yml.
I think need to upload my ports to github.
Also, testing of builds via poudriere would be better.
