### ISSUE TITLE
FS_LoadImage не загружает кубмапы

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1310]
Кубмапы вида "maps/env/mapname/cube#0" не загружаются. На оригинальном движке нет такой проблемы.
Пока копал, обратил внимание, что функции FS_LoadImage различаются, там что-то менялось.
Кубмапа состоит из 6 файлов tga, cube#0nx.tga и далее с постфиксами ny, nz, px, py, pz.
Подгружается в клиентке игры через LOAD_TEXTURE как cube#0 (стороны должны находиться сами)

**Comment by a1batross** [comment]
Пофиксил в https://github.com/FWGS/xash3d-fwgs/commit/1caa2765312af1fe9cc93676bae3d48aa44f2f0c
