### ISSUE TITLE
Where are the Win32 builds?

### ISSUE THREAD

**Issue by TheFerries** [FWGS/xash3d-fwgs#1311]
I Noticed lately the continous releases dont have any win32 builds to download, where are they? Maybe I'm missing something.

**Comment by TheKingFireS** [comment]
That's normal, Github actions failed to upload moment compilation episode 124.
However you can still download win32 build using action, just click artifact-win32-i386 in https://github.com/FWGS/xash3d-fwgs/actions/runs/4512565159.

**Comment by TheFerries** [comment]
Thanks for the explanation!

**Comment by a1batross** [comment]
Got them back!
