### ISSUE TITLE
В PrimeXT и ксашмоде перестал работать фонарик от первого лица

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1312]
Работает только от третьего.
Такой же эффект от первого лица я наблюдал ранее, если отсутствовала модель player.mdl.
Предпологаю, что могут быть виноваты коммиты
https://github.com/FWGS/xash3d-fwgs/commit/4ada40e8a8aaebeb7d06dc55956a161e1673a1b9
https://github.com/FWGS/xash3d-fwgs/commit/d085c5a84332b262cb2c51e0c30f9879fff641c5

**Comment by Aynekko** [comment]
Если сделать в клиенте ксашмода хак, чтобы CL_IsThirdPerson всегда возвращал 1, то фонарик работает.

**Comment by a1batross** [comment]
Fixed in 2c77f4c5
