### ISSUE TITLE
Ложные срабатывания антивируса на файлы движка

### ISSUE THREAD

**Issue by mihail2245** [FWGS/xash3d-fwgs#1314]
В последней версии Xash 3D [xash3d-fwgs-win32-i386.7z](https://github.com/FWGS/xash3d-fwgs/releases/download/continuous/xash3d-fwgs-win32-i386.7z) я заметил,что при запуске некоторых модов антивирус стал помечать важные dll в движке,как malvare и сносить их,после чего игра не запускается.Использую создание ярлыков со свойствами запуска.Занос папки в исключения не помогает.Кто-то может помочь мне в сложившейся ситуации

**Comment by mittorn** [comment]
Антивирус сам и есть малварь, поражающий иногда не только компьютер, но и пользователя :). Правильным решением было бы его отключить и включать только когда скачиваешь что-то подозрительное
Вообще обычно антивирусы ругаются на неподписанные бинарники. Разумеется, моды никто не подписывал, как и движок

**Comment by a1batross** [comment]
Могу помочь только удалить винду.

**Comment by mihail2245** [comment]
Я сразу знал,что в нём дело.Значит,буду отделываться от такого антивируса вообще

**Comment by mittorn** [comment]
Можешь попробовать добыть подпись (вроде это не сложно делается) и подписать бинариники. Это помогает в большинстве случаев. Просто мы ничего не можем с делать с тем, что какие-то последовательности байт в движке (в котором есть ещё и кастомный загузчик dll) не нравится некоторым антивирусам. Сейчас почти весь софт начинает вызывать smartscreen пока достаточное количество людей не пометит его доверенным у microsoft

**Comment by mihail2245** [comment]
Я вас понимаю.

**Comment by nekonomicon** [comment]
Как вариант можно ещё залить проблемные файлы на virustotal и написать на форум вендора антивирусной программы.

**Comment by 0x4E69676874466F78** [comment]
@mihail2245 какой антивирус-то?

**Comment by mihail2245** [comment]
> @mihail2245 какой антивирус-то?

360 total security стоял. Фуфло полное. На файлы движка при использовании некоторых модов, типа Half-Life Azure Sheep и Cleaner's Adventures помечал dll в корне движка, как, malware. Снёс его нафиг, всё нормально.

**Comment by 0x4E69676874466F78** [comment]
> 360 total security 

Ну да, это днище. https://ru.wikipedia.org/wiki/360_Total_Security
Тогда закрой issue. Снизу кнопка.
