### ISSUE TITLE
Half Life: Zombie Edition almost works, but it don't.

### ISSUE THREAD

**Issue by Lufims** [FWGS/xash3d-fwgs#1321]
I'm using Xash on Android, and I installed that mod, and it opened, but the buttons for new game, options, etc, are missing, and when I enter the game it loads the map and HUD, but I'm Gordon Freeman, not a headcrab, probably is something involving custom player models or scripts, idk.
![Screenshot_20230401-130849](https://user-images.githubusercontent.com/73536178/229301929-bfba9435-ba5c-4048-9723-b703726b64a0.png)
![Screenshot_20230401-130830](https://user-images.githubusercontent.com/73536178/229301954-bdba1a00-f477-4a16-adbd-907357820b80.png)
![Screenshot_20230401-130821](https://user-images.githubusercontent.com/73536178/229301961-b5b4087e-d564-44f9-a027-8596c54ccbbc.png)
![Screenshot_20230401-130805](https://user-images.githubusercontent.com/73536178/229301977-73c552d9-c420-4a62-88e9-e6680af5fe05.png)
![Screenshot_20230401-130757](https://user-images.githubusercontent.com/73536178/229301986-17233959-d7a5-4592-9be1-bbeae43de3d7.png)

**Comment by TheKingFireS** [comment]
That's mod is a Windows exclusive mod...

**Comment by TheKingFireS** [comment]
Next time don't complain about it when it come to Windows mods.

**Comment by Lufims** [comment]
> Next time don't complain about it when it come to Windows mods.

Ah, ok, I didn't know about that, I tried this mod on PC, but my PC sucks because of my windows 10 incompatible Chipset, and I can't use the opengl renderer because of that, anyway, sorry for bothering you.

**Comment by a1batross** [comment]
This mod doesn't support Android.
