### ISSUE TITLE
View server info 

### ISSUE THREAD

**Issue by warperX34** [FWGS/xash3d-fwgs#1323]
При заходе в мастер серверов утилита не работает

**Comment by nekonomicon** [comment]
Какая утилита?

**Comment by warperX34** [comment]
> Какая утилита?

View game info

**Comment by a1batross** [comment]
Пункт в сервер браузере. Он не дописан, надо его сделать.

**Comment by a1batross** [comment]
Done.
![image](https://github.com/FWGS/xash3d-fwgs/assets/3213697/03d06b6c-a962-4a2d-b5cc-7cf92e686107)

Скриншот из WON для сравенения
![image](https://github.com/FWGS/xash3d-fwgs/assets/3213697/0711468a-0bb6-4141-be7b-ecbdfd7b3ec5)
