### ISSUE TITLE
Underwater animation not working

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1325]
https://user-images.githubusercontent.com/76803825/230714059-44a620ae-0fe6-48cb-bd23-43eb49e4cfea.mp4

https://youtu.be/6TlpT5zH3Ic?t=164

**Comment by TheKingFireS** [comment]
Goldsrc doesn't have "underwater animation" either. That's for Quake.

**Comment by Vladislav4KZ** [comment]
iirc it was cut in some xash update

**Comment by TheKingFireS** [comment]
Yep.

**Comment by a1batross** [comment]
What are you talking about? What animation?

**Comment by TheKingFireS** [comment]
> What are you talking about? What animation?

He talking about Underwater Distortion.

**Comment by Vad1mCSO2** [comment]
In 0.19.2 has underwater distorsion

**Comment by TheKingFireS** [comment]
Who would check the old-engine codes? No one.

**Comment by a1batross** [comment]
I can't speak for everyone but I don't think it's worth restoring.
