### ISSUE TITLE
How do I build for Android?

### ISSUE THREAD

**Issue by Litleck** [FWGS/xash3d-fwgs#133]
Hi,
For sometime now I've been using the Xash engine on the Google play store to play half life on my phone. I've only just recently noticed that there's the GitHub page for the newer engine. However I can't seem to find how to build for Android unless there's already a compiled apk.

**Comment by Velaron** [comment]
It's in the readme

![image](https://user-images.githubusercontent.com/53096779/75288621-6503bf00-5825-11ea-9371-b0c4f586bfec.png)
