### ISSUE TITLE
Pathname redundancy

### ISSUE THREAD

**Issue by Flintastic** [FWGS/xash3d-fwgs#1331]
Xash does not locate files in the root of the "media" folder if they are redundantly declared to be in that folder.

For example, in the Field Intensity mod, the song in the intro does not play because it is declared as "**media/gearbox_Half-Life05.mp3**" in the .BSP but Xash tries to find it in "**media/media/gearbox_Half-Life05.mp3**".

**Comment by Vladislav4KZ** [comment]
I reported about a similar thing: https://github.com/FWGS/xash3d-fwgs/issues/592

I also noticed that xash adds the ``media/`` to the mp3 directory path
