### ISSUE TITLE
DELTA_ERROR

### ISSUE THREAD

**Issue by kiryD** [FWGS/xash3d-fwgs#1332]
![Screenshot_2023-04-19-20-44-44-372_in.celest.xash3d.hl.jpg](https://user-images.githubusercontent.com/74090680/233094639-9f54cf7b-915a-4962-82f7-0418680bfdab.jpg)

Can't find delta.lst

**Comment by TheKingFireS** [comment]
Nice pirated HL bro. Maybe check your valve if there is delta.lst.

**Comment by TheKingFireS** [comment]
Nope, look like your valve folder corrupted. ignored my first message.

**Comment by a1batross** [comment]
Reinstall game files from Steam version of the game.
