### ISSUE TITLE
Underwater visual differences

### ISSUE THREAD

**Issue by Flintastic** [FWGS/xash3d-fwgs#1333]
The underwater visuals in Xash are notably different from how they appear in GoldSrc.

![XashUWComp](https://user-images.githubusercontent.com/66497936/233803992-4dd80e80-23e4-4c72-81b1-4ce2d51844b5.png)

Main differences:

- Immediate surroundings are more visible (the wall textures can be discerned).
- Fog appears more abundant and seamless.
- Light flares are as visible above water as they are underwater.

**Comment by a1batross** [comment]
Most of the visual differences comes from incorrect gamma implementation in Xash. Fog may be different due to https://github.com/FWGS/xash3d-fwgs/issues/1188.

We should fix that at some point, but it's not the top priority.

**Comment by a1batross** [comment]
The `kRenderGlow` mode (light flares you're referring to) should be straightforward to fix.

**Comment by a1batross** [comment]
Fog in VBO mode might be slightly different (it's nearly impossible to make it look like in original)

but without VBO it must be fine since I reworked fog earlier this year
