### ISSUE TITLE
Cursor escapes the screen in notch devices as the video doesn't extends to the notch area. 

### ISSUE THREAD

**Issue by Lion4K** [FWGS/xash3d-fwgs#134]
I have a Motorola One Zoom device (XT2010-1) and when playing the video doesn't extends to the full screen, more precisely the area of the notch is ignored.
My screen resolution is 2340x1080.
I tried setting the resolution over command line using goldscr commands but didn't worked.
The issue is that when playing with mouse when you drag the mouse to left (or right, depending on the orientation) when the cursor hits the area without video the cursor escapes the play area and the camera stops turning, so you can't turn 360 in that direction.

In discord someone mentioned "safe mode" but didn't know how to, and he and I kinda agree on the resolution so maybe it will fix? In such case how do I change to my resolution?

Or if it's totally wrong, is there a way to fix?

**Comment by a1batross** [comment]
I guess, it's Android? You can't really change resolution on Android through the engine. What Android version do you have? For normal mouse play, you need to have at least Android 7.0 or root access.

Are you running new engine or old version from Google Play?

**Comment by Lion4K** [comment]
Yes, sorry I didn't specified the Android version, it's 9.0 Pie.
Yes the Google Play Store version.

**Comment by a1batross** [comment]
Yep, there is a bug in old engine that doesn't allow to use whole screen on
devices with aspect ratio bigger than 18.5:9, and you have 21:9.

The only workaround is to check if your firmware has setting to override
max aspect ratio. It varies from device to device so I can't point you
where this setting should be.

**Comment by Lion4K** [comment]
Yeah actually 21.5 by 9.

Will the new engine fix that?
Is there a compiled binary I could test, I mean enroll as tester.

By now I've figured that if I disable the notch in developer settings it fixes the issue, but that's not optimal in any way.

**Comment by a1batross** [comment]
You can try to download testing version from https://github.com/FWGS/xash3d-deploy/blob/anewengine-master

Yeah, it should be fixed here. I've set max aspect that high so it will use all available screen space, even if Android would be installed on toilet paper.

**Comment by Lion4K** [comment]
Like when they released iPhone 5 and ppl joked about the light saber long iPhone 20

**Comment by Lion4K** [comment]
Btw the link didn't worked.

**Comment by nekonomicon** [comment]
Right link: https://github.com/FWGS/xash3d-deploy/tree/anewengine-master

**Comment by Lion4K** [comment]
So yeah, I tested the APK, I didn't knew which one was the best so I figured the 64 one because my device is aarch64 or so say uname, anyway, I tested the video options and all I managed was to get a smaller screen, so I reverted back to old engine and since the other notch partial fix enables me to play I'm sticking with it.
Thanks !!
