### ISSUE TITLE
Уязвимость, позволяющая расскрывать реальный IP-адрес игрока.

### ISSUE THREAD

**Issue by unnamed25** [FWGS/xash3d-fwgs#1342]
Проблема достаточно серьёзная и я не знаю, исправлена-ли она в актуальных билдах Ксаша, поэтому написал сюда.
В общем, в движке есть какая-то уязвимость, позволяющая игрокам расскрывать реальные IP-адреса других игроков, даже если расскрывальщик не имеет доступа к серверу и даже если игрок, IP которого пытаются расскрыть, находится за VPN.
По крайне мере мне известно пока только 2 таких случая, но к сожалению я не могу пока разобраться, через какие именно механизмы движка происходит расскрытие реального IP игрока.
Если-же это уже исправлено - тогда извиняюсь и я в таком случае закрою этот issue.

**Comment by a1batross** [comment]
Ну то есть где-то есть, но неизвестно где и на этом все. Была ошибка с
чтением квара где хранится IP, но я эту проблему давно решил. Да и это
всего-то IP адрес, что от него такого будет?

Записывай демки. На каждую игровую сессию тогда.

**Comment by AndrewOculus** [comment]
@unnamed25 удалось ли выяснить какие то подробности? тоже пришел к выводу, что данные утекают - на сервер может заходить игрок, который просто пишет в чат ip остальных игроков.

**Comment by SNMetamorph** [comment]
А это случайно ли не какая-то консольная команда по типу `status`?

**Comment by a1batross** [comment]
>даже если игрок, IP которого пытаются расскрыть, находится за VPN.

Вот это особенно похоже на какие-то сказки.

**Comment by mittorn** [comment]
"ДА Я ТЕБЯ ПО IQ ВЫЧИСЛЮ"

**Comment by Vladislav4KZ** [comment]
@unnamed25 при онлайн игре в ксаш ты же ведь не всегда используешь VPN?

Есть вероятность, что он просто записал твой реальный IP-Адрес ещё до того, как ты начал использовать VPN.

**Comment by Vladislav4KZ** [comment]
Можешь написать название сервера и никнейм игрока, который сливал IP? Если конечно помнишь.

Может это админ так троллит 🤷🏻‍♂️

**Comment by hypeq** [comment]
Я тоже видел, как такое проворачивают. 
Не забываем, что сервер видит айпи адрес игрока когда тот даже не заходит на него, а просто посылает пакет для получения информации о сервере.
Я думаю что эти вещи как минимум могут привести до такого, как максимум до еще худших последствий.
Полагаю, что стоит переписать мастер сервер, чтобы тот сам запрашивал информацию у серверов и отсылал клиентам, так хотя-бы айпи случайного игрока можно скрыть.
P.S. я не из тех кто боится раскрыть свой динамический айпи, хоть я и постоянно туннелирую свой траффик :)

**Comment by SNMetamorph** [comment]
> Полагаю, что стоит переписать мастер сервер, чтобы тот сам запрашивал информацию у серверов и отсылал клиентам, так хотя-бы айпи случайного игрока можно скрыть.

Вообще бессмысленно. Отправит мастер список клиенту, а часть серверов клиенту просто недоступна, например, из-за блокировок провайдера. Ну и отображения пинга не будет.

**Comment by Velaron** [comment]
> Отправит мастер список клиенту, а часть серверов клиенту просто недоступна, например, из-за блокировок провайдера. 
Ну такое кстати довольно часто встречал при игре на GoldSrc, я наоборот считаю что такой вариант правильней, чем вообще не знать о существовании серверов, но вряд ли птичка такое реализует.

**Comment by a1batross** [comment]
Представим что конфигурация сети такова:

192.168.0.1 <- ваш компьютер
198.51.100.1 <- выданный провайдером внешний IP адрес
203.0.113.1 <- адрес вашего VPN сервера. 

Весь трафик проходит через провайдера, а затем к VPN. Весь Интернет должен видеть ваш IP адрес как адрес VPN сервера, то есть 203.0.113.1.

Теперь давайте подумаем, как вообще работает сеть в движке:
* Движок при включении сети по умолчанию даже не знает IP адрес. Квар "ip" равен "localhost", это специальный случай, где движок не пытается через DNS службы ОС отрезолвить имя в адрес. Если вы передали `-ip` движку, адрес он не меняет, он только помогает правильно маршрутизировать в случае если у вас несколько сетевых карт. Если в нашем случае туда передавать что-то из адресов выше, то ОС их просто не даст за-bind()-ить. Можно передать 0.0.0.0, тогда он будет слушать "на всех адресах", но отправка всё равно происходит через адрес VPN.

* Движок в общем случае не знает ваш IP адрес, пока вы ему не передали `-ip` о чём я написал выше. То что видно адрес VPN это не баг. Если вы не используете VPN и кто-то в чате вам написал ваш внешний IP адрес выданный провайдером, это тоже не баг. Так работает Интернет, это норма.

Что я вижу в этом репорте:
* Вы утверждаете, что каким-то образом используя VPN кто-то всё равно узнает IP адрес провайдера.
* При этом при правильной настройке сети такое сделать затруднительно. Да, о случаях утечки известно через WebRTC и DNS, но WebRTC у нас не используется, а DNS нужен только для преобразования адреса мастер-сервера.

Я не вижу здесь возможного вектора атаки. Так же я не вижу смысла что-то обсуждать, когда дискутирующие сами определиться не могут, а где всё же баг и уязвимость, где вместо доказательств только рассказы бабки у подъезда. И дабы избежать дальнейшего протекания FUD, я эту ишшую закрываю. Как будет что-то интересное, можете просто создать новую ишшую.
