### ISSUE TITLE
build randomly stops

### ISSUE THREAD

**Issue by XEN486** [FWGS/xash3d-fwgs#1344]
I run waf build, and after a bit of processing it just stops compiling and exits back to the terminal, no idea why, it doesn't show anything

**Comment by a1batross** [comment]
Can you post any detailed info?

**Comment by XEN486** [comment]
![image](https://user-images.githubusercontent.com/54139784/235353990-c31a3bec-d407-4069-af28-f292c328bb3f.png)
well this is a screenshot of the terminal, it's like I pressed control+c but I didn't

**Comment by a1batross** [comment]
That's weird. Never happened to me before on Windows.

Do you have enough RAM to run a build? What if you will run it in single thread (`waf build -j1`)? Maybe there is something useful in verbose mode (`waf build -v`)?

**Comment by a1batross** [comment]
If build fails for you, you can absolutely take the prebuilt version from Releases page: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

In most situations, you don't have to modify the engine, so compiling it from source is nearly worthless.

**Comment by XEN486** [comment]
hello, thanks for your quick reply! turns out, I just needed to restart my computer and it worked fine, sorry for wasting your time.
