### ISSUE TITLE
[MOD: HL1MMod] Game crashes upon firing a weapon.

### ISSUE THREAD

**Issue by Falderal-4250** [FWGS/xash3d-fwgs#1345]
**Screenshot:**
![Screenshot 2023-04-30 030409](https://user-images.githubusercontent.com/55860298/235347546-beea52b6-ec49-455e-9979-4184ef15c569.png)

**Engine Log:**
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/11361059/engine.log)

**Steps:**
1. Load up HL1MMOD (3/20/2023 update) in Xash3D FWGS Continuous (Updated 4/30/2023, release 2 - 3hrs as of writing).
2. Use any of the projectile-based weapons (handgun, shotgun, SMG, etc.)
3. Instantaneous crash, engine loops last played audio.

**Architecture:**
Windows 11 Home 64-bit (10.0, Build 22621)

**Summary:**
I don't know how long the issue has existed for, only that as I tried to play HL1MMOD on Xash3D FWGS it would lead to this crash. 

Checking the patch notes under the 3/20/2023 update, it makes mention of:
> Reworked how the game pre-caches visual effect sprites, this might introduce one time millisecond long micro-stutters, but might alleviate random crashes during long play.

_Source: Half-Life 1: MMod Update Released! on store.steampowered.com news section._

Could this possibly be related to the crash? I'm just wagering a guess at this point.

**Sources:**
1. [Half-Life 1: MMod Update Released!](https://store.steampowered.com/news/app/1761270/view/3708190655192203291?l=english)

**Comment by Vladislav4KZ** [comment]
Retest on the latest engine build.

I don’t experience any crashes when shooting with the weapons described above.

**Comment by a1batross** [comment]
Tested latest available HL1MMod, seems to be working fine
