### ISSUE TITLE
Некорректно записываются/воспроизводятся демо

### ISSUE THREAD

**Issue by genabetov** [FWGS/xash3d-fwgs#1348]
Отсутствуют некоторые звуки и анимации, зависают партиклы и гильзы в воздухе.

**Версия:** 
0.20 linux-amd64 build 2873

**Видео:** 
https://www.youtube.com/watch?v=QZpjA-lr6Tk

**Демо:** 
[t.dem.tar.gz](https://github.com/FWGS/xash3d-fwgs/files/11414395/t.dem.tar.gz)

**Comment by a1batross** [comment]
Проиграл демку на текущей версии, всё работает должным образом.

Не знаю когда конкретно было исправлено.
