### ISSUE TITLE
-game gearbox fails (Arch Linux)

### ISSUE THREAD

**Issue by hansnull** [FWGS/xash3d-fwgs#135]
Hi everyone,
can't start Opposing Force from Arch Linux, error:
`Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory`
Without the "-game" parameter Half-Life is loaded and works.
Any help appreciated.

**Comment by nekonomicon** [comment]
Do you have vgui.so beside gearbox folder?
Also, try to choose Opposing Force in Custom game menu section.

**Comment by hansnull** [comment]
The vgui.so is located in the parent directory of the gearbox folder.
Opposing Force is not listed within the custom game menu section.

**Comment by a1batross** [comment]
`LD_LIBRARY_PATH=. ./xash3d ...`

We had xash3d.sh that set LD_LIBRARY_PATH before and passed arguments to the engine but I didn't bothered about it because wanted an alternative solution like AppImage. But AppImage suck so hard that even Snap looks better in comparison so probably I will revert everything like it was in old engine.

**Comment by hansnull** [comment]
Tried:
`LD_LIBRARY_PATH="/usr/lib/xash3d:." xash3d -game gearbox`
same error

**Comment by hansnull** [comment]
Tried that also, did not work. But I got it working: I copied everything from the gearbox folder into the valve folder and started xash3d... Opposing Force is running :smile:

**Comment by hansnull** [comment]
What is also working: Just copy the cl_dlls folder from valve to gearbox.
Tested Opposing force now some hours: The desert eagle does not show the reloading animation, the fire sound is missing and the decals. Tried to use a "mod", but is also not working.

**Comment by nekonomicon** [comment]
Do you use WON HL?

**Comment by hansnull** [comment]
No, it is the version from Steam.

**Comment by mittorn** [comment]
maybe gearbox client use vgui2 like bshift?

**Comment by a1batross** [comment]
@mittorn no, it is not

**Comment by hansnull** [comment]
My gearbox cl_dlls folder contains:
client.dll
client.dylib
client.so
The valve cl_dlls folder contains:
gameui.so
particleman.so

**Comment by Toromino** [comment]
I am getting the same error message `Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory` on Void Linux

There is no vgui.so in gearbox, valve or bshift. (I copied the Linux versions of the games from Steam)

**Comment by Velaron** [comment]
> The vgui.so is located in the parent directory of the gearbox folder.
