### ISSUE TITLE
Streaming on Discord breaks when text from titles.txt is displayed

### ISSUE THREAD

**Issue by sanscriptum** [FWGS/xash3d-fwgs#1350]
Version: win32-i386 build 2951
Render: OpenGL, desktop screen size
OC: Win7

Running in a windowed mode, as it's required for the stream to be even seen. Everything works as normal, until the game shows the "Saved..." text or the chapter's title at the bottom, then the screen goes black on stream or/and flickers and the application must be restarted to fix it. The titles being shown seems to be the easiest way to reproduce it, and removing "Saved..." text from titles.txt was my temporary solution, but the chapter titles are displayed regardless.

It understand it might be a very niche problem, but it'd be nice to get it fixed, as hl.exe works without a hitch on this setup.

**Comment by a1batross** [comment]
Must be fixed since 68ff265e8d5f2d52ba0761f78e645cf0df445acf and 1d965d75432a3d1d7f456d808a5d80dba4993e75
