### ISSUE TITLE
Game text disappears too soon

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#1356]
Here's a map with the example of game_text entity configuration where the text disappears almost immediatelly on Xash3D engine, while holds as expected on GoldSource.
[gametext.zip](https://github.com/FWGS/xash3d-fwgs/files/11473093/gametext.zip)

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/04107d384e31eba5ee5a06f8316daee45da023f3 fix
