### ISSUE TITLE
[MOD: Counter-Strike 1.6] Если в начале аудиофайла находится буква n или t, то бот не сможет его воспроизвести

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1361]
Если в начале названия файла будет буква n, то в консоли, при появлении предупреждения об несуществующем файле, продолжение названия файла будет писаться с новой строки.

Этот баг проявился когда бот хотел сказать nice shot, но звук не воспроизвёлся

В консоли появилось такое предупреждение:
```
Warning: FS_LoadSound: couldn't load "sound/radio/bot
ice_shot2"
```

Тоже самое, если в начале названия будет буква t

Только вместо перехода на новую строку, будет отступ

Используется тестовая CS16Client для Windows:
https://github.com/Velaron/cs16-client

Версия YaPB: v4.4.841 (скачанная с артефактов GitHub Actions)
https://github.com/yapb/yapb

**Comment by a1batross** [comment]
This probably was fixed by https://github.com/FWGS/xash3d-fwgs/commit/5627dbbf3410ce9fe7ed26a935198a16591e89e5 too

**Comment by Vladislav4KZ** [comment]
Да, теперь исправлено.
