### ISSUE TITLE
Если в чате писать символ \n, то символы написанные после него будут перенесены на новую строку

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1362]
Тоже самое и с \t, если его ввести в чате, и за ним другие символы, то перед ними будет отступ.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/5627dbbf3410ce9fe7ed26a935198a16591e89e5

Но это потенциально может сломать что-то ещё, хотя навскидку не могу сказать что.
