### ISSUE TITLE
[Win32] Sys_Crash error booting vanilla Steam release of Blue Shift

### ISSUE THREAD

**Issue by FreshRoyal** [FWGS/xash3d-fwgs#1372]
![image](https://github.com/FWGS/xash3d-fwgs/assets/77604559/bbaa7e6f-54e2-43f5-8f99-480d9a2f84b7)

**Comment by nekonomicon** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md
