### ISSUE TITLE
Why does XASH3D_BASEDIR need that?

### ISSUE THREAD

**Issue by DeafMan1983** [FWGS/xash3d-fwgs#1373]
Hello everyone,

I have big problem with Linux x64 ( 64 Bit )
How do I run if It doesn't work for me :/ I already copy valve to $HOME/Xash/valve then it won't load why...
![image](https://github.com/FWGS/xash3d-fwgs/assets/57066679/a3722f36-10b3-4e53-9054-855d6a46bcfb)

I don't understand :( 
I show if it is correct or wrongly?
![image](https://github.com/FWGS/xash3d-fwgs/assets/57066679/103f2efe-ff69-4480-bd6b-7ef45cabd1c7)

Please tell me what is XASH3D_BASEDIR?

I use Ubuntu 22.04.1 64 Bit unpacked from AppImage

**Comment by a1batross** [comment]
XASH3D_BASEDIR is an environment variable that sets the working directory for the engine.

Huh. SetCurrentDirectory shouldn't fail or even crash like that.

**Comment by DeafMan1983** [comment]
Working directory is /home/jens/xash but nothing why does it happen if I get error message.  How do I fix?

**Comment by a1batross** [comment]
It's probably our bug. :)

**Comment by DeafMan1983** [comment]
Lol I found XASH3D_BASEDIR=.
Then it happens couldn't load cl_dlls/client_amd64.so but I copied from AppImage amd64 with wrong 32 Bit Eh???

**Comment by a1batross** [comment]
@DeafMan1983 yeah, there is a NOTE in a readme.

You can't run Half-Life (or any mods) in 64-bit mode, because 64-bit mode is only our extension, nor GoldSrc, nor original Xash3D supports it.

You need 32-bit AppImage (or use Flatpak, it's compiled only in 32-bit for now) or compile 64-bit binaries from https://github.com/FWGS/hlsdk-portable.

**Comment by DeafMan1983** [comment]
Oh no I thought Xash3D uses 64 Bit - I expected Russian developers compile into amd64 But I already coped from Steam Half-Life but without cl_dlls and dlls and I have downloaded xash3d-fwgs_amd64.AppImage means it all in 64 Bit not in 32 Bit. 

You mean I should compile Half-Life SDK 2.4 into amd64? Is it correctly?

**Comment by a1batross** [comment]
> I thought Xash3D uses 64 Bit - I expected Russian developers compile into amd64

Well, original doesn't. We do, except there are still no prebuilt binaries available.

>But I already coped from Steam Half-Life but without cl_dlls and dlls

You better go back and copy with cl_dlls and dlls folders.

>Half-Life SDK 2.4 into amd64

Half-Life SDK 2.4 doesn't support amd64 either, it just won't build. Only our SDK fork does.

**Comment by DeafMan1983** [comment]
Okay thanks sorry I hesitate much because I feel like because I want port client and server into C# but Dotnet doesn't support for 32Bit like linux-x86 that is why I expected xash3d-fwgs has amd64 that is why. Thank you for unsupported architecture #1256 

I wish you great day and say thanks enjoy your development with Xash3D :)
