### ISSUE TITLE
bug on create server on advanced settings cvars

### ISSUE THREAD

**Issue by LambdaLuke87** [FWGS/xash3d-fwgs#1375]
The configuration of checking, unchecking, and selecting advanced server options related to cvars has many bugs, for example when checking an option the next time you create an server game the marked box turn deselected and cant be re-enabled unless you restart the game, and among other bugs that I don't know how to describe them well, sorry

**Comment by Vladislav4KZ** [comment]
I have already reported on this:
https://github.com/FWGS/xash3d-fwgs/issues/509

**Comment by Vladislav4KZ** [comment]
Closing as a duplicate.
