### ISSUE TITLE
[They Hunger] Flamethrower witouth fullbright

### ISSUE THREAD

**Issue by LambdaLuke87** [FWGS/xash3d-fwgs#1377]
The flame sprite no have fullbright so in some darker maps areas are darker, that only happen in xash3D cause in normal version is always fullbright like the hitbody blood sprite

PD: if this is read by FreeSlave, hi mate how have you been, so long... ok no kidding I just spoke to you 3 seconds ago in DS Xdddd

![sos](https://github.com/FWGS/hlsdk-portable/assets/119668406/c57d6287-1618-49d5-9a9c-6a23f517acdd)

**Comment by a1batross** [comment]
It can be disabled with `r_sprite_lighting` set to 0.
