### ISSUE TITLE
Can't see input in the console on Android

### ISSUE THREAD

**Issue by phunni** [FWGS/xash3d-fwgs#1378]
I'm running Xash3D on Android on my Retroid Pocket 3+ and it seems to run well, except that, when I open the console, the keyboard obscures half the console - including the bit where I input commands. It means I have to try and enter a command, then hit enter several times just to see the ouput.

Any advice on preventing the keyboard obscuring the console?

**Comment by a1batross** [comment]
Are you running @Velaron's new port?

Old Engine port had window resize on keyboard popping up, something similar should be implemented here as well. Maybe even without resizing the whole window, just shifting console text up?

As a temporary workaround, you can load a game, and then open a console where it takes 50% of the screen. Or use a keyboard that support transparency, like Hacker's Keyboard.

**Comment by phunni** [comment]
I've been running the version on Google Play: [](https://play.google.com/store/apps/details?id=su.xash.engine) - should I be running the new port? I'm assuming so...

**Comment by a1batross** [comment]
Yeah, it's the new port.

**Comment by phunni** [comment]
Can't get the apk from the latest release to install. Trying to download and install just says: "not installed" and trying an adb sideload fails with:

`db: failed to install xash3d-fwgs-android.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl149363372.tmp/base.apk: Failed to collect certificates from /data/app/vmdl149363372.tmp/base.apk: Attempt to get length of null array]`

**Comment by Velaron** [comment]
It's not signed yet, I only started working on CI recently

**Comment by phunni** [comment]
Ah - so that's not the one to run just yet then?

**Comment by Velaron** [comment]
APKs should be signed now and I resolved the issue, console should now be always exactly above the keyboard

**Comment by AruMoon** [comment]
> How to download latest version cuz I tried to download google play version and I load up xash folder and it does not want to work can anyone help me with this or can ya show me how to get the app in this place.

Select valve folder, not xash

**Comment by Vladislav4KZ** [comment]
This issue has already been fixed.
Even according to these posts:

> APKs should be signed now and I resolved the issue, console should now be always exactly above the keyboard

> Brilliant - thank you!
