### ISSUE TITLE
Setgl texgamma " " command does not work

### ISSUE THREAD

**Issue by Nextone7777** [FWGS/xash3d-fwgs#1380]
I noticed that on the old Xash 0.19.2, if you write in opengl.cfg, for example, the setgl texgamma "3.0" command, then after loading on the map all the textures will be a little brighter, unlike the standard gamma. And as for me, this picture looks better, than the standard gamma in the game settings, but for some reason this command does not work on the new Xash 0.21. And here are the screenshots difference 1) vs 2)
![Screenshot_2023-06-05-14-29-25-725_in celest xash3d hl](https://github.com/FWGS/xash3d-fwgs/assets/130932444/e78d1982-8cee-4074-bb3a-60ea0d9418db)
![Screenshot_2023-06-05-14-39-16-943_in celest xash3d hl](https://github.com/FWGS/xash3d-fwgs/assets/130932444/169e7667-5928-4f91-91d5-a315f44bec36)

**Comment by a1batross** [comment]
texgamma was replaced by both gamma and brightness cvars.

**Comment by Nextone7777** [comment]
> texgamma was replaced by both gamma and brightness cvars.

In my opinion the early Xash 0.19 ability to use the setgl command was a good idea rather than just changing the gamma and brightness in the game settings which is not enough for android version and these gamma and brightness settings in general don't exactly give the same effect to the game as shown on screenshot 2. Can you return this command for new Xash on android?

**Comment by a1batross** [comment]
Our gamma implementation isn't accurate anyway and will be rewritten to match GoldSrc at some point.
