### ISSUE TITLE
Клиент не видит dds изображения

### ISSUE THREAD

**Issue by huigrunt** [FWGS/xash3d-fwgs#1387]
У себя в моде я на клиенте использую gRenderfuncs.GL_LoadTexture для загрузки тектсур из RenderAPI соответсвтвено. В билде 2956 всё нормально, грузит и отрисовывает без нареканий. А вот в билде 3001 всё как то печально. В место тектсуры виньетки мы имеем эмо текстуру(
![Metro Redux Screenshot 2023 06 20 - 01 39 14 41](https://github.com/FWGS/xash3d-fwgs/assets/90998299/9a002aaa-18cf-4e41-9ba3-f94d544383ee)

**Comment by Aynekko** [comment]
У меня в XashXT все работает. Может это как-то связано с коммитом https://github.com/FWGS/xash3d-fwgs/commit/68ff265e8d5f2d52ba0761f78e645cf0df445acf
Тебе нужно показать как ты рендеришь виньетку.

**Comment by a1batross** [comment]
Скинь лог движка запущенного с -dev 2 -log

**Comment by huigrunt** [comment]
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/11795582/engine.log)

**Comment by huigrunt** [comment]
А вот так рисую:

**Comment by a1batross** [comment]
[2023:06:20|13:43:40] Warning: FS_LoadImage: couldn't load "/gfx/fx_vignette"
[2023:06:20|13:43:40] Warning: FS_LoadImage: couldn't load "/gfx/ui_blood2"


Что-то со слешами в начале небось. Надо исправить, раз уж раньше работало

**Comment by huigrunt** [comment]
Ну в билде 2956 всё нормально же

**Comment by Aynekko** [comment]
> "/gfx/fx_vignette"
Вот так я никогда не делал, слеш в начале не нужен.

**Comment by huigrunt** [comment]
> > "/gfx/fx_vignette"
> 
> Вот так я никогда не делал, слеш в начале не нужен.
Прикол, не знал. Просто что удивительно в старом билде это слеш никому не мешал.

**Comment by a1batross** [comment]
Должно быть исправлено с https://github.com/FWGS/xash3d-fwgs/commit/5a4c443c790b6c1b3f31eb6a6d3ac10222571b3e
