### ISSUE TITLE
Possibility of making more than 3 quicksaves

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1389]
Right now, you can make only 3 quicksaves. The 4th one will delete the oldest one. I propose to increase the limit of SAVE_AGED_COUNT from 2 to something else, or better yet, add it to gameinfo for modders to change.

**Comment by a1batross** [comment]
I think having gameinfo.txt key would be sufficient.

With the proper UI quick saves won't clutter manual and auto saves.

**Comment by a1batross** [comment]
It's now possible to control it with `autosave_aged_count` and `quicksave_aged_count` keys in gameinfo.txt.
