### ISSUE TITLE
[MOD: Counter-Strike 1.6] Не работает повторная закупка гранат и прибора ночного видения

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1391]
Проверял на ксаше, собранного с ветки **new_vgui_support_api**

Используются оригинальные client.dll и mp.dll от последнего стимовского билда Counter-Strike 1.6

На ксаше, повторная закупка гранат и прибора ночного видения (с помощью команды rebuy, которая по умолчанию привязана на клавишу F2), работает только при использовании ReGameDLL, в то время как на GoldSource, это работает с использованием и оригинальной серверной библиотеки.

**Comment by a1batross** [comment]
rodir случаем не используешь?

**Comment by Vladislav4KZ** [comment]
> rodir случаем не используешь?

Я даже не знаю как он на винде работает.

Где-то читал, но уже забыл.

**Comment by Vladislav4KZ** [comment]
Запускал ксаш через эмулятор стима revEmu (так как запуск ксаша напрямую не работает).

**Comment by Vladislav4KZ** [comment]
Ну и в конфиге rev.ini, указан исполняемый файл ксаша ``xash3d.exe`` с аргументами ``-dev 2 -log``

**Comment by Vladislav4KZ** [comment]
Повторная покупка гранат и прибора ночного видения работает с использованием оригинальной серверной библиотеки на ксаше, только когда покупаешь их с помощью команд в консоли:

```
hegren - Взрывающаяся граната
sgren - Дымовая граната
flash - Ослепляюющая граната
nvgs - Прибор ночного видения
```

Когда покупаешь их в магазине, а не с помощью консольных команд, то их повторная закупка не работает.

Опять же, проверял с использованием оригинального клиента и сервера кс 1.6, а не связка CS16Client + ReGameDLL

Ну и соответственно, я эту issue завёл, потому что такая же проблема проявляется и с использованием CS16Client с оригинальной серверной библиотекой.

**Comment by Vladislav4KZ** [comment]
Я выяснил в чём была причина.

Повторная закупка гранат и прибора ночного видения, не работает в случае использования текстового меню магазина оружия.

Если покупать гранаты и прибор ночного видения в магазине с графическим интерфейсом, то в этом случае, их повторная закупка работает.

Проверено на GoldSource.

**Comment by a1batross** [comment]
Верно, текстовое меню отправляет команды слотов оружия. 

Графическое меню же меню как раз отправляет эти команды.
