### ISSUE TITLE
[14:40:02] Host_InitError: can't initialize cl_dlls/client_amd64.so: Failed to find library cl_dlls/client_amd64.so cl_dlls/client_amd64.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OrionW06** [FWGS/xash3d-fwgs#1396]
Hello!

I have downloaded the amd64 appimage from the latest build, and when I try to run the modern steam version of HL I get the error message in the title.

I am running Pop!_OS 22.04 LTS with kernel version 6.2.6, any ideas of how I can fix this? I have not attempted any fixes since I don't really have any clue what I am doing.

As expected, the file doesn't exist in valve/cl_dlls in both steam and Xash.

**Comment by Velaron** [comment]
Steam version is 32bit only, use 32bit engine or compile hlsdk-portable

**Comment by a1batross** [comment]
Read the comment above ^
