### ISSUE TITLE
hello i have a problem with this progam its that the console wont work and i am on mac using wine i need to use the console commands those anyone know

### ISSUE THREAD

**Issue by Saadsraidi** [FWGS/xash3d-fwgs#1400]
help will be appreciated

**Comment by Saadsraidi** [comment]
dont worry i found out how

**Comment by a1batross** [comment]
Pass -dev or -console to the command line arguments.

**Comment by clafloy** [comment]
> Pass -dev or -console to the command line arguments.

Do you put it under launch options in steam?
