### ISSUE TITLE
Текстура по какой-то причине имеет флаг luma, а в голде нет

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1401]
В ванильном ксаше точно так же.
Прикрепляю bsp и wad
[Desktop.zip](https://github.com/FWGS/xash3d-fwgs/files/12195653/Desktop.zip)

**Comment by a1batross** [comment]
Сильно ли это критично?

**Comment by Aynekko** [comment]
В общем-то нет. Если в каких-то модах никто на такое не жаловался, то и ладно. Я уже на своей стороне решил проблему. Закрою.
