### ISSUE TITLE
Cant seem to run Half life using xash3d-fwgs on the vita

### ISSUE THREAD

**Issue by SimonPhilpott** [FWGS/xash3d-fwgs#1407]
So I've followed this guide exactly.

https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/psvita.md

I've installed libshacccg.suprx, and double confirmed it with PIB Configuration Tool.

I've installed kubridge.skprx and referenced it in my config.

This is my first install of xash3d-fwgs so I've not had any legacy old version to worry about. Copied over to ux0:tai and installed using xash.vpk. I downloaded the latest zip from here. 

The data folder is correctly showing a xash3d folder which contains the contents of the data.zip (i.e. the data\xash3d folder is populated with the right initial files) and the valve folder from the original game (no overwritten content when copying over)

When I run Xash3d it opens to a black screen for less than a second and then closes, I don't see the menu like I'm supposed to.

**Comment by a1batross** [comment]
cc @fgsfdsfgs @SNMetamorph

**Comment by fgsfdsfgs** [comment]
What did you copy to `ux0:tai`?

**Comment by SimonPhilpott** [comment]
Right. Figured it out.

I missed that the latest version of Xash3d was the multiplayer fix, not V4.

Installed and everything works now.

**Comment by SimonPhilpott** [comment]
Fixed by installing the Multiplayer update version. Not V4.

**Comment by fgsfdsfgs** [comment]
That's vitaXash3D, that's ancient. This repo is for the new version, the PSVita builds are in the same continuous release as for all the other platforms.
