### ISSUE TITLE
Can't get past the train ride on Android

### ISSUE THREAD

**Issue by Destroyer5150** [FWGS/xash3d-fwgs#141]
Like the topic says. And also, the robot arm that's welding in the beginning shoot's out light beams. And the tunnel that crash's the game has a light beam problem 90% of the time. Can't find a work around. 
On an S9 Adreno Oreo.

**Comment by nekonomicon** [comment]
Do you use test version from [here](https://github.com/FWGS/xash3d-deploy/tree/anewengine-master)?

**Comment by a1batross** [comment]
Also, do you use Steam version of the game?

**Comment by Destroyer5150** [comment]
What version is best?

**Comment by nekonomicon** [comment]
@Destroyer5150 Can you answer our questions?

**Comment by Destroyer5150** [comment]
Sorry world has gone crazy 😪 The problem is on the new engine (red icon) with both steam and non steam. Old engine has run just fine for me for the last year. And I always use the latest release. And just found another odd thing, it creates folders even for txt files. Old engine didn't do that.

**Comment by Destroyer5150** [comment]
And I've used both test build's for new engine (test 64 - non test 64

**Comment by Destroyer5150** [comment]
It's fixed in the latest release. Still got graphical bugs with some lights looking solid, coffee steam looking solid, lots of glass is not properly transparent. Load/save game box turn's completely white with no text, and the whole screen turns white sometimes when quitting with nothing but the version info on bottom right corner. 
And a problem with all versions is if I don't hide the navigation bar before playing, the buttons are off as in I have to press a little left of any button for it to work. 
Overhaul pack works. 
Patiently waiting for CS 1.6 to work
Good job and thank you.

**Comment by a1batross** [comment]
Does it happens with GLES1 or GLES2 renderer?

**Comment by Destroyer5150** [comment]
2 far as I know. Only way I know how to switch is in game menu and that just crash's

**Comment by a1batross** [comment]
Was moved to #163
