### ISSUE TITLE
Can't start up Blue Shift, Counter-Strike, Counter-Strike: Condition Zero, and Day of Defeat

### ISSUE THREAD

**Issue by Gorilli09** [FWGS/xash3d-fwgs#1410]
Whenever I start those games, they receive an error message.

**Comment by mittorn** [comment]
Steam interfaces are not supported

**Comment by Gorilli09** [comment]
> Steam interfaces are not supported

That's what the error message told me

**Comment by mmillar-bolis** [comment]
You are receiving that error because the Steam versions of those games are not supported in Xash3D FWGS at the moment.

Please see the documentation: [Unsupported Mods and Reasons Why](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md)

---

If you would like to experiment on your own:

For Blue Shift, you can use the old WON version, or you can compile the excellent [hlsdk-portable version](https://github.com/FWGS/hlsdk-portable/tree/bshift).

For Counter Strike, you can use the WON version of CS 1.5 and replace the encrypted client `.dll` with [Numanoid's Decrypted Client](https://csm.dev/threads/cs-1-5-client-dll-decrypted-patched-for-usage.38845/).

However, if CS 1.6 is what you strongly prefer, you can try downloading or compiling the [ReGameDLL CS Server](https://github.com/s1lentq/ReGameDLL_CS). You will also have to download or compile a client, such as [csldr](https://github.com/mikkokko/csldr).

There are other projects you can look at, such as [d3adwolf's CS 1.6 bundle](https://github.com/d3adwolf/cs16-client/releases/tag/v1.0), but this is several years old now, I think. There is also [CSMoE](https://github.com/MoeMod/CSMoE) which is similar to CS: Online.

If you wish to play DoD in Xash3D, for now you may be limited to the [1.3 beta](https://gamebanana.com/mods/35721).

**Comment by Gorilli09** [comment]
> You are receiving that error because the Steam versions of those games are not supported in Xash3D FWGS at the moment.
> 
> Please see the documentation: [Unsupported Mods and Reasons Why](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md)
> 
> If you would like to experiment on your own:
> 
> For Blue Shift, you can use the old WON version, or you can compile the excellent [hlsdk-portable version](https://github.com/FWGS/hlsdk-portable/tree/bshift).
> 
> For Counter Strike, you can use the WON version of CS 1.5 and replace the encrypted client `.dll` with [Numanoid's Decrypted Client](https://csm.dev/threads/cs-1-5-client-dll-decrypted-patched-for-usage.38845/).
> 
> However, if CS 1.6 is what you strongly prefer, you can try downloading or compiling the [ReGameDLL CS Server](https://github.com/s1lentq/ReGameDLL_CS). You will also have to download or compile a client, such as [csldr](https://github.com/mikkokko/csldr). There are other clients available, but they are closed-source for now and still in testing, I believe.
> 
> There are other projects you can look at, such as [d3adwolf's CS 1.6 bundle](https://github.com/d3adwolf/cs16-client/releases/tag/v1.0), but this is several years old now, I think. There is also [CSMoE](https://github.com/MoeMod/CSMoE) which is similar to CS: Online.
> 
> If you wish to play DoD in Xash3D, for now you may be limited to the [1.3 beta](https://gamebanana.com/mods/35721).

Do you have any plans to add support to those games?

**Comment by Vladislav4KZ** [comment]
> You will also have to download or compile a client, such as csldr.

csldr isn't a client. It's a loader for the original client.dll, that patches it to add new features.

Original client.dll uses VGUI2 which is not supported by the current version of Xash3D FWGS.

There is a fork of the engine with VGUI2 support, but it has not been updated for a long time, and important bug fixes may be missing there.

The best solution to run CS 1.6 on Xash3D is CS16Client. But it is currently closed source.

**Comment by Vladislav4KZ** [comment]
> Steam interfaces are not supported

Maybe it's not supported by Xash3D, but mods can run without them.

As I know, Base Defense requires steam_api.dll, but it can run even with a stub (empty file named steam_api.dll)

**Comment by Vladislav4KZ** [comment]
> There are other projects you can look at, such as d3adwolf's CS 1.6 bundle, but this is several years old now, I think. 

What is this? This is some downloader of an unofficial build of Counter-Strike 1.6? Are you sure that it will work at all on xash?

**Comment by Vladislav4KZ** [comment]
> However, if CS 1.6 is what you strongly prefer, you can try downloading or compiling the ReGameDLL CS Server.

Original mp.dll will work on Xash3D if you use a client supported by the engine (without VGUI2)

**Comment by Vladislav4KZ** [comment]
> There are other projects you can look at, such as d3adwolf's CS 1.6 bundle, but this is several years old now, I think.

Ok, I figured out what it is. It's the GSClient, custom Non-Steam build of Counter-Strike 1.6 on GoldSource which contains the replaced master server, built-in anticheat (for example, it removes all third party ASI files from the game folder, which are not used by the original game), and autoupdater.

It still uses the original client.dll with VGUI2, therefore, it will not work on Xash3D FWGS.

**Comment by Vladislav4KZ** [comment]
> If you wish to play DoD in Xash3D, for now you may be limited to the 1.3 beta.

Xash3D supports Day of Defeat versions from BETA 1.2 to 3.1

Xash3D doesn't support the Steam release of Day of Defeat, because it uses VGUI2.

**Comment by StenApp** [comment]
> Whenever I start those games, they receive an error message.

That’s the reason why blue shift requires bshift unlocked?

**Comment by nekonomicon** [comment]
@StenApp this requirement for original xash3d.
We recommend to use WON Blue Shift libraries or compile Blue Shift libraries from sources.

**Comment by StenApp** [comment]
@Gorilli09  use Blueshift unlocker, then run Blueshift unlocked to play through xash3d:
[https://steamcommunity.com/app/130/discussions/0/3111392579685202694/](https://github.com/FWGS/xash3d-fwgs/issues/url)

**Comment by a1batross** [comment]
Please, never recommend Blue Shift unlocked here. We support normal Blue
Shift maps.

**Comment by StenApp** [comment]
> @StenApp this requirement for original xash3d. We recommend to use WON Blue Shift libraries or to compile Blue Shift libraries from sources.

I recently bought HL1 generations with blue shift. This is the WON and that doesn't work with xash3d.
i HAVE to use "blue shift unlocker1.1" else i get 
![Screenshot 2023-10-01 105547](https://github.com/FWGS/xash3d-fwgs/assets/32524257/70b945f1-686a-4555-be58-35f3e4d68bef)

**Comment by nekonomicon** [comment]
WON 1.0.1.6 and older does not work under Xash3D at all.

**Comment by StenApp** [comment]
Half-Life is 1.1.1.0, so is Opposing Force, Blueshift ist 1.0.0.1
