### ISSUE TITLE
Configuration fails: SDL2 not available

### ISSUE THREAD

**Issue by GrosserKaese** [FWGS/xash3d-fwgs#1413]
Hi, I know that error is somewhat famous, so here goes: When trying to configure the project, it fails with the known error:

![Screenshot 2023-08-29 224716](https://github.com/FWGS/xash3d-fwgs/assets/53865185/f85ba19a-f54f-46cd-a0fe-c6acb06c7c92)

I attach the logfile. I have used the SDL2 devel VC files from libsdl.org so no error there.

[config.log](https://github.com/FWGS/xash3d-fwgs/files/12469310/config.log)

**Comment by GrosserKaese** [comment]
No one has any idea?

**Comment by a1batross** [comment]
Not sure how this can happen at all.

Is Python recent enough? What version of Windows do you use?

**Comment by Marioiscool246** [comment]
I got it to properly configure by using mingw. The problem seems to be the double backslashes as they're not present when using mingw to configure.

**Comment by a1batross** [comment]
Keep in mind, nobody worked on MinGW port for a looong time.

It might even not load any games.

**Comment by Marioiscool246** [comment]
I only ran waf configure through mingw. I used the standard windows stuff for compiling.

**Comment by a1batross** [comment]
The problem is probably caused by your Windows configuration.

Try to do this on fresh virtual machine, if the problem persists, reopen the issue.
