### ISSUE TITLE
Failed to start xash3d test version

### ISSUE THREAD

**Issue by DavidBrazSan** [FWGS/xash3d-fwgs#142]
When I started the game, the application stopped.
Device: Samsung Galaxy J2 J200M
Android: 5.1.1

![Screenshot_2020-03-24-23-17-55](https://user-images.githubusercontent.com/60136669/77495245-c1f39480-6e26-11ea-8e4b-800fa7be6600.png)

**Comment by a1batross** [comment]
Can you record logcat and send it there?

**Comment by DavidBrazSan** [comment]
How do I do that?

**Comment by a1batross** [comment]
Google it, it's very common task.
