### ISSUE TITLE
Counter-Strike 1.5 mod and standalone cause error: client.dll is encrypted

### ISSUE THREAD

**Issue by StenApp** [FWGS/xash3d-fwgs#1429]
Hi,

i'd like to include CS1.5 in xash3D win32

- I installed standalone Counter-Strike and updated to 1.0.0.5 moved cstrike to Xash32 folder and loaded the mod.

- removed cstrike folder and installed 1.5 Counter-Strike HL1 mod in Xash3D folder next to valve folder.

It crashed in both cases with client.dll encrypted.
No Steam files used, what went wrong?

![Screenshot 2023-09-22 112144](https://github.com/FWGS/xash3d-fwgs/assets/32524257/7f6f3f3d-557a-4777-8453-0f74e274cd03)

**Comment by Velaron** [comment]
Some versions of CS are encrypted, you can find an unencrypted dll somewehere on the internet

**Comment by a1batross** [comment]
Or decrypt it yourself. There are existing tools for that.

**Comment by a1batross** [comment]
https://www.unknowncheats.me/forum/counterstrike-1-5-1-6-and-mods/443755-hldlldec-decrypting-libraries-versions.html
Had luck decrypting with this. Sadly, no binaries here.

**Comment by nekonomicon** [comment]
Related issue:
https://github.com/FWGS/xash3d-fwgs/issues/884

**Comment by dedok17** [comment]
Try this one
https://csm.dev/threads/cs-1-5-client-dll-decrypted-patched-for-usage.38845/

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/884
