### ISSUE TITLE
Mousewheel doesn't work twice in a row unless you move the mouse inbetween scrolls

### ISSUE THREAD

**Issue by FOTMarut** [FWGS/xash3d-fwgs#143]
### How to reproduce
1. `bind mwheeldown +jump`
2. Load a map
3. Scroll the wheel down once (the player character jumps)
4. Without moving the mouse at all, scroll the wheel down again

### Expected behavior

The player character should jump again.

### Actual behavior

It doesn't, unless you move the mouse before scrolling.

### Platforms

The issue is consistently occurring in the following platforms:
1. Linux 5.5, SDL2.0.12, commit 87340ceca8a9c5beceb35cb9f45ea108a5ee6f31, both 32- and 64-bit builds
2. Windows 10, 0.20 release (32-bit)

### Notes

Will attach a proposed fix soon

**Comment by FOTMarut** [comment]
Done. #144
Tested on SDL2, NOT on SDL 1.2

**Comment by FOTMarut** [comment]
This fix mimicks this: https://sourceforge.net/p/quakespasm/code/HEAD/tree/trunk/quakespasm/Quake/in_sdl.c#l1080

**Comment by a1batross** [comment]
Closed since MR was merged.
