### ISSUE TITLE
8 секунд черного экрана перед главным меню, если в системе отключен микрофон (Win10)

### ISSUE THREAD

**Issue by dedok17** [FWGS/xash3d-fwgs#1431]
Понял причину, когда переключился альт-табом на батник.
На первом скрине видно, на каком моменте происходит подвисание.

<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/4fd2493e-c394-4486-9cc5-740b1e63ec04" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/623ea70c-9185-4ff1-8c76-3bed543bd73f" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/fad26082-ed57-4bc4-b4a6-5cfae849941c" width=25%>
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/56ae0542-e92c-4d48-8fb6-8a58a9282694" width=25%>

**Comment by a1batross** [comment]
Починилось?

**Comment by dedok17** [comment]
Да просто микрофон включить да и всё
