### ISSUE TITLE
Нормализация sv_skycolor для моделей как в GoldSrc

### ISSUE THREAD

**Issue by dedok17** [FWGS/xash3d-fwgs#1432]
https://github.com/FWGS/hlsdk-portable/blob/04e56448f25a5061f16c063f462d6cc61da1538e/dlls/lights.cpp#L145
Этот код, перед тем как присвоить значения sv_skycolor, меняет цвета, чтобы соответствовало тому как это делает qrad/hlrad. Он в серверной библиотеке, а значит есть везде в модах.

В итоге, например на c2a5w
sv_skycolor_r 365
sv_skycolor_g 356
sv_skycolor_b 268

На boot_camp — 360, 318, 245.
И так далее.

В Ксаше значения баундятся до 255 и модели выглядят белыми на солнце.
R_StudioDynamicLight
https://github.com/FWGS/xash3d-fwgs/blob/bfe17fa241c66752eed34084ddc602da1de3ec63/ref/gl/gl_studio.c#L1382
Но в GoldSrc это не так. Чтобы такого не было, нужно нормализовать значения (привести к виду 0-255), если хоть одно превышает 255. Вот так:

		if( FBitSet( ent->model->flags, STUDIO_FORCE_SKYLIGHT ) || ( psurf && FBitSet( psurf->flags, SURF_DRAWSKY )))
		{
			VectorSet( lightDir, mv->skyvec_x, mv->skyvec_y, mv->skyvec_z );
			total = Q_max( Q_max( mv->skycolor_r, mv->skycolor_g ), mv->skycolor_b );
			if( total > 255.0f )
			{
				light.r = gEngfuncs.LightToTexGamma( (mv->skycolor_r * ( 1.0f / total ) ) * 255.0f );
				light.g = gEngfuncs.LightToTexGamma( (mv->skycolor_g * ( 1.0f / total ) ) * 255.0f );
				light.b = gEngfuncs.LightToTexGamma( (mv->skycolor_b * ( 1.0f / total ) ) * 255.0f );
			}
			else
			{
				light.r = gEngfuncs.LightToTexGamma( (mv->skycolor_r ) );
				light.g = gEngfuncs.LightToTexGamma( (mv->skycolor_g ) );
				light.b = gEngfuncs.LightToTexGamma( (mv->skycolor_b ) );
			}
		}

GoldSrc: (внимание на вьюмодель)
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/be4050aa-cd5a-42f0-9152-4ca5e9423ebc" width=25%>

Xash обычный
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/d61cffca-c02e-4430-be0a-fdd179aa983f" width=25%>

Xash новый код
<img src="https://github.com/FWGS/xash3d-fwgs/assets/145710155/053f4478-e046-43d3-8179-39ace3e951d8" width=25%>

**Comment by dedok17** [comment]
> Починилось? Зачем закрыл?

Мне кажется я придал всему этому слишком большое значение.

**Comment by a1batross** [comment]
Мало ли что ты там себе придал, баг-то есть?

**Comment by a1batross** [comment]
В GoldSrc в этой же функции никакой нормализации нет: значения из float skycolor_{r,g,b} кастуются в unsigned поля структуры colorVec.

Никакого bound() там нет -- гамма не применяется на данном этапе, а видимо где-то позже.

**Comment by dedok17** [comment]
На скринах все видно. Ну и это не баг а так, внешний вид

**Comment by lewa-j** [comment]
Если оно выглядит не так как должно, это баг. Графический баг.
