### ISSUE TITLE
Failed to find library cl_dlls/client_amd64.so

### ISSUE THREAD

**Issue by mooreye** [FWGS/xash3d-fwgs#1433]
./xash3d-fwgs-amd64.AppImage 
Xash3D FWGS installed as AppImage.
Base directory is /home/test. Set XASH3D_BASEDIR environment variable to override this
[22:50:21] Host_InitError: can't initialize cl_dlls/client_amd64.so: Failed to find library cl_dlls/client_amd64.so
cl_dlls/client_amd64.so: cannot open shared object file: No such file or directory

What gives?

**Comment by a1batross** [comment]
For 64-bit engine, you need 64-bit game DLLs.

These don't exist in Steam releases and not used in any Half-Life mods. You probably want to download 32-bit engine instead.
