### ISSUE TITLE
Support for special german characters Ä, Ö, Ü, ß

### ISSUE THREAD

**Issue by StenApp** [FWGS/xash3d-fwgs#1435]
Something is broken in my Won version.
I often miss german umlauts and the eszett.
Menu text is broken while overlay text is correct.
![Screenshot 2023-10-01 140614](https://github.com/FWGS/xash3d-fwgs/assets/32524257/011f1422-3e75-4ce5-9f1e-e1c2a8c6bb9a)

**Comment by a1batross** [comment]
Can you send your translation file?

**Comment by StenApp** [comment]
Where must i search for it and which file?
I bet its a ANSI UTF8 fault

**Comment by Vladislav4KZ** [comment]
> Where must i search for it and which file?

gfx/shell/strings.lst, gfx/shell/kb_act.lst

**Comment by a1batross** [comment]
We discussed this before, isn't it?

You even found these translation files yourself. It's valve_german,
gameui_german, and other files that ends with _german.txt.

пн, 2 окт. 2023 г., 15:25 Sten ***@***.***>:

**Comment by Vladislav4KZ** [comment]
> I found just kb_act.lst.
> strings.lst is missing, cannot find it in the folder nor in wad or pak files.

@StenApp strings.lst may be located in the valve/gfx/shell folder

**Comment by Vladislav4KZ** [comment]
> You even found these translation files yourself. It's valve_german,
> gameui_german, and other files that ends with _german.txt.

The WON version should not have these translation files.

**Comment by Vladislav4KZ** [comment]
Judging by the line "GameUI_QuitConfirmationText" you doesn't even have a gameui_english.txt file, let alone gameui_german.txt

**Comment by StenApp** [comment]
> You even found these translation files yourself. It's valve_german, gameui_german, and other files that ends with _german.txt.





> > I found just kb_act.lst.
> > strings.lst is missing, cannot find it in the folder nor in wad or pak files.
> 
> @StenApp strings.lst may be located in the valve/gfx/shell folder

It's missing...
![Screenshot 2023-10-02 143204](https://github.com/FWGS/xash3d-fwgs/assets/32524257/298839f9-1241-4785-a93d-7d3b0ecd254d)

**Comment by Vladislav4KZ** [comment]
> It's missing...
@StenApp Are you sure you were looking for this file in the valve folder, which is located in the WON version of Opposing Force?

The German translation couldn't have come out of nowhere

**Comment by StenApp** [comment]
I think we talk about 2 different things here:
- First: The HL1 WON version has problems to show umlauts and the esszett in the menu, they are in the .lst file
- Second: Is about translating to german @a1batross this was the steam version like i said here:
   https://github.com/FWGS/xash3d-fwgs/issues/1319#issuecomment-1718277713

**Comment by Vladislav4KZ** [comment]
@StenApp a1batross asked you to upload the translation files.

The WON has the translation files which are located in the folder gfx/shell, and named **strings.lst**, and **kb_act.lst**

**strings.lst** - Contains strings for the main menu
**kb_act.lst** - Contains strings with the action definitions in the keyboard settings menu.

The Steam version has the following translation files (they're located in the resource folder)

**gameui_language.txt**
**valve_language.txt**
**gearbox_language.txt**
etc.

**Comment by StenApp** [comment]
> > It's missing...
> 
> @StenApp Are you sure you were looking for this file in the valve folder, which is located in the WON version of Opposing Force?
> 
> The German translation couldn't have come out of nowhere

holy moly, there is one hdden in gearbox\pak0.pak
[strings.lst.txt](https://github.com/FWGS/xash3d-fwgs/files/12782702/strings.lst.txt)

**Comment by StenApp** [comment]
As for the Steam version i have a german one, updated 5min ago and this is it:

Steam\steamapps\common\Half-Life\valve\resource:
gameui_english.txt
valve_english.txt
Steam\steamapps\common\Half-Life\valve_german\resource:
gameui_german.txt
valve_german.txt
Steam\steamapps\common\Half-Life\gearbox\resource
gearbox_english.txt

**Comment by a1batross** [comment]
Well, the only reason I really ask for these translation files to check at which Unicode range these characters are, so I can add them specifically at mainui_cpp.

>This game is a mess!

It is!

**Comment by StenApp** [comment]
These are the translation files found in valve\resources (steam version)
[gameui_german.txt](https://github.com/FWGS/xash3d-fwgs/files/12783256/gameui_german.txt)
[valve_german.txt](https://github.com/FWGS/xash3d-fwgs/files/12783258/valve_german.txt)

i see i have to arduously copy german texts of valve and gameui to a new mainui_german.txt
Isn't there a way to write available translations in mainui file and leave the rest in english?

**Comment by a1batross** [comment]
>i see i have to arduously copy german texts of valve and gameui to a new mainui_german.txt

I explained this to you before. You actually don't have to.

mainui_cpp will ALWAYS load valve_german.txt, gameui_german.txt and gamedir_german.txt.
If exists, tokens in mainui_german.txt will take precedence over these.

**Comment by a1batross** [comment]
I wonder if it's so confusing to people, maybe we should drop the compatibility with Valve's GameUI translations file and fully provide our own custom translations?

Maybe in a better format that will be more easily to pick up with online translation editors like Weblate?

What do you think? cc @nekonomicon @Velaron @mittorn @Vladislav4KZ @SNMetamorph

**Comment by StenApp** [comment]
For me it's confusing which files are stored where, because i run Xash3d for the WON and a Steam version.

It would be helpful if Xash3d has a type of converter who uses available files (string.lst, kb_act.lst, valve_....txt, gameui_....txt on disk and generates a mainui file out of it. This way just have to complement translations.

**Comment by a1batross** [comment]
I'm telling you AGAIN. All of these files are being used. There is no need to generate ANYTHING.

All you need to do to copy Steam version (not WON, we specifically target Steam here) of the game that's already translated to German language, and you already have half-translated game UI.

**Comment by a1batross** [comment]
Forget about mainui files, try to get just half-translated game with Steam files. It's not that hard, you just copy valve folder out of Steam release, and copy whatever valve_german folder has into valve/custom.

**Comment by a1batross** [comment]
I'm tired of explaining this over and over, reopen this issue when you will do what I said you to do, and we will figure out what to do next.

**Comment by StenApp** [comment]
> Forget about mainui files, try to get just half-translated game with Steam files. It's not that hard, you just copy valve folder out of Steam release, copy whatever valve_german folder has into valve/custom, and set ui_language cvar to "german".

Sorry i didn't knew what to do. Now it works in mixed translation mode.
![Screenshot 2023-10-02 173355](https://github.com/FWGS/xash3d-fwgs/assets/32524257/ca8f0a55-5347-4e6a-87ac-e2607096819e)
![Screenshot 2023-10-02 173337](https://github.com/FWGS/xash3d-fwgs/assets/32524257/0dad1f0f-384e-49da-99ae-6f5f32ce4311)

Nonetheless i have problems with umlauts and esszett:

![Screenshot 2023-10-02 173656](https://github.com/FWGS/xash3d-fwgs/assets/32524257/b53319f5-a743-4b85-b02b-1c8f238f0cbf)
Möchten Sie....

![Screenshot 2023-10-02 173219](https://github.com/FWGS/xash3d-fwgs/assets/32524257/7ca3e5b7-5f4a-4adf-a174-653b0707d057)

Seitwärts...
Primärangriff
Sekundärangriff

**Comment by a1batross** [comment]
https://github.com/FWGS/mainui_cpp/commit/07421520b8635056007853ddf7c7abd6ee7bc604

Hope enabling this character range will be enough for now. In the future, it will dynamically render new characters, but for now it's pretty much hardcoded :(

I updated mainui_cpp submodule, now it should render normally.

**Comment by StenApp** [comment]
The menu for Half-Life is working now.
No success for Opposing force or the controls menu -
i guess both involve ANSI coded files which make problems here: gearbox/gfx/shell/strings.lst, gfx/shell/kb_act.lst
I converted both .lst files to UTF8 and it's working. 

WHY VALVE, JUST WHY?!

**Comment by DavidMacalister** [comment]
Related to: #1742
