### ISSUE TITLE
[MOD: Original Paranoia 1.2] Bugged textures in next maps

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/xash3d-fwgs#1436]
## Explanation:
It getting worsen everytime you enter next maps.
Bugged textures will be literally everywheres everytime you enter next maps.
increasing ``MAX_*`` in gameinfo.txt still won't solve this bug.

Also, there is random crash issues, Xash3D will crash when you try to quit game that used Paranoia's opengl32.dll.
## Info:
Latest Xash3D FWGS [8f819a2](https://github.com/FWGS/xash3d-fwgs/commit/8f819a2fde6fcdd5cf0c1c52384863763783c668)
OS: Windows 10 x86_64bit
GPU: GTX 1650 with latest updated driver(545.84).
MOD: https://www.moddb.com/mods/paranoia/downloads/paranoia-v-12
Log: [engine.log](https://github.com/FWGS/xash3d-fwgs/files/12777517/engine.log)

## Screenshot:
![p_army2_0000](https://github.com/FWGS/xash3d-fwgs/assets/71936968/602aa0bb-2340-4386-93d7-f6f57ee6662b)
![p_army11_0000](https://github.com/FWGS/xash3d-fwgs/assets/71936968/78cadc90-3573-423e-8f96-77e48426c22f)

**Comment by JoBergeron** [comment]
This bug is still present on today's engine build

**Comment by TheKingFireS** [comment]
Doesn't reproduce anymore on latest Xash3D-FWGS. (opengl32 crash-on-exit is still there)
