### ISSUE TITLE
AoM and AoM: DC modifications question

### ISSUE THREAD

**Issue by riddimmdfk** [FWGS/xash3d-fwgs#1437]
Hello!
I want to play Afraid of Monsters and Afraid of Monsters: Director's Cut through Xash3D FWGS. Do I need to download any special builds of these modifications (maybe there are special ones with more engine compatibility, for example), or are the official ones available on Mod DB enough?

**Comment by nekonomicon** [comment]
You can play this mods via old engine and separate launchers from moddb for a while.
I had plans to update old launchers when stable release of new engine will be available.

**Comment by riddimmdfk** [comment]
"Отдельные лаунчеры" – это [вот этот](https://www.moddb.com/engines/xash3d-fwgs-engine/downloads/afraid-of-monsters-directors-cut-crossplatform)? На не DC не нашёл.
И где я могу взять старый движок? На ГитХабе вроде все версии предварительные, или я чего-то недопонял...

**Comment by nekonomicon** [comment]
Также в оригинальном AoM реально нет каких-либо изменений в коде, там просто положили dll от WON HL 1.1.0.7, в которой присутствовал баг с неразрушаемыми трупами.
На ModDB есть [патч](https://www.moddb.com/mods/afraid-of-monsters/downloads/afraid-of-monsters-steampipe-patch) от моддера @malortie с dll собранным на свежем официальном HLSDK от 2013-го года с имитацией бага.

**Comment by riddimmdfk** [comment]
Большое спасибо за ответ!
