### ISSUE TITLE
Сломанный экран загрузки уровня

### ISSUE THREAD

**Issue by vklachkov** [FWGS/xash3d-fwgs#1447]
При загрузке карты отображается чёрный экран с надписью "Loading...". Точно так же, как в этих ишью:

- https://github.com/FWGS/xash3d-fwgs/issues/798
- https://github.com/FWGS/xash3d-fwgs/issues/641

Проблема зависит от видеокарты. Известно, что такая проблема есть на Alder Lake GT-1 и на мобильных телефонах.

Так же была жалоба от @Vladislav4KZ на вот такую красоту:

![](https://user-images.githubusercontent.com/22411953/274562621-46d4d6ac-6ece-438a-89d2-d86e6dcb74b7.png)

Предположительно, экран загрузки полагается на то, что OpenGL рендер не будет отчищать экран и это по большей части работает, но не всегда.

**Comment by Vladislav4KZ** [comment]
Перепроверь на последнем билде движка.

Возможно этот баг мог исчезнуть после этого комитета: https://github.com/FWGS/xash3d-fwgs/commit/0da7ffe45f146670612af066386161b0e77f5973

**Comment by a1batross** [comment]
Нет, он все ещё есть, теперь проявляется на один кадр, когда cls.state уже не ca_disconnected, но ещё не ca_active.

В этот момент движок пытается отрисовать levelshot, но так как его нет, экран остается незаполненным, а 2D часть уже рисуется.

**Comment by a1batross** [comment]
Now fixed completely with 56ba2325
