### ISSUE TITLE
vortigaunt crashes latest build

### ISSUE THREAD

**Issue by Adnan1091** [FWGS/xash3d-fwgs#145]
In the beginning of map c2a5g there are a group of vortigaunts that charges when they see the player.While they are charging,game crashes.
Tested:Latest nighty build,ARM64 android

**Comment by a1batross** [comment]
There are no vortiguants on c2a5g. There is no crash either.

Can you elaborate?

**Comment by Adnan1091** [comment]
sorry,i mean c2a5f

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/nanogl/commit/5a22eab53433dcd0d27110166ae33b91d188e342
