### ISSUE TITLE
Сглаживание

### ISSUE THREAD

**Issue by riddimmdfk** [FWGS/xash3d-fwgs#1450]
Здравствуйте!
Почему в движке на Windows отключено сглаживание объектов по умолчанию? В оригинальном Xash3D оно включено. Не подскажите, как его можно включить?

**Comment by nekonomicon** [comment]
Сглаживание включается в файле opengl.cfg:
`gl_msaa <1/0>` включает/выключает сглаживание.
Через `gl_msaa_samples` изменяется уровень сглаживания.
