### ISSUE TITLE
Engine cant load Quake mdl's.

### ISSUE THREAD

**Issue by APAmk2** [FWGS/xash3d-fwgs#1454]
If you try to load Quake models in Xash3D FWGS - Engine 'll crash with error that says mdl has unsupported type, everything loads fine when using latest Unkle Mike's engine build.
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/12926760/engine.log)
![23_10_13_16_064](https://github.com/FWGS/xash3d-fwgs/assets/107351397/fc621946-d7e1-4490-bc96-8510181b7c78)

**Comment by a1batross** [comment]
Совершенно забыл про эту ишшую. Хорошо напомнили, но уже другие люди.

Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/0f8f35b415c56af799298ed6ab6e9a2749e2f0cb
