### ISSUE TITLE
new game, and load game greyed out

### ISSUE THREAD

**Issue by GDPlayer** [FWGS/xash3d-fwgs#1456]
i'm on  android

**Comment by a1batross** [comment]
Engine version? Engine log?

**Comment by GDPlayer** [comment]
0.21

**Comment by a1batross** [comment]
Run the engine with -log -dev 2 command line args and post engine.log here.

**Comment by GDPlayer** [comment]
im on mobile idk how to upload a file

**Comment by a1batross** [comment]
It's your problem then, not mine.

**Comment by GDPlayer** [comment]
in the console it says it can't execute mainui.cfg
game is cstrike btw

**Comment by a1batross** [comment]
That's not the problem... I need the full log.

cstrike must be loaded with cs16-client. Without it, it won't work.

**Comment by a1batross** [comment]
Huh, makes sense...
I removed them in my custom menu to not confuse people. Never liked how WON
doesn't hide singleplayer options in multiplayer-only games, despite it
knows that.

cc @Velaron then?

**Comment by Velaron** [comment]
Sounds like OP doesn't use cs16-client?

**Comment by Vladislav4KZ** [comment]
> Sounds like OP doesn't use cs16-client?

When using CS16Client beta, these buttons are still present in the main menu.

**Comment by GDPlayer** [comment]
where do i get cs16client other than the old version

**Comment by a1batross** [comment]
https://github.com/Velaron/cs16-client/releases

**Comment by jmcerrejon** [comment]
FYI, I had the same issue, and I fixed copying the missing  _dll/hl_arm64.so_  in my installation. 😉

**Comment by a1batross** [comment]
@jmcerrejon if you copy **hl**_arm64.so you obviously get Half-Life with CS maps. CS needs its own game code and there are prebuilt binaries on the link above.

With HL and some HL mappacks it's fine though.
