### ISSUE TITLE
Feature request - CVAR for disabling skybox filtering

### ISSUE THREAD

**Issue by Jules451** [FWGS/xash3d-fwgs#1459]
First of all, let me thank you for your continued work on this engine. Having a proper source port for one of my favorite videogames of all time is wonderful.

Having said that, I noticed that disabling texture filtering (gl_texture_nearest) has no effect on the skyboxes. This issue is also present in the original Goldsrc engine (https://github.com/ValveSoftware/halflife/issues/2606). With the increasing popularity of playing the game without any filtering, having a variable that could also handle disabling skybox filtering would be quite nice (and, I assume, not too hard to implement).

By the way, is the software rendering still being actively maintained? I've just given it a try and while it seems to be working fine for the most part, I've been encountering issues such as crashes when loading certain levels and the skybox not being drawn at all (it defaults to a solid light blue color).

**Comment by a1batross** [comment]
This actually sounds like a bug than intended feature.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/b76a75d6b47da8b41a6da1c543dc3da929042cc2
