### ISSUE TITLE
[MOD: Counter-Strike] Не мигает бомба C4 на картах с 3D скайбоксом в виде одной огромной модели

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1461]
Видео:
https://youtu.be/nPg7dBmacm8

Карта:
https://gamebanana.com/mods/466280

Версия движка:
Xash3D FWGS v49/0.20 (win32-i386 build 3124)

Баг воспроизводится как на Windows, так и на Android, независимо от версии Counter-Strike и используемого в нем клиента.

Проверял на Counter-Strike 1.5 и Counter-Strike 1.6 как с использованием CS16Client от Velaron, так и с оригинальным клиентом на движке, собранном с ветки **new_vgui_support_api**

На других картах, бомба C4 мигает.

В Counter-Strike запущенном на GoldSource, бомба мигает и на карте de_beishan.

**Comment by Vladislav4KZ** [comment]
Такой баг проявляется и на карте de_dust2_2020.

Есть подозрение, что баг воспроизводится из-за 3D скайбокса.

**Comment by Vladislav4KZ** [comment]
Насколько я понял, 3D скайбокс в этих картах сделан в виде огромной модели, которая возможно установлена где-то в центре карты, а её видимая часть отображается за пределами карты.

На карте de_beishan вроде даже две таких модели используются, env01.mdl и env02.mdl находящиеся в папке `models/de_beishan/env`

**Comment by Vladislav4KZ** [comment]
Попробовал создать создать entpatch для карт de_beishan и de_dust2_2020 с удалением в них энтити `cycler_sprite`, которая и содержит модели 3D скайбокса (обычно их название начинается на **env**).

Но это не помогло, бомба всё равно не начала мигать.

**Comment by a1batross** [comment]
Проблема в дефолтном значении квара r_traceglow. В Ксаше он стоит 1, в голдсорсе 0.

Он контроллирует нужно ли куллить glow спрайты.

**Comment by a1batross** [comment]
b0a79df8
