### ISSUE TITLE
не отображается e_poly

### ISSUE THREAD

**Issue by candysuxx** [FWGS/xash3d-fwgs#1464]
при активации r_speeds во всех режимах так и не смог найти параметра, близкого по смыслу к e_poly
(w_poly, насколько я понимаю, это solid faces при r_speed 1, если нет, тогда следует починить и w_poly)

**Comment by a1batross** [comment]
wpoly это количество полигонов в BSP: мир и отдельные брашмодели.

epoly там есть. Он подсчитывает количество полигонов в студиомоделях (халфовых моделях)

spoly и apoly соответственно подсчитывают полигоны от спрайтов и алиас моделей (кваковских моделях, но они у нас пока что сломаны)

**Comment by a1batross** [comment]
Учти что PrimeXT/XashXT/Paranoia 2 и другие чисто Xash3D игры использующие RenderAPI обычно оверрайдят r_speeds. В этом случае я со стороны движка вообще ничего не сделаю, так как подсчётом занимается кастомный рендерер этих игр.

**Comment by SNMetamorph** [comment]
> Учти что PrimeXT/XashXT/Paranoia 2 и другие чисто Xash3D игры использующие RenderAPI обычно оверрайдят r_speeds. В этом случае я со стороны движка вообще ничего не сделаю, так как подсчётом занимается кастомный рендерер этих игр.

это при условии что выставлен gl_renderer 1

**Comment by a1batross** [comment]
Верно!

Мне кажется, в кастомных рендерерах тот же epoly не всегда имеет смысл, учитывая что пережевывать такие рендереры могут куда более тяжелые модели, тогда как стандартный рендерер движка для студиомоделей до сих пор полагается на glBegin или генерацию буферов с glDrawElements.
