### ISSUE TITLE
Running Half-Life (Counter-Strike Branch) on Xash3d but the Logo is not showing

### ISSUE THREAD

**Issue by xavier114** [FWGS/xash3d-fwgs#1465]
![image](https://github.com/FWGS/xash3d-fwgs/assets/46450797/502874e1-e557-46ef-a0aa-54007f51eab3)

All the files are there but no logo is showing.

**Comment by a1batross** [comment]
Send engine.log

**Comment by a1batross** [comment]
Don't forget to run engine with `-log`

**Comment by a1batross** [comment]
Also, animated logos don't show up with Steam background. For WON styled animated logo, you need WON styled background (see `gfx/shell/splash.bmp`).

Keep in mind that Steam backgrounds (defined by `resource/BackgroundLayout.txt` file) do take precedence OVER WON backgrounds.

**Comment by xavier114** [comment]
functions found
filesystem_stdio: custom memory allocation functions found
filesystem_stdio: custom platform-specific functions found
FS_LoadProgs: filesystem_stdio successfully loaded
C:/Half-Life.v1.1.0.8/ is working directory now
Adding directory: ./
FS_Init: done
FS_LoadGameInfo( valve )
FS_Rescan( Half-Life )
FS_AddGameHierarchy: adding recursive basedir valve
Adding directory: valve/downloaded/
Adding pakfile: valve/pak0.pak (3453 files)
Adding wadfile: valve/cached.wad (2 files)
Adding wadfile: valve/decals.wad (222 files)
Adding wadfile: valve/fonts.wad (3 files)
Adding wadfile: valve/gfx.wad (7 files)
Adding wadfile: valve/halflife.wad (3116 files)
Adding wadfile: valve/liquids.wad (32 files)
Adding wadfile: valve/spraypaint.wad (14 files)
Adding wadfile: valve/xeno.wad (264 files)
Adding directory: valve/
Adding directory: valve/custom/
InitDecals: 222 decals
Joystick: SDL GameController API
IN_TouchInit()
Base networking initialized.
Cannot load xashcomm.lst
SV_LoadProgs: initailized extended EntityAPI ver. 140
Dll loaded for game "Half-Life"
SV: hull0, player_mins: -16 -16 -36, player_maxs: 16 16 36
SV: hull1, player_mins: -16 -16 -18, player_maxs: 16 16 18
SV: hull2, player_mins: 0 0 0, player_maxs: 0 0 0
execing skill.cfg
execing video.cfg
Loading renderer: gl -> ref_gl.dll
execing opengl.cfg
SetDPIAwareness: Success
Trying safe opengl mode 0
bpp 24
R_ChangeDisplaySettings: Setting video mode to 512x384 windowed
Warning: FS_LoadImage: couldn't load "game"
VID_StartupGamma: gamma 2.5 brightness 0
GL_CheckExtension: OpenGL 1.1.0 - enabled
Video: Intel(R) HD Graphics 4400
GL_CheckExtension: GL_ARB_multitexture - enabled
GL_CheckExtension: GL_EXT_texture3D - enabled
GL_CheckExtension: GL_EXT_texture_array - enabled
GL_CheckExtension: GL_ARB_texture_cube_map - enabled
GL_CheckExtension: GL_ARB_seamless_cube_map - enabled
GL_CheckExtension: GL_ARB_texture_non_power_of_two - enabled
GL_CheckExtension: GL_ARB_texture_compression - enabled
GL_CheckExtension: GL_EXT_texture_edge_clamp - enabled
GL_CheckExtension: GL_EXT_texture_filter_anisotropic - enabled
GL_CheckExtension: GL_ARB_texture_border_clamp - enabled
GL_CheckExtension: GL_ARB_depth_texture - enabled
GL_CheckExtension: GL_ARB_texture_float - enabled
GL_CheckExtension: GL_ARB_depth_buffer_float - enabled
GL_CheckExtension: GL_EXT_gpu_shader4 - enabled
GL_CheckExtension: GL_ARB_vertex_buffer_object - enabled
GL_CheckExtension: GL_ARB_texture_multisample - enabled
GL_CheckExtension: GL_ARB_texture_compression_bptc - enabled
GL_CheckExtension: GL_ARB_shading_language_100 - enabled
GL_CheckExtension: GL_ARB_texture_rectangle - enabled
GL_CheckExtension: glDrawRangeElements - enabled

GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 4400
GL_VERSION: 4.3.0 - Build 10.18.15.4248
GL_EXTENSIONS: GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_ARB_conservative_depth GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_ARB_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_SUN_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_ARB_teGL_MAX_TEXTURE_SIZE: 16384
GL_MAX_TEXTURE_UNITS_ARB: 8
GL_MAX_CUBE_MAP_TEXTURE_SIZE_ARB: 16384
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT: 16.0
GL_MAX_RECTANGLE_TEXTURE_SIZE: 16384
GL_MAX_ARRAY_TEXTURE_LAYERS_EXT: 2048
GL_MAX_TEXTURE_COORDS_ARB: 8
GL_MAX_TEXTURE_IMAGE_UNITS_ARB: 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB: 4096
GL_MAX_VERTEX_ATTRIBS_ARB: 16

MODE: 1024x720

VERTICAL SYNC: disabled
Color 24 bits, Alpha 8 bits, Depth 24 bits, Stencil 8 bits
Renderer ref_gl.dll initialized
UI_LoadProgs: extended Menu API found
UI_LoadProgs: extended Menu API initialized
GL_UploadTexture: gfx/shell/cb_empty s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cb_over s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cb_down s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cb_checked s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cb_disabled s&3 [19 x 19]
Rendering Trebuchet MS(13, 500) took 0.067256 seconds
Rendering Trebuchet MS(10, 500) took 0.006455 seconds
Rendering Trebuchet MS(20, 500) took 0.011379 seconds
Rendering Trebuchet MS(13, 1000) took 0.009062 seconds
Rendering Trebuchet MS(13, 1000) took 0.006429 seconds
Rendering Trebuchet MS(13, 1000) took 0.015302 seconds
Rendering Tahoma(9, 500) took 0.006648 seconds
Sys_LoadLibrary: Loading avifil32.dll - ok
Sys_LoadLibrary: Loading msvfw32.dll - ok
Sys_LoadLibrary: Loading msacm32.dll - ok
Using SDL audio driver: wasapi @ 44100 Hz
Note: VoiceCapture_Init: capture device creation success (3: Microphone (High Definition Audio Device))
Note: cl_dlls/client.dll uses Windows API for mouse input
vgui_support: initialized legacy API in support module
CL_LoadProgs: failed to get address of HUD_DirectorMessage proc
CL_LoadProgs: failed to get address of HUD_ChatInputPosition proc
CL_LoadProgs: failed to get address of HUD_GetRenderInterface proc
CL_LoadProgs: failed to get address of HUD_ClipMoveToEntity proc
CL_LoadProgs: failed to get address of IN_ClientTouchEvent proc
CL_LoadProgs: failed to get address of IN_ClientMoveEvent proc
CL_LoadProgs: failed to get address of IN_ClientLookEvent proc
TextMessage: parsed 135 text messages
Warning: CL_LoadProgs: couldn't get mobility API
CL: hull0, player_mins: -16 -16 -36, player_maxs: 16 16 36
CL: hull1, player_mins: -16 -16 -18, player_maxs: 16 16 18
CL: hull2, player_mins: 0 0 0, player_maxs: 0 0 0
joystick found

Error: Couldn't find custom.hpk.
execing config.cfg
couldn't exec userconfig.cfg
Added controller: Logitech F710 Gamepad (1133:49689:0)
Time to first frame: 2.845 seconds
couldn't exec mainui.cfg
Localize_AddToDict( resource/mainui_english.txt ): couldn't open file. Some strings will not be localized!.
Reading config script file settings.scr
Reading config script file user.scr
GL_UploadTexture: gfx/shell/cls_n s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cls_f s&3 [19 x 19]
GL_UploadTexture: gfx/shell/cls_d s&3 [19 x 19]
GL_UploadTexture: gfx/shell/min_n s&3 [19 x 19]
GL_UploadTexture: gfx/shell/min_f s&3 [19 x 19]
GL_UploadTexture: gfx/shell/min_d s&3 [19 x 19]
FS_OpenStream: couldn't open "media/gamestartup"

**Comment by a1batross** [comment]
Also, you need installed old codecs like Cinepak and Indeo (probably some more) installed on your system.

**Comment by xavier114** [comment]
Its not even animated i just want to load the standard resource/game_logo.tga

**Comment by a1batross** [comment]
oh. Add it then yourself in `mainui_cpp` sources. There is an easy way to include mainui_cpp in your mod, just copypaste the sources and open CMakeLists.txt or use pregenerated VS2022 project.

**Comment by xavier114** [comment]
yeah i know that but when i try to load lets say a bmp logo or tga it always ignore transparency or just dont show at all.
