### ISSUE TITLE
Проблема с запуском xash

### ISSUE THREAD

**Issue by Artem-coderh** [FWGS/xash3d-fwgs#1468]
Я пытаюсь запустить xash но мне вылетает такая ошибка
```
1:  0xb6767fa6 (/lib/i386-linux-gnu/libasound.so.2
2: 0x1873f40
```
Использую Alpine linux (edge) в chroot debian sid архитектура процессора i686

**Comment by a1batross** [comment]
Она ни о чем не говорит, пускай под gdb и почти bt.

Или компили себе движок и сдк под musl.

**Comment by Artem-coderh** [comment]
Я не разбираюсь в gdb но я бы хотел узнать какие лучше использовать пакеты для сборки в alpine

**Comment by a1batross** [comment]
В Alpine должно собираться как есть, но из-за musl не будет совместимости с играми скомпилированными под стимовский голдсорс, все придется собирать из исходного кода

**Comment by Artem-coderh** [comment]
Спасибо за совет я как раз собираю из исходников конечно до этого я использовал тестовые сборки но иза chroot-а не было звука я также пробовал из под wine но там странно работала мышка
