### ISSUE TITLE
Crash on Android 2.3

### ISSUE THREAD

**Issue by Google61** [FWGS/xash3d-fwgs#147]
Crash on startup, after pressing launch Xash3D.
I have latest xash-deploy build (0.20.1). 0.19.2 is doing great.
Fly IQ245+, Android 2.3.6, armv7
https://pastebin.com/gYXWjyJS - log

**Comment by a1batross** [comment]
Well. I don't even know on which device I should try to reproduce it, since Android 2.3 is so rare.

0xdeadd00d means a VM failure. I guess with re-adapted for new Androids Java-side code such things may happen. I don't sure how though, we're still on Java 6.

**Comment by a1batross** [comment]
Please, send a logcat. Looks like it can be an unhandled exception.

**Comment by Google61** [comment]
Em

**Comment by a1batross** [comment]
Also, it can be connected that d8, Dalvik byte-code generator isn't able to really generate code for older Androids.

Better to use old dx instead, I think.

So much work and only because people don't want to abandon old Android devices.

**Comment by Google61** [comment]
Sorry for the delay, here is logcat https://pastebin.com/V2uBvqTm

**Comment by a1batross** [comment]
If this still happens (although we don't really support Android 2.3 anymore), create new issue.
