### ISSUE TITLE
Не работает свечение ламп на карте de_beishan

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1474]
**Xash3D FWGS**
https://youtu.be/mOGHp6K22U4

**GoldSource (есть свечение)**
https://youtu.be/QoPSr0FU3LY

Карта:
https://gamebanana.com/mods/466280

**Comment by a1batross** [comment]
r_traceglow в 0 выставил?

вс, 29 окт. 2023 г., 11:12 Владислав Сухов ***@***.***>:

**Comment by Vladislav4KZ** [comment]
> r_traceglow в 0 выставил?

Да, и я точно помню что после этого бомба начала мигать на этой карте.

Сейчас проверил на андроид версии ксаша, там есть свечение у ламп.

Причём как с ``r_traceglow 0`` так и с ``r_traceglow 1``

С ``r_traceglow 1`` только бомба перестаёт мигать.


Ну уже тогда на следующих выходных попытаюсь выяснить, почему на ПК версии они не светились.

**Comment by a1batross** [comment]
У меня на ПК они светятся с r_traceglow 0, как и ожидалось. Правда как-то поменьше, чем на записанном на голдсорсе, но это ладно.

**Comment by Vladislav4KZ** [comment]
На ПК пофикислось вводом квара ``r_traceglow 0``, он у меня был выставлен в 1.

Хотя на андроиде свечение работало как с ``r_traceglow 0``, так и с ``r_traceglow 1``.
