### ISSUE TITLE
Crash on Android 5.1.1

### ISSUE THREAD

**Issue by DavidBrazSan** [FWGS/xash3d-fwgs#148]
The application does not start and close.

**Comment by a1batross** [comment]
Which device? Which SoC and GPU? Send a logcat if it's possible.

Try to select GLES2 renderer in command line "-ref gles2".

**Comment by DavidBrazSan** [comment]
Device: Sansung Galaxy J2 J200M

**Comment by DavidBrazSan** [comment]
Log when using the command "-ref gles2"
https://pt.textbin.net/CD4jDXtpz3
