### ISSUE TITLE
r_ripple does not respect gl_texture_nearest

### ISSUE THREAD

**Issue by generic-name-guy** [FWGS/xash3d-fwgs#1482]
If you have r_ripple enabled, the ripple effect will always be filtered, no matter if you have gl_texture_nearest set to 1.

![c2a5b_0001.png](https://github.com/FWGS/xash3d-fwgs/assets/111185592/2c010a26-d5ee-4609-915f-ef87a3595aea)

![c2a5b_0000.png](https://github.com/FWGS/xash3d-fwgs/assets/111185592/d5c5184f-0400-41e6-b3d6-f1b7ccac4b86)

**Comment by a1batross** [comment]
It specifically has been made to respect it.

Try to toggle the nearest cvar value.

**Comment by generic-name-guy** [comment]
It goes back to being filtered after restarting the game.

**Comment by a1batross** [comment]
Ok, so it doesn't preserve the tex parameter.

вс, 5 нояб. 2023 г., 22:58 generic name guy ***@***.***>:

**Comment by generic-name-guy** [comment]
I found a new problem, some liquids in OP4 are completely flat textures with r_ripple enabled, i took a screenshot but forgot to send it over to my phone, it's in a flooded office in chapter 4 Missing in Action.

**Comment by a1batross** [comment]
Fixed in ab15662d78a248d8a22711efa155ac169aa2b89d
