### ISSUE TITLE
bash: ./xash3d-fwgs-i386.AppImage: cannot execute: required file not found

### ISSUE THREAD

**Issue by mooreye** [FWGS/xash3d-fwgs#1483]
I get this error on Fedora 38 when I try to run x32 AppImage. `valve` dir is in same directory.

**Comment by a1batross** [comment]
Install 32-bit libraries.

**Comment by DeltaLima** [comment]
in most cases with an 32 bit AppImage, the 32 bit fuse libraries are missing.
