### ISSUE TITLE
No sound Debian 10 amd64 with Appimage 32 bit

### ISSUE THREAD

**Issue by r1bnc** [FWGS/xash3d-fwgs#149]
How do I fix this issue, I do not have audio output on my Xash3D game.
I am using the latest release of AppImage x32 bit, I can't use the x86_64 version since my cl_dlls/dlls are being compiled in x32 bit (based on your old pre-https://github.com/FWGS/hlsdk-xash3d)
Older version of xash3d build 531 works but I have mouse input delays/lags in that version, so I switched to the latest xash3d version:

Console log for the Old Working version:
```
================================================================================
	Xash3D FWGS (build 531, Linux-i386) started at Apr04 2020 [08:00.55]
================================================================================
[08:00:56] Joystick: SDL
[08:00:56] No joystick found.
[08:00:56] execing video.cfg
[08:00:56] execing opengl.cfg
[08:00:56] Video: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2
[08:00:56] AVI: Not supported
[08:00:57] Using SDL audio driver: pulseaudio @ 44100 Hz
[08:00:57] Reading config script file settings.scr

```

Console log for the new AppImage latest version:
```
~/Desktop/xash3d_fwgs_linux$ ./xash3d-fwgs-linux-i686.0.20.AppImage -dev -console
Xash3D FWGS installed as AppImage.
Base directory is /home/user/Desktop/xash3d_fwgs_linux. Set XASH3D_BASEDIR environment variable to override this
[09:04:13] Console initialized
[09:04:13] IN_TouchInit()
[09:04:13] execing video.cfg
[09:04:13] Found renderer gl: OpenGL
[09:04:13] Loading renderer: gl -> libref_gl.so
[09:04:13] execing opengl.cfg
[09:04:13] Trying safe opengl mode 0
[09:04:13] bpp 24
[09:04:13] 
[09:04:13] GL_VENDOR: Intel Open Source Technology Center
[09:04:13] GL_RENDERER: Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2

...
[09:04:30] Couldn't open SDL audio: No such audio device
[09:04:30] Audio: sound system can't be initialized
[09:04:30] execing valve.rc

```

I read this issue (https://github.com/FWGS/xash3d/issues/374) from the old xash3d but I have the packages installed as i386 for my amd64 Debian 10 installation. Still no dice.
Any ideas?

**Comment by mittorn** [comment]
SDL seems to be built without pulseaudio support. Maybe installing i386 pulseaudio alsa plugin help

**Comment by gr01d** [comment]
Can you please elaborate which packages that needed to be installed, can you reproduce the same error on your system. If I install the i386 package for the pulseaudio and or alsa, some of my debian programs will be removed by APT.

**Comment by mittorn** [comment]
libasound2-plugins:i386 maybe

**Comment by a1batross** [comment]
You only need libraries for ALSA/PulseAudio, they shouldn't conflict with 64-bit software. For ALSA it's libasound2:i386 and libasound2-plugins:i386, for PA it's libpulse0:i386.

**Comment by gr01d** [comment]
Installed them all but still no sound,

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2:i386 is already the newest version (1.1.8-1).
libasound2-plugins:i386 is already the newest version (1.1.8-1).
libpulse0:i386 is already the newest version (12.2-4+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```


Can you release a non appimage version like in the old xash zip.

Can't test the x86_64 version (maybe this does not have problem, since I am using x64 OS myself), how do  I compile my custom xash3d project so that it outputs a x86_64 client so file? I've tried adding the x64 in the cmake command line but it does not work.

**Comment by Commenter25** [comment]
Having the same issue on Ubuntu MATE 20.04 64-bit, using the 32-bit AppImage, and libasound2:i386 libasound2-plugins:i386 and libpulse0:i386 were installed before even looking at this thread.

**Comment by xfcedos** [comment]
i had the same problem. just extract AppImage with `./file.AppImage --appimage-extract`, remove the libSDL2 library in the appeared squashfs-root folder and pack it back with `appimagetool /squashfs-root`

**Comment by a1batross** [comment]
If this still happens, reopen pls.

**Comment by Konstantin749** [comment]
> i had the same problem. just extract AppImage with `./file.AppImage --appimage-extract`, remove the libSDL2 library in the appeared squashfs-root folder and pack it back with `appimagetool /squashfs-root`.

Была такая же проблема на Debian Bullseye x86_64, решение помогло.
