### ISSUE TITLE
Building doesn't define alloca.h instead of malloc.h when malloc.h is not available

### ISSUE THREAD

**Issue by KayvK** [FWGS/xash3d-fwgs#1490]
While building, the error returns as follows (before modifications to the source):
[291/408] Compiling ref/gl/gl_decals.c
../ref/gl/gl2_shim/gl2_shim.c:37:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.

WAF had already configured it so alloca.h should be defined and used in place of malloc.h, but it seems this check has alluded gl_decals.c.

With this, I'm pretty sure the solution would be to check if malloc.h is not defined and use alloca.h if so. 
I was able to get it to build by doing this. 

However, the reason I don't attempt to commit this is because I am not 100% sure if what I am doing is right or a hack that just so happened to work.

**Comment by nekonomicon** [comment]
> and use alloca.h if so
 
 Why not `stdlib.h`?
 And which platform you use?

**Comment by nekonomicon** [comment]
And yes, you can define such macro instead of `malloc.h`:
```
#if defined( ALLOCA_H )
#include ALLOCA_H
#endif
```

**Comment by a1batross** [comment]
Fixed https://github.com/FWGS/xash3d-fwgs/commit/16cc0ca0fe19f0b424b562b11fafa684f4c3f9c7
