### ISSUE TITLE
Can't find android apk and play store version is broken..

### ISSUE THREAD

**Issue by Cruzejer123** [FWGS/xash3d-fwgs#1491]
I first knew that there was a new version of the xash engine and I also heard that there is a android beta on the google play store and I went there and checked it out, did everything, and resulting that it did not work and so I try again and got the same error 6 times before I gave up

 this was the error code:

Installation in
Progress 
------------------------------------------------------
        Total Files: %1$d%2$d
------------------------------------------------------
             %1$s: %2$d%%

I don't know how I got this error and I used steam verison of hl1 can someone in the team provide APKS for future builds or fix the google play verison because I kept using latest old version verison APK from 2018

I'm sorry I am being mean for this and I know ya are busy but having a working APK of the latest build would be a life saver.

**Comment by Cruzejer123** [comment]
Link?

**Comment by generic-name-guy** [comment]
change "FWGS" in the link to "Velaron"
