### ISSUE TITLE
[arm]Повторная инициализация player movement prediction.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#1492]
Иногда возможно срабатывание [ассерта](https://github.com/FWGS/hlsdk-portable/blob/master/pm_shared/pm_shared.c#L3352) на клиенте:
https://github.com/Velaron/cs16-client/issues/58#issuecomment-1792163222

Это связано с тем, что по какой-то причине значение `ps->number` может быть равно 0 здесь:
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/client/cl_pmove.c#L826C23-L826C23

И это приводит к выходу за границы буффера в клиенте как например здесь:
https://github.com/FWGS/hlsdk-portable/blob/master/pm_shared/pm_shared.c#L1734

Возможно дело в `unsigned char`.

**Comment by a1batross** [comment]
Fixed with a hack in a508467aa
