### ISSUE TITLE
Несовместимость с последним обновлением Half-Life

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1494]
Сегодня в Steam вышло обновление Half-Life:

```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 23:12:24 Nov 16 2023 (9884)
```

Если установить этот билд игры на ксаш, то движок упадёт с ошибкой после создания сервера
![Снимок экрана 2023-11-18 012046](https://github.com/FWGS/xash3d-fwgs/assets/22411953/6a932e2f-e22e-49c6-8114-719cc9bea5b1)
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/13395675/engine.log)

**Comment by nekonomicon** [comment]
Там прелопатили интерфейсы.
Возможно, в каком-то плане лучше подождать релиз нового Half-Life SDK.

**Comment by erfty125** [comment]
> Там перелопатили интерфейсы.
> Возможно, в каком-то плане лучше подождать релиз нового Half-Life SDK.

а если выйдет, то получается изменения коснутся и hlsdk-portable?

**Comment by a1batross** [comment]
Желающие, я думаю, могут уже достать структуры из дварфа.

сб, 18 нояб. 2023 г., 01:45 Andrey Akhmichin ***@***.***>:

**Comment by nekonomicon** [comment]
> а если выйдет, то получается изменения коснутся и hlsdk-portable?

Уже коснулись

**Comment by a1batross** [comment]
Учтите, что речь о последней сборке из Steam.
