### ISSUE TITLE
Couldn't find game directory 'valve'

### ISSUE THREAD

**Issue by staabm** [FWGS/xash3d-fwgs#1495]
for some reason when starting xash3d-fwgs app on macos it errors with "Couldn't find game directory 'valve'".

<img width="264" alt="grafik" src="https://github.com/FWGS/xash3d-fwgs/assets/120441/62611829-b95d-4e6e-bbea-19a3b66a1e83">

I am following the instructions on https://www.macsourceports.com/game/halflife for intallation.

- I have installed xash3d from https://github.com/MacSourcePorts/xash3d-fwgs/releases/download/v0.20-2023-10-02/Xash3D-FWGS-0.20.dmg as a dmg in the applications directory (I am on latest macos with a m1 pro)
- I used SteamCMD to download the game data
- I created a `~/Library/Application Support/Xash3D` directory and put the `valve` folder into it

<img width="452" alt="grafik" src="https://github.com/FWGS/xash3d-fwgs/assets/120441/9885fba3-a78f-4cc4-b8b3-7ccca68abc2b">

I wonder in which directory the app is searching for the game data.
-> would be great the error message would tell where it expects this folder

**Comment by nekonomicon** [comment]
[This changes] (https://github.com/MacSourcePorts/xash3d-fwgs/commits?author=tomkidd) not in upstream and i'm not sure how it must work:
You can try to set path via `XASH3D_BASEDIR` environment variable.
Or need to ask @tomkidd about his macport.

**Comment by cyco** [comment]
@staabm You need to escape that space between `Application` and `Support` or quote everything _after_ the tilde. You accidentally created two directories: `~/Library/Application` and `./Support` and effectively put the valve directory at `~/Downloads/Support/Xash3D/valve`

try running

```bash
$ mkdir -p "$HOME/Library/Application Support/Xash3D/valve"
$ mv "$HOME/Downloads/Support/Xash3D/valve/"* "$HOME/Library/Application Support/Xash3D/valve"
```

@nekonomicon Thanks for mentioning `XASH3D_BASEDIR` that's what I was looking for. It does not seem to be mentioned in the docs.

I think this issue can be closed.
