### ISSUE TITLE
[goldsrc-proto branch] Не работает скачивание файлов с FastDL

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1496]
Проверял на сервере MaddyMurk DeathMatch

Адрес сервера: 37.230.162.74:27015

Подключался по следующему шаблону в консоли:

```
connect ip:port goldsrc
```

Отрывок из лога в момент подключения к серверу:
```
[2023:11:18|23:20:19] Adding http://maddymurk.ru/hl/ as download location
[2023:11:18|23:20:19] Verifying and downloading resources...
[2023:11:18|23:20:19] File maps/pluckedfromreality.bsp queued to download
[2023:11:18|23:20:19] HTTP: Starting download maps/pluckedfromreality.bsp from maddymurk.ru
[2023:11:18|23:20:19] HTTP: Request sent!
[2023:11:18|23:20:19] problem downloading maps/pluckedfromreality.bsp:
NO ERROR
[2023:11:18|23:20:19] Error: Header to big
[2023:11:18|23:20:19] Error: no servers to download maps/pluckedfromreality.bsp!
[2023:11:18|23:20:19] Error: server failed to transmit file 'maps/pluckedfromreality.bsp'
```

[engine.log](https://github.com/FWGS/xash3d-fwgs/files/13401049/engine.log)

**Comment by mittorn** [comment]
Оно и не будет работать, пусть убирает cloudflare

**Comment by mittorn** [comment]
Видимо, для goldsrc надо реализовывать скачивание фрагментами.  Потому там могут быть https, ftp и просто нерабочие сервера. голдсорс выкачивает просто без fastdl, да и игроки, которые всё уже скачали не заметят разницы. Например включили когда-то cloudflare и оно перестало работать. Если под linux поддерживать https относительно несложно дёрнув бинарь openssl, на остальных платформах придётся или тащить openssl с собой (возмоюно, вместе с curl) или использовать уже платформенный веб-клиент, опять же проблему с cloudflare это вряд ли решит - он как раз нужен чтобы не давать качать не из браузера

**Comment by a1batross** [comment]
Скачивание фрагментами у нас работает с голдсорсом.

Но я встречал этот баг, если HTTP загрузчик получил не 200, то соединение
не продолжается.

Другими словами, из-за загрузчика иногда не работает подключение.

**Comment by mittorn** [comment]
Ок, значит надо переделать логику. Там сейчас счётчик, соответсвенно если файл нескачался- нет способа откатиться на фрагменты обратно, он может только пропустить файл.  Загрузчик делался, когда фрагменты были гарантированно сломаны. Теперь пришло время это переделывать

19 ноября 2023 г. 16:33:47 GMT+03:00, Alibek Omarov ***@***.***> пишет:

**Comment by Vladislav4KZ** [comment]
Закрываю в связи с новой issue: https://github.com/FWGS/xash3d-fwgs/issues/1838
Там другие ошибки, и проблема проявляется не на всех GoldSource серверах.
