### ISSUE TITLE
Host_InitError: can't initialize cl_dlls/client_amd64.dll: failed to find library cl_dlls/client_amd64.dll

### ISSUE THREAD

**Issue by sh4nesu** [FWGS/xash3d-fwgs#1497]
Processor: AMD Ryzen 5 5600G
OS: Windows 11
Xash3D FWGS testing build Win 32 AMD 64

When I try to launch the xash3d.exe it gives me this error:
Host_InitError: can't initialize cl_dlls/client_amd64.dll: failed to find library cl_dlls/client_amd64.dll

When I click ok, the window closes and nothing happens. tested the WON version and the version from Steam (legacy and 25th anniversery).

**Comment by Velaron** [comment]
Install 32-bit engine

**Comment by a1batross** [comment]
You need i386 build. 

amd64 only exists for few specific mods that are ported to 64-bit.

**Comment by soykhaler** [comment]
can i donwload 32bit half-life version from steam launcher?

**Comment by a1batross** [comment]
It's the only Half-Life version you can get from Steam.

**Comment by soykhaler** [comment]
i have the valve folder on xash and im getting this error


"Host_Errorlnit: cannot initialize cl_dlls/client_amd64.dll: Failed to find library cl_dlls/client_amd64.dll" i have xash3d 64-bit, idk what's the problem

**Comment by soykhaler** [comment]
fixed! installing i386 version

**Comment by admiraldaro** [comment]
Why 64-bit version even exist if it doesn't work?

**Comment by a1batross** [comment]
It works, see PrimeXT, see hlsdk-portable, it just not for most people using x86 machines.

**Comment by bbruh5918-arch** [comment]
Win 10
86x 32 bit
64 bit processor
|||||||||||||||||||||||||||||
Hey I'm using xash 3d with half life 1 and uuuh there was an error about client dllw and one about library I forgot what it was About do I used the half life sdk thing files and took the client.dll and replaced it and it has an error

![Image](https://github.com/user-attachments/assets/b10c7df5-4a41-48d2-910e-a02049846f98)
