### ISSUE TITLE
Broken demo (Host_Error: `CL_EDICT_NUM: clgame.entities is NULL` or `svc_bad`)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#1499]
Записал демо, пытаюсь её проиграть и ошибка
[minidemo_03_201123.zip](https://github.com/FWGS/xash3d-fwgs/files/13416806/minidemo_03_201123.zip)
```
[2023:11:20|18:44:41] BAD:  1610:svc_spawnbaseline
[2023:11:20|18:44:41] Wrote erroneous message to buffer.dat
[2023:11:20|18:44:41] Host_Error: CL_EDICT_NUM: clgame.entities is NULL
```
Другие демо до этого записывались нормально и игрались, в чём может быть причина? Могло быть из-за того что я начал с map c1a0c без костюма?

**Comment by a1batross** [comment]
О, ещё одна clgame.entities == NULL ошибка.

**Comment by 0x4E69676874466F78** [comment]
> О, ещё одна clgame.entities == NULL ошибка.

Это лечится?

**Comment by a1batross** [comment]
Просто где-то порядок инициализации неверный, нужно починить.

**Comment by a1batross** [comment]
Демка похоже всё-таки битая. Движок всегда записывает после заголовка демки сигнон. В сингоне находится вся начальная информация о сервере, таблицы дельтакодирования и начальные энтити.

Информации о сервере (сообщение svc_serverdata) в демке нет, соответствено аллокации энтитей не происходит, и поэтому движок завершается с ошибкой "clgame.entities == NULL" или "no free edicts".

**Comment by a1batross** [comment]
Наврядли демку можно как-то починить. Если намеренно пропустить svc_spawnbaseline, то демка споктнется об незареганные юзермессаги.

**Comment by a1batross** [comment]
Если это происходит не впервые, проверь что у тебя файл demoheader.tmp создается без проблем.

**Comment by 0x4E69676874466F78** [comment]
> Если это происходит не впервые, проверь что у тебя файл demoheader.tmp создается без проблем.

Пока произошло только 1 раз. demoheader.tmp там создался без проблем.

**Comment by 0x4E69676874466F78** [comment]
На сей раз demoheader.tmp оказывался почему-то 0 байт
[minidemo_06_241123.zip](https://github.com/FWGS/xash3d-fwgs/files/13459946/minidemo_06_241123.zip)
Демка падает на 
```
[2023:11:24|17:10:47] BAD:  410:???
[2023:11:24|17:10:47] Wrote erroneous message to buffer.dat
[2023:11:24|17:10:47] Host_Error: CL_ParseUserMessage: illegible server message 189
```

**Comment by 0x4E69676874466F78** [comment]
Зачем вообще demoheader.tmp почему нельзя записать заголовок сразу и всё в 1 файл?

**Comment by 0x4E69676874466F78** [comment]
Учитывая что у меня не всегда получается с первого раза я останавливаю и начинаю заново демку, в какой-то момент оно ломается.

**Comment by a1batross** [comment]
demoheader нужен чтобы записать сигнон. Ты же не всегда начинаешь демку с самого старта уровня, но при этом демка должна хранить в себе сообщения которые сервер присылает при коннекте.

**Comment by 0x4E69676874466F78** [comment]
А почему эти ~20КБ просто не хранить в памяти?

**Comment by a1batross** [comment]
На самом деле, вполне правильный вопрос :)

сб, 25 нояб. 2023 г., 12:22 NightFox ***@***.***>:

**Comment by artun42** [comment]
Привет, я тут решил немного демок подряд записать, одна вышла норм, оставшиеся 7 не открываются с такими же симптомами как и у Найтфокса. Поправь пожалуйста :)

**Comment by 0x4E69676874466F78** [comment]
Ещё я заметил что даже если демка воспроизводится она записана не совсем корректно, есть проблемы с анимацией выстрела, перезарядки, даже звук не воспроизводится при выстреле почему-то.

**Comment by a1batross** [comment]
Возможно исправлено в 22d3ba674ec973a2044f04ebb7f3886e1c28aa62

Суть: если начать записывать демку, перейти на другой уровень, остановить запись и сразу начать запись другой демки, то demoheader с сигноном оказывался пуст, так как при текущей записи демки, сигнон записывался в неё, а не в demoheader.

Решение: писать как в demoheader, так и в текущую записываемую демку.

**Comment by mittorn** [comment]
Кажется, я ловил это раньше и не понимал, почему, выглядело просто как 
"после changelevel демка иногда не записывается"
