### ISSUE TITLE
[TriAPI]HUD_DrawTransparentTriangles callback does not work correctly after changelevel

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#150]
As an example such code does not work after changelevel:
https://github.com/FWGS/hlsdk-xash3d/blob/poke646/cl_dll/poke646/scope.cpp
https://github.com/FWGS/hlsdk-xash3d/blob/poke646/cl_dll/tri.cpp#L115

Scope before changelevel:
http://ipic.su/7yK8Mi

Scope after changelevel:
http://ipic.su/7yK8Mo

**Comment by h1naria** [comment]
Also, new engine could not draw sprites in Night at the Office using TriAPI at all.

**Comment by nekonomicon** [comment]
Sorry, seems this issue is not related to engine.
