### ISSUE TITLE
Попробовал собрать git clone --recursive https://github.com/FWGS/hlsdk-xash3d.git и все сломалось при сборке (Ubuntu Arm64)

### ISSUE THREAD

**Issue by ArtemS2** [FWGS/xash3d-fwgs#1500]
[153/412] Compiling engine/client/cl_game.c
../filesystem/filesystem.c: In function ‘FS_InitGameInfo’:
../filesystem/filesystem.c:647:36: error: ‘DEFAULT_MAX_EDICTS’ undeclared (first use in this function)
  647 |         GameInfo->max_edicts     = DEFAULT_MAX_EDICTS; // default value if not specified
      |                                    ^~~~~~~~~~~~~~~~~~
../filesystem/filesystem.c:647:36: note: each undeclared identifier is reported only once for each function it appears in

In file included from ../3rdparty/opus/opus/celt/celt_encoder.c:49:
../3rdparty/opus/opus/celt/float_cast.h:135:10: warning: #warning "Don't have the functions lrint() and lrintf ()." [-Wcpp]
  135 |         #warning "Don't have the functions lrint() and lrintf ()."
      |          ^~~~~~~
../3rdparty/opus/opus/celt/float_cast.h:136:10: warning: #warning "Replacing these functions with a standard C cast." [-Wcpp]
  136 |         #warning "Replacing these functions with a standard C cast."
      |          ^~~~~~~

Waf: Leaving directory `/home/artem/xash3d-fwgs/build'
Build failed
 -> task in 'filesystem_stdio' failed with exit status 1 (run with -v to display more information)

**Comment by ArtemS2** [comment]
если к ./waf build  добавляю -v , то выводит:
artem@artem-desktop:~/xash3d-fwgs$ ./waf build -v
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/home/artem/xash3d-fwgs/build'
[143/412] Linking build/3rdparty/opus/libopus.a
18:48:57 runner ['/usr/bin/ar', 'rcs', '3rdparty/opus/libopus.a', '3rdparty/opus/opus/celt/bands.c.1.o', '3rdparty/opus/opus/celt/celt.c.1.o', '3rdparty/opus/opus/celt/celt_decoder.c.1.o', '3rdparty/opus/opus/celt/celt_encoder.c.1.o', '3rdparty/opus/opus/celt/celt_lpc.c.1.o', '3rdparty/opus/opus/celt/cwrs.c.1.o', '3rdparty/opus/opus/celt/entcode.c.1.o', '3rdparty/opus/opus/celt/entdec.c.1.o', '3rdparty/opus/opus/celt/entenc.c.1.o', '3rdparty/opus/opus/celt/kiss_fft.c.1.o', '3rdparty/opus/opus/celt/laplace.c.1.o', '3rdparty/opus/opus/celt/mathops.c.1.o', '3rdparty/opus/opus/celt/mdct.c.1.o', '3rdparty/opus/opus/celt/modes.c.1.o', '3rdparty/opus/opus/celt/pitch.c.1.o', '3rdparty/opus/opus/celt/quant_bands.c.1.o', '3rdparty/opus/opus/celt/rate.c.1.o', '3rdparty/opus/opus/celt/vq.c.1.o', '3rdparty/opus/opus/silk/A2NLSF.c.1.o', '3rdparty/opus/opus/silk/CNG.c.1.o', '3rdparty/opus/opus/silk/HP_variable_cutoff.c.1.o', '3rdparty/opus/opus/silk/LPC_analysis_filter.c.1.o', '3rdparty/opus/opus/silk/LPC_fit.c.1.o', '3rdparty/opus/opus/silk/LPC_inv_pred_gain.c.1.o', '3rdparty/opus/opus/silk/LP_variable_cutoff.c.1.o', '3rdparty/opus/opus/silk/NLSF2A.c.1.o', '3rdparty/opus/opus/silk/NLSF_VQ.c.1.o', '3rdparty/opus/opus/silk/NLSF_VQ_weights_laroia.c.1.o', '3rdparty/opus/opus/silk/NLSF_decode.c.1.o', '3rdparty/opus/opus/silk/NLSF_del_dec_quant.c.1.o', '3rdparty/opus/opus/silk/NLSF_encode.c.1.o', '3rdparty/opus/opus/silk/NLSF_stabilize.c.1.o', '3rdparty/opus/opus/silk/NLSF_unpack.c.1.o', '3rdparty/opus/opus/silk/NSQ.c.1.o', '3rdparty/opus/opus/silk/NSQ_del_dec.c.1.o', '3rdparty/opus/opus/silk/PLC.c.1.o', '3rdparty/opus/opus/silk/VAD.c.1.o', '3rdparty/opus/opus/silk/VQ_WMat_EC.c.1.o', '3rdparty/opus/opus/silk/ana_filt_bank_1.c.1.o', '3rdparty/opus/opus/silk/biquad_alt.c.1.o', '3rdparty/opus/opus/silk/bwexpander.c.1.o', '3rdparty/opus/opus/silk/bwexpander_32.c.1.o', '3rdparty/opus/opus/silk/check_control_input.c.1.o', '3rdparty/opus/opus/silk/code_signs.c.1.o', '3rdparty/opus/opus/silk/control_SNR.c.1.o', '3rdparty/opus/opus/silk/control_audio_bandwidth.c.1.o', '3rdparty/opus/opus/silk/control_codec.c.1.o', '3rdparty/opus/opus/silk/debug.c.1.o', '3rdparty/opus/opus/silk/dec_API.c.1.o', '3rdparty/opus/opus/silk/decode_core.c.1.o', '3rdparty/opus/opus/silk/decode_frame.c.1.o', '3rdparty/opus/opus/silk/decode_indices.c.1.o', '3rdparty/opus/opus/silk/decode_parameters.c.1.o', '3rdparty/opus/opus/silk/decode_pitch.c.1.o', '3rdparty/opus/opus/silk/decode_pulses.c.1.o', '3rdparty/opus/opus/silk/decoder_set_fs.c.1.o', '3rdparty/opus/opus/silk/enc_API.c.1.o', '3rdparty/opus/opus/silk/encode_indices.c.1.o', '3rdparty/opus/opus/silk/encode_pulses.c.1.o', '3rdparty/opus/opus/silk/float/LPC_analysis_filter_FLP.c.1.o', '3rdparty/opus/opus/silk/float/LPC_inv_pred_gain_FLP.c.1.o', '3rdparty/opus/opus/silk/float/LTP_analysis_filter_FLP.c.1.o', '3rdparty/opus/opus/silk/float/LTP_scale_ctrl_FLP.c.1.o', '3rdparty/opus/opus/silk/float/apply_sine_window_FLP.c.1.o', '3rdparty/opus/opus/silk/float/autocorrelation_FLP.c.1.o', '3rdparty/opus/opus/silk/float/burg_modified_FLP.c.1.o', '3rdparty/opus/opus/silk/float/bwexpander_FLP.c.1.o', '3rdparty/opus/opus/silk/float/corrMatrix_FLP.c.1.o', '3rdparty/opus/opus/silk/float/encode_frame_FLP.c.1.o', '3rdparty/opus/opus/silk/float/energy_FLP.c.1.o', '3rdparty/opus/opus/silk/float/find_LPC_FLP.c.1.o', '3rdparty/opus/opus/silk/float/find_LTP_FLP.c.1.o', '3rdparty/opus/opus/silk/float/find_pitch_lags_FLP.c.1.o', '3rdparty/opus/opus/silk/float/find_pred_coefs_FLP.c.1.o', '3rdparty/opus/opus/silk/float/inner_product_FLP.c.1.o', '3rdparty/opus/opus/silk/float/k2a_FLP.c.1.o', '3rdparty/opus/opus/silk/float/noise_shape_analysis_FLP.c.1.o', '3rdparty/opus/opus/silk/float/pitch_analysis_core_FLP.c.1.o', '3rdparty/opus/opus/silk/float/process_gains_FLP.c.1.o', '3rdparty/opus/opus/silk/float/regularize_correlations_FLP.c.1.o', '3rdparty/opus/opus/silk/float/residual_energy_FLP.c.1.o', '3rdparty/opus/opus/silk/float/scale_copy_vector_FLP.c.1.o', '3rdparty/opus/opus/silk/float/scale_vector_FLP.c.1.o', '3rdparty/opus/opus/silk/float/schur_FLP.c.1.o', '3rdparty/opus/opus/silk/float/sort_FLP.c.1.o', '3rdparty/opus/opus/silk/float/warped_autocorrelation_FLP.c.1.o', '3rdparty/opus/opus/silk/float/wrappers_FLP.c.1.o', '3rdparty/opus/opus/silk/gain_quant.c.1.o', '3rdparty/opus/opus/silk/init_decoder.c.1.o', '3rdparty/opus/opus/silk/init_encoder.c.1.o', '3rdparty/opus/opus/silk/inner_prod_aligned.c.1.o', '3rdparty/opus/opus/silk/interpolate.c.1.o', '3rdparty/opus/opus/silk/lin2log.c.1.o', '3rdparty/opus/opus/silk/log2lin.c.1.o', '3rdparty/opus/opus/silk/pitch_est_tables.c.1.o', '3rdparty/opus/opus/silk/process_NLSFs.c.1.o', '3rdparty/opus/opus/silk/quant_LTP_gains.c.1.o', '3rdparty/opus/opus/silk/resampler.c.1.o', '3rdparty/opus/opus/silk/resampler_down2.c.1.o', '3rdparty/opus/opus/silk/resampler_down2_3.c.1.o', '3rdparty/opus/opus/silk/resampler_private_AR2.c.1.o', '3rdparty/opus/opus/silk/resampler_private_IIR_FIR.c.1.o', '3rdparty/opus/opus/silk/resampler_private_down_FIR.c.1.o', '3rdparty/opus/opus/silk/resampler_private_up2_HQ.c.1.o', '3rdparty/opus/opus/silk/resampler_rom.c.1.o', '3rdparty/opus/opus/silk/shell_coder.c.1.o', '3rdparty/opus/opus/silk/sigm_Q15.c.1.o', '3rdparty/opus/opus/silk/sort.c.1.o', '3rdparty/opus/opus/silk/stereo_LR_to_MS.c.1.o', '3rdparty/opus/opus/silk/stereo_MS_to_LR.c.1.o', '3rdparty/opus/opus/silk/stereo_decode_pred.c.1.o', '3rdparty/opus/opus/silk/stereo_encode_pred.c.1.o', '3rdparty/opus/opus/silk/stereo_find_predictor.c.1.o', '3rdparty/opus/opus/silk/stereo_quant_pred.c.1.o', '3rdparty/opus/opus/silk/sum_sqr_shift.c.1.o', '3rdparty/opus/opus/silk/table_LSF_cos.c.1.o', '3rdparty/opus/opus/silk/tables_LTP.c.1.o', '3rdparty/opus/opus/silk/tables_NLSF_CB_NB_MB.c.1.o', '3rdparty/opus/opus/silk/tables_NLSF_CB_WB.c.1.o', '3rdparty/opus/opus/silk/tables_gain.c.1.o', '3rdparty/opus/opus/silk/tables_other.c.1.o', '3rdparty/opus/opus/silk/tables_pitch_lag.c.1.o', '3rdparty/opus/opus/silk/tables_pulses_per_block.c.1.o', '3rdparty/opus/opus/src/analysis.c.1.o', '3rdparty/opus/opus/src/mapping_matrix.c.1.o', '3rdparty/opus/opus/src/mlp.c.1.o', '3rdparty/opus/opus/src/mlp_data.c.1.o', '3rdparty/opus/opus/src/opus.c.1.o', '3rdparty/opus/opus/src/opus_decoder.c.1.o', '3rdparty/opus/opus/src/opus_encoder.c.1.o', '3rdparty/opus/opus/src/opus_multistream.c.1.o', '3rdparty/opus/opus/src/opus_multistream_decoder.c.1.o', '3rdparty/opus/opus/src/opus_multistream_encoder.c.1.o', '3rdparty/opus/opus/src/opus_projection_decoder.c.1.o', '3rdparty/opus/opus/src/opus_projection_encoder.c.1.o', '3rdparty/opus/opus/src/repacketizer.c.1.o']
[150/412] Compiling filesystem/filesystem.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-Iengine', '-I../engine', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '../filesystem/filesystem.c', '-c', '-o/home/artem/xash3d-fwgs/build/filesystem/filesystem.c.2.o']
[151/412] Compiling engine/client/console.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/client/console.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/client/console.c.2.o']
[152/412] Compiling engine/common/imagelib/img_main.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/common/imagelib/img_main.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/common/imagelib/img_main.c.2.o']
[153/412] Compiling engine/common/cmd.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/common/cmd.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/common/cmd.c.2.o']
[155/412] Compiling engine/client/cl_video.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/client/cl_video.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/client/cl_video.c.2.o']
[157/412] Compiling engine/client/cl_view.c
[157/412] Compiling engine/client/cl_tent.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/client/cl_view.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/client/cl_view.c.2.o']
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/client/cl_tent.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/client/cl_tent.c.2.o']
[161/412] Compiling engine/client/cl_securedstub.c
18:48:57 runner ['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Iengine/common', '-I../engine/common', '-Iengine/common/imagelib', '-I../engine/common/imagelib', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I3rdparty/opus/opus/include', '-I../3rdparty/opus/opus/include', '-I/usr/include/SDL2', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-DXASH_64BIT=1', '-DXASH_REF_SOFT_ENABLED=1', '-DXASH_REF_GL_ENABLED=1', '-D_REENTRANT', '../engine/client/cl_securedstub.c', '-c', '-o/home/artem/xash3d-fwgs/build/engine/client/cl_securedstub.c.2.o']
../filesystem/filesystem.c: In function ‘FS_InitGameInfo’:
../filesystem/filesystem.c:647:36: error: ‘DEFAULT_MAX_EDICTS’ undeclared (first use in this function)
  647 |         GameInfo->max_edicts     = DEFAULT_MAX_EDICTS; // default value if not specified
      |                                    ^~~~~~~~~~~~~~~~~~
../filesystem/filesystem.c:647:36: note: each undeclared identifier is reported only once for each function it appears in

Waf: Leaving directory `/home/artem/xash3d-fwgs/build'
Build failed
 -> task in 'filesystem_stdio' failed with exit status 1: 
	{task 281473158487632: c filesystem.c -> filesystem.c.2.o}
['/usr/bin/gcc', '-MMD', '-g', '-fvisibility=hidden', '-O3', '-fno-semantic-interposition', '-fdiagnostics-color=always', '-Werror=bool-compare', '-Werror=bool-operation', '-Werror=cast-align=strict', '-Werror=duplicated-cond', '-Werror=implicit-fallthrough=2', '-Werror=logical-op', '-Werror=nonnull', '-Werror=packed', '-Werror=packed-not-aligned', '-Werror=parentheses', '-Werror=return-type', '-Werror=sequence-point', '-Werror=sizeof-pointer-memaccess', '-Werror=sizeof-array-div', '-Werror=sizeof-pointer-div', '-Werror=strict-aliasing', '-Werror=string-compare', '-Werror=tautological-compare', '-Werror=vla', '-Werror=write-strings', '-Winit-self', '-Wmisleading-indentation', '-Wstringop-overflow', '-Werror=declaration-after-statement', '-Werror=enum-conversion', '-Werror=implicit-int', '-Werror=implicit-function-declaration', '-Werror=incompatible-pointer-types', '-Werror=int-conversion', '-Werror=jump-misses-init', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=strict-prototypes', '-fPIC', '-Ifilesystem', '-I../filesystem', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-Iengine', '-I../engine', '-DXASH_GAMEDIR="valve"', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_ALLOCA_H=1', '-DALLOCA_H="alloca.h"', '-DHAVE_TGMATH_H=1', '-DHAVE_STRCASESTR=1', '-D_GNU_SOURCE=1', '-DHAVE_STRCHRNUL=1', '-DXASH_LOW_MEMORY=0', '../filesystem/filesystem.c', '-c', '-o/home/artem/xash3d-fwgs/build/filesystem/filesystem.c.2.o']

**Comment by a1batross** [comment]
Пофиксим.
