### ISSUE TITLE
Azure Sheep mod for half life not working.

### ISSUE THREAD

**Issue by Cruzejer123** [FWGS/xash3d-fwgs#1502]
I got to the the part that leads down to the security guard office outside of the dormitories at the beginning state and just as I get near the door, it glitches out and I am inside of the control panel when an animation is supposed to play out but it's bugs out and I am stuck outside and can't go out and the door that doesn't let u out well I can go out and wander the rest of the level but I can't progress any further fix plz

Platform: Android

**Comment by nekonomicon** [comment]
You need to use [old engine](https://github.com/FWGS/xash3d/releases/tag/v0.19.2) and [separate launcher](https://github.com/nekonomicon/AzureSheep-android/releases/tag/1.0)

**Comment by Cruzejer123** [comment]
> You need to use [old engine](https://github.com/FWGS/xash3d/releases/tag/v0.19.2) and [separate launcher](https://github.com/nekonomicon/AzureSheep-android/releases/tag/1.0)

I try to install the old engine but it's so old now that my phone say it's not compatible with the current version of android

S23+ OneUI 6

**Comment by Vladislav4KZ** [comment]
Azure Sheep is currently not supported by the new engine on Android (no launcher). Use the old engine and the Azure Sheep launcher.

Closing as stale.
