### ISSUE TITLE
[BUG] After restart the create game settings was reset

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1506]
https://cdn.discordapp.com/attachments/471621339669725194/1176774868482674769/2023-11-22_13-41-34.mp4

**Comment by a1batross** [comment]
They aren't supposed to be saved yet.

We need a proper dumper info user.scr/settings.scr to do that, like GoldSrc does when user changes these settings. Probably even in a shadow file that won't trash user.scr/settings.scr on errors.

**Comment by unattendedplayer** [comment]
Is there a way to exec a config file automatically when starting a server since listenserver.cfg gets deleted and overwritten every time?
