### ISSUE TITLE
Sven Coop 5.25 mod for Half Life not working

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1507]
I downloaded from steam and copying into Xash3D and not working. Also Sven Coop 2.0 client.dll not working but works old engine
![image](https://github.com/FWGS/xash3d-fwgs/assets/76803825/7e99be21-e1f7-4d07-a77b-8cee69f0c079)

**Comment by nekonomicon** [comment]
[Sven-coop 5.0+ not supported at all](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md)
For old versions probably need fix.

**Comment by Qwertyus3D** [comment]
Let's say, Sven Coop 5.25 is not a mod for Half Life :) It's standalone game with specific engine. Sven Coop versions below 3.0 are most likely were created in early WON HL era before patch 1.1.0.0 (like 1.0.1.6 and earlier), so they also not compatible, since old HL also has a bit another engine, not supported by Xash3D.

**Comment by a1batross** [comment]
I wonder if we could support early mods, at least in some degree...

**Comment by nekonomicon** [comment]
> I wonder if we could support early mods, at least at some degree...

I think will be better to write external wrapper.

**Comment by a1batross** [comment]
Anyway, SC 5.x and higher is unsupported, and I don't think it ever will, due to SC being a game in active development and not supporting C++ mods like original Half-Life.

Closed as wontfix.

**Comment by unattendedplayer** [comment]
Would be interesting to run CS beta 5.2/6.1 on this engine...

**Comment by nekonomicon** [comment]
@unattendedplayer There probably need to write external wrapper as well as for sven-coop 2.0 and original rebellion.

**Comment by Vladislav4KZ** [comment]
> SC being a game in active development and not supporting C++ mods like original Half-Life.

It supports. I've tried running them on the Sven Co-op engine and even seen some guys hosting servers for mods running on Svengine.
