### ISSUE TITLE
Multi_manager issue

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#1508]
В общем, выяснил интересную штуку, которая меня мучала очень давно, и только теперь залез внутрь проблемной карты и понял наконец, в чём дело. Речь о карте **vis03** из мода **Visitors**. Там под Ксашем следующее - мы приходим на платформу поезда, видим красную лампу. Подходим к краю платформы - срабатывает триггер, по которому включается тёмный env_fade и активируется переход на следующую карту. Но под Голдсорсом там перед этим происходят (одновременно) ещё 3 события - красная лампа исчезает (func_wall_toggle, видимый со старта карты), появляется лампа с зелёным светом (func_wall_toggle, включаемый триггером) и срабатывает звук, сигнализирующий о "прибытии поезда". Так вот я голову сломал, почему это не происходит под Ксашем, а оказалось, что дело в имени этих энтить. Все 3 энтити названы **light** (это их targetname). И получается, именно потому, что их имя технически совпадает с названием энтити light, Ксаш игнорирует эти события мультименеджера. Стоит проверить данный момент в движке, возможно, не только мультименеджер так себя ведёт, но и другие энтити тоже могут игнорировать, к примеру, поле target, если там прописывается имя энтити, совпадающее к названием какого-либо типа энтить. В принципе, с мультименеджером есть известный факт, о котором пишут в гайдах, что нельза саму энтить называть multi_manager. А тут уже вопрос ещё и с названием других энтить.

**Comment by a1batross** [comment]
```
		if( !Q_strcmp( pkvd[i].szKeyName, "light" ))
		{
			Mem_Free( pkvd[i].szKeyName );
			pkvd[i].szKeyName = copystring( "light_level" );
		}

```

Ксаш зачем-то подменяет light на light_level

**Comment by a1batross** [comment]
Этот код https://github.com/FWGS/Xash3DArchive/commit/fd47c5db5becfc1b07845686e37c8b4f29e9ff4a#diff-47fc3bfc36664e659fecd91458dfbcf438202ad05e163c987d26e4de1242525bR4305 датирован январём 2011. 

Похоже просто на очень старый костыль.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/68377435c858b0a6b5350fee33ee184e13ec2ad9

**Comment by Qwertyus3D** [comment]
Да, скорее всего - опять малобюджетные фиксы какой-нибудь стрёмной фигни в каком-нибудь моде/коде. Хотя даже не знаю, о чём может идти речь, если код 2011 года.
