### ISSUE TITLE
Can't run AppImage build

### ISSUE THREAD

**Issue by Nord1cWarr1or** [FWGS/xash3d-fwgs#1512]
При попытке запуска AppImage (i386) из релизов, выдаёт следующую ошибку:
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
```
FUSE в системе установлен, прикладываю скрин искомой библиотеки.

![изображение](https://github.com/FWGS/xash3d-fwgs/assets/47604048/dcc62970-777e-4e84-a069-9fc46caeb214)

Дистрибутив: Garuda Linux (Arch based)

**Comment by a1batross** [comment]
Для 32-битного AppImage нужен 32-битный libfuse.

Могу предложить либо перейти на Flatpak версию, либо собирать из исходников.

**Comment by Nord1cWarr1or** [comment]
> Могу предложить либо перейти на Flatpak версию, либо собирать из исходников.

Сорри за оффтоп, но почему эта версия сразу три версии драйвера ставит?
![изображение](https://github.com/FWGS/xash3d-fwgs/assets/47604048/18be3f6b-3c1f-4685-ba1d-5cd173b195d2)

**Comment by Nord1cWarr1or** [comment]
Понял, спасибо
