### ISSUE TITLE
Glitchy demos

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#1514]
Ещё я заметил что даже если демка воспроизводится, она получается не совсем корректной. 
Есть проблемы с анимацией выстрела, перезарядки, даже звук не воспроизводится при выстреле почему-то.
Это довольно часто происходит и не только у меня. Легко ловится на дробовике.
Пример демки: [minidemo_07_241123.zip](https://github.com/FWGS/xash3d-fwgs/files/13506340/minidemo_07_241123.zip)

**Comment by a1batross** [comment]
Это пока что норма, к сожалению.

**Comment by a1batross** [comment]
Частично пофикшено в https://github.com/FWGS/xash3d-fwgs/commit/3c28b1175452c6ff060a767595995e56ff276e40 и https://github.com/FWGS/xash3d-fwgs/commit/c56e87604385ee61571d9ff77ffe1a520c20dca3

**Comment by a1batross** [comment]
Если будут какие-то ещё проблемы, создай ещё одну ишшью с конкретной демкой и объяснением что не так.

**Comment by 0x4E69676874466F78** [comment]
Спасибо, попробую.
