### ISSUE TITLE
Xash Error on Linux Mint. 64 bit appimage.

### ISSUE THREAD

**Issue by BigClarky** [FWGS/xash3d-fwgs#1517]
Xash Error

"Host_InitError: can't initialize cl_dlls/client_amd64.so: Failed ti find library  cl_dlls/client_amd64.so
 cl_dlls/client_amd64.so: cannot open shared object File: No such file or directory"

Yes I've tried building hlsdk and hlsdk-portable myself but neither one ever outputs .so files.
Yes I've searched for this issue and found no real fix.
I tried running the flatpak version but it doesn't even run.
I also tried running the i386 AppImage but that doesn't run on a 64 bit distro.
I eve tried running both the amd64 and i386 tar.gz builds butneither of those would run.

**Comment by nekonomicon** [comment]
> Yes I've tried building hlsdk and hlsdk-portable myself but neither one ever outputs .so files.

Any logs?

> I also tried running the i386 AppImage but that doesn't run on a 64 bit distro.

Install multilib.

**Comment by BigClarky** [comment]
>Any logs?

Unfortunately not at the moment because I reinstalled Mint due to another unrelated bug.
>Install multilib.

What does multilib do and how do I use/install it?

**Comment by nekonomicon** [comment]
> What does multilib do

Provides 32-bit libraries on 64-bit linux distros at least.

> how do I use/install it?

Google search: `<distroname> multilib/multiarch`

**Comment by BigClarky** [comment]
alright I've done that now

**Comment by nekonomicon** [comment]
You need to provide additional build flags if you want to compile 64-bit hlsdk binaries on amd64.
`-8` for waf and `64BIT` for cmake.

**Comment by BigClarky** [comment]
```
cmake -B build -S . 
cmake --build build
```
where do I place the 64BIT flag?

**Comment by BigClarky** [comment]
This actually worked! thank you so much!

I took these newly 64bit compiled .so files and placed the min the correct folders and the game actually launched!
