### ISSUE TITLE
Couldn't load /cl_dlls/client.so

### ISSUE THREAD

**Issue by NovaAssistant** [FWGS/xash3d-fwgs#152]
I'm running the Linux app-image (i686, newest release) and am encountering a simple error were Xash fails to load a non-existent file "client.so"

**Comment by NovaAssistant** [comment]
never mind, after some digging I figured it out

**Comment by NovaAssistant** [comment]
Never mind again, apparently I didn't figure it out, and despite the fact I have gotten the client.so file it wont work

**Comment by a1batross** [comment]
What's the problem? Just use Steam and get latest Half-Life. It has everything we need.

**Comment by NovaAssistant** [comment]
well, I don't know and the file is exactly were its telling me it isn't

**Comment by a1batross** [comment]
Again, did you got your game files from Steam? I'm not gonna provide any support if you pirated it. Linux binaries are downloaded automatically if you get Half-Life from Steam on Linux.

**Comment by NovaAssistant** [comment]
I think I screwed something up somewhere being an idiot, either that or its my potato computer. Probably cant handle it any way
