### ISSUE TITLE
[Menu Suggestion] Remove bottom tooltip/hint

### ISSUE THREAD

**Issue by OpenRift412** [FWGS/xash3d-fwgs#1521]
The addition of the menu tooltips at the bottom of the screen seems a bit redundant, as they already show up next to the menu items to begin with, so it's just taking up vertical space. Not entirely sure how this would be useful for mods that don't have data for these tooltips either.

![image](https://github.com/FWGS/xash3d-fwgs/assets/29780788/222dd6bf-26e1-45c5-8959-1c8253fe4422)

**Comment by a1batross** [comment]
Oh, it's actually a bug. It seems was added pretty early in mainui_cpp development, so I didn't took notice.

See the check in original mainui:
```c
        if( item && ( item->flags & QMF_HASMOUSEFOCUS && !( item->flags & QMF_NOTIFY )) && ( item->statusText != NULL ))
```

And check in mainui_cpp:
```c
	if( item && item == lastItem && ( ( statusText = item->szStatusText ) != NULL ) )
```

**Comment by a1batross** [comment]
Fixed https://github.com/FWGS/mainui_cpp/tree/b1f8d5c3697acfc3bad4f1ddbb9d966570d1428a
