### ISSUE TITLE
--enable-bsp2 causing ref_soft error during build phase

### ISSUE THREAD

**Issue by bk4928412** [FWGS/xash3d-fwgs#1527]
everytime i try to build, batch script throws this error, this only happens when i force bsp2. not sure if the issue is on my end but im gonna leave it here just in case if its a bug

![ref_soft](https://github.com/FWGS/xash3d-fwgs/assets/134561653/0c4adb86-754a-41a9-99ef-45c0312cc660)

**Comment by a1batross** [comment]
Unfortunately, ref_soft is incompatible with BSP2 right now.

**Comment by a1batross** [comment]
You can disable building ref_soft by using `--disable-soft` key.
