### ISSUE TITLE
Поддержка OpenAL Soft

### ISSUE THREAD

**Issue by Gr33nEyes** [FWGS/xash3d-fwgs#1529]
Поддерживает ли данный движок OpenAL Soft?

**Comment by nekonomicon** [comment]
Нет.
А смысл?
У движка свой DSP и вывод звука осуществляется через SDL2, либо напрямую через alsa или OpenSL ES.

**Comment by Gr33nEyes** [comment]
То есть, нет смысла использовать альтернативный звуковой движок вроде MetaAudio?

**Comment by SNMetamorph** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/762

**Comment by nekonomicon** [comment]
> То есть, нет смысла использовать альтернативный звуковой движок вроде MetaAudio?

На сколько я знаю MetaAudio использует MetaHook.
А сам MetaHook имитирует поведение модуля hl.exe движка GoldSource и первым делом он пытается инициализровать модуль hw.dll и за ним подгружает filesystem_stdio.dll, а после всего прочего ставит хуки на определенные функции в движке.
Проблема в том, что xash3d имеет другие наименования модулей и другую архитектуру.
Иными словами MetaHook его не поддерживает.

Вообще полную совместимость с OpenAL в плане эффектов имеет [miniadio](https://miniaud.io/) и если есть какие-то навыки кодинга практичней прикрутить к своему моду будет его.

**Comment by a1batross** [comment]
Когда-нибудь мы сделаем SoundAPI и можно будет прикрутить хоть OpenAL Soft, хоть что.
