### ISSUE TITLE
Защитник Windows помечает Xash как вредоносный файл

### ISSUE THREAD

**Issue by Gr33nEyes** [FWGS/xash3d-fwgs#1531]
В последнее время защитник Windows триггерится на исполняемый файл движка

**Comment by Gr33nEyes** [comment]
![image](https://github.com/FWGS/xash3d-fwgs/assets/40704849/b8fddf68-bdb9-4e77-9aa4-76a4dce50d7e)

**Comment by nekonomicon** [comment]
Дубль:
https://github.com/FWGS/xash3d-fwgs/issues/1385
https://github.com/FWGS/xash3d-fwgs/issues/1314

**Comment by SNMetamorph** [comment]
Я думаю нам нужно какой-то дикслеймер в README.md сделать по этому поводу
