### ISSUE TITLE
Avast Detects Trojan and Malware while installing i386 version of Xash 

### ISSUE THREAD

**Issue by john123903** [FWGS/xash3d-fwgs#1536]
why.

**Comment by nekonomicon** [comment]
Duplicated:
https://github.com/FWGS/xash3d-fwgs/issues/1385
https://github.com/FWGS/xash3d-fwgs/issues/1314

**Comment by Lordalt** [comment]
because avsat detects everything as a virus, even itself sometimes. i would just suggest uninstalling that and installing something thats acctually good or even not using any antivirus just like me

**Comment by john123903** [comment]
> because avsat detects everything as a virus, even itself sometimes. i would just suggest uninstalling that and installing something thats acctually good or even not using any antivirus just like me

Woah woah woah, fix your spelling bro.
