### ISSUE TITLE
Serious issues that render Xash3D useless on Windows

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#1538]
Issue 1 - Game settings reset every time starting a server
Issue 2 - Dedicated server crashes with bots on Windows
Issue 3 - The game is a lot darker than GoldSrc even at max brightness
Issue 4 - Third-party bots (POD-Bot) still doesn't work with Xash3D!
Issue 5 - rocket_frenzy crashes with Parabot
Issue 6 - jk_botti doesn't work at all
Issue 7 - After a restart, the game screws itself up (Spamming "Written bytes null" etc. crap)
If the developers keep adding new features before fixing the existing issues that didn't exist on the previous version (0.19.2), then this engine will never be completed and it will be like ReactOS (I know this isn't a valid comparison, they work harder than you to fix their shit at least).

Cool, then why don't you play with 0.19.2?
Issues again:
In VGUI games CTRL key stops working after interaction with VGUI (only thing fixed in 0.20 xD)
@kungfulon 's VGUI2 compatibility version isn't based on it (very brilliant choice right?)

I won't return back to this issue, because I know that you won't give a crap. Shameful, weeb!

**Comment by nekonomicon** [comment]
> Issue 6 - jk_botti doesn't work at all

jk_botti required patched metamod at least.

**Comment by SNMetamorph** [comment]
> If the developers keep adding new features before fixing the existing issues that didn't exist on the previous version (0.19.2)

Funny to hear that since 0.19.x was bugged and laggy af

**Comment by nekonomicon** [comment]
> Funny to hear that since 0.19.x was bugged and laggy af

+1.
0.19.x has many render and client prediction bugs.

**Comment by a1batross** [comment]
Make a new issue per bug.

**Comment by mittorn** [comment]
Dedicated server is really untested and i'm not sure that config works ok. Old engine exec'ed server.cfg on every restart, it keeped settings set from menu if it writed [listen]server.cfg or configured by user and applied on every restart
For this issue, it should be closed as invalid, but testing dedicated server moreand creating separate issues is welcome
