### ISSUE TITLE
Custom MASTERSERVER_ADR for Yggdrasil / IPv6 network

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1539]
I want to run Xash3D with custom `master server` for IPv6 / ([Yggdrasil](https://github.com/yggdrasil-network)) nodes only

After change `MASTERSERVER_ADR`  in `engine/common/netchan.h` to some address like `[xxx:xxx:xxx::]:27010` 
on connection attempt to the internet servers in HF, I get following error in debug mode `xash3d -dev 2`:

```
Error: Could not get TCP/IPv6 address, Invalid hostname: 'local host name'
```

I think it could be related to Yggdrasil's `0200::/7` validation in `engine/common/net_ws.c`

```
if( NET_StringToAdrEx( buff, &net6_local, AF_INET6 ))
```

**Comment by mittorn** [comment]
For host addres, i am getting this error for real IPV6naddress, writing ipv6 address and hostbame to /etc/hosts helps. Maybe we need some different way to detect ip addresses

**Comment by mittorn** [comment]
We already have dynamic masterserver list, check listmadters/addmaster commands
hard-coded addres is only default

**Comment by mittorn** [comment]
It is console command, try write itin config, or server.cfg if it's dedicated

**Comment by a1batross** [comment]
> It is console command, try write itin config, or server.cfg if it's dedicated

There is a `xashcomm.lst` file they are saved to. I do not recommend editing it directly, instead use `addmaster` command in console. It must be saved automatically to that file. 

Engine doesn't create it if the user hasn't specified custom master servers.
