### ISSUE TITLE
Unable to load libxash.so

### ISSUE THREAD

**Issue by Drackoy2** [FWGS/xash3d-fwgs#154]
I'm trying to run Xash3d on a Raspberry Pi Zero W with Raspbian (Debian). I've successfully compiled the program and I have the executable and .so files. I've tried placing them directly in the valve directory and alongside the valve directory. I keep getting the error:

`Xash Error: Unable to load the libxash.so: cannot open shared object file: No such file or directory`

Libxash.so is in the same directory as the executable.

I saw a very similar problem for the archived Xash3d engine but I didn't understand the answer. Sorry if this is an obvious problem.

**Comment by a1batross** [comment]
`LD_LIBRARY_PATH=$(pwd) ./xash3d`

**Comment by Drackoy2** [comment]
I'm sorry, I'm an idiot. To anyone else who has this problem, just do some reading. It takes a while but it's not hard.

And great work guys, with any luck I'll have Half-Life on my portable Raspberry.
