### ISSUE TITLE
Self-hosted solution for master server

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1540]
Could you please explain about software using for `mentality.rip:27010` in `engine/common/netchan.h` or any open source alternatives for HF master server?

I just want to run another instance for alt net, but formally it's like internet connection (Yggdrasil)

thanks

**Comment by SNMetamorph** [comment]
https://github.com/FWGS/pymaster

**Comment by a1batross** [comment]
Hm...

Did you add support for parsing V6 addresses in engine? Current `master` branch doesn't know how to parse V6 packets from master.

I did a quick patch, try rebuild engine with it: 

```diff
diff --git a/engine/client/cl_main.c b/engine/client/cl_main.c
index 5ca07ef1..fb4eada4 100644
--- a/engine/client/cl_main.c
+++ b/engine/client/cl_main.c
@@ -2191,9 +2191,20 @@ void CL_ConnectionlessPacket( netadr_t from, sizebuf_t *msg )
 		// serverlist got from masterserver
 		while( MSG_GetNumBitsLeft( msg ) > 8 )
 		{
-			MSG_ReadBytes( msg, servadr.ip, sizeof( servadr.ip ));	// 4 bytes for IP
+			uint8_t addr[16];
+
+			if( from.type6 == NA_IP6 ) // IPv6 master server only sends IPv6 addresses
+			{
+				MSG_ReadBytes( msg, addr, sizeof( addr ));
+				NET_IP6BytesToNetadr( &servadr, addr );
+				servadr.type6 = NA_IP6;
+			}
+			else
+			{
+				MSG_ReadBytes( msg, servadr.ip, sizeof( servadr.ip ));	// 4 bytes for IP
+				servadr.type = NA_IP;
+			}
 			servadr.port = MSG_ReadShort( msg );			// 2 bytes for Port
-			servadr.type = NA_IP;
 
 			// list is ends here
 			if( !servadr.port )
```

**Comment by a1batross** [comment]
>another masters could accept and return both protocol addresses

I think if a user can connect to v6 master server, they already have a way to connect to v6 servers. Same for v4. There isn't any reason to make this more complicated than it is.

Thanks for testing this, I will just apply that patch now.

**Comment by a1batross** [comment]
And Rust implementation is opensource now:

[xash3d-master](https://git.mentality.rip/numas13/xash3d-master)

**Comment by SNMetamorph** [comment]
Of course I have Yggdrasil. And yeah, I tested this and it works good.
