### ISSUE TITLE
IPv6 mask for MS_SCAN_REQUEST

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1541]
I want to use client filter with any port allowed for IPv6 `200::/7`, how can I properly provide that mask?

engine/common/netchan.h

```
#define MS_SCAN_REQUEST		"1\xFF" "0.0.0.0:0\0"
```

**Comment by a1batross** [comment]
The protocol doesn't really exist yet. You're free to do whatever you want for IPv6 queries.
