### ISSUE TITLE
 Could not setup pymaster server

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1542]
I'm trying to setup [pymaster](https://github.com/FWGS/pymaster) server, but seems this solution abandoned a bit

`python3 pymaster.py -i 0.0.0.0 -p 27010`:

```
Welcome to PyMaster!
I ask you again, are you my master?
Running on 0.0.0.0:27010
Client Query: xx.xx.xx.xx:58281, invalid infostring=0.0.0.0:0\gamedir\valve\clver\0.20\nat\0\key\445cdb41
```

`xash3d -dev 2`:

```
CL_ConnectionlessPacket: xx.xx.xx.xx:27010 : f
[09:23:33] Warning: invalid server list packet from xx.xx.xx.xx:27010 (missing extra header)
```

`engine/client/cl_main.c`
```
// check the extra header
if( MSG_ReadByte( msg ) == 0x7f )
```

Sent few PR there, would be nice to enable Issues feature.

**Comment by nekonomicon** [comment]
Yep, really @a1batross already use modified version with some additions + some people already rewrote master server to rust, but AFAIK source code not released yet.

**Comment by a1batross** [comment]
After the header goes an extra header used to validate the query random key.

It's detected by `0x7f` byte (reserved 127.0.0.0/8 network, so it's backwards compatible), and after that 5 extra bytes. 4 bytes are used for the random key (it's sent from the query) and 1 byte is reserved.
