### ISSUE TITLE
Illegal ?

### ISSUE THREAD

**Issue by Al-fata-tayeb** [FWGS/xash3d-fwgs#1550]
Does this engine a illegal thing " somehow ? "

Does really I need to buy a half life copy from steam ?

Sorry for my bad English

**Comment by nekonomicon** [comment]
> Does this engine a illegal thing " somehow ? "

https://github.com/FWGS/xash3d-fwgs/issues/63

https://web.archive.org/web/20180508095125/http://www.moddb.com/mods/half-life-subtitles-mod/news/sad-news-legal-issues-lack-of-time

> Does really I need to buy a half life copy from steam ?

Yes.
