### ISSUE TITLE
sr.ht migration

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1552]
Clickbait title!

I don't think it makes sense to move from GitHub, but we're (me and @mittorn) has tried using sr.ht for engine development, and it was mostly fine for both of us. 

What I want is to have another development mirror just in case there will be issues with GitHub (we already had the "sanctions" plaque on the `xash3d` repository, I already was banned on GitHub once, and already lost 2FA once earlier this month, and so on), so I don't have to stop working on the engine while trying to restore access to GitHub.

I think sr.ht having the classic, email-based workflow, forces following some of the contribution rules we already have. I understand that's a controversial topic, and I'm still not a fan of emails, but I think we can handle it. At least, until Forgejo gets federation support. Also, sr.ht frontend is pretty lightweight, which compared to GitHub (not to mention GitLab, ew) is a giant advantage.

Here goes the To-Do list on what we need to do to have SourceHut as a viable alternative for developers and contributors:

- [ ] We need Documentation/ports.md converted to MAINTAINERS file and extend it. Maintainers could leave their email address and/or GitHub handle. For that, we could have something similar to Linux kernel's `scripts/get_maintainer.pl` script (except I don't want to bring Perl dependency here, as I probably will rewrite that in Python). For GitHub, it might be possible to set up a bot that will automatically assign a PR to a specific port maintainer.

- [ ] SourceHut need to be properly advertised in documentation: the repository clone URL, the mailing list email address and so on. 

- [ ] Other FWGS projects need to also set up the mirrors. I'm not sure whether @nekonomicon would like to migrate `hlsdk-portable`, but since I'm working on `vgui_support` and `mainui_cpp`, I can do that.

- [x] builds.sr.ht looks pretty awesome. It supports all the three main *BSDs (@nekonomicon), compared to GitHub Actions.

**Comment by nekonomicon** [comment]
> I'm not sure whether @nekonomicon would like to migrate hlsdk-portable

I don't mind. I like new things and hate legacy.

**Comment by jeefo** [comment]
Politics about sanctions on github is very unclear, for example: https://github.com/FWGS/regamedll is marked as sanctioned too for an unknown reason:
![image](https://github.com/FWGS/xash3d-fwgs/assets/1781346/7545da87-bdc6-476c-9077-f8398eb22d17)

**Comment by a1batross** [comment]
@jeefo yeah, they already marked FWGS restricted. However, as support said, it only restricts us from paid services. Using GitHub for free is fine... for now.

@nekonomicon that's cool. :)

**Comment by a1batross** [comment]
builds.sr.ht integration: DONE
