### ISSUE TITLE
cygwin 

### ISSUE THREAD

**Issue by erfty125** [FWGS/xash3d-fwgs#1554]
можно ли собрать ксаш под cygwinом и если нет, то планируется ли cygwin для сборки КСАША? (забыл question label поставить)

**Comment by nekonomicon** [comment]
Сборка под cygwin'ом не отличается от сборки mingw.
Практического смысла мало, так как это все использует свой runtime и свою декорацию имен, не совместимые с MSVC.

**Comment by a1batross** [comment]
Cygwin нужен в первую очередь для очень специфичного *nix софта. 

Для нас он не просто бесполезен, а бесполезен в квадрате.

**Comment by erfty125** [comment]
> Cygwin нужен в первую очередь для очень специфичного *nix софта. 
> 
> Для нас он не просто бесполезен, а бесполезен в квадрате. 

да я просто щас трогаю idf для esp8266 и там как раз на основе cygwin всё сделали, сразу появилась идея это же и для КСАША применить, но ладно, кастомный shell в руки и можно собирать

**Comment by a1batross** [comment]
@erfty125 ну правильно. Скорее всего какая-то часть тулчейна прибита к юниксам.
