### ISSUE TITLE
IPv6 in sv_downloadurl

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1559]
Does `sv_downloadurl` in `valve/server.cfg` support IPv6?

I can download resources trough IPv4 protocol only - just need IPv6 for Yggdrasil connections.

**Comment by mittorn** [comment]
No, it's ipv4-only

**Comment by a1batross** [comment]
The HTTP client implementation is in net_ws.c file. I believe, it only needs to specify any matching protocol family instead of just IPv6 for our getaddrinfo/gethostbymame wrapper function.

sv_downloadurl however only allows to set only one address.

**Comment by mittorn** [comment]
Old xash3d allowed to specify multiple urls in sv_downloadurl delimited with spaces. Is not new engine allow this?

**Comment by oooo-ps** [comment]
Is this option not officially implemented to work with IPv6?

If no, can I disable this feature on the client side, to prevent external (internet) connections?

**Comment by nekonomicon** [comment]
> Is this option not officially implemented to work with IPv6?

It's fastdl %)
And new cvar from this PR is completely useless.
