### ISSUE TITLE
Unknown Command 'trysaveconfig' PS Vita

### ISSUE THREAD

**Issue by Haasman0** [FWGS/xash3d-fwgs#1561]
Every time I try to change the character or user name, it gives unknown command 'trysaveconfig' error in console. I think this is only present on PS Vita version. Is there a way to fix it?

**Comment by a1batross** [comment]
It's a legacy from the old engine. I'm still not sure whether the feature must be restored or completely dropped here, as it was mainly done for Android ports.

**Comment by Haasman0** [comment]
It is just annoying to change it manually in the config.cfg. It could be cool if it worked. Btw it gave this error when I used the 25th anniversary update of HL files.
________________________________

**Comment by a1batross** [comment]
The config files are saved when you properly exit the engine, like through Quit button in the menu. 

On Android the trysaveconfig helped to avoid the issue when the engine is forcibly killed, but only for menu options, of course it help if the user changed some settings directly from the console.

**Comment by Haasman0** [comment]
Ok I understand now, thanks!
________________________________
