### ISSUE TITLE
RSS for new server connections

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1562]
I want to make notification for subscribers when new player becomes online

is there any plugins or ideas how to implement this from debug log or with server API?

thanks

**Comment by a1batross** [comment]
There is an sv_log feature that writes logs to a file or sends them to a
remote server. It's compatible with GoldSrc, and even worked with
HLStats(X).

пт, 5 янв. 2024 г., 17:19 d47081 ***@***.***>:

**Comment by SNMetamorph** [comment]
> I want to make notification for subscribers when new player becomes online
> 
> is there any plugins or ideas how to implement this from debug log or with server API?
> 
> thanks

Also you just can use separate program that periodically send queries to server to get players count, and then publishes message to RSS that new player has arrived, etc.

**Comment by mittorn** [comment]
Use logaddress, it will report connections to specified server withput any periodical queries
