### ISSUE TITLE
Users authorization

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1564]
Hello, 

I have created open source web [app](http://94.140.114.89/hl/) to collect HL servers info (it's Yggdrasil-oriented project)

Would be nice to count users stats, and make ratings there but everyone able to login with same name.
Is there any solution to make verified users auth on server and keep guest connections?

Thanks!

**Comment by a1batross** [comment]
Unfortunately, there isn't really anything like this.

Yes, there are XashIDs that generated from hardware info, but it's easy to fake them.

**Comment by SNMetamorph** [comment]
> If no solution exists I thought about something like connection flag e.g. `-connect host:port -key 123`
> 
> hardware info is not an option, imho

Probably, "setinfo" can be used for this. AMX Mod X by default uses password authentication with setinfo "_pw"

**Comment by a1batross** [comment]
I don't think it's something that a game engine should solve.
