### ISSUE TITLE
New server not listed in search

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1565]
I have launched new server `94.140.114.89:27015` but it is not available in the internet servers list.

Master server is default - `mentality.rip`, maybe some separated registry available to participate or my instance does not correspond some requirements?

Sorry if my question duplicated

**Comment by a1batross** [comment]
Did you set `sv_lan 0` and `public 1`?

I'm not seeing any requests on my side.

**Comment by a1batross** [comment]
Just change the DLL path in gameinfo.txt.
