### ISSUE TITLE
Generated listenserver.cfg conflicts with GoldSource

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#157]
I have a mod in my steam Half-Life directory. I have a separate directory for Xash3D and it has a symlink to this mod directory in it, so the mod directory is shared between Steam Half-Life and Xash3D for easier testing on both engines. If I start a listenserver under Xash3D it produces listenserver.cfg in the mod directory which leads to that I can't run listenserver when running a mod via Steam Half-Life.
GoldSource just stops at
```
execing listenserver.cfg
Setting gamedir to mod
```
and does not proceed to actually load a map.

The `gamedir` command seems to be an issue for GoldSource.

**Comment by a1batross** [comment]
Seems was fixed in https://github.com/FWGS/xash3d-fwgs/commit/77bebe3000f62937fc785c119c4c6e1ed8bc2d8b
