### ISSUE TITLE
Is HL2 compatible with xash3d?

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1570]
I found leaked source engine and it works on my build
https://github.com/nillerusr/source-engine

What about xash3d by fwgs?

**Comment by AruMoon** [comment]
> I found leaked source engine and it works on my build
> https://github.com/nillerusr/source-engine
> 
> What about xash3d by fwgs?

It's 2 completely different engines. Xash3d runs only goldsource-compatible games

**Comment by perondeidad** [comment]
fteqw can do.
