### ISSUE TITLE
Building with WAF uses GCC instead of MSVC

### ISSUE THREAD

**Issue by flashintv** [FWGS/xash3d-fwgs#1572]
I've tried using most of the avaliable commands to try and force the compiler to stop using GCC, like check-c-compiler and check-cxx-compiler, nothing seems to work.
[config.log](https://github.com/FWGS/xash3d-fwgs/files/13923212/config.log)

**Comment by a1batross** [comment]
Rerun configure with `-vv` and post the log.

**Comment by flashintv** [comment]
[config.log](https://github.com/FWGS/xash3d-fwgs/files/13923346/config.log)
Here

**Comment by a1batross** [comment]
??? 

Isn't it used MSVC now? I'm seeing MSVC invocations.

**Comment by flashintv** [comment]
yeah sorry it fails GCC linking

**Comment by a1batross** [comment]
I don't see an error here. The engine is supposed to build with MSVC only on Windows, and I in config it's using it for the configuration tests, which means it detected MSVC as a working C/C++ compiler.

Somehow it picks "gas, gcc" and "ar", which doesn't really make sense. Waf's msvc.py automatically extracts all installed MSVC-like compilers, and maybe it tries to look like MSVC in vswhere output or registry.

Well, that's what you get with polluted PATH and registry on Windows, truly a useless OS for development.

**Comment by a1batross** [comment]
Try to run build with it, maybe it will be fine. 

Also, we have prebuilt Windows binaries, if you want to play some HL1 mods: https://github.com/FWGS/xash3d-fwgs/releases/download/continuous/xash3d-fwgs-win32-i386.7z (though Microsoft AV software gets angry at it, and I'm not sure why)

**Comment by flashintv** [comment]
> Try to run build with it, maybe it will be fine.
doesn't work tried it multiple times

**Comment by a1batross** [comment]
post a whole log then, idk

**Comment by flashintv** [comment]
> post a whole log then, idk

I think I fixed it by recloning the repository, thanks for help.
