### ISSUE TITLE
linux: building xash dedicated server has no executable

### ISSUE THREAD

**Issue by DeltaLima** [FWGS/xash3d-fwgs#1576]
Hi there!
I found out that building xash dedicated server under linux does not work as expected at the moment. 

What I expect: getting an executable `xash` and library `filesystem_stdio.so`
What I get: just `libxash.so` instead of `xash` executable. This does not occur on at commit #0132eb6e44cb4a414d400c9ba42e5b4a94dcb590 or earlier

```
Waf: Entering directory `xash3d-installscript/lol/build/xash3d-fwgs/build'
+ install xash3d-installscript/lol/build/xash3d-fwgs/bin/filesystem_stdio.so (from build/filesystem/filesystem_stdio.so)
+ install xash3d-installscript/lol/build/xash3d-fwgs/bin/libxash.so (from build/engine/libxash.so)
Waf: Leaving directory `xash3d-installscript/lol/build/xash3d-fwgs/build'

```

What I do:

```
./waf configure -T release -d --enable-tests --enable-lto
./waf build 
./waf install --destdir=../../lol
```

I took all neccessary steps from https://github.com/FWGS/xash3d-fwgs/blob/master/scripts/gha/build_linux.sh

I am running Debian 12 64 bit and installed the packages according to the README.md. 

In the releases of the dedicated server (https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous) there is also no executable in the tarball.

Best greetings! :)

**Comment by a1batross** [comment]
Thanks for report!

Fixed in https://github.com/FWGS/xash3d-fwgs/commit/a247e139bfeb8699ad4b2b32b1068e839a8d38fc
