### ISSUE TITLE
[MOD: Headcrab Frenzy] Глюки с текстурами пола

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1580]
На последнем билде движка, текстуры пола могут быть чёрными, либо вместо неё может быть какая-то случайная текстура, которая отдаляется или приближается, смотря в какую сторону идти.

Вот видео с этим багом.
https://youtu.be/YALPhtMu8QY?si=oh4mzMef7d_Pvji9

А вот просто чёрный пол. Скриншот сделан на карте hcf_range, но этот баг проявляется и на других картах.
![hcf_range_0001.png](https://github.com/FWGS/xash3d-fwgs/assets/22411953/1e7ec69e-cb0e-40e3-88f4-da4fee1e066a)

При записи видео и снятии скриншота, VBO рендерер был отключен.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3211
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/40041e30eb0dd93b6484c2b0057b21e3b70c15e3
Ветка: master

**Comment by a1batross** [comment]
А я говорил, что с glGenTextures всё равно какая-то фигня получилась.

gl_texturenum в surface_t должен быть номером GL объекта, а не номером текстуры в массиве движка.

**Comment by a1batross** [comment]
Fixed https://github.com/FWGS/xash3d-fwgs/commit/260edc2a08ea6ca3e34e93e807eb8e821c237c14
