### ISSUE TITLE
[MOD: Sands of War] Не удаётся запустить сервер

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1582]
В консоли появляется следующая ошибка:
```
Host_Error: CL_SetupPMove: ps->number == 0
```
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/13951651/engine.log)

Ссылка на мод:
https://www.moddb.com/mods/sands-of-war/downloads/sands-of-war-16

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3211
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/40041e30eb0dd93b6484c2b0057b21e3b70c15e3
Ветка: master

**Comment by a1batross** [comment]
Всё-таки что-то не так с этим.

Получается будто сервер спавнит клиента через кадр после подключения клиента. Но такого быть не должно, слот сразу занимается клиентом.

**Comment by a1batross** [comment]
Пробовал отлаживать, всё равно мне не ясно как эта ситуация вообще может происходить.

Убрал Host_Error в a508467a.
