### ISSUE TITLE
Проблема при сборки xash

### ISSUE THREAD

**Issue by Artem-coderh** [FWGS/xash3d-fwgs#1586]
Когда я компилирую xash на линукс то я получаю ошибку:

```
[ 81/275] Compiling engine/platform/linux/sys_linux.c
../engine/platform/linux/sys_linux.c: In function 'Linux_SetTimer':
../engine/platform/linux/sys_linux.c:153:20: error: 'struct sigevent' has no member named '_sigev_un'
  153 |                 sev._sigev_un._tid  = gettid();
      |                    ^

Waf: Leaving directory `/home/artem/xash/build'
Build failed
 -> task in 'xash' failed with exit status 1 (run with -v to display more information)
``` 
Использую Alpine Linux 3.19 x64

**Comment by a1batross** [comment]
Скорее всего в musl поля у структуры немного иначе зовутся

**Comment by Artem-coderh** [comment]
а как тогда это исправить

**Comment by Artem-coderh** [comment]
в общем я не смог исправить эту ошибку по этому я запустил в chroot Debian Sid. a1batross исправь эту ошибку пожалуйста

**Comment by a1batross** [comment]
Пофикшено. 

У нас теперь есть автоматические сборки под последний стабильный релиз Alpine: https://builds.sr.ht/~a1batross/xash3d-fwgs/commits/master/alpine.yml
