### ISSUE TITLE
SDL2 sanity check fail

### ISSUE THREAD

**Issue by degradka** [FWGS/xash3d-fwgs#1592]
Hello, so, I'm **trying** to cross-compile for windows from Linux, and MSVC installed just fine. I've downloaded SDL2-devel-2.28.5-VC from libsdl.org and waf gives me the sanity check fail. If I skip the sanity check, the compiler fails on port.h:
```
Z:\media\drive300\xashstuff\xash3d-fwgs\common\port.h(90): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
etc...
```
Log file with the sanity check:
`./waf configure -T release -8 --enable-msvc-wine --sdl2=../SDL2-2.92.2 -vv`
[config.log](https://github.com/FWGS/xash3d-fwgs/files/14069874/config.log)
Compile logs without it:
`./waf configure -T release -8 --enable-msvc-wine --sdl2=../SDL2-2.92.2 --skip-sdl2-sanity-check -vv`
`./waf build`
[compile.log](https://github.com/FWGS/xash3d-fwgs/files/14069883/compile.log)

P.S. I know this issue was posted a bunch of times, but I couldn't resolve it using solutions provided in other issues

**Comment by nekonomicon** [comment]
You need to download development SDL2 package.

**Comment by degradka** [comment]
It is the development package 
> SDL2-devel-2.28.5-VC

**Comment by degradka** [comment]
OMG I'm fucking stupid, it wasn't.
