### ISSUE TITLE
Running Counter-Strike (legacy version) in Xash3D 0.20 Mouse Not Working

### ISSUE THREAD

**Issue by byoreo** [FWGS/xash3d-fwgs#1595]
I opened Counter Strike with Velaron's client, but the mouse is not detected.

**Comment by mittorn** [comment]
Should it work at all? Old cs16client versions not allowed any mouse, 
maybe it's still not allowed. Use touchscreen, joysticks or play with 
keyboard

**Comment by a1batross** [comment]
I'm not sure that old CS16Client will even work with the new engine, it's probably will crash at start. I myself was patching it to newer RenderAPI calls, when I needed to do something with the CS.

Use newer one by @Velaron, it's hosted at https://github.com/Velaron/cs16-client. I tried it and it works as is.
