### ISSUE TITLE
Сломался рендер в cs1.6

### ISSUE THREAD

**Issue by ArtemS2** [FWGS/xash3d-fwgs#1596]
![Снимок экрана от 2024-01-30 15-30-00](https://github.com/FWGS/xash3d-fwgs/assets/69766464/f126f870-6649-4b35-a63d-38fce5320ee0)

**Comment by a1batross** [comment]
Ну... и что?

Да, сломался, вижу на картинке. Как ты такого эффекта-то добился? Хоть какую-то дополнительную информации сможешь из себя выдавить?

**Comment by Velaron** [comment]
Выглядит как очень жестко выкрученная гамма текстур?

**Comment by ArtemS2** [comment]
Попробовал ./xash3d -game cstrike &> new.log , получил 
[new.log](https://github.com/FWGS/xash3d-fwgs/files/14097807/new.log)

**Comment by a1batross** [comment]
Ну записал ты пустой лог, что толку-то?

Я спрошу ещё раз: 

```
Как ты такого эффекта-то добился? Хоть какую-то дополнительную информации сможешь из себя выдавить?
```

**Comment by ArtemS2** [comment]
Я просто пересобрал исходники движка и зашел в cs, если откатываюсь на прошлые бинарники , то все нормально

**Comment by ArtemS2** [comment]
Есть идеи как можно словить изменения?

**Comment by nekonomicon** [comment]
Назови хэши старого и нового коммитов.

**Comment by a1batross** [comment]
Смотришь версию старого бинарника, смотришь версию текущего.

git bisect good <версия старого>
git bisect bad <версия нового>

Пересобираешь, проверяешь. Если сломано, прописываешь git bisect bad, если работает ок, прописываешь git bisect good.

**Comment by ArtemS2** [comment]
Чет ничего не называет

**Comment by ArtemS2** [comment]
git log -p -2
commit b290046503b29272355528992782159e2168e426 (HEAD -> master, tag: continuous, origin/master, origin/HEAD, refs/bisect/good-b290046503b29272355528992782159e2168e426)
Это стабильный

**Comment by ArtemS2** [comment]
commit f67736180bc6b915355359fd481304bded1b300f (HEAD -> master, tag: continuous-tw_port, tag: continuous-appveyor-test, tag: continuous, origin/master, origin/HEAD, refs/bisect/bad)
А это со сбоем рендера

**Comment by a1batross** [comment]
Платформа какая?

**Comment by a1batross** [comment]
Ну arm64? А дальше?

**Comment by ArtemS2** [comment]
Orange Pi5B Ubuntu Ubuntu 22.04.3 LTS aarch64

**Comment by ArtemS2** [comment]
При вводе git log -p -2 у репа со сломанным рендером такая инфа еще была:  engine: client: allow nearest filtering for loading and pause icons

diff --git a/engine/client/cl_scrn.c b/engine/client/cl_scrn.c
index 5e045765..a6303e64 100644
--- a/engine/client/cl_scrn.c
+++ b/engine/client/cl_scrn.c
@@ -648,21 +648,21 @@ void SCR_RegisterTextures( void )
        // register gfx.wad images
 
        if( FS_FileExists( "gfx/paused.lmp", false ))
-               cls.pauseIcon = ref.dllFuncs.GL_LoadTexture( "gfx/paused.lmp", NULL, 0, TF_IMAGE );
+               cls.pauseIcon = ref.dllFuncs.GL_LoadTexture( "gfx/paused.lmp", NULL, 0, TF_IMAGE|TF_ALLOW_NEAREST );
        else if( FS_FileExists( "gfx/pause.lmp", false ))
-               cls.pauseIcon = ref.dllFuncs.GL_LoadTexture( "gfx/pause.lmp", NULL, 0, TF_IMAGE );
+               cls.pauseIcon = ref.dllFuncs.GL_LoadTexture( "gfx/pause.lmp", NULL, 0, TF_IMAGE|TF_ALLOW_NEAREST );
 
        if( FS_FileExists( "gfx/lambda.lmp", false ))
        {
                if( cl_allow_levelshots.value )
-                       cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/lambda.lmp", NULL, 0, TF_IMAGE|TF_LUMINANCE );
-               else cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/lambda.lmp", NULL, 0, TF_IMAGE );
+                       cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/lambda.lmp", NULL, 0, TF_IMAGE|TF_LUMINANCE|TF_ALLOW_NEAREST );
+               else cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/lambda.lmp", NULL, 0, TF_IMAGE|TF_ALLOW_NEAREST );
        }
        else if( FS_FileExists( "gfx/loading.lmp", false ))
        {
                if( cl_allow_levelshots.value )
-                       cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/loading.lmp", NULL, 0, TF_IMAGE|TF_LUMINANCE );
-               else cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/loading.lmp", NULL, 0, TF_IMAGE );
+                       cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/loading.lmp", NULL, 0, TF_IMAGE|TF_LUMINANCE|TF_ALLOW_NEAREST );
+               else cls.loadingBar = ref.dllFuncs.GL_LoadTexture( "gfx/loading.lmp", NULL, 0, TF_IMAGE|TF_ALLOW_NEAREST );
        }
 
        cls.tileImage = ref.dllFuncs.GL_LoadTexture( "gfx/backtile.lmp", NULL, 0, TF_NOMIPMAP );

commit 725b7ea7f97cb8f5681d9985823c49a8accd6719
Author: Alibek Omarov <a1ba.omarov@gmail.com>
Date:   Mon Jan 29 05:59:06 2024 +0300

    common: render_api: rename TF_ALLOW_NEAREST_TOGGLE to just TF_ALLOW_NEAREST, it's just shorter

diff --git a/common/render_api.h b/common/render_api.h
index 47981e37..8ab2643c 100644
--- a/common/render_api.h
+++ b/common/render_api.h
@@ -108,7 +108,7 @@ typedef enum
        TF_NOCOMPARE    = (1<<27),      // disable comparing for depth textures
        TF_ARB_16BIT    = (1<<28),      // keep image as 16-bit (not 24)
        TF_MULTISAMPLE  = (1<<29),      // multisampling texture
-       TF_ALLOW_NEAREST_TOGGLE = (1<<30),      // allows toggling nearest filtering for TF_NOMIPMAP textures
+       TF_ALLOW_NEAREST = (1<<30),     // allows toggling nearest filtering for TF_NOMIPMAP textures
 } texFlags_t;
 
 typedef enum
diff --git a/engine/ref_api.h b/engine/ref_api.h
index 5cb1d474..ce11df90 100644
--- a/engine/ref_api.h
+++ b/engine/ref_api.h
@@ -46,8 +46,8 @@ GNU General Public License for more details.
 #define REF_API_VERSION 7
 
 
-#define TF_SKY         (TF_SKYSIDE|TF_NOMIPMAP|TF_ALLOW_NEAREST_TOGGLE)
-#define TF_FONT                (TF_NOMIPMAP|TF_CLAMP|TF_ALLOW_NEAREST_TOGGLE)
+#define TF_SKY         (TF_SKYSIDE|TF_NOMIPMAP|TF_ALLOW_NEAREST)
+#define TF_FONT                (TF_NOMIPMAP|TF_CLAMP|TF_ALLOW_NEAREST)
 #define TF_IMAGE               (TF_NOMIPMAP|TF_CLAMP)
 #define TF_DECAL               (TF_CLAMP)
 
diff --git a/ref/gl/gl_image.c b/ref/gl/gl_image.c
index 6bae8a33..1b602c87 100644
--- a/ref/gl/gl_image.c
+++ b/ref/gl/gl_image.c
@@ -131,7 +131,7 @@ qboolean GL_TextureFilteringEnabled( const gl_texture_t *tex )
                if( FBitSet( tex->flags, TF_ATLAS_PAGE ))
                        return gl_lightmap_nearest.value == 0.0f;
 
-               if( FBitSet( tex->flags, TF_ALLOW_NEAREST_TOGGLE ))
+               if( FBitSet( tex->flags, TF_ALLOW_NEAREST ))
                        return gl_texture_nearest.value == 0.0f;
 
                return true;
diff --git a/ref/gl/gl_warp.c b/ref/gl/gl_warp.c
index e2daa154..961ec55c 100644
--- a/ref/gl/gl_warp.c
+++ b/ref/gl/gl_warp.c
@@ -882,7 +882,7 @@ void R_InitRipples( void )
        pic.numMips = 1;
        memset( pic.buffer, 0, pic.size );
 
-       g_ripple.rippletexturenum = GL_LoadTextureInternal( "*rippletex", &pic, TF_NOMIPMAP|TF_ALLOW_NEAREST_TOGGLE );
+       g_ripple.rippletexturenum = GL_LoadTextureInternal( "*rippletex", &pic, TF_NOMIPMAP|TF_ALLOW_NEAREST );
 }
 
 static void R_SwapBufs( void )

**Comment by a1batross** [comment]
Теперь попробуй с git-bisect найти ломающий коммит.

Так как воспроизводится он только у тебя. 

У меня сейчас рядом свободных устройств с linux-arm64 нет.

**Comment by ArtemS2** [comment]
[logcom.log](https://github.com/FWGS/xash3d-fwgs/files/14098109/logcom.log)
Может это будет полезно ввел git log -p -2 у нового репа

**Comment by ArtemS2** [comment]
artem@artem-desktop:~/builds/xash3d-fwgs$ git bisect start 
Уже на «master»

Эта ветка соответствует «origin/master».
artem@artem-desktop:~/builds/xash3d-fwgs$ git bisect bad

artem@artem-desktop:~/builds/xash3d-fwgs$ git bisect good b290046
Бинарный поиск: 85 редакций осталось проверить после этой (примерно 7 шагов)
[cf7a79bff3e6dd6923cfe8bd7c1262a0ac751553] ref: gl: particles aren't supposed to care about gamma

**Comment by ArtemS2** [comment]
Мне получается нужно откатиться до cf7a79b?

**Comment by ArtemS2** [comment]
@a1batross cf7a79b - сломан, следующий  a29f1899d3f4d75120b390d50cb3c6bc521a44a3 работает

**Comment by a1batross** [comment]
Почитай документацию самостоятельно. Мне лень тебе второй раз объяснять.

https://git-scm.com/book/ru/v2/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9E%D0%B1%D0%BD%D0%B0%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-Git#r_binary_search

**Comment by ArtemS2** [comment]
a311923d4e0ca8c8f5d6fb5cb585c0c37b37bb62 is the first bad commit
commit a311923d4e0ca8c8f5d6fb5cb585c0c37b37bb62
Author: Alibek Omarov <a1ba.omarov@gmail.com>
Date:   Sat Jan 6 21:44:41 2024 +0300

    engine: imagelib: apply texgamma to palette (ideally should be applied only to BSP/WAD textures)

 engine/common/imagelib/img_utils.c | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)

**Comment by ArtemS2** [comment]
Вроде разобрался с помощью видоса на ютубе)

**Comment by a1batross** [comment]
Какое значение texgamma?

**Comment by ArtemS2** [comment]
![Снимок экрана от 2024-01-30 17-29-49](https://github.com/FWGS/xash3d-fwgs/assets/69766464/fa5a4121-9dc1-401c-90d8-dea7fd720d77)
![Снимок экрана от 2024-01-30 17-28-36](https://github.com/FWGS/xash3d-fwgs/assets/69766464/f390ea4a-ebd4-43b3-ae65-318d7b4571c9)
Чет как-то сильно рендеру досталось

**Comment by ArtemS2** [comment]
texgamma в последнем коммите?

**Comment by a1batross** [comment]
Нет, просто впиши texgamma в консоли и скинь значение.

**Comment by ArtemS2** [comment]
Вписать с версией бинарников где все хорошо или где все плохо?

**Comment by a1batross** [comment]
Где плохо.

**Comment by ArtemS2** [comment]
2.0

**Comment by a1batross** [comment]
А lightgamma и brightness?

**Comment by ArtemS2** [comment]
lightgamma - 2.5 brightness - 1000000 ( "0.0" )

**Comment by ArtemS2** [comment]
![Снимок экрана от 2024-01-30 17-51-43](https://github.com/FWGS/xash3d-fwgs/assets/69766464/f49bc4e7-64d7-459a-8d01-0c23a40929f8)
Half life почему-то вроде не задело

**Comment by a1batross** [comment]
>brightness - 1000000 

Ор.

Сбрось его, пожалуйста, в ноль xD

**Comment by ArtemS2** [comment]
brightness 0 ?

**Comment by a1batross** [comment]
Да.

**Comment by ArtemS2** [comment]
![Uploading Снимок экрана от 2024-01-30 17-56-33.png…]()

**Comment by ArtemS2** [comment]
![Снимок экрана от 2024-01-30 17-56-33](https://github.com/FWGS/xash3d-fwgs/assets/69766464/bb86ae2c-020d-48f8-8589-95dd5535561a)

**Comment by a1batross** [comment]
Залимитил эти квары и для локальных игр: a3acb1c85b4e7393c0e8876495cbaabfb9c92786
