### ISSUE TITLE
Cs16 arm64 (Мб у меня паранойя, но походу тени сломались) :) 

### ISSUE THREAD

**Issue by ArtemS2** [FWGS/xash3d-fwgs#1597]
![Снимок экрана от 2024-01-30 17-28-36](https://github.com/FWGS/xash3d-fwgs/assets/69766464/c28d51ce-ea9e-4d95-885a-4059164702b0)
![Снимок экрана от 2024-01-30 18-43-19](https://github.com/FWGS/xash3d-fwgs/assets/69766464/759725ca-6719-4d7d-9518-153f098ee339)

**Comment by a1batross** [comment]
Это нормально. Теперь расчёт гаммы такой же, как и в оригинальной CS.
