### ISSUE TITLE
OSX CI builds

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1599]
Hey @sofakng 

Would you like to add CI for OSX? It seems GitHub Actions now have M1 machines for FOSS projects.

Even if it wouldn't deploy builds, it would be nice to check whether engine builds and all tests pass.

**Comment by a1batross** [comment]
Related: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by sofakng** [comment]
I'm looking into this now.  Thanks for bringing it to my attention!

**Comment by a1batross** [comment]
Done.
