### ISSUE TITLE
Video playback support

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#16]
* For modern Android we can use MediaCodec available in NDK since even 5.0. It provides low-level access to audio/video decoders/encoders and almost perfectly fits for our needs. OpenMAX AL is completely useless. 
* For generic support we still should provide GStreamer or FFmpeg backend.
* And obviously stub for those who don't want a dependency. 

I don't think we really need hardware decoder here, as playing just short intros and logos in menu isn't a complicated task for modern CPUs. One exception is videos in XashXT, but AFAIK nothing uses them, except demo.

Help is still needed here. :)

**Comment by nekonomicon** [comment]
>For generic support we still should provide GStreamer or FFmpeg backend.
FFmpeg is better, but eventually breaks compatibility.

**Comment by a1batross** [comment]
Yep. :(

We should implelent this at first, and if API will break too fast, we may drop it.

**Comment by mittorn** [comment]
We may use ffmpeg wrapper for firefox/UXP

**Comment by a1batross** [comment]
Moved to #817
