### ISSUE TITLE
Knife doesnt spawn on the begining of afraid of monsters

### ISSUE THREAD

**Issue by Adnan1091** [FWGS/xash3d-fwgs#160]
I dont know it's because i did not used any laucher with it in the latest version of xash3darm64.Also,healthbar can't be seen too.

**Comment by a1batross** [comment]
Which engine version do you used?

And I think AoM needs it's own libraries...

**Comment by Adnan1091** [comment]
It's the latest nighty version.I dont think it needs its own libraries
because in the changelog it said the engine uses specials hacks to
deprecate lauchners.

1 Mayıs 2020 Cuma tarihinde Alibek Omarov <notifications@github.com> yazdı:
> Which engine version do you used?
>
> And I think AoM needs it's own libraries...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/mL0A_Y8oAypN6l2O9VLxgSv9GAhF5rfPBORJ0e_w1fN_4OK8sEf6gQtXlWw-NQ6quXPzGiESwzhtiXgsoBlCgk85aCnBjZgu1dddFIC3-UXcKkSgRCEV8g3-gPQv24ypnaHRNUIeDHiuz-deLgdFgYsO_YqtOTDCajGwHOzLvsihuCbkezAwvcplsjYwj4Kz6uCgVw5w98jgdcT_eF5rUevEBqblg-stQ4cn2Wp2RA=s0-d-e1-ft#https://github.com/notifications/beacon/AOZCB3CKYD34BNKQEV4POV3RPJ7LNA5CNFSM4MW37K72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEULW65Y.gif>

**Comment by nekonomicon** [comment]
New engine uses libraries with special hacks for Afraid of Monsters, but not for Afraid of Monsters: Director's cut.

**Comment by Adnan1091** [comment]
I'm really sorry.I misread the changelog.Well,you can close this issue.
