### ISSUE TITLE
Make build for Android 

### ISSUE THREAD

**Issue by Xash66** [FWGS/xash3d-fwgs#1602]
Make build for Android

**Comment by a1batross** [comment]
Android port is maintained at https://github.com/Velaron/xash3d-fwgs

**Comment by Xash66** [comment]
A1batross you need fix recoil and spread on Xash3d Fwgs New Engine for Android just don't maintain the port

**Comment by a1batross** [comment]
Need for whom? For you?

With an attitude like that, I don't owe you anything.

**Comment by nekonomicon** [comment]
@Xash66 

1. Read https://github.com/FWGS/xash3d-fwgs?tab=readme-ov-file#contributing and https://github.com/FWGS/xash3d-fwgs/blob/master/CONTRIBUTING.md#if-you-are-reporting-bugs=
2. One issue per bug.
3. Don't write to closed issues.
