### ISSUE TITLE
Error when running xash.dll compiled with Visual Studio 2022

### ISSUE THREAD

**Issue by GodinhoBlaster** [FWGS/xash3d-fwgs#1603]
### Description:
I am facing an issue when trying to run the latest version of xash3d, updated 8 hours ago by @a1batross, natively compiled with Visual Studio 2022. The entire project, including other DLLs, LIBs, and EXEs compiled with Visual Studio 2022, compiles without errors. However, when attempting to execute the application using the xash.dll compiled with Visual Studio 2022, I encounter the following error:

![image](https://github.com/sultim-t/xash-rt/assets/24903409/1ec660d0-1dcf-40b7-9d41-270a54178066)

**Steps to Reproduce:**

1. Cloned the repository and opened the project in Visual Studio 2022.
2. Compiled the project without errors using Visual Studio 2022.
3. When trying to run the application with the compiled xash.dll from Visual Studio 2022, I receive the mentioned error. Note that using the xash.dll compiled with WAF alongside other components works perfectly.

**Expected Behavior:**
I expected the application to run correctly using the xash.dll compiled in Visual Studio 2022, just as it does when using the xash.dll compiled with WAF.

**Current Behavior:**
I receive a specific error when attempting to run the application with the xash.dll compiled in Visual Studio 2022.

**Environment:**
Operating System: Windows 10 Home Single Language: 22H2
Visual Studio Version: Microsoft Visual Studio Community 2022 (64 bits) - Current
Versão 17.8.3

**Attachments:**
Reproduced on Branch:
[MASTER](https://github.com/FWGS/xash3d-fwgs)

**Preprocessor Settings:**
```plaintext
XASH_GAMEDIR="valve"
HAVE_STDINT_H=1
STDINT_H="stdint.h"
HAVE_MALLOC_H=1
ALLOCA_H="malloc.h"
HAVE_TGMATH_H=1
_WINSOCK_DEPRECATED_NO_WARNINGS
_CRT_SECURE_NO_WARNINGS
_CRT_SILENCE_NONCONFORMING_TGMATH_H=1
XASH_LOW_MEMORY=0
XASH_SDL=2
DBGHELP=1
PSAPI_VERSION=1
XASH_REF_SOFT_ENABLED
XASH_REF_GL_ENABLED

**Comment by nekonomicon** [comment]
What are you trying to do?
https://github.com/sultim-t/xash-rt/issues/211

**Comment by GodinhoBlaster** [comment]
"I apologize @nekonomicon, but I made a mistake. I ended up writing in the wrong place; I was looking at other people's projects and didn't realize I was in another project. However, the project in question for the issue is indeed this one. Could you please help me with the mentioned error? I would be very grateful."

**Comment by a1batross** [comment]
>Note that using the xash.dll compiled with WAF alongside other components works perfectly.

Use `msvs` command of Waf to generate Visual Studio project file.

**Comment by a1batross** [comment]
I understand that using bare-bones Visual Studio project files might be more convenient for programmers using Windows, and we do provide VS projects for parts that might be used by modders, like `mainui_cpp`.

But compiling engine without Waf is discouraged. We had a long way from a set of Makefiles, VS projects, CMakeLists, etc. to a unified build system that has support for every platform we target.

If you want to avoid using Waf, you're on your own.

**Comment by a1batross** [comment]
If you're developing a mod, you do NOT need to make any changes to the engine. You can just grab prebuilt version from Releases page: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

**Comment by GodinhoBlaster** [comment]
"Actually, I'm in the process of porting a WinRT-UWP version because I'm converting it for Xbox One Series S and X. I had a semi-playable version using @MoeMod 's work, but the xash3d version he used at the time is very outdated now and presents some bugs in the game reload. When passing through some info_landmakers, it can also generate errors. Another example of an error that occurs is when returning to a previous map; it returns Host_ERROR, stating that it couldn't find the save.

[GAMEPLAY](https://youtu.be/OuA-bYe9oZg) Using @MoeMod's work.

I used ./Waf msvs to obtain a solution; however, it is still compiled by nmake, which complicates the process for a UWP version. To be honest, I'm not familiar with this possibility."

"[GAMEPLAY](https://youtu.be/ReqWJEFGFNE) Errors reported using the older version of xash3d."

**Comment by a1batross** [comment]
waf doesn't use nmake. It directly calls the MSVC compiler.

It's better to figure out how to target UWP from it.

**Comment by GodinhoBlaster** [comment]
"The thing is, to develop for **Xbox** and implement, it's necessary to use Visual Studio because it establishes the connection between the application and the **Xbox interface**. Additionally, for network pairing, this code is generated with each compilation. Regarding Waf not using nmake, I wasn't aware that it utilized **MSVS** tools. With a closer look, I realized this after your tips. However, in my case, I believe **Waf** may not be feasible. I know you are experts in the field, and for me, everything is still very new. The other libraries and **DLLs** work perfectly; yesterday, I even converted hlsdk_portable to native **MSVS**, and it worked perfectly."

**Comment by a1batross** [comment]
Sometimes you have to know how things are done under the hood, even if it's not directly documented. Make a small project, figure out how Visual Studio calls `cl.exe` and `link.exe` for UWP targets. Make another one that tries to load external DLLs: https://learn.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=msvc-170

Then maybe adapt new knowledge to the engine port.

I don't think I can help you with the port, as I'm not using Windows or anything Microsoft made for anything serious.

**Comment by GodinhoBlaster** [comment]
"I'm grateful for your attention, and if I discover something new, I'll bring it up in this thread. I'll study the idea of perhaps using Waf on Xbox.

**Comment by GodinhoBlaster** [comment]
Update:
I identified the cause of the error I was facing. The issue was related to the character set configuration, which needed to be set to "Multi-Byte" instead of "Unicode." By making this change, the problem was resolved, and I can now compile and run the project without errors.

Here is an image showing where you can configure this option:

While this matter can be considered resolved, to ensure transparency and provide space for further discussions, I will leave the issue open until the end of this week. If anyone has additional questions, suggestions, or wishes to discuss anything related, I am available for collaboration.

If there are no further comments or questions by the end of this week, we will consider the issue closed. Thanks to everyone for their collaboration!

![image](https://github.com/FWGS/xash3d-fwgs/assets/24903409/0cd74797-72b5-48b2-a375-5dd55b9870d8)
