### ISSUE TITLE
Question about using the static library method.

### ISSUE THREAD

**Issue by GodinhoBlaster** [FWGS/xash3d-fwgs#1605]
I'm facing challenges while compiling the xash.dll file in the [FWGS/xash3d-fwgs](https://github.com/FWGS/xash3d-fwgs) project and would like guidance on using the static library method to potentially work around the issue.

Questions:

How can I use the static library method during the compilation of xash3d?
Is it necessary to compile all dynamic libraries statically, or can I opt for a partial approach?
I'm trying to address the problem discussed in [Issue #1603](https://github.com/FWGS/xash3d-fwgs/issues/1603). Is there a possibility of circumventing this issue using the static library method?

If this method works, I will be closing the issue #1603. I appreciate in advance for any help or guidance provided.

**Comment by a1batross** [comment]
It's not very well supported right now I believe. Was added for a DOS port,
but nobody used it ever since.

Did you try to use LoadPackagedLibrary?
