### ISSUE TITLE
Understanding the Role of XASH_SDL Macro.

### ISSUE THREAD

**Issue by GodinhoBlaster** [FWGS/xash3d-fwgs#1609]
The XASH_SDL macro is used when the engine requires the assistance of SDL functions to start?Correct me if I'm wrong, but in the default compilation, SDL2 is called via LoadLibrary, which later invokes the Host_Game function in the engine. I did not find the XASH_SDL macro defined at any point. However, while examining the project by @MoeMod, I noticed that he uses the .lib method to include the engine in the executable. On this occasion, he employs the XASH_SDL macro, as he needs to use SDL_MAIN to initiate his application, as UWP does not have an entry function like WinMain or main

**Comment by a1batross** [comment]
XASH_SDL macro only indicates that the engine is going to be built with SDL support. The value of 2 says it's SDL2, the value of 12 says it's SDL1.2, undefined means no SDL at all.

However, SDL1.2 only was used on some legacy platforms that never got an SDL2 port and no SDL practically isn't used anywhere except dedicated.

**Comment by GodinhoBlaster** [comment]
"Thank you very much. I had doubts, but your answer helped me understand how the macro works."
