### ISSUE TITLE
KeyValue handler difference between GoldSrc and Xash 

### ISSUE THREAD

**Issue by Hedgefog** [FWGS/xash3d-fwgs#1618]
Hey there! 👋

Recently, I encountered an issue regarding the compatibility of Xash3D with my mods. Upon investigation, I discovered that Xash3D's implementation of KeyValue parsing during map loading differs from the GoldSrc version.
Unfortunately, it breaks my Custom Entities AmxModX API for GoldSrc games, which uses KeyValue to detect unregistered entities loading and provide an entity instance for it based on KVD. Not sure if it is possible to fix it and if it makes sense, but in case it is I would appreciate it if someone could fix it. 

Here is the issue I get in my mod repo with some details about this:
https://github.com/Hedgefog/cs-zombie-panic/issues/88

Here is the API implementation for handling KeyValue:
https://github.com/Hedgefog/cs-modding-kit/blob/f1ca0401ddac405d7a3376288db4b9728d6dfbd4/api/custom-entities/api_custom_entities.sma#L307

**Comment by a1batross** [comment]
Do I understand correctly that your mod allows to add custom entity, without the exporting the function through `LINK_CLASS_TO_ENTITY`? If so, that's honestly impressive.

This might be related to this logic: https://github.com/dreamstalker/rehlds/blob/master/rehlds/engine/pr_edict.cpp#L199

GoldSrc first searches for `classname` keyvalue, then tries to find an export, and if it failed goes for `custom` entity: https://github.com/dreamstalker/rehlds/blob/master/rehlds/engine/pr_edict.cpp#L207. I wonder if GoldSrc takes this branch in case of your mod, because otherwise it sets `ent->free = true`, which then takes a branch in `ED_LoadFromFile` to skip the entity spawn.

**Comment by a1batross** [comment]
Hm, I see. It calls `pfnKeyValue` with `classname` key in `SuckOutClassname`, before trying to search for an export.

Then it might be taking `custom` branch in `ED_ParseEdict`, finds `custom` export, and your unexported entity is considered valid by the engine.

**Comment by a1batross** [comment]
Though I don't see `custom` export in a DLL. =/

**Comment by jeefo** [comment]
I believe initial custom entity is created with ``info_target`` classname.

**Comment by Hedgefog** [comment]
Correct! it just replaces the entity during creation to info_target, write some metadata to it and then take control of this entity by handling entity events and functions calls to provide a developer life cycle API to implement custom logic for the entity based on this life cycle hooks. It is kinda weird, but that is the way.

**Comment by a1batross** [comment]
So the mapper places `info_target` entity, which then gets rewritten to something else?

Do you have a map example? ^^

**Comment by jeefo** [comment]
> So the mapper places `info_target` entity, which then gets rewritten to something else?
> 
> Do you have a map example? ^^

It's just created via CreateNamedEntity() call, it's not necessary to be present on a map :)

**Comment by a1batross** [comment]
@jeefo how is this connected to entities list parse then?

**Comment by Hedgefog** [comment]
> So the mapper places `info_target` entity, which then gets rewritten to something else?
> 
> Do you have a map example? ^^

No, the mapper can use a custom class name, that's it. Adding entity process working the same way as If you register entity using `LINK_CLASS_TO_ENTITY`.

1. CS Mod Developer registered a custom entity named `mymod_entity` and write logic for it
2. Optionally can make `fgd` file with all KeyValues this entity used and send it to the mapper
3.  Mapper places the entity with classname `mymod_entity` on the map using FGD or manually
4. Custom Entities API handles KeyValue emits during the map parsing stage and replaces classname of the custom entity with info_target to make the engine create it
5. Custom Entities API changes classname to custom after engine processes the entity

**Comment by a1batross** [comment]
Thanks for answer.

I see now. The fix should be fairly simple. As far as I understand, it must be enough to call `pfnKeyValue` so your code could rewrite classname to `info_target` so the engine won't fail creating it.

**Comment by Hedgefog** [comment]
> Thanks for answer.
> 
> I see now. The fix should be fairly simple. As far as I understand, it must be enough to call `pfnKeyValue` so your code could rewrite classname to `info_target` so the engine won't fail creating it.

Correct! Thank you!

**Comment by a1batross** [comment]
Fixed in 80b3f9009134245ea20bfce5de207d796e7152bb
