### ISSUE TITLE
Смог запустить XashDS с сервером dmc , но его не видит мастер сервер.

### ISSUE THREAD

**Issue by ArtemS2** [FWGS/xash3d-fwgs#1621]
Прямое подключение работает , но в списке серверов не получается увидеть. (

**Comment by a1batross** [comment]
sv_lan 0 и public 1 выставлены?

Если нет, выставь и проверь. Если да, я не уверен, что могу что-то сделать с твоей конфигурацией сети, разбирайся сам.

**Comment by ArtemS2** [comment]
Спасибо большое, появился)
