### ISSUE TITLE
Unable to adjust in-game resolution

### ISSUE THREAD

**Issue by Highlandzxl** [FWGS/xash3d-fwgs#1622]
There is no resolution adjustment function in the engine.

**Comment by a1batross** [comment]
Platform? 

It's intentionally disabled on mobile platforms.

**Comment by Velaron** [comment]
Not really, just a limitation with SDL currently

**Comment by a1batross** [comment]
I don't really want the resolution to be customizable on phones.

It doesn't give any advantage on mobile platforms where pixel fill rate is good enough, and we don't use too heavy shaders.

The only thing it was used in old engine is to make stretched goatse-like screen.
