### ISSUE TITLE
(android) look sensitivity goes crazy while i hold mouse 1/mouse 2/mouse 3

### ISSUE THREAD

**Issue by Gorrex** [FWGS/xash3d-fwgs#1625]
Sorry, its solved was using an outdated version, new versions dont have that problem. 
New problem XD. sensitivity is extremely strange in android compared with a pc using mouse, know its a passion proyect and mouse users are a minority though, im not complaining. I dont know how to delete this thread.

**Comment by a1batross** [comment]
I'm not sure what you even tried to say here.
