### ISSUE TITLE
[Android] [GLES3Compat] Невозможно запустить тренировочный курс

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1626]
При выборе пункта "Hazard Course" в главном меню, когда выбран GLES3Compat (gl2_shim) рендерер, игра вылетает (закрывается без окна с ошибкой).

Этот баг не воспроизводится при запуске новой одиночной игры, при выборе пункта "New Game" в главном меню.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3253
Тип сборки: android-arm64
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/a508467aaccd93b0cf290f4d5cb4b6c17981cec5
Ветка: master

Устройство: Samsung Galaxy A52 (SM-A525F)
ОС: Android 14 (OneUI 6.0)

**Comment by Vladislav4KZ** [comment]
Вот отрывок лога с ошибкой:
```
Ver: Xash3D FWGS 0.20 (build 3253-a508467, android-arm64)
Crash: signal 11 errno 0 with code 1 at 0x0 0x0
[2024:02:26|18:20:41] Ver: Xash3D FWGS 0.20 (build 3253-a508467, android-arm64)
Crash: signal 11 errno 0 with code 1 at 0x0 0x0
```

Полный engine.log:
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/14404490/engine.log)

**Comment by a1batross** [comment]
Эта текстура 24x1. Ксаш её видимо как 1D пытается грузить и падает на glTexImage1D.

Предположение конечно.

**Comment by a1batross** [comment]
Возможно исправлено с https://github.com/FWGS/xash3d-fwgs/commit/373321ff00a057e93f741ed35edca9e21b4e06af

**Comment by Vladislav4KZ** [comment]
> Возможно исправлено с https://github.com/FWGS/xash3d-fwgs/commit/373321ff00a057e93f741ed35edca9e21b4e06af

Да.
