### ISSUE TITLE
Игра вылетает при разворачивании шторки уведомлений

### ISSUE THREAD

**Issue by someone38** [FWGS/xash3d-fwgs#1633]
Игра вылетает при разворачивании шторки уведомлений xash3d continuous master build 3257 android arm64
Poco x4 gt xiaomi eu 14.0.7 miui 14 android 13

https://github.com/FWGS/xash3d-fwgs/assets/116880487/23fefc75-ee80-4e56-8586-64c40393f4d1

**Comment by erfty125** [comment]
https://github.com/FWGS/xash3d-fwgs/assets/98973867/0fe0d00c-f5f0-4c86-976a-0a7eefde9ecd

**Comment by a1batross** [comment]
Fixed.
