### ISSUE TITLE
is snd_mix.c file still using leaked code?

### ISSUE THREAD

**Issue by valina354** [FWGS/xash3d-fwgs#1635]
in https://github.com/FWGS/xash3d-fwgs/issues/63#issuecomment-916021611  it says that but it has been sometime and i cant see anything related to leaks in the file? has it been rewritten yet or something or no? because i wanna make my game on xash3d and try to upload on steam so i need to know quick

**Comment by nekonomicon** [comment]
You couldn't release xash3d-based game on steam.
Need clean room implementation of engine/SDK without license violation:
https://web.archive.org/web/20180508095125/http://www.moddb.com/mods/half-life-subtitles-mod/news/sad-news-legal-issues-lack-of-time

**Comment by a1batross** [comment]
>because i wanna make my game on xash3d and try to upload on steam so i need to know quick

You didn't even start making your game and already have plans to release your game on Steam and complaining here.

I'm closing this.

**Comment by valina354** [comment]
well if the codes are still using leaked stuff then ill try rewriting them myself as i really want to make games using xash3d

**Comment by nekonomicon** [comment]
There trouble even not in leaked source code.
Main trouble in Valve's EULA for HLSDK, you need to write SDK from scratch.

**Comment by valina354** [comment]
> There trouble even not in leaked source code. Main trouble in Valve's EULA for HLSDK, you need to write own SDK from scratch.

i understand that, but i will still try to rewrite the leaked code parts  then make pull request incase it helps anyone

**Comment by nekonomicon** [comment]
Ok.
There some leaked parts in network/demo protocol yet.
At least need to rewrite net_buffer.c.
@a1batross said, this code can be replaced with [Quake 3 parts](https://github.com/id-Software/Quake-III-Arena/blob/master/code/qcommon/msg.c).

**Comment by valina354** [comment]
> Ok. There some leaked parts in network/demo protocol yet. At least need to rewrite net_buffer.c. @a1batross said, this code can be replaced with [Quake 3 parts](https://github.com/id-Software/Quake-III-Arena/blob/master/code/qcommon/msg.c).

i decided to start rewriting the sdk parts as they seem the most important other then engine tho im not sure what to being with in rewriting, like if rewriting entities first is best choice

**Comment by nekonomicon** [comment]
There basic SDK reimplementation in pure C:
https://github.com/FWGS/stubserver

**Comment by mittorn** [comment]
I think, we need rewrite hlsdk-based parts of quakewrapper. This allows use quake game code instead of rewriting entities from scratch

**Comment by valina354** [comment]
i was planning to start rewriting entities on primext sdk as its one i use  a lot and it has entities seperated in different cpp so its easier and then port rewritten entities it to hlsdk portable and stuff tho quakewarpper could probably work for some things

**Comment by valina354** [comment]
after forever of figuring out why it didnt work i finished rewriting first entity which is trigger_once (at least i hope its rewrite i rewrote it myself without looking at any sdk code), im guessing i have to keep doing this till most entities are done and then most of sdk will be rewritten or something?
![image](https://github.com/FWGS/xash3d-fwgs/assets/80889633/dbbb3cd6-fcf2-4db1-9c5a-b415ef23bd07)
