### ISSUE TITLE
The UI glitches when the game loads to another map

### ISSUE THREAD

**Issue by SkyLLerGithub** [FWGS/xash3d-fwgs#1639]
![Screenshot_20240311_004212](https://github.com/FWGS/xash3d-fwgs/assets/161835713/1458f360-545a-4c93-884e-4bc6368bacba)

**Comment by SkyLLerGithub** [comment]
I'm using Half Life Won 1.1.1.0 and the latest xash3d FWGS engine found from Google play store

**Comment by lewa-j** [comment]
#1447

**Comment by SkyLLerGithub** [comment]
> #1447

is there a fix for this?

**Comment by nekonomicon** [comment]
> is there a fix for this?

That means you have created duplicated issue.

**Comment by SkyLLerGithub** [comment]
> > is there a fix for this?
> 
> That means you have created duplicated issue.

Yes, I can see that, but is there any fix for this? I've checked and it doesn't show anything that'll solve the problem, it might be just because google translate inaccuracy, or do I have to wait for an update that fixes this?
