### ISSUE TITLE
Possible virus infected file

### ISSUE THREAD

**Issue by Kerr-Avon-2015** [FWGS/xash3d-fwgs#1640]
Sorry to bother you, but your file 'xash3d-fwgs-win32-i386.7z' might be infected with a virus.

On the page  [https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous](url) when I try to download the file 'xash3d-fwgs-win32-i386.7z', my virus killer (Avast) stops the download. If I disable Avast, then I can download the file, but when Avast scans the zip file, then it finds the file

filesystem_stdio.dll

to be infected. And Virus Total shows that around a third of the polled virus killers consider the file (filesystem_stdio.dll) to be infected, but since they don't agree on the name of the infection, then perhaps it's a false positive?

[https://www.virustotal.com/gui/file/c46c409a0e47f53762d1de52e9d890803618c380355f6b8ac6b22ac37eca5df2](url)

Thank you for your time.

**Comment by lewa-j** [comment]
`Trojan:Win32/Wacatac.B!ml` strikes again!
I bet `ml` stands for machine learning.

**Comment by a1batross** [comment]
`Wacatac` is a bullshit.

**Comment by a1batross** [comment]
>ML.Attribute.HighConfidence
>Malware (ai Score=88)
>Trojan:Win32/Wacatac.B!ml
>Trojan.Generic@AI.100
>Malware.AI.3963163280

It's all AI, machine learning and other idiocy.

If you think it's a virus, you can read the source code of a filesystem_stdio: https://github.com/FWGS/xash3d-fwgs/tree/master/filesystem. It's a small library.

You can also compile it yourself.

**Comment by SNMetamorph** [comment]
Duplicate of #1385. Also there is nothing we can do about this, that's Microsoft fault.
The only thing we can do in future after new engine release is to send all binaries to them so they can mark it as false-positive detections (had some experience with this, and it works good).
But developement builds will be always false-positive detected as malware, we just should deal with it.

**Comment by Kerr-Avon-2015** [comment]
Hello mate,

So the file is clean? Thank you for checking, and for creating this fork of
Xash3D.

Have a good day,

KA.
