### ISSUE TITLE
Can you sort the 'Custom Game' list alphabetically?

### ISSUE THREAD

**Issue by Kerr-Avon-2015** [FWGS/xash3d-fwgs#1641]
This game engine is great, especially for my not exactly fast laptop, but I do have a request; Would it be possible to enable the 'Custom Game' window to list the mods in alphabetical order, please? Either as standard, or via a "_List all mods in alphabetical order_" option on the Custom Game menu page, or as a command line setting or .ini file setting?

I have many mods, and trying to find any particular one on the Custom Game page, when they seem to be sorted at random (or at least not alphabetically) is a little irritating.

Thanks.

**Comment by a1batross** [comment]
That's a good idea actually. Right now it's probably sorted by the folder
name.

Menu already has the needed functionality for sorting by column in a
CMenuTable class. If anybody wants to contribute, just look how it's used
in ServerBrowser.cpl and apply the same code to CustomGame.cpp

сб, 16 мар. 2024 г., 03:12 Kerr-Avon-2015 ***@***.***>:

**Comment by nekonomicon** [comment]
> Right now it's probably sorted by the folder
name.

And it's normal, but will be good to see folder names into menu.

> Menu already has the needed functionality for sorting by column in a
CMenuTable class. If anybody wants to contribute, just look how it's used
in ServerBrowser.cpl and apply the same code to CustomGame.cpp

IMHO need to have functionality for ascending/descending sort by column name .

**Comment by a1batross** [comment]
It does actually have ascending/descending sort and proper UI for that.
Check ServerBrowser. :)

**Comment by Kerr-Avon-2015** [comment]
Thanks for the answers. I'm not a programmer, so I can't help, but
hopefully someone will add this feature sometime.
