### ISSUE TITLE
Xash3d FWGS 0.19.2  Exit Button 

### ISSUE THREAD

**Issue by Mandy3030** [FWGS/xash3d-fwgs#165]
Exit button in Notification is not working. It is not stopping the engine. Android version-4.4.2 kitkat.

**Comment by Vladislav4KZ** [comment]
Why is it written here about the exit button on Xash3D FWGS 0.19.2, if the Xash3D FWGS 0.20.1 repository is located here?

The "Exit" button from notification works for me.
