### ISSUE TITLE
Не включается электричество в главе Blast Pit при прохождении

### ISSUE THREAD

**Issue by j123123** [FWGS/xash3d-fwgs#1650]
Электричество там вроде подключается, но по факту оно не работает, и босса невозможно победить. И лужа по дороге назад не бъется током.
Брал xash3d-fwgs-amd64.AppImage из https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous на момент https://github.com/FWGS/xash3d-fwgs/commit/d041b2aa275332163ed6940922b5c31e14896de6
[saves.zip](https://github.com/FWGS/xash3d-fwgs/files/14784449/saves.zip)
Два сохранения - до активации и после активации двух кнопок

**Comment by a1batross** [comment]
На твоих сейвах почему-то вообще не проигрывается скрипт. Если загрузиться на карту, то работает. Если добежать с начала главы, то тоже работает.

Причём как на оригинальных библиотеках, так и на hlsdk-portable.

**Comment by j123123** [comment]
Да, тут походу тоже проблема в неправильных игровых файлах.

**Comment by jiffygist** [comment]
Такая же проблема. Как её решить? Можно ли "включить электричество" через консоль?

**Comment by a1batross** [comment]
@jiffygist наверняка можно попытаться через enttools дёрнуть триггер который включает ракетный двигатель и убивает тентакли.

Но я если честно сходу не скажу как.

Лучше проверить что игровые файлы не из кривой пиратки, а из стима и перезапустить главу начисто.

**Comment by jiffygist** [comment]
@a1batross да, спасибо. Получилось включить огонь через

```ent_fire init_rocket_fire use```

для включения электричества не нашёл нужный триггер

**Comment by jiffygist** [comment]
Также в Questionable Ethics кнопка включения красного лазера не работает, когда включены 4 синих лазера

[save-questionable-ethics.zip](https://github.com/FWGS/xash3d-fwgs/files/15133161/save-questionable-ethics.zip)

Можно включить через ```ent_fire biglaser use```

**Comment by a1batross** [comment]
Я думаю, все бы проблемы решились исключив использование кривых пираток. =/

**Comment by j123123** [comment]
А отчего в пиратках сломаны внутриигровые скрипты? На них как-то хитро завязана защита, или что?

**Comment by a1batross** [comment]
Нет, никакой защиты здесь нет в принципе.

Скорее всего это просто битые файлы.
