### ISSUE TITLE
Не получается тянуть ящики

### ISSUE THREAD

**Issue by j123123** [FWGS/xash3d-fwgs#1651]
Ящики получается только толкать, тянуть за собой их не получается
Брал xash3d-fwgs-amd64.AppImage из https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous на момент https://github.com/FWGS/xash3d-fwgs/commit/d041b2aa275332163ed6940922b5c31e14896de6

**Comment by a1batross** [comment]
Я поленился писать в жаббере.

Это на последнем hlsdk-portable? Я попробовал тянуть на себя ящик на t0a0b1. Один тащится нормально, а второй куда-то в бок улетает. Это баг ещё оригинальной халфы, насколько я помню.

**Comment by nekonomicon** [comment]
Ящики нормально тянутся.
В любом случае можно поиграться со значением квара `pushablemode`, ну и если действительно есть какие-то проблемы, хотелось бы увидеть сравнение с последней версией Half-Life из steam.

**Comment by a1batross** [comment]
Я сравнил, они тягаются нормально. 

@j123123 ты файлы игры со Steam стянул? С пиратками проблемы могут быть.

**Comment by j123123** [comment]
> Это на последнем hlsdk-portable? 

Да, сам собирал.

Ну он у меня вообще не тащится, тупо стоит неподвижным. Нажимаю кнопку ``e`` и пытаюсь назад идти - ящик положения не меняет совсем.

**Comment by j123123** [comment]
@a1batross  Не, у меня стима просто нет. Могу попробовать старый компакт-диск с халвой еще попробовать найти, и на файлах с него проверить. Не знаю, пиратка там или нет.

**Comment by j123123** [comment]
Да, похоже что проблема в файлах игры. С другой папкой ``valve`` тащить ящики получается
