### ISSUE TITLE
SysCrash when loading any map

### ISSUE THREAD

**Issue by Youssef-Sameh-2003** [FWGS/xash3d-fwgs#1656]
![image](https://github.com/FWGS/xash3d-fwgs/assets/144914804/781a77cb-e45e-4e9a-a42e-9d8c8bcb9728)
i get this error when i try to run any map

note : i just download xash-fwgs and compiled it and i didn't change any code and i am using Half Life Valve folder

**Comment by a1batross** [comment]
You need vgui.dll to run original HL dlls.

**Comment by Youssef-Sameh-2003** [comment]
I have vgui.dll, the game starta fine but when i try load any map it crashes like this

**Comment by Youssef-Sameh-2003** [comment]
Yes

**Comment by a1batross** [comment]
Which version of Half-Life do you use?

**Comment by a1batross** [comment]
Closing due to no response from the reporter.
