### ISSUE TITLE
Engine doesn't send to player his player entity

### ISSUE THREAD

**Issue by Hedgefog** [FWGS/xash3d-fwgs#1660]
It looks like the engine doesn't send to the player his own entity, even `pViewEntity` is not equal to the player, causing camera entities to not work correctly. I'm using `SetView` function to set a custom view entity for the player to implement third-party camera, but even in this case engine doesn't render the player entity to the host player.

https://github.com/FWGS/xash3d-fwgs/blob/8f6771dff474e2dc010ddf96eb7e9cd5e1c1b5a6/engine/server/sv_game.c#L3620

**Comment by a1batross** [comment]
Is there a way to locally force that cosmetics preview from your mod?

**Comment by Hedgefog** [comment]
Yep, sure:

- Join any team
- Write to the console `ce_spawn hwn_item_gift` multiple times to spawn cosmetic gifts
- Press M and open "Cosmetics" or write `hwn_cosmetics` to the console

**Comment by a1batross** [comment]
This is actually a bug of `cs16-client`.
