### ISSUE TITLE
kRenderFxGlowShell rendering incorrectly

### ISSUE THREAD

**Issue by Hedgefog** [FWGS/xash3d-fwgs#1662]
Entities with `kRenderFxGlowShell` effect render as transparent

![image](https://github.com/FWGS/xash3d-fwgs/assets/7786660/aad3f310-c2a8-4a97-a2a8-eb448d423ff6)

It also has an issue related to color, if the entity has `kRenderFxGlowShell` render effect and `rendercolor` set to `{0, 0, 0}` rendered glow shell will be white.

**Comment by nekonomicon** [comment]
All good, but can you provide info on which mods it may be tested and show screenshot how it look under GoldSource?

**Comment by Hedgefog** [comment]
> All good, but can you provide info on which mods it may be tested and show screenshot how it look under GoldSource?

It shouldn't be transparent. 

![20240419044021_1](https://github.com/FWGS/xash3d-fwgs/assets/7786660/a480e447-3d2c-481f-92ec-cb5bfce1c7c4)
![20240419044040_1](https://github.com/FWGS/xash3d-fwgs/assets/7786660/f61512d7-c4c9-4504-bca9-f0ba799118de)

The mod I have issue with: https://github.com/Hedgefog/cs-halloween-mod

**Comment by a1batross** [comment]
I see some weird ordering problem on screenshot above.

It's like the green bridge gets drawn on top of skeleton with glowshell effect.

**Comment by Hedgefog** [comment]
> I see some weird ordering problem on screenshot above.
> 
> It's like the green bridge gets drawn on top of skeleton with glowshell effect.

I've tested the engine with other maps and mods and it looks like the depth buffer is broken not only for glowshell entities. Any transparent entities behind may be visible through the other entities even if these entities have no transparency or render mode.

**Comment by a1batross** [comment]
What's the value of gl_vbo and which renderer do you use?

**Comment by Hedgefog** [comment]
> What's the value of gl_vbo and which renderer do you use?

I tried with a different renderer, it has the same issue with the phone and PC. I used the default `gl_vbo` value which equals `0`.
