### ISSUE TITLE
Sys_crash when starting campaign, changing to a different game, exiting xash, starting hazard course

### ISSUE THREAD

**Issue by Zakaria-ouertani** [FWGS/xash3d-fwgs#1666]
![image](https://github.com/FWGS/xash3d-fwgs/assets/75418838/f1075ecd-c72a-454b-81d7-641274663997)
I get this error when opening xash
Was working fine a while back. Last thing i did before opening xash was installing this mod  (though i really doubt thats the cause of this issue)
https://www.moddb.com/mods/hlcoop/downloads/half-life-coop-v20-base-mod
but even after deleting the mod and copying untouched valve folder it still happens

![image](https://github.com/FWGS/xash3d-fwgs/assets/75418838/532c7de0-6ad4-4433-9b5f-59f7442ff3eb)

these ae the other games
They were all working fine too.

**Comment by a1batross** [comment]
It easily can be just broken mod. 

I recently stuck with a similar crash myself while making a mod. It's very easy to register a cvar that will crash the engine on unload. Not something we can do without potentially breaking compatibility.

You probably didn't remove mod correctly and it still using mod's server DLL (if it replaced default Half-Life)

**Comment by a1batross** [comment]
Mod doesn't have any custom server DLL but has this: https://www.moddb.com/mods/hlcoop/downloads/hldll-for-your-cooperative-half-life-server

Did you install it? Don't touch it, just say yes or no.

**Comment by a1batross** [comment]
I was probably wrong, it works fine for me, even after installing the mod.

**Comment by Zakaria-ouertani** [comment]
> I was probably wrong, it works fine for me, even after installing the mod.

no i didnt 
but as i said after

**Comment by a1batross** [comment]
Now BaseCmd has a copy of a base command name, which is kinda more correct.

This also might've affected this issue. I couldn't reproduce it, but you can try again.

**Comment by Zakaria-ouertani** [comment]
I figured it out
it was my mistake as i was using some modified files in the valve folder and i completely forgot about that (i dont even remember why and when i copied the truly original untouched files it worked fine)
My bad and sorry for the trouble 
Thank you
