### ISSUE TITLE
Crash While booting

### ISSUE THREAD

**Issue by goober-183** [FWGS/xash3d-fwgs#1668]
Was trying to help my friend get xash3d-fwgs installed and it spat out this error...

![image 000000](https://github.com/FWGS/xash3d-fwgs/assets/151787624/4fce47a3-e73f-4468-87ab-90ce0961597f)

**Comment by a1batross** [comment]
Use game files from Steam version of the game.

**Comment by a1batross** [comment]
Also, you seem to be running an outdated version of the engine.

The latest version is at https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

**Comment by a1batross** [comment]
Closing due to no response.
