### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by Ligmanator** [FWGS/xash3d-fwgs#1669]
The game doesn't work when I am in the menu. It doesn't let me click anything or do anything.

**Comment by a1batross** [comment]
What kind of response do you expect, while not trying to explain anything?

Reopen when you will be ready to share more information with us.

**Comment by Ligmanator** [comment]
Okay so what I was saying is that while I was loading up the game it takes me to the menu. Then I press any of the mission thingies (for example) "Day One". Although it does fully load the game the game freezes/crashes when I am in the main menu for the game. This is where the issue starts. I cannot click or do anything while I am in the main menu. The device I'm using is a Chromebook. The Chromebook might be the problem but I don't know.
