### ISSUE TITLE
[MOD: Brutal Half-Life beta 2] Обезглавленные NPC

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1670]
![_zoo_0001](https://github.com/FWGS/xash3d-fwgs/assets/22411953/f27b3945-2761-4a0c-a6ae-645e3376595b)
![_zoo_0002](https://github.com/FWGS/xash3d-fwgs/assets/22411953/e186f11b-c8c4-4a01-b1a1-36724c28854b)

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3323
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/f4a77308ec6a73ee8fdeb6212d3ae02ca68485a9
Ветка: master

**Comment by a1batross** [comment]
Вроде недавно играл, всё было ок. 

Видимо сломали тоже недавно. Ладно, зато проще bisect-ить.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/85b0699288942933078260afa48188c2f647b1e5 and https://github.com/FWGS/xash3d-fwgs/commit/b8417fa46d2e52607f2e6ae2a5dbe4349ec36d62
