### ISSUE TITLE
A stupid Situation

### ISSUE THREAD

**Issue by gtrent** [FWGS/xash3d-fwgs#1674]
Hello, I apologize in advance for necro-ing this but I am unable to find a valid link for this build and it cannot be substituted. My community needs to be able to download xash3d_fwgs_win32_0.19.2 and the only downloads I can find go thru some most unsavory websites. It cant be avoided, due to hard incompatibilties and I would like to avoid third party downloads. Currently we are taking a chance with infected downloads and that is not sustainable. Getting a new build working would require alot of patches that im not skilled enough to handle on my own as it is completely broken out-of-the-box and I dont have the source code to recompile for the new engine. Im also looking at the possibility of downgrading due to this, even though older builds had their own issues. 
Another heads up, if im the first person to ask, I am probobly the calm before the storm. ALOT of people are going to be requesting this until an alternative is available. For the sanity of you project issues, I gratefully ask, that you be swift, to avoid spam. Its only a popular youtube video away from blowing up.

If you are not the same Developer, I apologize in advance, I tried to confirm that before posting. Regardless, I hope you have a pleasant Day.

(Sven Coop VR)

**Comment by nekonomicon** [comment]
> xash3d_fwgs_win32_0.19.2

For what purpose?
Why not use the latest test builds?

**Comment by SNMetamorph** [comment]
0.19.x and older versions are deprecated and no longer supported anymore. Some day 0.19.x game servers will be disabled from master server too.

**Comment by a1batross** [comment]
You're free to post your mod here and I'll try to make it working on the
new engine.

>I am probobly the calm before the storm. ALOT of people are going to be
requesting this until an alternative is available. For the sanity of you
project issues, I gratefully ask, that you be swift, to avoid spam. Its
only a popular youtube video away from blowing up.

I will gladly accept your challenge. Open the flood gates!

**Comment by gtrent** [comment]
So it appears its not a mod but a build of the engine, I was not aware as I dont use it myself but have alot of users that do, regardless. The item of issue is Lambda1Vr. It is a vr port of half life 1 for the Quest based on xash3d. Last I checked, it was 1 protocol version behind the build yall have here.

**Comment by a1batross** [comment]
>The item of issue is Lambda1Vr

I literally told @DrBeef & co multiple times to upstream their changes. If they don't want to, well, what can we do?

You still can compile old engine version from source code.

**Comment by gtrent** [comment]
My apologies, I was not aware of the situation. My day job steals alot of my time away from working on the project. Since I need to compile anyway, Do you think the it will compile for ARM/linux as is? I would like to take QEMU out of the equation if possible. Are there any flags that need to be set?

**Comment by gtrent** [comment]
Thank you again for taking time out of your day to respond. Even if its not a drop-in ready solution, I appreciate you willingness to try to resolve any issue with you project. It really is quite an excellent piece of software.

**Comment by nekonomicon** [comment]
If it has android support, what's wrong may be with arm linux?

**Comment by a1batross** [comment]
@gtrent as far as I understand, one could host a server with a mod on an x86 PC and connect from Lambda1VR client.

Since you're looking for `xash3d_fwgs_win32_0.19.2` all you need is to compile the old engine on Windows. There were instructions at https://github.com/FWGS/xash3d and https://github.com/FWGS/xash3d/wiki/Building-and-running#cmake-recommended

**Comment by gtrent** [comment]
Server machine is ARM/Ubuntu Server 20.04. it was originally running in QEMU(might have been FEX) before I suffered data loss. Would like to compile server software to native if possible. QEMU causes alot of overhead. If the project wasnt structured to facilitate this without a rewrite, then that is an acceptable loss. Thank you again.

**Comment by a1batross** [comment]
The problem is, if the mod you're running (I believe it's some early Sven-Coop version), then it's probably only works on 32-bit x86. If it has Linux support (usually used for dedicated servers) which makes things easier to set up on ARM server.

Then you need either some kind of emulator (like FEX, Box86... not sure if can recommend QEMU, it's pretty slow) and dedicated Xash3D build. It can also be compiled from source.

**Comment by mittorn** [comment]
Why not use cheap x86 vps? Xash3d only needs one core and less than 200mb ram, cheapest promo plan of any vps provider should be enough.
And old engine includes dll loader, so even if there is no server library, you may try it, it usually works good enough for old servers. I even packaged this for android with qemu included to run old singleplayer mods (known as xashds-android)

**Comment by Buggem** [comment]
easy, switch to the point of the Xash3D 0.19.2 branch in this GitHub and compile from there :shrug:
