### ISSUE TITLE
gamestartup.mp3 not playing in the menu, when starting the game with valve.avi and sierra.avi

### ISSUE THREAD

**Issue by gabberhead** [FWGS/xash3d-fwgs#1676]
the gamestartup.mp3 is not playing in the menu, when starting the game with the avi files. without, the gamestartup.mp3is playing in the menu.

but the gamestartup.mp3 also starts playing with the avi files, when the console is activated. when closing the console again, the gamestartup.mp3 also stops playing in the menu.

the problem exists for monts now.

**Comment by Vladislav4KZ** [comment]
Same as: https://github.com/FWGS/xash3d-fwgs/issues/1637

**Comment by a1batross** [comment]
Closing as duplicate.
