### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by OlegAckbar** [FWGS/xash3d-fwgs#1679]
Arch Linux amd64 билд i386
`[132/282] Compiling engine/common/soundlib/libmpg/reader.c
../engine/common/soundlib/libmpg/reader.c: В функции «default_init»:
../engine/common/soundlib/libmpg/reader.c:860:70: ошибка: несоответствие указательных типов в условном выражении [-Wincompatible-pointer-types]
`

**Comment by a1batross** [comment]
Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/caf14c1b7c1476c519c67e9a480957a3cad8fad0
