### ISSUE TITLE
native 'client_print_color' not working

### ISSUE THREAD

**Issue by Czarintax** [FWGS/xash3d-fwgs#168]
I've noticed that using native **client_print_color** won't print to chat on Xash. But able to use native **client_print**, but of course, without colors. So i would appreciate if someone can give a hand to it. Or aren't we able to use it?

> native client_print_color(index, sender, const message[], any:...);

### [amxmodx.cpp](https://github.com/alliedmodders/amxmodx/blob/6ef40779e7f88dde2202fd554ebebc5500f0eea4/amxmodx/amxmodx.cpp#L362)
```
static cell AMX_NATIVE_CALL client_print_color(AMX *amx, cell *params) /* 3 param */
{
	if (!g_bmod_cstrike)
	{
		params[2] = print_chat;
		return client_print(amx, params);
	}

	int len = 0;
	char *msg;
	int index = params[1];
	int sender = params[2];

	if (sender < print_team_blue || sender > gpGlobals->maxClients)
	{
		sender = print_team_default;
	}
	else if (sender < print_team_default)
	{
		sender = abs(sender) + 32; // align indexes to the TeamInfo ones.
	}

	if (!index)
	{
		for (int i = 1; i <= gpGlobals->maxClients; ++i)
		{
			CPlayer *pPlayer = GET_PLAYER_POINTER_I(i);

			if (pPlayer->ingame && !pPlayer->IsBot())
			{
				g_langMngr.SetDefLang(i);
				msg = format_amxstring(amx, params, 3, len);

				if (static_cast<byte>(*msg) > 4) // Insert default color code at the start if not present, otherwise message will not be colored.
				{
					memmove(msg + 1, msg, ke::Min(len++, 191));
					*msg = 1;
				}

				if (len > 187)	// Max available bytes: 188
				{
					len = 187;
					if ((msg[len - 1] & 1 << 7))
					{
						len -= UTIL_CheckValidChar(msg + len - 1); // Don't truncate a multi-byte character
					}
				}
				
				msg[len] = 0;

				UTIL_ClientSayText(pPlayer->pEdict, sender ? sender : i, msg);
			}
		}
	}
	else
	{
		if (index < 1 || index > gpGlobals->maxClients)
		{
			LogError(amx, AMX_ERR_NATIVE, "Invalid player id %d", index);
			return 0;
		}

		CPlayer* pPlayer = GET_PLAYER_POINTER_I(index);

		if (pPlayer->ingame && !pPlayer->IsBot())
		{
			g_langMngr.SetDefLang(index);

			msg = format_amxstring(amx, params, 3, len);

			if (static_cast<byte>(*msg) > 4) // Insert default color code at the start if not present, otherwise message will not be colored.
			{
				memmove(msg + 1, msg, ke::Min(len++, 191));
				*msg = 1;
			}

			if (len > 187)	// Max available bytes: 188
			{
				len = 187;
				if ((msg[len - 1] & 1 << 7))
				{
					len -= UTIL_CheckValidChar(msg + len - 1); // Don't truncate a multi-byte character
				}
			}

			msg[len] = 0;

			UTIL_ClientSayText(pPlayer->pEdict, sender ? sender : index, msg);
		}
	}

	return len;
}
```

**Comment by StevenKal** [comment]
Xash3D is using a different message (TextMsg) to print chat colors (also different & more color codes).
You should better make your own "client_print_color_xash3d" stock with "^1<->8" color codes ("^1" for red, "^2" for green, "^7" for the default value of "con_color" CVar; etc.; so test & see).
Or pass those codes in the standard "client_print" with "print_chat".

**Comment by a1batross** [comment]
@StevenKal it's not using "different" message, it just CS16Client probably has no support for colored text due to I'm not using proprietary VGUI in it. But the Xash is made that way, so you can use Q3-style colorcodes anywhere you want to. 

This issue should be moved to FWGS/cs16-client instead tbh.

**Comment by StevenKal** [comment]
You're right.
But I basically mistaken since some months ago I started testing such things in various games and I forgot while writting my previous message, that Xash3D has such features in the client itself rather than on game binary (I'm refering to the AGHL.ru's modified HL binary which has similar color chat feature [with a few differences & extend] but via the "TextMsg" message in the game).

**Comment by a1batross** [comment]
Not an engine bug.
