### ISSUE TITLE
Не работают звуки меню с ui_renderworld 0

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1681]
Если вызвать главное меню во время игры, при значении квара ``ui_renderworld`` равном ``0``, то при нажатии на любой пункт меню, не воспроизводится звук.

Но при ``ui_renderworld 1``, звуки меню воспроизводятся вместе со звуками игры на заднем фоне.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3350
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/413a0fb2e5a52e6763a8ee1a27400e0f90d4e53e
Ветка: master

**Comment by a1batross** [comment]
Исправил.
