### ISSUE TITLE
Невозможно писать кириллицей в чат

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1682]
При вводе кириллических букв в консоль или чат, они не будут отображаться.

Причём если кто-то из игроков написал сообщение в чат используя кириллицу, то она отображается. А у меня она не вводится. Вводятся только латинские буквы.

У меня стоят такие значения кваров, задающих кодировку текста:
```
cl_charset utf-8
hud_utf8 0
vgui_utf8 0
con_charset cp1251
```

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3351
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/929dfd2c71acd3a0f5746a320e59500963ca4eb8
Ветка: master

**Comment by a1batross** [comment]
Интересно, не тут ли https://github.com/FWGS/xash3d-fwgs/commit/e18e9ae2eaef4df163956b5c7d9adb96358ec021 сломали

**Comment by Vladislav4KZ** [comment]
> Интересно, не тут ли https://github.com/FWGS/xash3d-fwgs/commit/e18e9ae2eaef4df163956b5c7d9adb96358ec021 сломали

Нет, сломалось в этом коммите:
https://github.com/FWGS/xash3d-fwgs/commit/2e0fc3e4c16805de4403fa3b033155a508e6bc46

**Comment by a1batross** [comment]
Исправил в https://github.com/FWGS/xash3d-fwgs/commit/32d4bdb80f7a0d2b6d3d2c2be7aee09d5f636e01
