### ISSUE TITLE
How to replace .avi?

### ISSUE THREAD

**Issue by NTeditor** [FWGS/xash3d-fwgs#1683]
Hello, I have a suggestion for how to replace .avi.

I'm sure you've heard of Valve.bsp.
Map, models and animations, what if we use this?

We only need those who can make custom animations.

 _Attention, all text was translated from Russian by Google translator_

**Comment by nekonomicon** [comment]
А зачем?
Все уже есть в движке.
Можно показывать карту в меню.

**Comment by nekonomicon** [comment]
> Attention, all text was translated from Russian by Google translator

Практичней использовать DeepL, но да, у нас основной процент разработчиков - русскоговорящие.

**Comment by a1batross** [comment]
Я не уверен, что можно проиграть карту как интро.

Но можно попробовать запустить карту через map_background, а в меню заспавнить пустое окно, которое будет ожидать EndGame или вручную его дёргать (для кнопки пропуска, например).

**Comment by NTeditor** [comment]
> Я не уверен, что можно проиграть карту как интро.
> 
> Но можно попробовать запустить карту через map_background, а в меню заспавнить пустое окно, которое будет ожидать EndGame или вручную его дёргать (для кнопки пропуска, например).

Для запуска нужно скинуть карту и модели в папку valve и прописать в консоль map "название карты" без кавычек и расширения
