### ISSUE TITLE
[MOD: Sven Coop 4.8] Крашится при запуске сервера

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1686]
![Безымянный](https://github.com/FWGS/xash3d-fwgs/assets/22411953/bd107500-bbb8-41a7-99a5-00d9692c0b93)
[engine.log](https://github.com/user-attachments/files/15765071/engine.log)

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3358
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/f047749e61f6f7c778e3382c78cb48dd505be14d
Ветка: master

**Comment by a1batross** [comment]
Это может быть и не SC, а я сломал с предыдущим коммитом...

**Comment by a1batross** [comment]
Ан нет. Похоже, что объединение обычной модели и модели с текстурами сделано неправильно.

**Comment by a1batross** [comment]
Раньше этого не было, так как в Mod_StudioLoadTextures передавалась модель с текстурами, до их объединения.

**Comment by a1batross** [comment]
Я временно запатчу, но потом к этому вернусь.

**Comment by SNMetamorph** [comment]
В других модах тоже вылет по этой причине происходит

**Comment by a1batross** [comment]
Мне вообще не нравится ни усечение, ни объединение.

Оно совершенно не учитывает структуру модели. У усеченных моделей запросто какая-то информация может быть после текстур. Ровно, как и объединение копирует всё после textureindex, полагаясь на то, что текстуры и скины находятся после заголовка текстур. 

Да, studiomdl может быть не создает такие файлы, но они вполне вероятно могут существовать, учитывая сколько модификаций этого studiomdl существует.

**Comment by SNMetamorph** [comment]
> Да, studiomdl может быть не создает такие файлы, но они вполне вероятно могут существовать, учитывая сколько модификаций этого studiomdl существует.

Вполне может попасться что-то экзотическое

**Comment by a1batross** [comment]
Забавно как большинство проблем с модами вызывают такие выдумки на ровном месте.

Притом я не уверен что нынче в модификациях вообще используют это разделение на модель без текстур и модель которая содержит только текстуры, кроме случаев когда модель уже разделена.
