### ISSUE TITLE
messagemode активируется через раз

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1690]
Нажимаешь Y чтобы написать сообщение в чат (команда messagemode).
Можно что-то написать, можно просто нажать enter или escape - главное выйти из режима.
Нажимаешь повторно Y - ничего не происходит.
Нажимаешь Y еще раз - работает.
Проблема появилась в период с 19 апреля по 8 мая (у меня имеются билды движка этих дат, на первой проблемы нет).
Возможно, виноват этот коммит, но я не разибраюсь - просто предположил по названию.
https://github.com/FWGS/xash3d-fwgs/commit/e18e9ae2eaef4df163956b5c7d9adb96358ec021

**Comment by a1batross** [comment]
Исправил в https://github.com/FWGS/xash3d-fwgs/commit/f7e12586cf7fccb4dd6eda00a1648305ab5cf3ba

**Comment by a1batross** [comment]
Таки да, ты кстати верно угадал коммит :D
