### ISSUE TITLE
Env model error in HL:enriched

### ISSUE THREAD

**Issue by 21Shephard** [FWGS/xash3d-fwgs#1692]
The env.mdl models in enriched/models/skybox disappear when you load the saved game or respawn and are replacing by normal skybox.

**Comment by a1batross** [comment]
The map it's happening on?

**Comment by a1batross** [comment]
Version?

**Comment by 21Shephard** [comment]
All maps and v0.885 alpha

**Comment by a1batross** [comment]
Can you be more specific? I didn't played this mod, except first chapter.

**Comment by 21Shephard** [comment]
For example surface tension.
Whenever I load the save of the game near the mountain where the plane passes, the 3D map is deleted and the normal Half Life skybox of the game appears instead.env models are disappearing 
Especially in xen.xen chapters, 3D skyboxes disappear when you load or respawn.
In short, everything in the enriched/models/skybox directory is corrupted.

**Comment by 21Shephard** [comment]
https://github.com/FWGS/xash3d-fwgs/assets/166573134/c860f63b-5f19-44e4-90d1-95042205078c

Like this

**Comment by Vladislav4KZ** [comment]
It seems that @21Shephard uses an outdated build of the new engine from Google Play.

Use the latest one from GitHub.

**Comment by a1batross** [comment]
Thanks @Vladislav4KZ 

Yeah, I can see 31xx build number from his video now. Closing then.
