### ISSUE TITLE
Не заглушается фоновая музыка при сворачивании игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1693]
В настройках звука опция "Mute when inactive" помечена крестиком, но музыка не заглушается.
Заглушаются только звуки.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3363
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/260edc2a08ea6ca3e34e93e807eb8e821c237c14
Ветка: master

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/03c8ea14cc20345764a99dccd623b079c4dd44a3 

Не проверял, но должно быть исправлено.

**Comment by a1batross** [comment]
Оказывается не до конца закоммитил всё, теперь должно собираться.

**Comment by Vladislav4KZ** [comment]
Исправлено.
