### ISSUE TITLE
[MOD: Vampire Slayer] Невозможно запустить сервер

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1694]
```
Warning: Mod_LoadStudioModel: models/p_claw.mdl missing textures file
Error: Could not load model models/p_claw.mdl
```
[engine.log](https://github.com/user-attachments/files/15874805/engine.log)

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3363
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/260edc2a08ea6ca3e34e93e807eb8e821c237c14
Ветка: master

**Comment by a1batross** [comment]
А файл p_clawt.mdl никуда не делся?

**Comment by Vladislav4KZ** [comment]
> А файл p_clawt.mdl никуда не делся?

Его и не было изначально.

Я скачал этот мод с moddb, и установил его пару минут назад.

Перед твоим сообщением, я сделал дубликат файла p_claw.mdl с названием p_clawT.mdl.

После этого вылезла аналогичная ошибка с p_bike.mdl

Проделал ту же операцию с p_bike.mdl и игра запустилась.

**Comment by Vladislav4KZ** [comment]
Такая же проблема проявляется и в Gunman Chronicles.

**Comment by a1batross** [comment]
Полезу-ка я в эту логику в третий раз. =/

Мне не нравится, что можно уронить клиент если удалить T.mdl.

**Comment by a1batross** [comment]
Пока отревертил, всё снова должно работать.
