### ISSUE TITLE
flatpak not installing

### ISSUE THREAD

**Issue by romulasry** [FWGS/xash3d-fwgs#1696]
failed to run refine for system/flatpak/*/su.xash.Engine.Compat.i386/master: failed to get state: app/su.xash.Engine.Compat.i386/x86_64/master not found in any remote

**Comment by a1batross** [comment]
You're supposed to install the flatpak bundle from `continuous` pre-release tag.

As we don't have Flatpak repository *yet*, it is the only way to use Flatpak build. Not very convenient, I know.
