### ISSUE TITLE
gameinfo.txt is Written to XASH3D_RODIR Path

### ISSUE THREAD

**Issue by mmillar-bolis** [FWGS/xash3d-fwgs#1700]
__OS:__ Windows 10 x64 (21H2)
__CPU:__ Intel Core i7-8700T @ 2.4GHz
__GPU:__ Nvidia GeForce RTX 2060
__Xash Build:__ 5694610 (win32-amd64)
__Game DLLs:__ [hlsdk-portable/hlfixed \(05c6e89\)](https://github.com/FWGS/hlsdk-portable/tree/hlfixed)

__Issue:__

When running the program with the `XASH3D_RODIR` and `XASH3D_BASEDIR` environment variables set, `gameinfo.txt` is written into `XASH3D_RODIR` instead of `XASH3D_BASEDIR`.

If `gameinfo.txt` is not present, it will be converted from `liblist.gam`. This appears to happen before the runtime switches to the `XASH3D_BASEDIR` path.

Related to our discussion under issue #1697, I currently set the shell to the same path as `XASH3D_RODIR` and then execute `xash3d.exe` relative to that path (to ensure that the `valve` directory is found under my setup). Example:

```
# Not really an env var of mine, just here to clarify
# XASH_BINARY_PATH=C:\Users\Generic\Program Files\Games\Half-Life\App\Xash3D-Fwgs64\xash3d.exe

# Read-only directory of mods
XASH3D_RODIR=C:\Users\Generic\Program Files\Games\Half-Life\App\Mods

# Write-only directory that is used during execution time
XASH3D_BASEDIR=C:\Users\Generic\Program Files\Games\Half-Life\Data\Profile

# The current directory of the shell just before execution time (matching RODIR)
pushd "C:\Users\Generic\Program Files\Games\Half-Life\App\Mods"

..\Xash3D-Fwgs64\xash3d.exe

popd
```

(This works around a relatively minor issue I'm having with the runtime detecting the `valve` directory when the shell's current working directory is different from `XASH3D_RODIR`.)

Here is the console output (that occurs before `qconsole.log` is initialized):

```
Console initialized.
filesystem_stdio: custom pool allocation functions found
filesystem_stdio: custom memory allocation functions found
filesystem_stdio: custom platform-specific functions found
FS_LoadProgs: filesystem_stdio successfully loaded
Adding directory: C:/Users/Generic/Program Files/Games/Half-Life/App/Mods/
Adding directory: ./
Convert C:/Users/Generic/Program Files/Games/Half-Life/App/Mods/valve/liblist.gam to valve/gameinfo.txt
FS_InitStdio: done
C:/Users/Generic/Program Files/Games/Half-Life/Data/Profile is working directory now
```

It looks possible that the `gameinfo.txt` conversion writes to a path relative to the current working directory before the runtime can switch to the `XASH3D_BASEDIR` path. This issue didn't occur in builds before April, such as 7584bbe.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/6ff3231daba5b75d6c35679b5b630860cba867a8

Must be fixed now.

**Comment by mmillar-bolis** [comment]
Hey, it's working wonderfully! Thank you again!
