### ISSUE TITLE
Не загружаются wad файлы с корневой директории игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1701]
Любые wad файлы, которые не запакованы в pak, pk3 архивы или не находятся в папке, имя которой заканчивается на **.pk3dir** не загружаются.

В абсолютно чистой, оригинальной папке valve, при запуске вылезает ошибка:
```
Host_InitCommon: couldn't load gfx.wad
```

Хотя этот файл присутствует в папке valve.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3375
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/5694610478a1df8d0156d17ef8355167ca670ad5
Ветка: master

**Comment by Vladislav4KZ** [comment]
Ну и ещё wad файлы могут грузиться с папки custom.

С корневой папки gamedir они не грузятся.

В консоли появлются следующие ошибки, например:
```
Error: W_Open: couldn't open gamedir/wadname.wad: No such file or directory
Error: FS_AddWad_Fullpath: unable to load wad "gamedir/wadname.wad"
```

**Comment by Vladislav4KZ** [comment]
С папки downloaded wad файлы загружаются, но при этом в консоли появляются ошибки об неудачном открытии wad файлов с папки downloaded, т.к. они якобы отсутствуют.

**Comment by Vladislav4KZ** [comment]
А при загрузке wad файлов с папки custom, в консоли пишется что некоторые вады загрузились, а для некоторых пишется ложная ошибка, что не удалось открыть вады из-за их отсутствия.

**Comment by a1batross** [comment]
Совершенно забыл про порядок монтирования.

Исправил в c73fa3d7
