### ISSUE TITLE
Проблема сервера с командой coop 1. Игроки спавнятся в друг друге и т.д.

### ISSUE THREAD

**Issue by DENCHIKTEAM** [FWGS/xash3d-fwgs#1702]
Здравствуйте, захотелось попробовать поиграть в кооп через Xash. Я вписал команду coop 1 и сначала пытался начать с карты c0a0, но быстро стало понятно что вагону вообще плевать на игроков. И я быстро переключился на c1a0, где вновь столкнулся с проблемами этого режима (хотя скорее всего я что-то не так делаю). Например, при переходах между картами игроки спавнятся в друг друге и то что HEV костюм на карте рассчитан только на одного человека. И то мы его лишаемся при переходе на уровень и вдобавок получаем застревание. Мне этого было достаточно чтобы заполнить этот ишшуй, наверно при дальнейшей проверке карт на них бы были поломанные скрипты и другое. Возможно нужен какой-то патч или специальные карты, или лучше подробнее покопаться в консоли. Может кто-то уже запускал кооп сервер и знает все хитрости. Надеюсь на поддержку.

**Comment by a1batross** [comment]
coop в халфе особо ни на что не влияет. Это не ошибка движка, просто в
халфе как таковой кооператива нет и достигается он только модами

**Comment by nekonomicon** [comment]
Coop в халфе в зачаточном состоянии и видимо у gearbox была идея реализовать нормальный кооп в Opposing Force, но этого не случилось.
В любом случае, ты тут не первый "пионер".

**Comment by a1batross** [comment]
Как вариант, я недавно исправлял несколько багов в SC 4.8, может по пути исправилось ещё несколько багов в более ранних версиях SC. В любом случае можно посмотреть что открыто в багтрекере. SC 5.0+ однозначно работать не будут.

Ещё есть кооператив который пилил @mittorn в ветке gravgun в hlsdk-portable. Но его придётся немного ручками фиксить под новый движок.

**Comment by DENCHIKTEAM** [comment]
По вашему совету скачал SC 4.8, но при попытке запустить локальный сервер или подключится к уже запущенному удаленному серверу движок вылетает
[engine.log](https://github.com/user-attachments/files/16085577/engine.log)
![Screenshot_12](https://github.com/FWGS/xash3d-fwgs/assets/51756144/8797150e-28ea-40de-ba4d-ee0816e0a595)

**Comment by Vladislav4KZ** [comment]
@DENCHIKTEAM сначала обнови движок, потом кидай логи. У тебя старый билд.

**Comment by DENCHIKTEAM** [comment]
Обновил, карты запускаются. В Sven Co-op игроки не застревают в друг друге, но нельзя подобрать HEV костюм, из-за этого охранник не открывает дверь ведущую к переходу на другую карту.

**Comment by Vladislav4KZ** [comment]
> но нельзя подобрать HEV костюм, из-за этого охранник не открывает дверь ведущую к переходу на другую карту.

Потому что надо синглплеерные карты хл устанавливать через батник "Install_HLSP_Support.bat".
Этот скрипт скопирует карты Half-Life, пропатчит их ripent'ом, и распакует необходимые ресурсы из архива hlsp_support.sven.

В этом .bat-скрипте по умолчанию прописаны пути, соблюдающие иерархию папок Steam версии Half-Life.

Для правильной установки поддержки синглплеерных карт Half-Life, надо редактировать скрипт.

**Comment by Vladislav4KZ** [comment]
@lewa-j я знаю, но по дефолту этих .ent файлов нет.

Они лежат в hlsp_support.sven.
