### ISSUE TITLE
Разрозненность версий нового движка на разных платформах/лаунчерах

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1703]
Для Android есть два порта нового движка, каждый из которых имеет свою версию прописанную в манифесте, хоть она и не совпадает с той, которая отображается в самой игре.

Порт от Velaron (новый лаунчер) имеет версию под номером 0.21
Порт от mittorn (старый лаунчер) имеет версию под номером 0.20.1

А внутри самой игры, независимо от лаунчера до сих пор отображается версия 0.20, которая была выпущена ещё в 2019 году.

**Comment by a1batross** [comment]
Я думаю все надо обозвать 0.21 и не мучиться.
