### ISSUE TITLE
Couldn't find game directory 'valve' (Android)

### ISSUE THREAD

**Issue by Glumanda828** [FWGS/xash3d-fwgs#1705]
I tried multible  things i tried to only ad the valve folder (The error in the title happens if i launch it) and I tried choosing the full halflife folder (it says no game detected)
![1720212915662](https://github.com/FWGS/xash3d-fwgs/assets/131969228/8f967843-da6f-4d45-9f29-1073fe4b1ec3)
![1720212915659](https://github.com/FWGS/xash3d-fwgs/assets/131969228/f6208ff3-53be-4e66-8e29-db9ca3832c3b)

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/6ff3231daba5b75d6c35679b5b630860cba867a8

Must be fixed now.

**Comment by Glumanda828** [comment]
Thanks now it works.
