### ISSUE TITLE
[Windows] В окнах с ошибками некорректно отображается кириллица

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1708]
Уже не раз замечал, что кто-то кидает скриншот с ошибкой, а там часть текста отображается знаками неподдерживаемых символов "�" (вопрос в ромбике).

Такое ощущение, что ксаш использует кодировку UTF-8 для текста в окнах с ошибками, а встроенный текст-заполнитель из Windows, который объясняет причину ошибки закодирован в Windows-1251 (в случае с русскоязычной версией Windows).

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/a1191eb4ab8fa9dea65b7075f5d3ac5e7e751a3e

**Comment by Vladislav4KZ** [comment]
Теперь нормально отображается:
![Снимок экрана 2024-07-09 104110.png](https://github.com/FWGS/xash3d-fwgs/assets/22411953/2243c69a-1c6a-46fc-a7d6-d73e2a730f41)

**Comment by a1batross** [comment]
Я ещё не уверен стоит ли их вообще показывать на родном для юзера языке, учитывая что все остальные сообщения движок всегда пишет на ломаном английском, хехе, но наверное пусть будет.

Может хоть даст возможность юзеру самостоятельно разобраться в проблеме. :)
