### ISSUE TITLE
Error with interface

### ISSUE THREAD

**Issue by wirke** [FWGS/xash3d-fwgs#171]
I cant edit some options in interface

**Comment by Velaron** [comment]
You didn't give any valuable information.

**Comment by wirke** [comment]
![xash3d_2020_05_16_00_08_56_200](https://user-images.githubusercontent.com/46074473/82096384-8c25aa80-9709-11ea-88a7-491623aceb53.png)

**Comment by Velaron** [comment]
https://github.com/FWGS/xash-extras

**Comment by wirke** [comment]
Thanks!

**Comment by johndoe71rus** [comment]
Can you explain what to do with xash-extras?

**Comment by wirke** [comment]
Extract to valve folder

**Comment by Velaron** [comment]
put extras.pak from releases to valve folder

**Comment by johndoe71rus** [comment]
Did  i do something wrong? 
https://i.imgur.com/sURnuWI.png can't change options
https://paste.ubuntu.com/p/9f9sGtyZFM/ log

**Comment by wirke** [comment]
Download a pak archive from https://github.com/FWGS/xash-extras releases and put it in "valve" folder...

**Comment by johndoe71rus** [comment]
in log 
[11:11:52] Adding pakfile: ./extras.pak (139 files) 
this is it?

**Comment by wirke** [comment]
OK, download zip archive https://github.com/FWGS/xash-extras/archive/v0.19.2.zip and extract folders gfx, media, touch_default and all files near to valve folder

**Comment by johndoe71rus** [comment]
sorry ./extras.pak not valve/extras.pak

**Comment by wirke** [comment]
All ok now?

**Comment by johndoe71rus** [comment]
yes. thanks
