### ISSUE TITLE
Virus 

### ISSUE THREAD

**Issue by Somie98** [FWGS/xash3d-fwgs#1710]
Hey man when i'm using a lastest continuous version, but i found that the file "filesystem_stdio.dll" is a virus can you fix it ???

**Comment by a1batross** [comment]
It's a false-positive. Many antiviruses are too paranoid and there is
nothing we, as an individuals, can do about it.

If you have troubles trusting our published binaries, you can build the
engine from the source yourself.

**Comment by Vad1mCSO2** [comment]
Yes. This is false-postitive antivirus is really known
