### ISSUE TITLE
[MOD: ThreeWave CTF] [Quake карты] Чёрные текстуры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1719]
Установлен мод: https://www.moddb.com/downloads/threewave-ctf
С патчем: https://www.moddb.com/games/half-life/downloads/threewave-ctf-crossplatform

На картах для Quake мода ThreeWave CTF: https://www.moddb.com/mods/threewave-capture/downloads/threewave-ctf-for-quake-full-pack все текстуры чёрные, ничего не видно кроме моделей и скайбокса.

На ранних билдах движка такой проблемы не было.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651

**Comment by a1batross** [comment]
bisect-ом выявил что проблема в a311923d4e0ca8c8f5d6fb5cb585c0c37b37bb62

**Comment by a1batross** [comment]
Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/85dfaaa2c2f8894204b9a6fb4e867dd54dfde219
