### ISSUE TITLE
mouse lags

### ISSUE THREAD

**Issue by llacqie** [FWGS/xash3d-fwgs#172]
When I move the mouse and walk, the mouse lags and twitches. I think the mouse raw input parameter should help, but I can't find it in the settings.

**Comment by a1batross** [comment]
OS Version? 
Xash3D FWGS version?

Do you think we all have psychic abilities?

**Comment by wirke** [comment]
OS: Win 10
XASH: 0.20(latest release)

**Comment by a1batross** [comment]
Try the development version from https://github.com/FWGS/xash3d-deploy/tree/anewengine-master

**Comment by wirke** [comment]
Nothing has changed

**Comment by wirke** [comment]
I tried to change version, change start parameters, resolution and much more.

**Comment by a1batross** [comment]
Which Win10 version? Screenshot the "winver" program. 

I heard there is bugs in Fall Creators Update.

**Comment by wirke** [comment]
![изображение](https://user-images.githubusercontent.com/46074473/82124216-318e5c00-97a6-11ea-9379-a9f963f924e3.png)

**Comment by wirke** [comment]
I have tested on my laptop(windows 8.1) and everything is fine, but sometimes the mouse also moves sharply to the side. Is mouse movement processing implemented in the engine itself or in a separate library?

**Comment by a1batross** [comment]
@wirke well, there is two mouse implementations. The GoldSrc historically has mouse input in client.dll, but in Xash3D FWGS we decided to move this into engine.

It creates some incompatibilities with original client.dll. I guess you got game files from latest Steam version of Half-Life or it's more outdated?

**Comment by wirke** [comment]
Its "more outdated".

**Comment by wirke** [comment]
![1402931876_596349329](https://user-images.githubusercontent.com/46074473/82129945-3a9c1f00-97e0-11ea-8a21-e14c54bfceed.jpg)

**Comment by nekonomicon** [comment]
Raw input in GoldSrc was added in 2013.

**Comment by wirke** [comment]
MSVC development version compiled with vs6 or vs2008?(vs2008 ver have only sln/vcproj files)

**Comment by nekonomicon** [comment]
MSVC 2017

**Comment by a1batross** [comment]
Nobody can reproduce it. No info was given whatsoever. Closing, maybe it got magically fixed with #470 too? :)
