### ISSUE TITLE
[MOD: ThreeWave CTF] Не исчезает след от крюка

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1720]
Xash3D FWGS (не исчезает): https://youtu.be/qWkQru9bHgI
GoldSource (исчезает): https://youtu.be/wFrs6Cy51Qc

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651

**Comment by a1batross** [comment]
Исправлено в 64726f13
