### ISSUE TITLE
Darkened options using 25 year update files? 

### ISSUE THREAD

**Issue by Gorrex** [FWGS/xash3d-fwgs#1724]
![Screenshot 2024-07-18 075403](https://github.com/user-attachments/assets/3211afa5-88a1-418d-8f38-77c549f54688)
I can change the options via console or even in the menu but the visual feedback is missing (it works with the 1.1.1.1 won version)

**Comment by Vladislav4KZ** [comment]
Where is extras.pk3?

**Comment by Gorrex** [comment]
didnt found that file in any of the 2 valve folders (25 year one and won 1.1.1.1)

**Comment by Vladislav4KZ** [comment]
@Gorrex this file comes with the engine. It should be in the valve folder in the xash3d fwgs zip archive.

**Comment by Gorrex** [comment]
> @Gorrex this file comes with the engine. It should be in the valve folder in the xash3d fwgs zip archive.

Thanks, that worked too. must have lost that file while trying different hl versions . i will delete this if i can
