### ISSUE TITLE
[MOD: Earth's Special Forces] Игрок проваливается сквозь землю

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1728]
Использовал эту версию: https://www.moddb.com/mods/special-forces1/downloads/earth-s-special-forces-open-beta-christmas-release-2007

Это происходит на всех картах.
Xash3D FWGS (проваливается): https://www.youtube.com/watch?v=ngJP6ShNZac
GoldSource (не проваливается): https://www.youtube.com/watch?v=fGi-uUB-T1g

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3397
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/64726f13e185145072b4feaff8e1d93bfe850825
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651

**Comment by a1batross** [comment]
Fixed in 7a469fb481d9bdb62923868f1acdff65d9058e6e
