### ISSUE TITLE
Xash3D keeps crashing

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1731]
![image](https://github.com/user-attachments/assets/4cd507da-9bc6-4e2b-9bca-4d2fc24603bb)

**Comment by Vladislav4KZ** [comment]
Where and when does it crash?
Any details?

**Comment by Vad1mCSO2** [comment]
When starting or joining MP servers

**Comment by Vladislav4KZ** [comment]
Did you install some custom client.dll?
Where did Half-Life download from? Which version?

**Comment by Vad1mCSO2** [comment]
Elinsrc's client and 25th anniversary version

**Comment by Vad1mCSO2** [comment]
in old version of xash3d works fine

**Comment by Vladislav4KZ** [comment]
I also encountered an engine crash when connecting to a server or creating one.

Xash3D FWGS for Android uses hlsdk-portable, on which the Elinsrc client is also based.

```
Ver: Xash3D FWGS 0.20 (build 3399-7a469fb, android-arm64)
Crash: signal 11 errno 0 with code 1 at 0x0 0x0
[2024:07:21|14:14:59] Ver: Xash3D FWGS 0.20 (build 3399-7a469fb, android-arm64)
Crash: signal 11 errno 0 with code 1 at 0x0 0x0
```

Engine log: [engine.log](https://github.com/user-attachments/files/16323663/engine.log)

Tested on:
Xash3D FWGS v49/0.20
Build number: 3399
Platform: android-arm64
Commit: https://github.com/FWGS/xash3d-fwgs/commit/7a469fb481d9bdb62923868f1acdff65d9058e6e
Branch: master

Device: Samsung Galaxy A52 (SM-A525F)
OS: Android 14 (OneUI 6.1)

**Comment by Vladislav4KZ** [comment]
Just yesterday or the day before yesterday there were no crashes on Android yet.

**Comment by Vladislav4KZ** [comment]
This crash starts reproducing from this commit: https://github.com/FWGS/xash3d-fwgs/commit/982e32d108cde862fe7013458e2e49bb1014638b

This crash cannot be reproduced with game libraries which are compiled from code based on original HLSDK by Valve.
It only reproduces with game libraries which are compiled from hlsdk-portable and mods based on it.

**Comment by Vladislav4KZ** [comment]
This crash also occurs when starting a new game.

**Comment by a1batross** [comment]
Added yet another hack in 790f9bde54fa4af59c55255753a5dd723bb06b9d
