### ISSUE TITLE
PHS generating takes a lot of time on some maps

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1734]
For example, hg_industrialzone map:
```
[2024:07:23|01:28:53] Average leaves visible / audible / total: 2827 / 3818 / 4024
[2024:07:23|01:28:53] Uncompressed PHS size: 1.93 Mb
[2024:07:23|01:28:53] Compressed PHS size: 1.92 Mb
[2024:07:23|01:28:53] PHS building time: 9107.74 ms
```

**Comment by a1batross** [comment]
Are you running this in release mode?

I got 307.73 ms with release config, and 14621.76 ms with debug config.

I wouldn't advise doing any performance comparisons in non-optimizing debug mode.

**Comment by a1batross** [comment]
300 milliseconds is pretty much expected for such map anyway.

**Comment by SNMetamorph** [comment]
It tooks 276 milliseconds on release build. Never thought that difference between release and debug can be such tremendous.

**Comment by SNMetamorph** [comment]
So we can close it for now, and reopen if something similar will be encountered, which is unlikely
