### ISSUE TITLE
[MOD: Marathon Rampancy] Белый квадрат вместо радара

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1737]
При открытии таблицы счёта игроков, радар начинает нормально отображаться.
На GoldSource такого бага нет.

Ссылка на мод: https://www.moddb.com/mods/marathon-rampancy/downloads/marathon-rampancy

Видео: https://youtu.be/I8c8-Nrc0JU

Лог движка: [engine.log](https://github.com/user-attachments/files/16358264/engine.log)

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3402
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/173aa7333a2cb0f767cca22814e31ee59b10e121
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651

**Comment by a1batross** [comment]
Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/90da9659d11314fa9a3538149857efb76e66c238
