### ISSUE TITLE
Дедикатед сервер не работает?

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1738]
После запуска сервера (используется папка valve из стима) не показывается IP, команда status не выводит таблицу игроков, нет реакции на смену кваров (обычно при смене пишется <cvarname> changed to <value>, сейчас просто ничего не выводит).
Сервер запускается как xash3d.exe -dedicated +developer 2
![image](https://github.com/user-attachments/assets/ddbdc377-1e1a-4164-9be2-a922332cacb3)
Билды движка:
3323 - проблема отсутствует
3363 - при вводе квара показывает, что cvar changed, но на status реакции нет, IP сервера в логе отсутствует
3399 и 3402 - собственно, проблема.

**Comment by a1batross** [comment]
Ему похоже allow_console не выставлялся. https://github.com/FWGS/xash3d-fwgs/commit/e70f9a67b85ef3184f058cd10480d32ef68d14eb

Я проблему не замечал, так как свои сервера всегда с `-dev` запускаю. Да и в принципе, почти не отключаю dev режим.

**Comment by Aynekko** [comment]
Действительно, параметр -console решил проблему. И, вижу, ты сделал фикс. Спасибо! :)
