### ISSUE TITLE
"New Game", "Training Room", and "Load Game" grayed out when launching game

### ISSUE THREAD

**Issue by camthesaxman** [FWGS/xash3d-fwgs#174]
**Computer:** Raspberry Pi 3 Model B
**OS:** Void Linux armv7l musl

**Steps taken:**

Make directory where game will be installed:
`mkdir /home/pi/projects/Xash3D`

Build and install xash3d:
`cd /home/pi/projects`
`git clone --recursive https://github.com/FWGS/xash3d-fwgs.git`
`cd xash3d-fwgs`
`./waf configure -T release --prefix=/home/pi/projects/Xash3D`
`./waf build`
`./waf install`

Copy Half-Life game files:
I verified that the Steam version of Half-Life runs on my x86-64 Linux PC, then copied the `~/.steam/steam/steamapps/common/Half-Life/valve` directory from my PC to `/home/pi/projects/Xash3D/lib/xash3d/valve` on my Raspberry Pi.

Build hlsdk-xash3d (needed for some ARM shared libraries):
`cd /home/pi/projects`
`git clone https://github.com/FWGS/hlsdk-xash3d`
`cd hlsdk-xash3d`
`mkdir build && cd build && cmake ../`
`make`

Copy shared libraries:
I copied `/home/pi/projects/hlsdk-xash3d/build/dlls/hl.so` to `/home/pi/projects/Xash3D/lib/xash3d/valve/dlls/hl.so`, and copied `/home/pi/projects/hlsdk-xash3d/build/cl_dll/client.so` to `/home/projects/Xash3D/lib/xash3d/valve/cl_dlls/client_armv7hf.so`.

Launching the game:
The game launches successfully with `LD_LIBRARY_PATH=/home/pi/projects/Xash3D/lib/xash3d /home/pi/projects/Xash3D/lib/xash3d/xash3d`, however the aforementioned items in the main menu are grayed out, and it is not possible to start a single player game.

**Comment by nekonomicon** [comment]
```I copied /home/pi/projects/hlsdk-xash3d/build/dlls/hl.so to /home/pi/projects/Xash3D/lib/xash3d/valve/dlls/hl.so, and copied /home/pi/projects/hlsdk-xash3d/build/cl_dll/client.so to /home/projects/Xash3D/lib/xash3d/valve/cl_dlls/client_armv7hf.so.```
Read messages in the console.
You need to rename this libraries.

**Comment by camthesaxman** [comment]
I renamed hl.so to hl_armv7hf.so, and it worked. However, there was nothing in the terminal about that.

**Comment by lewa-j** [comment]
He meant the in-game console.
To do this, run the game with the -console argument. And maybe -dev 2

**Comment by camthesaxman** [comment]
Oh, okay. I really think it should be mentioned somewhere in the README about needing to build `hlsdk-xash3d` and copy the .dll/.so files from it.
