### ISSUE TITLE
В консоли XashDS перестал отображаться текст кроме верхней строки (пример команда cmdlist)

### ISSUE THREAD

**Issue by DENCHIKTEAM** [FWGS/xash3d-fwgs#1746]
С определенного времени, и возможно не только у меня, в консоли перестал отображаться какой либо текст: например после смены карты или при вводе команды cmdlist. Интересно то что при добавлении параметра -dev этот текст магическим образом появляется где должен быть, а команды также начинают корректно отображать текст.
_Консоль без параметра -dev_
![изображение_2024-07-28_213200149](https://github.com/user-attachments/assets/9dc0ba15-02f5-4a71-9f21-386fedad05c9)
_Консоль с параметром -dev_
![изображение_2024-07-28_213334670](https://github.com/user-attachments/assets/0c3a5ea8-0cfe-4385-bd99-a3ff1fbc2e17)
![изображение_2024-07-28_213351243](https://github.com/user-attachments/assets/b8778581-95c2-40b8-a97d-34ab8f1908b0)

**Comment by SNMetamorph** [comment]
Прикрепи engine.log. Но я полагаю что дело в недавно пофикшенном баге, на самых последних билдах он исправлен.

**Comment by DENCHIKTEAM** [comment]
Вот пожалуйста
лог без параметра -dev
[engine.log](https://github.com/user-attachments/files/16404907/engine.log)
лог с параметром -dev
[engine.log](https://github.com/user-attachments/files/16404912/engine.log)

**Comment by DENCHIKTEAM** [comment]
Действительно, ну я как обычно. Я сейчас поставил самую свежий коммит и теперь консоль нормально работает и без -dev. Проблема решена
