### ISSUE TITLE
Изменение в поведении developer

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1747]
У меня в конфиге на постоянке прописан developer 2. В ярлыке -dev **отсутствует**.

На билде 3399 перестали отображаться в консоли серверные ALERT( at_aiconsole, ... ).
Билд 3385 - отображаются.
Если дописать в ярлык -dev 2 - все равно не отображаются.

**Comment by a1batross** [comment]
Исправил в f4a3b857
