### ISSUE TITLE
[Android] Вопрос: Сборка лаунчера в AndroidIDE 2.7.1-beta

### ISSUE THREAD

**Issue by Alex3474247** [FWGS/xash3d-fwgs#1748]
AndroidIDE много что может, я смог скомпилировать idTech4A++ и Zeta Touch, возможно ли то же самое с FWGS или можно даже не пытаться, использовать только Android Studio?
Органичения состоят в том что максимальная версия NDK которую я могу установить в AndroidIDE, это r26b (26.1.10909125) и пакеты не все могут быть установлены. Не любая версия NDK будет работать в AndroidIDE.

**Comment by a1batross** [comment]
Когда-то можно было скомпилировать движок из Termux. Но наврядли этим
кто-то будет заниматься сейчас.

Patches welcome.

**Comment by Vladislav4KZ** [comment]
В AndroidIDE и есть терминал на базе Termux.

**Comment by erfty125** [comment]
> AndroidIDE много что может, я смог скомпилировать idTech4A++ и Zeta Touch, возможно ли то же самое с FWGS или можно даже не пытаться, использовать только Android Studio?
> Органичения состоят в том что максимальная версия NDK которую я могу установить в AndroidIDE, это r26b (26.1.10909125) и пакеты не все могут быть установлены. Не любая версия NDK будет работать в AndroidIDE.

пиши баш скрипт сборки и всё(да, в термуксе)

**Comment by a1batross** [comment]
Мне кажется куда проще не насиловать своё зрение и нервы, и делать всё на ПК.

**Comment by erfty125** [comment]
> Мне кажется куда проще не насиловать своё зрение и нервы, и делать всё на ПК.

Мной описанный путь предполагает изучение процесса сборки приложения, что очень пригождается когда приходится например на другую билд систему перенести и т.д, да и не таскать андроид студио оверхедом это уже довольно веская причина для такого

**Comment by Velaron** [comment]
> > Мне кажется куда проще не насиловать своё зрение и нервы, и делать всё на ПК.
> 
> Мной описанный путь предполагает изучение процесса сборки приложения, что очень пригождается когда приходится например на другую билд систему перенести и т.д, да и не таскать андроид студио оверхедом это уже довольно веская причина для такого

Ну уже есть такое в старом движке, работает на одной платформе и отваливается при апдейтах ndk/sdk, да и студию никто не заставляет тащить, градл разве что

**Comment by erfty125** [comment]
> > > Мне кажется куда проще не насиловать своё зрение и нервы, и делать всё на ПК.
> > 
> > Мной описанный путь предполагает изучение процесса сборки приложения, что очень пригождается когда приходится например на другую билд систему перенести и т.д, да и не таскать андроид студио оверхедом это уже довольно веская причина для такого
> 
> Ну уже есть такое в старом движке, работает на одной платформе и отваливается при апдейтах ndk/sdk, да и студию никто не заставляет тащить, градл разве что

Ну не знаю даже. Сам ксаш то понятно надо симаком/вафом собирать, я не спорю, но лаунчер можно и баш скриптом собрать, не такой он и огромный(тем более если не планируется вносить изменения в лаунчер). Вместо сборки градлом можно заранее собрать джаваговно в лаунчере и на этапе сборки просто либы добавлять и подписывать апк
