### ISSUE TITLE
No way to contact developers

### ISSUE THREAD

**Issue by grepwood** [FWGS/xash3d-fwgs#175]
I tried mailing, but nobody responded. https://xash.su/#contacts advertises a Discord room but doesn't offer an invite link.

**Comment by saucesaft** [comment]
Think this is the invite:
https://discord.com/invite/4bz6Acvj?utm_source=Discord%20Widget&utm_medium=Connect

**Comment by a1batross** [comment]
Must be fixed now.

Also you can always use https://discord.fwgs.ru.
