### ISSUE TITLE
[Android] Themed icon does not work 

### ISSUE THREAD

**Issue by DavidMacalister** [FWGS/xash3d-fwgs#1752]
I saw that in theory Xash supports the Android themed icon function, there is even this function in the icon's XML, but it doesn't work, I believe it's because there isn't this color folder, and consequently there is also no ic_launcher background

The icon looks normal with the Android themed icon function 

![Screenshot_20240729-184038.png](https://github.com/user-attachments/assets/1dfb5b07-689b-416d-9ecc-376e658f1178)![Screenshot_20240729-183944.png](https://github.com/user-attachments/assets/00f0f810-fa1f-4dce-ba63-fee179042183)

**Comment by Vladislav4KZ** [comment]
> I believe it's because there isn't this color folder, and consequently there is also no ic_launcher background

No, it's not the name of the folder. It is a color parameter that takes the value from ic_launcher_background from the values folder.

For a themed icon, you need a monochrome icon. I already posted a screenshot in Discord with this icon. I'll create a Pull Request later.

**Comment by Vladislav4KZ** [comment]
Should work in the latest build of the engine.

**Comment by DavidMacalister** [comment]
Now it's working, thank you for your work ![Screenshot_20240803-112526.png](https://github.com/user-attachments/assets/abd60234-9d7e-4f43-b679-19e11d84084d)
