### ISSUE TITLE
FOV does not correspond to Steam HL settings

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#1753]
Проблема такая - ни при каких настройках FOV в Ксаше не совпадает с FOV, который используется в Стим ХЛ. Не знаю, как там всё высчитывается, но под Ксашем оружие в руках расположено существенно выше, чем под Стим ХЛ. Соответственно, с некоторым оружием присутствуют проблемы подобно того, что оно слишком сильно перекрывает обзор, либо идёт эффект "срезания" задней части модели на анимациях. Это происходит как в случае применяемого r_adjust_fov, так и в случае, когда квар выключен. При отключенном кваре разница просто гигантская.

Для примера:
FOV 90 Steam HL -
![Steam90](https://github.com/user-attachments/assets/d3e857a6-f215-4621-a794-9de907bcb824)

FOV90 Xash -
![Xash90](https://github.com/user-attachments/assets/9e53f11d-6127-402d-9084-10411f2663ba)

FOV 105 Steam HL -
![Steam105](https://github.com/user-attachments/assets/14d8a359-2b2f-4dcb-b382-796067f3089e)

FOV 105 Xash -
![Xash105](https://github.com/user-attachments/assets/abd9500e-0f62-4e2e-bca9-a76fcdfdc8ac)

**Comment by Qwertyus3D** [comment]
И отдельно отмечу, что моделвьюер также показывает положение оружия при просмотре, которое соответствует Стим ХЛ и не не соответствует Ксашу.

**Comment by SNMetamorph** [comment]
У тебя стимовский билд со старой ветки, или уже после обновления на 25-летие игры?

**Comment by Qwertyus3D** [comment]
После обновления.

**Comment by Vladislav4KZ** [comment]
@Qwertyus3D проверь квар ``viewsize``, его значение должно быть равно ``120``.
На низких значениях, где-то примерно от 100 до 110 вьюмодель оружия подымается.

**Comment by Vladislav4KZ** [comment]
С Xash3D FWGS вырезали изменение размера экрана, поэтому ``viewsize`` не меняет его размер, но модель оружия от первого лица может перемещаться то вверх, то вниз, в зависимости от указанного значения.

**Comment by Qwertyus3D** [comment]
Да, похоже, что в этом проблема. Viewsize был установлен на 100, хотя полностью окно охватывается только при 120. Как-то странно квар вырезали тогда, раз он до сих пор влияет.

**Comment by a1batross** [comment]
>При отключенном кваре разница просто гигантская.

В HL25 есть аналог `r_adjust_fov`, зовётся `gl_widescreen_yfov`.

**Comment by Qwertyus3D** [comment]
Да, действительно. Видимо, имеет смысл и в Ксаше название квара поменять, раз сделали аналог.

**Comment by a1batross** [comment]
Не уверен, они этот квар в рендерер засунули.

Всё что начинается на `gl_`, за некоторыми исключениями, всё-таки специфично для OpenGL. У нас же adjust fov делается ещё при определении refdef.

**Comment by a1batross** [comment]
Сверил изображение между халфой старой версии, халфой новой версии с gl_widescreen_yfov 0 и ксашем с r_adjust_fov 0 -- разницы нет.

Сверил изображение между халфой новой с gl_widescreen_yfov 1 и ксашем с r_adjust_fov 1 -- разнциы тоже нет. 

Думаю, можно закрывать.
