### ISSUE TITLE
Bad collision around func_pushable and func_door_rotating

### ISSUE THREAD

**Issue by adslbarxatov** [FWGS/xash3d-fwgs#1760]
Hi!

We've tried to fix this problem by ourselves. But we still can't find where it comes from. Please, help us to understand it (if this problem is not in the engine) or to fix it (in other case). Thank you in advance!

---

## Problem essence

- incorrect collision of `func_pushable` with non-cube form (basically, a parallelepiped) when touching surrounding walls;
- incorrect collision of `func_door_rotating` when `Ox` or `Oy` flags are checked.

We assume that both problems have one source that somehow comes from hulls processing. Later you will understand why we think so. Also we think that the problem cannot come from the `.bsp` file or compilers settings because this case doesn't explain the behavior of these objects when players crouches or jumps around them (also see below).

We can assume that the problem may come from `client.dll` or `hl.dll` because we're using versions of them that are not from FWGS build. But we can't find any piece of code that somehow touches the collision math.

## How to reproduce

We've written a video that shows both problems. You can find it [here](https://drive.google.com/drive/folders/1TgBuUvlcFP7PZ_Jv8QkMTMwaykeZKZil?usp=sharing). Also under this URL we've placed the test map, its compiled version and compilers settings. 

### 1. Pushables

1. Place a `func_pushable` with a rectangular base on the map.
2. Move it consistently towards the walls.
3. ***Object will clip through walls on positive directions of Ox and Oy axes***. On a video it looks like the collision box stays cube-shaped.
4. On negative directions its behavior will be correct.

See video `Pushables test.mp4` for details.

### 2. Doors

1. Place a horizontally oriented `func_door_rotating` on the map. Check its `Ox` flag (or `Oy`, it brings the same result).
2. Step on it, then try to jump under it. The behavior will be correct.
3. Open the door. It should “hang” down.
4. Step on in again. Try to fall down through the opened aperture. ***You'll meet an invisible barrier***.
5. Press crouch button. You will fall down as intended.
6. Release crouch button. ***The player will remain crouched, like there is a barrier over him***.
7. Press jump button. The player will pass the aperture without any barrier.

See video `Doors test.mp4` for details.

**Comment by a1batross** [comment]
As far as I understand, it tries to pick the closest monster hull based on bbox size, see `SV_HullForBsp` function in `sv_world.c`. It might be possible to change the offset based on origin, but monsters hulls can't perfectly match arbitrary bbox size.

The issue with the door can be partially mitigated by enabling `ENGINE_PHYSICS_PUSHER_EXT`. It's easy to set it through PhysicAPI. Take `physint.h` and `enginefeatures.h` from the `engine` and `common` folders from this repository and add this somewhere in your hl.dll:
```c
#include "physint.h"
#include "enginefeatures.h"

static int SV_CheckFeatures( void )
{
	return ENGINE_PHYSICS_PUSHER_EXT;
}

static physics_interface_t g_phys_iface =
{
	.SV_CheckFeatures = SV_CheckFeatures,
};

extern "C" DLLEXPORT int Server_GetPhysicsInterface( int version, server_physics_api_t *api, physics_interface_t *iface )
{
	if( version != SV_PHYSICS_INTERFACE_VERSION ) return 0;

	*iface = g_phys_iface;
	return 1;
}
```

**Comment by adslbarxatov** [comment]
Hi!

Thank you for recommendations. The door problem for our case (90°-based orientation) has been solved.

But we have a question about pushables. Are we correct in understanding that the engine uses these four standard hulls with square base for pushables as well? Does it mean that the problem with clipping is unsolvable for now?

P. S. Pushables with square base (f. e., simple crates) have problems too (but less remarkable). We still can see a gap (1 or 2 map point) between two cube-shaped crates pushed to the wall and a little (1 or 2 map point) clipping through the wall for the single crate. It is also affects only positive axes directions

**Comment by adslbarxatov** [comment]
That's sad. Anyway, thank you for help and fast response!
