### ISSUE TITLE
Лагает движение игрока при удерживании кнопки использования

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1763]
Это проявляется при игре на удалённых серверах, запущенных как на новом, так и на старом движке.

При этом должен быть установлен клиент из последнего обновления Half-Life, в честь 25-летия игры.

С client.dll от ранней версии Half-Life (от 3 августа 2020 года, с номером сборки 8684) такой баг не воспроизводится.

Видео: https://youtu.be/v6T3CK-ubT8

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3412
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/4c569e1d5f3fae94d9b514a9ce718b4a26d2938c
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4717

**Comment by Vladislav4KZ** [comment]
С серверной библиотекой из последнего обновления Half-Life, игрок не замедляется при удерживании кнопки использования в мультиплеере.
Он замедляется только в синглплеере.

А на серверной библиотеке из ранней версии Half-Life от 3 августа 2020 года, игрок замедляется при удерживании кнопки использования как в мультиплеере, так и в синглплеере.

**Comment by mittorn** [comment]
Подозреваю, что движок ничего с этим не сможет сделать. Просто valve сломали игру в этом апдейте.  Думаю, это поведение стоит в physinfo передавать, но в любом случае исправить поведение на оригинальном свежем клиенте не выйдет

**Comment by a1batross** [comment]
Так и есть. Это не баг движка и наврядли мы сможем с этим что-то поделать.

У версий Half-Life до обновления и после отличается физика игрока. Насколько я знаю, только в скорости игрока при зажатом +use, поэтому это и выливается в лаги при несоответствии версий, так как предиктинг становится бесполезен.
