### ISSUE TITLE
[Android] Selected directory doesn't contain any games

### ISSUE THREAD

**Issue by joelemiliano** [FWGS/xash3d-fwgs#1764]
So I want to add Half Life to my library and so I copied the game files from my computer to my phone and put the valve folder in a folder called "halflife" in /storage/emulated/0 and I select the halflife folder and a error pops in the screen saying "Selected directory doesn't contain any games" so I selected the valve folder and still the error happens

**Comment by Vladislav4KZ** [comment]
Send a screenshot of the valve folder, maybe you didn't copy all the game files.

**Comment by joelemiliano** [comment]
> Send a screenshot of the valve folder, maybe you didn't copy all the game files.


https://github.com/user-attachments/assets/0ff1118d-d6e1-499c-8142-9d911266116b

**Comment by Vladislav4KZ** [comment]
@joelemiliano You don't have some of the files. Specifically liblist.gam.

**Comment by Vladislav4KZ** [comment]
You might need to try packing the valve folder into a zip archive on your PC, then unzip the zip on your phone.

Copying a single file from your PC to your phone shouldn't be a problem.

**Comment by joelemiliano** [comment]
> You might need to try packing the valve folder into a zip archive on your PC, then unzip the zip on your phone.
> 
> Copying a single file from your PC to your phone shouldn't be a problem.

gonna try

**Comment by joelemiliano** [comment]
> > You might need to try packing the valve folder into a zip archive on your PC, then unzip the zip on your phone.
> > Copying a single file from your PC to your phone shouldn't be a problem.
> 
> gonna try

@Vladislav4KZ thank you it worked
