### ISSUE TITLE
[Android] Не нажимается кнопка Test Fire (Blast Pit)

### ISSUE THREAD

**Issue by Alex3474247** [FWGS/xash3d-fwgs#1771]
Не могу нажать кнопку Test Fire хотя всё включил, прикрепляю видео. Соответственно дальше пройти не могу.
https://drive.google.com/file/d/1BQj73EiUZce7jyeHSNn5u9V36j0vzNt8/view?usp=drivesdk
Версия hl купленная в стиме, апк файл взят из релизов, сам ничего не собирал, Андроид студия старая (Flamingo).

**Comment by john123903** [comment]
[english] did you download the latest version? if yes, then it might be a bug.
[russian] ты скачал последнюю версию? если да, то это может быть ошибка.

**Comment by Vladislav4KZ** [comment]
Подтверждаю.

Проверял на файлах игры, взятых из последнего обновления Half-Life в Steam в честь 25-летия игры.

```
Protocol version 48
Exe version 1.1.2.2 (valve)
Exe build: 12:23:38 Dec 22 2023 (9920)
```

Баг воспроизводится только на библиотеках собранных с репозитория [hlsdk-portable](https://github.com/FWGS/hlsdk-portable)

На Android версии движка как раз используются игровые библиотеки собранные из вышеуказанного репозитория.

На оригинальных библиотеках Half-Life этот баг **не воспроизводится**.

Проверял на:
Xash3D FWGS v49/0.21
Номер сборки: 3419
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/a5f7027229ffc3667dbaca0683c628e235a9692a
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4717

**Comment by a1batross** [comment]
Я тоже пробовал, тоже сломано с hlsdk-portable.

@nekonomicon есть идеи?

**Comment by a1batross** [comment]
Ранее тоже были репорты связанные с этим...

**Comment by nekonomicon** [comment]
У меня есть 2 варианта:
1. https://github.com/FWGS/hlsdk-portable/commit/f58544a1568f6abbbe28bf3c5c94b5b967e4f69c, https://github.com/FWGS/hlsdk-portable/commit/19f3e9197854f4bfbd3cf63bcead19439275f926
2. https://github.com/FWGS/hlsdk-portable/commit/e552d2cc06d303335def49075e5cf152eaed623b

В любом случае точно не уверен в причине поломки.

**Comment by a1batross** [comment]
@nekonomicon бисектом нашёл f58544a1568f6abbbe28bf3c5c94b5b967e4f69c.

Лучше их отревертить. Если сильно нужно, то для них есть ветка с исправлениями, насколько я помню.

**Comment by a1batross** [comment]
Fixed in HLSDK
