### ISSUE TITLE
[Enhancement] Запускать карту-бэкграунд после отключения от сервера

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1772]
После отключения от сервера (это касается как сингла, так и мультиплеера) хотелось бы, чтобы в меню запускалась заданная карта-бэкграунд при ее наличии, как при старте игры.
Понимаю, что это понравится не всем, поэтому лучше сделать опционально, например через gameinfo.

**Comment by a1batross** [comment]
Я думаю, что эти карты бэкграунды задумывались как те что из Source, а там бэкграунд карта не возвращается после того, как игрок вышел из игры.

Впрочем, менеджментом бэкграунд карт занимается меню. Наверное в меню можно как-то подхватить момент смены состояния клиента и поднять бэкграунд карту.

**Comment by Aynekko** [comment]
> Наверное в меню можно как-то подхватить момент смены состояния клиента и поднять бэкграунд карту.

В CMenuMain::Draw сделал
```
if( !EngFuncs::ClientInGame() )
	UI_LoadBackgroundMap();
```
И, собственно, сам механизм взял из уже имеющегося кода
```
bool UI_LoadBackgroundMap( void ) // force load background map
{
	int bgmapid = EngFuncs::RandomLong( 0, uiStatic.bgmapcount - 1 );
	char cmd[128];
	snprintf( cmd, sizeof( cmd ), "maps/%s.bsp", uiStatic.bgmaps[bgmapid] );

	if( EngFuncs::FileExists( cmd, TRUE ) )
	{
		snprintf( cmd, sizeof( cmd ), "map_background %s\n", uiStatic.bgmaps[bgmapid] );
		EngFuncs::ClientCmd( FALSE, cmd );
		return true;
	}

	return false;
}
```
Этого оказалось достаточно вроде бы.
