### ISSUE TITLE
MOD: Cleaner's Adventures: убрать повтор mp3-файлов

### ISSUE THREAD

**Issue by Alex3474247** [FWGS/xash3d-fwgs#1775]
Только что проверил, в оригинальной версии CAd для Windows от 2006 года через GoldSrc нет повтора мп3-звуков (те которые в папке media), а также при загрузке сохранений если момент триггера уже пройден, данный мп3 файл не воспроизводится. Они воспроизводятся однократно. А в Xash3D ставятся на повтор, особенно это смущает на примере коротких мп3-шек susp1, 2, 3.mp3 когда данный звук воспроизводится многократно. Но триггер срабатывает корректно, они включаются в нужный момент времени.

**Comment by nekonomicon** [comment]
Проблема в Xash3D или hlsdk-portable?
Оригинальный CAd под ксашем на пк проверялся?

**Comment by Alex3474247** [comment]
Проблема в hlsdk-portable т.к. если запускать CAd в оригинале через ксаш на винде, не заменяя библиотеки мода, то проблема не проявляется. Могу прикрепить видео.

**Comment by nekonomicon** [comment]
Видео ни к чему, проблема уже знаю в чем.
Issue в любом случае создана не в том репозитории.

**Comment by nekonomicon** [comment]
Исправлено: https://github.com/FWGS/hlsdk-portable/commit/f543f1c6b3edd18d737fa7ff92619f5817f4178b
