### ISSUE TITLE
Psvita failed to launch 

### ISSUE THREAD

**Issue by Blkrobz** [FWGS/xash3d-fwgs#1781]
![2024-08-15-172822-628263_1.jpg](https://github.com/user-attachments/assets/cc384cc1-8976-45d0-9f64-96a5163b2c8e)

**Comment by mittorn** [comment]
Try start map from console. It seems, we need add -Wl,--no-undefined to 
linkflags

**Comment by a1batross** [comment]
Can you check whether f3d181b5 fixed it?

**Comment by Blkrobz** [comment]
It fixed the launch, I switched to CS - option to start a lan game is blurred out, internet game freezes

Half-Life plays well

**Comment by a1batross** [comment]
CS isn't included in this port.

I might add it later but I would need some help from somebody who owns a Vita (because Vita3K can't run Xash yet)

**Comment by Blkrobz** [comment]
If i can help with testing I'm all in

**Comment by a1batross** [comment]
Closing, as the problem solved.
