### ISSUE TITLE
Не работает Software рендерер

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1783]
Игра просто крашится при запуске с ref_soft рендерером.

```
Ver: Xash3D FWGS 0.21 (build 3424-f3d181b, win32-i386)
Sys_Crash: address 7273E4C3, code C0000005
Exception: D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\cvar.c:518:0
PC: D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\cvar.c:518:0
 0 7273E4C3 Cvar_RegisterVariable (D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\cvar.c:518:0) (xash.dll)
 1 6F4DB779 GL_InitCommands (D:\a\xash3d-fwgs\xash3d-fwgs\ref\gl\gl_opengl.c:1184:0) (ref_gl.dll)
 2 6F4DB974 R_Init (D:\a\xash3d-fwgs\xash3d-fwgs\ref\gl\gl_opengl.c:1276:7) (ref_gl.dll)
 3 7282EBBC R_LoadRenderer (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\ref_common.c:576:255) (xash.dll)
 4 7282F2F6 R_Init (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\ref_common.c:748:7) (xash.dll)
 5 72743D1D Host_Main (D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\host.c:1190:263) (xash.dll)
 6 000F1355 WinMain (D:\a\xash3d-fwgs\xash3d-fwgs\game_launch\game.cpp:210:64) (xash3d.exe)
 7 000F15B0 __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:26) (xash3d.(ntd
```

Лог движка: [engine.log](https://github.com/user-attachments/files/16634823/engine.log)

Проверял на:
Xash3D FWGS v49/0.21
Номер сборки: 3424
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/f3d181b5ee2f2ac585ed908d35f78828dc621f9b
Ветка: master

Сведения об устройстве:
Ноутбук Lenovo B590 (не заводской комплектации)
ОЗУ: 8ГБ DDR3 1600 МГц
ЦП: Intel® Celeron® 1000M 3-его поколения (Ivy Bridge) с частотой 1.80 ГГц
Видеоускоритель: Intel® HD Graphics для процессоров Intel® 3-его поколения. Базовая частота 650 МГц, максимальная 1 ГГц. (Конкретная модель не указана).
Версия драйвера видеоускорителя: 10.18.10.4358
ОС: Windows 10 Домашняя для одного языка x64 22H2
Номер сборки ОС: 19045.4780

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/7619824d8048b6d2858f2051e1cc6bc334eeb146
