### ISSUE TITLE
gl_texture_nearest 1 not working on A32 custom rom EvoX 8

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1784]
I can't upload images anymore on application

**Comment by Vad1mCSO2** [comment]
![Screenshot_20240816-160558_Xash3D_FWGS_(Test) 1](https://github.com/user-attachments/assets/01f57494-3819-44d1-82fb-09ba45dffddc)
![Screenshot_20240816-160609_Xash3D_FWGS_(Test) 1](https://github.com/user-attachments/assets/e7fcca57-77a3-435f-a3b4-ef9b6292aa69)

**Comment by a1batross** [comment]
Renderer? GPU? Does it specifically happen on this custom ROM?

**Comment by Vad1mCSO2** [comment]
NanoGL, GPU is unknown

**Comment by Vad1mCSO2** [comment]
All GL renders no differences

**Comment by Vladislav4KZ** [comment]
Write the full name of the device. Is it Samsung? Or Oppo? What is A32?

**Comment by Vad1mCSO2** [comment]
Samsung Galaxy A32 4G
Android 14 EvoX 8

**Comment by Vad1mCSO2** [comment]
![Screenshot_20240816-162732_Настройки 1](https://github.com/user-attachments/assets/0b564fca-d77f-40bf-bd5c-3f484b0acee2)

**Comment by Vladislav4KZ** [comment]
It looks like the GPU related issue.
![Screenshot_20240816_145409_Discord.png](https://github.com/user-attachments/assets/49adad82-55b9-4c92-90fe-a51fc41bdca1)

**Comment by a1batross** [comment]
The device I'm working on, also has Mali-G52 and I don't think it has this issue. The main difference is that it uses FOSS drivers, and it's not Android, so... =/

I'm going to close it if it's Mali-specific issue. I'm not sure if anything could be done with filtering, unless there is some obscure Mali-specific extension for TexEnv.

**Comment by Vad1mCSO2** [comment]
That was bad acceleration graphics

**Comment by Vad1mCSO2** [comment]
(^^) works fine when switching to angle rendering
