### ISSUE TITLE
Build fails because non-defined macro ALLOCA_H

### ISSUE THREAD

**Issue by GrosserKaese** [FWGS/xash3d-fwgs#1785]
Like the title says. It basically fails here:

```
VFileSystem009.cpp
D:\_projects\xash3d-fwgs\filesystem\VFileSystem009.cpp(19): error C2006: "#include": expected FILENAME or <FILENAME>.
D:\_projects\xash3d-fwgs\filesystem\VFileSystem009.cpp(19): fatal error C1083: File (Include) can't be opened: "": No such file or directory
```
I tried to change the code to

```
#if defined (ALLOCA_H)
#include ALLOCA_H
#endif
```

but that produces only more fails. Any solutions?

I'm using WAF on Windows 11, latest patches, no changes in the source code so far.

**Comment by a1batross** [comment]
Can you attach a config.log file located in build folder?

**Comment by a1batross** [comment]
I pushed a small fix. Post config.log before pulling out latest sources anyway.

**Comment by GrosserKaese** [comment]
[config.log](https://github.com/user-attachments/files/16645221/config.log)

My guess is, the problem is with the alloca(1) function, it doesn't find it in all three header files.

**Comment by GrosserKaese** [comment]
Mh, the error is gone, but now it fails here:

```
D:\_projects\xash3d-fwgs\filesystem\filesystem.c(1719): error C2065: "ENOENT": nichtdeklarierter Bezeichner
D:\_projects\xash3d-fwgs\filesystem\filesystem.c(2838): error C2065: "ENOENT": nichtdeklarierter Bezeichner
```

It's missing the declaration? Here is the config.log:

[config.log](https://github.com/user-attachments/files/16645250/config.log)

**Comment by a1batross** [comment]
`alloca()` exists judging by config.log, but for some reason it doesn't link with `__security_cookie` and `@__security_check_cookie@4`. Not sure how could this happen, because MSVC enables it's buffer security features by default and we never disable them. 

Pushed a fix to always include `errno.h`. The error above should get fixed.

**Comment by a1batross** [comment]
Can I ask why you decide to build the engine yourself? We provide binaries built from latest commit at https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous.

**Comment by GrosserKaese** [comment]
I want to work on a "mod" which should have several enhanced features. The problem is that the usual SDK only compiles the .dll files, but not the .exe file with the "important" stuff in it.

Thank you so much for being so involved in it, buuuuut... it failed again. This time, he doesn't like mbstate_t being redefined, 'different base types':

`C:\tools\MVS\VC98\include\wchar.h(652): error C2371: "mbstate_t": Neudefinition; unterschiedliche Basistypen`

**Comment by a1batross** [comment]
Then can you tell which features, for example? Almost everything can be done on SDK side. And this engine is developed in a way to be extensible out of the box. There are few things where it doesn't yet, but it's usually solved on a per-mod basis.

Keep in mind that this engine is work in progress and the safest way to ensure your mod works on future systems, get all the optimizations and bug fixes is to stay as close to the upstream engine as it's possible.

The "exe" with important stuff is just a stub launcher that passes a default base directory to the engine. It's intentionally made to be as simple as possible, so one could take it and change the default directory, icon and everything else.

**Comment by a1batross** [comment]
Also, yeah, it's better to not have over 9000 compilers on your Windows machine. Compilers just do what they are being told to, and considering how easy it is to mess up with Windows, there has been numerous bugreports on builds being broken, which isn't really our fault, as the engine gets compiled successfully on GitHub Actions, engine developers' personal computers and virtual machines.

**Comment by GrosserKaese** [comment]
Not exactly, for example, if you want to enhance the flashlight, this is only possible with some workarounds, and if you want to change the lighting system itself, it's completly impossible.

Hey, let's close this down. The error seems to be strongly on my end, and debugging MY specific machine doesn't make any sense.

**Comment by a1batross** [comment]
>Not exactly, for example, if you want to enhance the flashlight, this is only possible with some workarounds, and if you want to change the lighting system itself, it's completly impossible.

I can recommend you looking into PrimeXT then. It has a lot of improvements on rendering side.

**Comment by GrosserKaese** [comment]
Nyeah, I did this earlier, and the project is pretty much dead. The documentation hasn't been updated in a year, and there is not much intention behind it anymore.

**Comment by a1batross** [comment]
1) I don't think that's something @SNMetamorph would agree with. But he is the sole developer behind it, and he also has a real life, it's expected to not see commits flowing every day.

2) So instead of picking a stable SDK you think your mod will have better support with an engine fork? Did I read this correctly?

**Comment by GrosserKaese** [comment]
1. The english documentation stays quite empty, the entities are almost non-documented. Updating your engine every once in a while is nice and all, but if you lack to explain to your users how all the pieces fall into place, you might as well not develope at all. Almost no tutorials, no explanation, no nothing. And I know that this is just a hobby for the guy, and I can't expect a AAA-title like support, but the case still stands.
2. I'll choose whatever serves my case better, and if the more versatile option is an an engine fork, then it's the engine fork.

**Comment by a1batross** [comment]
2. Don't forget to follow the GPL license, then. Despite all the licensing issues, the engine is still mostly derived from GPL code.

**Comment by nekonomicon** [comment]
> The english documentation stays quite empty, the entities are almost non-documented.

I think if you have any questions about this SDK you can ask author in discord.

**Comment by nekonomicon** [comment]
Anyway PrimeXT in active development and any things can be fully changed tomorrow and it would be hard to have documentation in actual state everyday.
