### ISSUE TITLE
HELP NEEDED!! Keeps CRASHING!!!

### ISSUE THREAD

**Issue by Impulse706** [FWGS/xash3d-fwgs#1789]
I recently tried to run xash3d on my jailbroken Nintendo Switch. However, when I load up the game, I'm greeted with a Hard Atmosphere Crash. (Error Code: 2144-0002). I have also tried using the title override method to run it (Which also failed). 

I've Tried Everything and can't seem to find anything online. Can Anyone help??

Thanks.

**Comment by a1batross** [comment]
Can you post any additional information?

I don't have my Switch anymore and can't test if it works or not. (Not sure if it ever worked in emulator though)

**Comment by a1batross** [comment]
Is there an engine.log in the same folder where "valve" is located?

This doesn't really give any info...

вс, 18 авг. 2024 г., 21:37 Impulse706 ***@***.***>:

**Comment by Impulse706** [comment]
No there's not. Do I need to find one or something? -Sorry i'm new to this whole thing anyways.

**Comment by a1batross** [comment]
by the way, do you run latest switch build from https://github.com/FWGS/xash3d-fwgs/releases/download/continuous/xash3d-fwgs-nswitch.7z?

cc @fgsfdsfgs can you try it on your Switch?

**Comment by Impulse706** [comment]
Pretty Sure I do. (Double Checking rn) I downloaded it from the hb appstore... don't know if that's the latest version.

**Comment by a1batross** [comment]
It probably isn't. As far as I remember, hb appstore has an outdated version. I don't think it can even work on modern firmware.

I think you can just replace everything.

**Comment by Impulse706** [comment]
Alright I'll be replacing everything. - but should i keep the contents of the valve folder that came with the download because it looks to have important contents. anyways ill still try. Thanks!!!

**Comment by Impulse706** [comment]
So I've copied all of the files and I believe i've done everything right, Annnnnnnnnnddd I still get the same error...😒. I honestly don't quite know what to do except delete files or move them around. I had a 2DS and used the same valve folder and i've tried 2 installations. I'm going to experiment and see what works.

**Comment by fgsfdsfgs** [comment]
Please redo the install from scratch. Nuke your xash3d folder, move the one from the release to your SD card, then add in the `valve` folder, preferably a clean one from the PC version.

**Comment by Impulse706** [comment]
So I can keep the .nro files??

**Comment by Impulse706** [comment]
So after completely retrying everything, it crashes again with yet the same error.... Help!!! I've searched for fatal.log and crash.log and could not find either.

**Comment by fgsfdsfgs** [comment]
Seems to work just fine on my Switch, but I am running 16.0.2 / AMS 1.5.3. Guess I'll update and recheck again.

**Comment by fgsfdsfgs** [comment]
Works on 18.1.0 / AMS 1.7.1 too. You're definitely doing something wrong. Can you post screenshots or listings of your `xash3d` folder, your `valve` folder and the `dlls` folder that's inside `valve`?

**Comment by Impulse706** [comment]
Sure! Here's A video: 

https://github.com/user-attachments/assets/fb1b4327-a1e1-45c8-a9e3-ee384a7e6ccc

Hopefully that link works idk.

**Comment by fgsfdsfgs** [comment]
And you're putting it in the `switch` folder on your SD card?

**Comment by Impulse706** [comment]
No I am not putting it in the switch folder. I'm running it by using the hbmenu or the method where you hold R and launch a title.

**Comment by Impulse706** [comment]
NeverMind!!! I got it working. Thank you all for your help!!!!!

**Comment by Noob0dooN** [comment]
> NeverMind!!! I got it working. Thank you all for your help!!!!!

How did you do it?

**Comment by Impulse706** [comment]
@Noob0dooN, After looking at some files and rebooting and reconfiguring some settings with files, I was able to get it working. I also tried checking for the most recent updates on the port, and after looking through homebrew again, I found the launcher and it worked.

**Comment by Noob0dooN** [comment]
> @Noob0dooN, After looking at some files and rebooting and reconfiguring some settings with files, I was able to get it working. I also tried checking for the most recent updates on the port, and after looking through homebrew again, I found the launcher and it worked.
> 
> If you have any questions or issues, I'd be happy to help.

i got it to work by completeley  deleting the Xash3D folder and installing it to _D:/Switch/_ instead of _D:/_
it was originally at the root of the sd because thats where the hb shop installed it and i didn't realise it was wrong
