### ISSUE TITLE
Add toggle for custom pk3 packages

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1794]
This feature can toggle custom HUD, Skins, models and etc.
> PK3 can package as ZIP format.

[BKHUD.zip](https://github.com/user-attachments/files/16659794/BKHUD.zip)

**Comment by a1batross** [comment]
That's not something an engine should do.

There is pk3 and pak support, there is `custom` folder for your mods. Just package your mod or paste it to `custom` folder, and that's it.
