### ISSUE TITLE
Перестал работать предиктинг оружий

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#1799]
Судя по всему, баг начал проявляться после коммита https://github.com/FWGS/xash3d-fwgs/commit/9a432a5a13b4ae45da2a67205b1f7ecefa5d9333

**Comment by a1batross** [comment]
У меня работает

**Comment by SNMetamorph** [comment]
Странно, это все проявляется только на одном конкретном сервере, но каким-то образом также у меня всё то же самое один раз получилось воспроизвести на локальном dedicated сервере, какая-то эзотерическая хрень

**Comment by a1batross** [comment]
>это все проявляется только на одном конкретном сервере

На каком?..

**Comment by SNMetamorph** [comment]
69.255.233.74:27014
