### ISSUE TITLE
SDL_GL_ResetAttributes

### ISSUE THREAD

**Issue by johndoe71rus** [FWGS/xash3d-fwgs#180]
successful build x86 but cant run, 
build log https://paste.ubuntu.com/p/8Dzt24jHJP/

then i run, get error 
LD_LIBRARY_PATH=$(pwd) ./xash3d
Xash Error: Unable to load the libxash.so: /home/johndoe/game/hlcs/libxash.so: undefined symbol: SDL_GL_ResetAttributes

lubuntu 18.04(i686)

**Comment by a1batross** [comment]
Что это за версия Ubuntu? Можешь писатл на русском, я помню вас из часа OpenXRay.

**Comment by johndoe71rus** [comment]
репы общие с убунту 18.04 но LXDE 
стоят обе либы libsdl1.2-dev и libsdl2-dev

**Comment by a1batross** [comment]
>This function is available since SDL 2.0.2. 

Вообще, выглядит так, будто у тебя устаревший SDL2, но он не может быть таким в 18.04.
И с SDL1.2 он наврядли мог слинковаться.
C++ манглинг ни при чём, так как С++ у нас нет.

Добавь ключ -v к вызовам waf configure и waf build и покажи лог сборки.

**Comment by johndoe71rus** [comment]
https://paste.ubuntu.com/p/gHZbP7zc6f/ 

libsdl1.2-dev 1.2.15+dfsg2-0.1ubuntu0.1
libsdl2-dev 2.0.9+dfsg1-1ubuntu1

**Comment by mittorn** [comment]
Что выдаёт ldd по libxash.so?

**Comment by johndoe71rus** [comment]
https://paste.ubuntu.com/p/k2qNStrwDC/

**Comment by johndoe71rus** [comment]
запустил. была библиотека libSDL2 в папке. убрал ее и запустилось.

**Comment by mittorn** [comment]
Значит с libSDL от голдсорса не работает. Он там 2.0.1

**Comment by a1batross** [comment]
Нет. А почему он должен?

@johndoe71rus локализации поддерживаются. Но для меню их никто не делал например. Есть в планах добавить поддержку в Weblate, но никаких сроков я не могу сказать.

**Comment by johndoe71rus** [comment]
где почитать про настройку локализации? Так понимаю это титры и озвучка.

**Comment by a1batross** [comment]
А, не, титры и озвучка это локализация самой халфы. Это всегда работало. На всяких рутрекерах полным полном фанатских локализаций халфы.

Под локализацию меню я имел ввиду это: https://github.com/FWGS/mainui_cpp/blob/master/translations/mainui_skeleton_everything.txt :)
