### ISSUE TITLE
[MOD: Counter-Strike Beta 6.5] Не запускается сервер

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1800]
В консоли выводится это сообщение:
```
***Only Losers cheat!***
```

Ввод кваров ``sv_cheats 0`` и ``cl_filterstuffcmd 0`` не помогает.

С ``cl_filterstuffcmd 1`` ещё появляется сообщение:
```
model is a privileged variable
```

На старом движке Xash3D FWGS 0.19.2 build 1201 эта версия Counter-Strike запускается.

На новом движке Counter-Strike начинает работать только с версии Beta 6.6

Лог движка: [engine.log](https://github.com/user-attachments/files/16714149/engine.log)

Проверял на:
Xash3D FWGS v49/0.21
Номер сборки: 3431
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/57774315774ef646951ec3e67d2171e36a3590a9
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4780

**Comment by a1batross** [comment]
Достаточно игровую папку переименовать в cstrike.

Я не знаю почему это работает со старым движком, но игра судя по декомпилу проверяет валидность файлов в client.dll и если что не так, выводит эту строчку и выходит.

Причём считывает файлы используя не движковые функции, а обычный сишный stdio. Так что и RoDir тут в пролёте.

**Comment by Vladislav4KZ** [comment]
На старом движке у меня установлены только две папки -- valve и csb65

На новом движке у меня также есть папка cstrike с установленным CS16Client.

**Comment by Vladislav4KZ** [comment]
Заработало после переименования папки ``cstrike``.

CS Beta 6.5 всё так же запустил с папки ``csb65`` на новом движке.

Переименование ``client.dll`` в ``cstrike/cl_dlls`` не помогало, помогло только переименование самой папки ``cstrike`` с установленной CS 1.6 и клиентом CS16Client.
