### ISSUE TITLE
Realistic lightmap (16x16 to 1x1 lightmap)

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1802]
![fu_plainhop_0001](https://github.com/user-attachments/assets/c8944834-5719-4bdf-874f-985650885e3d)
This feature can shadow realistic than default shadow
![image](https://github.com/user-attachments/assets/cb1dd28a-9acd-42ad-83e8-9501cbff882e)
Command used: gl_texture_nearest 1 and gl_lightmap_nearest 1

**Comment by a1batross** [comment]
It's already implemented by Uncle Mike in `bsp30ext`.

As for existing maps, I don't think it's possible to do anything with them.

**Comment by Vad1mCSO2** [comment]
I mean for existing maps

**Comment by mittorn** [comment]
I think, this needs separate utility that change lightmap scales on map

After rescaling lightmap, need recalculate it with light/rad ulility
Changing lightmap resolution with external lightmap is not possible now. 
Yes, it can be implemented somewhere else, for example, you can overload 
engine renderer with renderapi and load external lightmap lumps changing 
scale

**Comment by SNMetamorph** [comment]
> I think, this needs separate utility that change lightmap scales on map After rescaling lightmap, need recalculate it with light/rad ulility Changing lightmap resolution with external lightmap is not possible now. Yes, it can be implemented somewhere else, for example, you can overload engine renderer with renderapi and load external lightmap lumps changing scale

No other utilities are needed for this. Map just can be recompiled with rad tool with desired resolution and maybe some other settings.

**Comment by a1batross** [comment]
> > I think, this needs separate utility that change lightmap scales on map After rescaling lightmap, need recalculate it with light/rad ulility Changing lightmap resolution with external lightmap is not possible now. Yes, it can be implemented somewhere else, for example, you can overload engine renderer with renderapi and load external lightmap lumps changing scale
> 
> No other utilities are needed for this. Map just can be recompiled with rad tool with desired resolution and maybe some other settings.

I don't they are interested in maps for which they have rad files and all light entities intact. Vanilla HL for example does have all light entities, but not the rad files.
