### ISSUE TITLE
Can you make amxmodx works 

### ISSUE THREAD

**Issue by Mmah2000** [FWGS/xash3d-fwgs#1808]
This application works great for me, you've done alot ✅ only that amx modx dont work on Android, can you show us how to do that ?

**Comment by a1batross** [comment]
It's not that easy to make it work on Xash to begin with, let alone Android port.

**Comment by Mmah2000** [comment]
Okay 👌, i understand that now. Here's another thing to ask about, I've change the hud scale to 3, how i can adjust my crosshair to a small one and i want to change the video it's so wide the players look so far away and thank you sooooo mush. This is just questions not an issues you've done alot ✅ 
![Screenshot_2024-09-01-18-16-17-275_su xash engine test](https://github.com/user-attachments/assets/6618c422-b7bc-4653-8ea8-46e065b8cabb)

**Comment by a1batross** [comment]
I don't think it's really possible at the moment. 

Crosshair in cs16-client is drawn as part of HUD, so when you use hud_scale, it gets scaled too.

**Comment by Mmah2000** [comment]
> I don't think it's really possible at the moment.
> 
> Crosshair in cs16-client is drawn as part of HUD, so when you use hud_scale, it gets scaled too.

What about the video scale,can i zoom in  just a little bit 🙏 ?

**Comment by Mmah2000** [comment]
> I don't think it's really possible at the moment.
> 
> Crosshair in cs16-client is drawn as part of HUD, so when you use hud_scale, it gets scaled too.

Okey , one last thing how can zoom in a little bit 🙏, the players looks so faraway , how to that ?? This is the last question ,i promise.

**Comment by a1batross** [comment]
Use the `default_fov` cvar.

**Comment by Mmah2000** [comment]
> Use the `default_fov` cvar.

That's so easy for you 😅 i didn't get that , you mean default.res ?? And what to change in it, im so sorry.

**Comment by a1batross** [comment]
Open console, type `default_fov 90` and it will set your field of view to 90 degrees.

Oh wait, changing FOV doesn't work in CS as far as I remember.

Well, there is also thing called `r_adjust_fov`, it's set to 1 by default and it will try to compensate field of view for wide screen. You can try entering `r_adjust_fov 0` in the console, it will make stuff visually closer to you.

**Comment by Mmah2000** [comment]
> Open console, type `default_fov 90` and it will set your field of view to 90 degrees.
> 
> Oh wait, changing FOV doesn't work in CS as far as I remember.
> 
> Well, there is also thing called `r_adjust_fov`, it's set to 1 by default and it will try to compensate field of view for wide screen. You can try entering `r_adjust_fov 0` in the console, it will make stuff visually closer to you.

You are a hero 👏💪❤️ cant wait for a small crosshair thank you sooooo much.
