### ISSUE TITLE
Ambient_generic не учитывает положение игрока в пространстве

### ISSUE THREAD

**Issue by GoldSrcFreeman** [FWGS/xash3d-fwgs#1811]
При установке флага `Play everywhere` ambient_generic больше не учитывает положение игрока в пространстве и всегда играет моно звук.

**Comment by a1batross** [comment]
А он не должен?

**Comment by GoldSrcFreeman** [comment]
На Голдсорсе с этим флагом он работает как обычно с панорамным звуком, просто радиус становится бесконечный.

**Comment by a1batross** [comment]
Баг видимо в функции SND_SpatializeSounds в файле s_main:

```
	// don't pan sounds with no attenuation
	if( ch->dist_mult <= 0.0f ) dot = 0.0f;
```

Вот эта строчка возможно должна быть удалена, но проверить сейчас и закоммитить фикс я не могу.

**Comment by GoldSrcFreeman** [comment]
Мы в тебя верим!

**Comment by a1batross** [comment]
Fixed in 93dcbf3f

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/2eb8f88a201fdc68545b6bb4a38412fea420d2a4 

Поскольку этот баг/фича использовались в ксашевых модах, теперь это исправляется только включением `-bugcomp sp_attn_none`.
