### ISSUE TITLE
QUESTIONS ?

### ISSUE THREAD

**Issue by Mmah2000** [FWGS/xash3d-fwgs#1812]
1 What's the new features in this last update.
2 Whats about the hud scale Being drawn with crosshair thing any changes ?
3 can you change crosshair in cs Client too an small x or a dot maybe 🤔 
That's All and thank you so much "specially a1batross"

**Comment by a1batross** [comment]
I said there won't be any changes on this from our side.

Crosshair in cs16-client is something that better be reported to https://github.com/Velaron/cs16-client
