### ISSUE TITLE
Possible inaccuracy in TE_SPRITE_SPRAY implementation

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#1815]
The `TE_SPRITE_SPRAY` message calls `R_Sprite_Spray` which calls `R_Spray` with `kRenderGlow` as rendermode for the temporary sprites. However just by example of sprites used with this message it probably should be `kRenderTransAlpha` (e.g. tinyspit.spr used in bullsquid code).

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/c7ad8e4bf6dc48b6cb15ac869beb602a472af5d5
