### ISSUE TITLE
Xash 3d fwgs mac port for the console commands

### ISSUE THREAD

**Issue by Daveworstmaker** [FWGS/xash3d-fwgs#1816]
Im trying to figure out how to use console in half life 1 and i search the web but i can't find one thing about xash 3d fwgs mac port so can someone tell me how to set up console commands in the xash 3d fwgs and there is no command line

**Comment by a1batross** [comment]
There is updated Mac port. It unfortunately isn't packed into a Mac bundle yet, as I don't know how to do that, but you're supposed to run it from console anyway.

You can grab it from https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

Command line arguments and console commands are the same as on the other platforms.

**Comment by Daveworstmaker** [comment]
how do i set it up?
