### ISSUE TITLE
how to build on x86_64 system?

### ISSUE THREAD

**Issue by johndoe71rus** [FWGS/xash3d-fwgs#182]
Хотел прояснить.
Первый раз я собрал xash3d-fwgs на calculate linux (gentoo based) даже не понадобился ключ -8 для пропуска ошибок. Система была x86_64, но в конфиге была проверка что gcc может собирать 32-х разрядные приложения. Утвердительный был ответ на вторую попытку. В итоге собралось и запускается. На экране написано что i386 версия.
Решил собрать на новой lubuntu 20.04 x86_64. тут уже понадобился ключ -8, но из-за ошибок собирает не все необходимое. при запуске требует client_amd64.so.
сейчас собирается не на всех х86_64 системах?

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs#gnulinux

Причина описана в readme.

Билдсистема будет предпочитать собирать под i386. Если это возможно, соберёт. Невозможно, будет собирать под amd64. Такое поведение включено только для amd64, потому для сборки на тех же армах или эльбрусах всё будет собираться как есть.

-8 в данном случае просто отключает эту логику.

**Comment by ljcool2006** [comment]
I am so confused.
