### ISSUE TITLE
Spectator glitch when teleporting at start

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1824]
https://github.com/user-attachments/assets/c3defbb3-2e3f-4c07-acee-1994d104f23c

**Comment by a1batross** [comment]
What exactly is wrong here?

**Comment by Vad1mCSO2** [comment]
Optimizations of teleporting player too far to unoptimized area

**Comment by a1batross** [comment]
What do you even mean

**Comment by Vad1mCSO2** [comment]
When current player in spectator mode (e.g. Free-roaming camera and 1st person) glitches to unoptimized area and player gone. I switching left and right to restore view

**Comment by a1batross** [comment]
I don't see a problem there. The player normally gets teleported after an unsuccessful jump. 

(Also wtf is wrong with his nickname)

**Comment by Vad1mCSO2** [comment]
> The player normally gets teleported after an unsuccessful jump.

yes but will be gone due to optimization in spectator mode

**Comment by Vad1mCSO2** [comment]
I see this problem

**Comment by Vad1mCSO2** [comment]
but custom HUD texts still working

**Comment by a1batross** [comment]
Again, it works as intended. I don't see a bug here.

The spectated player doesn't perform a successful jump due to their low skill and by trigger on a map gets teleported back. You see exactly that while spectating.

There is no optimization or whatever you think.
