### ISSUE TITLE
Natural Selection still has issues on my device

### ISSUE THREAD

**Issue by JackA1ltman** [FWGS/xash3d-fwgs#1826]
As you can see, in the screenshot, after I created the server and entered the game, my spawn is the same as in the original Half-Life, and I cannot access any team selection entry (no changes). I checked the engine.log and found that the info_join_, Info_team_, and info_spectate prompts indicate that this function is missing. I am using the latest pre-built release from October 5th on an Android device with Android 13.I remember that the latest build has been updated to Fixes Natural Selection 3.3 beta 9. My NS version comes from the latest NS version at https://github.com/ENSL/NS, which is 3.3 beta 9.
Device:Redmi Note12T Pro
Version:Android 13 - MIUI 14
![Screenshot_2024-10-06-09-43-26-757_su xash engine test](https://github.com/user-attachments/assets/ebd79c24-a2b8-4213-956e-4d89ae5995ba)
[engine.log](https://github.com/user-attachments/files/17267850/engine.log)

**Comment by mittorn** [comment]
Did anyone publish NS port?
I remember, i made some broken (due to missing working vgui versions for android) NS build, but i never published it

**Comment by JackA1ltman** [comment]
> Did anyone publish NS port?
> I remember, i made some broken (due to missing working vgui versions for android) NS build, but i never published it
> 

o
Only because of this.Maybe this update has nothing to do with Android devices XD![Screenshot_2024-10-06-12-37-30-400_mark.via-edit.jpg](https://github.com/user-attachments/assets/ab43e7a3-2407-48e6-8a72-9a0dd58d2d1d)

**Comment by a1batross** [comment]
You can't run NS on Android because NS itself isn't ported.
