### ISSUE TITLE
Xbox 360 gamepad issues

### ISSUE THREAD

**Issue by RobG66** [FWGS/xash3d-fwgs#1827]
I downloaded the nightly executable and tried playing HL.  There's no dead zone adjustment on the controls so as a result I see minor drift in the controls.  Look up/down controls don't work correctly (they re-center almost immediately) and look left/right is jerky.

**Comment by SNMetamorph** [comment]
Yeah, I think there is a plenty of work for proper supporting gamepads or platforms such as Nintendo Switch and PS Vita. So it will be very useful if somebody explain which features for this type of controls are crucial and how they works or how they should be implemented.

**Comment by a1batross** [comment]
There are two game pad input systems. The one that made in client.dll, originally implemented by Valve, and the one that's only specific to Xash3D FWGS (which was mostly made to simplify input for mods by moving it back to the engine).

You can disable the Valve's gamepad support with `-nojoy` command line and disable Xash's gamepad support with `-noenginejoy`. It is also possible to disable them in console with `joystick 0` for Valve's input or `joy_enable 0` for Xash's input.

Both have their own advantages and disadvantages, but as for setting up deadzone, Valve's uses cvars `joyforwardthreshold`, `joysidethreshold`, `joypitchthreshold` and `joyyawthreshold` with values in percentages and Xash uses `joy_forward_deadzone`, `joy_side_deadzone`, `joy_pitch_deadzone`, `joy_yaw_deadzone` with integer values from 0 to 32768. (forward and side means movement, pitch and yaw means camera).

To disable up/down centering, you need to enable `Joystick look` in the menu or enter `+jlook` in the console.
