### ISSUE TITLE
[Enhancement] Show used video memory for textures during r_showtextures

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1831]
Self-explanatory.

**Comment by a1batross** [comment]
Implemented in https://github.com/FWGS/xash3d-fwgs/commit/96f306170968624afe3b881fb9527f2b2c7f7a22.

Also added a small QoL feature to skip empty pages, which is often the case with default renderer: as normal textures get uploaded one by one sequentially, skyboxes start from 5800 for compatibility with some (which?) old mods.
