### ISSUE TITLE
Opposing Force and another mod with new weapons won't show new weapon

### ISSUE THREAD

**Issue by Lappiphat55** [FWGS/xash3d-fwgs#1833]
When I play Opposing Force in android and another mod with new weapon such:
-Scientist Slaughterhouse
-Expanded Arsenal
-Brutal Half-Life Beta 2

Does anyone know how to fix this?

**Comment by a1batross** [comment]
These mods require a special APK that contains ported game libraries. Unfortunately, there aren't any for the new engine.
