### ISSUE TITLE
How compile dlls/cs_arm64.so?

### ISSUE THREAD

**Issue by hav4k** [FWGS/xash3d-fwgs#1834]
Hi.

I wanna setup a server with Counter Strike 1.6 in Raspberry Pi 3 Model B+, but console log needs this archive to work. Please, any advice is wellcome. Thanks.

Regards.

**Comment by nekonomicon** [comment]
Just compile regamedll_cs from official repository.
We didn't support it anyway.

**Comment by a1batross** [comment]
@nekonomicon regamelite is DEAD.

Upstream ReGameDLL_CS works everywhere, except the binary is probably need to be renamed to match the [library naming scheme](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/extensions/library-naming.md).

I'm closing this as this isn't strictly an engine bug and we both already told reported what to do. If you have any questions, reopen it or just create a new one.

**Comment by hav4k** [comment]
Finally, i use Wine with hlds.exe. For now, is working fine. Thanks for reply, anyway.
