### ISSUE TITLE
Build instructions for Fedora

### ISSUE THREAD

**Issue by d47081** [FWGS/xash3d-fwgs#1835]
Tried to replace libs with `yum` and `-devel` but no luck
https://github.com/FWGS/xash3d-fwgs#debianubuntu

Also here in no `sudo dpkg --add-architecture i386`

Could somebody share the recipe or just few examples of dependencies name?

**Comment by nekonomicon** [comment]
Just install packages with `.i686` postfix.

**Comment by a1batross** [comment]
Fixed. https://github.com/FWGS/xash3d-fwgs#redhatfedora
