### ISSUE TITLE
Ограниченная видимость карты после игры на GoldSource серверах.

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1839]
Чтобы воспроизвести этот баг, вам нужно подключиться к GoldSource серверу, затем отсоединиться от него и запустить любую карту. При повторном запуске карты этот баг исчезает.

Видео: https://www.youtube.com/watch?v=9IStOYDPFWs

Проверял на:
Xash3D FWGS v49/0.21
Номер сборки: 3481
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/10bfadb556b9043f4dd1b4672d2342485be0e457
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.5011

**Comment by Vladislav4KZ** [comment]
Во время воспроизведения этого бага, при движении игрока, в консоли появляются следующие сообщения:
```
PM  Got a velocity too high on 2
PM  Got a velocity too low on 0
PM  Got a velocity too low on 1
PM  Got a velocity too high on 2
```

**Comment by Vladislav4KZ** [comment]
Команда ``restart`` кстати не помогает, помогает только повторный запуск сервера через меню с этой же или другой картой.

**Comment by Vladislav4KZ** [comment]
Если запускать карту через команду ``map`` в консоли, то баг будет воспроизводится до тех пор, пока не будет введена команда ``disconnect``.

То есть при смене карты через консоль с помощью команд ``map`` или ``changelevel`` баг будет воспроизводиться и на следующей карте как в мультиплеерном, так и в синглплеерном режиме.

**Comment by a1batross** [comment]
Как оказалось, Ксашу не очень нравится когда отсутствует таблица для movevars_t, которая как раз таки не используется для GoldSrc. :) https://github.com/FWGS/xash3d-fwgs/commit/505ad6d69b3c30c0372e27aa9e6680771e77819d
