### ISSUE TITLE
FWGS v0.20 and 0.19.2 Android/ Zombie models don't load

### ISSUE THREAD

**Issue by zapepsiman** [FWGS/xash3d-fwgs#184]
In my first try with the valve folder it does load, but when I launch it back the zombie models disappear (only the npc is active)

**Comment by lewa-j** [comment]
Are you sure your game data wasn't corrupted?

**Comment by zapepsiman** [comment]
i tried with valve filesof the pc version of xash3d, won version and the steam one, the only way I found to fix it is unnistalling and reinstalling Xash FWGS,  going into c1a1 (first encounter with zombies), saving, closing xash and going again, it seems to work

**Comment by zapepsiman** [comment]
It appears "Gibbed monster is thinking" in the console when the zombie doesn't load

**Comment by lewa-j** [comment]
Sounds like skill.cfg issue

**Comment by zapepsiman** [comment]
Skill.cfg
// Zombie
sk_zombie_health1	"50"
sk_zombie_health2	"50"
sk_zombie_health3	"100"

sk_zombie_dmg_one_slash1	"10"
sk_zombie_dmg_one_slash2	"20"
sk_zombie_dmg_one_slash3	"20"

sk_zombie_dmg_both_slash1	"25"
sk_zombie_dmg_both_slash2	"40"
sk_zombie_dmg_both_slash3	"40"
