### ISSUE TITLE
После игры на GoldSource сервере, тег [Xash3D] остаётся в никнейме при игре на серверах, работающих на движке Xash3D

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#1840]
Этот тег убирается сменой никнейма, если играть не на сервере, работающем на движке GoldSource.

Проверял на:
Xash3D FWGS v49/0.21
Номер сборки: 3481
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/10bfadb556b9043f4dd1b4672d2342485be0e457
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.5011

**Comment by a1batross** [comment]
Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/67c898f9ad10f1da364cacc743c0248625537fee
