### ISSUE TITLE
Сетевая ошибка, вылет с сервера во время игры

### ISSUE THREAD

**Issue by someone38** [FWGS/xash3d-fwgs#1842]
Xash3D FWGS 0.21 (3481, 10bfadb, master, android-arm64)
Сервер Dawn Half-life 84.22.153.100:27015
Прикрепляю логи
[buffer.dat.log](https://github.com/user-attachments/files/17355734/buffer.dat.log)
[engine.txt](https://github.com/user-attachments/files/17355742/engine.txt)

**Comment by a1batross** [comment]
Возможно, исправлено. https://github.com/FWGS/xash3d-fwgs/commit/ff47fbaedcef35db2cdaa4675b592fb22ae80ea9
