### ISSUE TITLE
Add HLSDK to builds.

### ISSUE THREAD

**Issue by Buggem** [FWGS/xash3d-fwgs#1850]
It's pretty annoying to manually compile HLSDK for builds so maybe you could add it to the releases if you would be so kind? `valve` and `bshift` are the most played GoldSrc games, so could you just update the Github Actions dockerfile to build FWGS/hlsdk-portable `master` and `bshift` branches? It would be much appreciated and save me a LOT of time. (I noticed that the MacOS versions have it compiled, at least for `valve`)

**Comment by a1batross** [comment]
Xash3D FWGS is an engine. Build HLSDK or not is a choice of a port maintainer, some ports include it, some ports don't.

Usually ports that don't include prebuilt HLSDK already has precompiled binaries you can get from Steam like Windows or Linux.

**Comment by a1batross** [comment]
Though we probably should do that on 64-bit builds.

**Comment by a1batross** [comment]
On other hand, I would rather discourage users from using 64-bit builds on platforms supported by GoldSource and games and mods for it.

Therefore, Windows and Linux on x86 won't get prebuilt game binaries because these platforms can run 32-bit engine and have all mods.

But Mac on x86 don't support 32-bit applications anymore, therefore it has prebuilt binaries. Same for Android, PSVita and NSwitch.

**Comment by Buggem** [comment]
@a1batross but at the same time, 64-bit builds provide more RAM access allowing to fully utilise the power of the clients computer. Mine has 64gbs of RAM, and I didn't buy that for nothing :P

**Comment by Buggem** [comment]
And also `bshift` Steam binary had a crash, so I had to manually compile it.

**Comment by nekonomicon** [comment]
> And also bshift Steam binary had a crash, so I had to manually compile it.

https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md

> but at the same time, 64-bit builds provide more RAM access allowing to fully utilise the power of the clients computer.

But it's completely useless for such old games.
64-bit common registers and SIMD can give you boost, but not RAM.
