### ISSUE TITLE
MultiEmulator broke Windows XP compatibility

### ISSUE THREAD

**Issue by Srandista** [FWGS/xash3d-fwgs#1854]
I know it's 2024, but last time, it was an easy fix, so maybe it'll be same this time as well.

Adding MultiEmulator broke Windows XP compatibility, Xash3D won't launch with following error messages:

```
xash3d.exe - Entry Point Not Found
The procedure entry point CompareStringEx could not be located in the dynamic link library KERNEL32.dll. 

Unable to load the xash.dll: The specified procedure could not be found.
```

If I use older xash.dll, the game will run just fine, but that kinda defeats the purpose.

**Comment by a1batross** [comment]
I will look into that.

**Comment by a1batross** [comment]
Could you check latest commit?

**Comment by Srandista** [comment]
It works again!

**Comment by Srandista** [comment]
It works again!
