### ISSUE TITLE
player: Camera not rotated accurately while strafing

### ISSUE THREAD

**Issue by Buggem** [FWGS/xash3d-fwgs#1858]
In Steam Half-Life, there is a little tilt when using A or D keys. This isn't really that big a problem but if you are aiming on accuracy you should implement this.

**Comment by nekonomicon** [comment]
Try to set `sv_rollangle 2` in the console.

**Comment by a1batross** [comment]
This feature has always been present, even in the original Xash3D, you just use `sv_rollangle` cvar.
