### ISSUE TITLE
SayText and TextMsg

### ISSUE THREAD

**Issue by GLoOoccK** [FWGS/xash3d-fwgs#1859]
Problem displaying messages with plugins and modules that use `#Spec_PlayerItem`

![Spec_PlayerItem](https://github.com/user-attachments/assets/a1382c84-76f9-4c75-8d74-0a15860a3b21)

https://github.com/alliedmodders/amxmodx/issues/776#issuecomment-546615132
https://github.com/WPMGPRoSToTeMa/SafeNameAndChat/blob/master/Main.cpp#L990-L1029
https://github.com/OciXCrom/ChatManager/blob/master/scripting/include/cromchat.inc#L892

**Comment by a1batross** [comment]
Engine version?

**Comment by a1batross** [comment]
Are you sure it's also engine problem and not cs16-client specific?

**Comment by Buggem** [comment]
cs16-client used on windows/linux is very unstable sadly. It probably is a cs16-client problem.

**Comment by a1batross** [comment]
`#Spec_PlayerItem` is defined NOT in titles.txt but in valve_english.txt.

Ideally, those strings should've been translated using pre-existing VGUI2 translation files support but instead it follows hardcoded array of strings, and `#Spec_PlayerItem` isn't one of them: https://github.com/Velaron/cs16-client/blob/8f325bc5e42c4e073cd46e9377118806fb7d59cf/cl_dll/saytext.cpp#L180

I probably wrote this part before I implemented VGUI2 translation files parsing and forgot to fix it.

cc @Velaron could you add `Localize()` call there or just turn `#Spec_PlayerItem` into a `%s`.

**Comment by a1batross** [comment]
Closing it here as it's definitely a cs16-client bug. Reopen issue at https://github.com/Velaron/cs16-client.
