### ISSUE TITLE
In the xash3d-fwgs-win32-i386 version from 26.10.2024, the tooltips at the bottom of the screen do not work

### ISSUE THREAD

**Issue by usergithub64** [FWGS/xash3d-fwgs#1861]
In the xash3d-fwgs-win32-i386 version from 26.10.2024, when hovering the mouse over the menu items, the tooltips at the bottom of the screen do not work and the menu items are shifted to the bottom of the screen:
![xash3d_2024_10_27_14_32_10_518](https://github.com/user-attachments/assets/67394999-d9ae-4b87-b90e-900d0c7f286a)
![xash3d_2024_10_27_14_32_21_578](https://github.com/user-attachments/assets/a7fbd1ba-9418-4439-970a-17194c90a827)
In the xash3d-fwgs-win32-i386 version from 15.10.2024, everything works fine:
![xash3d_2024_10_27_14_30_58_508](https://github.com/user-attachments/assets/5fe3cb7a-6738-40b1-b647-69d141b372ad)
![xash3d_2024_10_27_14_31_15_255](https://github.com/user-attachments/assets/4064c4ab-1464-438b-ae62-d7ce9d825a2e)

**Comment by a1batross** [comment]
It's an intentional change, as WON menu never uses them.

Not only that, in most cases they aren't helpful at all, stating the obvious help text like "Done" button just says "Go back to previous menu".

They're only left in menu that were added by us, like Touch and Gamepad menus, as they often have new settings, where a little help string might be useful.

**Comment by a1batross** [comment]
These tooltips aren't helpful for touchscreen users either, as they only show up on mouse hover and there is nothing similar to this action on a touchscreen.

BTW, I'm open to suggestions for implementing short help/description.

**Comment by a1batross** [comment]
Feel free to open a new issue with suggestions for better help strings.

**Comment by usergithub64** [comment]
Why are the options in the main menu shifted to the bottom of the screen, like in the first screenshot?

**Comment by a1batross** [comment]
It's the same, original WON menu does this.

**Comment by usergithub64** [comment]
Can you tell which commits revert these fixes? (so that the menu items show up as in the 15.10.2024 version and the tooltips show up as in the 15.10.2024 version)

**Comment by a1batross** [comment]
Yeah, you don't actually need to build an engine for this. 

All you need is to revert [this](https://github.com/FWGS/mainui_cpp/commit/5432b8642ed1ea7ae6f655636ff16e706023ace2) and [this](https://github.com/FWGS/mainui_cpp/commit/196f22ae9a43b9470674ba583c6a90d93d8e5906) and compile ONLY mainui_cpp and put it in `cl_dlls` directory.

`menu.dll` located in alongside `client.dll` always have precedence over built-in one.
