### ISSUE TITLE
Increasing multiplayer FPS limit

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1864]
As I've been told, Xash is slowly getting popular in KreedZ community and the main movement trick: bhopping is highly FPS dependent. 

200 doesn't seem enough for them and Xash3D FWGS being nicely optimized can easily reach 1000 FPS, so maybe it's time to increase the limit to either 500 or even 1000.

There are, however, few bugs caused by high frame rate like #1851 and one that seems wasn't reported yet: we're sending clc_move commands to server too often, and it's easy to get kicked by anti-flood mechanism. These two issues are probably interconnected.

**Comment by Moharebx** [comment]
I already told you that we need a much more FPS than 200 lol I think 600 is good like crack cs1.6 once u go over 600 it starts going slow motion so 600 is good...

Try to post the change in a small release and see if all players will face the same bugs or maybe new ones :D 
( Plz don't forget the resolution change as well :) )

**Comment by a1batross** [comment]
>once u go over 600 it starts going slow motion

Engine side of this bug has already been fixed.

**Comment by Moharebx** [comment]
> Engine side of this bug has already been fixed.

Nice so when u gonna release the version that has max 600 FPS ?

**Comment by a1batross** [comment]
Maybe soon. 

The idea is to keep the limit at 200 FPS for multiplayer games but let it go up to 1000 with `fps_override` cvar set to 1.

**Comment by Moharebx** [comment]
> The idea is to keep the limit at 200 FPS for multiplayer games but let it go up to 1000 with `fps_override` cvar set to 1.

So it's gonna be able to reach 200 by default with no commands? And after U apply the commands it can reach to 1000 ? Both multiplayer and singleplayer?
