### ISSUE TITLE
HELP ME PLEASE!

### ISSUE THREAD

**Issue by Mmah2000** [FWGS/xash3d-fwgs#1869]
Hello @a1batross 
I installed xash on termux on debian and ubuntu the dedicated server works perfectly the only thing that im not able to add metamod-r or metamod-p idk y. Every time i try to add metamod server crash i installed xash3d 32bit new engine on qemu-user i386
And tried xash3d 64amd on 64bit architectures. Im the only who can't add metamod "server without metamod works perfectly in both" i hope u can help 
![image0](https://github.com/user-attachments/assets/f9aac54b-a1d0-4469-b0af-2e9ddfee8348)
I really hope you can help or give instructions what to do . THANKS

**Comment by a1batross** [comment]
Who knows? Try the same on actual x86 hardware, it might be QEMU limitation.

**Comment by Mmah2000** [comment]
> Who knows? Try the same on actual x86 hardware, it might be QEMU limitation.

Give me instructions what to do from zero plz n thank you so much u r my hero "im newbie at termux" maybe I've been doing it wrong

**Comment by a1batross** [comment]
You have to figure out yourself. 

At least, you need some kind of PC or an x86 server. I don't think you could do everything you want just from your phone.

**Comment by Mmah2000** [comment]
Hello a1batross plz help install dedicated server on termux so i can add metamod, i want to create lan server with amxmodx  , 😁 i didn't know how to do it and there's no instructions i can find on internet plz help . when u have time 😭 its nothing compared with ur knowledge i have no one to ask else but u

**Comment by a1batross** [comment]
Again, better do this on x86 hardware rather than on your phone.

There is no much sense doing this from emulator, performance would be abysmal.

**Comment by Mmah2000** [comment]
> Again, better do this on x86 hardware rather than on your phone.
> 
> There is no much sense doing this from emulator, performance would be abysmal.

The thing is im doing all this so I can play offline lan with amxmodx on my phone, run server n play in it i saw ppl playing that i just don't know how to do it

**Comment by Mmah2000** [comment]
I installed `proot-distro` `qemu-user-i386` and  and tried `qemu-user-arch64` when i add metamod server crash , what to in my situation i need info .i want to do it just from my phone . This is the last thing and thank you @a1batross so much

**Comment by Mmah2000** [comment]
So is that all help u can provide do it on actual hardware?????? @a1batross

**Comment by Mmah2000** [comment]
![Screenshot_2024-11-10-11-48-53-963_com termux](https://github.com/user-attachments/assets/ae103f7b-ac95-4e6f-b34c-a2a578c63c09)
As u see here regamedll work just fine why metamod don't, it work on everyone's phone y it doesn't work for me ??
