### ISSUE TITLE
Missed CODING_STYLE.md ?

### ISSUE THREAD

**Issue by UnkwUsr** [FWGS/xash3d-fwgs#187]
As written in https://github.com/FWGS/xash3d-fwgs#contributing
> Before sending a PR, check if you followed our coding guide in CODING_STYLE.md file.

But I can't find that CODING_STYLE.md file anywhere in all your projects. I think it's missed.
https://github.com/FWGS/xash3d-fwgs/blob/master/CONTRIBUTING.md also sheds little bit light.

**Comment by a1batross** [comment]
You're right. It was meant to be CONTRIBUTING.md.
