### ISSUE TITLE
My fps is still stuck at 60 in the new experimental release !

### ISSUE THREAD

**Issue by Moharebx** [FWGS/xash3d-fwgs#1872]
![Screenshot_2024-11-01-22-38-21-622_su xash engine test](https://github.com/user-attachments/assets/272952a7-1f6f-49e8-8789-6580ef70d927)

I did everything right but it's still 60 as you can see from the down right corner, I have my cl_showfps 2 developer 1 fps_override 1 and fps_max 999 it's still 60 idk why :b

**Comment by SNMetamorph** [comment]
Try `gl_vsync 0`
