### ISSUE TITLE
Arm64 Binary

### ISSUE THREAD

**Issue by coreybruce** [FWGS/xash3d-fwgs#1874]
Hi there I was just wondering if you we could get Arm64 binaries

**Comment by nekonomicon** [comment]
For what platform?

**Comment by coreybruce** [comment]
Sorry I should have specified, for Linux please :)

**Comment by coreybruce** [comment]
I have been doing my own unofficial binaries for Arm64 for a while and do it every 2 weeks which I use for my AUR package

https://gitlab.com/linuxbombay/xash3d-fwgs
https://aur.archlinux.org/packages/xash3d-fwgs-bin

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/bfb84a7ac4b33529bc3c715bdb508e62416120e6

Though we don't run tests there yet.

And it also doesn't include hlsdk-portable build, it's something that should be resolved in hlsdk-portable repo ideally.

**Comment by Srandista** [comment]
Just want to thank you for providing these new binaries, it's very much appreciated!
