### ISSUE TITLE
Audio lagging

### ISSUE THREAD

**Issue by HaasOfPain** [FWGS/xash3d-fwgs#1878]
I have a problem with the new engine the music of the game stutters like cs 1.6 menu music and half life OST maybe his my phone idk

**Comment by a1batross** [comment]
I've upgraded SDL to 2.30.9, can you check with the latest build?

**Comment by HaasOfPain** [comment]
Same problem

**Comment by HaasOfPain** [comment]
Same problem in the new version, maybe his my phone my phone his an A15

**Comment by a1batross** [comment]
Can you post more info about your device.

**Comment by HaasOfPain** [comment]
Maybe this can help
VUE Audiotechnik a-15
A full range system with the following features:
Frequency response: 52 Hz–18 kHz 
Max long term output: 125 dB SPL 
Coverage: 70º x 55º 
Construction: Multi-ply, cross-grain laminated birch

**Comment by a1batross** [comment]
Eh... I didn't really mean an audio device, but rather what you're running Xash on, is it the bluetooth audio (which was cauing some troubles before) or it's wired.

**Comment by HaasOfPain** [comment]
When i use wireless headphones via bluetooth the audio sounds good

**Comment by a1batross** [comment]
I'm still asking you about what you're running the game engine on...

**Comment by HaasOfPain** [comment]
What you mean phone or computer?
The sistem of the phone?
If im using headphone?
What's the version of xash?

**Comment by D-113CR** [comment]
Galaxy A15 specs:

SoC: Mediatek Helio G99 8x @~2 GHz
GPU: Mali-G57 MC2
RAM: 4/6/8 Gb depending on model

**Comment by HaasOfPain** [comment]
In the new version the audio is now fixed
