### ISSUE TITLE
Xash Error

### ISSUE THREAD

**Issue by Andrew-Yang-please** [FWGS/xash3d-fwgs#188]
https://i.ibb.co/XssW1hm/Xash-Error.png
I see this when I try to play Half-Life

**Comment by a1batross** [comment]
Can you provide more information?

**Comment by Andrew-Yang-please** [comment]
> Can you provide more information?

Alibek, what sort of more information would you like to see?

**Comment by nekonomicon** [comment]
You need to place vgui.dll from Half-Life folder to folder with Xash3D FWGS.

**Comment by a1batross** [comment]
@nekonomicon please don't try to poke in the sky **even** if you think you're right.

vgui.dll (although it's proprietary) is being distributed within engine release and even with testing builds. Users don't need to add or replace it usually.

@Andrew-Yang-please describe how you installed the game and the engine. Where did you took the Half-Life game data? Which engine build are you running? Do you have client.dll in valve/cl_dlls/client.dll folder? Did you tried to look into it with Dependency Walker? Is it actually valid file?

**Comment by nekonomicon** [comment]
@a1batross AFAIR, the latest release for windows does not have vgui library and extras.

**Comment by a1batross** [comment]
Yeah, extras are optional and don't affect the client.dll loading but we should include them anyway. That's... a known problem. :)

**Comment by TheComputerNerd88** [comment]
In case anyone is looking for a solution to this issue, here's how I solved it. Head to the [Xash3D ModDB page and download it](https://www.moddb.com/engines/xash3d-engine/downloads/xash3d-engine-v099-build-4344-extras-stable). Disregard the first 2 archives found in the zip file, the one you want is called, "Xash3D_extras.7z". Extract it and move the valve/cl_dlls/client.dll file from the archive into your installation. 

Your Xash3D install should now load!

**Comment by nekonomicon** [comment]
@TheComputerNerd88 you didn't right. It's not solution.

**Comment by TheComputerNerd88** [comment]
My solution works for me - just wanted to tell people a possible way to get Xash3D working for them in case they ever come across this thread.

**Comment by nekonomicon** [comment]
@TheComputerNerd88 
1. @Andrew-Yang-please did not answer a1batross's qustion.
2. Your solution useful for original Xash3D, but useless for Xash3D FWGS. Xash3D FWGS is aimed to support Steam HL, so you must not to replace anything.
3. For Xash3D FWGS you must use extras from FWGS/xash-extras repository.

**Comment by TheComputerNerd88** [comment]
I see. Sorry for the trouble!

**Comment by EllVEBIT** [comment]
![Screenshot_2020-07-15-21-17-41](https://user-images.githubusercontent.com/51740831/87573796-e1207580-c6e6-11ea-8c26-c935dc005025.png)
![Screenshot_2020-07-15-21-16-58](https://user-images.githubusercontent.com/51740831/87573802-e2ea3900-c6e6-11ea-91e7-b285e871b176.png)
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/4926706/engine.log)
Последняя тестовая

**Comment by nekonomicon** [comment]
@EllVEBIT одна issue на один баг.
Тут тема началась с винды, а ты пришел с андроидом.
