### ISSUE TITLE
(PSVITA) xash doesnt go past console screen.

### ISSUE THREAD

**Issue by Renunderscore** [FWGS/xash3d-fwgs#1887]
what the title says, it just shows me a console with some text, that has a couple errors that read:
error: cant initialize dlls/hl_psvita_armv7hf.so: "ux0:/data/xash3d/valve/dlls/hl_psvita_armv7hf.so": could not resolve symbol "strtok"

opengl error: GL_INVALID_ENUM while uploading *default (2d)
Error: cant initialize gameui dll: "ux0:/data/xash3d/libmenu.so": Could not resolve symbol "strtok"

then after that it just says execing a bunch of files but nothing more.

**Comment by a1batross** [comment]
Tried to fix the `strtok` in 0db2597d1e9b300bcc33d8486bd6b7f8e61ef996.

Can you wait until it finishes building for PSVita (usually takes around 10 minutes) and try again?

For the future, you can just post engine.log. It should be created in `xash3d` folder.

**Comment by Renunderscore** [comment]
ah sweet, thanks! will notify as soon as it updates

**Comment by Renunderscore** [comment]
Works perfectly now! much appreciated.
