### ISSUE TITLE
Day of Defeat 3.1b broken menu sounds, in-game music goes B-r-r-r-r-r-r

### ISSUE THREAD

**Issue by jarcen** [FWGS/xash3d-fwgs#1888]
This one:

https://www.moddb.com/mods/day-of-defeat/downloads/dod-v31b-for-steam

Works fine on vanilla engine, on Xash3D audio is broken. I tried latest build from 9 hours ago, situation has improved and at least music in main menu re-appeared but menu sounds are still silent and in-game music is still stuck and makes loud motor noises.

**Comment by Vladislav4KZ** [comment]
I also reported this earlier: https://github.com/FWGS/xash3d-fwgs/issues/1263
