### ISSUE TITLE
No sound on Windows Vista

### ISSUE THREAD

**Issue by D-113CR** [FWGS/xash3d-fwgs#1892]
I don't know if this is a hardware issuse or a driver issue but I noticed the same issue occuring in ET: Legacy (Wolfenstein: Enemy Territory) when using SDL2 as the audio backend. This might also be an issue with using WASAPI since a few other programs were silent. Is there a way to force ASIO or DirectSound instead of WASAPI?

**Comment by mittorn** [comment]
So, it seems to be SDL-related?
SDL have options to select uded audio backend, maybe this may help to 
workaround this

**Comment by a1batross** [comment]
Can you try to make a batch file that looks like this?

```
set SDL_AUDIODRIVER=directsound
xash3d -dev 2 -log
```

And paste `engine.log` here?

**Comment by a1batross** [comment]
We now use DirectSound by default.
