### ISSUE TITLE
How Can my public server aper on old  engine direct list

### ISSUE THREAD

**Issue by happyhere-TN** [FWGS/xash3d-fwgs#1895]
There is any way or cmd some thing to make my cstrike server aper on direct list servers for old engine (im open it with new engine )
sv_master ms2.xash.su:27010 desnt work :/

**Comment by a1batross** [comment]
You can't. The old engine uses Xash3D 48 protocol, where the new engine uses Xash3D 49 protocol.

**Comment by happyhere-TN** [comment]
Done  :/
