### ISSUE TITLE
Pls how fix this

### ISSUE THREAD

**Issue by Skye450** [FWGS/xash3d-fwgs#1896]
![IMG_20241122_101705.jpg](https://github.com/user-attachments/assets/d0b69ef6-b156-4747-b3a5-fcf7f8f369b2)

Server android work servers pc no compressed data

**Comment by a1batross** [comment]
Can you post an IP address of a server where this happens

пн, 25 нояб. 2024 г., 15:00 Skye450 ***@***.***>:

**Comment by Skye450** [comment]
46.174.55.60:27015

**Comment by Skye450** [comment]
> 
> 
> 46.174.55.60:27015
> + Problem ![Screenshot_2024-11-25-15-15-23-534_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/1a293aa4-10f8-420e-a457-4fb6fbf95b4a)
> 
> 

And kick my don't I know this server not this 46.174.55.60:27015
![Screenshot_2024-11-25-15-28-23-747_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/4303c114-e691-4a8a-a9df-2dab949957cb)

**Comment by a1batross** [comment]
"Malformed/abnormal compression data" error fixed with https://github.com/FWGS/xash3d-fwgs/commit/888599677ebae40626b1b970b2bcc362e2d94185

If you have something else, just open a new issue.
