### ISSUE TITLE
RCBot for Rocket Crowbar crashes on startup

### ISSUE THREAD

**Issue by jarcen** [FWGS/xash3d-fwgs#1899]
Works on vanilla HL 1.1.1.0, crashes instantly on Xash3D.

RCBot is taken from here: http://rcbot.bots-united.com/files.htm
Bottom left tile that says "RCbot1 for Rocket Crowbar", direct link: http://rcbot.bots-united.com/downloads/bot_for_rcb/rcbot_rcb150.zip
Installation is fiddly, to simplify repro I assembled minimal working version of the mod with bot: [RockCrowbar.zip](https://github.com/user-attachments/files/17962983/RockCrowbar.zip)

Text copied from crash message box: (OCR, possible errors)

```
Ver: Xash3D FWGS 0.21 (build 3529-df4194c, win32-i386)
Sys_Crash: address 00000000, code C0000005
000000000(???)
1 100270A0 GetEntityAPI (rcbot.dll)
2 00031355 WinMain (D:\a\xash3d-fwgs\xash3d-fwgs\game_launch\game.cpp:210:64) (xash3d.exe)
3 00D315B0 _scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:26) (xash3d.exe)
4 75F20419 BaseThreadInitThunk (KERNEL32.DLL)
5 779C662D RtlGetAppContainerNamedObjectPath (ntdll.dll)
6 779C65FD RtiGetAppContainerNamedObjectPath (ntdll.dll)
```

Relevant console output lines:

```
Error: HPB_bot - Error determining MOD directory name!
Error: HPB_bot - MOD dll not found (or unsupported MOD)!
```

Dunno why it's called HPB Bot under the hood, but to stress it again: works on vanilla engine.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/1f5c97964b87c08a29e41513d05fd4198b22258c

Thanks for the report!

**Comment by a1batross** [comment]
As it turned out, Half-Life after 1.1.1.1 doesn't actually return full path in this function. Some newer mods rely on this behavior, like Sandbot.

The old behavior can now be enabled with `-bugcomp get_game_dir_full` command line flag.
