### ISSUE TITLE
Multiplayer "Assertion failed" problem

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#190]
Joining a multiplayer game in Xash3d deploy will sometimes result in an error with the title "Assertion failed". Then it will be mentioned the location of Xash's folder and "Line: 264".
> Expression: IsValidIndex(i)
> For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.

Then you will be given 3 options: Abort, Retry, Ignore
Pressing "Abort" will result in a crash of Xash. "Ignore" will send the user back to the main menu and "Retry" option will make a new window with a Sys Crash error, then the engine will crash.

**Comment by nekonomicon** [comment]
Can you attach screenshot with error message and backtrace?

**Comment by mewS1xN1n3** [comment]
> Can you attach screenshot with error message and backtrace?
Assertion failed!: https://cdn.discordapp.com/attachments/543711693298204674/730123759448490174/X20Problem1.PNG
Sys Crash: https://cdn.discordapp.com/attachments/543711693298204674/730123782177685574/X20Problem2.PNG

**Comment by a1batross** [comment]
Doesn't reproduce for me anymore.
