### ISSUE TITLE
Why kick my

### ISSUE THREAD

**Issue by Skye450** [FWGS/xash3d-fwgs#1906]
![Screenshot_2024-12-01-14-04-28-170_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/4c1357ad-b98e-4dbf-b578-e451a33e322f)

**Comment by a1batross** [comment]
Server IP address?

Record a demo and send here.

**Comment by Soyundesconocido** [comment]
Yo puse estos comandos en la consola y lo solucione

cl_nodelta 1
net_chokeloop 1

**Comment by a1batross** [comment]
>cl_nodelta 1

Do not recommend harmful things.

пн, 9 дек. 2024 г., 01:06 Soyundesconocido ***@***.***>:

**Comment by Skye450** [comment]
> ![Screenshot_2024-12-01-14-04-28-170_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/4c1357ad-b98e-4dbf-b578-e451a33e322f)
> 
> 

Please fix it it has something to do with internet I tried it

**Comment by a1batross** [comment]
`svc_pings` issue was fixed by 48cc526c7e56

**Comment by Skye450** [comment]
Big thanks 👍
