### ISSUE TITLE
Movement issue in multiplayer

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#191]
While playing Xash3D 0.20 multiplayer on servers with players that use the older version, you will encounter many issues with  the movement of the players and the movement of yourself, such as teleporting, walking through the walls and others. Other users with the older version of Xash on servers will see u just as normal. I tested this from multiple devices and tried to change different settings but that didn't work. Even when you spectate another player you will see his movement "laggy".

https://cdn.discordapp.com/attachments/471642404764778507/730125716812726282/2020-07-07_21-18-08.mkv 
In this video everything seems almost normal but sometimes the other players are spinning and moving in a direction at the same time.

**Comment by mewS1xN1n3** [comment]
Difference between 0.19 and 0.20: https://www.youtube.com/watch?v=9ixisuzK1Aw

**Comment by mittorn** [comment]
disable cl_nopred

**Comment by a1batross** [comment]
Yes, enable predicting by `cl_nopred 0`
