### ISSUE TITLE
Android builds are broken

### ISSUE THREAD

**Issue by Srandista** [FWGS/xash3d-fwgs#1910]
Android builds are broken for couple of days. After quick testing, it seems, that one of these two commits is likely culprit: 

https://github.com/FWGS/xash3d-fwgs/commit/4798cd6d1e90e4e83717ad186430044ea479ac56
https://github.com/FWGS/xash3d-fwgs/commit/1f5c97964b87c08a29e41513d05fd4198b22258c

Other systems (at least Windows and Linux) aren't affected, even after that massive Ogg/Opus PR. Android build from 28.11. work just fine.

![Screenshot_20241202-103006](https://github.com/user-attachments/assets/f9911525-6ccd-424c-a091-a8f75f522f41)

**Comment by a1batross** [comment]
Doesn't happen to me. What's your Android version?

**Comment by a1batross** [comment]
Oh, it does. Judging by logcat, it's -fstack-protector. Interesting, what could've even caused it?
