### ISSUE TITLE
Звуки из sentences.txt могут играть только wav

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#1911]
Т.к. Xash поддерживает (помимо wav) mp3, ogg и opus, хотелось бы сконвертировать сентенсы в их форматы.
Столкнулся с проблемой, что сентенсы не играются, т.к. "файл не найден".
Проблема, вероятно, здесь - https://github.com/FWGS/xash3d-fwgs/blob/614b9113ad34b3bc9bc87de3cdb8b1914c0633ef/engine/client/s_vox.c#L503

**Comment by a1batross** [comment]
Если убрать .wav отсюда, то он будет грузить, то что найдёт. К сожалению указывать расширение в файле sentences нельзя, потому что точка там это спецсимвол.

**Comment by Aynekko** [comment]
> Если убрать .wav отсюда, то он будет грузить, то что найдёт. К сожалению указывать расширение в файле sentences нельзя, потому что точка там это спецсимвол.

Да, в этом я уже убедился :D

**Comment by a1batross** [comment]
Исправил в https://github.com/FWGS/xash3d-fwgs/commit/f5d635b67bb00ba6ba90b0f026bee9630e7fd043.

Только учти, что теперь он ищет перебором. Сначала будет искать wav, потому что он имеет приоритет выше, потом mp3 и последними ogg и opus.
