### ISSUE TITLE
Why kick my 



### ISSUE THREAD

**Issue by Skye450** [FWGS/xash3d-fwgs#1914]
I play and suddenly get kicked out I don't know why![Screenshot_2024-12-08-18-15-32-683_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/080004ab-ff74-4ee0-8357-7435143b4df9)

**Comment by a1batross** [comment]
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/1906

**Comment by Skye450** [comment]
how I didn't understand The problem is only in this server

**Comment by Skye450** [comment]
This 46.174.55.60:27015

**Comment by Skye450** [comment]
![Screenshot_2024-12-08-20-54-54-483_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/d9338496-be05-4fc8-a42f-fa9f7c0cb25d)

**Comment by Skye450** [comment]
> Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/1906

All servers have the same problem kick
