### ISSUE TITLE
Small Credit/Title Fonts using HL25

### ISSUE THREAD

**Issue by lafleur560** [FWGS/xash3d-fwgs#1920]
The UI scales properly but the fonts for the chapter titles are tiny in 2k and 4k resolutions. Changing the fonts size in TrackerScheme.res in valve folder doesn’t do anything.

**Comment by a1batross** [comment]
TrackerScheme.res isn't used by us, instead the HUD font used is a legacy bitmap font that present in game files located in `gfx.wad`.

As a stop gap, before we drop using all these bitmap fonts, there is a way to scale it using `hud_fontscale` console variable.

**Comment by a1batross** [comment]
Keep in mind, changing `hud_fontscale` require game restart.

For now, I'm closing this, as the proper scaling is part of the whole text rendering overhaul project, that I just didn't have enough time to work on yet.

**Comment by lafleur560** [comment]
Thanks it worked great.
