### ISSUE TITLE
[MOD: Cry of Fear] Any ways to quit the game will cause crash-on-exit or freeze (?), happened similar to #545

### ISSUE THREAD

**Issue by TheKingFireS** [FWGS/xash3d-fwgs#1927]
Any ways to quit the game including console's `exit`, console's `quit`, c_game_menu1.bsp's quit button, Xash3D-FWGS's quit button and System's close button.
Press quit button will cause making program have white fade, unresponsive, no way to back to responsive, happened similar to #545 but CoF doesn't use fmod.dll.

I also noticed that last line not included in engine.log.
`ended irrKlang update thread`

Engine logs:
filtered (removed all spammy OpenGL errors):
[engine-filtered.log](https://github.com/user-attachments/files/18219594/engine-filtered.log)

unfiltered: 
[engine.log](https://github.com/user-attachments/files/18219593/engine.log)

Info:
Patch version: 1.55 (1.2 and 1.0 untested)
Xash3D-FWGS: https://github.com/FWGS/xash3d-fwgs/commit/e751092555975c7ec3a65e1da1144ca6a4e6a1b1
OS: Windows 10 x86_64bit
GPU: GTX 1650
Custom renderer: Enabled
Map: Any

**Comment by a1batross** [comment]
Must be fixed in https://github.com/FWGS/xash3d-fwgs/commit/687c9b004f4477d7e325bf138e16c097f0b60f85

**Comment by TheKingFireS** [comment]
Confirmed, It is fixed.
