### ISSUE TITLE
I can't play multiplayer

### ISSUE THREAD

**Issue by 21Shephard** [FWGS/xash3d-fwgs#1928]
When I open Lan server, the game freezing

https://github.com/user-attachments/assets/04b0315d-21de-4b8c-bf6c-6da8dde0f3de

**Comment by a1batross** [comment]
Post an engine.log, rather than the video.

It makes no sense to record the video in such low resolution (because the recorder scaled it down to fit the screen) anyway.

**Comment by 21Shephard** [comment]
> Post an engine.log instead of than the video.
> 
> It makes no sense to record the video in such low resolution (because the recorder scaled it down to fit the screen) anyway.

[engine.log](https://github.com/user-attachments/files/18222041/engine.log)

**Comment by 21Shephard** [comment]
I downloaded latest build and that fixed.
