### ISSUE TITLE
android build problem

### ISSUE THREAD

**Issue by qq430950189** [FWGS/xash3d-fwgs#1930]
ld.lld: error: undefined symbol: vtable for __cxxabiv1::__class_type_info
>>> referenced by VFileSystem009.cpp
>>>               filesystem/VFileSystem009.cpp.2.o:(typeinfo for IBaseInterface)
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)

ld.lld: error: undefined symbol: vtable for __cxxabiv1::__si_class_type_info
>>> referenced by VFileSystem009.cpp
>>>               filesystem/VFileSystem009.cpp.2.o:(typeinfo for IFileSystem)
>>> referenced by VFileSystem009.cpp
>>>               filesystem/VFileSystem009.cpp.2.o:(typeinfo for CXashFS)
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
maybe a stuff of my mistake,but i don't know how to resolve it.

**Comment by qq430950189** [comment]
I am a new and not familiar with the use of Android NDK, C/C++, and also the WAR build program. As a result, I made a build error,but I don't know where to make the changes. i know this is a Waf-related question and i should do it myself, but I appreciate that someone can help me.

**Comment by qq430950189** [comment]
there are some likely slutions(I don't know where to make the modifications or which is effective for this）
add -lstdc++
add -fno-rtti
add LOCAL_ALLOW_UNDEFINED_SYMBOLS := true in a android.mk file

**Comment by qq430950189** [comment]
If your CPU is NOT x86 compatible or you decided build 64-bit version of engine, you may want to compile [Half-Life SDK](https://github.com/FWGS/hlsdk-portable). This repository contains our fork of HLSDK and restored source code for Half-Life expansions and some mods.
because this?

**Comment by a1batross** [comment]
Why did you start from probably the most complex port out there if you think you don't have enough experience?

Maybe make a simple mod on PC first?

**Comment by qq430950189** [comment]
ok thank you,you are right.
