### ISSUE TITLE
[MOD: Brutal Half-Life v3] Constant hang-outs at exiting a game

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#1935]
Приложение зависает при любой попытке выхода. Неважно, была начата сама игра или, нет. Зависает даже после запуска меню и попытке выйти. Включая зависание при выходе из игры по горячей клавише (если карта уже запущена).

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/687c9b004f4477d7e325bf138e16c097f0b60f85#diff-a2902df09023dd04e947df04dbcc8a440aee79a09c808ff478c30bf793cf1005R104
