### ISSUE TITLE
Cannot open shared object file...

### ISSUE THREAD

**Issue by spoiler-github** [FWGS/xash3d-fwgs#194]
Can't start game on ARM. Downloaded valve folder from linux steam version (x86) and put into Xash3d folder. Start game button is gray and I can't start game from menu. What I do wrong? Screenshot: https://imgur.com/a/LLYzQ4s

**Comment by nekonomicon** [comment]
You need to compile client and server libraries from FWGS/hlsdk-xash3d repository.

**Comment by a1batross** [comment]
Updated README with explanation of this issue.
