### ISSUE TITLE
why no custom resolution in android :"(

### ISSUE THREAD

**Issue by Elixir7z** [FWGS/xash3d-fwgs#1942]
they should include custom resolutions, literally you can't see almost anything of the chat in the default resolution that comes XDDDDDD or at least me xd, just look at the screenshot, for us custom resolutions are not for having skill or something like that xddd but it is more for comfort when executing commands or writing in the chat 

![Screenshot_20241230_222421_Xash3D FWGS (Test)](https://github.com/user-attachments/assets/d8b89a78-896b-43ac-aee7-ca47243d6dee)

![Screenshot_20241230_230329_Xash3D FWGS (Test)](https://github.com/user-attachments/assets/21eae416-f616-4910-86b7-62029349e559)

**Comment by a1batross** [comment]
Won't fix.
