### ISSUE TITLE
Console in Xash3D deploy

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#195]
The console won't show up in Xash3D Deploy. I tried creating a shortcut and add to target, in properties, -console but still nothing.

**Comment by nekonomicon** [comment]
xash3d-deploy - name of repository.
You need to write platform and version.

**Comment by mewS1xN1n3** [comment]
V49/0.20(Android-armv7l build 1923)

**Comment by Velaron** [comment]
@mewS1xN1n3 "-dev 1" works for now

**Comment by mewS1xN1n3** [comment]
> @mewS1xN1n3 "-dev 1" works for now

Good it's working
