### ISSUE TITLE
New game on 0.20

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#198]
Starting a new game on Xash3D 0.20 will cause the screen to be white for 7-8 seconds

**Comment by nekonomicon** [comment]
Which platform?

**Comment by Vladislav4KZ** [comment]
It looks like you are missing a file cached.wad

**Comment by mewS1xN1n3** [comment]
> Which platform?

Both mobile and computer

**Comment by a1batross** [comment]
@mewS1xN1n3 Make sure you have all game data.

You didn't even posted log files. They are generated with "-dev 2 -log" passed to Xash3D in command line.
It's not worth discussing it, unless you post them.

**Comment by mewS1xN1n3** [comment]
> @mewS1xN1n3 Make sure you have all game data.
> 
> You didn't even posted log files. They are generated with "-dev 2 -log" passed to Xash3D in command line.
> It's not worth discussing it, unless you post them. 

I wrote -dev 2 -log in the command line, there was no difference but I observed that the game acts normal when I look up during the intro ( the white screen )

**Comment by mewS1xN1n3** [comment]
> It looks like you are missing a file cached.wad

I have the file

**Comment by a1batross** [comment]
>I wrote -dev 2 -log in the command line, there was no difference but I observed that the game acts normal when I look up during the intro ( the white screen )

Post. The. Log. File.

Or I am going to close that issue.

**Comment by mewS1xN1n3** [comment]
Carp I cannot find the log
