### ISSUE TITLE
Opposing Force not loading correctly.

### ISSUE THREAD

**Issue by jumper-cable-morty** [FWGS/xash3d-fwgs#199]
I was trying to load up Opposing Force, but whenever I click boot camp or new game, it gives me two errors, SV_LoadProgs: couldn't get entity API, and can't initialize opfor.dll.
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/4982940/engine.log)
I'm using Windows 7 x64, and I'm using the 0.20 release of xash3d-fwgs.

**Comment by a1batross** [comment]
Where did you get that Opposing Force build? 
You **must** download it from Steam.

**Comment by jumper-cable-morty** [comment]
Oh, I got the WON version I think. I'll use the steam version then.

**Comment by a1batross** [comment]
Yeah, WON is not supported unfortunately. :(

**Comment by a1batross** [comment]
@jumper-cable-morty if everything will be fine, close this issue please.
