### ISSUE TITLE
[MOD: Team Fortress Classic] Сломаны текстуры игроков

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#200]
На новом движке неправильно обновляется модель после данного куска кода:
```C++
g_engfuncs.pfnSetModel(pev, "models/player/scout/scout.mdl"); // <- здесь всегда scout.mdl
g_engfuncs.pfnSetClientKeyValue(ENTINDEX(ENT(PEV)), "model", "models/player/sniper/sniper.mdl"); // <- в этой строке модель зависит от класса игрока
```

В итоге с любой моделью используются текстуры от scout.mdl:
![image](https://user-images.githubusercontent.com/53096779/88653161-62f3a400-d0d4-11ea-9019-cdb0b1679863.png)

**Comment by Vladislav4KZ** [comment]
By the way, I noticed the same in Sven Coop 3.0
