### ISSUE TITLE
Xashbox

### ISSUE THREAD

**Issue by mewS1xN1n3** [FWGS/xash3d-fwgs#201]
Launching Xashbox in 0.20 will cause all the buttons to disappear (I tried enabling them from the console, it didn't work)

**Comment by mittorn** [comment]
Xashbox is depended on scripting which was not added to 0.20. Also enttools only supported in ggm now, they are not merged to new engine. And i will remove some useless enttools command used by xashbox, so some featires will never work (until someone update xashbox).
There maybe some bugs in touch, breaking xashbox and i'll check it later

**Comment by mittorn** [comment]
#193
