### ISSUE TITLE
Host_InitError: Can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jane-Kopke** [FWGS/xash3d-fwgs#203]
This issue i'm having is driving me crazy, and i don't understand why this is happening because i wrote the path to the valve folder in the conf file, i even double checked but it's still not launching the engine.
I'm running Arch Linux and i installed it from the package on AUR.

**Comment by Velaron** [comment]
you still need to copy vgui.so from the original installation

**Comment by Jane-Kopke** [comment]
Now when i launch it i get this error message 


`Ver: Xash3D FWGS 0.20 (build 1950-065811c, linux-i386)
Crash: signal 11 errno 0 with code 1 at (nil) (nil)
Ver: Xash3D FWGS 0.20 (build 1950-065811c, linux-i386)
Crash: signal 11 errno 0 with code 1 at (nil) (nil)
Stack backtrace:
Stack backtrace:
 1: 0xe705a20d <_ZN4vgui9TextImage7getFontEv+29> (/usr/lib/xash3d/vgui.so)
 1: 0xe705a20d <_ZN4vgui9TextImage7getFontEv+29> (/usr/lib/xash3d/vgui.so)
 2: (nil)
 2: (nil)
 3: 0xe704abc0 <_ZN4vgui5Image6getPosERiS1_+0> (/usr/lib/xash3d/vgui.so)
 3: 0xe704abc0 <_ZN4vgui5Image6getPosERiS1_+0> (/usr/lib/xash3d/vgui.so)
Stack dump:
Stack dump:
 0: 0x30
 0: 0x30
 1: 0x1
 1: 0x1
 2: 0xbfe0aaed (valve/cl_dlls/client.so)
 2: 0xbfe0aaed (valve/cl_dlls/client.so)
 3: 0xe705b107 <_ZN4vgui11vgui_strcpyEPciPKc+39> (/usr/lib/xash3d/vgui.so)
 3: 0xe705b107 <_ZN4vgui11vgui_strcpyEPciPKc+39> (/usr/lib/xash3d/vgui.so)
 4: 0xbfe0aaed (valve/cl_dlls/client.so)
 4: 0xbfe0aaed (valve/cl_dlls/client.so)
 5: 0x1
 5: 0x1
 6: 0x57c362a0
 6: 0x57c362a0
 7: 0xe7059d46 <_ZN4vgui9TextImage11getTextSizeERiS1_+54> (/usr/lib/xash3d/vgui.so)
 7: 0xe7059d46 <_ZN4vgui9TextImage11getTextSizeERiS1_+54> (/usr/lib/xash3d/vgui.so)
 8: 0x57c362a0
 8: 0x57c362a0
 9: 0x5b
 9: 0x5b
10: 0x5790f82c
10: 0x5790f82c
11: 0x57c362a0
11: 0x57c362a0
12: 0x57c362a0
12: 0x57c362a0
13: 0x1
13: 0x1
14: 0x1
14: 0x1
15: 0xe705a197 <_ZN4vgui9TextImage7setTextEiPKc+71> (/usr/lib/xash3d/vgui.so)
15: 0xe705a197 <_ZN4vgui9TextImage7setTextEiPKc+71> (/usr/lib/xash3d/vgui.so)
16: 0x57c362a0
16: 0x57c362a0
17: 0xfff8d5d8
17: 0xfff8d5d8
18: 0xfff8d5dc
18: 0xfff8d5dc
19: 0xe704b029 <_ZN4vgui5ImageC1Ev+105> (/usr/lib/xash3d/vgui.so)
19: 0xe704b029 <_ZN4vgui5ImageC1Ev+105> (/usr/lib/xash3d/vgui.so)
20: 0xfff8d5f4
20: 0xfff8d5f4
21: 0xff
21: 0xff
22: (nil)
22: (nil)
23: (nil)
23: (nil)
24: (nil)
24: (nil)
25: 0x57c362a0
25: 0x57c362a0
26: 0xbfe0aaed (valve/cl_dlls/client.so)
26: 0xbfe0aaed (valve/cl_dlls/client.so)
27: 0xe705a13c <_ZN4vgui9TextImage7setTextEPKc+44> (/usr/lib/xash3d/vgui.so)
27: 0xe705a13c <_ZN4vgui9TextImage7setTextEPKc+44> (/usr/lib/xash3d/vgui.so)
28: 0x57c362a0
28: 0x57c362a0
29: 0x1
29: 0x1
30: 0xbfe0aaed (valve/cl_dlls/client.so)
30: 0xbfe0aaed (valve/cl_dlls/client.so)
31: (nil)
31: (nil)
`

**Comment by Jane-Kopke** [comment]
i fixed it nevermind, turns out that the AUR package is terribly out of date and broken, you guys need to update the AUR package

**Comment by a1batross** [comment]
@Jane-Kopke We don't support Arch, it's third-party package, instead it's better to use our AppImage. 


I just realized we have this in README. Damn.
