### ISSUE TITLE
Full Working Gamepad

### ISSUE THREAD

**Issue by doster88** [FWGS/xash3d-fwgs#209]
I want Xash3d to be full compatible with different gamepads. I have a Terios T3 gamepad and only thing that somehow worked is Right stick look that working only by X axis.

**Comment by a1batross** [comment]
Then implement it by yourself.

**Comment by glebm** [comment]
If the gamepad is supported by SDL2 gamecontrollerdb, the last remaining PR is https://github.com/FWGS/xash3d-fwgs/pull/275

**Comment by lewa-j** [comment]
@glebm Not every platform uses SDL backend.

**Comment by glebm** [comment]
Right, I've only fixed the case where the backend uses SDL2 + the new GameController API

Some issues were fixed in other backends as well (but only incidentally) and sensible default mappings were added

**Comment by glebm** [comment]
@doster88 SDL2 GameController fixes have been merged, you can try again now

**Comment by a1batross** [comment]
GameController API highly depends on database. :( 

But at least you can configure them from Steam or some standalone utility, outside of engine.

**Comment by glebm** [comment]
Also note that the D-Pad won't work in the menu until https://github.com/FWGS/mainui_cpp/pull/40 is merged (and then the `mainui` submodule is bumped here)
