### ISSUE TITLE
Enhancement request: Make GAME_PATH a waf option

### ISSUE THREAD

**Issue by eprokhor-quest** [FWGS/xash3d-fwgs#21]
**game_launch/game.cpp** defines this:
`#define GAME_PATH "valve" // default dir to start from`
Can you make this a **waf configure** option so that users can build custom game launchers without editing the sources?

**Comment by a1batross** [comment]
Yes, it may be useful, but...
1) If you're developing a game, you don't need to modify engine, just copy game_launch to your SDK tree and add to your buildsystem.
2) If you're engine developer, you free to do it in your own fork.

Also, don't forget, that Xash3D FWGS launcher and original engine launcher are incompatible.

**Comment by a1batross** [comment]
Closing due to absence of issue OP.
