### ISSUE TITLE
Implement pointer capture api android 8.0 and up

### ISSUE THREAD

**Issue by abasgames** [FWGS/xash3d-fwgs#218]
This well allow android oreo and up users to use their mouse to play xash-fwgs as they do in pc

https://developer.android.com/training/gestures/movement#pointer-capture

**Comment by a1batross** [comment]
We have this implemented partially through Android extensions by NVidia.

As far as I know, they should be available from 7.0 and higher.

**Comment by mittorn** [comment]
Pointer capture API for 8+ will allow to hide pointer, 7.x method cannot do this

**Comment by abasgames** [comment]
Yes it can you must uncheck hide mouse option in configuration

**Comment by abasgames** [comment]
> Pointer capture API for 8+ will allow to hide pointer, 7.x method cannot do this

![USER_SCOPED_TEMP_DATA_orca-image--1444901011](https://user-images.githubusercontent.com/45899491/92300684-79a7d900-ef65-11ea-9af5-d5826e7cae70.jpeg)

**Comment by mittorn** [comment]
Does not work for me, pointer still shown on 3 different devices. And it unuseful without immersive mode
