### ISSUE TITLE
Black bar doesn't go off

### ISSUE THREAD

**Issue by Adnan1091** [FWGS/xash3d-fwgs#223]
The black bar of android which has 3 buttons doesn't go off in the latest build of xash3dARM64

**Comment by mittorn** [comment]
I'll recheck that, it seems last refactoring of android project break immersive mode

**Comment by Fancy2209** [comment]
Any updates on this?

**Comment by Vladislav4KZ** [comment]
Fixed in new launcher by Velaron
https://play.google.com/store/apps/details?id=su.xash.engine
