### ISSUE TITLE
Change android:targetSdkVersion="28 to android:targetSdkVersion="29

### ISSUE THREAD

**Issue by abasgames** [FWGS/xash3d-fwgs#224]

**Comment by a1batross** [comment]
Is there any reason to do except Google bullshittery? I try to not increase API target as it usually means changed behaviour, while we certanly don't need more than 1k lines of Java to fire up engine.

We previously had API level like 16 or 17 and even with the same code, some things had broken after upgrading.

**Comment by mittorn** [comment]
Only need it if google makes it mandatory for GP. I stil use 9 for my local builds except i testing high api level behaviour
