### ISSUE TITLE
Engine couldn't load maps from archives

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#226]
1. When I type `map <mapname>` in the console I see:
```
[14:04:32] >\map c0a0
[14:04:32] Error: map c0a0 doesn't exist
```

2. When I try to load saves I see:
http://ipic.su/7yNct6

3. When I try to start new game It's possible to load map from zip-archive, but impossible from pack.

**Comment by a1batross** [comment]
Seems to be working now?

**Comment by Vladislav4KZ** [comment]
@a1batross No it still doesn't work. I literally ran into this bug the day before yesterday.

**Comment by a1batross** [comment]
Well, I can load any maps from ZIP. Saves are working.

**Comment by Vladislav4KZ** [comment]
> Well, I can load any maps from ZIP. Saves are working.

Did you at least delete the maps from the game folder before zipping them?
At least this bug is reproduced on Windows, I have not tested it on Android yet

**Comment by Vladislav4KZ** [comment]
This bug also reproduces on Android.
Did you use ZIP with or without compression?

**Comment by Vladislav4KZ** [comment]
Maps are loaded successfully only from ZIP archive without compression

**Comment by a1batross** [comment]
Yes, without.

Loading ZIPs with compression is useless, because to read any file it has to be loaded in memory and decompressed.

**Comment by a1batross** [comment]
Most file types, like sounds, text files or models can be loaded from compressed ZIPs.

Other types like maps, wads or saves aren't planned to be supported due to how FS_Open works right now.
