### ISSUE TITLE
SPR_DrawHoles and broken alpha in Night at the Office

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#227]
Night at the Office uses SPR_DrawHoles function to draw sprites, but under new engine it has black alpha:
http://ipic.su/7yNcwh
http://ipic.su/7yNcwj

**Comment by a1batross** [comment]
Probably an issue after renderdll split. No one tested that.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/ef786b7d799cf8ca3d4dddeccb4b2787fd8af2ec
