### ISSUE TITLE
[Android] Back button cause engine to shutdown

### ISSUE THREAD

**Issue by Google61** [FWGS/xash3d-fwgs#228]
Instead should open pause, isn't it?
Android Pie, if matters

**Comment by Vladislav4KZ** [comment]
It has been fixed for a long time. I don't know the commit, but the latest version doesn't have such a bug.

**Comment by a1batross** [comment]
Finally.

**Comment by Vladislav4KZ** [comment]
Retest this on Xash3D FWGS 0.21 from Google Play Store.

I can't do it myself because I didn't have this issue on both the old 0.20.1 beta Continuous build from GitHub and the new 0.21 beta version of the engine from Play Store.

**Comment by a1batross** [comment]
Doesn't happen on new port anymore.
