### ISSUE TITLE
Keypress repeat does not work

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d-fwgs#23]
Long-pressing arrow keys does not repeating field cursor movement

**Comment by a1batross** [comment]
It's because there is a really dumb check for repeat allowed keys. =/
I even don't know why it should be here.

**Comment by mittorn** [comment]
how to move cursor without it?

**Comment by a1batross** [comment]
Fixed by #8770bdc69426a9fc03998a92498a85bb2f64db81
