### ISSUE TITLE
Game config settings don't save

### ISSUE THREAD

**Issue by polaris911** [FWGS/xash3d-fwgs#233]
On Xash3D FWGS on the Retroid Pocket 2. 
Control settings and touch input settings reset to defaults every time you open the app.

**Comment by a1batross** [comment]
I guess it's an Android based console, so you're just using normal Android builds?

What version do you use?

**Comment by Vladislav4KZ** [comment]
You need to exit the game through the "Quit" button in the main menu, then all settings will be saved.
