### ISSUE TITLE
Can't Initialize on Windows

### ISSUE THREAD

**Issue by vus7294** [FWGS/xash3d-fwgs#245]
Host_InitError: can't initialize
/data/data/in.celest.xash3d.hl/lib/client.dll:

i just uncompressed binary and put valve, bshift, gearbox folder in root of xash3d.exe
what is wrong with my setting?

**Comment by lewa-j** [comment]
You have to get valve folder from steam.

**Comment by vus7294** [comment]
include hl.exe in root folder?

**Comment by lewa-j** [comment]
No. The problem is gameinfo.txt

**Comment by a1batross** [comment]
>/data/data/in.celest.xash3d.hl/lib/client.dll:

>/data/data/in.celest.xash3d.hl

>client.dll

WHAT

**Comment by vus7294** [comment]
it seems fixed for delete 3 folder and put valve folder that directly installed from steam but seems have much problems and bugs

**Comment by a1batross** [comment]
So it can be closed now?
