### ISSUE TITLE
bug: gles-only platforms uses soft renderer by default

### ISSUE THREAD

**Issue by glebm** [FWGS/xash3d-fwgs#247]
Currently, on a platform with only gles (and no gl) the game always use `soft` renderer by default due to a startup logic issue.

Though the code makes [some effort](https://github.com/FWGS/xash3d-fwgs/blob/7b127c23f5d078c0f538aba732caaf978435d8f3/engine/client/ref_common.c#L586) to check which renderer `so` are available at startup, it always tries  `DEFAULT_ACCELERATED_RENDERER` first and falls back to software rendering if that fails:

https://github.com/FWGS/xash3d-fwgs/blob/7b127c23f5d078c0f538aba732caaf978435d8f3/engine/client/ref_common.c#L672-L684

`DEFAULT_ACCELERATED_RENDERER` is hard-coded to `gl`:

https://github.com/FWGS/xash3d-fwgs/blob/7b127c23f5d078c0f538aba732caaf978435d8f3/common/defaults.h#L195-L201

The default accelerated renderer should probably be set to the first available one if `DEFAULT_ACCELERATED_RENDERER` is not available.

**Comment by mittorn** [comment]
Maybe need add selection of DEFAULT_ACCELERATED_RENDERER from build system when GL is disabled?

**Comment by mittorn** [comment]
https://github.com/batocera-linux/batocera.linux/pull/2703
Fallback is broken here

**Comment by glebm** [comment]
While I don't know what the best solution is, it may be best to both set `DEFAULT_ACCELERATED_RENDERER` from waf and also check if the `DEFAULT_ACCELERATED_RENDERER` is available and fallback to the first available one if not

**Comment by glebm** [comment]
Fix verified
