### ISSUE TITLE
gl4es: close_gl4es is never called

### ISSUE THREAD

**Issue by glebm** [FWGS/xash3d-fwgs#258]
https://github.com/ptitSeb/gl4es/commit/221fa1e67a80e89fa431fa1a92aa6a25f6085aab fixes crash on startup but introduces another issue that should be fixed in this repo:

From https://github.com/FWGS/xash3d-fwgs/pull/255#issuecomment-751898551

@lewa-j:
> Now the close_gl4es should be called somewhere. I think in the GL_ClearExtensions or the R_Shutdown. @mittorn

@glebm:
> @lewa-j But we should only call it if we ever called init (which doesn't happen if we didn't create a gl context)

@lewa-j:
> R_Shutdown shouldn't be called if context creation failed.

**Comment by mittorn** [comment]
So we need add export for gl4es_close to gl4es api (if still not present) and document it first
https://github.com/ptitSeb/gl4es/blob/master/include/gl4esinit.h

**Comment by glebm** [comment]
Exported in https://github.com/ptitSeb/gl4es/pull/271
