### ISSUE TITLE
Set EGL_LIB

### ISSUE THREAD

**Issue by glebm** [FWGS/xash3d-fwgs#259]
`EGL_LIB` is set to `NULL` here. Should it be a build option?

https://github.com/FWGS/xash3d-fwgs/blob/7f989987654e8aac35c49761f28e93782f5d555b/engine/platform/sdl/vid_sdl.c#L956-L958

**Comment by glebm** [comment]
Looks like this can be set via `SDL_VIDEO_EGL_DRIVER` anyway, nevermind

**Comment by mittorn** [comment]
It is only left here for specific device ports and seems not used anymore
