### ISSUE TITLE
xash.dll not found

### ISSUE THREAD

**Issue by PowerX-NF** [FWGS/xash3d-fwgs#276]
i just built xash3d-fwgs without errors but when i try to run the game i get xash.dll not found
i added xash.dll and added it beside it

i tried changing xash.dll to engine.dll but this didn't work either

i tried both xash.dll and renaming it to engine.dll but didn't work

**Comment by lewa-j** [comment]
Show your working directory and how exactly you launch it.

**Comment by PowerX-NF** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/43983075/103490830-37b17580-4e27-11eb-89bb-99bcc69bacce.png)

when i run the game i get this error

![Screenshot (12)](https://user-images.githubusercontent.com/43983075/103490899-9c6cd000-4e27-11eb-938b-c06e4bfb0877.png)

**Comment by lewa-j** [comment]
You need SDL2

**Comment by PowerX-NF** [comment]
i have sdl2

**Comment by PowerX-NF** [comment]
i have sdl2 for  vc++

**Comment by PowerX-NF** [comment]
i downloaded sdl2 and got this error

![Screenshot (13)](https://user-images.githubusercontent.com/43983075/103492044-0473e400-4e31-11eb-934d-135855b372ba.png)

**Comment by lewa-j** [comment]
One issue per issue please. I consider this one solved.

**Comment by PowerX-NF** [comment]
yeah sdl2 problem is solved
