### ISSUE TITLE
no option to run in a window

### ISSUE THREAD

**Issue by arceuss** [FWGS/xash3d-fwgs#283]
im using the latest testing build
![image](https://user-images.githubusercontent.com/28229451/103718721-abb56000-4f84-11eb-9662-4262b23a1166.png)
theres no way for me to enable it

**Comment by arceuss** [comment]
and i actually cant change most things
examples are renderer and everything in video options

**Comment by lewa-j** [comment]
First of all, you forgot extras.pak thus the menu looks wrong.
https://github.com/FWGS/xash-extras/releases

**Comment by a1batross** [comment]
Works for me, on all platforms (that have window management)
