### ISSUE TITLE
No text for env_message

### ISSUE THREAD

**Issue by nemyax** [FWGS/xash3d-fwgs#29]
In my standalone mod based on XashXT 0.81, the main asset directory is **base**, and localised assets are in **mw_en** (for English) and **mw_ru** (for Russian). In **base/gameinfo.txt**, gamedir is set to "mw_en".
Both **mw_en** and **mw_ru** contain a **titles.txt** file, and there is no **titles.txt** in **base**.
When I launch the game without the **-game** parameter, **env_message** entities don't show any text. However, when I launch it with **-game mw_ru**, the messages work fine.
With the original Xash3D, they work as expected in both cases.

**Comment by a1batross** [comment]
gamedir parameter in gameinfo.txt is deprecated. Probably, it was removed not fully.

**Comment by nemyax** [comment]
What's the alternative?

**Comment by a1batross** [comment]
Nothing. It was done by Unkle Mike when he tried to make filesystem hierarchy, where executables and gamedir can be placed in different folders.

So gamedir parameter is set automatically by real gamedir name.
