### ISSUE TITLE
AMXX 1.9 and AMXX 1.10 not working

### ISSUE THREAD

**Issue by CaNNiC2** [FWGS/xash3d-fwgs#290]
Hello guys , 
So i tried using **AMXX 1.9** and **1.10** versions in Xash3D FWGS server on Ubuntu (Linux)  , but its not working 
But with **AMXX 1.8.2** it works perfectly 
Could there be anyway to make **1.9**/**1.10** work with xash3d because i need it to run some plugins that won't work with **1.8.2** version

And yes for metamod im using [Metamod-p 1.21p37 Custom Build for Xash3D by mittorn and Solexid](https://www.moddb.com/engines/xash3d-fwgs-engine/downloads/metamod-p-121p37-custom-build-for-xash3d)
Here's error log 
```cpp
[2020:12:20|15:25:25] L 12/20/2020 - 15:25:25: Error parsing gameconfig file "cstrike/addons/amxmodx/data/gamedata/common.games.txt":
[2020:12:20|15:25:25] L 12/20/2020 - 15:25:25: Error 1 on line 0, col 0: Stream failed to open
[2020:12:20|15:25:25] L 12/20/2020 - 15:25:25: Could not read common.games gamedata: File could not be opened: unknown
```

**Comment by a1batross** [comment]
I need to publish my patches I did for AMXXOnAndroid because there is some fixes to make it possible to run with Xash3D FWGS.

**Comment by CaNNiC2** [comment]
No No not for Android!!
I mean on Ubuntu (Linux) , and i mean AMX Mod X 1.8.2 works perfectly but 1.9 and 1.10 versions arent working
So how to fix it , how to make AMXX version 1.9 or 1.10 work with Xash3D FWGS in Linux

**Comment by nekonomicon** [comment]
@CaNNiC2 you didn't understand.
He mean patches to improve amxx support for any platform.

**Comment by a1batross** [comment]
I hope I didn't lose the sources...

**Comment by CaNNiC2** [comment]
OK !! I hope you release the patches for linux asap because i need to move to AMXX 1.9 cause like i said some plugins i need arent working in AMXX 1.8.2

**Comment by Severin228** [comment]
Hello Friend. Have you found a backup of AMXX 1.9.0? I want to switch to 1.9.0 as soon as possible.
Another question. I remember running 1.9.0 somehow (but with errors, of course), and so, for some reason, the color for the chat no longer worked there, which could be added with the command:
^^1(Red)
^^2(Green)
etc...
Looking forward to your soonest reply!

**Comment by a1batross** [comment]
Newer AMXX _do_ actually work on the new engine.

They intentionally can't find some symbols like `SV_KickPlayer` and `svs` but only because those are private symbols and don't really have to be compatible.
