### ISSUE TITLE
Print out texts when sounds are played (Possible subtitle system)

### ISSUE THREAD

**Issue by qabRieL99** [FWGS/xash3d-fwgs#294]
I wonder if something like this is possible? Original HL series lack the support of subtitles, so it would be nice.

**Comment by lewa-j** [comment]
See https://github.com/FWGS/xash3d/issues/171

**Comment by DrPeeper228** [comment]
This mod is no longer available

**Comment by a1batross** [comment]
It's something that mod should care about.
