### ISSUE TITLE
detail.txt generation

### ISSUE THREAD

**Issue by lewa-j** [FWGS/xash3d-fwgs#295]
Feature advertised by r_detailtextures description but not present in the code.
Also gl_detailscale present but never used due to that.

If feature was removed intentionaly, we must change the description of r_detailtextures and get rid of gl_detailscale.

Related lines
https://github.com/FWGS/xash3d-fwgs/blob/9bc3d6d31578f4e12bccdf976ebdceee61cd8141/ref_gl/gl_opengl.c#L839
https://github.com/FWGS/xash3d-fwgs/blob/9bc3d6d31578f4e12bccdf976ebdceee61cd8141/ref_gl/gl_opengl.c#L854
The old engine: https://github.com/FWGS/xash3d/blob/725fd84b5ba8d405979d63df7a906feb1bc87d51/engine/client/gl_rmisc.c#L226

**Comment by nekonomicon** [comment]
AFAIR, r_detailtextures used in CS CZ.

**Comment by a1batross** [comment]
Do we actually need that generator? 
If not, I will delete it's leftovers.

**Comment by lewa-j** [comment]
I dont think anyone ever used it besides UnkleMike. Anyway this better to be separate tool than the part of the engine.

**Comment by a1batross** [comment]
UnkleMike saidthat no one used this tool and it was too hardcoded, so he removed it.
