### ISSUE TITLE
[Android] Window size is not restored in the console after invoking the on-screen keyboard in software renderer.

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#298]
https://youtu.be/pgIG3LNUOqU

**Comment by mittorn** [comment]
For is completely broken in gles renderers

**Comment by Vladislav4KZ** [comment]
И также исправлено в старом лаунчере в версии от mittorn:
https://github.com/mittorn/xash3d-android-project/releases/tag/android-legacy-prerelease
