### ISSUE TITLE
C99

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#30]
I suggest moving to C99 standard.
We actually never supported old compilers, so it shouldn't be a problem.

Instead we get:
* possibility to define variables not only at start of the block. 
* __VA_ARGS__(supported in msvc, but support is still partial and may be buggy)
* better inline
* stdint.h
* restrict keyword
* compound literals(msvc sucks here)
* designated initializers.
* more UB
* ...

Yes, it's hard to implement C99 fully in compilers, but standards are theoretical(especially C99) and anyway we can still use implemented subset of C99.

**Comment by a1batross** [comment]
Sometimes we forgot about definition at block start rule and still use compilers defaults, which is C11, AFAIK.

**Comment by FOTMarut** [comment]
Actually, it looks like it's a C99 feature
[https://en.cppreference.com/w/c/language/declarations#Notes](url)

**Comment by a1batross** [comment]
@FOTMarut I know. I mean that compilers use C11 by default and because of that we sometimes forget that we still target C89 with some extensions.

**Comment by a1batross** [comment]
@FOTMarut I know. I mean that compilers use C11 by default and because of that we sometimes forget that we still target C89 with some extensions.

**Comment by a1batross** [comment]
Still waiting for @mittorn's opinion on this.

**Comment by mittorn** [comment]
It is not good to drop some compilers before full migration to new engine

**Comment by a1batross** [comment]
@mittorn that's the my point. We don't have to drop compilers, as we never supported them properly.

**Comment by a1batross** [comment]
We can also move to C++ internally, of course, with keeping C compatibility on runtime. 

I am not joking. Even Unkle Mike moved to C++ in his XashNT engine.

**Comment by a1batross** [comment]
Until we don't have any alternatives on MS Visual C runtime on Windows, it's not worth to move on C99, let alone C11.

How to write in C for Windows? Don't write in C for Windows.

**Comment by SNMetamorph** [comment]
> We can also move to C++ internally, of course, with keeping C compatibility on runtime.
> 
> I am not joking. Even Unkle Mike moved to C++ in his XashNT engine.

I think it'll be good
