### ISSUE TITLE
[non-topic] Open-Source  Hammer Alternative

### ISSUE THREAD

**Issue by ushakov-31293** [FWGS/xash3d-fwgs#303]
If we have open-source HL1 engine, do we have an open-source Hammer alternative?

**Comment by nekonomicon** [comment]
https://github.com/joeriedel/tread2.4f
https://github.com/LogicAndTrick/sledge
https://github.com/TrenchBroom/TrenchBroom

**Comment by ushakov-31293** [comment]
There must be one flagman project.

First and second are dead.

Third - HL1 is not officially supported.

And [this one](https://jack.hlfx.ru/ru/) is dead too?

**Comment by nekonomicon** [comment]
J. A. C. K. is commercial non-opensource project.

> Third - HL1 is not officially supported

HL support was added by our teammate - @mittorn

**Comment by ushakov-31293** [comment]
Cool. But on it's website and github site there is no info about that support. Was patch approoved? Is support feature-compatible with official Hammer?

**Comment by a1batross** [comment]
I'm not a mapper but I wish we had an opensource Xash "flagship" map editor.

On other hand, this doesn't sound like a big problem, as there is plenty of FOSS editors that support Half-Life and there is JACK which pretty cool (although commercial) editor. Map compilers are opensource.

**Comment by ushakov-31293** [comment]
Thank you guys (главное в этом слове не сделать ошибку) for your reply.

No one level designer wants to waste time - there should be standard tool. As @nekonomicon  suggests - TrenchBroom can become that standard solution. And it looks really very interesting, even better than Jack.

By compilers you means http://zhlt.info/ ?

I had no knew about it thank you, @nekonomicon .

**Comment by mittorn** [comment]
UMHLT and P2ST are the most recent now.
TrenchBroom supports half-life wad (with my patch, already in upstream), but not models, which may be important for mappers. And it has very unusual interface/controls
Maybe some radiant forks support HL better? But it all seems to be dead
There is still no better solution than VHE/Jack

**Comment by ushakov-31293** [comment]
Jack even has no workable download link for windows.

UMHLT is inactive during 4 years, 

And, can you, please,  suggest what is P2ST?

> Maybe some radiant forks support HL better?

No one wants to deal with unknown forks, as I think.

**Comment by nekonomicon** [comment]
> Jack even has no workable download link for windows.

Jack is available in steam.

> UMHLT is inactive during 4 years

Because development is finished.

> And, can you, please, suggest what is P2ST?

Paranoia 2: The Savior Tools.

**Comment by ushakov-31293** [comment]
> UnkleMike's VHLT (untested) 

Untested during 4 years.

> Jack is available in steam.

I shall buy it in the future to support it. But, it latest release was also 4 years ago.

And, maybe you add XASH as paid better newer game engine for HL 1 mods in Steam to get some money?

> Paranoia 2: The Savior Tools

Can you, please, explain - what is it?

**Comment by nekonomicon** [comment]
Paranoia 2: The Savior is first game on Xash3D with own map/model formats.

**Comment by ushakov-31293** [comment]
CLI tools?

**Comment by nekonomicon** [comment]
Yep.

**Comment by ushakov-31293** [comment]
What knowledge developer must have to work on XASH and the toolset?

Of cource, C and C++, and what computer graphics knowledge is required?

**Comment by nekonomicon** [comment]
Linear/vector algebra and knowledge of quake-like engines architecture.
May be reverse-engineering skills.

**Comment by ushakov-31293** [comment]
MMF education solves the first problem, but where get knowledge of the last two?

**Comment by a1batross** [comment]
I don't think there is anything to reverse engineer now, except maybe some interesting mods.
These times are gone, engine is mostly ready. 

It all needs to be better tested.

**Comment by ushakov-31293** [comment]
Excuse me, but without programming there is no fun. Beta testers can be found in school, I think. And, after programming in any case developer should test his work.

Maybe, there are some docs about engine architecture?

**Comment by a1batross** [comment]
>Beta testers can be found in school

That's where you came from today? If not, then you can already write your own games with Xash right now and not waste time by asking stupid questions.

**Comment by a1batross** [comment]
The engine architecture is similar to Quake, there is plenty of articles on Quake engine.
