### ISSUE TITLE
Do I have to open source my modified code based on Xash3D-FWGS?

### ISSUE THREAD

**Issue by kalenclark** [FWGS/xash3d-fwgs#304]
I'm making a HL1 mod, and I may modified some code of Xash3D-FWGS to build Xash3D executable and other dlls.
I'll declare this project is using code from this project,
so the question is:
Do I have to open source my modified version code from xash3d-fwgs?

**Comment by kalenclark** [comment]
Is it licensed under GPL?

**Comment by lewa-j** [comment]
Yes

**Comment by kalenclark** [comment]
> Yes

What about my mod?

**Comment by a1batross** [comment]
You may not opensource anything that's on HLSDK side: client.dll and mod dll(hl.dll).

But you must publish modified engine and menu source code, as they both licensed under GPL.

**Comment by kalenclark** [comment]
> You may not opensource anything that's on HLSDK side: client.dll and mod dll(hl.dll).
> 
> But you must publish modified engine and menu source code, as they both licensed under GPL.

What about close-source library(like Noesis GUI library, I have no access to the source code) used in engine side?

**Comment by kalenclark** [comment]
Thanks for your patience~ I got what I wanna know.

**Comment by a1batross** [comment]
>What about close-source library(like Noesis GUI library, I have no access to the source code) used in engine side?

Well in this case we don't mind because we already using engine with non-free code which is Half-Life game code and headers from SDK.

**Comment by kalenclark** [comment]
> > What about close-source library(like Noesis GUI library, I have no access to the source code) used in engine side?
> 
> Well in this case we don't mind because we already using engine with non-free code which is Half-Life game code and headers from SDK.

OK, thanks~ : >

**Comment by a1batross** [comment]
It would still be GPL violation but in reality seems no that much people care unless the source is just freely available.

I'm not sure how can you sell that but there was no games built on Xash that gone commercial and we don't know.
