### ISSUE TITLE
Stuck on Freeman being stunned by soldiers

### ISSUE THREAD

**Issue by grepwood** [FWGS/xash3d-fwgs#309]
During a playthrough on hard of Steam version of data assets, in commit 652a946e09800b154150dfcf224c7e8fe0bbfc10, the engine will leave the player in a dark corridor after the soldiers' dialogue. The only way to continue to the trash compactor is by entering noclip mode and going dropping out of noclip inside the trash compactor. Furthermore, the trash compactor does not start once the player materializes there out of noclip mode.

**Comment by a1batross** [comment]
Was there anything in log?

**Comment by grepwood** [comment]
Unable to reproduce :(

**Comment by a1batross** [comment]
@grepwood sorry for not noticing it. 

Bug like this sometimes happens even in current vanilla Half-Life. Did you tried our HLSDK fork where we fix some of the HL1 bugs?
