### ISSUE TITLE
How to run mods with AppImage Linux releases?

### ISSUE THREAD

**Issue by rea987** [FWGS/xash3d-fwgs#310]
Greetings,

I am able to run official titles like HL with 32 bit AppImage Linux release just fine but unable to run mod with it. Xash3D FWGS v0.19.2 allows me to use arguments like `-dll`, `-vguiloader` to run HL mods for Windows on Linux. For example, following is my launch command for **Half-Life: Azure Sheep** for Xash3D FWGS v0.19.2:

`LC_ALL=C ./xash3d.sh -game azuresheep -dll dlls/hl.dll -clientlib cl_dlls/client.so`

However, same doesn't work with Xash3D FWGS 0.20. Have arguments changed or v0.20 doesn't support user mods yet? Thank you!

**Comment by a1batross** [comment]
0.20 doesn't support Windows DLLs under non-Windows systems.
In 0.19.x and older it was a temporary solution that wasn't really stable enough, so it got removed.

To run Azure Sheep, you can compile it from the source code: https://github.com/FWGS/hlsdk-xash3d, branch asheep.

**Comment by rea987** [comment]
Thank you!
