### ISSUE TITLE
Bug with rain in 101 grunts

### ISSUE THREAD

**Issue by Skyrim-police** [FWGS/xash3d-fwgs#313]
Bug in 101 grunts mod 
https://user-images.githubusercontent.com/65493638/107681287-89131700-6ca7-11eb-8ed8-51b0a8e40e71.mp4

use last version of Xash3D from: https://github.com/FWGS/xash3d-deploy/tree/anewengine-master
mod link: https://www.runthinkshootlive.com/posts/101-grunts/

**Comment by SkyNinja** [comment]
I can confirm that this also occurs in the first map of Edge of Darkness, played on Win32-i386 build 2144.

**Comment by Vladislav4KZ** [comment]
This bug is also present in They Hunger (no rain animation)

**Comment by a1batross** [comment]
Fixed by now. 

The rain frequency is weird though, it gets synchronized like as if rain drops move upwards, but it's just FPS dependent.
