### ISSUE TITLE
High Resolution Textures Option Missing

### ISSUE THREAD

**Issue by SkyNinja** [FWGS/xash3d-fwgs#315]
In my video options menu, there is no option for high resolution textures. Old Xash documentation cites the command "host_allow_materials", but the command is not found in FWGS. In-game, no custom materials display.

**Comment by a1batross** [comment]
It was removed in upstream. We plan to revert it but it's not so easy after engine refactoring.

**Comment by palmerj** [comment]
Any progress on this?

**Comment by a1batross** [comment]
Unfortunately, nobody worked on it since. :(

**Comment by unattendedplayer** [comment]
I support this option to come back. It totally renders my work for an HD mod useless.

**Comment by a1batross** [comment]
Duplicate of https://github.com/FWGS/xash3d-fwgs/issues/27
