### ISSUE TITLE
[Android] Incorrect chapter title

### ISSUE THREAD

**Issue by MJ32768** [FWGS/xash3d-fwgs#320]
The chapter "Forget About Freeman" turned into "On You Own" incorrectly in game , but in "titles.txt" , it's still "FORGET ABOUT FREEMAN!" ,  the problem really sucks , please help🙏
![Screenshot_20210224-115124](https://user-images.githubusercontent.com/52265716/108944950-b17f1600-7696-11eb-975f-54d0f3b4ad0d.png)
![Screenshot_20210224-115235](https://user-images.githubusercontent.com/52265716/108945587-cf00af80-7697-11eb-84d0-1a5cea1e4bd6.png)

**Comment by MJ32768** [comment]
Exactly , only if when I load or save game can I see the strange "On Your Own" , if I change chapters when playing game , it will correctly displays "FORGET ABOUT FREEMAN" in the right area of screen for a few seconds ( I'm a Chinese student , my English is not very good )

**Comment by lewa-j** [comment]
Did you tested it on GoldSrc?

**Comment by MJ32768** [comment]
> 您是否在GoldSrc上测试过？

Not yet, I play the official steam version in PC and use Xash3D Android port to play half life

**Comment by MJ32768** [comment]
I mean……, I haven't try PC version of Xash yet

**Comment by a1batross** [comment]
I looked what GoldSrc does:

1. It searches for SV_SaveGameComment export in server dll. If it's found, it's being used to generate save chapter title. Xash does the same.
2. If it's not found, the engine provided version is used. And there is the difference: GoldSrc has hardcoded map name to title key dictionary, when Xash reads "message" key of world entity. 

The fix is obvious, we need take that hardcoded dictionary and use it.

**Comment by MJ32768** [comment]
> I looked what GoldSrc does:
> 
> 1. It searches for SV_SaveGameComment export in server dll. If it's found, it's being used to generate save chapter title. Xash does the same.
> 2. If it's not found, the engine provided version is used. And there is the difference: GoldSrc has hardcoded map name to title key dictionary, when Xash reads "message" key of world entity.
> 
> The fix is obvious, we need take that hardcoded dictionary and use it.

So what files do you need? Here is my "titles.txt" :
https://drive.google.com/file/d/1Z4PJgjtF083AK3z5cja8gpffNPfDxeWd/view?usp=sharing

**Comment by a1batross** [comment]
Zero, I already fixed it. Testing it and gonna push the fix.

**Comment by MJ32768** [comment]
> Zero, I already fixed it. Testing it and gonna push the fix.

I completed the game with Xash FWGS today, only the chapter "Forget About Freeman" has the strange titles in the "Save/load game " interface

**Comment by MJ32768** [comment]
And when I watch the end credits after the chapter "End game", it played music for a few seconds and suddenly stopped , maybe it's the  problem of my device, but I just can't enioy the full music! I know it is unsuitable to put forward a new issue here , however, it should also be solved:
![Screenshot_20210226-171921](https://user-images.githubusercontent.com/52265716/109303812-468c3580-7876-11eb-95e7-270edac9830b.png)
![35e86601e85aaa3](https://user-images.githubusercontent.com/52265716/109303828-4be98000-7876-11eb-930c-afa12546db4e.png)

**Comment by a1batross** [comment]
One bug = one report.

**Comment by MJ32768** [comment]
> One bug = one report.
You are quite right

**Comment by MJ32768** [comment]
Sure, you are right.

**Comment by BlackShadow** [comment]
On Your Own is the "Beta" title for Forget About Freeman. It's inside of the BSP file. Xash probably read it inside the BSP file instead of titles.txt
