### ISSUE TITLE
[Android] Missing conveyor belt texture

### ISSUE THREAD

**Issue by MJ32768** [FWGS/xash3d-fwgs#321]
I get white conveyor belt in specific perspective , how to solve this problem?
   ![Screenshot_20210224-150321](https://user-images.githubusercontent.com/52265716/108988121-10f91800-76cf-11eb-88cb-8bda8d61e815.png)
![Screenshot_20210224-150420](https://user-images.githubusercontent.com/52265716/108988138-16eef900-76cf-11eb-9866-a4787f68e3dc.png)

**Comment by a1batross** [comment]
Try to disable VBO (r_vbo 0 in console) and see if it bug shows up again.

Also, please, when bugreporting **always** tell what your hardware is and which Android version you're running.

**Comment by MJ32768** [comment]
It works! Thank you!

**Comment by a1batross** [comment]
No, can you tell what hardware you have, so we can fix it later?

**Comment by MJ32768** [comment]
My phone is Letv X500, I flashed it with Cyanogenmod13(Android6.0.1), I changed dpi from 480 to 400, the hardware accelerate is not working ,
![Screenshot_20210226-203819](https://user-images.githubusercontent.com/52265716/109301361-ce704080-7872-11eb-9f2f-e2f7c54d7e49.png)
![Screenshot_20210226-203825](https://user-images.githubusercontent.com/52265716/109301385-d6c87b80-7872-11eb-898d-bcc81befb583.png)
![Screenshot_20210226-203852](https://user-images.githubusercontent.com/52265716/109301411-e21ba700-7872-11eb-8892-ff279afd7179.png)
if you need to know other information , just tell me

**Comment by a1batross** [comment]
Should be fine with vbo-fix merge.

**Comment by mittorn** [comment]
Need to retest. It is nanogl-related
