### ISSUE TITLE
Mouse still showing 

### ISSUE THREAD

**Issue by RVV10** [FWGS/xash3d-fwgs#322]
The mouse cursor still shows on the side of the screen on android even if I turn off ignore mouse

**Comment by a1batross** [comment]
This option doesn't make your mouse cursor disappear, it's drawn by Android itself. Option to "ignore mouse" just should ignore any mouse input, as sometimes it's only conflicting with other types of input: gamepad or touchscreen.

I guess we can make Android disable it though.

**Comment by RVV10** [comment]
> This option doesn't make your mouse cursor disappear, it's drawn by Android itself. Option to "ignore mouse" just should ignore any mouse input, as sometimes it's only conflicting with other types of input: gamepad or touchscreen.
> 
> I guess we can make Android disable it though.

I tested it with my small phone which works fine and I tested it in nvidia smart tv works fine
But on my main phone the mouse cursor still shows when I look the left
Many people has this issue on the latest smart phones
I even tested it on my friend phone same issue

**Comment by a1batross** [comment]
So what? This option is _not intended_ to hide mouse cursor.

**Comment by mittorn** [comment]
It hides mouse via nvidia api if availiable
