### ISSUE TITLE
Stuck in level c0a0a

### ISSUE THREAD

**Issue by r4v3n6101** [FWGS/xash3d-fwgs#324]
After building for arch I stucked in the every map after I load. Stuck in c0a0a after c0a0 and so on. +map is not solution as it has same effect. Me using steam's `valve` dir.

**Comment by a1batross** [comment]
Post engine log.

**Comment by r4v3n6101** [comment]
@a1batross, solved as xash3d doesnt have access to `valve` directory. Is there any way to provide path to other location than nearby of `xash3d` executable?

**Comment by a1batross** [comment]
Yes, through environment variables.

XASH3D_BASEDIR is to set base writable directory.

There is also RoDir feature, that allows to store game data on read-only storage, can be controlled with XASH3D_RODIR envvar or -rodir command line key.
