### ISSUE TITLE
Проблема с интерполяцией энтити

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#329]
В мультиплеере энтити/игроки двигаются дерганно, даже если пинг невысокий. Также, этому подвержена и анимация моделек.

**Comment by noname946** [comment]
Такое ощущение, что интерполяция в новом Ксаше вовсе сломана.
Ибо на новых серверах всё какое-то дёрганное, особенно на лесницах, там игрока вообще трясёт.

**Comment by SNMetamorph** [comment]
> 
> 
> Такое ощущение, что интерполяция в новом Ксаше вовсе сломана.
> Ибо на новых серверах всё какое-то дёрганное, особенно на лесницах, там игрока вообще трясёт.

Да это еще и на старом ксаше так было, в прикрепленном видео как раз таки старый ксаш.

**Comment by SNMetamorph** [comment]
Пока неясно. На свежем сервере 0.20 все плавно даже если серверный FPS 30. Единственное, стрела арбалета в HLDM летит будто бы совсем без интерполяции. На старых серверах 0.19 все игроки дерганные, но энтити вроде нет.
Думаю, нужно проблему конкретизировать.
