### ISSUE TITLE
Attempting to create a LAN game while no network is present quits back to main menu

### ISSUE THREAD

**Issue by x6herbius** [FWGS/xash3d-fwgs#33]
I've been trying to test a multiplayer map in my own fork, and was attempting to do this on my laptop without network connectivity. I only needed to run up a local server with me in it, so actual connectivity was not required.

If I go through the main menu to the multiplayer section and attempt to create a LAN game in this instance, I get the following error:

```
[17:51:01] Scanning for servers on the local network area...
[17:51:01] Host_Error: NET_SendPacket: Network is unreachable to 100.221.255.191:27015
```

Because of the host error, I then get taken back to the main menu and am unable to proceed in creating the local server. (Note that I'm running with `-dev 5` - I dunno if the same would happen without that option).

My first thoughts on remedying this would be to allow an option to be passed to NET_SendPacket (and the other functions that the local server calls through to) to specify whether failures should be critical. Is this something that would be considered? I could put together a pull request for it if so.

**Comment by mittorn** [comment]
New engine may have many such errors. It was not tested so much in multiplayer. All network errors should be ignored because network may disappear temporary and restore, that will not break UDP connections. Just replace it with error message like in old engine. Yes, you may create PR

**Comment by x6herbius** [comment]
https://github.com/FWGS/xash3d-fwgs/pull/34

**Comment by x6herbius** [comment]
Has been merged. Apologies about the commit message format, I'll make sure that's right next time.
