### ISSUE TITLE
Неправильный рендер растровых шрифтов в mainui.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#331]
При использовании ref_soft, если по каким-либо причинам mainui использует растровые шрифты для текста, а не векторные через freetype, то растровые шрифты рендерятся с тёмно-синим оттенком.
![test](https://user-images.githubusercontent.com/79874964/109717964-03e49900-7ba7-11eb-8f72-ed71d49db0fe.png)

**Comment by mittorn** [comment]
alpha блендинг очень неточный в ref_soft, это ожидаемое поведение для этого оттенка. Базовая часть RGB332 блендится точно по таблице, а остальная RGB233 просто делится на 2 и суммируется операцией или, от того синие артефакты на тёмных оттенках.
Если по какой-то причине ttf шрифты выглядят лучше - им просто повезло что там другой оттенок преобладает не как у консольного шрифта.
в общем для текущей технлолгии блендинга wontfix. Если я вдруг займусь ещё рендером и попытаюсь задействовать другие алгоритмы или даже simd, может что-то будет лучше.
Замечу что в голдсорсе такого варианта блендинга за пределами vgui просто нет, только additive, альфатест и отрисовка без блендинга  Как он в vgui реализован - не знаю, но вроде как не очень быстро и vgui менюхи в software только по этому в кс отрубали - на них fps проседал в 0. Из-за этого скорее всего и появилась опция vgui menus
