### ISSUE TITLE
Сломан перевод названий глав в сохранениях.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#332]
После коммита fa555c1 сломался перевод названий глав в сохранениях, если до этого коммита сохранения из c1a0 имели название главы "Anomalous Materials", то после этого коммита сохранения имеют название "#C0A1TITLE".
Если откатить этот коммит, то баг исчезает, но при этом сохранения, сделанные после этого коммита остаются с непереведёнными названиями глав.

**Comment by lewa-j** [comment]
Не могу воспроизвести. На какой конкретно карте проявляется? titles.txt на месте?

**Comment by noname946** [comment]
@lewa-j На c1a0.
titles.txt на месте.

**Comment by lewa-j** [comment]
при ручном сохранении через меню, всё работает как надо. Заметил только с автосейвом. Стоило об этом упомянуть.

**Comment by noname946** [comment]
@lewa-j Проверил сохранения через меню, действительно, в этом случае названия глав сохраняются как надо, я просто тестировал только qucksave, он тоже подвержен этой проблеме.

**Comment by lewa-j** [comment]
Но при быстром сохранении название не "#C0A1TITLE" а "[quick]#C0A1TITLE" и это уже указывает на суть проблемы.
