### ISSUE TITLE
Не обновляется показание пинга у игроков в scoreboard на новых серверах.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#341]
На новых серверах не обновляется показание пинга у игроков в scoreboard, вместо этого он всегда показывает 0.
Тестировал на тестовом сервере на 49 протоколе "[Eclipse]TestServer"

**Comment by mittorn** [comment]
Да, тоже сломано как и в оригинале. Надо тег какой-то добавить для портирования изменений со старого движка

**Comment by noname946** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/454300801230c45d3c7f2cd77ffa4ce337e57cb8.
