### ISSUE TITLE
Не работает RCON на новых серверах.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#342]
На новых серверах не работает RCON, не смотря на правильный/неправильный пароль или команду, команда rcon просто ничего не возвращает в ответ.
Тестировал на тестовом сервере на 49 протоколе "[Eclipse]TestServer"

**Comment by mittorn** [comment]
В оригинальном ксаше сломана передача ответа на rcon, сами команды передаются, а в ответ пустой print.
В старом движке мы это поправили. Можно портировать со старого, но лучше вообще сделать другой ркон с хэшем и солью какой-нибудь, то что сейчас с передачей сырого пароля никуда не годится

**Comment by noname946** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/c62db950f190d2059dca45ac88f3c53439e304f3.
