### ISSUE TITLE
Не читает строки с gamedir_english.txt если стоит язык отличимый от английского

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#348]
Стоит русский язык (ui_language russian)
Если в файле перевода отсутствуют некоторые строки или один из файлов вообще отсутсвует (пр. есть valve_russian.txt и нет tfc_russian.txt но есть tfc_english.txt)
То наблюдается такая картина:
![Безымянный](https://user-images.githubusercontent.com/22411953/110606732-ae1a7d00-81b4-11eb-82e5-cd31d27f6a8e.png)

В GoldSource если есть не переведённые строки то они берутся c файла gamedir_english.txt

**Comment by a1batross** [comment]
ЕМНИП, оно ещё сложнее и есть специальный тег [english] в _russian файлах. Имеет ли он отношение к этому я не знаю.

Я думаю для первого раза достаточно просто добавить _english перед тем, что выставлено в ui_language.

**Comment by Vladislav4KZ** [comment]
> есть специальный тег [english] в _russian файлах

Я видел это в официальной русской локализации в Steam версии Half-Life, но у меня на данный момент файлы без этого тега

**Comment by a1batross** [comment]
Должно быть исправлено теперь.
