### ISSUE TITLE
Нет звука ходьбы по лестнице

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#349]
Везде, в оригинальном Half-Life и в модах

**Comment by Vladislav4KZ** [comment]
Последняя сборка движка для Windows

На Android версии есть звук
Последнюю сборку на андроид не смог скачать так как оба 32-битный и 64-битный ксаш это пустой файл

**Comment by noname946** [comment]
В одиночной игре или в мультиплеере?
Ибо если в мультиплеере, то это известная проблема.

**Comment by Vladislav4KZ** [comment]
@noname946 да, только в мультиплеере

**Comment by noname946** [comment]
@Vladislav4KZ https://github.com/FWGS/xash3d-fwgs/issues/329#issuecomment-792350993
Я уже про это писал, правда не упомянул про так-же отсутствующий звук, но как я понял проблема общая.

**Comment by a1batross** [comment]
Проблема была в неправильно закодированной дельте.

Фикс требует обновления сервера и я не знаю кто владелец того сервера, что сейчас в списке.
