### ISSUE TITLE
All breakables sound and look like glass when broken

### ISSUE THREAD

**Issue by RobyKalilla** [FWGS/xash3d-fwgs#351]
except crates, strangely......
I have Xash3D, downloaded as xash3d-vc.

**Comment by lewa-j** [comment]
Provide a way to reproduce. Save and screenshot

**Comment by RobyKalilla** [comment]
https://streamable.com/pvmi2k

**Comment by a1batross** [comment]
Video link is not available anymore.

And
>xash-vc

It seems it's an old engine issue.
