### ISSUE TITLE
Жёлтые точки кружат над игроком когда он взял флаг в TFC

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#356]
![Снимок экрана (21)](https://user-images.githubusercontent.com/22411953/110928200-cf17d500-8350-11eb-8b3b-ca24c7ecd858.png)

**Comment by noname946** [comment]
Проверь консоль, случайно там нету что-то типа этого?:
"Monster %s stuck in wall--level design error"

**Comment by Vladislav4KZ** [comment]
> Проверь консоль, случайно там нету что-то типа этого?:
> "Monster %s stuck in wall--level design error"

Не, нет такого

**Comment by a1batross** [comment]
Нет, это что-то другое, не застревание монстра. :) 

Но мне вообще казалось что так быть и должно.

**Comment by Vladislav4KZ** [comment]
В последней сборке ксаша их не видно
