### ISSUE TITLE
Спам в консоль при использовании эффекта EF_BRIGHTFIELD.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#357]
При использвании эффекта EF_BRIGHTFIELD, если зайти в консоль или в главное меню не делая disconnect, то в консоль каждую секунду начнёт спамить этой ошибкой:
`Error: Overflow 4096 particles`

**Comment by mittorn** [comment]
https://ru.m.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B0%D0%BC

**Comment by a1batross** [comment]
Not a bug.
