### ISSUE TITLE
Квары с флагом FCVAR_SERVER не меняются через server.cfg.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#360]
Квары с флагом FCVAR_SERVER не меняются через server.cfg при запуске сервера, например, mp_allowmonsters не смотря на указание в server.cfg как 1, после запуска он остаётся 0.

**Comment by Velaron** [comment]
Там какая-то проблема с тем что конфиг вообще не вызывается на выделенных серверах

**Comment by noname946** [comment]
@Velaron Неа, таки вызывается, ибо hostname, public и sv_password меняются через server.cfg.

**Comment by a1batross** [comment]
Потому что идиотизм.

Когда-то давно server.cfg исполнялся самим игровым кодом -- этот факт можно проверить посмотрев комментарий в конструторе CHalfLifeMultiplay.

Потом это убрали и server.cfg стал исполняться движком где-то после загрузки DLL. Делает ли так Ксаш? Нет. Должен ли? Я считаю, да. Но тем не менее эпопея с конфигами длится уже несколько лет.

**Comment by a1batross** [comment]
Притом со всей этой инициализацией есть проблема -- любители пихать "map" в server.cfg.

И по логике своей ему можно там быть. Однако процесс загрузки игры в Ксаше не соответствует таковому в GoldSrc. И где вставить "exec server.cfg" не вызвав бесконечный цикл? Загадка.

**Comment by a1batross** [comment]
Текущая ситуация такая:
1) server.cfg не вызывается современными дллками и наш hlsdk-xash3d тоже так не делает.
2) Xash это делает единожды ДО загрузки дллки. По идее, можно было бы свободно выполнить server.cfg после загрузки дллки, только проблема в том, что Ксаш подгружает сервер только при необходимости -- когда имя карты уже известно.
3) GoldSrc это делает единожды сразу после загрузки дллки. Однако GoldSrc устроен другим образом -- dedicated сервер сначала подгружает дллку, а потом запускает какую-нибудь карту. Вполне возможно так происходит и с listenserver, и с обычной игрой.

**Comment by mittorn** [comment]
В старом движке проблема решалалась созданием кваров через set. Это хоть и не совсем корректно, но надёжно
