### ISSUE TITLE
Не работает квар r_wadtextures 1

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#361]
Новый движок всё равно загружает встроенные в карту текстуры если включён этот квар. А должен вместо них загружать текстуры только с wad файлов

Скриншоты сделаны со сторонним halflife.wad

Вот старый движок
![Screenshot_20210313-160400.png](https://user-images.githubusercontent.com/22411953/111026839-dd302900-8416-11eb-9bff-035f2a3dc977.png)

Вот новый движок
![Screenshot_20210313-160904.png](https://user-images.githubusercontent.com/22411953/111026865-f33de980-8416-11eb-91e3-d9cb7a5f9cea.png)

**Comment by noname946** [comment]
В старых билдах нового Ксаша помню оно точно работало, видно, сломалось от чего-то.

**Comment by a1batross** [comment]
Можешь этот wad файл выложить?

**Comment by Vladislav4KZ** [comment]
@a1batross https://disk.yandex.kz/d/GqDBanIUvMbBAg

**Comment by a1batross** [comment]
У меня работает на последней сборке. С учетом того, что переключение работает только до запуска любой карты, так как иначе текстуры уже будут загружены в память и не будут перечитываться второй раз.
