### ISSUE TITLE
Mem_Alloc: out of memory (alloc at ../engine/client/cl_demo.c:956) при попытке запустить демку.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#362]
При попытке запустить записанную демку, игра вылетает с "Mem_Alloc: out of memory (alloc at ../engine/client/cl_demo.c:956)".

**Comment by lewa-j** [comment]
Всегда публикуй полный лог. И желательно файл демки которая это вызывает.

**Comment by noname946** [comment]
@lewa-j Лог не предоставляю, ибо не вижу в этом смысла, даже по моему осмотру там ничего полезного не нахожу, но если вам так нужно, вот.
Так-же выкладываю саму демку.
[engine.txt](https://github.com/FWGS/xash3d-fwgs/files/6137501/engine.txt)
[demo0000.zip](https://github.com/FWGS/xash3d-fwgs/files/6137504/demo0000.zip)
Не забудьте сменить расширение на .dem у демки, ибо GitHub не позволяет залить демку с её родным расширением.

**Comment by lewa-j** [comment]
Там есть полезная информация. Например, то что ты используешь ref_soft. Ты же этого не указал.

**Comment by lewa-j** [comment]
А сколько у тебя в системе памяти?

**Comment by noname946** [comment]
@lewa-j 4 гигабайт.
И не уверен если честно, что это вообще проблема рендера.

**Comment by lewa-j** [comment]
Проверил этот файл на Wundows, и ref_soft и ref_gl работают без крашей.

**Comment by a1batross** [comment]
malloc может конечно упасть с ENOMEM, но на Linux это надо сильно постараться.

**Comment by lewa-j** [comment]
Но Mem_Alloc не смотрит на причину. Там просто `if( mem == NULL )`

**Comment by mittorn** [comment]
Да не надо постараться. Надо просто очень большое число сравнимое с размерами рамы или адресного пространства

**Comment by mittorn** [comment]
даже если на 32 битах выдеделить 4 гига то наверняка в АП не будет непрерывного участка в 4 гига. aslr ещё сильнее ограничивает размер аллокации

**Comment by a1batross** [comment]
Probably was fixed in https://github.com/FWGS/xash3d-fwgs/pull/933
