### ISSUE TITLE
Не читает файлы с pk3 архивов содержащие кириллицу в названии

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#364]
Не читает файлы с pk3 архивов содержащие кириллицу в названии когда используется сжатие
Файлы с латиницей он читает

Если архив создан без сжатия то читает и кириллицу

Названия файлов в архиве сохранены в кодировке UTF-8
Пробовал и с Windows-1251, тоже самое (тоже читает только без сжатия)

Эти файлы - звуки для vox

UPD: Небольшая поправка, также читает символы с кириллицей на минимальном уровне сжатия, дальше уже не может

**Comment by nekonomicon** [comment]
Русские символы занимают 2байта в unicode,  но в движке это нигде не учитывается и считается, что все символы ANSI, и после перевода всех символов в нижний регистр допустим строки могут сломаться.
