### ISSUE TITLE
Не компилируется с параметром -T sanitize.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#365]
При попытке скомпилировать движок с параметром -T sanitize, то на этапе линковки libxash происходит ошибка:
```
[235/235] Linking build/engine/libxash.so
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: engine/common/net_ws.c.1.o: in function `NET_StringToSockaddr':
*secret*/xash3d-fwgs/build/../engine/common/net_ws.c:496: undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status
```
Параметры компиляции:
`-T sanitize -8 --disable-vgui --disable-gl`
Полный лог компиляции:
[build.txt](https://github.com/FWGS/xash3d-fwgs/files/6143115/build.txt)

Используемый компилятор: GCC 9.3.0.
OS: Gentoo Linux.
Платформа: amd64.

**Comment by mittorn** [comment]
Добавь пока что -pthread во флаги линковки

**Comment by a1batross** [comment]
Fixed.
