### ISSUE TITLE
Некоторые символы в нике, в scoreboard показываются как другие символы.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#366]
Заметил, что некоторые символы в нике, в scoreboard показываются как другие символы.
Например, вместо " < " показывается " ; ", вместо " > " показывается " : ", вместо " ^ " показывается " ' ".
(Перемещено из https://github.com/FWGS/hlsdk-xash3d/issues/160)

**Comment by mittorn** [comment]
Проблема в файлах халфы

**Comment by mittorn** [comment]
Конкретно - gfx.wad
