### ISSUE TITLE
More Security on Engine

### ISSUE THREAD

**Issue by CaNNiC2** [FWGS/xash3d-fwgs#369]
Can you guys make Xash3D FWGS more secure
Im saying this because there are some kids who spam in my servers and I have banned them many times but they still manage to get unbanned .

**Because :** 
When I ban by **IP** - they change IP using VPN
When I ban by **XashID** - they change their XashID

I have even made some plugins that detect their names and ban them but they got it 

Actually I have found an Anti Proxy/VPN AMXModX Plugin but it uses a module that works only on AMXX 1.9 and up , and AMXX 1.9/1.10 aren't working on Xash3D FWGS as I've reported before on #290 

And someone has told me that XashID can be changed by changing Phone IMEI , so it would be good if in next version you'll make it unchangable 
Or add support for AMXX1.9/1.10

**Comment by mittorn** [comment]
It cannot be unchangeable. Xash id is just fool-proof, not permanent unique identification, but it helps from most of bad players because they are too silly or too lazy to override identification, but not from all

**Comment by a1batross** [comment]
XashID can't be enforced to be static.

Also newer AMXModX versions should work now.
