### ISSUE TITLE
Check library dependency on Win32

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#37]
We need to check if client.dll actually have direct dependency on SDL2. If so, we can assume that this game uses HLSDK2.4 input code and we may enable SDL2 relative mouse mode.

**Comment by a1batross** [comment]
Closing. 

I don't remember the details what SDL2 detection in client.dll will give us and why I thought it isn't working now and how it should.

**Comment by mittorn** [comment]
???

**Comment by a1batross** [comment]
@mittorn а у тебя есть какие-то идеи? Я не помню что должен делать движок и ДОЛЖЕН ЛИ, если SDL2.dll нет в импортах client.dll.
