### ISSUE TITLE
assert failed at ../ref_gl/gl_context.c:126

### ISSUE THREAD

**Issue by daniwenne** [FWGS/xash3d-fwgs#370]
I'm trying to get blueshift to work on my raspberry pi 4 on arch linux. When I try to start a new game, I get `assert failed at ../ref_gl/gl_context.c:126`. Vanilla half-life works just fine.

**Comment by a1batross** [comment]
Can you post whole log?

Can you also confirm, that you downloaded Half-Life: Blue Shift from Steam?

**Comment by daniwenne** [comment]
Here you go: https://pastebin.com/WvJqgTN1
And yes, I downloaded half life: blue shift from steam.

**Comment by a1batross** [comment]
It seems you have broken game data. Redownload it. 

You can use https://github.com/SteamRE/DepotDownloader to download games from steam directly to your RPi.

**Comment by daniwenne** [comment]
> It seems you have broken game data. Redownload it.
> 
> You can use https://github.com/SteamRE/DepotDownloader to download games from steam directly to your RPi.

That was exactly it! Thank you very much!
