### ISSUE TITLE
failing to bulild on Pi4/Retropie

### ISSUE THREAD

**Issue by Exarkuniv** [FWGS/xash3d-fwgs#371]
hello im trying to compile this on my Pi4 running buster 
i used ` git clone --recursive https://github.com/FWGS/xash3d-fwgs` to get the files
then `./waf configure -T release --prefix=/home/pi/half `  to config the waf
then     `./waf `build to start building it 

`../engine/common/net_encode.c:1326:4: warning: cast increases required alignment of target type [-Wcast-align]`
  ` *(float *)((byte *)to + pField->offset ) = flTime;`
    `^`
`../engine/common/net_encode.c:1264:6: error: this condition has identical branches [-Werror=duplicated-branches]`
    `if( bSigned )`
     ` ^`
`cc1: some warnings being treated as errors`

`In file included from /usr/include/SDL2/SDL.h:36,`
                ` from ../common/port.h:151,`
                 `from ../engine/common/common.h:39,`
                 `from ../engine/client/titles.c:16:`
`/usr/include/SDL2/SDL_audio.h:228:9: warning: packed attribute causes inefficient alignment for ‘needed’ [-Wattributes]`
    ` int needed;                 /**< Set to 1 if conversion possible */`

at the end of it when it fails i get this mess

`../engine/client/cl_main.c:2214:48: warning: cast increases required alignment of target type [-Wcast-align]
   if( MSG_GetMaxBytes( &net_message ) >= 4 && *(int *)net_message.pData == -1 )
                                                ^

Waf: Leaving directory `/home/pi/xash3d-fwgs/build'
Build failed
 -> task in 'xash' failed with exit status 1:
        {task 3052310768L: c net_encode.c -> net_encode.c.1.o}
['/usr/bin/gcc', '-g', '-fvisibility=hidden', '-O3', '-fdiagnostics-color=always', '-Werror=return-type', '-Werror=parentheses', '-Werror=vla', '-Werror=tautological-compare', '-Werror=duplicated-cond', '-Werror=duplicated-branches', '-Werror=bool-compare', '-Werror=bool-operation', '-Wcast-align', '-Werror=cast-align=strict', '-Werror=packed', '-Werror=packed-not-aligned', '-Wuninitialized', '-Winit-self', '-Werror=implicit-fallthrough=2', '-Wstrict-aliasing', '-Werror=incompatible-pointer-types', '-Werror=implicit-function-declaration', '-Werror=int-conversion', '-Werror=implicit-int', '-Werror=strict-prototypes', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=declaration-after-statement', '-fPIC', '-Iengine/common', '-I../engine/common', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I/usr/include/SDL2', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_TGMATH_H=1', '-DXASH_BUILD_COMMIT="cb942d7"', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-D_REENTRANT', '../engine/common/net_encode.c', '-c', '-o/home/pi/xash3d-fwgs/build/engine/common/net_encode.c.1.o']`

some people got it to compile but it was at the beginning of last year i think. 
Sorry im not good at programming or i would try more at figuring it out on my own.

thanks for any help

**Comment by a1batross** [comment]
Can you try it again with latest revision?

**Comment by Exarkuniv** [comment]
> 
> 
> Can you try it again with latest revision?

sure thing

**Comment by Exarkuniv** [comment]
still following the same way i posted before

i used git clone --recursive https://github.com/FWGS/xash3d-fwgs to get the files
then ./waf configure -T release --prefix=/home/pi/half to config the waf
then ./waf build to start building it

it still fails at the same spot 

if i use git clone https://github.com/FWGS/xash3d-fwgs
then ./waf configure -T release
then ./waf

it comes up with the same error 
  

Waf: Leaving directory `/home/pi/xash3d-fwgs/build'
Build failed
 -> task in 'xash' failed with exit status 1:
        {task 3053992560L: c net_encode.c -> net_encode.c.1.o}
['/usr/bin/gcc', '-g', '-fvisibility=hidden', '-O3', '-fdiagnostics-color=always', '-Werror=return-type', '-Werror=parentheses', '-Werror=vla', '-Werror=tautological-compare', '-Werror=duplicated-cond', '-Werror=duplicated-branches', '-Werror=bool-compare', '-Werror=bool-operation', '-Wcast-align', '-Werror=cast-align=strict', '-Werror=packed', '-Werror=packed-not-aligned', '-Wuninitialized', '-Winit-self', '-Werror=implicit-fallthrough=2', '-Wstrict-aliasing', '-Werror=incompatible-pointer-types', '-Werror=implicit-function-declaration', '-Werror=int-conversion', '-Werror=implicit-int', '-Werror=strict-prototypes', '-Werror=old-style-declaration', '-Werror=old-style-definition', '-Werror=declaration-after-statement', '-fPIC', '-Iengine/common', '-I../engine/common', '-Iengine/server', '-I../engine/server', '-Iengine/client', '-I../engine/client', '-Iengine/client/vgui', '-I../engine/client/vgui', '-Iengine', '-I../engine', '-Ipublic', '-I../public', '-Icommon', '-I../common', '-Ipm_shared', '-I../pm_shared', '-I/usr/include/SDL2', '-DHAVE_STDINT_H=1', '-DSTDINT_H="stdint.h"', '-DHAVE_TGMATH_H=1', '-DXASH_BUILD_COMMIT="868947c"', '-DXASH_LOW_MEMORY=0', '-DHAVE_SDL2=1', '-DXASH_SDL=2', '-D_REENTRANT', '../engine/common/net_encode.c', '-c', '-o/home/pi/xash3d-fwgs/build/engine/common/net_encode.c.1.o']

**Comment by a1batross** [comment]
Post whole log, on pastebin.com or gist.github.com for example.

**Comment by Exarkuniv** [comment]
Is there a log file I can pull from
I was just copied when I used ./waf-v.

**Comment by Exarkuniv** [comment]
https://gist.github.com/Exarkuniv/d0faa02ef0d921f2d5cc727f19d22c93  without -v

https://gist.github.com/Exarkuniv/9fb9ef873e4615ba5ce025ec33dba6c1  with -v

**Comment by a1batross** [comment]
Can you try once again? 

I don't have ARMv8 with 32-bit OS anywhere around so I can't check it, moreover with kinda old GCC 8.

**Comment by Exarkuniv** [comment]
@a1batross that worked perfectly 
thank you for doing that
