### ISSUE TITLE
How to generate a solution for vs2019

### ISSUE THREAD

**Issue by CeSun** [FWGS/xash3d-fwgs#373]
How to generate a solution for vs2019 by waf，I note that only 2010 and 2008 are supported

**Comment by a1batross** [comment]
I recommend using `waf msvs` which will generate project. It'll call waf for building.

There is another option though `waf msdev`, very experimental and can be unstable. The main feature is that it's pure VS solution and doesn't call waf for build.

**Comment by CeSun** [comment]
Thank you. I tried to use `waf msdev`, it's so good.
