### ISSUE TITLE
What file is "gfx / conchars"？

### ISSUE THREAD

**Issue by CeSun** [FWGS/xash3d-fwgs#374]
I generated the solution through the following script, and compiled the binary file.
`./waf configure -T release --sdl2=./SDL2-2.0.14 --prefix=./build`
`./waf msdev
`
When I run the game, It report an error.  "W_LoadWadFile: couldn't load gfx.wad"

**Comment by a1batross** [comment]
Well, that's a problem of msdev.
It doesn't generate install rules, at all.

So you have to write rules to copy Xash binaries to folder where you also copied "valve" folder from Half-Life.
