### ISSUE TITLE
[MOD: The Specialists] Краш при смене карты с включённым предиктом

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#377]
Sys_Crash: address 77227F26, code C0000005
 0 77227F26 RtlAllocateHeap (ntdll.dll)
 1 77226CDC RtlAllocateHeap (ntdll.dll)
 2 77225C7E RtlAllocateHeap (ntdll.dll)
 3 093EC261 V_CalcRefdef (client.dll)
 4 093EC1FA V_CalcRefdef (client.dll)
 5 093EC1E7 V_CalcRefdef (client.dll)
 6 093BA90C HUD_DrawTransparentTriangles (client.dll)

[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6210231/engine.log)

**Comment by Vladislav4KZ** [comment]
Не крашит когда настроены квары:
cl_lw 0
cl_nopred 1

**Comment by a1batross** [comment]
Так включённым или выключенным? Потому что cl_lw 0/cl_nopred 1 -- это выключенный предикт оружия и физики игрока.

Во втором случае я не уверен, что исправление имеет смысл.

**Comment by Vladislav4KZ** [comment]
@a1batross слово "НЕ" видел? В названии issue я написал что крашит при ВКЛЮЧЁННОМ предикте. А комментарий что НЕ крашит когда ввёл указанные квары, хотя насчёт cl_lw 0 я не уверен, надо будет проверить без него.

**Comment by SNMetamorph** [comment]
Вспомнил: так это ж в самом TS баг с вылетом при смене карты. Я даже писал патчер для фикса этого бага.

**Comment by SNMetamorph** [comment]
Могу тебе в дискорде отправить пропатченную DLL клиента, если надо.

**Comment by Vladislav4KZ** [comment]
Один раз словил краш даже с выключенном предиктом.

cl_lw тыкал чтобы анимации оружия фиксить, и как я понял его вообще не надо трогать, т.к. с cl_nopred 0 анимации оружия исправляются и появляется отдача у оружия

**Comment by SNMetamorph** [comment]
Ну то есть это точно баг клиентской DLL

**Comment by Vladislav4KZ** [comment]
@SNMetamorph ну скинь мне в дискорд. Знаешь же мой ник там?

**Comment by a1batross** [comment]
@Vladislav4KZ сорян, но давай без отрицаний. :)

Эх был бы исходный код от специалистов...

**Comment by SNMetamorph** [comment]
Ну исходники разрабами безвозвратно потеряны, хотя в общем то там ничего хорошего не было.

**Comment by SNMetamorph** [comment]
Это баг самого мода, а именно client.dll, на который даже есть фикс, так что можно закрывать.
