### ISSUE TITLE
[MOD: The Specialists] При удерживании ЛКМ происходит баг с быстрыми выстрелами и сильной отдачей оружия

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#379]
https://streamable.com/k3nesl

**Comment by SNMetamorph** [comment]
Скачай самый последний билд движка, там этот баг пофикшен. И возможно еще что-то с этим связанное тоже пофикшено.

**Comment by Vladislav4KZ** [comment]
@SNMetamorph я как раз и использую последнюю версию движка. При включённом предмете бага нет, при выключенном есть. Но, если играть с включённым предиктом, то движок крашится при смене карты.

**Comment by Vladislav4KZ** [comment]
@SNMetamorph я как раз и использую последнюю версию движка. При включённом предикте бага нет, при выключенном есть. Но, если играть с включённым предиктом, то движок крашится при смене карты.

**Comment by a1batross** [comment]
Я думаю нет никакого смысла поддерживать работу без предикта.

Раньше опция отключения была из-за сломанного предикта в локальной игре, но сейчас с ним почти всё в порядке, вроде только один достаточно критичный баг.

**Comment by SNMetamorph** [comment]
@a1batross что за баг?

**Comment by a1batross** [comment]
@SNMetamorph #353

**Comment by SNMetamorph** [comment]
Пофикшено в коммите https://github.com/FWGS/xash3d-fwgs/commit/ed0ca2b2d2263197b98b3c28e4e75bc475e08f8c, можно закрывать.
