### ISSUE TITLE
Possible crash if custom.hpk was generated by GoldSource

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#38]
Subj.

The custom.hpk was generated by GoldSource previously and when it put to Xash3D, bah, it crashes on validating resources(don't have backtrace).

Reference file. Rename custom.hpk.zip back to custom.hpk. GitHub limitations. 🤷‍♂️ 
[custom.hpk.zip](https://github.com/FWGS/xash3d-fwgs/files/3087118/custom.hpk.zip)

**Comment by unnamed9** [comment]
Исправлено в каком-то из коммитов.
Так что думаю, можно закрыть.
