### ISSUE TITLE
[MOD: The Specialists] Исчезновение HUD при свёртывании и развёртывании игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#381]
Снова появляется только тогда, когда игрок получил урон или умер

**Comment by a1batross** [comment]
Не воспроизводится после обновления SDL2?

**Comment by Vladislav4KZ** [comment]
> Не воспроизводится после обновления SDL2?

При первой попытке восстановления окна игры в полноэкранном режиме после сворачивания, HUD исчезает на долю секунды и возвращается. Но при этом, если были подобраны powerup'ы (замедленное движение, замедленная пауза, удвоение скорострельности), их надписи не возвращаются в верхний левый угол экрана, и их невозможно использовать, пока игрок не умрёт и не подберёт этот powerup снова.

Со второй или третьей попытки восстановления окна после сворачивания, HUD исчезает и не появляется.

**Comment by a1batross** [comment]
В консоли нет ничего про то, что якобы меняется разрешение?

**Comment by Vladislav4KZ** [comment]
И ещё насчёт пауэрапов: их хоть и невозможно использовать после сворачивания-разворачивания игры, но при попытке его использования когда встал на место, где парит моделька другого пауэрапа, игрок подбирает новый пауэрап, выбрасывая при этом старый. Но новый также невозможно использовать, пока не умрёшь и не подберёшь его снова.

**Comment by a1batross** [comment]
Ну и я в оконном режиме конечно же проверял.

**Comment by Vladislav4KZ** [comment]
> В консоли нет ничего про то, что якобы меняется разрешение?

Есть. Всегда, после восстановления окна пишется что-то вроде смены разрешения на 1366x768@69 (родное разрешение монитора, оно же выставлено в самой игре)

Я прямо сейчас игру не запускал, пишу по памяти, т.к. я этот баг проверял буквально вчера.

**Comment by a1batross** [comment]
Да, виновник найден -- SDL2 в фуллскрине отправляет событие смены разрешения. В 6232e288e12831ef39e5d704181873a26ab5731d сделал простую проверку, действительно ли поменялось разрешение и похоже всё исправилось.

Однако, теперь этот баг будет проявляться при растягивании окна. Скорее всего оповещение клиентки о смене разрешения я вовсе удалю, как удостоверюсь что у нас это нигде не используется.

**Comment by Vladislav4KZ** [comment]
@a1batross поставил последний билд. Проблема с исчезновением HUD исчезла, проблема с пауэерапами тоже.

Но в консоли всё ещё остались сообщения о смене разрешения экрана.

**Comment by a1batross** [comment]
Не страшно. До меня только дошло как вся видеоподсистема хреново работает
на винде и я её буду исправлять.

Эту и похожие ишшуи можно закрывать.
