### ISSUE TITLE
Strong network lags after changelevel in multiplayer 

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#383]
TODO add video

**Comment by SNMetamorph** [comment]
Возможно это каким-то образом связано с багом, который происходит когда возобновляешь игру после долгого нахождения в брейкпоинте при отладке.

**Comment by mittorn** [comment]
В старом движке чинил перезапуском дельты

**Comment by SNMetamorph** [comment]
@mittorn а как это сделать? Где этот код находится в старом движке?

**Comment by mittorn** [comment]
Уже не помню

**Comment by SNMetamorph** [comment]
Полагаю что это пофикшено в коммите https://github.com/FWGS/xash3d/commit/79c2ce86a2671e0261b57d8f38c60494ddfc6905
