### ISSUE TITLE
Движок делает искажённые скриншоты

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#384]
При нажатии F5 (команда snapshot) делает поврежденные скриншоты, на разных просмотрщиках или системах этот скриншот выглядит по разному, в Windows на нём белые полосы с дублированием изображения, на Android вообще чёрная картинка

Этот скриншот был сделан в Half-Life на карте boot_camp
![boot_camp_0000.png](https://user-images.githubusercontent.com/22411953/112657220-65351a80-8e7c-11eb-9383-12f433638996.png)

**Comment by Adnan1091** [comment]
''Pressing F5 (snapshot command) takes corrupted screenshots, on different viewers or systems screenshot looks different, on Windows it has white bars with duplicate images, on Android it has a black picture.

This screenshot was taken in Half-Life on the map boot_camp''

**Comment by nekonomicon** [comment]
Вероятней всего все сломал этот коммит:
https://github.com/FWGS/xash3d-fwgs/commit/221a9bab546547f683a531415e21c4d4d0315bd4

Пишет всеравно в RGB24

**Comment by Adnan1091** [comment]
Wait,you know russian?What languages are allowed in issues?

**Comment by a1batross** [comment]
@Adnan1091 every Xash developer knows Russian (it's unintended lol), so we accept issues both in English and Russian.

**Comment by Adnan1091** [comment]
Ah,it would be better if you said earlier i wouldn't have to translate the issue.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/9c8059ea96e3d9047b444024b28f7cb5e720d673
