### ISSUE TITLE
Не удаляются satchel'ы в случае смерти или отключения игрока.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#386]
В случае смерти или отключения игрока, оставленные им satchel'ы остаются, хотя судя по коду hlsdk они должны удаляться.

**Comment by Velaron** [comment]
а satchelfix выставлен в 1?

**Comment by noname946** [comment]
@Velaron Странно, я думал, что оно только фиксит возможность satchel'ами блокировать двери.
Значит, это таки баг самого hlsdk и лечится этим кваром.

**Comment by nekonomicon** [comment]
Да, со стимовскими либами сатчелы остаются только при отключении игрока, а у нас специально сделано так.
