### ISSUE TITLE
[MOD: Counter-Strike & Sven Coop 4.x] Белые искры от пуль

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#388]
В консоли появляется ошибка "Error: UserTracer with color > 12"

**Comment by Vladislav4KZ** [comment]
Также замечено в Sven Coop 4.0 Beta
С той же ошибкой в консоли

**Comment by Vladislav4KZ** [comment]
В Sven Coop запущенном с параметром -gldebug появляются такие ошибки при выстреле
```
[2021:07:24|13:00:12] ^3OpenGL Error:^7 GL_INVALID_OPERATION error generated. Calling glTexEnvi from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
[2021:07:24|13:00:12] ^3OpenGL Error:^7 GL_INVALID_OPERATION error generated. Calling glDisable from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
[2021:07:24|13:00:12] ^3OpenGL Error:^7 GL_INVALID_OPERATION error generated. Calling glDepthMask from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
```

**Comment by Vladislav4KZ** [comment]
```
OpenGL Error: GL_INVALID_OPERATION error generated. Calling glTexEnvi from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
OpenGL Error: GL_INVALID_OPERATION error generated. Calling glDisable from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
OpenGL Error: GL_INVALID_OPERATION error generated. Calling glDepthMask from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
OpenGL Error: GL_INVALID_OPERATION (at D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_rmain.c:924)
```

**Comment by SNMetamorph** [comment]
> 
> 
> ```
> OpenGL Error: GL_INVALID_OPERATION error generated. Calling glTexEnvi from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
> OpenGL Error: GL_INVALID_OPERATION error generated. Calling glDisable from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
> OpenGL Error: GL_INVALID_OPERATION error generated. Calling glDepthMask from the current immediate mode state is invalid. Check glBegin() / glEnd() pairs.
> OpenGL Error: GL_INVALID_OPERATION (at D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_rmain.c:924)
> ```

Судя по коду, там какой то баг внутри игрового DrawTransparentTriangles, т.е. к движку это отношения не имеет по сути дела.

**Comment by Vladislav4KZ** [comment]
> Судя по коду, там какой то баг внутри игрового DrawTransparentTriangles, не очень понятно, имеет ли этот баг отношение к движку.

В Counter-Strike 1.5 таких ошибок нет кстати, появляется только та про которую я писал в первом сообщении, но искры белые

В четвёртых версиях Sven Coop появляются ещё и ошибки OpenGL при выстреле (такие же ошибки были и в Digital Paintball Redux)

**Comment by Vladislav4KZ** [comment]
> такие же ошибки были и в Digital Paintball Redux
> 

И я кажется понял почему, там спрайт краски отображается на чёрном квадрате

**Comment by Vladislav4KZ** [comment]
Только что опять проверял в Counter-Strike. При стрельбе в некоторые поверхности цвет искр нормальный, в остальных случаях белый

**Comment by Vladislav4KZ** [comment]
На голдсурсе при изменении кваров `tracerred` `tracergreen` `tracerblue` меняется цвет искр, а не ксаше нет. Все ещё белые.

**Comment by Vladislav4KZ** [comment]
Оно ещё может выглядеть так: одна искра оранжевая, а все остальные белые.

**Comment by mittorn** [comment]
Баг с треугольниками теоретически можно поправить проверяя пары TriBegin/TriEnd

**Comment by SNMetamorph** [comment]
#1810 решает эту проблему, но желательно всё равно протестировать

**Comment by Vladislav4KZ** [comment]
Проверил в Counter-Strike 1.5, бага с белыми искрами больше нет на последнем билде движка.
