### ISSUE TITLE
[MOD: The Specialists] Отсутствует в списке карта ctb_deadheat

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#389]
Эта карта режима "Capture the Briefcase (Захват чемодана)" её можно загрузить через консоль, а в меню её нет. Остальные карты видно в списке

**Comment by a1batross** [comment]
Список зависит от того, какая энтити была прописана в liblist.gam.

Но Ксаш его конвертирует в gameinfo.txt. Конвертер мог заглючить отчего-то.
Покажи liblist.gam, сгенерированный gameinfo.txt и саму карту.

**Comment by Vladislav4KZ** [comment]
@a1batross сделал энтпатч этой карты и понял, что в этой карте для спавна игроков используется info_player_team1 и info_player_team2, а в gameinfo.txt и liblist.gam прописано "info_player_deathmatch" для мультиплеера

**Comment by a1batross** [comment]
Интересно что делает голдсорс в этом случае.

**Comment by nekonomicon** [comment]
Может быть если GoldSource не находит sp_entity и mp_entity, то считает карту мультиплеерной или общего назначения?

**Comment by Vladislav4KZ** [comment]
> Может быть если GoldSource не находит sp_entity и mp_entity, то считает карту мультиплеерной или общего назначения?

Синглплеерный спавн "info_player_start" есть на той карте. И в GoldSource её можно выбрать из списка мультиплеерных арт

**Comment by nekonomicon** [comment]
Вариант рипентом поудалять\подобавлять такие точки спауна и посмотреть, что будет.
Вообще в Opposing Force изначально планировали добавить кооперативный режим, и в обычном hlsdk есть зачатки + соответствующий квар в движке, так что может быть и карты с sp_entity должны быть пригодны для мультиплейера.

**Comment by Vladislav4KZ** [comment]
> Вариант рипентом поудалять\подобавлять такие точки спауна и посмотреть, что будет.
Удалил я эти точки спавна, карта со списка в GoldSource не исчезла.

И ради эксперимента, скопировал синглплеерную карту из Half-Life в мод, она тоже появляется среди мультиплеерных карт

**Comment by nekonomicon** [comment]
Тогда может быть и так, что mpentity и spentity - остались в конфигах с ранних версий, а в движке в данный момент не проверяются вообще.

**Comment by Vladislav4KZ** [comment]
Но в самом Half-Life на GS же не видно синглплеерных карт среди мультиплеерных

**Comment by nekonomicon** [comment]
Может быть и так, что карты каким-то образом фильтруются, но только для игр Valve.

**Comment by a1batross** [comment]
Разобрался. Всё это часть GameUI.dll в голдсорсе.

Поиск там... в стиле Valve.
1. Исключается всё что содержит подстроку из mpfilter из liblist.gam. 
2. Для Half-Life и Opposing Force просто исключается набор карт:
`(mapname[0] == 'c' || mapname[0] == 't') && mapname[2] == 'a' && mapname[1] >= '0' && mapname[1] <= '5'`
`mapname[0] == 'o' && mapname[1] == 'f'`

И что с этим делать? mpfilter я конечно добавлю, но делать костыль для HL и OF не сильно хочется.
Можно попробовать расширить mpfilter, чтобы он считался за регулярку и для HL и OF добавлять это поле движком.

Энтити в расчёт не берутся.

**Comment by Vladislav4KZ** [comment]
Также запустил BrainBread на ксаше. В списке нашёл всего лишь одну карту! А их в игре много

**Comment by nekonomicon** [comment]
Еще актуально?

**Comment by Vladislav4KZ** [comment]
> Еще актуально?

Да

**Comment by a1batross** [comment]
Этот мод не имеет mpfilter, но зато есть некорректно выставленный mpentity.

Сделал такую вещь. Если мод заявляет о себе как только мультиплеерном, то все его карты считаются за валидные.

4107bd4e0fdbf1a6b0f031739afa92ea7fc6754f
