### ISSUE TITLE
New library naming scheme proposal

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#39]
I propose a new library naming scheme, which will allow to distribute mods and games in single archive to different operating systems and CPUs: 

Legend:
* $os -- Q_buildos() return value, in lower case.
* $arch -- Q_buildarch() return value, in lower case.
* $ext -- OS-specific extension: dll, so, dylib, etc.

The scheme will be:

1. Client library: 
* ```client.$ext``` for **Win/Lin/Mac** with **x86**.
* ```client_$arch.$ext``` for **Win/Lin/Mac** with **NON-x86**.
* ```client_$os_$arch.$ext``` for everything else.

2. Menu library: 
* ```menu.$ext``` for **Win/Lin/Mac** with **x86**.
* ```menu_$arch.$ext``` for **Win/Lin/Mac** with **NON-x86**.
* ```menu_$os_$arch.$ext``` for everything else.

3. Server library:
* On  **Win/Lin/Mac** with **x86**, it **MUST** use the raw gamedll name for corresponding OS field from `gameinfo.txt`.
* On **Win/Lin/Mac** with **NON-x86**, it **MUST** use the raw gamedll name for corresponding OS field from `gameinfo.txt`, but append ```_$arch``` before file extension. Like: ```hl_amd64.so``` or ```cs_e2k.so```.
* On everything else, it must use gamedll name from ```gamedll_linux``` field, but append ```_$os_$arch``` before file extension. Like: ```hl_haiku_amd64.so``` or ```cs_freebsd_armhf.so```. 
Why ```gamedll_linux``` and not ```gamedll```? Because it looks more logic that way, most operating systems are *nix-like and share code with Linux, rather than Windows. 
4. Refresh library: not needed, as RefAPI is not stable and it's not intended to distribute with mods.

For any libraries distributed **with** engine, naming scheme should be used more convenient for OS port. 

Issue #0. Inconsistency between ABI and Q_buildarch.
Resolution: Change Q_buildarch return value to use Debian-styled architectures list: https://www.debian.org/ports/, which includes a special naming for big/little-endian and hard/soft-float ARM.

Issue #1: Build-system integration.
Resolution: extend MACRO_TO_DEST_CPU and MACRO_TO_DESTOS from Waf: https://gitlab.com/ita1024/waf/blob/master/waflib/Tools/c_config.py#L1002, if needed.

**Comment by a1batross** [comment]
Issue #2(related to #0): 
Which ARM flavours we actually need to handle? 

Following Debian-styled arch names, it will be like this:
armhf -- vfp, i.e. runs only on armv7a and has hard-float ABI.
armel -- no float acceleration, i.e. runs even on armv4t. **Do we need this?**

Maybe it would be enough only maintain hard-/soft-float ABI?

**Comment by a1batross** [comment]
Resolution:
Define 5 different kinds of ARM code: 
* armv4l.
* armv5l: mapped to Android's armeabi
* armv6l.
* armv7l:  mapped to Android's armeabi-v7a
* armhf:  mapped to Android's armeabi-v7a-hard

~I hope 32-bit ARM would die as soon as possible~

**Comment by mittorn** [comment]
armv?l
armv?hf

**Comment by a1batross** [comment]
That's an idea, really.

**Comment by a1batross** [comment]
Updated.

**Comment by a1batross** [comment]
Implemented in the latest commits https://github.com/FWGS/xash3d-fwgs/commit/ec18dd95353f8308b5583263e106c7474f899e62 and https://github.com/FWGS/xash3d-fwgs/commit/89a3fd632316cf7dbcbe40a7e69e1aea446b89ae.

**Comment by a1batross** [comment]
Integration is fully done and it seems working ok.
