### ISSUE TITLE
Не работают команды banid, addip, listid и listip.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#390]
На новых серверах не работают команды banid, addip, listid и listip, даже хелпер по banid и addip не вызывается.

**Comment by a1batross** [comment]
Коммит https://github.com/FWGS/xash3d-fwgs/commit/9c9953bb60e1414bd2849b647a603245850909a1 исправляет writeid и writeip.

Но воспроизвести именно эту проблему я не могу. У меня всё вызывается.

**Comment by a1batross** [comment]
Также https://github.com/FWGS/xash3d-fwgs/commit/c62db950f190d2059dca45ac88f3c53439e304f3 реализует редирект, может быть поэтому ты не видел выхлопа этих команд.

**Comment by noname946** [comment]
@a1batross Неа, banid и addip не работали именно при попытке их вызвать из самой консоли сервера.
Но я попробую протестировать изменения после этих новых коммитов и доложу.

**Comment by noname946** [comment]
@a1batross listid и listip всё-ещё ничего не возвращают.
banid не работает, если указывать UserID, ввиде "#0".
addip заработал

**Comment by a1batross** [comment]
banid и не будет работать, так как идентификатор просто не пересылается на сервер. XashID требует переработки, возможно, поэтому пока не будем торопиться с ним.

Что за консоль сервера такая? У меня всё работает.
```
listid
[01:31:57] id ban list
[01:31:57] -----------
listip
[01:32:01] ip ban list
[01:32:01] -----------
addip 60 192.168.1.102
listip
[01:39:21] ip ban list
[01:39:21] -----------
[01:39:21] 192.168.1.102 255.255.255.255 expries in 59.271025 minutes
```

addip работает, я проверил.

**Comment by a1batross** [comment]
Обманул. XashID передается, но ключ был переименован с i на uuid.

**Comment by a1batross** [comment]
XashID должен быть исправлен после этого коммита https://github.com/FWGS/xash3d-fwgs/commit/f5e400de69339ec2f998641727e56757e9909135

**Comment by noname946** [comment]
@a1batross Исправился clientuseragent, спасибо.
banid по XashID теперь работает, но указание через UserID всё-ещё игноируется.
А вот что делать с listid и listip я уже не знаю, оно ибо даже через rcon ничего не выдаёт

**Comment by a1batross** [comment]
Ах да, забыл сказать.

userid начинаются не с 0, а с 1.

**Comment by noname946** [comment]
@a1batross Неа, тоже не работает.

**Comment by a1batross** [comment]
Использование userid пока не поддерживается, так как чревато из-за натуры XashID.
