### ISSUE TITLE
[Windows] Не приглушается звук игры когда она свёрнута

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#391]
Даже когда включена настройка "Mute when inactive"

**Comment by a1batross** [comment]
Платформа.

Когда же ты научишься писать сразу всё...

**Comment by Vladislav4KZ** [comment]
Windows

**Comment by Vladislav4KZ** [comment]
В оконном режиме звук игры глушится, а в полноэкранном нет

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/6232e288e12831ef39e5d704181873a26ab5731d
