### ISSUE TITLE
Не блокируется действия кнопок в VGUI меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#393]
Должны работать только цифры, но в ксаше если выбираешь какой-то пункт меню, то игрок стреляет. И при нажатии WASD игрок двигается когда открыто меню.

На всякий случай: Windows 10 20H2, чтобы опять не спрашивали

**Comment by SNMetamorph** [comment]
Такое чувство, что баг где-то в месте где движок вызывает клиентскую функцию HUD_KeyInput, и по идее он должен в зависимости от возвращенного значения либо пропускать ивент в движок, либо нет.

**Comment by a1batross** [comment]
Fixed with #470
