### ISSUE TITLE
[Android] [MOD: Team Fortress Classic] При нажатии любой кнопки в VGUI меню появляется клавиатура

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#394]
![Screenshot_20210328-144355.png](https://user-images.githubusercontent.com/22411953/112746928-0d112c00-8fd4-11eb-827d-26faafd31fa1.png)

**Comment by Velaron** [comment]
Не исключено что это у меня, всё таки что сам vgui реверснутый, что клиент, что неизвестно как я его прикрутил.

**Comment by mittorn** [comment]
Это ожидаемое поведение, иначе не работал бы нормально ввод на полях ввода в vgui там где экранной клавиатуры нет
можешь попытаться переписать vgui_support так чтобы он определял поля ввода или просто отключить там это при включенном таче

**Comment by a1batross** [comment]
На самом деле не очень, потому что клавиатура теперь не появится в вгуи вообще. 

Пока вгуи как-то не вызовет из саппорта нужную функцию.
