### ISSUE TITLE
При движении вверх по неровным поверхностям камера дёргается

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#395]
https://streamable.com/7k1vp9
https://streamable.com/o7gyit

**Comment by SNMetamorph** [comment]
Да, тоже замечал такое, на последнем билде.

**Comment by Vladislav4KZ** [comment]
За последнее время были всякие фиксы мультиплеера.
И на последнем билде дёрганий нет.
Поэтому эту issue закрываю.

**Comment by Vladislav4KZ** [comment]
А не, ещё раз поиграл в мультиплеере. Этот баг все ещё актуален. Но проявляется не на всех серверах

**Comment by SNMetamorph** [comment]
Я вангую что он проявляется только на старых серверах? Ну т.е. на тех что на 0.19.x версии

**Comment by Vladislav4KZ** [comment]
А разве есть сервера на новом движке?

Максимум кастомный билд 0.19.x версии

Это я про сервера для Half-Life говорю

**Comment by a1batross** [comment]
Есть. В меню они подсвечиваются полным цветом, легаси сервера имеют более приглушенный цвет + колоркоды игнорируются.

**Comment by Vladislav4KZ** [comment]
Насчёт цветности текста в названиях я знаю, просто на те серверы которые "цветные", можно подключаться и со старого движка.

А я помню что серверы запущенные на новом движке, не видны в списке на старом, и при попытке подключения по ip выдаст ошибку о несовместимом протоколе

**Comment by a1batross** [comment]
Ни на старых, ни на новых серверах ошибка не воспроизводится.

Возможно, она связана с тем насколько долго работает сервер. Пока закрою. Если вдруг кто сможет воспроизвести, можно попробовать записать демку.
