### ISSUE TITLE
[MOD: The Specialists] Чёрная модель игрока в режиме от третьего лица

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#397]
GoldSource (модель подсвечена):
![Снимок экрана (29).png](https://user-images.githubusercontent.com/22411953/112751103-ff68a000-8fed-11eb-8bac-9a01215e2684.png)

Xash3D FWGS 0.20.1 (модель не подсвечена):
![ts_bikini_0000.png](https://user-images.githubusercontent.com/22411953/112751120-1b6c4180-8fee-11eb-8de6-1748cefc6d62.png)

**Comment by Vladislav4KZ** [comment]
Даже заметил что прицел исчез в ксаше, думал что так и должно быть

**Comment by Vladislav4KZ** [comment]
Заметил что при свёртывании и развёртывании игры модель подсвечивается, но когда умираешь она снова становится чёрной
https://streamable.com/jnotnn

**Comment by SNMetamorph** [comment]
Возможно это пофикшено в коммите https://github.com/FWGS/xash3d-fwgs/commit/4f31d7504a85d9e9b86c64b3bda75753e385ca81, но надо протестировать.

**Comment by Vladislav4KZ** [comment]
> Возможно это пофикшено в коммите https://github.com/FWGS/xash3d-fwgs/commit/4f31d7504a85d9e9b86c64b3bda75753e385ca81, но надо протестировать.

Нет, не пофикшено

**Comment by SNMetamorph** [comment]
Вообще, учитывая как выглядят поверапы, похоже сломано освещение студиомоделей, с чем и связан этот баг.

**Comment by Vladislav4KZ** [comment]
Также заметил, что в этом моде отображается белый значок голосового чата. После сворачивания-разворачивания игры, значок становится оранжевым.

**Comment by Vladislav4KZ** [comment]
После разворачивания игры, когда игрок умирает или получает урон, игрок снова становится чёрным и появляется HUD, но значок голосового чата остаётся оранжевым.

**Comment by Vladislav4KZ** [comment]
Когда исчезает HUD после сворачивания-разворачивания игры, невозможно сменить оружие.

**Comment by a1batross** [comment]
@Vladislav4KZ заводи отдельные ишшью. Мы не экономим место на серваках майкрософта :)

Кажется знаю в чем проблема. Воспроизводится если выставить `r_lighting_extended 0`?

**Comment by Vladislav4KZ** [comment]
> Кажется знаю в чем проблема. Воспроизводится если выставить `r_lighting_extended 0`?

Да, с кваром `r_lighting_extended 0` баг также воспроизводится.

**Comment by a1batross** [comment]
А жаль!

**Comment by a1batross** [comment]
Проверил.

На модели игрока стоит рендермод TransColor:
```
	if( g_studio.numlocallights )
		R_LightLambert( g_studio.lightpos[ptricmds[0]], pstudionorms[ptricmds[1]], lv, color );
	else
	{
		if( RI.currententity->curstate.rendermode == kRenderTransColor )
			VectorCopy(  (byte*)&RI.currententity->curstate.rendercolor, color );
		else
		{
			color[0] = lv[0] * 255;
			color[1] = lv[1] * 255;
			color[2] = lv[2] * 255;
		}
	}
```

Имхо тут не должно быть этой сложной проверки на TransColor. Но стоит взглянуть поподробнее, так как это может где-то сломать применение цвета на студиомодели. Хотя голдсорс в первом приближении только на глоушеллы читает rendercolor.

**Comment by a1batross** [comment]
Fixed in 74ce7e9b
