### ISSUE TITLE
[MOD: Sven Coop 3.0] Ошибка Host_Error: ED_LoadFromFile: found · when expecting { при загрузке некоторых карт

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#398]
В Sven Coop 3.0 при загрузке некоторых карт (hplanet, crisis2) крашится сервер с ошибкой в консоли Host_Error: ED_LoadFromFile: found · when expecting {

[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6217407/engine.log)

**Comment by nekonomicon** [comment]
Проблема еще актуальна?

**Comment by Vladislav4KZ** [comment]
> Проблема еще актуальна?

Не могу проверить, Sven Coop 3.0 перестал запускаться

**Comment by Vladislav4KZ** [comment]
А не. запускается. Решил проблему скопировав fmod.dll с папки Sven Coop 3.0 в корневую директорию движка.
Там какой-то мод заменил fmod.dll

**Comment by Vladislav4KZ** [comment]
Проблема всё ещё актуальна. Указанные карты не запускаются на последнем билде ксаша.

**Comment by a1batross** [comment]
Проверил. Голдсорс выдает такую же ошибку на hplanet: `Host_Error: ED_LoadFromFile: found`. Даже печатать дальше не хочет.

В карте похоже какой-то мусор в конце entities.

**Comment by a1batross** [comment]
WON версия однако загрузила без проблем.

**Comment by Vladislav4KZ** [comment]
@a1batross у меня и самый последний билд голдсурса без проблем запускал эту карту.

Или у тебя в консоли появилась эта ошибка, но при этом карта запустилась?

**Comment by a1batross** [comment]
У меня нет виндового голдсорса кроме WON рядом. Надо выкачать. :)

Поэтому проверял просто подкинув карту в файлы халфы.

А текущий голдсорс просто выдает предупреждение, но грузит карту? Может быть нам здесь тоже стоит убрать Host_Error тогда. Не очень хочу вставлять костыль в загрузчик, отрезающий мусор.

**Comment by a1batross** [comment]
```
      if (com_token[0] != '{') {
        Host_Error("ED_LoadFromFile: found %s when expecting {",com_token);
      }
```

Таки нет, это просто Host_Error.

**Comment by a1batross** [comment]
Вердикт пока такой: карты скорее всего изначально битые.

Я могу написать простенькую программу фиксилку, вставить костыль в движок или просто закрыть ишшую как wontfix.

**Comment by Vladislav4KZ** [comment]
Наврал, на последнем билде голдсурса данная карта в Sven Coop 3.0 не запускается.

**Comment by Vladislav4KZ** [comment]
На последнем билде GoldSource, Sven Coop 3.0 вообще отказывается нормально работать. Крашится на всех картах.

**Comment by Qwertyus3D** [comment]
Карта hplanet начинает работать после простого пересохранения в BSPGuy, другую карту не проверял.

**Comment by Qwertyus3D** [comment]
Я так понял, ошибка связана с тем, что указанный символ использовался в карте в конце энтпатча, где его не должно быть. Вполне возможно, что это пережиток старого движка Халфы, ещё до версии 1.1.0.0. Возможно, тогда такие символы создавались компилятором, и движок их спокойно жевал.

**Comment by a1batross** [comment]
Можно было бы сделать детальный разбор почему старый движок халфы такое жевал, благо у меня есть билд где эти карты грузятся.

Но заморачиваться совершенно не хочется. Тем более, что это ни на что не влияет и исправляется обычным пересохранением карты, или небольшой правкой в HEX редакторе :)

**Comment by Qwertyus3D** [comment]
В общем, проверил, все карты Свен-Кооп 3.0 после пересохранения работают.
