### ISSUE TITLE
[MOD: Counter-Strike 1.5] Краш игры с ботами PODBot 2.5

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#399]
Когда запускаешь сервер без ботов, игра работает. Когда запускаешь с ботами, крашится после выбора команды с ошибкой `assert failed at c:\users\travis\build\fwgs\xash3d-fwgs\engine\server\sv_game.c:4153`
В старом движке боты работают нормально

[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6220717/engine.log)

**Comment by a1batross** [comment]
Must be fixed in ca3544d5.

**Comment by Vladislav4KZ** [comment]
Нет, это не пофикшено.

Теперь игра закрывается с ошибкой
```
assert failed at D:\a\xash3d-fwgs\xash3d-fwgs\engine\server\sv_game.c:4158
```

**Comment by Vladislav4KZ** [comment]
Эта ошибка появилась с ботами YaPB 4.2.623. Они появляются в игре, начинается раунд не успеют двинутся как вылезает эта ошибка.

А PODbot 2.5 вообще не работает. Ошибку движок не выдает, но пишется что нет вэйпоинтов хотя они есть. Также с PODBot я не могу выбрать команду вообще, застреваю в наблюдателях без интерфейса
