### ISSUE TITLE
Список багов в некоторых модах.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#4]
Дубль https://github.com/FWGS/xash3d/issues/323
Общее:
- ~Не отображается Muzzleflash у Alien Grunt'ов(спрайт muz4.spr). Это немного затрудняет прохождение Afraid of Monsters: Director's Cut, так как в этом моде Alien Grunt'ы имеют прозрачные модели, а при стрельбе из hivehand должна отображаться [улыбающаяся физиономия](http://afraidofmonsters.wikia.com/wiki/Bleeding_Specter).~(исправлено)
- ~Отображается Muzzleflash на Holster-анимации оружия.~(Исправлено)
- ~[Не работает на клиенте(с тач-управлением проблема не воспроизводится)](https://cs-mapping.com.ua/forum/showpost.php?p=924687&postcount=115)~(исправлено)
- ~Монстры не видят сквозь окна, вроде и не фатально, но ломает прохождение Azure Sheep на карте asmap04c(ученый не может открыть дверь, потому что не видит игрока).~(исправлено)
- ~Монстров на движущихся платформах трясет во все стороны.~
- ~Не отображаются прозрачные кастомные декали(Например из trusty pack или мода Echoes)~(исправлено, но возможно проблема VBO)
- ~Не игнорируется bottom-left-ориентация tga-текстур.~(исправлено) 
- He отображается белый текст в меню в некоторых модах(только на Android).

Adrenaline Gamer:
- ~Красный флаг имеет синюю текстуру.~
- Мерцание текстуры ctf_base на карте agctf_bootcamp под некоторым углом обзора.

Battlegrounds:
- ~[Вылет](https://cs-mapping.com.ua/forum/showpost.php?p=919786&postcount=310)~

Big Scientists:
- ~Не отображаются большие модели под некоторым углом обзора.~(Исправлено)

Deathmatch Classic:
- Неверный размер хуллов, из-за чего модели игроков проваливаются ногами в текстуры и возможны застревания на спауне.
- ~При падении в лаву игрок не получает урон, пока в ней не движется.~(исправлено)
- ~Не отображается анимация lightninggun'а при cl_lw 1.~(исправлено)
- ~Не отображается панель выбора оружия при cl_lw 0.~(не баг)

Decay:
- ~Не отображаются анимации у лап вортигонта при cl_lw 1.~

Echoes:
- ~Срабатывает assert на карте echoes21 при включеном VBO.~(связан с VBO)

Sweet Half-Life:
- ~Вылет при стрельбе из плазмагана(в движке имеется assert для этого бага)~(исправлено)

They Hunger:
- ~На загрузке сохранений глушитель у глока появляется не сразу(похоже GoldSrc имеет ту же проблему, но репредиктинг в оригинальном xash3d build 3598+ решает проблему)~(возможно не баг)
- ~На загрузке сохранений пропадает зеленый фильтр у прицела снайперской винтовки.~(возможно не баг)
- ~Не раскрывается пламя у огнемета(в оригинальном They Hunger и моем декомпиле, в версии от malortie оно реализано не через TE_PROJECTILE)~(исправлено)
- На одной из карт поезд проходит сквозь цистерны
- На одной из последних карт вертолет, который должен обстреливать зомби, просто висит в воздухе.

ThreeWave CTF:
- Не отображается фон из fallback_dir(воспроизводится только на android)

Residual Life:
- ~Зависает скрипт [в этом месте](https://m.youtube.com/watch?v=fdncoLqmlZo&feature=youtu.be&t=763) и охранник с зомби не двигаются пока игрок не убьет зомби.~(исправлено)

Poke646 и Poke646: Vendetta:
- ~Из-за обнуления таймера глобального времени отрисовки HUD при смене карты, HUD может длительное время не отрисовываться.~(не связано с движком)
- ~Не отображается прицел у арбалета( Не отрабатывает вызов HUD_DrawTransparentTriangles ).~(не связано с движком)
- ~Заедание звука открытия двери на карте po_intro в Poke646.~(исправлено)

Blue Shift:
- ~[Баг с водой](https://github.com/FWGS/xash3d/issues/354)~(связан с VBO)

Cleaner's Adventures:
- ~[Баг с водой](https://github.com/FWGS/xash3d/issues/354)~(связан с VBO)
- ~Отображение черно-розовых квадратов вместо текстур при частых загрузках сохранений~(исправлено)

Top-Down:
- ~Вместо модели player в синглплеере используется модель gordon или любая другая модель, выбранная для мультиплеера.~(воспроизводится только с включенным режимом разработчика)
- ~Не меняется body-модель у модели игрока~(воспроизводится только с включенным режимом разработчика)

Opposing Force:
 - ~Черный экран при переходе с карты of0a0 на карту of1a1~

**Comment by Vladislav4KZ** [comment]
> Battlegrounds:
> - [Вылет](https://cs-mapping.com.ua/forum/showpost.php?p=919786&postcount=310)

Тестировал этот мод. Вылетов не заметил ни при запуске карты, ни при выстреле

**Comment by Vladislav4KZ** [comment]
> Opposing Force:

> Черный экран при переходе с карты of0a0 на карту of1a1

Проверил, чёрного экрана нет, переход уровней прошёл нормально

**Comment by Vladislav4KZ** [comment]
> Sweet Half-Life:

> •Вылет при стрельбе из плазмагана в движке имеется assert этого бага)

Проверил на последнем тестовом ксаше, вылета при стрельбе из плазмагана нет.

**Comment by Vladislav4KZ** [comment]
> Decay:
>
> Не отображаются анимации у лап вортигонта при cl_lw 1.

Такого бага не наблюдаю даже с cl_lw 1.

**Comment by Vladislav4KZ** [comment]
> Residual Life:
> 
> * Зависает скрипт [в этом месте](https://m.youtube.com/watch?v=fdncoLqmlZo&feature=youtu.be&t=763) и охранник с зомби не двигаются пока игрок не убьет зомби.

Проверил на последнем билде ксаша, такого бага нет.

> Cleaner's Adventures:
> 
> * Отображение черно-розовых квадратов вместо текстур при частых загрузках сохранений

Никогда не видел такого бага. Попробовал специально часто загружать сохранения и никаких чёрно-розовых квадратов не было.

**Comment by Vladislav4KZ** [comment]
> * Монстры не видят сквозь окна, вроде и не фатально, но ломает прохождение Azure Sheep на карте asmap04c(ученый не может открыть дверь, потому что не видит игрока).

На последнем билде ксаша такого бага нет.

**Comment by Vladislav4KZ** [comment]
> * Не отображаются прозрачные кастомные декали(Например из trusty pack или мода Echoes)

Исправлено в новом движке

**Comment by Vladislav4KZ** [comment]
> * На одной из последних карт вертолет, который должен обстреливать зомби, просто висит в воздухе.

Это карта ``they54`` где игрок должен убить зомби-босса с протезами вместо руки и ноги?

**Comment by nekonomicon** [comment]
Нет, на другой карте на мосту.

**Comment by a1batross** [comment]
>Deathmatch Classic:
>Не отображается панель выбора оружия при cl_lw 0.

Биты оружия там передаются только с cl_lw 1. Не баг, на голдсорсе происходит то же самое.

**Comment by a1batross** [comment]
Зачеркнул "Монстров на движущихся платформах трясет во все стороны.". 

Квар cl_fixmodelinterpolationartifacts из HL25 исправляет эту проблему, по дефолту он как раз включен.

**Comment by a1batross** [comment]
>Красный флаг имеет синюю текстуру.

Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/9d3949a94833c6346094956fe20452ba51f6c423

**Comment by a1batross** [comment]
>Мерцание текстуры ctf_base на карте agctf_bootcamp под некоторым углом обзора.

У меня не воспроизводится. Что ты тут имел ввиду, @nekonomicon?

>He отображается белый текст в меню в некоторых модах(только на Android).
>Не отображается фон из fallback_dir(воспроизводится только на android)

Это актуально ещё? Если относится к ref_gles1 (который nanogl), то вроде у @mittorn были планы на его удаление. 
Про фон тоже интересно, вполне возможно какие-то из фиксов ФС уже должны были это исправить.

>На одной из карт поезд проходит сквозь цистерны
>На одной из последних карт вертолет, который должен обстреливать зомби, просто висит в воздухе.

Было бы хорошо знать какие карты...

**Comment by nekonomicon** [comment]
Наверно все это проверю в ближайшее время, может и не актуально уже.

**Comment by Vladislav4KZ** [comment]
> Echoes:
>
>Срабатывает assert на карте echoes21 при включеном VBO.(связан с VBO)


Не воспроизводится на последней сборке движка с включённым VBO.

**Comment by a1batross** [comment]
Если что-то из этого списка актуально, лучше завести по новой ишшуе на баг.

**Comment by a1batross** [comment]
>Неверный размер хуллов, из-за чего модели игроков проваливаются ногами в текстуры и возможны застревания на спауне.

https://github.com/FWGS/xash3d-fwgs/commit/7a469fb481d9bdb62923868f1acdff65d9058e6e
