### ISSUE TITLE
[MOD: Sven Coop 4.6 - 4.8] Краш при запуске сервера

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#400]
![Снимок экрана 2021-03-29 154532](https://user-images.githubusercontent.com/22411953/112819154-17035f80-90a6-11eb-8e6b-ff4eff9e1426.png)
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6220817/engine.log)

Бывает и такая ошибка
![Снимок экрана 2021-03-29 155102](https://user-images.githubusercontent.com/22411953/112819757-b9234780-90a6-11eb-9468-fb19f5946821.png)
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/6220856/engine.log)

Windows 10 Pro x64 20H2
Последняя тестовая версия Xash3D FWGS коммит: f5e400d

**Comment by Vladislav4KZ** [comment]
Версии Sven Coop 4.6 и 4.7 также крашатся при запуске сервера, рабочие версии это Sven Coop 3.0 - 4.5 (Версии ниже 3.0 не проверял)

**Comment by lewa-j** [comment]
С этими версиями идёт свой движок или они работают на оригинальном GoldSrc от Half-Life?

**Comment by Vladislav4KZ** [comment]
> С этими версиями идёт свой движок или они работают на оригинальном GoldSrc от Half-Life?

Ну так если это мод то конечно он использует оригинальный GoldSource из Half-Life

Свой движок использует только Sven Coop 5.0

**Comment by Vladislav4KZ** [comment]
Также проверил версии с Sven Coop 0.8 по Sven Coop 2.1, работают только Sven Coop от 0.8 до 1.9 (Sven Coop 0.8 это даже не мод, а карта для Half-Life, а Sven Coop 1.0 использует оригинальные client.dll и hl.dll с Half-Life)

А версии 2.0 и 2.1 не запускаются (ошибка client.dll)

**Comment by Vladislav4KZ** [comment]
Также версии 2.0 и 2.1 не запускаются на последнем стимовском билде Half-Life, там уже ошибка связана с fmod.dll

**Comment by mittorn** [comment]
Моды с fmod не нужны

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/585ec5ce893002c9a2c547043c820214046f5a97 

Исправляет работу client.dll в Sven-Coop 4.8.

Сервер все ещё крашится на некоторых картах.

**Comment by a1batross** [comment]
Отреверсив небольшой кусок сервера, выявил баг в 4.8.

Если на карте есть сущность, унаследованная от `CBaseMonster` и вызывающая `CBaseMonster::MonsterInit`, то скорее всего произойдёт краш в функции `GetActivitySequenceName` (благо, имена всех функций присутствуют в Linux версии сервера). 

`CBaseMonster::MonsterInit` сбрасбывает pev->gaitsequence в значение 255, а `GetActivitySequenceName` не проверяет границы сиквенсов в модели.

Почему же это не крашится под голдсорсом? Есть предположение что размер буфера выделенного под студиомодель сильно больше, чем сама модель. (и это действительно так, если верить [ReHLDS](https://github.com/dreamstalker/rehlds/blob/9c1e84328ebcdb47ea83c157dd8c7e493dda28a6/rehlds/engine/l_studio.cpp#L54))

Частично баг исправляет удаление логики усечения загруженной модели https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/mod_studio.c#L916-L918, но выделенный размер явно меньше того, чем аллоцирует голдсорс (опять же, если верить rehlds).

Есть другой вариант конечно -- пропатчить бинарь hl.dll, заменив в нём выставление gaitsequence в 255 на, например, 0. Но возможно это тогда что-то сломает в логике сервера.

**Comment by nekonomicon** [comment]
Мне кажется проще сделать отключение усечения модели для одной популярной платформы, либо положиться на `bugcomp`.

**Comment by nekonomicon** [comment]
> Также версии 2.0 и 2.1 не запускаются на последнем стимовском билде Half-Life, там уже ошибка связана с fmod.dll

Там fmod используется на стороне сервера для прекэширования звуков, сорцы мода `Overturn` можно посмотреть как пример, не знаю правда работает ли этот мод под ксашем.

**Comment by a1batross** [comment]
Скорее всего я уберу усечение. Оно как-то не консистентно применяется, сами
можете посмотреть в исходниках.
