### ISSUE TITLE
[MOD: Team Fortress Classic] Очень странно сломан лазер у снайперской винтовки

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#404]
Если выстрелить снайперкой во время движения, лазер будет светиться при зажатии ЛКМ даже на ходу, хотя светиться он должен только при низкой скорости игрока (практически стоя на месте).

Исправляется двумя способами которые я нашёл:
1. Выстрелить ещё раз уже не двигая игроком.
2. Смениться на другое оружие и обратно.

**Comment by SNMetamorph** [comment]
А как он там вообще реализован? Через темпэнтити? Я просто сталкивался со сьехавшими лучами у трипмин, может быть, это связанные вещи.

**Comment by Velaron** [comment]
тут именно какая-то проблема с предиктингом оружия а не самой энтитей лазера

**Comment by Velaron** [comment]
fixed
