### ISSUE TITLE
[MOD: BrainBread] Запускается только одна единственная карта

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#405]
Запускается только та карта которая есть в списке. Остальные не видно, а они есть и много!

При их загрузке через консоль происходит ошибка якобы сервер полон

В liblist.gam mpentity указан как bb_player_spawn

**Comment by Vladislav4KZ** [comment]
В остальных картах вытащил информацию о энтитях через ripent, и там используются точки спавна с такси названиями: bb_spawn_zombie и bb_spawn_player (в liblist.gam указано немного иначе, bb_player_spawn)

**Comment by Vladislav4KZ** [comment]
Когда я отредактировал gameinfo.txt и заменил  mpentity с info_player_spawn на info_spawn_player появилась другая часть карт в списке. И они стали нормально запускаться

**Comment by mittorn** [comment]
Надо уже убрать эту проверку точки спавна

**Comment by a1batross** [comment]
156b2b2b10edc3a92c768036ce6fe99c8264255a
