### ISSUE TITLE
Where are implement  of opengl  function?

### ISSUE THREAD

**Issue by CeSun** [FWGS/xash3d-fwgs#407]
When I build in `enable-gles2` mode, my msvc compiler tell me that it can't link implement  of opengl  function .
I read gles2 code, I just found `extern function` and not found it's implement or static lib or other.

**Comment by CeSun** [comment]
I have another question:

**Comment by nekonomicon** [comment]
Which platform?
You must not use this options for pc version of Xash3D FWGS.

**Comment by CeSun** [comment]
What is pc default graphic interface?

**Comment by nekonomicon** [comment]
{Open}GL

**Comment by CeSun** [comment]
Think you, I got it.

And, Finally, I want to ask  what ide do you use to adapt to WAF build tools?
There is no plug-in supporting WAF in vs code.

**Comment by Velaron** [comment]
waf generates compile_commands.json which is supported by lots of IDEs, vs code included

**Comment by a1batross** [comment]
I'm not sure if we support GLES on Windows. It exists only for platforms that can't use full OpenGL renderer, like Android and other variations of embedded Linux.

**Comment by mittorn** [comment]
It maybe useful with angle in uwp
