### ISSUE TITLE
Плывет рендер

### ISSUE THREAD

**Issue by AruMoon** [FWGS/xash3d-fwgs#408]
Не знаю когда, начали плыть текстуры на всех рендерах gles1, 2 и software

https://youtu.be/ldafhXDW6VY

Телефон Xiaomi Redmi Note 5A, прошивка Havoc OS с 10 андроидом

Происходит как на 0.19, так и в 0.20 последнем

**Comment by AruMoon** [comment]
Плыть перестало также внезапно, как и появилось
И судя по всему происходило только на gles2 рендере, потому что судя по всему рендер не переключался

**Comment by a1batross** [comment]
Я бы посоветовал разве что избегать всяких васянских прошивок. :)

**Comment by AruMoon** [comment]
Эта прошивка - форк LineageOS
И не такая уж она и васянская

**Comment by a1batross** [comment]
Вопрос не в популярности, а в технической грамотности тех, кто её делают.

Я и к LineageOS отношусь с подозрением.

**Comment by mittorn** [comment]
На adreno можно обновлять бинарники драйверов. Их в виде прошиваемых зипов делают и даже в виде magisk модулей.
так же в ядрах обновляют kgsl - прослойку между юзерспейсными дровами и оборудованием
Так что по идее можешь поискать дрова в которых нет этой проблемы - порой xda на тему своего устройства.
