### ISSUE TITLE
[Android 8+] Не создаётся ярлык с главного меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#409]
Эта проблема есть как в старом так и в новом движке, начиная с версии Android 8 Oreo не создаётся ярлык через главное меню движка. Но его можно создать через меню виджетов в лаунчере

**Comment by mittorn** [comment]
Да, это как-то заблокировали или изменили, теперь через pendingIntent не работает

**Comment by Vladislav4KZ** [comment]
Не актуально в связи с новым лаунчером от Velaron.
