### ISSUE TITLE
[Android] краш по нажатию кнопки "Назад" после открытия консоли

### ISSUE THREAD

**Issue by AruMoon** [FWGS/xash3d-fwgs#410]
Если хоть один раз за запущенную сессию игры открыть консоль, а после закрыть, то по нажатию кнопки "Назад" будет краш

Android 10

**Comment by lewa-j** [comment]
Дубликат #228

**Comment by AruMoon** [comment]
Там написано, что баг исправлен. Но крашится все еще, последний билд
