### ISSUE TITLE
[Android] Переподключение игрока, когда написал в чате слово с буквой Р

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#413]
Когда пишешь "привет" или просто букву "Р" в чате, сервер перезагружается
https://streamable.com/jx6mq3

**Comment by Vladislav4KZ** [comment]
Проверил, в этой же версии ксаша для Windows, там такого бага нет

**Comment by nekonomicon** [comment]
Нужно уточнять платформу.

**Comment by mittorn** [comment]
#414 дубликат
Платформа с unsigned char, важно это а не сервер ли это

**Comment by Vladislav4KZ** [comment]
Пофикшено
