### ISSUE TITLE
Некорректно пишутся русские буквы в чате

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#414]
На Windows этот баг есть только на серверах запущенных на тестовой версии 0.20
На Android этот баг есть везде, как на новых, так и на старых серверах и в локальном сервере

Вот так выглядит сообщение содержащее кириллицу
![Безымянный](https://user-images.githubusercontent.com/22411953/114143102-8c3c2380-9935-11eb-8309-42e20419b1c3.png)

**Comment by mittorn** [comment]
Где-то signed char забыли в протоколе. У вас ещё видать на сервере unsigned char

**Comment by Vladislav4KZ** [comment]
Пофикшено
