### ISSUE TITLE
[MOD: Night At The Office] Не рисуются спрайты индикатора урона на HUD и не работает letterboxing в катсценах

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#417]
^ не появляются черные полоски по краям экрана например в самом начале игры.

**Comment by nekonomicon** [comment]
Эти спрайты рисуются через triapi, то есть вероятней всего сломано triapi:
https://github.com/FWGS/hlsdk-xash3d/blob/noffice/cl_dll/tri.cpp#L126

**Comment by Vladislav4KZ** [comment]
У меня всё работает на последней сборке движка.

![f14_0002.png](https://github.com/user-attachments/assets/85cf592b-6b7c-41ce-b994-bb7e10166010)
![f13a_0000.png](https://github.com/user-attachments/assets/1e301054-d0f3-4235-b27c-33f791c19ab2)
![f13a_0001.png](https://github.com/user-attachments/assets/50c2a869-6eba-4c11-b686-31d1b37c7ec8)


Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master

ОС: Windows 10 Pro x64 22H2
Номер сборки ОС: 19045.4651
