### ISSUE TITLE
Enhancement request: auto-gen player's name

### ISSUE THREAD

**Issue by MoeMod** [FWGS/xash3d-fwgs#42]
As many players don't change their name in configurations, how about reading the current user name and use it as default?
For example,
```
BOOL GetUserNameA(LPSTR lpBuffer,LPDWORD pcbBuffer ); // for Windows
NSString * NSUserName(void); // for macOS
```

**Comment by a1batross** [comment]
It's already has been implemented for Win32 and POSIX: https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/system.c#L123

It even should work, but it always getting overriden, as even default config.cfg has `name "Player"` line in it.

**Comment by a1batross** [comment]
Hm... what about adding a button to reset name from mainui_cpp? "reset name" in console will actually give user name.

It already has a special check to not allow some default names.

I just don't want to add a check for "Player" in engine after loading config.cfg. It's not something that should be done in core element.

**Comment by a1batross** [comment]
Closing due to absence of issue OP. Feel free to re-open this, when you will be ready to discuss.
