### ISSUE TITLE
[MOD: Paranoia] Проблема с полупрозрачностью у шлема.

### ISSUE THREAD

**Issue by klaxons1** [FWGS/xash3d-fwgs#420]
![image](https://user-images.githubusercontent.com/59658354/114304694-44f09700-9add-11eb-9aa6-7b0a6e43e06e.png)
Ref_software.Проблема с полупрозрачностью у шлема.

**Comment by Qwertyus3D** [comment]
Software-режим не предполагает наличия прозрачности вообще, ЕМНИП. Так что это не ошибка, а проблема того, что пользователь изгаляется, как ему хочется :D

**Comment by a1batross** [comment]
In Paranoia1, it's better to use ref_gl.

ref_soft doesn't really nicely works with mods anyway.
