### ISSUE TITLE
[MOD: Team Fortress Classic] Невидимые кальтропы

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#422]
В новом движке не отображается модели кальтропов, они есть и наносят урон но их не видно
Это вот такая колючка у скаута вместо гранат
![Caltrop](https://user-images.githubusercontent.com/22411953/114410384-2669c900-9bcd-11eb-88fb-2305d2f72cae.png)

В старом движке они видны

**Comment by Velaron** [comment]
Спавнятся по центру карты и почти сразу пропадают

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/ddd48c420bd155a8799555431bf53861a12d396d
