### ISSUE TITLE
[Windows] Невозможно повысить лимит более 200 FPS

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#423]
Старый Xash3D FWGS и последняя версия Xash3D от Дяди Миши может выдавать более 200 FPS если позволяет железо и квар fps_max выставлен на значение более 200

А вот новый Xash3D FWGS выдаёт максимум 200 FPS если даже fps_max настроен например на 500

Похожая проблема есть на Android но там 60 FPS, и повышение ограничения не помогает

**Comment by SNMetamorph** [comment]
Это специальный лимит в коде, чтоб от потенциальных багоюзеров и читеров защититься, в исходниках называется FPS_MAX, если не не изменяет память.

**Comment by a1batross** [comment]
@SNMetamorph прав. Необходимости в FPS более 200 нет, только если у кого-то найдется монитор на 240Гц.
