### ISSUE TITLE
[Windows] В синглплеере ограничение FPS с включённым vsync всегда 60, даже если частота обновления монитора выше

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#426]
В синглплеере ограничение FPS с включённой вертикальной синхронизацией всегда 60, даже если частота обновления монитора выше (у меня 68Hz), с выключенной верт. синхронизацией fps повышается (нет ограничения)

В мультиплеере же с включённым vsync всё нормально, в нём ограничение fps столько же сколько герц у монитора

**Comment by noname946** [comment]
Пробовал крутить vid_displayfrequency квар?

**Comment by Vladislav4KZ** [comment]
> Пробовал крутить vid_displayfrequency квар?

Поставил vid_displayfrequency 68, теперь норм. Почему тогда в мультиплеере без этого квара частота обновления была выше?

**Comment by noname946** [comment]
@Vladislav4KZ Так и задумано ибо.
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/host.c#L565
Тут стоит проверка на Host_IsLocalGame. и если оно не true = vsync вовсе вырубается.
В общем, not a bug.

**Comment by a1batross** [comment]
Скорее баг в существовании vid_displayfrequency. 

Сказано всинк -- значит надо ждать синхронизации от драйвера.

**Comment by noname946** [comment]
@a1batross А это уже вопросы к Дяде Мише, ибо когда ему задавали вопрос, зачем этот изврат с vid_displayfrequency, он сказал что-то типа:
"Что бы неопытные пользователи мониторы не сжигали."

**Comment by a1batross** [comment]
@noname946 Xash3D != Xash3D FWGS.

У нас смена видеорежима работает таким образом, что неопытные пользователи смогут её сломать только вне движка, расковыряв настройки их Windows или Linux.

**Comment by noname946** [comment]
@a1batross Я знаю, я просто хотел тем самым сказать, что в результате этой странной логики этот изврат передался и в форк.
В любом случае, его можно просто выпилить и сделать нормальную синхронизацию с видеодрайвером системы.

**Comment by Vladislav4KZ** [comment]
Больше не актуально, так как квар ``vid_displayfrequency`` удалили из ксаша.
