### ISSUE TITLE
xash 3d fwgs vgui2 support

### ISSUE THREAD

**Issue by ahmad12331233** [FWGS/xash3d-fwgs#428]
https://github.com/kungfulon/fwgs-vgui2-support

this guy made xash 3d have vgui2 support but it does work??? and if its works why no-one build custom version of xash 3d fwgs with vgui2 support

for anyone who dont know what vgui2 its just something with it you can run cs1.6 with orginal dll files and all other gold src games

**Comment by ahmad12331233** [comment]
and if no-one want to build it   i will but how i have VS2019

**Comment by ahmad12331233** [comment]
and please i need vgui2 support come to xash 3d fwgs because with vgui2 i can run away more goldsrc games in xash 3d fwgs

**Comment by ahmad12331233** [comment]
in original xash 3d fwgs i just can run half life and any other gold src game will never run

**Comment by a1batross** [comment]
No, we won't add more proprietary code in Xash, even if some games depend on it.

**Comment by ahmad12331233** [comment]
but why :(

**Comment by a1batross** [comment]
Obvious.

It's proprietary.

**Comment by ahmad12331233** [comment]
oh :(

**Comment by ahmad12331233** [comment]
ok

**Comment by ahmad12331233** [comment]
yeah its better......... you right xash 3d fwgs is verry good at this time and its one of the most stable github game engines ever
