### ISSUE TITLE
Иногда не рисует лого выбранное в меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#432]
Проверил на Windows и Android, когда рисую лого рисуется лямбда как на старой версии движка, новые логотипы не работают. А иногда они работают после удаления файлов custom.hpk и logos/remapped.bmp, потом снова перестают работать

После смены логотипа рисуется либо лямбда как на скриншоте, либо предыдущий выбранный логотип

![Screenshot_20210430-210610.png](https://user-images.githubusercontent.com/22411953/116715139-3d475280-a9f8-11eb-9c07-66a7417b708b.png)

**Comment by Vladislav4KZ** [comment]
Должно рисоваться такое лого

![Screenshot_20210430-210930.png](https://user-images.githubusercontent.com/22411953/116715405-7da6d080-a9f8-11eb-9906-9881d9a80ce4.png)

**Comment by Vladislav4KZ** [comment]
При смене лого в меню и отключении от сервера пишется
```
creating custom.hpk
Error: FS_FileCopy: unexpected end of input file (0 < 5176)
```

При подключении к серверу пишется
```
HPAK_AddLump called with bogus lump, md5 mismatch
Purpoted: A0540B4C7EDBDF9D37AB2E9ABBDB5A8A
Actual: 46DBD4BC459E5908CBF0512BEBDFC09D
Removing conflicting lump
Removing logos/remapped.bmp from HPAK custom.hpk.
Error: FS_FileCopy: unexpected end of input file (292 < 5176)
```

**Comment by Vladislav4KZ** [comment]
И ещё бывает зависает на этом моменте при подключении к серверу
```
Compressing filebuffer (5.05 Kb -> 2.26 Kb)
```

**Comment by Vladislav4KZ** [comment]
И ещё я заметил такой момент, когда в папке valve хранится custom.hpk, то в любом другом мультиплеерном моде имеются проблемы с рисованием логотипа.

Когда удаляешь эти файлы
```
moddir/logos/remapped.bmp
moddir/custom.hpk
valve/logos/remapped.bmp
valve/custom.hpk
```
То рисование кастомных лого работает.

При смене лого в меню опять все ломается, и снова нужно удалять эти файлы

**Comment by SNMetamorph** [comment]
Возможно что пофикшено в #1118

**Comment by Vladislav4KZ** [comment]
> Возможно что пофикшено в #1118 

Хорошо, проверю через пару часов

**Comment by Vladislav4KZ** [comment]
@SNMetamorph проверил, всё работает! Лого успешно меняется после перезапуска/переподключения к серверу.

**Comment by SNMetamorph** [comment]
Значит, можно наконец закрывать

**Comment by SNMetamorph** [comment]
> И ещё бывает зависает на этом моменте при подключении к серверу
> 
> ```
> Compressing filebuffer (5.05 Kb -> 2.26 Kb)
> ```

В TFC при подключении к серверу точно такой же баг у меня. Но теперь уже понятно, что это никак со спреями не связано.
