### ISSUE TITLE
Dedicated server memory leak with subsequent crash when second players connects 

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#433]
Happens only with sv_send_logos 1
![изображение](https://user-images.githubusercontent.com/25657591/116749262-a603ee80-aa3b-11eb-9c22-00dae9d1e24f.png)
![изображение](https://user-images.githubusercontent.com/25657591/116749286-ac926600-aa3b-11eb-9b8f-ff461720a87d.png)

**Comment by noname946** [comment]
Что-то мне кажется, что #358 и этот баг связаны.

**Comment by mittorn** [comment]
Да, фрагбуффер начинает непрерывно заполняться и оно падает. Дядя Миша в основном тестировал с максимальным размером пакета. так это не успевало происходить т.к фрагбуффер всегда доходил мгновенно

**Comment by SNMetamorph** [comment]
sv_client.c:124 изменить на if( frmax > FRAGMENT_MIN_SIZE && frmax < FRAGMENT_MAX_SIZE )

**Comment by SNMetamorph** [comment]
Пофикшено в коммите https://github.com/FWGS/xash3d-fwgs/commit/f31e9ae19e0d9f3d8eccfb7735eaf44b54917fa7
