### ISSUE TITLE
Crash on client-side when map changes on server

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#434]
![изображение](https://user-images.githubusercontent.com/25657591/116751955-bb7b1780-aa3f-11eb-9b71-7642c88c93b9.png)

**Comment by mittorn** [comment]
xashoeblya XD
clgame.entities 0 или освобождён.
где-то сталкивался с этим когда legacy протокол делал

**Comment by SNMetamorph** [comment]
https://github.com/FWGS/xash3d/commit/0d3892671dcdde39ebfbdb0d3bf00b93cf8a9c5b
