### ISSUE TITLE
Не может загрузить wad файлы fonts.wad gfx.wad cached.wad с pk3 архива

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#435]
Не может загрузить wad файлы fonts.wad gfx.wad cached.wad с pk3 архива

`[2021:05:01|20:53:30] Adding zipfile: tfc/custom/TFCRusFull.pk3 (518 files)`
`[2021:05:01|20:53:30] ^1Error:^7 W_Open: couldn't open tfc/custom/TFCRusFull.pk3/cached.wad`
`[2021:05:01|20:53:30] ^1Error:^7 FS_AddWad_Fullpath: unable to load wad "tfc/custom/TFCRusFull.pk3/cached.wad"`
`[2021:05:01|20:53:30] ^1Error:^7 W_Open: couldn't open tfc/custom/TFCRusFull.pk3/fonts.wad`
`[2021:05:01|20:53:30] ^1Error:^7 FS_AddWad_Fullpath: unable to load wad "tfc/custom/TFCRusFull.pk3/fonts.wad"`
`[2021:05:01|20:53:30] ^1Error:^7 W_Open: couldn't open tfc/custom/TFCRusFull.pk3/gfx.wad`
`[2021:05:01|20:53:30] ^1Error:^7 FS_AddWad_Fullpath: unable to load wad "tfc/custom/TFCRusFull.pk3/gfx.wad"`

Простые wad файлы с текстурами (halflife.wad, tfc.wad) загружаются нормально
Вот пример:
`[2021:05:01|20:53:30] Adding zipfile: tfc/custom/tfc.pk3 (1 files)`
`[2021:05:01|20:53:30] Adding wadfile: tfc/custom/tfc.pk3/tfc.WAD (279 files)`

**Comment by a1batross** [comment]
Кинь этот архив, пожалуйста.

**Comment by Vladislav4KZ** [comment]
> Кинь этот архив, пожалуйста. 

https://yadi.sk/d/QWggKD4RmLXxzg

**Comment by mittorn** [comment]
Со сжатием не будет работать так, поддержка zip ограниченная

**Comment by a1batross** [comment]
Да, рекомендую перепаковать без сжатия. Или как вариант, указать zip что нельзя сжимать файлы с расширениями .wad, .pak, .pk3, .zip и так далее, что поддерживает движок из форматов архивов.

Со сжатием невозможно открыть пак внутри пака, вне зависимости от формата.

**Comment by a1batross** [comment]
Добавил текстовое предупреждение в https://github.com/FWGS/xash3d-fwgs/commit/585955eb19cc890872a481d4d51e3ba98d6d4e24

Увы, _открыть_ сжатый файл нельзя из-за того, как спроектирована ФС. По крайней мере сходу я не придумал решения этой проблеме.

Однако, его можно прочитать весь, что означает сжатие будет работать для текстовых файлов, карт, моделей, звуков. В данном случае дескриптор на файл просто не отдается.

**Comment by Vladislav4KZ** [comment]
> рекомендую перепаковать без сжатия. 

Да, перепаковал без сжатия теперь те wad файлы загрузились
