### ISSUE TITLE
Windows 10: xash.dll "cannot be found" in latest build from master

### ISSUE THREAD

**Issue by x6herbius** [FWGS/xash3d-fwgs#44]
I'm having issues running xash3d.exe when compiled on either of my Windows 10 machines, in either debug or release. When I run the executable I get the error:

```
Unable to load the xash.dll: The specified module could not be found.
```

I vaguely remember having issues with this before, so I tried to use Dependency Walker to see whether I could deduce what was wrong. Unfortunately when I try and profile the executable, Dependency Walker hangs (apparently indefinitely) after the implicit modules plus IMM32.dll have been loaded.

The engine build works as expected on my Ubuntu machine.

**Comment by a1batross** [comment]
Dependency Walker hangs for me too. :(

But for me, it works. MSVC2017.

**Comment by x6herbius** [comment]
Aha, I'm on 2019. I'll give 2017 a shot and see if it makes any difference.

**Comment by x6herbius** [comment]
I've tried installing VS 2017 and using the different versions of MSVC that Waf reports are available (`--msvc_version` with 16.0`, `15.9` and `15.0` when invoking `configure`), but that doesn't seem to have made any difference

**Comment by a1batross** [comment]
I will look into this. But does autobuilds are not working too?

Sadly, Windows doesn't give better error reporting, compared to `dlerror()` in most it's implementations. :(

**Comment by x6herbius** [comment]
If by autobuilds you mean executing `waf build` on the command line, those don't work either.

**Comment by a1batross** [comment]
I mean, xash3d-deploy repo. Look into newengine-master branch. Download xash-vc.7z, it's the engine built with MSVC.

**Comment by x6herbius** [comment]
The engine build from that repo appears to work for me.

**Comment by a1batross** [comment]
Interesting... 

Can you explain how you building and running the engine? Things are changing rapidly for the new engine. 

Maybe you should try to use `git bisect` and find commit which fails build for you.

**Comment by x6herbius** [comment]
The command line I use by default to build the engine is:

```
python waf configure --build-type=debug --prefix=build/install --sdl2=C:\Users\Vesper\Documents\SDL2-2.0.9 --vgui=C:\Users\Vesper\Documents\GitHub\vgui-dev build install
```

However, thinking about it, I have a suspicion that the missing dependency is either SDL2 or VGUI, given I have to provide them both to `configure`. I'll check to make sure that these are accessible from the installed output location.

**Comment by a1batross** [comment]
They must be put in same directory, where dlls that they linked against
too.

SDL2 must be near xash.dll and vgui.dll near vgui_support.dll and both of
them is in the same directory where xash3d.exe is located.

Just put all DLLs, except game dlls, in same directory and you will be fine.

вс, 2 июн. 2019 г., 23:41 Jonathan Poncelet <notifications@github.com>:

**Comment by x6herbius** [comment]
I've made a note of all this. Thanks for the help in debugging.
