### ISSUE TITLE
[MOD: The Specialists] На карте SS_HQ_f3.bsp вылетает при отрисовке одной с моделей

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#443]
Происходит только под ксашем

**Comment by Vladislav4KZ** [comment]
Уже не вылетает. Карта запустилась нормально

**Comment by Vladislav4KZ** [comment]
Почему эта issue до сих пор открыта? Проблема же исчезла.

Я помню у меня тоже на этой карте игра вылетала, а теперь давно уже как не вылетает.

**Comment by Velaron** [comment]
Потому что я забыл что она существует
