### ISSUE TITLE
[MOD: ThreeWave CTF] [Quake карты] Анимированный скайбокс рисуется сквозь потолок

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#444]
Установлен мод для Half-Life: ThreeWave CTF

Установлены карты отсюда https://www.moddb.com/mods/threewave-capture/downloads/threewave-ctf-for-quake-full-pack

Вот как это выглядит
![ctf6_0000.png](https://user-images.githubusercontent.com/22411953/116991213-0aea6d80-acf6-11eb-8c42-0bc066251775.png)

**Comment by a1batross** [comment]
На скриншоте ctf6 (или vertigo).

Больше не воспроизводится, что с VBO, что без.
