### ISSUE TITLE
[Windows] [MOD: Team Fortress Classic] Дёргается мышка

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#449]
После открытия VGUI меню (меню выбора команды, классов, командное меню на shift и т.д.), начинает дёргаться мышка. Когда захожу в главное меню и захожу в игру обратно, мышка не дёргается

https://streamable.com/i6syxc

**Comment by a1batross** [comment]
Fixed with #470
