### ISSUE TITLE
"New Game" and "Load Game" options are greyed out on aarch64

### ISSUE THREAD

**Issue by benthetechguy** [FWGS/xash3d-fwgs#450]
I'm running Manjaro ARM on a Pinebook Pro and Raspberry Pi 4. Compiled on both systems, copied the valve directory from a steam installation, and it doesn't launch. I see a window titled "Half-Life" open for a split second then close. No output in the terminal. I tried compiling for both 32 and 64 bit ARM and they have the same issue.

**Comment by Velaron** [comment]
But did you also compile and install this https://github.com/FWGS/hlsdk-xash3d

**Comment by benthetechguy** [comment]
Ah, I knew I forgot something.

**Comment by benthetechguy** [comment]
Nope, still greyed out.

**Comment by benthetechguy** [comment]
Yes, The gameinfo.txt contained `gamedll_linux "dlls/hl_i386.so"` and I changed it to `gamedll_linux "dlls/hl_arm64.so"` (which exists in the dll folders I checked) and the issue persists.

**Comment by Velaron** [comment]
is **type** set to "Single" inside gameinfo?

**Comment by benthetechguy** [comment]
Yes.
Here's the whole file if anything else would be of use:
```
// generated by Xash3D FWGS 0.20-4f31d75 (linux-arm64)


basedir         "valve"
gamedir         "valve"
title           "Half-Life"
startmap                "c0a0"
trainmap                "t0a0"
version         1
type            "Single"
dllpath         "cl_dlls"
gamedll         "dlls/hl.dll"
gamedll_linux           "dlls/hl_arm64.so"
gamedll_osx             "dlls/hl.dylib"
icon            "game.ico"
sp_entity               "info_player_start"
mp_entity               "info_player_deathmatch"
secure          "1"
max_edicts      900
max_tempents    500
max_beams               128
max_particles   4096
```

**Comment by benthetechguy** [comment]
Didn't work :(
Thanks for all your help!

**Comment by a1batross** [comment]
Run engine with -dev 2 -log and post engine.log here.

**Comment by Velaron** [comment]
You forgot to send the engine.log, it probably contains a hint to what happened

**Comment by Velaron** [comment]
Oh wait, you are a different person, sorry

**Comment by Idiot64** [comment]
alright, cant even create a local game

but here you go:
https://gist.github.com/Idiot64/5673c58bb0492fb8fafa941dfb68f8e7

seems like it cant find gamestartup and some ohter things

**Comment by Idiot64** [comment]
oh gamestartup is just music

**Comment by Idiot64** [comment]
![image](https://user-images.githubusercontent.com/70104078/117771064-ff3b0180-b235-11eb-8805-8e5a4e730bd6.png)
wut

**Comment by Velaron** [comment]
> ![image](https://user-images.githubusercontent.com/70104078/117771064-ff3b0180-b235-11eb-8805-8e5a4e730bd6.png)
> wut

You built the hlsdk-xash3d project and installed the libraries after?

**Comment by Idiot64** [comment]
uhh, yes i think

i got it from the aur, so if the dependencies are right, i should have everything

**Comment by Idiot64** [comment]
![image](https://user-images.githubusercontent.com/70104078/117772531-92c10200-b237-11eb-8e05-43dee92fcabd.png)
wanna know the solution to this horror?

click change game

![image](https://user-images.githubusercontent.com/70104078/117772601-a2404b00-b237-11eb-8f35-16245fd6e57a.png)

and choose the one with 'single'

**Comment by a1batross** [comment]
@Idiot64 @benthetechguy that's not a solution!

We need to know an exact reason that causes this problem. 

Do you use RoDir?

**Comment by Idiot64** [comment]
rodir?

**Comment by Idiot64** [comment]
it couldn't find something, now it loaded something else where that was or so

**Comment by Idiot64** [comment]
oh, i had multiple "vavles" with different names
and the steam version was the one with "single"

**Comment by Idiot64** [comment]
ALRIGHT DOODS
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

`gamedll_linux		"dlls/hl.so"

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

i hope this works for you guys

**Comment by a1batross** [comment]
It is `hl.so` in Steam version. If you downloaded something else, then it's not our problem.

**Comment by xstrex** [comment]
I'm not sure who to report this to, figured I'd start here, since it's relevant. Recently got a RG351M, tossed ArkOS on it, and installed Half-Life per these [instructions](https://github.com/christianhaitian/arkos/wiki/ArkOS-Emulators-and-Ports-information#half-life-1-rg351pm-only). Ran into the same problem as above. 

In the Half-Life folder for ArkOS, they supply a file `Copy Contents into valve folder.zip`, which contains, among other things, a `hl_arm64.so`. If I leave the stock `gameinfo.txt` alone, the new game options are greyed out, just as before. But if I change this line, to use the new library, it works like a charm. `gamedll_linux           "dlls/hl_arm64.so"`.

I believe somewhere I read that the engine would append the architecture to the `hl.so`, that doesn't happen as one might expect. I still had to edit the `gameinfo.txt` to make it work. 

If I need to bring this up to the ArkOS folks, I'll open an PR with them; just wanted to start here.

**Comment by a1batross** [comment]
@xstrex how old build is? We're not releasing anything at this moment, it may be better to compile latest engine from master branch.

**Comment by xstrex** [comment]
Couldn't tell ya, it came with the latest [arkOS](https://github.com/christianhaitian/arkos/releases/tag/v2.0.11.09.2021) release

**Comment by a1batross** [comment]
Just screenshot main menu, in the right bottom corner there is all info
about build.

вт, 21 дек. 2021 г., 21:14 xstrex ***@***.***>:

**Comment by xstrex** [comment]
v48/0.19.3 build 2092 725fd84b Linux-aarch64

**Comment by a1batross** [comment]
Oh it's not even this tree, but so called "[Old Engine](https://github.com/FWGS/xash3d)" which we stopped developing a few years ago.

They either can switch to this fork, either fix gameinfo.txt because it didn't had autodetection back then.

**Comment by xstrex** [comment]
I'll open an issue with them, thanks for the help.
