### ISSUE TITLE
won versions dll support?

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#451]
would be pretty neat, take your time

**Comment by Idiot64** [comment]
well, its less buggy

**Comment by wowyousucc** [comment]
> we have bugfixed hlsdk-xash3d then :)

well, banning me for a comment in a closed issue is ridicolously stupid

**Comment by wowyousucc** [comment]
weebz

**Comment by wowyousucc** [comment]
> we have bugfixed hlsdk-xash3d then :)

yoo, you can still bash corpses like a king with the crowbar

**Comment by wowyousucc** [comment]
not-so-bugfixed

**Comment by wowyousucc** [comment]
haha

**Comment by wowyousucc** [comment]
work more then

**Comment by wowyousucc** [comment]
havin' fun?

**Comment by wowyousucc** [comment]
-v-

**Comment by wowyousucc** [comment]
**-v-**

**Comment by Velaron** [comment]
> > we have bugfixed hlsdk-xash3d then :)
> 
> yoo, you can still bash corpses like a king with the crowbar

because you didnt enable the crowbar fix, fixes are disabled by default for compatibility

and you were banned for posting links to a crap mod as a solution probably
