### ISSUE TITLE
Не запускается Steam версия Deathmatch Classic

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#453]
```
Host_InitError: can't initialize cl_dlls/client.dll
```

С клиентом от WON версии мод запускается

**Comment by Velaron** [comment]
скорее всего из-за filesystem_stdio

**Comment by Vladislav4KZ** [comment]
Запускается на последнем билде движка.

**Comment by Vladislav4KZ** [comment]
Снова перестал запускаться из-за изменений в файловой системе.

Где-то начиная с этого коммита: https://github.com/FWGS/xash3d-fwgs/commit/24f7db19d8324355bbfcd02a11e1069f171c45b0

**Comment by a1batross** [comment]
Fixed in 934d9ba6
