### ISSUE TITLE
Ложные ошибки об неудачном открытии сжатого файла в pk3 архиве

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#455]
Заметил в моде Firearms который скачал с moddb как автономный мод, где базовые ресурсы Half-Life запакованы в pk3 архиве

То же самое и в моём русификаторе для Team Fortress Classic

Вот что примерно пишет ксаш в консоли:
`[19:09:09]  ^1Error:^7 FS_OpenZipFile: can't open compressed file resource/gameui_russian.txt[2021:05:21|19:09:09] Localize_AddToDict( resource/gameui_russian.txt ): loaded 240 words(UTF-16LE encoding)`
`[19:09:09]  ^1Error:^7 FS_OpenZipFile: can't open compressed file resource/valve_russian.txt[2021:05:21|19:09:09] Localize_AddToDict( resource/valve_russian.txt ): loaded 190 words(UTF-16LE encoding)`
`[19:09:09]  ^1Error:^7 FS_OpenZipFile: can't open compressed file resource/mainui_russian.txt[2021:05:21|19:09:09] Localize_AddToDict( resource/mainui_russian.txt ): loaded 286 words(UTF-16LE encoding)`
`[19:09:09]  ^1Error:^7 FS_OpenZipFile: can't open compressed file resource/tfc_russian.txt[2021:05:21|19:09:09] Localize_AddToDict( resource/tfc_russian.txt ): loaded 30 words(UTF-16LE encoding)`

Эти ошибки пишутся для каждого использованного файла из архива, но движок их успешно читает и никаких проблем с этими файлами нет.

Также здесь нет переноса на новую строку, видно по отрывку из лога. Когда пишется новое сообщение в консоли оно продолжает писаться в той же строке где была ошибка

**Comment by nekonomicon** [comment]
Еще актуально?

**Comment by Vladislav4KZ** [comment]
> Еще актуально?

Да

**Comment by Vladislav4KZ** [comment]
Единственное что перенос строки только добавили, сама ошибка осталась

**Comment by a1batross** [comment]
Fixed in e791d44dd86e4d7ef10e38f3a1f5e9e3d9f7a334 and 18d55c1de2b359d52658a5d494f15364479a64e8
