### ISSUE TITLE
[MOD: The Specialists] При броске видимая модель гранаты зависает в воздухе

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#457]
При броске видимая модель гранаты зависает в воздухе и исчезает лишь после взрыва гранаты.
Гипотеза: по какому-то условию граната перестаёт добавляться через AddToFullPack, из-за чего у клиентов остаётся лишь самый последний стейт, что видится как замирание.
Так же проявляется с подствольными гранатами в HLDM.

**Comment by noname946** [comment]
Насчёт подстволки.
Баг похоже "плавающий", ибо проявляется безпричинно и рандомно на тестовом сервере, в основном такое замечать начал у подземного выхода на вертолётную площадку.
Причём что странно, модель гранаты порой таки "встаёт" на место где-то на середине пути полёта, но не всегда.

**Comment by SNMetamorph** [comment]
Да, так и есть, видимо это как-то связано или с дельтой, или с проверкой видимости на стороне сервера

**Comment by Vladislav4KZ** [comment]
Недавно появился похожий баг в Team Fortress Classic, у солдата ракета из РПГ зависает в воздухе. Хотя раньше такого не было

**Comment by Vladislav4KZ** [comment]
Может быть исправлено с этим коммитом: https://github.com/FWGS/xash3d-fwgs/commit/0e286f31c54f772de3058ca8efa89cf059602892

Надо перепроверить

Хотя, у меня этот баг был давным давно, но до указанного выше коммита вроде небыло зависания гранаты в воздухе

**Comment by Vladislav4KZ** [comment]
Да, действительно данного бага не наблюдаю. Он был давно исправлен
