### ISSUE TITLE
Bug with blood trail of gore.

### ISSUE THREAD

**Issue by En04ik** [FWGS/xash3d-fwgs#459]
I can't explain this so... there is a screenshot https://ibb.co/KGz4pnk

**Comment by En04ik** [comment]
This bug only on xash 0.20.1, you can't see that bug if you are playing on xash 0.19.2 or goldsource

**Comment by hiIexistlol** [comment]
looks like brutal doom, i never had that issue and i tried it on the newest version
I didn't see it

**Comment by Vladislav4KZ** [comment]
> (looks like brutal doom lol) i never had that issue and i tried it on the newest version
> I didn't see it

Because he uses custom models

**Comment by hiIexistlol** [comment]
why would he send an issue if he didn't try it with default assets? they look vanilla to me, the blood decals are stretched, maybe this is only for android?

**Comment by Velaron** [comment]
it doesn't matter, if a bug can't be reproduced on goldsrc it is a bug that should be fixed

**Comment by hiIexistlol** [comment]
yea, just trying to figure out what is the problem

**Comment by a1batross** [comment]
Who knows? If this still happens, post a new issue.
