### ISSUE TITLE
[MOD: Gunman Chronicles] В меню мультиплеерных карт есть синглплеерные

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#467]
### **Gunman Chronicles liblist.gam**
```
// Gunman Game .dll Listing File
// Load order is determined by file order.
game "Gunman Chronicles"
url_info "www.gunmanchronicles.com"
version "Steam"
svonly "0"
cldll "1"
startmap "city1a"
trainmap "demo1"
hlversion "1000"
nomodels "0"
nohimodel "1"
mpfilter "demo"
mpentity "info_player_deathmatch"
gamedll "dlls\gunman.dll"
icon "icon"
developer "Rewolf Software"
manual "http://www.3dactionplanet.com/gunman/help/walkthrough/index.shtml"
```

### **Список мультиплеерных карт в GoldSource**
![goldsource_mp_maps](https://user-images.githubusercontent.com/22411953/120316397-31082b00-c2ff-11eb-9dc4-c7720ccf93b6.png)

### **Список мультиплеерных карт в Xash3D FWGS**
![xash_mp_maps](https://user-images.githubusercontent.com/22411953/120316711-86443c80-c2ff-11eb-89a6-3ce218da34d8.png)

Нету только карты **demo1** так как она есть в mpfilter

**Comment by a1batross** [comment]
Это максимально странно.

По идее ключ mpentity устарел и используется только в WON версиях голдсорса. Что Ксаш и делает, если есть фильтр, использует только фильтр.

В голдсорсе проверки на mpentity больше нет. Тогда почему там только 6 карт?

**Comment by a1batross** [comment]
Если это из вот этого репака: https://www.moddb.com/games/gunman-chronicles/downloads/gunman-chronicles-steam-version

То я кажется понял что они наделали. Голдсорс возможно не проверяет наличие мультиплеерных карт в паках. И если это так, то я сомневаюсь что буду это фиксить.

**Comment by nekonomicon** [comment]
Голдсорсовский GameUI вообще не отображает в списках карты и модели игрока в паках.

**Comment by nekonomicon** [comment]
В модах под GoldSource мультиплеерные карты и модели игрока всегда вне паков.

**Comment by a1batross** [comment]
Если это так, то можно закрывать ишшью как wontfix.

У нас архивы максимально прозрачны для всего движка (за исключением того что в них нельзя писать, а FS_Open в ZIP я когда-нибудь поправлю). Поэтому вставлять костыль ради GameUI я не вижу смысла.

В данном случае можно было бы проверять как mpfilter, так и mpentity. Но это тоже может что-то сломать в модах.

**Comment by Vladislav4KZ** [comment]
> По идее ключ mpentity устарел и используется только в WON версиях голдсорса. Что Ксаш и делает, если есть фильтр, использует только фильтр.
> 
> В голдсорсе проверки на mpentity больше нет. Тогда почему там только 6 карт?

6 карт было из-за того, что синглплеерные карты были запакованны в pak0.pak

Но, карты с префиксом ``demo`` всё равно не отображаются в списке карт для создания сервера, так как он указан в mpfilter.

Да, на последней стимовской версии Half-Life, mpfilter работает.

**Comment by a1batross** [comment]
Я не уверен как такую проблему решать, не сломав ничего. Так что пусть так и будет.

**Comment by a1batross** [comment]
Я не уверен как такую проблему решать, не сломав ничего. Так что пусть так и будет.
