### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by hiIexistlol** [FWGS/xash3d-fwgs#471]
Hello, I would like to share Ideas for things that could be changed
1. When you press a button in the menu, currently the releasing of it plays the click and release sounds together
make it when you press it, the 1st sound plays, and if you release the second one, i looked at some WON menu videos and that's the case there
2. Music while loading, this could be hard (maybe move music to another thread in the cpu) but this is the case in goldsrc, the music plays while loading which is very nice in my opinion
3. Stencil shadows, I know there is an Issue already and this is the wrong place, but please don't forget them.

I'd like to hear what you think and could implement,
have a nice day!

**Comment by hiIexistlol** [comment]
also, changing weapons looks a little glichy (not the case in goldsrc)

**Comment by hiIexistlol** [comment]
animations are sometimes out of sync, you can see it on host_framerate .0002

**Comment by a1batross** [comment]
One issue per request/bugreport

ср, 2 июн. 2021 г., 18:57 hiIexistlol ***@***.***>:

**Comment by hiIexistlol** [comment]
alright, i'll get to it
