### ISSUE TITLE
[MOD: Gunman Chronicles] Некоторое оружие издаёт неправильные звуки, или вообще не издаёт их в мультиплеере

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#472]
Оружие без звука (сервер запущен первый раз с момента запуска игры): https://streamable.com/kj9yf6

Оружие с неверными звуками когда походил или пострелял с другого оружия (оно издаёт звуки ходьбы, сигналов худа и всякой хрени): https://streamable.com/pw87lq

Запуск сервера второй раз, нормальный звук у оружия: https://streamable.com/jlieek

Это касается только мультиплеера, в синглплеере у всего оружия правильный звук

Тоже самое заметил в моде Absolute Redemption

**Comment by Vladislav4KZ** [comment]
Такой же баг есть и в They Hunger

**Comment by Vladislav4KZ** [comment]
Кстати, в They Hunger эта проблема со звуками исчезла после установки SteamPipe патча от malortie

**Comment by SNMetamorph** [comment]
Баг редкий, но сейчас тоже поймал его в Half-Life, звук подбирания айтемов заменился на звук шага в вентиляции. Такое ощущение, будто индексы звуков не совпадают на сервере и на клиенте (cl.sound_index)

**Comment by SNMetamorph** [comment]
Причём, прямо видно через s_show 1 что и путь до файла другой.

**Comment by Vladislav4KZ** [comment]
@SNMetamorph я буквально вчера вместе с игроками заметили этот баг, они говорили что этот баг появлялся в твоём последнем коммите

**Comment by Vladislav4KZ** [comment]
И ещё кстати возможно баг появился недавно из-за серверов на новом движке.

Раньше их не было, и можно было подключаться только к старым.

**Comment by SNMetamorph** [comment]
> @SNMetamorph я буквально вчера вместе с игроками заметили этот баг, они говорили что этот баг появлялся в твоём последнем коммите

Он уже давно появился, примерно с момента как переписали `s_vox.c` полностью

**Comment by Vladislav4KZ** [comment]
> Он уже давно появился, примерно с момента как переписали `s_vox.c` полностью

Я имел ввиду, что баг только недавно появился в обычном Half-Life.

Сам баг по-моему появился намного раньше, до переписи `s_vox.c`.

**Comment by Vladislav4KZ** [comment]
Смотри на дату моего баг репорта, я писал про него год назад. Где-то в мае 2021 года.

А коммит с переписанным `s_vox.c` датируется 22 февраля 2022 года
https://github.com/FWGS/xash3d-fwgs/commit/3f7773f83bda59aa897b23ce7d9386cd2226732c
