### ISSUE TITLE
Music while loading

### ISSUE THREAD

**Issue by hiIexistlol** [FWGS/xash3d-fwgs#475]
Music while loading, this could be hard (maybe move music to another thread in the cpu) but this is the case in goldsrc, the music plays while loading which is very nice in my opinion

**Comment by hiIexistlol** [comment]
also, music replays from the point of the save file, not on goldsrc
it gets annoying

**Comment by a1batross** [comment]
Loads are too fast for modern computers, there is no reason to play anything.

Saving music position and playing it is a nice feature of Xash3D's audio and saverestore subsystems. Nothing is planned doing on this side.

**Comment by hiIexistlol** [comment]
but what about ports for low-end devices, like 3ds port takes really long to load, some music would be nice though

**Comment by a1batross** [comment]
We support low-end devices, like I was running engine on my [Motorola ZN5](https://open.tube/videos/watch/69e5ddfb-0b92-4f57-8e11-8b8ae45e0b85) and @mittorn on his [mp3 player](https://xxivproduction.video/videos/watch/9bc3eb98-8777-42bd-af99-036c463a3afe).

I think in such cases, mod developers actually can make engine play some background music, through client or menu dll.

**Comment by hiIexistlol** [comment]
oh, nice i could get rid of the crackeling that way
