### ISSUE TITLE
Не работает тачконтрол _wheel

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#480]
В списке изменений релиза Xash3D FWGS 0.20 было написано следующее `New touch control: _wheel. Works like a mouse wheel.`

Я создал кнопку "wheel" ввёл в поле Command строку _wheel, но при касании пишется `Unknown command: _wheel`

Может я что-то неправильно делаю или оно действительно не работает?

**Comment by Velaron** [comment]
если я правильно понял 
_wheel команда_при_прокрутке_вверх команда_при_прокрутке_вниз команда_при_отжатии_кнопки

есть еще _hwheel, горизонтальная версия колесика

**Comment by Vladislav4KZ** [comment]
> если я правильно понял 
> _wheel "команда_при_прокрутке_вверх" "команда_при_прокрутке_вниз" "команда_при_нажатии_кнопки"
> 
> есть еще _hwheel, горизонтальная версия колесика

Так и сделал, теперь работает
