### ISSUE TITLE
[Android] Не загружает игровые библиотеки (клиент и сервер) с указанного лаунчера когда запускаешь мод с ярлыка

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#486]
Установлен лаунчер TF15Client. Когда запускаешь TFC через лаунчер, игра работает как и должна работать.

Но если создать ярлык и запустить мод с него, то мод не работает, запускается Half-Life с картами из tfc даже если имя пакета лаунчера написано правильно.

Это сразу заметно по отсутствию поддержки VGUI которая есть в клиенте Team Fortress Classic

**Comment by a1batross** [comment]
Я если честно мало понимаю зачем нам поддержка ярлыков, в том виде в каком они есть.

**Comment by nekonomicon** [comment]
Было бы логично искать пакеты по каким-то атрибутам и отображать названия приложений в списке + как-то определять используюмую папку модификации.

**Comment by a1batross** [comment]
@nekonomicon ты прав.

Когда-то давно я искал пакеты модов по metadata. Раз уж мы немного уже изменили Java часть модов, то справедливо было бы завести несколько строк метаданных как раз для таких вещей.

**Comment by mittorn** [comment]
Проблема не движка, а мода. Чтобы ярлыки работали мод должен симлинк создавать на lib в текущем состоянии. Ну или переделать ярлыки

**Comment by a1batross** [comment]
@mittorn нет, в Android есть специальный метод который даёт путь к библиотекам другого пакета, доступный с API 1. И я вроде это добавлял, но вот точно не помню.

**Comment by Vladislav4KZ** [comment]
Не актуально в связи с новым лаунчером от Velaron.
