### ISSUE TITLE
В списке мультиплеерных карт показывает только те что заданы в mpfilter

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#488]
После этого коммита https://github.com/FWGS/xash3d-fwgs/commit/43f113756553cfcb3f9ed35c7be129937db32c5c в модах где задано название карт в mpfilter, отображаются только они, хотя должны наоборот исчезнуть со списка. Настоящих мультиплеерных карт теперь не видно в списке.

Например в Gunman Chronicles в списке есть только demo карты, и больше ничего

**Comment by Velaron** [comment]
! забыл убрать :)

**Comment by Vladislav4KZ** [comment]
Пофикшено
