### ISSUE TITLE
Мигают энтити с MOVETYPE_STEP

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#489]
Проявляется во всех модах
В прикрепленном ролике мод The Specialists, карта ts_hammertime
https://youtu.be/l4bLGPh5USI

**Comment by noname946** [comment]
Такая проблема проявляется не только в "The Specialists", но и в самой халфе.
Например, на карте lost_village2 в некоторых местах есть некоторая фауна из Зена ввиде моделей, оно всегда мерцает в мультиплеере.
Или например после установки трипмины, тоже поначалу мерцает, но потом со временем перестаёт.

**Comment by SNMetamorph** [comment]
Возможно связано с багом #457

**Comment by SNMetamorph** [comment]
Сейчас в ходе тестов выяснил, что мигают только энтити с MOVETYPE_STEP
А поскольку у NPC такой же movetype, то есть основания полагать, что есть связь с багом #501 
![изображение](https://user-images.githubusercontent.com/25657591/124005747-66925800-da14-11eb-959d-527370c0b1d3.png)

**Comment by SNMetamorph** [comment]
Хотфикс бага #501 помог и от этого бага тоже

**Comment by SNMetamorph** [comment]
Сейчас выяснил, что мигание происходит из-за того что значения renderamt и rendercolor скачут с 0 до 255 и обратно.

**Comment by SNMetamorph** [comment]
Наткнулся на весьма странного содержания код в CL_LinkPacketEntities, после комментирования которого перестали скакать renderamt и rendercolor, но причем сами мигания энтити никуда не исчезли. 
https://github.com/FWGS/xash3d-fwgs/blob/ccf90beb7d85928630ea9273545ce734edbac175/engine/client/cl_frame.c#L1248-L1258

**Comment by a1batross** [comment]
Интересная логика.

Так из-за чего мигают? Из-за renderamt/rendercolor или всё-таки они скачут, а энтити мигают? А кто не скачет, тот москаль? А Крым чей?

**Comment by a1batross** [comment]
Это на удаленном или локальном сервере происходит?

**Comment by SNMetamorph** [comment]
@a1batross на удалённом

**Comment by a1batross** [comment]
Там выше InterpolateModel вызывается для STEP.

Попробуй закомментировать всю проверку. :)

**Comment by SNMetamorph** [comment]
Комментирование этого блока кода помогло решить проблему:
https://github.com/FWGS/xash3d-fwgs/blob/ccf90beb7d85928630ea9273545ce734edbac175/engine/client/cl_frame.c#L1223-L1227

**Comment by SNMetamorph** [comment]
Потестил, это фиксит #559 и #501 (но при условии что сервер не на старом движке)

**Comment by SNMetamorph** [comment]
Выявил кое-какую интересную закономерность. Решил потестить и сравнить animtime который пишется в position history на голдсурсе и ксаше. 

Стою на месте, ничего не мигает, все нормально
![изображение](https://user-images.githubusercontent.com/25657591/155604255-25f99951-a544-4830-a383-677cd15e364a.png)

Затем ухожу за стену (энтити пропадает из PVS в этот момент), потом выхожу обратно, модель начинает мигать и с animtime происходит нечто странное:
![изображение](https://user-images.githubusercontent.com/25657591/155604615-d3c5663c-91fd-4015-894e-660498c5d361.png)
Через некоторое время animtime перестаёт меняться и сразу же модель перестаёт мигать.

**Comment by SNMetamorph** [comment]
В голдсурсе ситуация аналогичная, только при этом модель не мигает.
![изображение](https://user-images.githubusercontent.com/25657591/155605093-7ed19132-8ef0-458c-bc88-bb48d0d2462c.png)

**Comment by SNMetamorph** [comment]
Хотфикс сделан в https://github.com/FWGS/xash3d-fwgs/commit/13b36e66b351138a59b2135bed803fa6d7f00a62
Однако это избавления от следствия, а не от причины, так что в будущем было бы неплохо разобраться с реальной причиной этой проблемы
