### ISSUE TITLE
Сломаны звуки, которые пытаются звучать изнутри геометрии уровня.

### ISSUE THREAD

**Issue by noname946** [FWGS/xash3d-fwgs#491]
Перестали звучать звуки, которые по тем или иным причинам звучат изнутри геометрии уровня.
В качестве примера, перестал работать звук мотора у антимасс-спектрометра во время его запуска на карте c1a0e.
Или например сломался звук вагонетки на карте c2a2.
Есть подозрения, что сломалось после этого коммита https://github.com/FWGS/xash3d-fwgs/commit/60c10333aaf98a65fc0556b283c68df606b7ec7d.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/c50f73b892cb1481fd3a07d861a1ee5ff73cd3c6
