### ISSUE TITLE
Keyboard in Chat

### ISSUE THREAD

**Issue by qberkdc** [FWGS/xash3d-fwgs#495]
Message I Typed Scrolls Up After Keyboard Opens

**Comment by a1batross** [comment]
What? Can you explain?

**Comment by qberkdc** [comment]
When the Keyboard I Write a Message Is Opened The message appears at the bottom left, but after the keyboard is opened, the messages slide to the top

**Comment by Vladislav4KZ** [comment]
This bug was in the old engine, the new version does not have this bug, messages are always written at the bottom of the screen

**Comment by Vladislav4KZ** [comment]
I caught this bug on the new engine when I minimized/maximized the game. After that, the keyboard changes the screen size and the chat message is written at the top of the screen.
![Screenshot_20210615-170630.png](https://user-images.githubusercontent.com/22411953/122042760-5f583100-cdfc-11eb-9c58-7833a800c383.png)![Screenshot_20210615-170643.png](https://user-images.githubusercontent.com/22411953/122042795-6a12c600-cdfc-11eb-87b0-a7ce64868f00.png)

**Comment by a1batross** [comment]
Since we cannot safely notify client.dll about the resolution change, this cannot be considered as a bug anymore.
