### ISSUE TITLE
Save files are not compatible betwwn Windows and Android

### ISSUE THREAD

**Issue by Srandista** [FWGS/xash3d-fwgs#498]
Hello.
I tried both Windows and Android versions today, and even tho both work fine on its own, I found out, that the saves aren't compatible, even if I used the same test version for both of them. Saves are transferable, and I can technically load (they are correctly described in Load menu and are also showing correct screenshots), but the NPCs aren't moving. I did test early part of the game after the train ride, where Barney is escorting Gordon to the Black Mesa facility. When I saved game on PC during his way to the door and load this save on my Android phone, Barney did not continue to the door, and the same behavior occurred, when I tried it vice-versa (copied save from the phone to the PC).

I used Steam build on both devices, PC was running Windows 10, while my phone (Pixel 4a) was running latest Android 11.

**Comment by a1batross** [comment]
Hi! 

This is a known problem. Saves aren't compatible between Windows and everything else.

To be technically correct, this is due different C++ ABI, Windows uses Microsoft developed [C++ mangling](https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=msvc-160) and mostly everybody else use [Itanium ABI](https://itanium-cxx-abi.github.io/cxx-abi/abi.html). I started to write a library that will abstract this few years ago but never finished it.

Meanwhile, when Valve ported GoldSource to Linux, they introduced their own very simplistic mangling and then just bruteforce all possible symbol names at runtime. Somehow that works. 

There isn't too much you can do about this.

**Comment by a1batross** [comment]
Fixed.

**Comment by Srandista** [comment]
Thank you for the fix!. Also, I can confirm, that indeed it does work on my setup mentioned in original post (Windows PC and Android phone).

**Comment by a1batross** [comment]
From now on you must be able to load even GoldSource saves on Android.

Of course, only in latest builds. Well, I see you know how to use autobuilds so that shouldn't be a problem. :)
