### ISSUE TITLE
Gamma/brightness is incorrect on Windows

### ISSUE THREAD

**Issue by x6herbius** [FWGS/xash3d-fwgs#50]
I've been looking at this for the last couple of days but haven't had any success in tracking down the cause yet, so I thought I'd put some details down here in case they're helpful for diagnosis.

The Windows build looks very washed-out: https://media.discordapp.net/attachments/548621970187616268/589464898925232128/windows.png?width=1896&height=1133

Compare this to the Linux build, where the brightness seems more correct: https://media.discordapp.net/attachments/548621970187616268/589464938913988618/linux.png?width=2002&height=1133

I've determined that this is **not** due to the brightness/gamma settings tied to the console variables in the engine - they use the built gamma table, and if I set this to identity values or bypass it completely, there is still no change at all on Windows. With the table active, I can change the gamma and brightness and they do seem to affect the on-screen picture, but they only seem to be able to make it more washed-out, and never less so than in the above screenshot.

As an aside, the gamma table is currently being built every frame when running the main menu, because `R_BeginFrame` checks if `FCVAR_CHANGED` is set on the gamma and brightness cvars, but doesn't reset this flag once the table has been rebuilt. This doesn't fix the washed-out issue, but it's worth noting nonetheless.

I've also tried running with various video modes and OpenGL modes on Windows, but none of these has made any difference.

**Comment by x6herbius** [comment]
I'm attempting to look into this using RenderDoc, but when I boot the engine I get the following message:

`OpenGL. Context not created via CreateContextAttribs. Capturing disabled.
Only OpenGL 3.2+ contexts are supported.`

**Comment by a1batross** [comment]
I think it's better to trace which commit has broke the engine.

I'm still busy(until today I hope), so if you have time, you can try it by yourself. Use a `bisect` [tool](https://git-scm.com/docs/git-bisect).

**Comment by a1batross** [comment]
The problem has appeared after 4483 merge.

**Comment by x6herbius** [comment]
I'll see if I can do some more investigating today.

**Comment by x6herbius** [comment]
I've tried building from the commit just before the one mentioned earlier and the problem still persists. I'll see if I can go further back.

**Comment by a1batross** [comment]
For me reverting a merge commit fixes everything. O_o

i.e. on https://github.com/FWGS/xash3d-fwgs/commit/74062fab128365738208953fd3ab37b1019dcc83 everything is fine. 

These attributes are binary compatible with SDL2 and setting an offset keeps compatibility. This should be removed and proper GL_Set/GetAttribute must be implemented in engine for SDL2.

**Comment by x6herbius** [comment]
Surely that change _isn't_ binary-compatible, though? For example:

`REF_GL_ALPHA_SIZE,`
`REF_GL_BUFFER_SIZE, // = REF_GL_ALPHA_SIZE + 1`
`REF_GL_DOUBLEBUFFER // = REF_GL_ALPHA_SIZE  + 2`

Becomes:

`REF_GL_ALPHA_SIZE,`
`// UNUSED_REF_GL_BUFFER_SIZE,`
`REF_GL_DOUBLEBUFFER // = REF_GL_ALPHA_SIZE + 1,`

So the actual values of the enum constants are no longer the same. Is this what was intended?

**Comment by a1batross** [comment]
Woops.

**Comment by a1batross** [comment]
Ok, I will fix it in next commit. :)

**Comment by a1batross** [comment]
Fixed.
