### ISSUE TITLE
Дёрганная анимация NPC на coop серверах

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#501]
https://streamable.com/gbhndt

**Comment by SNMetamorph** [comment]
mittorn говорил что у NPC интерполяция как-то неправильно работает, и поэтому такой баг есть. Вроде бы он собирался пофиксить.

**Comment by mittorn** [comment]
На coop подменяются некоторые параметры у NPC на заведомо неверные. Такая конфигурация хорошо со старым движком работала, под новый надо снова подбирать
https://github.com/FWGS/hlsdk-xash3d/blob/gravgun/dlls/client.cpp#L1479

**Comment by SNMetamorph** [comment]
> На coop подменяются некоторые параметры у NPC на заведомо неверные.
А для чего это? Кстати, NPC и в обычном мультиплеере хл тоже дергает, можно увидеть если запустить crossfire с mp_allowmonsters 1

**Comment by mittorn** [comment]
Иначе на старом дёргало ещё сильнее

**Comment by SNMetamorph** [comment]
> 
> 
> Иначе на старом дёргало ещё сильнее

Хм, видимо это был лишь фикс следствия, а не причины, как нибудь потом попробую разобраться с этим всем

**Comment by SNMetamorph** [comment]
Протестил на локальном сервере, в мультиплеере HLDM та же проблема, но проявляется она только по мере возрастания пинга: к примеру, с пингом 80 уже прекрасно видно этот баг, но он не проявляется если пинг околонулевой. Причем, он как то проявляется периодами, 1-2 секунды никак не дергает, а потом вновь начинает. Этим всем баг очень похож на https://github.com/FWGS/xash3d-fwgs/issues/438

**Comment by SNMetamorph** [comment]
В общем, разобрался в чем была суть проблемы. Есть в движке такой host.features флаг ENGINE_COMPUTE_STUDIO_LERP, он как раз сглаживает вот это вот всё. Только дело в том, чтобы сглаживание работало, нужно чтобы клиентская DLL выставила этот флаг в своих features (чего конечно же >90% модов не имеет и иметь не будет). По словам ДМ, этот функционал сделан флагом потому что ТЕОРЕТИЧЕСКИ может вызывать проблемы с некоторыми (так никто и не знает с какими) модами. Предлагаю вместо feature флага сделать это поведение сделать включенным по умолчанию, и кроме того переключаемым через квар: если вдруг из-за этого возникнут проблемы с какими-либо модами, то можно будет просто для них отключить этот квар в конфиге.

**Comment by a1batross** [comment]
Дёргаться больше не должны, но FPS может оставлять лучшего. Пока неизвестно что с этим делать -- но лучше завести новую ишшую, если сильно будет глаза мозолить.

**Comment by Vladislav4KZ** [comment]
https://youtu.be/tkpVq-6_snA

**Comment by Vladislav4KZ** [comment]
Вот здесь очень хорошо видно
https://youtu.be/L7hOD6dSMig

**Comment by Vladislav4KZ** [comment]
Также заметил такое же подёргивание у гранат при броске.
