### ISSUE TITLE
Не работает реверс аудио каналов

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#503]
В настройках звука есть флажок "Reverse audio channels", он должен поменять аудиоканалы местами но не работает

Пишет в консоли
```
Cvar_Set: variable 's_reverse_channels' not found
```

**Comment by a1batross** [comment]
Нам вообще сильно нужна эта опция?

**Comment by nekonomicon** [comment]
Побаловаться %)
Я не знаю, что мешает повернуть наушники или переставить колонки.
