### ISSUE TITLE
crashed with "assert failed at c:\users\travis\build\fwgs\xash3d-fwgs\engine\common\lib_common.c:345"

### ISSUE THREAD

**Issue by githubsucksatlife** [FWGS/xash3d-fwgs#504]
![image](https://user-images.githubusercontent.com/86205157/122685867-68873a80-d20e-11eb-8592-763104b0f636.png)
crashes when entering a game

**Comment by githubsucksatlife** [comment]
also some buggy stuff has been happening to the images as well
turn off VBO and you should see it.

**Comment by a1batross** [comment]
From save or just entering game?

If it's save, post it here. And post hl.dll.

**Comment by Srandista** [comment]
I got this error during intro tram ride every time I run a new game.

**Comment by a1batross** [comment]
Fixed.

**Comment by Srandista** [comment]
Thank you for the fix!
