### ISSUE TITLE
Continious integration, autobuilds and other

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#506]
As Travis CI now goes to complete monetization, we need to think about alternatives.

What I am suggesting?
* Add and leave aarch64 builds for Travis CI, because they are sponsored and don't take precious credits.
  - Maybe we could also use free ppc64le and s390x machines.
* Move to GitHub Actions, like in hlsdk-xash3d.

However, as splitting between various CIs, will make our git repo hack for autobuilds completely useless, I also suggesting:
* Publishing new builds at GitHub Releases, as we now can unsubscribe from releases notifications.
* Moving xash3d-deploy to archive.
* Maybe in the future we could host autobuilds on our infrasturcture.

**Comment by nekonomicon** [comment]
Right idea.

**Comment by mittorn** [comment]
Механизм на подобии того что в деплое был всё ещё может быть полезен для чего-то, что хочется отображать как README на гитхабе и может быть для gh-pages если это где-то будет использоваться, где надо обновлять только текст

**Comment by a1batross** [comment]
@mittorn он мог бы быть полезен, не будь у нас гонки.

Из-за того, что все билды собираются параллельно, на трависе был костыль с выгрузкой артефактов на яндекс.диск и уже по нему генерация README.md.

То что мы сейчас (и возможно в будущем, ведь неизвестно когда прекратят майнить на бесплатных CI и когда прекратят закручивать гайки) частично переезжаем с трависа на гитхаб ситуацию не упрощает. В этом GitHub Releases хороши -- просто списком выводится всё подряд и загружать можно параллельно с нескольких машин.

**Comment by a1batross** [comment]
GitHub Actions migration is complete for a while now.

Closing this.
