### ISSUE TITLE
Чёрные пятна и точки на загрузочных экранах

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#508]
### Замечено в Counter-Strike и в Firearms
![Снимок экрана (18)](https://user-images.githubusercontent.com/22411953/122888850-0dfff280-d364-11eb-94d8-81d70a9f2176.png)![Снимок экрана (19)](https://user-images.githubusercontent.com/22411953/122889147-5ae3c900-d364-11eb-952b-a0c31241d46f.png)

**Comment by mittorn** [comment]
Старый добрый SGB
