### ISSUE TITLE
FreeBSD missing Platform_Sleep and Platform_DoubleTime implementations

### ISSUE THREAD

**Issue by bariscodefxy** [FWGS/xash3d-fwgs#510]
Im trying build to FreeBSD, i got some errors
![Screenshot_20210625-225627](https://user-images.githubusercontent.com/85716242/123478837-b635e580-d608-11eb-9bea-2cf4cab1a303.jpg)

**Comment by a1batross** [comment]
At first, if you're having problems that can be presented as TEXT, you probably need to post them as TEXT too. There is no need to screenshot textual information.

At second, I don't recommend using these scripts. In the future, they will probably gone. Just follow normal build instructions.

Anyway, I see what's the problem and will try to fix this, thanks!

**Comment by a1batross** [comment]
Must be fixed in latest commit

**Comment by bariscodefxy** [comment]
I finally builded, thanks for fixing!
