### ISSUE TITLE
SDL2 Sanity

### ISSUE THREAD

**Issue by PowerX-NF** [FWGS/xash3d-fwgs#513]
Checking for library SDL2 sanity                        : no
SDL2 not availiable! If you want to build dedicated server, specify --dedicated
(complete log in E:\007NightfireRework\FWGS2\build\config.log)

Please help

waf configure -T release --sdl2=E:\007NightfireRework\FWGS2\SDL2 --prefix=E:\007NightfireRework\bin_fwgs

**Comment by a1batross** [comment]
Post config.log please.

SDL2 folder must have contents of development archive for Visual Studio from libsdl.org.

**Comment by PowerX-NF** [comment]
thanks i figured out how to fix it

**Comment by g0g5** [comment]
Sorry dude but I got the same problem here. Can you tell that how to fix it up?
I simply downloaded "SDL2-devel-2.0.16-VC.zip", extracted to "./SDL2-2.0.16", renamed it to "./SDL2". Did I get the wrong package?
