### ISSUE TITLE
Clientside engine function hudGetModelByIndex returns invalid model index

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#518]
On GoldSrc it's index of actual visible entity model, but in Xash3D it's index of another unrelated model

**Comment by a1batross** [comment]
Example?

**Comment by SNMetamorph** [comment]
To determine model name I use this code
```
cl_entity_t *traceEntity = g_pClientEngfuncs->GetEntityByIndex(entityIndex);
model_t *entityModel = g_pClientEngfuncs->hudGetModelByIndex(traceEntity->curstate.modelindex);
modelName = entityModel->name;
```
1. Result on GoldSrc (correct)
![изображение](https://user-images.githubusercontent.com/25657591/124311421-b0ac4280-dba8-11eb-897e-97b93302ba61.png)
2. Result on Xash3D (incorrect)
![изображение](https://user-images.githubusercontent.com/25657591/124311450-bbff6e00-dba8-11eb-9317-70d310e818d3.png)

**Comment by SNMetamorph** [comment]
The issue in `hudGetModelByIndex` function, because it returns invalid model pointer. 
To get valid, we should do:
```
cl_entity_t *traceEntity = g_pClientEngfuncs->GetEntityByIndex(entityIndex);
model_t *entityModel = g_pClientEngfuncs->hudGetModelByIndex(traceEntity->curstate.modelindex - 1);
modelName = entityModel->name;
```

**Comment by SNMetamorph** [comment]
I think hudGetModelByIndex should refer to something like `CL_GetModelByIndex` instead of `Mod_Handle`

**Comment by SNMetamorph** [comment]
Or may be modelindex on server and client are points to different models?

**Comment by SNMetamorph** [comment]
> Or may be modelindex on server and client are points to different models?

No, it's not related to modelindex field. It messed up with this code as well
`model_t *worldModel = g_pClientEngfuncs->hudGetModelByIndex(1);`
On GoldSrc, this returns pointer to worldspawn brush model, as it should.
On Xash3D this returns pointer to some other studiomodel, which is incorrect.

**Comment by SNMetamorph** [comment]
Solution found: `Mod_Handle` should be replaced with `CL_ModelHandle` in client engine functions API, ref_api does same and it works as it should.
