### ISSUE TITLE
[MOD: Base Defense] Белая обводка на экране

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#523]
![pve_wintertown_0001.png](https://user-images.githubusercontent.com/22411953/125083705-88fa3480-e0ea-11eb-9ec4-3f924467a55c.png)

Эта обводка должна появляться при получении урона, и она должна быть красного цвета

**Comment by Vladislav4KZ** [comment]
Кстати, эта обводка исчезает когда появляется текст на экране (например, название оружия с ценой)

И когда текст исчезает, обводка появляется снова

**Comment by Vladislav4KZ** [comment]
Вот пример:
![pve_tomb_0002.png](https://user-images.githubusercontent.com/22411953/125085086-04a8b100-e0ec-11eb-8a15-ed24c95561d4.png)

**Comment by Vladislav4KZ** [comment]
В последней сборке движка произошли изменения.
Теперь при появлении текста, белая обводка не исчезает, а становится красной как я уже говорил, будто игрок получает урон.

Её конечно же не должно быть вообще, когда игрок не получает урон, ни белой ни красной.

**Comment by Vladislav4KZ** [comment]
Сегодня вернулось прежнее поведение бага. Не знаю почему вчера обводка окрашивалась в красный цвет.

**Comment by a1batross** [comment]
Исправлено в da6586b847bc350fe1d4b10f2d7b7e0826980a72
