### ISSUE TITLE
Отсутствует текст пути и названия файлов текстур для тач кнопок

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#526]
**Вот список с русским btns_main.bmp:**
![Screenshot_20210719-184850.png](https://user-images.githubusercontent.com/22411953/126162305-0ea0fbd3-1f1b-4bcf-848a-6dbf5d01ad8f.png)

**Вот список с оригинальным btns_main.bmp:**
![Screenshot_20210719-185129.png](https://user-images.githubusercontent.com/22411953/126162477-33136967-392e-4ac1-8a01-9a6250b82b7e.png)

**Comment by a1batross** [comment]
Это вообще никак не должно быть связано и скорее всего сигнализирует о проблеме где-то в загрузчике текстур.

Этот список отрисовывается иначе и к btns_main.bmp не имеет никакого отношения.

**Comment by mittorn** [comment]
в логе есть что-то подозрительное?

**Comment by a1batross** [comment]
C -gldebug само собой

**Comment by Vladislav4KZ** [comment]
В логе нет ничего необычного, проверял с -gldebug как и с оригинальным файлом так и с другим

**Comment by mittorn** [comment]
с gl4es попробуй, наверняка что-то с состояниями в трансляторе

**Comment by mittorn** [comment]
ну и не работает наверняка этот gldebug на андройдах

**Comment by mittorn** [comment]
некоторые драйвера выводят ошибки в лог, особенно китайцы с mali - они часто отладку включенной оставляют

**Comment by Vladislav4KZ** [comment]
> ну и не работает наверняка этот gldebug на андройдах

Я логи смотрел на винде, ксаш соответственно тоже на винде запускал с -gldebug

**Comment by mittorn** [comment]
там такая же проблема?

**Comment by mittorn** [comment]
приложи проблемный файл

**Comment by Vladislav4KZ** [comment]
Сегодня заметил что уже с оригинальным файлом такая проблема.

**Comment by Vladislav4KZ** [comment]
При том заметил это только на Windows, на Android с оригинальным btns_main.bmp текст присутствует

**Comment by Vladislav4KZ** [comment]
Так же заметил на компьютере что отсутствует текст и у тач профилей (нет названий конфигов)

Хотя там присутствуют как и конфиги так и текстурки тач кнопок

**Comment by Vladislav4KZ** [comment]
На Windows теперь получилось наоборот, заменил файл, появился текст в списке выбора текстур кнопок и тач профилей

Так что точно дело не в файле, а в чем то другом что текст появляется через раз (или через два как повезёт)

**Comment by Vladislav4KZ** [comment]
Не воспроизводится на последней сборке движка.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master
