### ISSUE TITLE
[Android] Отсутствуют ресурсы в extras.pak

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#527]
![Screenshot_20210721-121353.png](https://user-images.githubusercontent.com/22411953/126440583-6c56bc00-39c9-4df0-a6df-ec569d04672f.png)![Screenshot_20210721-121437.png](https://user-images.githubusercontent.com/22411953/126440608-c11b326e-4eb6-432e-968f-96b9ad75614e.png)![Screenshot_20210721-121412.png](https://user-images.githubusercontent.com/22411953/126440630-4be9fa4f-1c9d-4eaf-9af1-52c858570d0a.png)

**Comment by Vladislav4KZ** [comment]
Это на последней сборке за вчерашний день, проверял xashdroid-32 и xashdroid-64, в обоих версиях extras.pak пустой, весит 12 байт

**Comment by Vladislav4KZ** [comment]
Это было даже не на последней сборке, наверное после миграции с Travis CI на GitHub Actions сломался скрипт запаковали ресурсов в extras.pak

А раньше не замечал этого потому-что все версии ставил поверх а на этот раз предыдущую версию удалил и поставил начисто

**Comment by mittorn** [comment]
ну да,  у нас пак идентифицируется версией которая прописана вручную. Можно наверно сделать генерацию контрольной суммы

**Comment by AruMoon** [comment]
Скрипт сборки github actions написан неправильно. `matrix.targetos != 'android'` скачивает на всех билдах кроме android

**Comment by Vladislav4KZ** [comment]
Исправлено
