### ISSUE TITLE
[MOD: Snow War] У текста через букву появляется черная полоса

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#537]
Счётчик фпс, текст в чате и консоль выглядит вот так
![kotm_faceoff_0001.png](https://user-images.githubusercontent.com/22411953/126753277-ca8aa0b5-1f54-4422-b56a-8eea0645f2c8.png)

И консоль начала флудить этой ошибкой
```
OpenGL Error: GL_INVALID_OPERATION error generated. Target doesn't match the texture target.
```

**Comment by Vladislav4KZ** [comment]
Вот такая ошибка на последней тестовой сборке
```
OpenGL Error: GL_INVALID_OPERATION error generated. Target doesn't match the texture target.
OpenGL Error: GL_INVALID_OPERATION (at D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_rmain.c:924)
```

**Comment by Vladislav4KZ** [comment]
Кстати Glow FX тут не причём, этот баг происходит случайно, уже несколько раз включал этот эффект и он работал нормально, а текст с чёрными полосками появился без него

**Comment by Vladislav4KZ** [comment]
Тоже самое может происходить и в Go-Mod

**Comment by mittorn** [comment]
боюсь что это всё-таки какая-то проблема с драйвером. У меня на NST со свежими дровами чёрные полосы на случайных текстурах мира всплывали притом что каких-либо ошибок рендера не было

**Comment by Vladislav4KZ** [comment]
Артефакты с текстом я заметил при использовании новой видеокарты, только когда запустил этот мод впервые на ней. Теперь повторно его не могу воспроизвести.

**Comment by Vladislav4KZ** [comment]
Теперь чтобы воспроизвести баг с артефактами в тексте, нужно свернуть-развернуть игру.

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/6232e288e12831ef39e5d704181873a26ab5731d
