### ISSUE TITLE
Issues with MIPS (big endian) architecture

### ISSUE THREAD

**Issue by tyabus** [FWGS/xash3d-fwgs#54]
I tried to launch xash3d-fwgs engine on my router (latest commit, big endian), but it seems to be almost broken on this architecture.

Issues list:
map loading dosen't work (first, the engine says that map has invalid format, then it says that map dosen't have a valid spawn point, after commenting that checks, the engine crash at the map load)
wads loading dosen't work

The issues list is not full, because i still can't resolve the map loading issue

**Comment by mittorn** [comment]
It is not supported. You may implement it yourself
