### ISSUE TITLE
Локализация информативных и ошибочных окон

### ISSUE THREAD

**Issue by AruMoon** [FWGS/xash3d-fwgs#540]
![Screenshot_20210727_015749](https://user-images.githubusercontent.com/28903731/127058344-1a0e6df7-c20e-424d-a88a-b4c0787d3cc3.png)
Сам движок работает и всё запускается, но в таких окнах с ошибками или информацией вместо системного языка использутеся вообще какой-то тамильский язык, то бишь вообще какой-то левый

**Comment by nekonomicon** [comment]
А почему иконка Xming?
Каким образом и на какой платформе запущен движок?

**Comment by AruMoon** [comment]
Это иконка X.org, а не Xming
Платформа Linux, запускаю через AppImage

**Comment by nekonomicon** [comment]
Какой дистрибутив Linux?

**Comment by nekonomicon** [comment]
Какая архитектура?

**Comment by mittorn** [comment]
Мржет у тебя кривой растровый шрифт в системе?

**Comment by AruMoon** [comment]
Manjaro Linux на KDE Plasma. amd64. Графический сервер Wayland. Шрифты все дефолтные, а именно семейста Noto. Я сказал, проблема не в шрифте, а в локализации, потому что это именно другой язык.

**Comment by AruMoon** [comment]
P.S. На Xorg сервере тоже так

**Comment by a1batross** [comment]
Это не локализация, так как сообщения об ошибке **никогда** не переводятся.

Скорее кривая кодировка.

**Comment by mittorn** [comment]
я не знаю что надо сделать чтобы получить сообщение об ошибке на другом языке. Даже если заюзать API на Host_Error, это будет по дургому выглядеть

**Comment by AruMoon** [comment]
Я ничего и не делал, я сам хз как вообще так получилось. На другом ПК вообще сообщений об ошибках нет

**Comment by a1batross** [comment]
Покажи вывод locale.

Ещё как вариант попробуй распаковать AppImage и удалить SDL2, может ошибка
в нём.

**Comment by AruMoon** [comment]
> Покажи вывод locale. Ещё как вариант попробуй распаковать AppImage и удалить SDL2, может ошибка в нём.

```
locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```

**Comment by AruMoon** [comment]
![Screenshot_20210727_184746](https://user-images.githubusercontent.com/28903731/127165335-35678158-705f-489d-bbaf-feea7565ab87.png)
также

**Comment by mittorn** [comment]
Репортить разрабам SDL2 видимо

**Comment by AruMoon** [comment]
> Репортить разрабам SDL2 видимо

Дак я даже без SDL2 запустил. На скриншоте

**Comment by mittorn** [comment]
из системы тоже SDL2 удалил?

**Comment by AruMoon** [comment]
Нет, его удалить из системы не могу, слишком много зависимостей

**Comment by mittorn** [comment]
https://github.com/libsdl-org/SDL/issues
пока не вижу репорта

**Comment by a1batross** [comment]
Надо его сначала воспроизвести локально.

**Comment by AruMoon** [comment]
Если надо, могу дать удаленный доступ

**Comment by a1batross** [comment]
Is it still an issue? If so, reopen pls.
