### ISSUE TITLE
Зависание при выходе или смене игры в модах, использующих FMOD

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#545]
Poke646 и Poke646: Vendetta v1.1 Юбилейное издание (Anniversary edition)

Зависает когда выходишь из игры либо меняешь мод через меню Custom game

**Comment by Vladislav4KZ** [comment]
То же самое и в Tactical Espionage Action.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master

**Comment by Vladislav4KZ** [comment]
У меня мод Tactical Espionage Action установлен со всеми патчами, которые есть на moddb.


Зависание при выходе из игры также до сих пор присутствует в модах Poke646 и Poke646 Vendetta.

**Comment by Vladislav4KZ** [comment]
То же самое и в моде Operation Black Thunder.

https://www.moddb.com/mods/operation-black-thunder

**Comment by Vladislav4KZ** [comment]
То же самое и в Public Enemy.

https://www.moddb.com/mods/public-enemy

**Comment by Vladislav4KZ** [comment]
Ещё один мод в копилку.

То же самое происходит и в Project Timeless.

https://www.moddb.com/mods/project-timeless

**Comment by Vladislav4KZ** [comment]
Я заметил, что этот баг проявляется только в модах, использующих FMOD (не FMODEx, а обычный) для воспроизведения фоновой музыки.

**Comment by Vladislav4KZ** [comment]
Sven Co-op 4.8 например, использует FMOD Ex (fmodex.dll), и там нет зависания при выходе из игры.

**Comment by Vladislav4KZ** [comment]
В одних модах использующих FMOD зависание при выходе из игры может происходить сразу, даже без запуска карты.

А в других (например в Paranoia v1.2) зависание при выходе из игры воспроиздится только во время воспроизведения фоновой музыки. (По окончанию воспроизведения музыки, ещё не проверял).

**Comment by Vladislav4KZ** [comment]
> (По окончанию воспроизведения музыки, ещё не проверял).

На карте p_army3 в моде Paranoia музыка зациклена, но даже при вводе команды ``stopmp3`` в консоль, музыка хоть и перестаёт играть, но движок всё равно зависает при попытке завершения работы, после того, как играла музыка.

**Comment by Vladislav4KZ** [comment]
В Operation Black Thunder если переименовать файл fmod.dll в папке мода "opbt", то мод также успешно запустится, и при этом можно выходить из него без зависания.

Зависание при выходе происходит когда загружена библиотека fmod.dll

**Comment by Vladislav4KZ** [comment]
> В Operation Black Thunder если переименовать файл fmod.dll в папке мода "opbt", то мод также успешно запустится, и при этом можно выходить из него без зависания.
> 
> Зависание при выходе происходит когда загружена библиотека fmod.dll

В Poke646 то же самое.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/687c9b004f4477d7e325bf138e16c097f0b60f85
