### ISSUE TITLE
[MOD: Snow War] Артефакты на карте ctf_riverside

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#547]
На местах с артефактами просел фпс (возможно из-за флуда ошибок в консоли)
![ctf_riverside_0000.png](https://user-images.githubusercontent.com/22411953/127629461-e0ca7bcd-3f84-4e3f-a181-5a07c18a5511.png)
![ctf_riverside_0001.png](https://user-images.githubusercontent.com/22411953/127629576-48ba06a3-13cb-4bd9-827c-7bc9fc8f788b.png)
![ctf_riverside_0002.png](https://user-images.githubusercontent.com/22411953/127629638-70417cc7-8280-4727-8619-28bfdcc1b0b1.png)

В консоли такая ошибка:
```
OpenGL Error: GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
```

**Comment by Vladislav4KZ** [comment]
После перезагрузки карты артефакты исчезли, но они могут появляться на других картах

**Comment by Vladislav4KZ** [comment]
Сменил карту, там тоже артефакты но не чёрный цвет а слабые затемнения
![ctf_shiver_0000.png](https://user-images.githubusercontent.com/22411953/127630510-59665ca4-6293-4f7c-801d-2d2a706a0279.png)

**Comment by SNMetamorph** [comment]
После коммита https://github.com/FWGS/xash3d-fwgs/pull/551/commits/51fff6223b17edc5a6f72c789e23814185eb1a11 надо перепроверить этот и подобные ему баги с OpenGL Error, теперь в консоли должна быть более подробная информация

**Comment by Vladislav4KZ** [comment]
```
OpenGL Error: GL_INVALID_OPERATION error generated. Target doesn't match the texture target.
OpenGL Error: GL_INVALID_OPERATION (at D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_rmain.c:916)
```

**Comment by Vladislav4KZ** [comment]
Данный багрепорт был сделан, когда в использовании находилась видеокарта NVIDIA GeForce 9500 GT. Версия драйвера там была 342.01 (финальная версия, окончание поддержки после 2017 года)

На NVIDIA GeForce GTX 1050 Ti данный баг не воспроизводится. Версия драйвера 527.56 (Game Ready)

**Comment by Vladislav4KZ** [comment]
Этот баг всё ещё актуален.

**Comment by Vladislav4KZ** [comment]
Больше не удаётся воспроизвести баг на последнем билде ксаша, скачанного с артефактов GitHub Actions, который успешно скомпилировался для Windows.

Пробовал такие способы:
- Запустить мод с этой картой, при захвате изображения ксаша с помощью OBS Studio
- Сворачивать-разворачивать игру при захвате ксаша в OBS Studio
- Просто сворачивать-разворачивать игру
- Включить Glow FX (Шейдер для NVIDIA C for Graphics)
- Сворачивать-разворачивать игру с включенным Glow FX

Ни в одном из вышеуказанных способов попытки воспроизведения бага, не удалось вызвать артефакты на этой карте.

**Comment by Vladislav4KZ** [comment]
Как я написал в соседнем багрепорте: https://github.com/FWGS/xash3d-fwgs/issues/553#issuecomment-1551059756

Здесь то же самое, артефактов нет, но во время запуска карты, в консоли появляются ошибки (два раза), и больше не появляются в процессе игры.

Данная ошибка:
```
OpenGL Error: GL_INVALID_ENUM error generated. Texture type and format combination is not valid.
```

Проявляется на всех картах мода Snow War.
