### ISSUE TITLE
Проблема с поиском hl.so

### ISSUE THREAD

**Issue by iZarif** [FWGS/xash3d-fwgs#548]
Опять неведомая магия:
Запустил hl под ксашем
Сменил игру на свой мод
"New game" недоступна
полез в папку с модом открыл gameinfo.txt (сгенерированный) там прописано

dllpath    "cl_dlls"
gamedll    "dlls/hl_amd64.dll"
gamedll_linux    "dlls/hl_amd64.so"
gamedll_osx    "dlls/hl_amd64.dylib"

Все так и есть файлы лежат где надо и называются как надо

Потом я решил изменить пути на

gamedll    "dlls/hl.dll"
gamedll_linux    "dlls/hl.so"
gamedll_osx    "dlls/hl.dylib"

и тогда мод начал работать, причем сами файлы я не трогал

Xash3D FWGS 0.20-7b8ec0a (linux-amd64) - версия ксаша

**Comment by nekonomicon** [comment]
Нет никакой проблемы.
Движок автоматически проставляет суффиксы.

**Comment by iZarif** [comment]
> Нет никакой проблемы.
> Движок автоматически проставляет суффиксы.

А почему тогда gameinfo.txt сгенерировался с префиксами?

**Comment by a1batross** [comment]
В этом и проблема, он не должен их подставлять. 

Покажи liblist.gam своего мода.

**Comment by mittorn** [comment]
Если у тебя сборка мода под amd64 и 64битный движок, то и dll назови с суффиксами. Но я не думаю что собирать 64битный мод под венду хорошая идея, движок то у всех 32битный на винде из-за совместимости

**Comment by iZarif** [comment]
> В этом и проблема, он не должен их подставлять.
> 
> Покажи liblist.gam своего мода.

liblist.gam есть да, он с суффиксами, я сам его создавал.

**Comment by a1batross** [comment]
>да, он с суффиксами

А, тогда это не баг. Не вставляйте туда суффиксы
