### ISSUE TITLE
Чёрный экран при запуске half-life

### ISSUE THREAD

**Issue by KomaDi** [FWGS/xash3d-fwgs#554]
Запускаю half-life и просто чёрный экран. Сделал лог, но не знаю выявил ли он проблему
Телефон: poco f2 pro
[Log_2021-08-04_16-59-55.txt](https://github.com/FWGS/xash3d-fwgs/files/6933746/Log_2021-08-04_16-59-55.txt)

**Comment by Vladislav4KZ** [comment]
На последнем билде такая проблема появилась и у меня

**Comment by Vladislav4KZ** [comment]
На последних билдах не должно воспроизводиться.

Этот баг был исправлен в новом лаунчере от Velaron.
