### ISSUE TITLE
[MOD: They Hunger] Некоторые текстуры чёрные

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#555]
![they30_0000.png](https://user-images.githubusercontent.com/22411953/128476545-aef80809-19d1-4dbd-97ac-3ea9ef2039c9.png)![they30a_0000.png](https://user-images.githubusercontent.com/22411953/128476559-294d4742-fad4-44d5-9df9-d924fb4bae53.png)![they30a_0002.png](https://user-images.githubusercontent.com/22411953/128476577-a3115d5b-03a0-4608-92fb-1559fc854f79.png)![they30a_0001.png](https://user-images.githubusercontent.com/22411953/128476566-fb5bae33-551a-40e7-b197-c6a79dcbcf71.png)![they30a_0003.png](https://user-images.githubusercontent.com/22411953/128476607-209ad86d-e41e-4828-97ba-21a8e2f2ec12.png)

**Comment by Vladislav4KZ** [comment]
Заметил на третьем эпизоде They Hunger, также на этих картах в меню вместо текста появились чёрные прямоугольники
![Снимок экрана (46).png](https://user-images.githubusercontent.com/22411953/128476790-83cea358-0a6d-4e47-a936-5466023577c5.png)

**Comment by Vladislav4KZ** [comment]
Мод был запущен с -gldebug, ошибок в консоли  не было

**Comment by Vladislav4KZ** [comment]
Насчёт текста, почти в самом начале игры где игрок берёт зонт, через некоторое время в консоль начинают сыпаться такие ошибки:
```
[2021:08:06|14:05:37] ^3OpenGL Error:^7 GL_INVALID_ENUM error generated. <cap> enum is invalid; expected GL_ALPHA_TEST, GL_BLEND, GL_COLOR_MATERIAL, GL_CULL_FACE, GL_DEPTH_TEST, GL_DITHER, GL_FOG, etc. (136 others).
[2021:08:06|14:05:37] ^3OpenGL Error:^7 GL_INVALID_ENUM error generated. Invalid target.
[2021:08:06|14:05:37] ^3OpenGL Error:^7 GL_INVALID_ENUM error generated. <cap> enum is invalid; expected GL_ALPHA_TEST, GL_BLEND, GL_COLOR_MATERIAL, GL_CULL_FACE, GL_DEPTH_TEST, GL_DITHER, GL_FOG, etc. (136 others).
[2021:08:06|14:05:37] ^3OpenGL Error:^7 GL_INVALID_ENUM error generated. Invalid target.
[2021:08:06|14:05:37] ^3OpenGL Error:^7 GL_INVALID_ENUM (at D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_rmain.c:816)
```
И текст в меню покрылся серыми прямоугольниками

**Comment by nekonomicon** [comment]
А это точно оригинальный They Hunger или какая-то сборка?

**Comment by Vladislav4KZ** [comment]
> А это точно оригинальный They Hunger или какая-то сборка?

Да, это сборка от Team Raccoon с русской озвучкой и заменёнными моделями

Такая проблема была и в оригинальном They Hunger на ксаше, но теперь в обоих версиях текстуры стали нормальные, хотя вчера были чёрные

**Comment by a1batross** [comment]
Потому что дело не в моде.

Дело в кривом драйвере и я примерно понимаю что в ксаше надо переделать,
чтобы и с ними всё работало.

У тебя же NVIDIA? Какая версия драйвера, я со своей карточкой под виндой
попробую.

**Comment by Vladislav4KZ** [comment]
> У тебя же NVIDIA? Какая версия драйвера, я со своей карточкой под виндой
> попробую.

Да, NVIDIA GeForce 9500 GT, версия драйвера 342.01

**Comment by nekonomicon** [comment]
Ну в любом случае лучше сразу уточнять, что используется какой-то ретекстур.
На старом движке были проблемы со спрайтами крови из Trusty pack.

**Comment by Vladislav4KZ** [comment]
> Ну в любом случае лучше сразу уточнять, что используется какой-то ретекстур.
> На старом движке были проблемы со спрайтами крови из Trusty pack.

Текстуры там оригинальные, изменены только таблички с текстом переведённый на русский язык

**Comment by Vladislav4KZ** [comment]
Не воспроизводится на последней сборке движка.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master
