### ISSUE TITLE
[MOD: Team Fortress Classic] Не отправляется сообщение в чат с большой буквой "Я"

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#561]
В Half-Life я могу писать в чат большую букву Я, а в TFC не могу

**Comment by mittorn** [comment]
А нечего быть о себе такого высокого мнениЯ

**Comment by Vladislav4KZ** [comment]
Вот ещё что нашёл, когда пишешь текст содержащие следующие буквы:
кнваподжмиб
ЙУКНГЩЪФЫОЛДЭЯСТЬЮ

То он может не отправиться в чат

**Comment by Vladislav4KZ** [comment]
Если писать слова с указанными буквами и поставить точку или любой другой символ, то сообщение сможет отправиться в чат

**Comment by Vladislav4KZ** [comment]
Но это на локальном сервере, когда подключаешься к серверу из интернета то там нельзя писать любые русские слова без дополнительного символа

**Comment by mittorn** [comment]
Чат фильтруется в серверной библиотеке и на это никак повлиять нельзя
Разве что запатчить.
Надо проверить корректно ли доходит сообщение до сервера. Может быть ты переключил клиент в cp1251, а сервер ожидает utf-8? Если сообщение доходит до серверной библиотеке корректно то вопрос точно не к движку

**Comment by Vladislav4KZ** [comment]
Оказывается, под голдсорсом та же фигня, когда пишешь эти буквы они не отправляются в чат

**Comment by Vladislav4KZ** [comment]
> Может быть ты переключил клиент в cp1251, а сервер ожидает utf-8?

Нет, не переключал, стоит utf-8

**Comment by Vladislav4KZ** [comment]
Вот на сервере @AruMoon в tfc вообще русский текст не отправляется в чат без символов

**Comment by mittorn** [comment]
Тогда репорти в https://github.com/ValveSoftware/halflife
