### ISSUE TITLE
compiled windows gl and software performance issue

### ISSUE THREAD

**Issue by shefben** [FWGS/xash3d-fwgs#563]
Hey, I have a question.

has anyone run into an issue where using the GL renderer gives you terrible FPS? 1-8 fps?

I have compiled fwgs with both vc6 and vs2019  and using waf (for windows) and they give me similar results in release mode.. and debug mode

I'm using sdl 2.0.5

Software mode is 'ok' at best, I typically get 14fps, which is playable...

Just wondering if I have something setup incorrectly or if i'm missing a precomp flag; vs2019 I didn't touch the flags but vc6 flags are:
XASH_SDL,MY_COMPILER_SUCKS,MAINUI_USE_CUSTOM_FONT_RENDER,XASH_LITTLE_ENDIAN,XASH_MSVC,XASH_WIN32

**Comment by a1batross** [comment]
Hi. 

This doesn't seem as incorrect configuration. Though we don't really support VC6, it's very old compiler. And why SDL 2.0.5? It was released like 5-6 years ago I think.

Can you tell what GPU do you have and which drivers are installed? Do you have same problem with prebuilt version?

**Comment by mittorn** [comment]
If you are using GL renderer with software GDI implementation, 1-8fps is OK because it's slow.
Try mesa implementations:
https://github.com/pal1000/mesa-dist-win
msvc6 works "as is" and may break in future versions, we only keeping supporting it in vgui_support library (need for dll loader)

**Comment by a1batross** [comment]
msvc6 isn't really supported anymore.
