### ISSUE TITLE
con_color should be queryable by pfnCvarGetString

### ISSUE THREAD

**Issue by kungfulon** [FWGS/xash3d-fwgs#565]
In original GoldSrc, `con_color` is a CVAR, not a CMD. So mods can query it using `gEngfuncs.pfnCvarGetString`.

One example of mod that queries this is Counter-Strike 1.6. Also I think maybe there're some mods out there would be interested in this value too maybe...

I'm trying to include VGUI2 support into Xash and found out this issue.

**Comment by a1batross** [comment]
I pushed a fix into `con_color_cvar` branch.

Try it, if it works. Can't test it right now.

**Comment by kungfulon** [comment]
Just tested. Querying it is ok, though if want to set it, must quote the value or it will only get the first number as the value.

`con_color "255 255 255"` will work correctly but `con_color 255 255 255` won't. 

In current `master` build `con_color 255 255 255` works correctly.

**Comment by kungfulon** [comment]
IMO mainly it's because currently the code uses `Cmd_Argv( 1 )` as the value, not counting any args follow after it.

This is very minor, though it might be better if it's possible to support it.

**Comment by a1batross** [comment]
>though if want to set it, must quote the value or it will only get the first number as the value.

I don't think that's a bug, unless GoldSrc supports this.

Ok, I will test it later and merge.

**Comment by kungfulon** [comment]
OK I just tested and confirmed that GoldSrc has the same logic.
