### ISSUE TITLE
Запуск amd64 версии движка

### ISSUE THREAD

**Issue by Gr33nEyes** [FWGS/xash3d-fwgs#567]
![image](https://user-images.githubusercontent.com/40704849/129456060-71fc621b-5233-4c85-8086-623cfe4ed6b8.png)

**Comment by nekonomicon** [comment]
Нужно собрать ручками библиотеки из репозитория FWGS/hlsdk-xash3d.

**Comment by a1batross** [comment]
Более того, это бесмысленно если у вас Windows.

**Comment by Gr33nEyes** [comment]
У меня Windows 7 x64 версия, и я не могу просто запустить amd64 версию движка?

**Comment by a1batross** [comment]
64-битная винда умеет запускать 32-битные приложения и делает это лучше
всех.

И так будет пока винда не сдохнет.

**Comment by nekonomicon** [comment]
≥ У меня Windows 7 x64 версия, и я не могу просто запустить amd64 версию
 движка?

Если все игры и моды для GoldSource собраны для x86 windows, кто и главное зачем будет пересобирать их для x64 windows за тебя?
Поддержка amd64 сборок на windows может иметь смысл для UWP и Vulkan-рендера с RTX.
В данный момент они собираются, чтобы были.

**Comment by a1batross** [comment]
>UWP

Это вообще другая дискуссия. Технология мертвая, её нет смысла поддерживать.

А Vulkan RTX рендерер ещё не замержен. Пока да, чтобы было.

**Comment by mittorn** [comment]
А vulkan rtx и не нужен amd64. Бкдем поставлять вместе со специальной сборкой radv когда бэкенд допилят. А невидия сосала, сосёт и будет сосать

**Comment by a1batross** [comment]
Anyway, not a bug.
