### ISSUE TITLE
[MOD: Half-Life:ReSrced] Движок не загружает текстуры высокого разрешения

### ISSUE THREAD

**Issue by Gr33nEyes** [FWGS/xash3d-fwgs#570]
В последнем билде движок не загружает текстуры высокого разрешения

**Comment by nekonomicon** [comment]
Дубль https://github.com/FWGS/xash3d-fwgs/issues/27

А вообще нужно ли оно в движке?
Из того, что реально сделано это пак кривых текстур с генеренных нейронкой под названием ReScred и пак текстур на Quake Remake, от поддержки которого отказались.

**Comment by Gr33nEyes** [comment]
И работает только на его билде автора
