### ISSUE TITLE
Краш при запуске с пути с содержанием кириллицы

### ISSUE THREAD

**Issue by KorteZZ88** [FWGS/xash3d-fwgs#571]

**Comment by mittorn** [comment]
Что-то новое, у нас вроде никакой магии с путями не происходит. А подробнее есть какая-то информация?

**Comment by SNMetamorph** [comment]
![изображение](https://user-images.githubusercontent.com/25657591/129576212-422b2e2f-e796-4b82-acc0-13bcc29caebb.png)

**Comment by KorteZZ88** [comment]
![image](https://user-images.githubusercontent.com/78810011/129576597-e82e339b-9da2-456b-bf14-7841d425f2d6.png)

**Comment by nekonomicon** [comment]
А с кириллицей в начале пути примеры есть?
Зачем использовать кириллицу в названии рабочей папки и названии ресурсов?

**Comment by Vladislav4KZ** [comment]
> А с кириллицей в начале пути примеры есть?

D:\Ксаш3D\New Engine, тоже не запускается
![Снимок экрана 2021-08-16 205654.png](https://user-images.githubusercontent.com/22411953/129584690-43c6f331-4953-4700-b182-c15464374bba.png)

**Comment by mittorn** [comment]
винда опять не осилила кодировки. Я так понимаю, там ascii вызов используется, а они не могут в utf-8. А откуда utf-8 путь пришёл - из SDL?

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/host.c#L983
Собственно тут и есть баг - путь получен через SDL, а выставляется виндой. Или получать его надо виндой же, или выставлять через SDL

**Comment by mittorn** [comment]
Ещё как вариант поставить локаль UTF-8 для не-unicode функций, windows научился это делать недавно:
https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

**Comment by mittorn** [comment]
С одной стороны это сразу должно поправить utf-8 во всяких виндовых диалогах, с другой может сломать если где-то в коде будет что-то в cp1251 в модах
