### ISSUE TITLE
Исчезает прицел при наводке на NPC или игрока

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#575]
Когда автоприцеливание включено (sv_aim 1) исчезает прицел когда наводишь его на NPC или игрока.

В GoldSource он не исчезает а смещается с центра экрана и наводится на противника

**Comment by Vladislav4KZ** [comment]
Проверил в старой версии Xash3D FWGS там такой проблемы нет

**Comment by Vladislav4KZ** [comment]
И в последней версии ксаша от Дяди Миши автоприцел тоже нормально работает

**Comment by mmillar-bolis** [comment]
I can confirm that this is a problem when `sv_aim` is set to `1`. Sometimes, it is affected by an enemy, and sometimes it is affected by where the player is looking or standing on a map. I have attached screenshots with pos coordinates to help in reproducing the issue.

I am using `Xash3D FWGS 0.20-dd90262 (2021-08-27 continuous build)` and `hl.dll` and `client.dll` from [hlsdk-xash3d](https://github.com/FWGS/hlsdk-xash3d/tree/master/dlls) commit `136ee78`, built with MSVC6.

I can also reproduce this with the OpFor dlls, so I believe it is an engine issue.

![t0a0_0000](https://user-images.githubusercontent.com/62162171/132111408-47612959-df76-4089-9459-74ed0dacde68.png)
![t0a0_0001](https://user-images.githubusercontent.com/62162171/132111409-a8ebadcd-a9ef-4b80-9c74-6236f1fb7a73.png)

**Comment by a1batross** [comment]
Fixed.
