### ISSUE TITLE
[MOD: Rocket Crowbar 2] Краш при смерти игрока

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#576]
```
assert failed at D:\a\xash3d-fwgs\engine\server\sv_game.c:4153
```

**Comment by a1batross** [comment]
@Vladislav4KZ возможно, это тоже исправлено в 4c02c255065e28938af35a2f1930495c090fdfdd.

**Comment by Vladislav4KZ** [comment]
> возможно, это тоже исправлено в https://github.com/FWGS/xash3d-fwgs/commit/4c02c255065e28938af35a2f1930495c090fdfdd

Верно, именно после этого коммита мод перестал крашиться при смерти игрока.
