### ISSUE TITLE
[MOD: Space Prisoner] Мигает фонарик

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#577]
В определённой карте фонарик мигает, а в начале игры он работал нормально

https://youtu.be/mCK0ywLDfBw

**Comment by Vladislav4KZ** [comment]
Также, на видео модель оружия стала чёрной хотя в игре она выглядела нормально как до записи, во время и после записи видео.

**Comment by Vladislav4KZ** [comment]
Вот сохранение игры на этой карте
[flashlight.zip](https://github.com/FWGS/xash3d-fwgs/files/7012333/flashlight.zip)

**Comment by Vladislav4KZ** [comment]
Также заметил в моде Times of Troubles

**Comment by Vladislav4KZ** [comment]
Тоже самое и в The Conspiracy in Shadow

**Comment by a1batross** [comment]
Проверил в текущей версии, на твоём сохранении, фонарик не мигает. Исправлено? Надеюсь...
