### ISSUE TITLE
[MOD: Base Defense] Невозможно запустить сервер с выключенным режимом разработчика

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#578]
Запустил ксаш с параметрами -console -game bdef, не могу создать сервер

Когда запускаю с параметрами -dev -game bdef то я могу создать сервер в игре

**Comment by Vladislav4KZ** [comment]
Проблема решается сменой значения параметра ``mp_entity`` в gameinfo.txt с ``info_player_deathmatch`` на ``info_player_start``

**Comment by a1batross** [comment]
Я бы этот механизм вырезал честно говоря.

`mp_entity` имеет смысл только для фильтрации карт в списке (и то, современные версии GoldSource на него не полагаются). А вот запрещать заходить на карту если в ней нет точки спавна глупо. В конце концов, мод это поведение может переопределять как угодно.

**Comment by a1batross** [comment]
cc @mittorn @SNMetamorph 

Есть мысли по этому поводу? Мы уже отключали механизм детекта зацикленных чейнджлевелов -- из-за его лишних срабатываний. Я думаю, и этой проверке не место в движке.

**Comment by SNMetamorph** [comment]
Думаю, эта проверка бессмысленна. Это же движок лезет в зону ответственности игровой библиотеки.

**Comment by mittorn** [comment]
А как голдсорс удаляет сингловые карты из списка? Мне вообще не 
нравится, что он парсит ентити ради списка карт

Проверку лучше убрать

**Comment by a1batross** [comment]
@mittorn раньше был mpentity ключ в liblist.gam который парсил список энтитей и карты, где были "мультиплеерные" энтити, появлялись в списке. Дядя Миша это расширил это до такой проверки, чтобы не загружать карты без спавна. Но это ко всему прочему влияет и на синглплеер через ключ sp_entity в gameinfo.txt.

Сейчас mpentity заменён ключом mpfilter. С ним движок выкидывает из списка все карты в названии которых есть подстрока из mpfilter.

**Comment by a1batross** [comment]
156b2b2b10edc3a92c768036ce6fe99c8264255a
