### ISSUE TITLE
Windows: Quitting multiplayer crashes when closing sockets

### ISSUE THREAD

**Issue by x6herbius** [FWGS/xash3d-fwgs#58]
The crash occurs in `NET_Config`, net_ws.c:1599. The socket is number 2168 on my machine, which doesn't look like an invalid value, but the stack trace shows that `_invalid_parameter_noinfo` is called by the `close` function.

**Comment by a1batross** [comment]
Oh, it should be closesocket, not close.

**Comment by a1batross** [comment]
Check, I've fixed it in 386a68e334986a41545b40d68ef90645916916f7.

**Comment by x6herbius** [comment]
Thanks!
