### ISSUE TITLE
Останавливается музыка при смене карты

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#580]

**Comment by Lamenich** [comment]
так это вроде и в обычной халве на golsrc также....

**Comment by AruMoon** [comment]
да, на голде есть такая проблема, но в xash3d было исправлено и должна продолжать играть с момента, где была пауза

**Comment by Vladislav4KZ** [comment]
> так это вроде и в обычной халве на golsrc также....

Прикинь, на старых версиях голдсурса этой проблемы не было, как и на старой версии ксаша

**Comment by Lamenich** [comment]
> > так это вроде и в обычной халве на golsrc также....
> 
> Прикинь, на старых версиях голдсурса этой проблемы не было, как и на старой версии ксаша

тогда хз

**Comment by mittorn** [comment]
Блин, извечные проблемы с этой фоновой музыкой, надо тестировать отдельно

**Comment by Vladislav4KZ** [comment]
В последней сборке данное поведение не наблюдается.
