### ISSUE TITLE
[MOD: The Infected] Невидимые кнопки в меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#581]
![Screenshot_20210821-171535.png](https://user-images.githubusercontent.com/22411953/130320093-b8294d33-d429-4f8d-acee-d25f7842ae29.png)

**Comment by Qwertyus3D** [comment]
Это проблема модифицированного btns_main.bmp. Он по умолчанию должен иметь палитру 256 цветов, а автор мода вложил полноцветное изображение. В движке для интерфейса много разных ограничений, которые под ГолдСорс порой игнорятся, а в Ксаше привязаны к тому "как должно быть". И нестандартная глубина цвета вызывает подобные баги. Иногда бывает, что попадается и неправильно работает картинка с цветностью меньше 8 бит, кто-то ухитряется в 4 или даже в 1 бит сохранять.

**Comment by a1batross** [comment]
https://github.com/FWGS/mainui_cpp/commit/d5ae1187e0e849869b026ef92ffc22a8fa62b7ed 

Пофиксил. Достаточно вроде как просто стрипнуть альфу.
