### ISSUE TITLE
[MOD: Vengeance & Rebellion | Remod] Чёрная кровь при свете фонарика

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#584]
Вот так выглядит жёлтая кровь без фонарика
![smip10_0001.png](https://user-images.githubusercontent.com/22411953/130550446-57afd5b6-12bd-450d-8605-435725063427.png)

А вот с включенным фонариком
![smip10_0000.png](https://user-images.githubusercontent.com/22411953/130550512-2e1acfb8-06d0-4efd-ab56-a3e07bd5c4f3.png)

**Comment by Vladislav4KZ** [comment]
А вот когда светишь с другой стороны, она вообще становится зелёной
![smip10_0002.png](https://user-images.githubusercontent.com/22411953/130550698-29a7279c-5131-4d22-ab1a-dc04d17ee1aa.png)

Кровь должна быть жёлтой, от убитых пришельцев

**Comment by mittorn** [comment]
r_vbo 0
Динамическое освещение декалей слишком накладным выйдет

**Comment by a1batross** [comment]
Should be fine with vbo-fix merge. Reopen if it's still broken.
