### ISSUE TITLE
Предварительный просмотр изменения яркости не работает в реальном времени

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#585]
В настройках видео когда регулируешь уровень гаммы изменения видны сразу на картинке, а когда регулируешь яркость на картинке предпросмотра изменений нет. Но как только начнёшь опять регулировать гамму, картинка станет более или менее яркой, в зависимости от уровня яркости настроенного ползунком

**Comment by Vladislav4KZ** [comment]
https://streamable.com/iqv082

**Comment by mittorn** [comment]
https://github.com/FWGS/mainui_cpp/blob/master/menus/VideoOptions.cpp#L166
Тут сделать то же самое для второго слайдера

**Comment by Vladislav4KZ** [comment]
Пофикшено в коммите https://github.com/FWGS/mainui_cpp/commit/d0240161f0a1ac34a8fcd056a21bd641df755f2b (mainui_cpp)
