### ISSUE TITLE
Квар cl_righthand 1 выворачивает модели наизнанку

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#586]
![Screenshot_20210825-105659.png](https://user-images.githubusercontent.com/22411953/130729061-ef0a3e1b-7e6b-425e-ab7c-7b40105aaafd.png)![Screenshot_20210825-105720.png](https://user-images.githubusercontent.com/22411953/130729084-698b183e-9f54-4bbf-bdd0-8f75307deb43.png)

**Comment by a1batross** [comment]
Он и не поддерживается вне Counter-Strike.
