### ISSUE TITLE
Instructions to build it for Android

### ISSUE THREAD

**Issue by sergioroprado** [FWGS/xash3d-fwgs#590]
The instructions to build for android would be really appreciated. Thanks.

**Comment by Adnan1091** [comment]
It would be better to port mods to work on new engine(20).

**Comment by nekonomicon** [comment]
> It would be better to port mods to work on new engine

It would be better to test all existing mods on x86 windows under new engine to make it more stable.

**Comment by a1batross** [comment]
@sergioroprado I don't understand why do you want to build your own engine specifically for Android. There is CI builds which must be fine.

Anyway, we only support building on Linux and there is scripts available used for GitHub Actions, which could be used as a guide, unless there is no actual documentation for it.

**Comment by Adnan1091** [comment]
@nekonomicon Can't we test it on android though?

**Comment by nekonomicon** [comment]
@Adnan1091 you can test mods from this list:
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/supported-mod-list.md#list-of-half-life-based-mods

**Comment by Adnan1091** [comment]
Games that doesn't require custom dll works fine.I have problem with the mods that require custom dll.I can't build it cuz i don't have a PC.Are there any mods that require custom dll,has updated to make it work on new engine?

**Comment by nekonomicon** [comment]
@Adnan1091 if you doesn't have PC you probably do not know how this mods must work under GoldSource.
Some simple mods currently will work out of the box:
https://github.com/FWGS/hlsdk-xash3d/blob/mobile_hacks/dlls/moddef.h

**Comment by sergioroprado** [comment]
@nekonomicon @a1batross 

I would like build the android apk myself because i wanna play Blue Shift on this new engine Xash3D. Let me explain:

The BSLauncher/BS-android depends of the app Xash3D to run Blue Shift. In this case, the BSLauncher need the Xash3D app package with the name "in.celeste.xash3d.hl".

The deprecated Xash3D app used the package name "in.celeste.xash3d.hl", but this new Xash3D changed the app package to "su.xash.engine". This change made the BSLauncher unable to use the new engine Xash3D.

To make the BSLaucher work with this new Xash3D, first i tryed to buid myself a modded version of BSLauncher, but it always fail when i try to build it. Then i thought in another aproach: change back the app package of this new Xash3D to the old "in.celeste.xash3d.hl".

English isn't my main language, so i apologise if is hard to understand what i said.

**Comment by AruMoon** [comment]
You don't need BS launcher yet

**Comment by a1batross** [comment]
@sergioroprado there is a reason why support for old mods is dropped.

1. We added arm64 support and due to how mod support is working, that will lead to broken mods. None of them support arm64.
2. We dropped support for hard-float ABI on armv7 due to NDK changes.

That said, you still can play bshift on new engine. It's now packaged with "mobile_hacks" libs that dynamically detect game and enable simple hacks for them. Bshift will just work there without a change.

**Comment by sergioroprado** [comment]
@a1batross Can you please give me some instructions? Were i can find this "mobile_hacks"?

**Comment by a1batross** [comment]
You don't need to. Just download latest testing build: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

**Comment by sergioroprado** [comment]
@a1batross I have both Half Life and Blue Shift inside the "xash" folder. Half Life is inside "valve" subfolder and Blue Shift on "bshift" subfolder. Half Life runs fine, but Blue Shift can't be detected by the app. What could be the problem?

**Comment by nekonomicon** [comment]
@sergioroprado Just run Xash3D FWGS with `-game bshift` parameters.

**Comment by sergioroprado** [comment]
@nekonomicon Thank you.

**Comment by Adnan1091** [comment]
It's off topic but when will the immersive mode bug will be fixed?Navbar doesn't go off.It will nearly be one year since i reported this bug.One more guy also reported it but it was closed  since it was duplicate.

**Comment by a1batross** [comment]
🤷🏼

**Comment by MarcoffGX** [comment]
excuse me, I want to ask a question about building a xash3d machine on Android using Termux, does anyone know what to install into this apk, so I can work on building mods on my android.. 

Please help. 🙏

**Comment by MarcoN0nt4h** [comment]
@a1batross  can this SDK be built via android application (Android-IDE / AIDE) ?

**Comment by a1batross** [comment]
@MarcoN0nt4h no. 

Use PC to develop mods.

**Comment by RandomFinn** [comment]
> You don't need to. Just download latest testing build: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous

How do I download it to android? Or Am i missing something? Or am i just stupid

**Comment by AruMoon** [comment]
> > You don't need to. Just download latest testing build: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous
> 
> How do I download it to android? Or Am i missing something? Or am i just stupid

It's now available on Play Market as early version

**Comment by RandomFinn** [comment]
> > > You don't need to. Just download latest testing build: https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous
> > 
> > 
> > How do I download it to android? Or Am i missing something? Or am i just stupid
> 
> It's now available on Play Market as early version

It's really crap, i ran half life once, then quit, and it never opened again

**Comment by a1batross** [comment]
@RandomFinn we don't have another one, so...

send issues to https://github.com/Velaron/xash3d-android-project

**Comment by Vladislav4KZ** [comment]
@a1batross wrong repository.

Issue tracker is here: https://github.com/Velaron/xash3d-fwgs
