### ISSUE TITLE
mp3 play воспроизводит музыку только с папки media

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#592]
Из-за этого например в кроссплатформенной версии мода The Gate не играет музыка, в консоли выдаёт ошибку
```
FS_OpenStream: couldn't open "media/sound/mp3/название саундтрека"
```

**Comment by a1batross** [comment]
Fixed in 398cec626e41896e0fd290081eaab7e2974d35b8
