### ISSUE TITLE
OpenXR support opposed to OpenVR

### ISSUE THREAD

**Issue by HeadClot** [FWGS/xash3d-fwgs#60]
Hey just a suggestion,
Opposed to using OpenVR which is limited to Steam VR supported headsets. It would probably be beneficial to support Open XR instead. Why I say this is that Xash could support a wider variety of VR headsets via this API.

More details here -> https://www.roadtovr.com/openxr-1-0-release-microsoft-hololens-vr-oculus-rift-quest/

**Comment by a1batross** [comment]
Yes, I know about it. I waited for OpenXR release to continue working on 0.20-vr branch. :)

**Comment by HeadClot** [comment]
OK, This is good to know. Thanks for the heads up :)

**Comment by a1batross** [comment]
OpenXR is the only option for VR nowadays.

While there is no anything VR related in development, it still planned. Patches welcome.
