### ISSUE TITLE
[MOD: The Real] Двойная анимация взмаха монтировки

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#600]
На GoldSource в этом моде анимация у монтировки нормальная

**Comment by nekonomicon** [comment]
Проблема на самом деле в моде.
Там 2 анимации под ряд в клиентской dll отрабатывает, но GoldSource это как-то обходит, а ксаш нет.

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/51945f002b8ad272e60149666fbbe1b22c37cba3
