### ISSUE TITLE
Просвечиваются объекты в воде когда включен VBO рендер

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#605]
С VBO
![1rocks_0001.png](https://user-images.githubusercontent.com/22411953/131509643-5dc31199-7df9-497b-9472-60e157179171.png)

Без VBO
![1rocks_0003.png](https://user-images.githubusercontent.com/22411953/131509693-b6c74d02-47cb-4020-9c3c-83a16c5e5f3d.png)

**Comment by a1batross** [comment]
Moved to #700
