### ISSUE TITLE
a lot of issues (libxash.so, client.so and sound)

### ISSUE THREAD

**Issue by DannyXjsu** [FWGS/xash3d-fwgs#609]
I am using **Arch Linux (amd64)** and I've built Xash3D from code, but I wasn't able to get it working properly and faced many issues.

## libxash.so

I followed the instructions, made a folder called xash3d, put the binaries inside and copied the valve folder inside it, when I ran `./xash3d`, it gave me to following error:

`Xash Error: Unable to load the libxash.so: libxash.so: cannot open shared object file: No such file or directory`

Very strange because that library is inside the directory, I searched if anyone had the same problem and found (#154) that you need to run:

`LD_LIBRARY_PATH=$(pwd) ./xash3d`

So it could find the libraries that are in that same directory that xash3d is, but after running that, it gave me another error.

## client.so

`Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory`

I checked inside the valve folder to make sure it was inside cl_dlls, it was.

I tried fixing by copying everything inside the valve folder outside of it, so it's in the same directory xash3d is, but that didn't work. I put everything back to the valve folder then I ran xash3d with `-help` and found the `-clientlib` parameter, then I put `-clientlib 'valve/cl_dlls/client.so'` but for some reason it didn't work, I also tried all of the following:

`-clientlib '~/xash3d/valve/cl_dlls/client.so'`

`-clientlib '$(pwd)/valve/cl_dlls/client.so'`

`-clientlib '/home/user/xash3d/valve/cl_dlls/client.so'`

None of it worked.
I thought that it wasn't able to read valve's client.so, so I cloned hlsdk-xash3d and built the libraries myself and put then inside the cl_dlls directory and it also didn't work, then I finally decided to put the client.so and hl.so (that came with building hlsdk-xash3d) in the same directory xash3d is and using `-clientlib 'client.so'` and it finally worked, it showed the main menu of the game but then another problem arose; no sounds.

## ALSA lib

To make sure that the game isn't muted:
![image](https://user-images.githubusercontent.com/11770219/132082830-c2c17125-dfa6-407c-a7de-6c0f357ccc45.png)

In the terminal it gave me:

`ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: cannot open shared object file: No such file or directory)`

I searched around and couldn't find anything Xash3D related, only Lutris and others, their fixes didn't apply here.
I gave up on trying to find a solution for this.

## IMO

If those issues are already known and there are already fixes for them, they should be well documented. But there is no wiki and I found that the README.md was lacking a lot and didn't cover a few things (such as what to do with the libraries you've built and where they are located and where do you need to put them, I had to figure it myself).
Turns all of the documentation is in the old repository of Xash3D, I only came to find out about it as I was writing this. I do not know much about the Xash3D project and why it has two repositories but if in the future, this new repository is planned to be the main one, the least thing one could do is copying over the old wiki and updating it.

I hope that the issues I brought up can help making this project better.

**Comment by AruMoon** [comment]
Check libraries and binary with `file` (sudo pacman -S file) if they are 64-bit or 32-bit. All compiled libraries you can find in folders in the `build` folder where you built that. Or you can compile single binary using `--single-binary` parameter when configuring waf

**Comment by DannyXjsu** [comment]
they are all 32 bits
![image](https://user-images.githubusercontent.com/11770219/132108687-9679a0e1-0604-47f0-8518-b7efe7b6754b.png)

**Comment by nekonomicon** [comment]
> Host_InitError: can't initialize cl_dlls/client.so: vgui.so: cannot open shared object file: No such file or directory

You need to have vgui.so from steam.

> ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: cannot open shared object file: No such file or directory)

This trouble related to your linux distributive.
Engine does not use alsa directly, so something wrong with sdl2 package in arch linux.

**Comment by a1batross** [comment]
Updated README with explanation of this issue.
