### ISSUE TITLE
Drop of OSX/iOS support

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#61]
We won't support OSX/iOS anymore because of destructive decisions Apple make. 

Yesterday they removed 32-bit and ok, it's was kinda understandable.
Today they will remove OpenGL for no reason.
Tomorrow they will remove possibility of running native code.

Originally, OSX/iOS support was added because it was easy to maintain, but when it rеquires more action from us, I don't think we can support it without a dedicated maintainer for this platforms. 

Platform code will not be removed, so someone can take it and continue support but I will remove OSX/iOS ports from autobuilds, will not provide them in releases, close all rеlated issues as WONTFIX and finally remove it from list of supported ports.

So, Apple, f*ck you.

**Comment by a1batross** [comment]
>Tomorrow they will remove possibility of running native code.

They actually did it, sort of. https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by pcgamer31098** [comment]
> Today they will remove OpenGL for no reason.
OpenGL wasn't removed from macOS, it was only deprecated.

**Comment by a1batross** [comment]
So... what? If something is deprecated, then it's not guaranteed to work, not supported, may be deleted at any time, I need to continue?

**Comment by pcgamer31098** [comment]
I just meant that OpenGL is still available on macOS for now, and it's not removed.

**Comment by pcgamer31098** [comment]
I don't know about iOS though.

**Comment by byQyadrixx** [comment]
`unban me - _-`

**Comment by zaptrem** [comment]
@a1batross could [this](https://github.com/kakashidinho/metalangle) project work as a drop-in solution to get iOS support working? It seems simple, just let Google/ANGLE devs deal with Apple while you work on what matters.

**Comment by a1batross** [comment]
Thanks for pointing at this! I thought about translating gles2 to vulkan
with angle, then translating it to metal with moltenvk which is apparently
free and open source now...

But the problem with iOS/OSX support is not because Apple wants to break
software. Everyone breaks software actually, Googleshit does it(every
Android update breaks more and more apps because of MUH SECURITY),
Microsoft tried to do this but failed(UWP).

The problem is the lack of devices. I'm not planning to have dedicated Mac
or iPhone/iPad just to fullfil the wishes of 3.5 users of Xash3D FWGS on
Apple OSes. I doubt @mittorn (active engine developer) or @nekonomikon (BSD
port maintainer) wants it too.

I'm looking at @Ichicoro, he seems to be interested in Apple OS ports but
remember developing this engine is completely enthusiastic work.

вт, 28 апр. 2020 г., 0:00 zaptrem <notifications@github.com>:

**Comment by zaptrem** [comment]
I do all of my iOS development in a VMware VM of MacOS on a Windows host. Though it's a little slow, I think the same thing might work for running the necessary test cases before release.

Here's a tutorial as well as a download for a premade MacOS VM if you're interested: https://techsviewer.com/how-to-install-macos-10-15-catalina-on-vmware-on-windows-pc/

**Comment by a1batross** [comment]
@zaptrem if you're so smart, do it yourself.

**Comment by mittorn** [comment]
@zaptrem 
If you need it, port it. It should be easy because of SDL2. The hardest is filesystem integration and some launch UI

**Comment by zaptrem** [comment]
I’m just trying to be helpful, you don’t need to attack me. I know nothing about graphics programming so I’m afraid I wouldn’t be much help.

**Comment by a1batross** [comment]
You don't have to. Porting engine is simple, as briefly described in
engine_porting_guide.md.

I'm not attacking you. Just don't think we(in FWGS) aren't disscussed this.
Actually before the OSX/iOS drop, I did maintained OSX port and mittorn
maintained iOS port. We've worked on this without having a devices, just
with virtual machines.

It worked out... but not for long, because things started to break which
lead us to this announcement.

Even if maintaining is not that hard, virtual machines are just a
playground and too far from real hardware. It doesn't worth our time. At
least my time, because after I upgraded to Ryzen CPU, my OSX VM started to
fail to boot.

**I just don't want to waste time on fighting mills anymore**.

вт, 28 апр. 2020 г., 20:42 zaptrem <notifications@github.com>:

**Comment by zaptrem** [comment]
It seems that file doesn't exist in this repo. 
![image](https://user-images.githubusercontent.com/1612230/80527290-217f1b80-8962-11ea-8a31-fd9c3022e6ac.png)

**Comment by nekonomicon** [comment]
@zaptrem Just open `Documentation` folder.

**Comment by Ichicoro** [comment]
@zaptrem I made an iOS port recently. It hasn't been merged yet, because I do need to clean up the code a bit, but if you're interested, you could DM me @Ichicoro#3127 on discord and we could talk about it :)

**Comment by rspeed** [comment]
> They actually did it, sort of.

Am I missing something? That's an entirely optional extra step and still results in native code.

**Comment by a1batross** [comment]
@rspeed 

I won't ask them like "please apple sign my software please". Still I don't want my software to be called insecure just because Apple didn't signed it.

That probably would not be a problem if I used Apple devices but I have __none__ and Hackintosh im VM isn't really usable(also it doesn't work on Ryzen for some reason).

If you want, you're free to maintain port. But personally I don't want to, Apple is disgusting.

**Comment by rspeed** [comment]
> I won't ask them like "please apple sign my software please". Still I don't want my software to be called insecure just because Apple didn't signed it.

Which isn't the case. The only difference is that notarized apps have a note reading "Apple checked it for malicious software and none was detected."

**Comment by a1batross** [comment]
Then what's the reason for App Store to exist? If user deliberately downloaded an executable file bypassing App Store, they know what they do.

Well, now they using App Store to censor everyone they don't like. It's only a matter of time when notarization will be used to just reject everyone who is against of Apple's walled garden.

**Comment by ChrisPHardin** [comment]
It's 2023 and the 2018 build still works on a modern non-jailbroken iPhone with the latest iOS just fine. The only things not working are controllers. So I don't get all the fuss, it couldn't have been THAT hard to maintain it or at least update the controller support. I'm not an experienced developer but will try to look into doing it myself.

**Comment by rspeed** [comment]
> It's only a matter of time when notarization will be used to just reject everyone who is against of Apple's walled garden.

Do you have a timeline for this?

**Comment by a1batross** [comment]
@rspeed looks like it didn't happen after all.

But can't say we ever broke OSX here intentionally either. It's just nobody wants to step in and support it, it's a dead platform with no users.

**Comment by a1batross** [comment]
By the way, code signing kinda became mandatory on Windows as well because otherwise its built-in AV software always thinks your software is some kind of malware. And I absolutely despise Microsoft for that.

**Comment by mittorn** [comment]
mingw seems to be already dropped :(
What about proprietary msvc, the worst compiler?

**Comment by a1batross** [comment]
@rspeed well I already did. There is another person maintaining Windows port, as noted in Documentation/ports.md.

**Comment by a1batross** [comment]
As @mittorn said, MinGW is gone, and only latest MSVC versions are supported now. That's whole Windows support it got. I almost don't use Windows, but there is @SNMetamorph who is willing to maintain a port.

So if you're so frustrated by missing Mac support, you can take responsibility and step up as a Mac port maintainer, and I won't even stop you despite having bad attitude towards Apple.

I think that case is closed.

**Comment by Ichicoro** [comment]
> By the way, code signing kinda became mandatory on Windows as well because otherwise its built-in AV software always thinks your software is some kind of malware. And I absolutely despise Microsoft for that.
> 
> Not that I loved these big tech corporations anyway.

That's... very much not true? I have a fairly standard Windows 11 setup and I haven't encountered any issue with unsigned software

**Comment by Velaron** [comment]
> > By the way, code signing kinda became mandatory on Windows as well because otherwise its built-in AV software always thinks your software is some kind of malware. And I absolutely despise Microsoft for that.
> > Not that I loved these big tech corporations anyway.
> 
> That's... very much not true? I have a fairly standard Windows 11 setup and I haven't encountered any issue with unsigned software

And then there are multiple issues with people that do have this problem :/

**Comment by Buggem** [comment]
macOS is pretty shitty when it comes to opensource software but Xash3D works after some hacking. I really don't blame Apple for their "walled garden" approach, they are just trying to protect the average user (not programmers like you or me).

**Comment by Razcoina** [comment]
> I really don't blame Apple for their "walled garden" approach, they are just trying to protect the average user (not programmers like you or me).

If every OS did that, we would have no programmers in a few years.
