### ISSUE TITLE
What happened to xash 3d ios?

### ISSUE THREAD

**Issue by Darthveder69420** [FWGS/xash3d-fwgs#610]
Why is it discontinued?

**Comment by a1batross** [comment]
No people to maintain it.

And Apple can go eat shit.

**Comment by Darthveder69420** [comment]
Welp. I am guessing part of the reason is apple doing shit that make developing harder. Do is there any ipa of the old engine that I van download. Just wanna see how half life works on an ipad.

**Comment by a1batross** [comment]
I'm not sure... 

It was too long ago. :(

**Comment by Darthveder69420** [comment]
Sadge

**Comment by Darthveder69420** [comment]
Nevermind I found an ipa that works on ios 14

https://github.com/FWGS/xash3d-deploy/blob/ios-port-master/README.md


You need to download the output 64 version for it to work.

**Comment by mittorn** [comment]
Just port it yourself if you need it. Porting should be very easy now

**Comment by Darthveder69420** [comment]
How?

**Comment by chinalhx** [comment]
> Just port it yourself if you need it. Porting should be very easy now

do u have email？cuz,I develop ios project have some question wanna ask u！pls help：（

**Comment by mittorn** [comment]
Use waf ios targets or xcode project generator

**Comment by Darthveder69420** [comment]
I don’t have a pc.
