### ISSUE TITLE
Сломанные env_bean в режиме ring при активации далеко от игрока

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#614]
Вот пример карты: [test_sprite.zip](https://github.com/FWGS/xash3d-fwgs/files/7147966/test_sprite.zip)
Если запустить в xash то и подойти к самой последней "витрине" то там никаких кольцевых лучей не видно.
А вот в goldsrc их видно.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/190e4a5e8a088d5017e5aa450c9cdac1f22906bc
