### ISSUE TITLE
прямой IP

### ISSUE THREAD

**Issue by santi10218** [FWGS/xash3d-fwgs#616]
Они знают, как подключиться к конкретному серверу по ip. Пример: Подключитесь к этому серверу 192.168.1.0:00000

**Comment by AruMoon** [comment]
Write on English please, if you don't talk on Russian
You cannot connect to GoldSrc servers. Only Xash3D FWGS

**Comment by Vladislav4KZ** [comment]
Почему это до сих пор висит в issues? Это и не багрепорт и не вопрос связанный с движком. Какой-то непонятный текст на ломанном русском
