### ISSUE TITLE
Failures in experimental resolution

### ISSUE THREAD

**Issue by XGhostRX** [FWGS/xash3d-fwgs#618]
I have seen that there are bugs on the buttons when using the experimental resolution, I think that problem should be corrected at once

**Comment by 100NOC4Oyt** [comment]
Go to recent apps and go back to the game. Solved

**Comment by 100NOC4Oyt** [comment]
> I have seen that there are bugs on the buttons when using the experimental resolution, I think that problem should be corrected at once

Go to recent apps and go back to the game. Solved
