### ISSUE TITLE
[MOD: Opposing Force] Нет звука телепортации у displacer'а

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#619]
Используется оригинальная Steam версия Half-Life Opposing Force на Xash3D FWGS 0.20.1 для Windows.

На голдсурсе звук телепортации у displacer есть а на ксаше нет

**Comment by Vladislav4KZ** [comment]
https://www.youtube.com/watch?v=qaRW082bHlc

У ксаша звук телепортации заработал только 1 раз после сворачивания/разворачивания игры

**Comment by mittorn** [comment]
а как себя ведёт при включенном/выключенном cl_lw и cl_nopred?

**Comment by Vladislav4KZ** [comment]
> а как себя ведёт при включенном/выключенном cl_lw и cl_nopred?

Тоже звук появился только один раз и больше не появлялся.

В синглплееере кстати звук есть всегда

**Comment by a1batross** [comment]
https://github.com/FWGS/Xash3DArchive/commit/ae84eccc6f7510d9e1ce007cc2f91a8a14f81abc

Возможно связано с этим.

При телепортации проигрывается звук displacer_self.wav на начальной позиции игрока, который должен отсекаться по PAS. Ксаш делает проверку по PVS, но с большим радиусом. Я пока не понимаю почему.

**Comment by a1batross** [comment]
Проблема исправилась с:

1) Реализацией PHS. Это одно и то же, что и PAS, id Software назвали его Potentially Hearable Set, Valve его называет Potentially Audible Set. Заранее посчитанный PHS присутствует только в картах формата Quake 2, в QuakeWorld и Half-Life он просчитывается из PVS. Вычисление относительно быстрое, но и памяти с повышением количества листьев в BSP жрёт в геометрической прогрессии (хорошо хоть в сжатом виде). Так как он нужен только для сервера и только для мультиплеера, вычислять я его планирую только в этих случаях.

2) Удалением вот [этого](https://github.com/FWGS/xash3d-fwgs/blob/0848f28d831319f3e63019f93a1815f2d12c13f1/engine/server/sv_game.c#L4289-L4305). Ксаш зачем-то запоминает позицию положения камеры игрока в этой функции и вдальнейшем её использует для [исключения](https://github.com/FWGS/xash3d-fwgs/blob/0848f28d831319f3e63019f93a1815f2d12c13f1/engine/server/sv_game.c#L342) по PVS/PHS того, что не должен видеть/слышать игрок. Но именно такой порядок приводит к тому, что позиция камеры записанная в `pfnSetFatPVS` не совпадает с реальной позицией игрока, и соответственно камеры.

В ближайшее время создам PR для тестирования этих изменений.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/338399e622200b748f96b2daea7104ec7e614f6a 

Решил закоммитить как есть, ибо я уже пару дней гоняю с этими изменениями, внося только мелкие правки. Тем более, PHS включается только для мультиплеера.
