### ISSUE TITLE
[Windows] [OpenGL] Чёрные вьюмодели оружия на записи экрана

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#620]
Игра записываться через Open Broadcaster Software (OBS) Studio

Во время записи видео, оружия в игре отображаются нормально, но в записанном видео они чёрные

**Comment by mittorn** [comment]
Давай ты не будешь репортить баги которые видно только на записанном видео сюда. Это не баг движка и наверняка в другом opengl софте тоже есть артефакты на записи

**Comment by AruMoon** [comment]
> Игра записываться через Open Broadcaster Software (OBS) Studio
> 
> Во время записи видео, оружия в игре отображаются нормально, но в записанном видео они чёрные

Запиши захватом экрана и проверь, и еще на нижний слой добавь изображение любое и проверь, может быть это прозрачность, а не чернота

**Comment by Vladislav4KZ** [comment]
> > Игра записываться через Open Broadcaster Software (OBS) Studio
> > 
> > Во время записи видео, оружия в игре отображаются нормально, но в записанном видео они чёрные
> 
> Запиши захватом экрана и проверь, и еще на нижний слой добавь изображение любое и проверь, может быть это прозрачность, а не чернота

Записал игру через Захват экрана, и оружия отображаются нормально
