### ISSUE TITLE
[MOD: Opposing Force] Двойная анимация взмаха ножа и гаечного ключа

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#621]
У монтировки анимация нормальная, а у ножа двойная, в opposing force на ксаше запущенном на винде

**Comment by Vladislav4KZ** [comment]
А анимация удара у ножа нормальная, воспроизводится только один раз за нажатие

**Comment by Vladislav4KZ** [comment]
Та же самая проблема и у гаечного ключа

**Comment by Vladislav4KZ** [comment]
Такие анимации проявляются как с такими кварами cl_lw 1 cl_nopred 0
так и с cl_lw 0 cl_nopred 1

**Comment by nekonomicon** [comment]
Тут все по аналогии с этой проблемой:
https://github.com/FWGS/xash3d-fwgs/issues/600

Потому что клиентский код у оружия ближнего боя почти один и тот же.

**Comment by Vladislav4KZ** [comment]
> Тут все по аналогии с этой проблемой:
> https://github.com/FWGS/xash3d-fwgs/issues/600
> 
> Потому что клиентский код у оружия ближнего боя почти один и тот же.

Значит эту issue можно закрывать?

**Comment by Vladislav4KZ** [comment]
Ладно, закрываю. Я так и подумал что оно похоже на то о чём я репортил ранее, но тут анимация у монтировки нормальная а у остальных рукопашных оружий двойная

**Comment by nekonomicon** [comment]
> анимация у монтировки нормальная а у остальных рукопашных оружий двойная

Могли исправить, либо там код монтировки исключительно серверный.
А вообще в опфоре был квар для переключения клиентских и серверных пушек, может и в этом дело.

**Comment by nekonomicon** [comment]
> Значит эту issue можно закрывать?

Лучше пусть висит, будем знать, что проверять наверняка.

**Comment by a1batross** [comment]
Выяснил возможную причину -- событие взмаха приходит дважды, сначала от предиктинга, а потом почему-то от сервера.

Вроде флаг FEV_NOTHOST должен стоять и должна срабатывать проверка на включенный предиктинг у клиента на сервере. И она даже срабатывает.

Но видимо есть ещё какое-то место, где либо отсутствует nothost, либо не работает проверка.

**Comment by nekonomicon** [comment]
Да все вытекает из этого:
https://github.com/FWGS/hlsdk-portable/commit/33ba064b88d9b0e818009049aef13f53bd16ae20

2 анимации на клиенте + спамит серверка.

**Comment by a1batross** [comment]
Нет, на клиенте две анимации приходят в один кадр, и ничего плохого от
этого не происходит.

Тут именно не должно быть события с сервера

ср, 22 мая 2024 г., 06:51 Andrey Akhmichin ***@***.***>:

**Comment by SNMetamorph** [comment]
А это случайно не имеет отношения к данной ишью?

https://github.com/ValveSoftware/halflife/issues/1621

**Comment by a1batross** [comment]
Попытался исправить через https://github.com/FWGS/xash3d-fwgs/commit/51945f002b8ad272e60149666fbbe1b22c37cba3. Возможно и #600 тоже, попрошу @Vladislav4KZ по возможности проверить.

Причину описал в комментариях к коду.

Но всё-таки, это костыль. Возможно и нам стоило бы не сбрасывать `sv.current_client`, но это такая глобалка, изменение поведения которой чтобы сымулировать внутренний баг голдсорса, может развалить по пути весь сервер.

Кстати, судя по CCrowbar::SwingAgain из HLSDK, возможно действительно подразумевалось проигрывать анимацию дважды, но почему-то теперь это считается за баг. :)

**Comment by Vladislav4KZ** [comment]
Перепроверил анимации в Opposing Force.

У ножа и у трубного ключа двойная анимация взмаха исправлена, но при этом у трубного ключа остался двойной звук взмаха.

**Comment by a1batross** [comment]
@Vladislav4KZ в GoldSrc тоже двойной звук взмаха у газового ключа

**Comment by Vladislav4KZ** [comment]
> в GoldSrc тоже двойной звук взмаха у газового ключа

Точно, это я со Sven Coop перепутал, там нет двойного звука.
