### ISSUE TITLE
[MOD: Go-Mod] Краш при входе в меню Customize

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#623]
```
Sys_Crash: address 6DFE2C33, code C0000005
 0 6DFE2C33 GetExtAPI (menu.dll)
 1 6E00790F GetExtAPI (menu.dll)
 2 1001A73C vgui::Panel::internalMouseReleased (vgui.dll)
```

**Comment by Vladislav4KZ** [comment]
Сейчас мод крашится без окна с ошибкой, в логе написано это
```
Sys_Crash: address 00000000, code C0000005
 0 00000000(???)
 1 71BCCF65 CMenuItemsHolder::AddItem (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\controls\ItemsHolder.cpp:519:0) (menu.dll)
 2 71BF8AD6 CMenuPlayerSetup::_Init (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\menus\PlayerSetup.cpp:482:0) (menu.dll)
 3 71BCDC32 CMenuItemsHolder::Init (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\controls\ItemsHolder.cpp:275:0) (menu.dll)
 4 71BCC694 CMenuFramework::Init (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\controls\Framework.cpp:90:0) (menu.dll)
 5 71BC7769 CMenuBaseWindow::Show (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\controls\BaseWindow.cpp:34:0) (menu.dll)
 6 71BCCAF4 CMenuFramework::Show (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\controls\Framework.cpp:43:0) (menu.dll)
 7 71BF79FB UI_PlayerSetup_Menu (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\menus\PlayerSetup.cpp:490:27) (menu.dll)
 8 71BBC414 CEventCallback::operator() (D:\a\xash3d-fwgs\xash3d-fwgs\mainui\EventSystem.cpp:65:8) (menu.dll)
 9 71BC705F CMenuBaseItem::_Event(menu.dll)
 10 71BD11(menu.dl((xaHost_WriteGLConfig()
```
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/9095259/engine.log)

**Comment by a1batross** [comment]
Больше похоже на проблему с тем что модель игрока рисуется. На некоторых
модах оно и правда может вызвать краш.

вт, 12 июл. 2022 г., 19:55 Владислав Сухов ***@***.***>:

**Comment by Ian502** [comment]
I am having a similar crash while opening customize on half-life and other mods!
![imagen](https://github.com/FWGS/xash3d-fwgs/assets/11865784/6d82b228-7eec-46e7-bbf5-925558f7a734)
tried running different versions of Xash, even old engine, I can't find which config file or whatever does this.

**Comment by Vladislav4KZ** [comment]
Не воспроизводится на последней сборке движка.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master

**Comment by Vladislav4KZ** [comment]
Проверял на всех моделях как с 3D превью, так и без него.

Где нет картинки, пишется "No preview".
Но движок уже не крашится.

**Comment by a1batross** [comment]
Да, я дня три назад наконец-то исправил кучу говнокода в меню. Возможно что-то из этого повлияло.

Намеренно я не фиксил.

**Comment by Ian502** [comment]
Still crashes for me on latest continuous build [[647261F](https://github.com/FWGS/xash3d-fwgs/commit/64726f13e185145072b4feaff8e1d93bfe850825)] on regular HL when entering the Customize menu, even on other mods. Like Sven Coop 2.0f, DMC, and my own mod Mortal Kombat.
![imagen](https://github.com/user-attachments/assets/51776a39-e364-45c1-a0c0-5dd74f5d2888)
![imagen](https://github.com/user-attachments/assets/bd9157fc-522f-43ac-bbaf-c1c1cdd0bd21)

**Comment by Vladislav4KZ** [comment]
@Ian502 Do you have any custom player models installed? If so, can you post the link to models here?

**Comment by Vladislav4KZ** [comment]
> Still crashes for me on latest continuous build [[647261F](https://github.com/FWGS/xash3d-fwgs/commit/64726f13e185145072b4feaff8e1d93bfe850825)] on regular HL when entering the Customize menu, even on other mods. Like Sven Coop 2.0f, DMC, and my own mod Mortal Kombat.

I don't have this issue even in the Mortal Kombat mod.
