### ISSUE TITLE
[MOD: Snow War] На VBO рендере меняются текстуры при ходьбе

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#624]
https://youtu.be/TR6pxKcQoBg

**Comment by Vladislav4KZ** [comment]
Есть похожий баг и в Go-Mod только там меняются текстуры некоторых декалей, в основном вместо крови -  текстуры стен, без vbo тоже самое

**Comment by a1batross** [comment]
Баг ещё воспроизводится? Возможно переход на GenTextures должен был его пофиксить.

**Comment by Vladislav4KZ** [comment]
> Баг ещё воспроизводится? Возможно переход на GenTextures должен был его пофиксить.

gl_vbo же read-only квар. В Snow War проблема с подменой текстур воспроизводилась только с VBO.

А вот насчёт Go-Mod:
Проверил вчера на последней (на тот момент) сборке движка, декали отображались нормально. Кровь была кровью, а не текстурой стены.

**Comment by a1batross** [comment]
Should be fine with vbo-fix merge. Reopen if it's still broken.

**Comment by Vladislav4KZ** [comment]
> Should be fine with vbo-fix merge.

Подтверждаю, перепроверил на последнем билде движка с gl_vbo 1. Баг больше не воспроизводится ни на одной из карт.
