### ISSUE TITLE
Devices equipped with Qualcomm snapdragon processors are not very stable

### ISSUE THREAD

**Issue by magisk666** [FWGS/xash3d-fwgs#631]
Using Qualcomm snapdragon processor to play xash3d on mobile phones is easy to crash

**Comment by AruMoon** [comment]
More details, please.
I'm using snapdragon and everything is ok

**Comment by magisk666** [comment]
> 请提供更多详细信息。 我正在使用金鱼草，一切正常

xash3d Android The support for Qualcomm snapdragon GPU is not very good

**Comment by a1batross** [comment]
Add more details please.

I run xash3d-fwgs on Adreno and haven't found any problems.

**Comment by mittorn** [comment]
Some adreno drivers may crash, but we do not have affected devices. In some cases updating adreno libraries on device should help, but only when it's possible
