### ISSUE TITLE
I hope to develop a xashds compatible with Android 7-11

### ISSUE THREAD

**Issue by magisk666** [FWGS/xash3d-fwgs#632]
1.31已经不兼容Android8.0

**Comment by a1batross** [comment]
What? Can you explain?

**Comment by magisk666** [comment]
> 什么？你可以解释吗？

When will the Android version of xashds be updated

**Comment by nekonomicon** [comment]
@magisk666 It was linux version of xashds launched under emulator.
Anyway It's wrong repository for such issue and "xashds launcher" not supported anymore.
And you can compile and run native xashds version for android via termux.

**Comment by AruMoon** [comment]
or you can get compiled binary and sdk here https://link.us1.storjshare.io/s/jwke7fquzymqjyjnq6cb33piuirq/xash/

**Comment by AruMoon** [comment]
> or you can get compiled binary and sdk here https://link.us1.storjshare.io/s/jwke7fquzymqjyjnq6cb33piuirq/xash/

My mistake, it's old version
