### ISSUE TITLE
Crash on playdemo or timedemo demo0000.dem (64bit only)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#634]
[demo0000.zip](https://github.com/FWGS/xash3d-fwgs/files/7310394/demo0000.zip) в valve
Запускаем демку: `playdemo demo0000`
Получаем `Mem_Alloc: out of memory (alloc at \engine\client\cl_demo.c:956)`

Нет ошибки в 32битной сборке.

**Comment by Vladislav4KZ** [comment]
На 64-битной версии для Android нет краша с этой демкой

**Comment by 0x4E69676874466F78** [comment]
@Vladislav4KZ 
> На 64-битной версии для Android нет краша с этой демкой

Тестирую на винде.

**Comment by 0x4E69676874466F78** [comment]
Бамп. Баг так и не починили?

**Comment by 0x4E69676874466F78** [comment]
Новая демка [minidemo.zip](https://github.com/FWGS/xash3d-fwgs/files/9122461/minidemo.zip)
На 64бит, если поправить аллокатор то ошибка Demo message length < 0
На 32бит всё играет ок.

**Comment by 0x4E69676874466F78** [comment]
@zgdump спасибо!
