### ISSUE TITLE
[Android] Чёрный экран во время смены уровня в одиночной игре

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#641]
![Screenshot_20211014-115413.png](https://user-images.githubusercontent.com/22411953/137259893-7b2f90b9-5ec5-4fef-a9ca-dd5b3d2ccac0.png)

**Comment by Vladislav4KZ** [comment]
Такой баг я обнаружил на Meizu C9 Pro
CPU: Spreadtrum SC9832E
GPU: Mali-T820
Android 8.1.0 Oreo

На устройстве Nokia 2.2 такого бага нет
Android 11 R
CPU: MediaTek Helio A22
GPU: PowerVR GE8320

**Comment by Vad1mCSO2** [comment]
Почему Mali видеокарта постоянно чистка рендера похоже как `gl_clear 1`

**Comment by mittorn** [comment]
Мы не указываем стратегию обновления экрана явно (на это в egl есть 
расширение), потому не перерисовываемый экран может выглядить как угодно 
(особенно на адрено, где тайлы меняются местами.

По  идее можно было бы отключить перерисовку экрана в синглплеере 
совсем, а для мультиплеера показывать прогрессбар полноэкранно. Тут 
вопрос - узнаем ли мы именно в том кадре, в котором началась загрузка 
карты про смену карты чтобы нарисовать и карту и надпись Loading?

Исправлять это "как есть", делая скриншот перед загрузкой будет 
неэффективно - чтение данных из gpu происходит медлннно и например на 
некоторых mali чтение пикселей может занять больше секунды.

Изменение стратегии обновление экрана же может сказаться на потреблении 
и fps, если заставить драйвер каждый раз сохранять старый кадр - он 
скорее всего будет копировать весь экран. Возможно, можно временно 
изменить стратегию SwapBuffers? Не уверен что потом можно будет 
корректно вернуть оригинальную, но с этим можно поэкспериментировать

Ещё возможно было бы эффективно последний кадр отрисовать в фреймбуффер, 
но как и в первом случае это потребует в уже в последнем кадре знать о 
предстоящей загрузке.

**Comment by Vladislav4KZ** [comment]
Этот баг может быть исправлен после этого коммита: https://github.com/FWGS/xash3d-fwgs/commit/0da7ffe45f146670612af066386161b0e77f5973

У меня уже нет устройства с видеоускорителем от Mali, поэтому перепроверить не смогу.

**Comment by a1batross** [comment]
Now fixed completely with 56ba2325
