### ISSUE TITLE
[PC] Возможно ли хоть как то запустить Counter-Strike?

### ISSUE THREAD

**Issue by TheBACKTRACK** [FWGS/xash3d-fwgs#647]
Окно с Half-Life просто закрывается при попытке выбрать Counter-Strike
У меня действительно оригинальная версия Counter-Strike из Steam
Возможно ли хоть где нибудь кроме андроида запустить контру?
Когда я пишу xash3d.exe -game cstrike окно не открывается

**Comment by nekonomicon** [comment]
CS 1.6 требует поддержки vgui2, который ксаш не поддерживает. В этом плане есть наработки от японца:
https://github.com/kungfulon/xash3d-fwgs

CS 1.5 имеет зашифрованный клиент, поэтому не работает тоже.
Более старые версии CS могут в той или иной степени работать.

**Comment by TheBACKTRACK** [comment]
> 
> 
> CS 1.6 требует поддержки vgui2, который ксаш не поддерживает. В этом плане есть наработки от японца: https://github.com/kungfulon/xash3d-fwgs
> 
> CS 1.5 имеет зашифрованный клиент, поэтому не работает тоже. Более старые версии CS могут в той или иной степени работать.

Очень крутые наработки у того чела что аж движок не хочет запускаться ваще класс

**Comment by TheBACKTRACK** [comment]
> 1.3 запускай или 1.5 расшифрованную, 1.6 оригинальная не будет работать нормально

1.3 у меня отказалась нормально работать значит вариант остался только один

**Comment by mittorn** [comment]
Так я имею в виду использовать 1.3 целиком, а не с сервером от 1.6
А если ты с ПК будешь ломиться на мобильные сервера (а кс у нас оффициально только для мобилок) - готовься недовольство от игроков словить и сломанные конфиги как подарочек от админов серверов.
Так уж исторически сложилось что cs16client только на мобилках и мышевозных серверов нет, а если будет то это очень сложно в поддержке будет

**Comment by TheBACKTRACK** [comment]
> Так я имею в виду использовать 1.3 целиком, а не с сервером от 1.6 А если ты с ПК будешь ломиться на мобильные сервера (а кс у нас оффициально только для мобилок) - готовься недовольство от игроков словить и сломанные конфиги как подарочек от админов серверов. Так уж исторически сложилось что cs16client только на мобилках и мышевозных серверов нет, а если будет то это очень сложно в поддержке будет

Так я и использовал 1.3 полностью, я же сказал что нельзя выбрать команду там

**Comment by mittorn** [comment]
Тогда странно. Но попробуй vgui меню отключить
```
setinfo "_vgui_menus" "0"
setu "_vgui_menus" "0"
```
mp.dll точно не от 1.6?

**Comment by mittorn** [comment]
Ну и классическое jointeam N, joinclass N в консоли конечно же

**Comment by sidreshot** [comment]
> > Тогда странно. Но попробуй vgui меню отключить
> > ```
> > setinfo "_vgui_menus" "0"
> > setu "_vgui_menus" "0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mp.dll точно не от 1.6?
> 
> Меню VGUI отключил, команда не выбирается

У меня в чистой CS1.5 все выбирается и работает. 
Только баг с отображением оружия единственная проблема - https://github.com/FWGS/xash3d-fwgs/issues/722
