### ISSUE TITLE
[Android] [MOD: Team Fortress Classic] Белые спрайты огня и взрыва

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#648]
Происходит на обеих рендерах, GLES1 и GLES2
Без VBO и с VBO

В определённых местах спрайт от взрыва ракеты РПГ становится белым
![Screenshot_20211019-101002.png](https://user-images.githubusercontent.com/22411953/137842936-12d65c86-3044-4b5e-a90b-1f858863b791.png)

**Comment by a1batross** [comment]
nanogl bug?

**Comment by a1batross** [comment]
Like in https://github.com/FWGS/xash3d-fwgs/issues/452?

**Comment by Vladislav4KZ** [comment]
> nanogl bug?

@a1batross Я в первой же строчке написал:
> Происходит на обеих рендерах, GLES1 и GLES2
> Без VBO и с VBO

**Comment by Vladislav4KZ** [comment]
И кстати этот багрепорт был создан когда у меня был Meizu C9 Pro.

На Samsung Galaxy A52 пока не проверял.

**Comment by Vladislav4KZ** [comment]
Сегодня проверил, ни на GLES1 (NanoGL), ни на GLES2 (gl-wes-v2) баг не воспроизвёлся.
