### ISSUE TITLE
[MOD: Half-Rats: Parasomnia] Индикатор здоровья сдвигается вправо при включенном фонаре

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#655]
https://www.youtube.com/watch?v=xSEXa19WEaw
https://www.youtube.com/watch?v=a0zZSIFdnY4

**Comment by a1batross** [comment]
Смешной баг, но хочется от него плакать.

Заметка для себя:

Вот здесь ребята получают клиентский индекс спрайта по имени
https://github.com/HeathGames/half_rats_parasomnia_src/blob/279928b9da8231ee47fe46d7f7238f4eb40f0acd/cl_dll/flashlight.cpp#L71

Двумя строчками ниже они получают индекс движковый по индексу клиентскому

Здесь они ошибочно передают движковый индекс в метод CHud, который ищет по индексам клиентским.
https://github.com/HeathGames/half_rats_parasomnia_src/blob/279928b9da8231ee47fe46d7f7238f4eb40f0acd/cl_dll/flashlight.cpp#L149

Вывод:
Индекс клиентский и индекс движковый в Ксаше не совпадают. Им скорее всего просто повезло, что в голдсорсе это работает как нужно.

**Comment by a1batross** [comment]
Fixed in 6e031b5
