### ISSUE TITLE
Slow loading on Android 11

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#657]
Just noticed that. Seems very odd and unusual.

**Comment by QUAKEULUS** [comment]
did you repackage everything into pak0.pak pak1.pak files?

**Comment by QUAKEULUS** [comment]
> @QUAKEULUS New engine supports zip format. So @Velaron just packed files to pk3.

How is it supported? does entire valve folder need to be valve.zip? or are individual folders supported like valve/maps.zip?

or is it like before, anything in /valve/* as /valve/pak0.zip

thanks
