### ISSUE TITLE
Crosshair disappears in snap range when autoaim is enabled

### ISSUE THREAD

**Issue by coppermine733** [FWGS/xash3d-fwgs#664]
When autoaim is enabled, if the crosshair is in autoaim range for a target, it will disappear until it is close enough to the target or back out of range enough to stop the snap behavior. It is consistent behavior and happens often enough that it is easily reproducible. A good place to see this is by aiming at the rat on the floor in the targeting range of the hazard course. If you disable autoaim the problem does go away, but so does the autoaim function and the red crosshair when targeting enemies. I've tested this with both the 0.20 build and the rolling release on Windows 7 and 10 64-bit. I also thought maybe it was an asset issue so I've tried with both 1.1.1.0 data and current steam data but it made no difference. This feature does work correctly in the standard Xash3D 4344/0.99.
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/7446864/engine.log)

**Comment by Vladislav4KZ** [comment]
This has already been said in Russian https://github.com/FWGS/xash3d-fwgs/issues/575

**Comment by a1batross** [comment]
Fixed.
