### ISSUE TITLE
The half life display is abnormal on raspberry pi os

### ISSUE THREAD

**Issue by PTALTS-LK** [FWGS/xash3d-fwgs#669]
Start xash when libref_gles2.so is available:
[engine-p1.log](https://github.com/FWGS/xash3d-fwgs/files/7490259/engine-p1.log)
![p1](https://user-images.githubusercontent.com/62936489/140606668-e0be9788-69d6-4563-9ce7-6141312c9f60.png)
Start xash without libref_gles2.so
[engine-p2.log](https://github.com/FWGS/xash3d-fwgs/files/7490260/engine-p2.log)
![p2](https://user-images.githubusercontent.com/62936489/140606697-37f4fdb2-4f9c-4962-a7fb-6415c5259a87.png)

cpu:armv6hf
os:raspberry pi os(armhf)

**Comment by CPXMC** [comment]
Fake KMS GL Driver is enabled

**Comment by a1batross** [comment]
Try other renderers. Currently all of them except GL have breaking issues. :(

**Comment by CPXMC** [comment]
> Try other renderers. Currently all of them except GL have breaking issues. :(

ooooooops

**Comment by a1batross** [comment]
ref_gles2 is deprecated now.

Users better switch to ref_gles3compat or ref_gl4es.
