### ISSUE TITLE
Is Xash3D compatible with microphone?

### ISSUE THREAD

**Issue by CristobalManga** [FWGS/xash3d-fwgs#672]
My brother lives in another country, and thanks to this XASH3D application, we were able to play together.
And since I haven't heard him for years, I wanted to talk to him through the microphone in the game, but it doesn't seem to work.
And I wanted to know if it is not compatible or is it some problem of mine.
Thank you...

**Comment by AruMoon** [comment]
Voice chat is WIP

**Comment by CristobalManga** [comment]
> Voice chat is WIP

Sorry, I didn't understand, what does WIP mean?

**Comment by AruMoon** [comment]
> > Voice chat is WIP
> 
> Sorry, I didn't understand, what does WIP mean?

Work In Progress
