### ISSUE TITLE
Перестают работать сенсорные кнопки, после выхода из игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#673]
Сбрасываю настройки тача, кнопки работают. Выхожу из игры и захожу снова кнопки перестают работать.

В меню тач кнопок видно что у всех кнопок пропали команды, а при открытии тач конфига в текстовом редакторе, вместо команд отображаются кракозябры
![Screenshot_20211114-223426.png](https://user-images.githubusercontent.com/22411953/141690021-22c26760-9fbf-41c5-9462-773ea53732cd.png)

**Comment by Vladislav4KZ** [comment]
Наверно баг появился из-за этого коммита https://github.com/FWGS/xash3d-fwgs/commit/39893609fd5d709a2a6a577182d59134b95e8700 так как раньше такой проблемы не было

**Comment by a1batross** [comment]
Верно. Я забыл вызвать EscapeCommand. :)
