### ISSUE TITLE
[MOD: Half-Life Decay] Не работает смена уровня

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#675]
dy_accident1 -> dy_accident2

На GoldSource на карте dy_accident1 после чёрного экрана меняется карта, а на Xash3D чёрный экран исчезает, а карта так и не меняется

**Comment by Vladislav4KZ** [comment]
Что странно, смена карты dy_accident2 -> dy_hazard сработала

**Comment by a1batross** [comment]
Исправлено в c896425ad972eaeda73a7aceb821adc7f9614a92
