### ISSUE TITLE
На последнем билде ксаша кикает с серверов с античитами

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#680]
Например [MoD]DeathMatch и hype hldm

**Comment by AruMoon** [comment]
Это к движку не относится

**Comment by mittorn** [comment]
ну так свяжись с админами. Это совершенно нормально т.к они детектят фильтрацию команд

**Comment by Vladislav4KZ** [comment]
> ну так свяжись с админами. Это совершенно нормально т.к они детектят фильтрацию команд

С админами я уже связался, решил написать чтобы узнать на чьей стороне причина отсоединения от серверов

**Comment by mittorn** [comment]
впрочем если окажется что фильтрация слишком агрессивная, можно будет переоткрыть снова
