### ISSUE TITLE
Please increase MAX_TEXTURES

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#684]
From 4096 to at least 8192. Nothing should break from this as far as I know and increased limit could provide more benefits.

**Comment by a1batross** [comment]
Yes, it's only defined by renderer, nothing will break by increasing the value.

Xash may consume more memory but that's not a problem.

**Comment by a1batross** [comment]
Fixed in ecddae8

**Comment by mittorn** [comment]
Check references before doing that. for fixed-size arrays this is not very good idea

**Comment by mittorn** [comment]
what about dynamic limit in gameinfo.txt? Once someone need 8k, next time 16k may be needed

**Comment by a1batross** [comment]
@mittorn then post a different issue about implementing `max_textures` in gameinfo.txt.
