### ISSUE TITLE
Android: Bugs from new Xash3D FWGS engine

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#69]
1. The "disconnect" button works as a restart.
2. Water bug on both gles renderers like there
![Screenshot_20191016-173147](https://user-images.githubusercontent.com/22411953/66926027-21b36b80-f04f-11e9-9a60-8289297ab09b.jpg)
3. Black screen after minimizing engine
4. Black bars instead of text in the console when playing hazard course (64bit version only)
![Screenshot_20191020-121028](https://user-images.githubusercontent.com/22411953/67155498-b9a4a400-f332-11e9-933a-cdc72f030a3f.jpg)

**Comment by mittorn** [comment]
4 - this is in every version after restarting map
