### ISSUE TITLE
[Android] Не запускается движок, закрывается без ошибки

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#692]
Предыдущие версии тестового движка запускались, теперь на последних билдах при запуске выкидывает на главный экран андроида

**Comment by Vladislav4KZ** [comment]
Посмотрел логи в logcat, ругается на отсутствие libxash.so. Посмотрел в скачанный apk файл, его там действительно нет

Использую 64бит версию движка

**Comment by Vladislav4KZ** [comment]
Из собранных библиотек есть только libclient.so и libserver.so, библиотеки рендеров и движка отсутствуют

**Comment by hypeq** [comment]
автобилд, bruh

**Comment by a1batross** [comment]
Fixed in 23e2f4d0
