### ISSUE TITLE
[Xash] Mod:Counter Strike | My server disappears from the master server list

### ISSUE THREAD

**Issue by Insans12** [FWGS/xash3d-fwgs#693]
My xash cs 1.6 server not showing up in the master server list, before it appeared normally, ports are open, and public is set to "1".
Sometimes I open three servers together, with their respective ports open and rarely all three appear together, now only one appears once in a while.
The server runs on Windows and uses Xash FWGS 0.19.2, metamod modified for xash and amxmodx 1.8.2

**Comment by hypeq** [comment]
0.19.2 fwgs build blocked from master server list

**Comment by a1batross** [comment]
What's your server IP address?

**Comment by Insans12** [comment]
The current ip is 181.94.81.229, the ip is dynamic, once I have already changed the ip to test if it was solved but it did not work.

**Comment by a1batross** [comment]
Your server is probably under NAT. I'm seeing that master server gets correct reply from you and added to server list.
