### ISSUE TITLE
Broken gamma settings and wrong default gamma

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#694]
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/client/vid_common.c#L182
При том что тут как и надо 2.2 https://github.com/FWGS/xash3d-fwgs/blob/master/common/xash3d_types.h#L47
Ошибке подвержен и goldsrc. Стоит гамма с древних времён ЭЛТ-моников, когда как давно уже у всех ЖК.

Статьи по теме:
https://prateekvjoshi.com/2014/05/24/what-is-gamma-correction/
https://docs.cryengine.com/plugins/viewsource/viewpagesrc.action?pageId=1605651
https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

> CRT Monitors: The interesting thing to note is that the native gamma of a CRT is 2.5. This is almost the inverse of our eyes! So technically, values from a gamma-encoded image file could be sent straight to the screen and they would automatically be corrected. The CRT monitors will almost nullify them by default. However, a small gamma correction of 1.1 needs to be applied to achieve an overall display gamma of 2.2. This is usually already set by the manufacturer’s default settings, but can also be set during monitor calibration.

Кроме этого я ещё заметил что работа с гаммой/цветами при одинаковой их `gamma 2.5` (при `brightness 1`) отличается. Это не говоря о разной обработки хромированных поверхностей и спрайтов (заведу отдельные задачи).
![изображение](https://user-images.githubusercontent.com/4449851/144851338-dd54ae48-f3ed-4652-9fdc-9df0e797f684.png)
![изображение](https://user-images.githubusercontent.com/4449851/144851392-0e04d29a-b4d2-4f4b-bda5-db16e4487f2e.png)

**Comment by mittorn** [comment]
У ДМ же ЭЛТ монитор, так что логично. Я тоже полгода назад с ЭЛТ сидел, там нормально с такой

**Comment by a1batross** [comment]
Это кстати не обязательно баг.

В голдсорсе тоже по дефолту 2.5.

**Comment by a1batross** [comment]
Сорян, не прочитал полностью.

Да, интересно получается. С одной стороны, цветопередача "тех" мониторов была другой и текстуры создавались под "них". С другой стороны, эти времена уже прошли и как хотя бы HL1 должна выглядеть неизвестно. Я с дефолтными значениями нахожу её больно светло-мыльной, в старом движке что интересно было иначе.

Какая коррекция тут конкретно нужна

**Comment by SNMetamorph** [comment]
Я еще сейчас делаю одну штуку, связанную со всем этим, позже открою PR

**Comment by 0x4E69676874466F78** [comment]
@a1batross пузачей у меня уже не осталось.
В простом варианте просто добиться чтобы градиент на текстуре был равномерный, как показано здесь: 
![изображение](https://prateekvjoshi.files.wordpress.com/2014/05/3-encoding.png)
Если он при 2.2 на ЖК неравномерный значит гамма в игре сломана.
Но тут есть подвох, оригинальная халфа могла быть в теории со сломанной гаммой, однако это был эталонный опыт игры. Если она сломана надо думать, я бы завёл отдельный квар имитации оригинальной гаммы на 2.2 гамме.
Для проверки как должна быть выглядеть оригинальная халфа на ЭЛТ как вариант можно взять старую WON-версию оригинала, далее дождаться как [тут в magpie](https://github.com/Blinue/Magpie/projects/1#card-73887871) запилят CRT-шейдер (ранее попросил для старых игр, а то больно на них смотреть даже через хороший ЖК), хороший CRT-шейдер умеет имитировать и гамму CRT, можно посмотреть как халфа примерно должна выглядеть, правильно ли у неё градиент отображается. Возможно перенесу META CRT как вроде самый физически корректный, если существующие не устроят.
В самой игре вроде была настройка гаммы с квадратиками (то что сейчас видно в mainui в сломаном виде потому что картинка масштабируется что неправильно и даже на 640х480 не пиксель в пиксель), запущу на родном на тот момент разрешении и проверю что квадратики выглядят как надо (сливаются). 
Ну и и сравнить на тестом градиенте в игре, заодно проверить правильная ли гамма у освещения. 
Ксаш тоже на этом фильтре погонять и попробовать добиться того же вида, отнормировать потом в 2.2 чтобы без фильтра так же всё выглядело.

**Comment by mittorn** [comment]
в хл1 гамма текстур в принципе неправильная. Как самих текстур, так и изображения на выходе. Это же просто Karen Laur едила и собирала фотки в естественном освещении. Потом патчили light.exe пытаясь добиться приемлемого эффекта на глаз. Ещё были эксперименты с овербрайтом. Никто не задумывался над этим вопросом на математическом уровне по сравнению, например, со звуком.
Так что если хочешь получить корректную гамму - надо будет смотреть весь путь света - сами текстуры (тут понять вообще что использовать - linear, gamma или вообще srgb, srgb тоже != gamma 2.2, хоть и близко), применение цвета к текстуре (прямое домножение, овербрайт), применение лайтмапы и, если у тебя в моде есть - диффуза и спекуляра.  В сорсе с этим всем запутались и понаписали такой лапши, в которой никто не может теперь разобраться нормально

**Comment by mittorn** [comment]
Надо ещё придумать что делать с текстурными флагами. 32 бита там явно не хватает. Логично иметь флаги на то что текстура должна быть линейной/gamma/srgb (как вообще это переключать?) и если она должна быть рендертаргетом - это задаёт ограничения на форматы
Может вообще повыкидывать старые флаги? там есть какие-то зарезервированные

**Comment by SNMetamorph** [comment]
> Надо ещё придумать что делать с текстурными флагами. 32 бита там явно не хватает. Логично иметь флаги на то что текстура должна быть линейной/gamma/srgb (как вообще это переключать?) и если она должна быть рендертаргетом - это задаёт ограничения на форматы Может вообще повыкидывать старые флаги? там есть какие-то зарезервированные
Нужно наверно какую-то систему поверх всего этого сделать. Пара функций Get/SetTexturesFlags или типо того. Ну и enum под флажки, только сделать это просто числами, а не битовыми флагами, ибо даже 64 не факт что хватит.

**Comment by mittorn** [comment]
64 то хватит, но если просто взять 64 то наверняка что-то сломается. Я честно говоря не знаю как это решить ничего не сломав

**Comment by SNMetamorph** [comment]
То есть это получится новая система флагов поверх старой. И при инициализации нужно просто на основе старых флагов выставлять новые, всё то что юзает старые битовые флаги, так и останется работать, все чему нужны свежие фичи, будет юзать новую систему с enum. Не знаю, как понятней описать.

**Comment by 0x4E69676874466F78** [comment]
В WON халфе гамма настраивается в настройках более корректно чем у ксаша, при условии что она запускается с ключом `-window` тогда никакого масштабирования на весь экран не происходит, а само меню в 640x480 вне зависимости от выбранного видеорежима, поэтому картинка выглядит как надо пиксель в пиксель. Гамма двигается по делению `0.1`.
Квадратики надо рассматривать отдалившись от монитора на некоторое расстояние пока они не станут сливаться с внутренней частью.
`gamma 1.8` 
![изображение](https://user-images.githubusercontent.com/4449851/146931084-337083cd-4839-4439-aa42-2b4f1264748e.png)
`gamma 2.0` 
![изображение](https://user-images.githubusercontent.com/4449851/146930297-7975d68f-bd2e-4077-9079-e88f7a37c9ae.png)
`gamma 2.2` 
![изображение](https://user-images.githubusercontent.com/4449851/146930443-f6459a61-b156-4ba7-94bd-037a6867b85d.png)
`gamma 2.5` 
![изображение](https://user-images.githubusercontent.com/4449851/146932342-d7a2e55d-66e6-4b7b-b0f9-108f06eedb23.png)
`gamma 3.0` 
![изображение](https://user-images.githubusercontent.com/4449851/146931481-8562f555-d76f-4d36-ab83-fe1fd2e73bf6.png)

В моём случае гамма лучше всего `2.0`.

В ксаше к сожалению всё гораздо хуже. При `brighthess 0` (по умолчанию) и `gamma 1.8` такое:
![изображение](https://user-images.githubusercontent.com/4449851/146933196-14e5195c-ba08-4953-bfd0-c75ba2ef2b27.png)
И квадратики всё равно не сливаются, а градиент по сравнению с HL WON не такой.
При гамме или яркости выше они ещё больше контрастируют.

**Comment by 0x4E69676874466F78** [comment]
Я сравнил меню:
![bad xash3d menu](https://user-images.githubusercontent.com/4449851/146934176-0fe44f00-05db-44c5-bd66-c5c3dfded53c.png)
Как раньше и писал, на ксаше картинка растянута, это квадратикам мешает, для гаммы тестовое изображение должно быть пиксель в пиксель.
Градиент всё равно не такой же (при `gamma 1.8`), однако в ксаше он более равномерный.
![изображение](https://user-images.githubusercontent.com/4449851/146935549-e7fee657-ba95-463e-80d2-37016dc1e5e7.png)


В халфе won кстати по умолчанию `brightness 1`, но это в config.cfg, если оттуда убрать то будет `0.0` отдаваться самим движком. В халфе оно называется Glare reduction.

Попробовал сделать его тоже в 0. Вот что при `gamma 1.8`, всё равно квадратики выглядят корректнее.
![изображение](https://user-images.githubusercontent.com/4449851/146936261-01506907-ba23-4888-a41e-257a097a2946.png)

Добавил градиент при таком режиме вниз.
![изображение](https://user-images.githubusercontent.com/4449851/146936641-2c06b3db-b131-453e-8ce6-08bd66580776.png)
Он (третий) стал более равномерным. Стало быть `brightness 1`, из config.cfg некорректный с точки зрения градиента, но возможно разработчики специально Glare reduction выкрутили, поищу оригинальный диск.

**Comment by 0x4E69676874466F78** [comment]
Забыл скинуть вариант с `2.2`. Вот выставил `brightness 0`, `gamma 1.8`:
![изображение](https://user-images.githubusercontent.com/4449851/146937669-1e301432-8ae3-4c71-94a0-3edcac9a8f81.png)
Без выкрученного Glare reduction, гамма 2.2 стала правильной!

**Comment by 0x4E69676874466F78** [comment]
Стимовский вариант халфы за канон не рассматриваем. Там сломана настройка гаммы, тыкаешь как дурак в ползунки без обратной связи и оно ещё даже не сразу применяет, а перезапускает игру! В консоли параметр gamma хоть и можно изменить фактически он не применяется. Явно на игру забили с художественной точки зрения.

**Comment by 0x4E69676874466F78** [comment]
Ещё в Half-Life Alpha Press Preview 0.52 в gaben.cfg `brightness 1`, а в config.cfg там вообще `brightness "1-jump"` 💩 
Нашёл у себя Half-Life 1.0 (build 738), эта та где ещё кнопка console сделано виндовой кнопкой, там конфиг отсутствует, и движок отдаёт `brightness 1`, `gamma 2.5`. Гамма при этом настраивается корректно и на 2.2 при `brightness 0` выглядит правильно.

Но я начинаю подозревать почему габен выкрутил brightness в 1.
![изображение](https://user-images.githubusercontent.com/4449851/146954573-7a9fea27-108a-4fa1-bcaa-84ad28eebc4b.png)

![изображение](https://user-images.githubusercontent.com/4449851/146954753-997edd5d-1782-4df2-b839-97cf4c83488a.png)

Возможно на ЭЛТ мониторах контраст на лайтмапах более заметен был.

**Comment by 0x4E69676874466F78** [comment]
Чтобы было пиксель в пиксель нужно задать такое:
```
testImage.SetRect( 390, 225, 466-1, 450-1); // 288, 280
```

![изображение](https://user-images.githubusercontent.com/4449851/147474202-12afc878-5269-426e-a71a-8788e521b224.png)

1.8 гамма похожа на 2.2 в оригинальной халфе, на глаз квадратики нормально слипаются, но если сравнить градиенты это не то же самое.
![изображение](https://user-images.githubusercontent.com/4449851/147474436-81a0357b-6e9e-477d-a2da-a2c83a457983.png)
2.2 гамма даёт совершенно другой вариант.
![изображение](https://user-images.githubusercontent.com/4449851/147474377-2c36cdb4-4608-4e6b-8059-614103444031.png)
Ксашевская 1.9 больше похожа на халфу 2.2:
![изображение](https://user-images.githubusercontent.com/4449851/147474770-4f98bc42-0c3a-431a-b6c4-b526346e94a7.png)

**Comment by a1batross** [comment]
Было исправлено в https://github.com/FWGS/xash3d-fwgs/pull/1563
