### ISSUE TITLE
Android APK crashes

### ISSUE THREAD

**Issue by androidnewbi** [FWGS/xash3d-fwgs#696]
Hi, the android APK crashes as soon as i select Path to game resources or try to launch game. I'm using 32 bit version. Thanks

**Comment by Vladislav4KZ** [comment]
Duplicate https://github.com/FWGS/xash3d-fwgs/issues/692

**Comment by hype-epta** [comment]
new 32 bit build crashing on launching

**Comment by hype-epta** [comment]
i also have this problem

**Comment by androidnewbi** [comment]
Yeh new build is still missing required files, I checked the APK, they r missing from Lib folder.
Not sure if i should close this issue as its a duplicate of #692?

**Comment by Gazername79** [comment]
Yep, i use 32 bit version then it's just keep crashes for no reason.

**Comment by a1batross** [comment]
Fixed in 23e2f4d0
