### ISSUE TITLE
How do I download build artifacts

### ISSUE THREAD

**Issue by DuendeInexistente** [FWGS/xash3d-fwgs#697]
![image](https://user-images.githubusercontent.com/20157727/145470538-e9623cdb-a665-4a2f-91f5-a512d81b4758.png)

The build actions pages have no download option anywhere (There's a 7z to a windows build in the ubuntu upload log but it 404s) and the continuous release page only lists android downloads.

**Comment by a1batross** [comment]
We don't use Actions artifacts yet and sometimes it doesn't work right for releases due to some kind of race condition I don't know.

**Comment by a1batross** [comment]
Fixed.
