### ISSUE TITLE
Creating mod shortcut gets cut off on small screen on Android

### ISSUE THREAD

**Issue by androidnewbi** [FWGS/xash3d-fwgs#698]
This has been a problem in the old versions too. When i try to create a mod shortcut it doesn't show the whole page and its not scrollable, would you make it scrollable? Thanks!

**Comment by a1batross** [comment]
Do we still wanna support this hack?

**Comment by androidnewbi** [comment]
Not sure what you mean, i was just reporting an issue with the android version that I'm not able to use the option within the app to create a mod shortcut due to it not working on smaller screens. What do you mean about me supporting this hack?

**Comment by Vladislav4KZ** [comment]
Not relevant in Velaron's Xash3D FWGS Launcher (shortcut creation is not implemented). Perhaps this feature will appear in the future. In last resort, if you want this feature to be returned, create a new issue.

The current topic of this issue has lost relevance anyway.
