### ISSUE TITLE
Неправильный рендер тумана у брашевых энтити под водой.

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#700]
Под водой туман у брашевых энтити рендерится с каким-то светло-молочным оттенком, от чего этот туман выделяется от тумана под водой.
OS: Xubuntu 21.10.
GPU: Intel HD Graphics 2000.
Версия Mesa: 21.2.2
Рендер: OpenGL.
![test](https://user-images.githubusercontent.com/96422615/146764773-91e9ba17-fe64-491d-81d4-d223691921c8.png)

**Comment by Vladislav4KZ** [comment]
Попробуй выключить VBO, я видел этот же баг на винде, должно помочь если я ничего не путаю.

Если что видеокарта: NVIDIA GeForce 9500 GT

**Comment by Vladislav4KZ** [comment]
Да, точно. Отключение VBO решает проблему, проверил на андроиде ещё

**Comment by Vladislav4KZ** [comment]
Я кстати уже писал про этот баг
https://github.com/FWGS/xash3d-fwgs/issues/605

**Comment by a1batross** [comment]
Should be fine with vbo-fix merge. Reopen if it's still broken.
