### ISSUE TITLE
Невозможно загрузить карту через команду map.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#703]
При этом пишет в в консоль эту ошибку:
```
Error: map c0a0 is invalid or not supported
```
Лечится предварительной загрузкой карты через "New game" или "Hazard course".
OS: Xubuntu 21.10

**Comment by Vladislav4KZ** [comment]
Вот что у меня написало при загрузке карты c1a0
```
Error: Mod_LoadPlanes: Lump size 38537 was not a multiple of 20 bytes
Mod_LoadWorld: 1 error(s), 0 warning(s)
Error: map c1a0 is invalid or not supported
```

**Comment by Vladislav4KZ** [comment]
Также заметил ещё что когда запущена одиночная игра, невозможно создать сервер, можно только подключиться к серверам. И только после подключения к серверу, можно создать собственный

**Comment by a1batross** [comment]
А у тебя там Blue Shift карт не намешано?

**Comment by Vladislav4KZ** [comment]
> А у тебя там Blue Shift карт не намешано? 

У меня точно нет

**Comment by Vladislav4KZ** [comment]
Хотя погоди, буквально недавно появился кооперативный сервер Blue Shift и оттуда скачалась карта. Оттуда попала карта из Blue Shift и из-за неё эти проблемы

**Comment by a1batross** [comment]
Может быть исправлено после 0963e05.
