### ISSUE TITLE
Не работают тач кнопки создаваемые coop сервером

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#705]
В старых билдах кнопка "COOP SERVER" работала, а сейчас нет. Да и ещё исчезает при нажатии. Консольная команда coopmenu тоже не работает. Пишет "Unknown command: coopmenu"

**Comment by Vladislav4KZ** [comment]
На старом движке это меню работает, поэтому проблема не в сервере

**Comment by mittorn** [comment]
Возможно, проблема из-за touch_show/touch_hide?
https://github.com/FWGS/xash3d-fwgs/blob/1bf08cc2c367b1c3524fc8d0a071eb1901eb27b7/engine/client/in_touch.c#L627
Сходу посмотрел, вроде должно быть всё правильно, если конечно где-то условие не перевёрнуто
Т.к старый движок не имеет нормального механизма доставки больших порций reliable данных, кнопки отсылаются порциями:
https://github.com/FWGS/hlsdk-xash3d/blob/gravgun/dlls/gravgunmod.cpp#L2799
Имеет ли смысл чинить это под новый когда там можно выслать менюху целиком  -не знаю. Такие моды серверные конечно спорные т.к используют возможности движка не предусмотренные оригинальной игрой.
Так же не будет работать меню в ggm т.к завязано на скриптинг. И тут вообще по логике надо делать эмуляцию с сервера, а не хранить состояние в кварах

**Comment by a1batross** [comment]
Скриптинг есть в новом движке.

**Comment by mittorn** [comment]
set тоже есть?

**Comment by Vladislav4KZ** [comment]
Не воспроизводится в последнем билде движка.

Команда ``set`` уже добавлена в новый движок.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3389
Платформа: android-arm64
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8
Ветка: master
