### ISSUE TITLE
В автоподстановке консоли `\` вместо `/`

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#708]
В ксаше:
![изображение](https://user-images.githubusercontent.com/4449851/146948669-eb117480-9e6d-4f26-bebd-dc8f54cafd95.png)
В халфе:
![изображение](https://user-images.githubusercontent.com/4449851/146949153-64b25edb-29a1-4047-ae16-184a66b3c917.png)

Обычно в чатах `/` начало команды.

**Comment by a1batross** [comment]
Is this really an issue?

**Comment by 0x4E69676874466F78** [comment]
@a1batross ну некрасиво и неправильно. Не предлагаю бежать сломя голову исправлять, просто имейте ввиду.

**Comment by a1batross** [comment]
Removed in 46fd27eb14cc3d0db6bc260515531f50348a40a0 and 295adcf22215d2c46e92ecf6fb5c16dc7834b565.

Reason is described in first commit. In short: there is no real use of backslashes in console anymore. It may make sense in chat, if we want to support that.
