### ISSUE TITLE
Сломались анимации передвижения у NPC на старых coop серверах.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#709]
После этого коммита:
https://github.com/FWGS/xash3d-fwgs/commit/a28d15e51913f7eb5e61b7191c9d1faebc3e7ce5
Сломались анимации передвижения у NPC на старых coop серверах, теперь NPC передвигаются с постоянным мерцанием, к тому-же анимация постоянно куда-то убегает вперёд самого NPC.
Предположительная причина: несовместимость старого протокола с новой, фикшенной дельтой.
https://user-images.githubusercontent.com/96422615/146973040-1340d6fb-f884-454b-a75b-985496d809e3.mp4

**Comment by a1batross** [comment]
Ну это неудивительно. Дельта один из основных механизмов кодирования. И она должна совпадать между клиентом и сервером.

**Comment by SNMetamorph** [comment]
А можно увидеть, как было до этого коммита?

**Comment by unnamed9** [comment]
@SNMetamorph К сожалению, проверить старые билды у меня нет возможности.

**Comment by SNMetamorph** [comment]
> @SNMetamorph К сожалению, проверить старые билды у меня нет возможности.

Я это всё к тому, что насколько я помню и на старых билдах этот баг был. Более того, он есть и на связке новый клиент+сервер, я подробности расписывал в https://github.com/FWGS/xash3d-fwgs/pull/517 и https://github.com/FWGS/xash3d-fwgs/issues/501

**Comment by unnamed9** [comment]
@SNMetamorph Постоянно убегающей вперёд анимации точно не было до того коммита, так что этот баг не связан с теми.

**Comment by SNMetamorph** [comment]
Вот кстати, это можно нормально подебажить через GoldSrc Monitor, только придется еще несколько полей добавить в вывод энтити репорта, в особенности нужно чекнуть что там лежит в cl_entity_t->latched и как эти данные меняются с течением времени.

**Comment by AruMoon** [comment]
> @SNMetamorph Постоянно убегающей вперёд анимации точно не было до того коммита, так что этот баг не связан с теми.

этот баг уже достаточно давно

**Comment by Vladislav4KZ** [comment]
Эту ишшую можно тоже закрывать, я же писал про то же самое здесь https://github.com/FWGS/xash3d-fwgs/issues/501

**Comment by unnamed9** [comment]
Не исправлено, анимации NPC на старых coop серверах до сих пор убегают вперёд самого NPC.

**Comment by Vladislav4KZ** [comment]
Да, мне кажется стало только хуже. Зашёл на Кооп сервер, стало дёргаться сильнее чем раньше
