### ISSUE TITLE
materials: include files

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#710]
Раз мы не можем искать файлы внутри директории, то может мы хоть сможем явно их включать через общие файлы?
Хочется структурировать материалы по группам иначе тот же halflife.wad/materials.mat очень распухнет.

**Comment by a1batross** [comment]
Не понял вопроса. Ты не ошибся репозиторием?

**Comment by 0x4E69676874466F78** [comment]
@a1batross именно так 😿
