### ISSUE TITLE
App crashes on Half-Life Xen levels (Android)

### ISSUE THREAD

**Issue by androidnewbi** [FWGS/xash3d-fwgs#711]
I had the same problem on old engine, I'm not sure if the problem is my device (only has 384MB RAM) or engine. I'm using the 32 bit version and throughout the game, the app crashes every so often. However from the part of the game with the teleporting labs, it crashes very frequently, and by by Xen (map c4a2) the app always crashes on loading. The problem seems to be specific to certain maps and certain places in the maps. Has anyone else had this problem?
Here's the log 
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/7763151/engine.log)
![2021-12-22-13-03-58](https://user-images.githubusercontent.com/85172821/147107243-6f837526-a6e3-4d18-8aeb-d4c6b76e69ba.jpg)

Also a question, not an issue, how do i long jump?
And another question, how can i hide log or whatever its called (the yellow text) at the top of the screen?
![2021-12-22-14-28-50](https://user-images.githubusercontent.com/85172821/147108164-121ced24-dd58-4dbb-a986-fddda83e01ee.jpg)

**Comment by Adnan1091** [comment]
Wait,does the immersive mode bug has been fixed?I can't see immersive mode buttons on your screenshot.

**Comment by Adnan1091** [comment]
Wait,does the immersive mode bug has been fixed?I can't see immersive mode buttons on your screenshot.

**Comment by Vladislav4KZ** [comment]
> Wait,does the immersive mode bug has been fixed?I can't see immersive mode buttons on your screenshot.

Old android smartphones had physical buttons, and there is simply no navbar in the system

**Comment by Adnan1091** [comment]
Dude,it's been 2 years i have reported this bug.I am not updating xash3d because of this.

**Comment by a1batross** [comment]
Can you post a logcat?

**Comment by androidnewbi** [comment]
> > Wait,does the immersive mode bug has been fixed?I can't see immersive mode buttons on your screenshot.
> 
> @Adnan1091
> 
> Old android smartphones had physical buttons, and there is simply no navbar in the system
> 
> And no, the navbar bug is still not fixed

Yeh, its an old phone with physical buttons



> Can you post a logcat?

U mean me or @Adnan1091?

**Comment by a1batross** [comment]
Yeah, you. Post system log.

Add "-noch" to the engine command line, reproduce the bug and post log.

**Comment by androidnewbi** [comment]
u mean to type it in console? Warning: Unknown command
Sorry if i misunderstood you

**Comment by a1batross** [comment]
There is a "command line arguments" field in launcher.

You just need to add "-noch" here. With spaces, so if it has for example "-dev 3 -log", you need to add so it looks like "-dev 3 -log -noch".

**Comment by androidnewbi** [comment]
Sorry to drive you nuts, but I'm not sure how to get log.
I have the CatLog app and it has the option to save log or record log, app crashes if i select to record log.
Should i open engine (with -noch command) reproduce error, and then go into CatLog and select save log and post?

**Comment by a1batross** [comment]
You need to:
1. Start recording log.
2. Start the engine (with -noch command line argument)
3. Reproduce crash
4. Stop recording log and post it here.

I don't know anything about CatLog app but I suppose it needs root to be able to record logs for other application that itself.

I usually do it most simple way, just connect my phone to PC, enable debugging and run `adb logcat`. There is many guides on Internet how to do this, like this for example: https://support.citrix.com/article/CTX232375

**Comment by androidnewbi** [comment]
Then i guess I'm out of luck, i haven't been able to root my device and cant connect my device to PC (USB port broken and only works for charging).
I knew CatLog needs root to log for other apps but thought that maybe -noch command somehow made engine log in a way i didn't need root...

**Comment by a1batross** [comment]
No, it just disables crash handling, that dialog box from first screenshot. :)

Android has it's own better crash handling thing but it's only shown in logcat. :(

**Comment by androidnewbi** [comment]
Right, get it now :)
Do you know where the android logcat is stored in root?
I have a way of getting temp root access to view files manually (not through another app) but need to know where they are stored.
I googled it but didn't find anything

**Comment by Velaron** [comment]
There are plenty of apps on Google Play that allow you writing logs without PC or root

**Comment by androidnewbi** [comment]
Yeh but as @a1batross said needs root to log other apps

**Comment by Velaron** [comment]
That is true only for new Android versions

**Comment by Velaron** [comment]
Turns out it's here since Android 4.1.2, guess I am too old xD

**Comment by Vladislav4KZ** [comment]
> Yeh but as a1batross said needs root to log other apps

Logcat available without root/adb on Android 4.0 or older

Otherwise you need PC with Android Debug Bridge, or rooted Android

**Comment by androidnewbi** [comment]
> Turns out it's here since Android 4.1.2, guess I am too old xD

:) and I'm even older, running android 2.3 😉

Here's the log, hope its the right thing (sorry for not cutting out all but relevant part, not sure which parts needed) 
[log.txt](https://github.com/FWGS/xash3d-fwgs/files/7769909/log.txt)

**Comment by androidnewbi** [comment]
Not sure if this is of any interest but just noticed that as the game loads just before crash, part of the log or console or whatever its called is highlighted red, is this some kind of out of memory error or something?
![2021-12-23-18-38-33](https://user-images.githubusercontent.com/85172821/147280936-a7b65270-afb8-40fe-ad9b-247a69732a24.jpg)

**Comment by mittorn** [comment]
Looks like out of memory as i do not see andy debugger messages, process just died. And i see many gc messages before xash3d dies. Try reduce limits in gameinfo.txt

**Comment by androidnewbi** [comment]
Thanks for response!
How do i reduce limits?

**Comment by androidnewbi** [comment]
What parameters should I edit within the file?
Thanks
