### ISSUE TITLE
No random seed for random tiles 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#712]
При каждом запуске оригинальной халфы есть случайное зерно для случайных тайлов.
Видеодемонстрация работы механизма: https://www.youtube.com/watch?v=NNv17T02WlY
Тестовая карта: [test_random_tiling.zip](https://github.com/FWGS/xash3d-fwgs/files/7768724/test_random_tiling.zip) 
В ксаше всегда одна и та же последовательность случайных текстур каждый раз.

Тестировать через `+map test_random_tiling` потому что в оригинальной халфе тайлы не меняются при смене карт через консоль, зерно там на всю сессию движка.

**Comment by a1batross** [comment]
Не стал их менять. Рандом есть, но он не зависит от запуска.

**Comment by 0x4E69676874466F78** [comment]
@a1batross то есть это сознательный уход от случайной смены?
А почему не стал? Может лучше консольной командой задавать поведение?

**Comment by a1batross** [comment]
А зачем? Карта всегда выглядит одинаково, есть детерменированность.

**Comment by 0x4E69676874466F78** [comment]
Потому что это задокументированная фича оригинальной халфы:
> A Half-Life innovation is the randomly tiling texture set. This texture is very useful for organic materials or for organic damage to regular textures. With a random texture family, each texture is designed to tile seamlessly with any other member of the family, and by applying the first member of the random set to a wall, the engine will display that wall with a randomly tiled assortment of all members of that random set.
There can be up to ten members of a randomly tiling set. The naming convention is that all members of the family have the same name, preceded by -X, where X is a digit from 0 to 9, in ascending order. For example, a six texture random set would be named -0texname.bmp to -5texname.bmp.
Note that by applying the first member (the -0 texture) of the set to a brush, you apply the whole set. If you apply any other member of the set, then the wall appears with only that member and no other

**Comment by a1batross** [comment]
Фича задокументированная и поддерживается Ксашем.

Собственно о чём и тред: голдсорс меняет рандом каждый перезапуск, ксаш же его не меняет каждый запуск, seed статичен.

**Comment by a1batross** [comment]
Но зачем?

**Comment by Velaron** [comment]
Наверно потому что Xash3D рекламируется как опенсорсная альтернатива GoldSrc совместимая с его модами, если конкретно у тебя нет желания этим заниматься можно хотябы оставить ишую пока кто-то не запилит

**Comment by a1batross** [comment]
Мне просто интересно как переключение текстурок в рандомном порядке связано с совместимостью. То что оно не от каждого перезапуска движка зависит наоборот в плюс -- карта визуально от этого не меняется, сколько бы раз вы её не запустили.

Если что выпиливается одной строчкой.

**Comment by 0x4E69676874466F78** [comment]
@a1batross так задумали разработчики, это художественный приём. Без этого игровой опыт не будет идентичным тому времени. Фича конечно может быть спорная, но она есть и в каком-то роде она уникальная.
Этот приём потенциально могут даже использовать для случайных головоломок (и секретов) которые не проходятся тупо по прохождению, например на карте разбросаны статуи и на одной из них есть разгадка, при каждом запуске игры текстура с разгадкой будет в разных местах.

**Comment by a1batross** [comment]
Фича не спорная -- это максимум решение наидревнейшей проблемы, когда мы в силу особенностей нашего зрения легко видим повторяющийся узор.

Только на логику игровую это никак не влияет. :) Это всё только заботы рендерера.

**Comment by 0x4E69676874466F78** [comment]
Почему же они решили делать случайное зерно каждый запуск халфы, а не захардкодить какое-то значение?
И говорю это реально могут использовать для игровых механики головоломки, возможно в каком-то моде где-то это даже используют, кто знает.

**Comment by nekonomicon** [comment]
> Наверно потому что Xash3D рекламируется как опенсорсная альтернатива GoldSrc совместимая с его модами, если конкретно у тебя нет желания этим заниматься можно хотябы оставить ишую пока кто-то не запилит

Претендующая на clean room.
У Васи так, а у Пети вот так, нужно ли иначе?

**Comment by Velaron** [comment]
Может тогда не стоит обещать совместимость? Это в любом случае осознанный выбор сделанный разработчиками халвы, а значит поведение в движке должно соответствовать оригиналу.

**Comment by 0x4E69676874466F78** [comment]
@nekonomicon да просто квар завести для режимов работы и всё.

**Comment by nekonomicon** [comment]
Совместимость на уровне чего?
Идентичность обещать глупо, никто не спорит.

**Comment by Velaron** [comment]
А какая собственно разница на уровне чего?) На уровне рендера или системы материалов, не имеет значения. Это в любом случае деградация которая не привносит ничего объективно хорошего, чисто вкусовщина которой мне кажется не очень место в такой части движка.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/f0feb1dfbf9a9d5f62f8f19ccb744c0d5acac8ed

Вместо нытья могли бы уже поправить самостоятельно.
