### ISSUE TITLE
console_history.txt

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#714]
Очень полезная штука, но с багами. Почему-то очень много пустых линий в текстовом файле у меня набирается.
![Безымянный](https://user-images.githubusercontent.com/70335841/147391442-0da7a456-4b9a-4eb6-b3ff-f57b0fb617b9.jpg)
Отдельно хотелось бы, чтобы если команда совпадает на 100%, то она бы не дублировалась. Скажем, если я ввел "r_shadows 1" 4 раза подряд, то сохранялась бы только одна строчка. Бывает часто, что я стрелочками меняю последние команды и одну и ту же нажимаю два раза случайно, а потом она еще и дублируется в истории и все это потом в прогрессии...нувыпонели.

**Comment by a1batross** [comment]
Должно быть пофикшено после f007374

**Comment by Aynekko** [comment]
Похоже, нет (я скачал из continuous билда)
Вот первый запуск, вбил несколько команд, вышел. Пробелов вроде нет, но строчка продублировалась.
![image](https://user-images.githubusercontent.com/70335841/147820411-c37f82c8-7c45-45a1-b856-dc4d32f99c1d.png)
Вот что произошло после второго запуска и выхода. Я стрелочками вверх-вниз выбрал пару команд и активировал.
![image](https://user-images.githubusercontent.com/70335841/147820501-bfb6b7ab-5c78-4c0c-9609-70f73864a2e7.png)
И наконец, третий запуск. Пару команд вбил сам, пару выбрал стрелочками.
![image](https://user-images.githubusercontent.com/70335841/147820571-01850068-7399-4527-abf2-740d72126543.png)

**Comment by magisk666** [comment]
biuld

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Aynekko ***@***.***>
Sent: Sunday, December 26, 2021 2:36:47 AM
To: FWGS/xash3d-fwgs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FWGS/xash3d-fwgs] console_history.txt (Issue #714)


Очень полезная штука, но с багами. Почему-то очень много пустых линий в текстовом файле у меня набирается.
[Безымянный]<https://user-images.githubusercontent.com/70335841/147391442-0da7a456-4b9a-4eb6-b3ff-f57b0fb617b9.jpg>
Отдельно хотелось бы, чтобы если команда совпадает на 100%, то она бы не дублировалась. Скажем, если я ввел "r_shadows 1" 4 раза подряд, то сохранялась бы только одна строчка. Бывает часто, что я стрелочками меняю последние команды и одну и ту же нажимаю два раза случайно, а потом она еще и дублируется в истории и все это потом в прогрессии...нувыпонели.

―

**Comment by zgdump** [comment]
Проблема так же наблюдается и у меня. После коммита f007374 проблема не ушла

**Comment by Aynekko** [comment]
Бамп, хотелось бы фикс

**Comment by a1batross** [comment]
Попробуй с этим коммитом 081cf9132bd8bc7ad8a81e2af6fccbfe5dd1e3da 

Если всё ок, закрой issue.

**Comment by Aynekko** [comment]
Все отлично вроде как, протестил несколько запусков. Спасибо :)
