### ISSUE TITLE
Server crashes on startup 

### ISSUE THREAD

**Issue by eliasbrucart** [FWGS/xash3d-fwgs#715]
As of today 12/28/2021 my xash server crashes when it finishes loading all the plugins and modules. The log throws me the following error: 

[2021:12:28|13:58:58] Sys_Crash: address 41414141, code C0000005
 0 41414141(???)
 1 0D874143(???)
 2 100E206B SV_DirectConnect (server\sv_client.c:134:31) (xash_sdl.dll)
 3 100E9D59 SV_ConnectionlessPacket (server\sv_client.c:3385:49) (xash_sdl.dll)
 4 10100C4B SV_ReadPackets (server\sv_main.c:413:27) (xash_sdl.dll)
 5 10101399 Host_ServerFrame (server\sv_main.c:685:0) (xash_sdl.dll)
 6 10023279 Host_Frame (common\host.c:797:0) (xash_sdl.dll)
 7 10022572 Host_RunFrame (common\host.c:277:18) (xash_sdl.dll)
 8 100225A9 Host_FrameLoop (common\host.c:300:0) (xash_sdl.dll)
 9 1002412A Host_Main (common\host.c:1395:0) (xash_sdl.dll)
 10 0040124D(xash_vc.exe)
 11 0040138A(xash_vc.exe)
 12 76D80419 BaseThreadInitThunk (KERNEL32.DLL)
 13 777B662D RtlGetAppContainerNamedObjectPath (ntdll.dll)
 14 777B65FD RtlGetAppContainerNamedObjectPath (ntdll.dll)

I don't upload the whole file because the first part is loading the plugins, modules, etc.

**Comment by mittorn** [comment]
It seems that address was overwriten with "AAAA" string

**Comment by Vladislav4KZ** [comment]
> xash_sdl.dll

Why did you report a bug on Xash3D FWGS 0.19.2 (Old Engine) in the Xash3D FWGS 0.20.1 (New Engine) repository?
