### ISSUE TITLE
Will CS16Client upgrade to xash 0.20.0 new engine?

### ISSUE THREAD

**Issue by Insans12** [FWGS/xash3d-fwgs#717]
Why is cs16client not updated to work with the xash 0.20.0 new engine ?
recently a hacker who knows a vulnerability of version 0.19.2 entered my server, sent messages without a name and crashed it instantly
![Screenshot_20211231-203751_Xash3D FWGS](https://user-images.githubusercontent.com/95554903/147867449-5732d9a5-c824-48b5-9a01-984daed989ad.jpg)
![Screenshot_20211231-203526_Xash3D FWGS](https://user-images.githubusercontent.com/95554903/147867451-1ce6dde3-0a67-4874-979d-cda1a56ab02b.jpg)
The link offers a supposed build of xash 0.19.3 that removes the "invisible player" vulnerability, amxx privilege bypass, etc, but I'm sure it's a virus. If there is actually a version of xash 0.19.3 beta, please send it to me.

**Comment by nekonomicon** [comment]
> Why is cs16client not updated to work with the xash 0.20.0 new engine ?

New engine in beta stage yet.
Plus you can connect from an old client to xash3d fwgs 0.20.1 server.

**Comment by Vladislav4KZ** [comment]
> Plus you can connect from an old client to xash3d fwgs 0.20.1 server.

@nekonomicon you are wrong, from the old engine it's impossible to connect to the server based on new engine

**Comment by a1batross** [comment]
We probably need to finalize new engine ASAP and build CS16Client as is.

Old engine vulns that nobody will ever fix is really, really bad.

**Comment by Insans12** [comment]
> We probably need to finalize new engine ASAP and build CS16Client as is.
> 
> Old engine vulns that nobody will ever fix is really, really bad.

Ok thanks for the information
