### ISSUE TITLE
Увеличить лимит MAX_MODELS и MAX_MAP_MODELS.

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#718]
Я использую ксашмод и уже без проблем повышал этот лимит в движке. Поэтому хотелось бы, чтобы его повысили "официально", чтобы было проще обновлять движок без перекомпила под себя. 1024 модели это очень мало, т.к. ксаш поддерживает огромные карты, а в ксашмоде почти все декорации делаются как в сорсе - пропами.
Опытным путем выяснил, что можно поднять лимит без проблем до 4096.
Если не в движке делать, так хотя бы вынесите оверрайд в gameinfo.тхт. Эдикты же можно поднять до 8192, а модели всего лишь 1024... Заранее спасибо!

**Comment by mittorn** [comment]
А не жирно?
Лимиты, заложенные в протокол меняются не "без проблем"

**Comment by SNMetamorph** [comment]
> А не жирно? Лимиты, заложенные в протокол меняются не "без проблем"

В 0.20 их в протоколе бы стоило подтянуть на будущее, всё равно не с чем обратную совместимость ломать.

**Comment by Aynekko** [comment]
> А не жирно?
Не жирно, я ведь только что объяснил, почему.

**Comment by a1batross** [comment]
```
#define MAX_MODEL_BITS		12		// 12 bits == 4096 models
#define MAX_SUPPORTED_MODELS		(1<<MAX_MODEL_BITS)

#ifdef SUPPORT_BSP2_FORMAT
#define MAX_MODELS			MAX_SUPPORTED_MODELS	// because BSP2 contain too much embedded bsp-models
#else
#define MAX_MODELS			1024		// g-cont. reduce the memory without breaking proto
#endif
```

Мы можем спокойно увеличивать до 4096 без потери совместимости.

**Comment by SNMetamorph** [comment]
Может быть стоит в 0.20 сразу пачкой поднять некоторые лимиты в протоколе? Ибо потом уже действительно без нарушения совместимости это не получится сделать. А пока что серверов на 0.20 совсем нет.

**Comment by a1batross** [comment]
@SNMetamorph нет, мы никогда не ломаем протокол. Сверху добавить можно, менять нельзя.

49-ый протокол уже есть в природе, провернуть фарш через мясорубку обратно нельзя.

**Comment by a1batross** [comment]
MAX_MODELS решил всё же увеличить до предела текущего протокола. Судя по комментарию, лимит был ниже из-за потребления памяти, но у нас давно для этого есть решение в виде low memory mode при компиляции движка.

MAX_MAP_MODELS по идее не должен влиять на реальный лимит, но при этом в загрузчике моделей лимит всё равно проверяется, плюс к тому же в [UMHLT](https://github.com/FWGS/UMHLT/blob/master/common/bspfile.h#L14) и [Paranoia2](http://git.mentality.rip/mittorn/Paranoia2/src/branch/lp64/common/bspfile.h#L64) лимит выше, чем того позволяет движок.

**Comment by Aynekko** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/ddc4d7666874ce050d33ba6cc5781f08180776c5/common/bspfile.h#L76
Этот лимит можно увеличить до 2048? При тесте лимитов обнаружил что нельзя создать более чем 768 брашевых энтитей. Это маловато, учитывая лимит по моделькам 4096 и общим энтитям 8192.
Вот цитата Дяди Миши:
"протокол оно не ломает, просто начинает жрать больше памяти."
Ссылка на цитату:
http://hlfx.ru/forum/showthread.php?s=4b18f5056c1cfb51e4e09a546e1aa14d&threadid=3689&postid=200784#post200784

**Comment by a1batross** [comment]
Поменял до 1024, чтобы соответствовать PrimeXT компиляторам. 9f914182

**Comment by SNMetamorph** [comment]
> Поменял до 1024, чтобы соответствовать PrimeXT компиляторам. [9f91418](https://github.com/FWGS/xash3d-fwgs/commit/9f9141823ae95392b8b4ef9bb663d1cf7aa157ff)

Блин, а я в компиляторах еще хотел поднять некоторые лимиты, в т.ч. и этот

**Comment by Aynekko** [comment]
Поднимите до 2048 и там, и там, будет оптимально для брашевых моделей
https://github.com/SNMetamorph/PrimeXT/blob/9d7fce11125fa2ebf893ce94400169b48d49e3a6/common/bspfile.h#L69

**Comment by a1batross** [comment]
@SNMetamorph как поменяешь тогда, кинь патч и сюда.

В UMHLT тоже 2048 моделей лимит. Так что имеет смысл унифицировать.
