### ISSUE TITLE
Transparent bug in CS 1.5

### ISSUE THREAD

**Issue by sidreshot** [FWGS/xash3d-fwgs#722]
Hello!
Launched the game and see a transparent weapon.
In the HL itself, everything is fine.
Tried various graphical settings - didn't help.
![2022-01-05_03-12](https://user-images.githubusercontent.com/10060394/148130987-b1c769e2-9932-42c3-9d7c-f20f22a546a3.jpg)
![2022-01-05_03-122](https://user-images.githubusercontent.com/10060394/148130989-b1480034-08b0-4955-bee2-83a318260dc4.jpg)

Windows 11/ xash3d-fwgs 32bit v0.20/Nvidia GTX1080

**Comment by a1batross** [comment]
Try to toggle cl_righthand value

**Comment by sidreshot** [comment]
> 

I tried it. The graphical bug has nothing to do with which hand the player has the weapon in.

**Comment by Vladislav4KZ** [comment]
Я уже писал https://github.com/FWGS/xash3d-fwgs/issues/387

И да, я знаю что ты можешь читать по русски

**Comment by sidreshot** [comment]
> Я уже писал #387
> 
> И да, я знаю что ты можешь читать по русски
Гуглил, гуглил! Ясно. Этим единственным последним критичным на мой взгляд багом более полугода никто не реагирует. Будем надеяться на реакцию.

**Comment by a1batross** [comment]
Duplicate of #387
