### ISSUE TITLE
Движок не открывает ZIP-файлы без сжатия

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#724]
Файлы созданы через 7Zip
![изображение](https://user-images.githubusercontent.com/25657591/148644433-3efdd4ba-be2c-4f13-9542-8fe9270624b8.png)

**Comment by a1batross** [comment]
Can you post an example?

**Comment by SNMetamorph** [comment]
Yes, it's testmap.zip
https://disk.yandex.ru/d/oSJa2goF5SVAMg

**Comment by Vladislav4KZ** [comment]
ZIP файлы с сжатием движок теперь тоже не открывает, он даже не запускается, и пишет что архив повреждён

**Comment by Vladislav4KZ** [comment]
```
Error: cannot find EOCD in tfc/custom/TFCRusFull.pk3. Zip file corrupted.
Mem_Free: data == NULL (called at D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\filesystem.c:931)
```

**Comment by a1batross** [comment]
Fixed in e29dcb4125e17d3bbf0860361d77e141ddb69b12 and 606b5354e63e5e4f5b6239002d9501fa8f33dcda
