### ISSUE TITLE
При нажатии на вторичную атаку, кнопка первичной атаки "отжимается"

### ISSUE THREAD

**Issue by Aynekko** [FWGS/xash3d-fwgs#725]
Ситуация: у меня есть оружие, которому можно менять зум на вторичную атаку (ПКМ) и при этом заряжать (как гаусс) на первичную (ЛКМ). Когда я нажимаю ПКМ, оружие тут же стреляет, будто отжимается ЛКМ. Это на continuous билде.
Я проверил релизный билд (0.20, 1707) - там такого нет. Если зажать ЛКМ, а потом зажать ПКМ, то оружие мое продолжает заряжаться и нормально зумится. То же самое поведение на оригинальном ксаше 4529. Что-то изменилось в continuous билде.

**Comment by lewa-j** [comment]
Забыл уточнить, какое поведение в стиме.

**Comment by a1batross** [comment]
Must be fixed in https://github.com/FWGS/xash3d-fwgs/commit/abbd0f92a48b6b8bdda0b57157e223b39a18b589

**Comment by Aynekko** [comment]
> Must be fixed in [abbd0f9](https://github.com/FWGS/xash3d-fwgs/commit/abbd0f92a48b6b8bdda0b57157e223b39a18b589)

Да, пофиксилось. Спасибо!
