### ISSUE TITLE
Relative mouse mode is never enabled on Windows when using non-SDL input

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#726]
For example when using a client compiled from hlsdk-xash3d, the mouse gets stuck in-game

**Comment by mittorn** [comment]
Ну значит опять пора ревертить мышку или плодить костыли

**Comment by a1batross** [comment]
Ревертиться ничего не будет. Костыли я как раз все вычистил. Последние пару-тройка ишшуй точно связаны с мышью и я их исправлю.

У нас фактически три режима работы мышки, которые нужно поддерживать. Это когда есть унифицированный интерфейс ввода и когда в клиенте SDL2 или Win32 код.

С унифицированным все относительно просто, мы сами занимаемся мышкой, в клиент передаем только УГлы. Движок в этом плане спасён, но конкретно передача лишь углов может в теории помешать играм например с top-down механиками. К счастью таких нет.

SDL2 ввод добавили Valve, когда портировали свои игры на Linux. Только по неизвестной мне причине они же его и принесли и в винду. Даже голдсорс с этим фактом плохо дружит -- по всему коду ввода понатыканы проверки `BClientUseSDL`, который выставляется в `true` только для клиенток Valve, проверкой на захардкоженный путь к client.dll. 

Мало того их клиентки с мышкой работают через SDL2, так ещё и включается этот код только с `m_rawinput`. Без него как вы можете догадаться работает только Win32 код. Это всё отвратительно, работает плохо, но ничего с этим не поделать -- совместимость.

Win32 ввод же был всегда. С его точки зрения движку для поддержки мыши делать нужно целое НИЧЕГО, поскольку всей мышью занимается клиент. Самое простое решение для движка и наиболее гибкое для мододелов.

В ранние дни форка эту схему понимало ровно 0 человек. Поэтому старый код мыши полон костылей, которые как-то должны вместе работать, но на самом деле нет. На те случаи когда ВООБЩЕ ничего не работает, был добавлен `m_enginemouse`. Но с корректной реализацией, которая удовлетворяет всем трём выше перечисленным, он скорее всего будет удалён.

**Comment by a1batross** [comment]
Must be fixed in c3513b1

**Comment by Velaron** [comment]
Fixed
