### ISSUE TITLE
cl_dlls/client_amd64.so not found

### ISSUE THREAD

**Issue by Foxtrot-Uniform** [FWGS/xash3d-fwgs#727]
When I try to launch the appimage it gives me this error in a window titled Xash Error

Host_InitError: can't initialize cl_dlls/client_amd64.so: Failed to find library cl_dlls/client_amd64.so cl_dlls/client_amd64.so: cannot open shared object file: No such file or directory.

I press OK and as to be expected nothing happens. I copied appimage release of the latest rolling version and placed extras.pak in valve folder of my WON GOTY installation with BS and OF

**Comment by a1batross** [comment]
Run 32-bit appimage

Or compile our HLSDK branch from sources

вт, 11 янв. 2022 г., 23:35 Foxtrot-Uniform ***@***.***>:

**Comment by Foxtrot-Uniform** [comment]
hmm

debian@debian:~/XASH3D$ '/home/debian/XASH3D/xash3d-fwgs-i386.AppImage' 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

I tried appimage extract and it complaeid about 

debian@debian:~/XASH3D$ '/home/debian/XASH3D/xash3d-fwgs-i386.AppImage' --appimage-extract
squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/activities.txt
squashfs-root/extras.pak
squashfs-root/libSDL2-2.0.so.0
squashfs-root/libmenu.so
squashfs-root/libref_gl.so
squashfs-root/libref_soft.so
squashfs-root/libvgui_support.so
squashfs-root/libxash.so
squashfs-root/mdldec
squashfs-root/vgui.so
squashfs-root/xash3d
squashfs-root/xash3d-fwgs.desktop
squashfs-root/xash3d-fwgs.png
debian@debian:~/XASH3D$ ls
squashfs-root  valve  xash3d-fwgs-amd64.AppImage  xash3d-fwgs-i386.AppImage
debian@debian:~/XASH3D$ cd squashfs-root
debian@debian:~/XASH3D/squashfs-root$ ls
activities.txt  libref_gl.so        libxash.so  xash3d-fwgs.desktop
AppRun          libref_soft.so      mdldec      xash3d-fwgs.png
extras.pak      libSDL2-2.0.so.0    vgui.so
libmenu.so      libvgui_support.so  xash3d
debian@debian:~/XASH3D/squashfs-root$ cd
debian@debian:~$ cd XASH3D
debian@debian:~/XASH3D$ '/home/debian/XASH3D/xash3d' 
Xash Error: Unable to load the libxash.so: libxash.so: cannot open shared object file: No such file or directory

of course I didnt forget to copy contents of squashfs to XASH3D directory

apt reintstall libfuse2 libfuse3-3 later nothing changed

weirdly enough AMD64 this time gave me "cant initliazle any video renders check your video drivers" probably due to my horrid old system of Turion TL-52 Amd XPress 200 system with OpenGL 2.1 but isn't there supposed to be fallback software renderer? Maybe I should try running old engine

I use Debian Sid

**Comment by Foxtrot-Uniform** [comment]
Also I checked manually and there is only client.dll in cl_dlls folder

**Comment by a1batross** [comment]
At first. Why do you expect to WON version to work if it was only released for Windows? Use latest Steam versions of the games, they support Linux.

At second, you don't need to unpack AppImage usually. Install 32-bit libfuse.

=========

Of course this wouldn't be so relevant, if you would compile HLSDK from source for 64 bits. Valve never provided 64-bit ports of their GoldSource games. We are supporting such ports on our own.

**Comment by a1batross** [comment]
Updated README with explanation of this issue.

**Comment by bulkmoerls** [comment]
> Of course this wouldn't be so relevant, if you would compile HLSDK from source for 64 bits. Valve never provided 64-bit ports of their GoldSource games. We are supporting such ports on our own.

3 years later. at least i compiled the HLSDK though. but i didn't get the client_amd64.so i would expect. did i miss anything?

**Comment by nekonomicon** [comment]
> did i miss anything?

Yep, always read documentation:
https://github.com/FWGS/hlsdk-portable?tab=readme-ov-file#build-options

**Comment by BKVad1m** [comment]
> Run 32-bit appimage
> 
> Or compile our HLSDK branch from sources
> 
> вт, 11 янв. 2022 г., 23:35 Foxtrot-Uniform ***@***.***>:
> […](#)

I don't have 32 bit OpenGL installed on linux because renders only 64 bit OpenGL and vulkan

<img width="783" height="258" alt="Image" src="https://github.com/user-attachments/assets/594d13d2-af7a-4293-96c6-c9ea92aeb4f4" />

**Comment by lewa-j** [comment]
> > Run 32-bit appimage
> > Or compile our HLSDK branch from sources
> > вт, 11 янв. 2022 г., 23:35 Foxtrot-Uniform _**@**_.***>:
> > […](#)
> 
> I don't have 32 bit OpenGL installed on linux because renders only 64 bit OpenGL and vulkan

Compile 64 bit HLSDK then
