### ISSUE TITLE
wscript: -fPIC not passed to linker with --enable-lto

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d-fwgs#73]
LTO generates position-depended code and fails to link without -fPIC in linker

**Comment by a1batross** [comment]
Why fpic isn't here? I thought, it added everywhere.

**Comment by mittorn** [comment]
on compile only, but LTO need compiler flags (including -fPIC) passed to linker too

**Comment by a1batross** [comment]
@mittorn where can I find a documentation of this behaviour?

**Comment by mittorn** [comment]
How LTO will generate code if it does not know correct compiler flags?

**Comment by a1batross** [comment]
@mittorn I understand this, but I sure we can't just append C/C++ flags to linker flags?

**Comment by mittorn** [comment]
all -f* and machine flags should be passed. I not sure about warnings, but lto may pooduce warnings too. preprocessor flags not needed of cause

**Comment by mittorn** [comment]
From gcc docs:
```
To use the link-time optimizer, -flto and optimization options should be specified at compile time and during the final link. It is recommended that you compile all the files participating in the same link with the same options and also specify those options at link time
```

**Comment by a1batross** [comment]
Fixed.
