### ISSUE TITLE
cl_dlls/client_arm64.so Not Found

### ISSUE THREAD

**Issue by act17** [FWGS/xash3d-fwgs#730]
I tried to compile the engine on a Raspberry Pi 400, and while everything went as expected, when trying to run the engine - and this is through a Shell file using `LD_LIBRARY_PATH=. ./xash3d` as is recommended - the program returns an error, stating that the file `cl_dlls/client_arm64.so` isn't found.
Did I miss a flag being checked in the compiling process? I can't seem to find any in the README. Thanks in advance for helping.

**Comment by a1batross** [comment]
Build [HLSDK](https://github.com/FWGS/hlsdk-xash3d] from source
