### ISSUE TITLE
Курсор не сдвигается с центра в главном меню

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#731]
Замечено в ~~модах The Specialists и Counter-Strike 1.5~~ во всех модах и возможно старых версиях Half-Life которые не используют SDL2

После открытия и закрытия консоли, курсор начинает нормально перемещаться по экрану

**Comment by SNMetamorph** [comment]
Плюсую. Тоже с этим только что столкнулся. Сброс конфига не помог.

**Comment by Vladislav4KZ** [comment]
Пофикшено https://github.com/FWGS/xash3d-fwgs/commit/89baa633c86324d00eec841fc9c365992a635c27
