### ISSUE TITLE
Sound amplifies multiple times if the window was minimized

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#734]
Звук почему-то накапливается. Это на винде.
Если при включённой галке "mute when inactive" рядом с повторяющимся звуком сверну окно и подожду минуты 3-4 то при разворачивании будет ужасный громкий звук что можно вздрогнуть, особенно когда в самой игре звук сделан тихим.
Также замечено что запоминается последний звук выстрела в сетевой игре, то есть игрок рядом стрельнул пока мы были свёрнуты, мы разворачиваем и слышим звук выстрела который уже давно свершился.
Как пример можно постоять на c0a0a у манипулятора.

**Comment by 0x4E69676874466F78** [comment]
Вот демонстрация:

https://user-images.githubusercontent.com/4449851/149670654-f220b227-00ff-4d91-ba02-da713fce2199.mp4

Вырезал долгое ожидание.

**Comment by Vladislav4KZ** [comment]
Галочка Mute when inactive почему-то не работает в полноэкранном режиме когда сворачивает игру

**Comment by Vladislav4KZ** [comment]
Про мут я уже писал https://github.com/FWGS/xash3d-fwgs/issues/391

**Comment by zgdump** [comment]
Проблему на Windows 10 и 11, x64 не наблюдаю. Но имею другую, очень похожую. Будто после сворачивания на пару секунд звук начинается двоится. Лучше всего воспроизводится на уровнях с вагончиком

**Comment by a1batross** [comment]
Больше похоже на то, что вместо Pause надо громкость в 0 выставлять.

Так микшер будет продолжать работать, просто без звука.

**Comment by 0x4E69676874466F78** [comment]
@zgdump чтобы мою проблему повторить надо быть именно с повторяющимся звуком.
А твою проблему с двоящимся звуком я ловил на вагончике где дикторша говорит если делать альтаб туда-сюда много раз в какой-то момент можно пойпать что она начинает двоиться. 

@a1batross как вариант обхода проблемы да.

**Comment by ruvaldak** [comment]
English translation transcript using translator: 

> Sound is piling up for some reason. This is the case on the Windows.
If with the tick "mute when inactive" next to the recurring sound minimize the window and wait 3-4 minutes, then when you unfold will be horrible loud sound that you can shudder, especially when the game itself made the sound quiet.
Also noticed that the last sound of a shot in online game is remembered, that is, a player nearby shot while we were minimized, we turn around and hear the sound of the shot, which has long been accomplished.
As an example, you can stand on the c0a0a at the manipulator.

> Here is a demonstration (turn on the sound in the video): [video] Cut out the long wait.

> The Mute when inactive checkbox does not work in full screen mode when you minimize the game for some reason

> I already wrote #391 about the mute.

> I don't have the problem on Windows 10 and 11, x64. But I have another one, very similar. It's like after minimizing for a couple of seconds the sound starts to double. It plays best on levels with a carriage

> It looks more like you should set the volume to 0 instead of Pause. That way the mixer will continue to work, just without sound.

> zgdump to repeat my problem it is necessary to be close to the repeating sound, or in a network game that someone nearby shot (although perhaps this is another problem already).
And your problem with the ambiguous sound, I caught on the trailer where the announcer said if you do a lot of back and forth in a moment you can catch that she begins to double. 
a1batross as a way around the problem yes.


Just an intuitive guess, it seems like the "Mute when inactive" switch is preventing sounds from playing when they should - sort of like a stop sign - which causes those sound events to build up in a sort of queue. When returning to the game, that queue is then played all at once. A quick & dirty fix would be, as @a1batross said, to make "Mute when inactive" set the master volume to 0 when the game loses focus.

Well, I guess it's not really dirty, considering that's exactly what muting does. I don't really see a downside to doing it that way.

Русский перевод: 

Просто интуитивное предположение: похоже, что переключатель "Отключить звук при неактивности" не позволяет звукам воспроизводиться, когда они должны - что-то вроде знака "стоп" - что приводит к тому, что эти звуковые события накапливаются в своего рода очереди. При возвращении в игру эта очередь воспроизводится сразу. Быстрое и грязное исправление было бы, как сказал @a1batross, заставить "Mute when inactive" устанавливать главную громкость на 0, когда игра теряет фокус.

Ну, я думаю, это не совсем грязно, учитывая, что именно это и делает отключение звука. Я действительно не вижу недостатков в том, чтобы сделать это таким образом.

**Comment by Aynekko** [comment]
> Больше похоже на то, что вместо Pause надо громкость в 0 выставлять.
> Так микшер будет продолжать работать, просто без звука.

Да, сделайте пожалуйста так. А то прям бабах из звуков. :)

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/7584bbe47e01652ba3c7a513367c14093f190e3a

Спустя джва года пофиксил.
