### ISSUE TITLE
[Half-Life] Some stuff is missing with original DLLs

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#739]
From Discord by dongchan:

So I tried HL on Xash3D FWGS for the first time using the steam files and I'm noticing a couple of items missing and what might looks like some other differences here and there.
Can those things be fixed by compiling the forked SDK instead of what comes with the Steam?
I've so far noticed two:
\- In the intro where the tank that leaks, no toxic goo coming out
\- In the corridor where the room in which you get your first grenades, the explosive tank is missing (I also tried to shoot the area but nothing happened, it seems the entity itself is missing and not just a visual glitch)
Also I should have precised I'm running the git version under Linux

**Comment by 0x4E69676874466F78** [comment]
Почему нет инфы на каких картах это происходит?

**Comment by a1batross** [comment]
@0x4E69676874466F78 
c0a0d
c1a1b

Anyway, doesn't reproduce for me.

**Comment by 0x4E69676874466F78** [comment]
> c0a0d

Ни разу не ловил чтобы там из бака не лилось. С трубы сверху тоже капает.

> c1a1b

А вот здесь я поймал это причём по началу мне показалось что только 1 раз. Но дальше я смог повторить летая ноклипом, короче это "собачки" могут при некоторых обстоятельствах своей волной достать до баллона и взорвать его.

**Comment by 0x4E69676874466F78** [comment]
Зато обнаружил багу, почему-то на c1a1b я застреваю при map c1a1b, при этом в won в версии там можно присесть и выпрыгнуть, а в ксаше намертво.

**Comment by a1batross** [comment]
Can't reproduce
