### ISSUE TITLE
Some background image resolutions cause an assertion failure

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#742]
The error arises and leaves me to console when I click some menu item or just after some time being in menu:
```
Host_Error: assert failed at ../ref_gl/gl_image.c:48
```

Example of background files that cause the issue: [resource.zip](https://github.com/FWGS/xash3d-fwgs/files/7953435/resource.zip)

The background works in Goldsource and in old xash3d engine version. Though while Goldsource stretches the image to my aspect ratio, the old engine renders it from the top to bottom cutting the part that does not fit into aspect ratio.

**Comment by a1batross** [comment]
Cute background.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/mainui_cpp/commit/2325b3cd5f01d78a421be5a2385b1b5cc807626e

Will close this as soon mainui_cpp update hits the engine.

**Comment by Vladislav4KZ** [comment]
I played the field intensity mod which is known for this error in xash. On the latest build, there is no such problem.
