### ISSUE TITLE
Should build with _FILE_OFFSET_BITS=64 on 32-bit glibc

### ISSUE THREAD

**Issue by mia-0** [FWGS/xash3d-fwgs#745]
Since glibc hasn’t made this the default yet, running 32-bit builds will cause issues on filesystems with 64-bit inodes (such as XFS) unless this option is used. The engine will be unable to open files reliably.

(Valve’s GoldSrc builds have the same problem.)

**Comment by a1batross** [comment]
On i386 we mostly rely on prebuilt or even proprietary libraries like client or server, or VGUI.

We don't expose interfaces with FILE or DIR anywhere but anyway, isn't it going to break compatibility?

**Comment by a1batross** [comment]
Reviewed interfaces, we don't leak libc file/directory handles anywhere, so it's enabled for everything

Fixed in 6dbb694fdc4847bd9acfc5dbb284f627f2871128
