### ISSUE TITLE
Host_Error: Mod_LoadMarkFaces: bad surface number

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#748]
В общем, имеем мод Dark Future:
https://www.moddb.com/mods/half-life-dark-future/downloads/half-life-dark-future-version-10

На картах darkf6.bsp и darkf26.bsp проявляется отказ движка загружать карту с ошибкой "bad surface number". Данная проблема проявляется под любым билдом Ксаша, включая самые старые билды Дяди Миши. Под обычным Steam HL проблема игнорируется, движок успешно загружает эти карты. Ошибка в самих картах, видимо, действительно есть, но она не настолько критична, чтобы запрещать движку загружать карты, раз уж Steam HL справляется. Я открывал данные карты с помощью утилиты BSP Viewer. Они открываются, но при попытке просматривать карту в определённых местах происходит вылет. К сожалению, автор не согласился предоставить исходники карт, ответив, что не располагает ими уже. В общем, реквестирую научить движок обрабатывать подобные карты, хотя бы с добавлением квара, который будет игнорировать ошибку (если вдруг открытие таких карт по умолчанию чем-то нежелательно). За последнее время мне вроде бы попадалась такая ошибка где-то ещё, но уже не помню точно. Есть у нас квар sv_validate_changelevel для игнора ошибок смены уровня, тут вот, может быть, что-то подобное сделать, если что.

**Comment by 0x4E69676874466F78** [comment]
Через bspguy можешь ещё попробовать посмотреть и пересохранить им ради интереса.

**Comment by Qwertyus3D** [comment]
Делал это, открывает и сохраняет нормально, но проблема не исчезает.

**Comment by Qwertyus3D** [comment]
Удалось пофиксить карты мода, движок их теперь принимает. Но вопрос о возможности движка игнорировать подобные ошибки остаётся открытым.

**Comment by UnrealKaraulov** [comment]
Судя по названию просто не соответствует действительности число сурфейсов? возможно кнопка Clean в bspguy должна бы это исправить.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да, как раз при помощи BSPGuy я и сделал правку карты. Но, кажется, Clean мне не помог, а помогла оптимизация.

**Comment by UnrealKaraulov** [comment]
Ну видимо в ксаше какие-то более серьезные проверки валидности карты, чем в оригинале

**Comment by a1batross** [comment]
Один из марксурфейсов там 0x8000. Ксаш мало того не позволяет беззнаковые маркфейсы, что логично, так даже если бы позволял, всё равно там проверка на негативный маркфейс, что опять же имеет смысл -- как вы будете указывать на какой-то левый кусок памяти?

```
(gdb) p/x LittleShort(in[18653])

$15 = 0x8000
```

**Comment by UnrealKaraulov** [comment]
@a1batross странно :) А игнорировать нельзя ? 

Bad face reference in marksurf 18653: 32768 / 12840

В BSPGUY тоже есть предупреждение. (одна ошибка)

Может специально сделано что бы сломать возможность просматривать или использовать карты где-то кроме того мода?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил в BSPGUY обход ошибки, и в меню FIXES->'Bad Face Reference', просто на 0 заменит.

**Comment by a1batross** [comment]
@UnrealKaraulov сомневаюсь. В любом случае тут либо писать утилиту которая автоматом детектит все проблемы и их исправляет, либо... впрочем ссылаться на твой NewBSPGuy. :)

Ибо движок костылями и кварами я портить не хочу. У меня в целом негативное отношение к вынесенными костылями под квар, ровно, как и к предложениям такого рода.

**Comment by a1batross** [comment]
@UnrealKaraulov https://github.com/FWGS/xash3d-fwgs/issues/398 раз уж ты тут, стоит обратить внимание ещё и на этот баг. Его кстати тоже можно было в фиксы добавить, если банальное пересохранение у тебя его не исправляет :)

**Comment by UnrealKaraulov** [comment]
@a1batross не уверен, но я думаю если bspguy не упадет, то после сохранения все исправится, хотя возможно часть данных будет утрачена

**Comment by UnrealKaraulov** [comment]
А там самой карты не прикрепили :( У меня нету этой игры :)

**Comment by mittorn** [comment]
Не, ну можно было бы конечно встроить в движок какой-то валидатор который перестроит лумпы, как это делает bspguy, но во-первых это сложная задача, во вторых это лишний код и медленная процедура
Работать же с невалидными данными как голдсорс означает, что будет неопределённое поведение

**Comment by lewa-j** [comment]
> что будет неопределённое поведение

можно даже сказать, "непредвиденные последствия"

<sub>простите<sub/>

**Comment by Vladislav4KZ** [comment]
> А там самой карты не прикрепили :( У меня нету этой игры :)

@UnrealKaraulov вот карта [hplanet.zip](https://github.com/FWGS/xash3d-fwgs/files/10419690/hplanet.zip)

**Comment by UnrealKaraulov** [comment]
@Vladislav4KZ ну в bspguy открывается без проблем, никаких варнов не выдает. Не знаю почему ошибка происходит и не знаю пропадет ли она после пересохранения в bspguy :(

**Comment by Qwertyus3D** [comment]
Эта карта входит в состав карт нового Sven Co-op, там она рабочая. А этот старый вариант тоже работает, если просто открыть в BSPGuy и сохранить. Даже никаких фиксов не требуется.

**Comment by UnrealKaraulov** [comment]
Ну я так и думал но не знал будет ли утеряна какая-то информация при сохранении. Все же если не хватает закрытой скобки то могло и сбить что-то :)

**Comment by a1batross** [comment]
Думаю, старые сломанные карты можно спокойно отправлять в NewBSPGuy.

**Comment by a1batross** [comment]
Всё-таки для удобства сделал костыль, который игнорирует сломанные mark surface, если общее количество фейсов не превышает лимит int16_t.

https://github.com/FWGS/xash3d-fwgs/commit/178602ea1fa85f700a2a5873d983162b42b3e9f4
