### ISSUE TITLE
Error: map is invalid or not supported

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#749]
После билда 4097, в котором была вырезана поддержка формата карт Blue Shift, в движке также появились дополнительные ограничения на загрузку некоторых карт, которых раньше не было. Приведу в пример мод Half-Life: Hazardous Materials: https://www.moddb.com/mods/half-life-hazardous-materials/downloads/hazardous-materials-episode-2-zip

Раньше он был совместим, и нормально проходился, но после нововведений на картах hm_ep2_l6a, hm_ep2_l8, hm_ep2_l10a возникает ошибка "map *** is invalid or not supported". Как я смог выяснить, связано это с наличием у данных карт проблемы "funny lump size". При этом старые билды Ксаша и ГолдСорс данную проблему просто игнорируют, и никаких препятствий для нормального геймплея на них не возникает. Кроме данного мода также уже встречал эту ошибку с новыми версиями движка на картах других модов, которые также успешно были пройдены ранее.

Соответственно, реквестирую рассмотреть варианты обхода данной проблемы в связи с тем, что ошибка не настолько критична, чтобы запрещать движку загружать подобные карты.

**Comment by Qwertyus3D** [comment]
Сейчас проверил дополнительно эти карты на соответствие стандартам. В них превышен лимит по клип-нодам (более, чем 32767). Возможно, Дядя Миша запретил подобным картам загружаться без Ксаш-мода или П2, из-за введения расширенного формата BSP30. Т. к. само по себе превышение клип-нодов не должно быть препятствием для движка, скорее для компилятора, насколько я понимаю. Если что, можно сделать квар на совместимость для загрузки таких карт.

**Comment by Qwertyus3D** [comment]
Вот, ещё один мод вспомнил с данной проблемой, The Robotropolis Project: https://www.moddb.com/mods/the-robotropolis-project/downloads/the-robotropolis-project-part-1-clandestine-infiltration Карта satam3 имеет ровно 100% лимита клипнодов, 32767, движок помечает её, как неподдерживаемую.

**Comment by a1batross** [comment]
Сомневаюсь что это возможно исправить.

Дело в том, что движок делает простую проверку -- если количество клипнодов вдруг превысило 32767, то он считает, что используется либо расширение какого-то кваковского компилятора, где смещается диапазон значений чтобы увеличить лимит клипнод, либо расширение Дяди Миши, где клипноды сразу 32-битные.

Даже если исключить поддержку таких карт Quake, то это всё равно повлияет на игры написанные для Ксаша -- мы либо жертвуем ими, либо модификациями под HL1.

**Comment by Qwertyus3D** [comment]
@a1batross Но в последнем приведённом примере клипнод ровно 32767, тем не менее, карта не грузится. Может, глупо, но раз 32767 укладывается в лимит, то и проверка должна быть смещена хотя бы на факт **превышения** лимита, т. е. 32768?

**Comment by Qwertyus3D** [comment]
Опять же, можно сделать квар, отключающий проверку. Вот и совместимость. Дядя Миша, конечно, предпочтёт не давать возможности выбора пользователю, но я считаю, что выбор должен быть, раз есть факторы, диктующие его необходимость. Да и сделать очередной квар не проблема, по-моему.

**Comment by a1batross** [comment]
Дядя Миша подсказал два варианта. Либо считать за расширение, если лумпа больше 32767 * 12, что в целом логично, так как компилятор использует расширение по необходимости, либо ещё проверять наличие второго расширенного заголовка.

По-моему есть смысл применить оба, так как сам по себе расширенный заголовок не говорит о наличии расширения клипнодов.

**Comment by Qwertyus3D** [comment]
Хороший вариант, пусть лучше проверка построже будет, раз возможность есть.

**Comment by a1batross** [comment]
Must be fixed in 13ed2742

**Comment by Qwertyus3D** [comment]
Да, починилось. Теперь просто показывает сообщение о превышении клипнодов, и работает.
