### ISSUE TITLE
fs: FS_SysFileExists with caseinsensitive = true is not working as expected

### ISSUE THREAD

**Issue by kungfulon** [FWGS/xash3d-fwgs#755]
On non-win32 platforms, `FS_SysFileExists` calls `FS_FixFileCase` in order to emulate win32 file name handling. However current logic only handles the `file name`, not the `full path`.

Test conducted on Ubuntu 20.04, with Xash3D built using i386 release configuration.

When I rename `valve/resource` folder to `valve/Resource`, the background and gameui localization file failed to load:

![image](https://user-images.githubusercontent.com/1312612/152555524-2e4c3640-46f8-4b79-8f78-13dd40eb8291.png)

**Comment by nekonomicon** [comment]
May be closed?
