### ISSUE TITLE
[MOD: Team Fortress Classic] Жёлтые точки кружат вокруг игрока когда взял флаг

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#759]
Да, я знаю что я писал про этот баг. Но тогда это было видно от первого лица, сейчас же когда берёшь флаг, то жёлтые точки не видны. Когда **кто-то** берёт флаг то вокруг него появляются жёлтые точки.

**Comment by a1batross** [comment]
Исправлено в https://github.com/FWGS/xash3d-fwgs/commit/380422a6dca4987a27d14e77e63c885920b25b3c
