### ISSUE TITLE
Problem in sentences.txt parsing

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d-fwgs#760]
If there're more than one space between sentence identifier and corresponding sound, the game won't play the sound.

How to reproduce:
1. Open valve/sound/sentences.txt and change `BA_DESK barney/c1a0_ba_desk` so it has two space characters in between.
2. Run c1a0 map. Barney at the desk is supposed to say the sentence, but he does not.

Message in console should appear (if game's running with `developer 2`):
```
Warning: FS_LoadSound: couldn't load " barney/c1a0_ba_desk"
```

The problem exists in the old engine too. Goldsource does not have such issue.

**Comment by a1batross** [comment]
Should've been fixed in 3f7773f
