### ISSUE TITLE
[Android] Not working swipe scrolling in menu

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/xash3d-fwgs#770]
Меню текущей v0.20 не отзывается на свайпы, прокрутка списков свайпом (настройка клавиш, тач-кнопок и т. п.) не функционирует (либо совсем, либо прокручивается, но только вверх, вне зависимости от направления свайпа). Также не работает прокрутка перетаскиванием боковой полосы прокрутки.

**Comment by Vladislav4KZ** [comment]
Я уже про это писал
https://github.com/FWGS/xash3d-fwgs/issues/642

**Comment by a1batross** [comment]
Fixed.
