### ISSUE TITLE
Скачивание pak/zip/pk3 паков, вместо отдельных файлов

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#771]
Допустим, на сервере есть файл karta.pak с таким содержимым:
- `models/house/b1.mdl`
- `models/furniture/table.mdl`
- `maps/mansion.bsp`
И на сервере стоит эта самая карта mansion. Когда игрок подключится, каждый перечисленный выше файл у него будет скачиваться по отдельности, хотя в данном случае нужно скачать только файл `karta.pak`. Нужно в движке реализовать такую логику.

**Comment by a1batross** [comment]
Она уже должна быть -- в старом движке можно было напрямую указать её в reslist.txt. Не помню добавили ли в новый движок.

**Comment by SNMetamorph** [comment]
> ну и вообще скачивание паков из соображений безопасности заблокировано

Тогда имеет смысл не полностью блочить загрузку паков, а как-то избирательно монтировать файлы из него. Потому что без паков дико неудобно на сервере хранить и обновлять карты, в директориях со звуками/моделями и прочим контентом разводится дикий срач.

**Comment by nekonomicon** [comment]
Я вижу только один адекватный вариант:
Сервер загружает ресурсы из пака, а отдает сначала список содержимого пака с хэш-суммами, а затем отдает отдельные файлы из пака.

Отправка архивов с сервера плоха сама по себе по ряду причин.

> в директориях со звуками/моделями и прочим контентом разводится дикий срач

Мне кажется это все легко решается самописными скриптами

**Comment by mittorn** [comment]
У меня на этот счёт была идея в принципе, но наверно с учётом медленной 
ФС на некоторых ОС может быть проблемой.

Это сделать возможность группировки скачанных файлов. Например файлы для 
карты map.bsp будут качаться в отдельный подкаталог, если указано в в 
каком-то параметре, общие файлы сервера domain.net будут качаться в 
подкаталог, указанный сервером и это всё добавляться в fs_path (т.е 
сервере передаёт список каталогов с приоритетами, а каждый файл в 
реслисте хранит тоже каталог-группу, к которой он отностится). Так же 
это позволит перекачать файл с другой контрольной суммой поверх.
Идея эта была когда держал coop сервер, мод забивал пользовательский 
каталог файлами, мало того, в разных модах мог быть подменён разный 
файл. Такой механизм иерархии позволял бы как навести красивую 
структуру, так и избежать конфликтов. Так же можно было бы предусмотреть 
механизм удаления старых файлов если сделать какую-то проверку 
принадлежности каталога к серверу (правда. как делать такое без 
какого-нибудь TLS не знаю)

В общем, не знаю, реально ли это нужно, но чего-то такого не хватало, 
когда coop держал. Возможно тут стоит задуматься вместо идеи качать паки.

**Comment by SNMetamorph** [comment]
Я закрыл ишью вот почему. На сервере как раз таки можно хранить файлы в паках, с этим проблем быть никаких не должно. Клиенту скачаются файлы в обычном виде, если будут конфликты какие-то, то файл просто перекачается, в этом никакой проблемы не вижу особой

**Comment by a1batross** [comment]
Грубо говоря любой пак для того чтобы его распространять в интернете. Скачал мод с условной геймбананы, закинул в папку с игрой, оно само подмонтировалось в VFS, наигрался, удалил и никаких следов присутствия.

По сети может быть неудобно разве что с HTTP сервером, так как HTTP сервер не в курсе о движковой VFS. Зато файл можно будет передать через фрагменты -- ксаш его прочитает, сожмёт и будет сжатую версию отдавать. 

Но для этого по-хорошему нужно решить несколько задач:
1) Сделать подсказку клиенту, чтобы он не делал запросы с HTTP сервера ИЛИ научить клиент обращаться к фрагментам когда все HTTP серверы отдали 404.
2) По-хорошему, стоит какую-нибудь эвристику для сжатия написать. Чтобы сжимать сжимаемое, а несжимаемое не сжимать. :)

**Comment by a1batross** [comment]
К слову, теперь можно дописывать PK3 и PAK к `.res` файлу карты, и движок сам примонтирует их после скачивания.

Можно и WAD дописывать, но уже необязятально -- сервер сам отправит клиенту список необходимых WAD-файлов. В отличие от голдсорса, хехе.

**Comment by SNMetamorph** [comment]
> По сети, в мультиплеере, может быть неудобно разве что с HTTP сервером, так как HTTP сервер не в курсе о движковой VFS. Зато файл можно будет передать через фрагменты -- ксаш его прочитает, сожмёт и будет сжатую версию отдавать.

Точно. Теперь вспомнил, зачем я эту issue открывал.
