### ISSUE TITLE
Sound problems 

### ISSUE THREAD

**Issue by XGhostRX** [FWGS/xash3d-fwgs#775]
I am seeing sound failures for some devices, for example mine which is a huawei p30 lite MAR-LX3Am and I already tried from the old engine

**Comment by a1batross** [comment]
Can you be more specific about your issue?

**Comment by a1batross** [comment]
Also post engine.log with new engine.

We don't work on old engine anymore.

**Comment by a1batross** [comment]
Will ask again, post engine.log.

Also, do you have game files from Steam? Not modded, not pirated.

**Comment by XGhostRX** [comment]
> Will ask again, post engine.log.
> 
> Also, do you have game files from Steam? Not modded, not pirated.

Yes, they are steam

**Comment by lewa-j** [comment]
Do you use bluetooth headphones?

**Comment by Aynekko** [comment]
> The some sounds are cut for example when I select a weapon or press the option to use,

Same thing happens in goldsource. Because those sounds are playing on the same channel (CHAN_ITEM I believe?). So the new sound is overriding the already playing one.

**Comment by XGhostRX** [comment]
> > The some sounds are cut for example when I select a weapon or press the option to use,
> 
> Same thing happens in goldsource. Because those sounds are playing on the same channel (CHAN_ITEM I believe?). So the new sound is overriding the already playing one.

Hmmm, I see
