### ISSUE TITLE
[Android] [GLES1] Частицы при стрельбе в стену отображаются как серые линии а не точки

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#777]
VBO: Отключен
GPU: Mali-T820

![Screenshot_20220224-202030.png](https://user-images.githubusercontent.com/22411953/155541722-590c38c1-2a65-4d32-910c-81347da6258b.png)

**Comment by Vladislav4KZ** [comment]
На GLES2 рендере, появляются только серые точки

**Comment by a1batross** [comment]
Looks like a bug with GL_QUADS on nanogl @mittorn was talking about...

**Comment by a1batross** [comment]
Probably fixed by now?

**Comment by Vladislav4KZ** [comment]
> Probably fixed by now?

No, it's not fixed.

**Comment by a1batross** [comment]
Там ЕМНИП квады.

**Comment by mittorn** [comment]
Tested with recent nanogl on desktop, particles draws correctly

**Comment by Vladislav4KZ** [comment]
Извиняюсь, я спутал эту issue с другой, в которой говорилось что цвет частиц серый, а не чёрный как в GoldSource и на старом движке 0.19.x.

Сейчас баг с "опилками" не воспроизводится и на андроид версии движка с nanogl.
