### ISSUE TITLE
Частицы при стрельбе в стену отображаются серыми точками

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#778]
А в GoldSource они чёрные. Это касается всех платформ, конкретно проверял на Windows и Android

**Comment by a1batross** [comment]
Не вижу принципиальной разницы. Есть пример?

**Comment by Vladislav4KZ** [comment]
> Не вижу принципиальной разницы. Есть пример? 

@a1batross 
**GoldSource**
![crossfire_goldsource.png](https://user-images.githubusercontent.com/22411953/158009527-38d608e2-f32e-41d2-ab8f-8bb91b781952.png)

**Xash3D FWGS**
![crossfire_xash3d.png](https://user-images.githubusercontent.com/22411953/158009543-3d105476-aaf0-4bcc-82f9-1bd54e22273b.png)

**Comment by a1batross** [comment]
Возможно, есть смысл закрыть, так как они теперь чёрные. На вид вроде не такие чёрные, но сравнил в GIMP, оба #1f1f1f 

Частично исправлено в https://github.com/FWGS/xash3d-fwgs/commit/85dfaaa2c2f8894204b9a6fb4e867dd54dfde219, так как texgamma больше (ошибочно) не применяется на палитру, используемую для партиклей.

![c1a0_shot0006](https://github.com/user-attachments/assets/a16c50e1-00e8-4d76-bb1f-e8da86ee3639)
