### ISSUE TITLE
Ксаш не воспроизводит звук когда в sentences.txt указано более одного параметра

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#779]
Например, можно написать в консоли
```
spk !HG_ALERT0
```
И при произнесении фразы, будет ошибка в консоли
```
Warning: FS_LoadSound: couldn't load "hgrunt/freeman!(t20"
```

И это слово "freeman!" не воспроизвелось из-за этой ошибки.

Вот как выглядит строка в sentences.txt содержащая это предложение:
```
HG_ALERT0 hgrunt/(t30) squad!, we!(e80) got!(e80) freeman!(t20 p105), clik(p110)
```

**Comment by Vladislav4KZ** [comment]
То есть, написав в консоли любое слово с двумя и более параметрами в скобках  например:
```
spk hello(p105 e90)
```
То будет ошибка, и слово не воспроизведётся.

**Comment by a1batross** [comment]
Fixed in e07417ae.

**Comment by a1batross** [comment]
@Vladislav4KZ как и в GoldSrc, в spk при передаче полного сентенса, нужно добавлять в кавычки. Так как он не учитывает остальные аргументы, только первый.

А так, да, баг поправил. Спасибо!
