### ISSUE TITLE
Enable linking with shared objects in current directory on Linux build

### ISSUE THREAD

**Issue by sedme0** [FWGS/xash3d-fwgs#780]
Currently, the Linux build requires the user to set the environment variable `LD_LIBRARY_PATH` in order to load the correct libraries. This doesn't need to be the case. By using the `-rpath` command line argument when linking, it's possible to load shared libraries from a specified directory during runtime, and it can even be relative. The documentation is on [this page](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html). If ld is called by gcc or g++, then you have to do `-Wl,-rpath,.` but I think if ld is called directly it's just `-rpath .`. I'd make the change myself, but I don't really know how Waf works.

EDIT: I figured it would take me a while to figure out how to do it with Waf, but it turns out all you have to do is add  `rpath = ['.'],` in `game_launch/wscript`. I won't submit a pull request, since I would have to account for all the build options (for instance, you wouldn't want to set the rpath if you're statically linking everything).

**Comment by a1batross** [comment]
Yeah, I wanted to do this but just forgot. It's not a problem for me to add env var, it mostly always possible in any configuration.

**Comment by a1batross** [comment]
Fixed in 8169c2a4
