### ISSUE TITLE
В некоторых местах поехала лайтмапа на карте crossfire.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#782]
После этого коммита:
https://github.com/FWGS/xash3d-fwgs/commit/24ea8fba4b31b79596786ec099befbafa3c008ce
В некоторых местах поехала лайтмапа на карте crossfire.
![test](https://user-images.githubusercontent.com/96422615/155998606-617d8e92-0d24-410b-8ca0-25020012596e.png)
![test2](https://user-images.githubusercontent.com/96422615/155998609-be094a5e-1930-4769-a2ea-a2f410b38be1.png)
![test3](https://user-images.githubusercontent.com/96422615/155998612-00e43f37-128b-4555-854b-7f5be0c38ee0.png)

**Comment by SNMetamorph** [comment]
Да, действительно есть такое, интересно почему

**Comment by a1batross** [comment]
Теперь слишком точная! xD

**Comment by SNMetamorph** [comment]
Есть одна гипотеза, сейчас буду её проверять, по результатам потом распишу всё

**Comment by SNMetamorph** [comment]
Да, действительно нужно все переменные которые в коммите том, перевести из double в float, а DotProductPrecise оставить как есть, тогда всё идеально работает. 
@a1batross

**Comment by a1batross** [comment]
@SNMetamorph вышли тогда патч.

Кстати не удивлюсь если DotProductPrecise помог бы исправить некоторые баги с физикой при высоких уровнях оптимизации

**Comment by SNMetamorph** [comment]
@a1batross готово
https://github.com/FWGS/xash3d-fwgs/pull/783

**Comment by SNMetamorph** [comment]
Можно закрывать

**Comment by unnamed9** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/edc171be0462e1f3b908a0603fec7dc7b09f94ad.
