### ISSUE TITLE
problem of builiding in cmd window 

### ISSUE THREAD

**Issue by devtunisia12** [FWGS/xash3d-fwgs#786]
fatal error C1083: cannot open include file 'build.h' no suck file or directory

how to fix it

**Comment by AruMoon** [comment]
How do you build?

**Comment by devtunisia12** [comment]
just i follow the steps of tutorial but i can't install the lasted version python because it is not support window 7 only window 10

**Comment by nekonomicon** [comment]
You can use any python version

**Comment by a1batross** [comment]
Post log

**Comment by devtunisia12** [comment]
![erro1](https://user-images.githubusercontent.com/94746514/157297612-8fcc14de-6f1f-4258-8ee9-c409c7a81727.png)
![erro2](https://user-images.githubusercontent.com/94746514/157297680-100a1d0b-5e7a-460c-8f5c-e9495a69ee84.png)

**Comment by mittorn** [comment]
Which compiler version do you use?

**Comment by AruMoon** [comment]
> i use python 3.8

It's not a compiler

**Comment by devtunisia12** [comment]
i use cmd in window 7

**Comment by a1batross** [comment]
If you don't know the basics yet, maybe it's better for you to download prebuilt version? You can get it from releases.

**Comment by devtunisia12** [comment]
ok

**Comment by devtunisia12** [comment]
i fix my problem

**Comment by devtunisia12** [comment]
thanks
