### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by XGhostRX** [FWGS/xash3d-fwgs#787]
The only thing I do not like about this version is that it is not displayed in full screen because if I press the arrow button it makes the game close, apart from that, they do not load the texts with colors in the list of servers
![Screenshot_20220308_141354_su xash engine](https://user-images.githubusercontent.com/90627848/157309886-ac4992e7-37dd-46a6-b274-f0e29118cff7.jpg)

**Comment by Velaron** [comment]
duplicate https://github.com/FWGS/xash3d-fwgs/issues/223
