### ISSUE TITLE
NAT servers do not load correctly

### ISSUE THREAD

**Issue by XGhostRX** [FWGS/xash3d-fwgs#788]
Recently I'm having this problem, I made two screenshots with the old engine and the new one in comparison
![Screenshot_20220308_155118_in celest xash3d hl](https://user-images.githubusercontent.com/90627848/157323433-55d70ad7-699c-4674-bcd8-d7a55c1e9516.jpg)
![Screenshot_20220308_154330_su xash engine](https://user-images.githubusercontent.com/90627848/157323469-5cea37a8-90c8-4364-8fd8-2b31ef028c72.jpg)

**Comment by Velaron** [comment]
duplicate https://github.com/FWGS/xash3d-fwgs/issues/185
