### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#789]
I keep getting this error when I try to launch it.
xash3d-fwgs-amd64.AppImage: 1: Syntax error: "(" unexpected

Wat do?

**Comment by a1batross** [comment]
Works for me.

What distro are you using? Where did you download this AppImage?

**Comment by mittorn** [comment]
Build from source if system does not support format

**Comment by TheAwesome98-Real** [comment]
maybe your system doesn't have the appimage executor (i don't know the proper name) installed on it

**Comment by a1batross** [comment]
You don't need any "executor" lol

**Comment by TheAwesome98-Real** [comment]
maybe they have a really uncommon distribution that hasn't got it installed by default
