### ISSUE TITLE
If you use wine to run Xash on Linux (Ubuntu 20.04.4) no window opens, but sounds do play

### ISSUE THREAD

**Issue by TheAwesome98-Real** [FWGS/xash3d-fwgs#800]
> Why on earth would you use xash3d with wine?!?!!? It compiles fine for x64 linux!!!!!

Because I want to run a windows goldsource game on Linux. (I hate windows.)

> Log?

There isn't any log file (as far as i could tell) and nothing is printed to console other than some from wine (not xash3d).

> What happens?

The sound from the intro.avi plays, then the menu music loop plays. No button rollover sounds play because there isn't a window for them to be in

I think this is something to do with xash3d starting in fullscreen but I don't know for sure. Also, the same thing happened with a flash game but I doubt that's relevant.

**Comment by a1batross** [comment]
Logging to file is enabled with `-log`. I also recommend enabling full verbosity with `-dev 2` parameter.

Finally you will get something like `wine xash3d.exe -dev 2 -log`

**Comment by TheAwesome98-Real** [comment]
This actually made the game work for some reason. Because of the -dev parameter, the intro video doesn't play, but I don't mind that much. Thanks.
