### ISSUE TITLE
[MOD: Half-Life : Echoes]  Отсутствуют модели машин, трупов.

### ISSUE THREAD

**Issue by E83892** [FWGS/xash3d-fwgs#804]
![Screenshot_2022-03-25-11-28-32-315_su xash engine](https://user-images.githubusercontent.com/77808332/160084053-146e06d8-7f9f-45a0-bd14-486ddb161f88.jpg)
![Screenshot_2022-03-25-11-28-52-218_su xash engine](https://user-images.githubusercontent.com/77808332/160084066-3b465fc5-98d5-40bd-b1f0-1ca75c52ae86.jpg)

**Comment by Vladislav4KZ** [comment]
Какая версия ксаша? Если 0.19.2 то она не поддерживается.

Если 0.20.1 то для этой версии нет лаунчера Half-Life Echoes, и поиграть нормально а этот мод ты никак не сможешь
