### ISSUE TITLE
cl_corpsestay in cs 1.6 android not working

### ISSUE THREAD

**Issue by MarcellStar1** [FWGS/xash3d-fwgs#807]
the time the corpse disappears is always under 5 seconds and does not match what is set in the cl_corpsestay console

**Comment by Vladislav4KZ** [comment]
And how does this relate to the engine?

**Comment by Vladislav4KZ** [comment]
And how does this relate to the engine?

**Comment by MarcellStar1** [comment]
> And how does this relate to the engine?

maybe it's this engine that makes the command not work or it was deliberately made to disappear to improve performance

**Comment by Vladislav4KZ** [comment]
> maybe it's this engine that makes the command not work or it was deliberately made to disappear to improve performance
> 

I just checked Counter-Strike 1.5 on Xash3D FWGS 0.20.1 for Windows, and did not notice this bug. The corpse does not disappear after 5 seconds, but remains for a long time.

**Comment by MarcellStar1** [comment]
> 

I used to remember someone telling me to downgrade to another version plus adding some code in the console argument and after that the body didn't disappear anymore but now I've forgotten how
