### ISSUE TITLE
Как правильно поменять шрифт в меню.

### ISSUE THREAD

**Issue by melomansky** [FWGS/xash3d-fwgs#809]
![Screenshot_20220328_191513](https://user-images.githubusercontent.com/94536394/160991458-7ec33299-faa5-4453-85fe-51a8d0efe59e.jpg)

как правильно подогнать текст чтобы не было этой ошибки

**Comment by Vladislav4KZ** [comment]
У тебя есть комп и фотошоп?

Скачай HLSDK и найди и открой Action файл для фотошопа, для создания btns_main.bmp

С телефона ты нормально не сделаешь
