### ISSUE TITLE
Support Nintendo Switch - Firmware 14 and up

### ISSUE THREAD

**Issue by Vendo232** [FWGS/xash3d-fwgs#812]
hello

would it be possible to continue supporting Nintendo Switch Port ( [xash3d-bshift.nro](https://github.com/switchports/xash3d-switch/releases/download/v1.0.1/xash3d-bshift.nro) 

https://github.com/switchports/xash3d-switch/

thank you

**Comment by a1batross** [comment]
Switch port is in the works now

**Comment by fgsfdsfgs** [comment]
While the port is getting merged, [this](https://github.com/fgsfdsfgs/xash3d-fwgs/releases/tag/v0.20-nx2) should work on current firmware versions, unless something changed again in 14.0.0.

**Comment by Vendo232** [comment]
it works great

![image](https://user-images.githubusercontent.com/44098230/161794680-a854fc0e-1590-45ac-a2b9-cae80ed21cdc.png)
