### ISSUE TITLE
Supporting Bot Plugins

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#813]
Hi there team, this is ToxicHolyGrenade.

To be honest, I tried everything to get one of the bot plugins working (RCBot) but as a result, it negatively affects the game, with the likes of not just detecting the linked up rcbot.dll file, but also results in the New Game, Hazard Course, and Load game buttons to be grayed out and inaccessible.

Would it be possible to have the engine support all of the bot plugins like RCBot? Many thanks for reading.

**Comment by a1batross** [comment]
It supports Half-Life? I'm seeing it's only for SvenCoop and Source games.

**Comment by nekonomicon** [comment]
http://rcbot.bots-united.com/

Click `about` button.

> The LATEST version of the bot (new version 1.3 and newer) supports the MODs

> Natural Selection 2 & 3

> Sven Coop 2 & 3

> Battlegrounds

> Bumper Cars 1.5 and older

> Deathmatch Classic

> Rocket Crowbar 1 & 2

> Half-life Deathmatch

**Comment by ToxicHolyGrenade** [comment]
Actually nekonomicon, it does work for Half-Life, but in XASH 3D FWGS' case, it doesn't.

**Comment by a1batross** [comment]
How exactly it doesn't work? Anything in the console? Run engine with `-dev 2` and post engine.log here.

If it still happens, reopen the issue.
