### ISSUE TITLE
Cannot Run Mods if the Folder Names Have Spaces 

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#814]
For some reason, unlike XASH, it cannot run mods unless the spaces are not there. Can this be fixed?

**Comment by a1batross** [comment]
Can you provide an example? Because I'm thinking either path has spaces, either mod directory has spaces.

**Comment by a1batross** [comment]
Both situations should be handled, but we can't even reproduce with this little information.

**Comment by ToxicHolyGrenade** [comment]
I have renamed SvenCoop to Sven Co-op for instance, and once I had tried to change the game, the mod won't load.

**Comment by ToxicHolyGrenade** [comment]
I remember the original XASH doesn't have that problem, but over here on FWGS it does.

**Comment by a1batross** [comment]
I tried to reproduce and had no problem with it.

Can you describe what you're doing in detail?

**Comment by a1batross** [comment]
Don't forget to enclose game directory name into quotes, otherwise it will be passed as separate arguments. 

Xash shouldn't have any special hacks to concatenate arguments when it's users' and their shell job.
