### ISSUE TITLE
Xash3D Ubuntu Server Permission Problem

### ISSUE THREAD

**Issue by GKN0** [FWGS/xash3d-fwgs#820]
I get this error when I try to start the server:

Cannot exec './xash3d': Permission denied

I tried chmod +x xash3d.sh but nothing happens.
Ubuntu Version: 20.04 64Bit

**Comment by AruMoon** [comment]
`chmod +x xash3d`

**Comment by GKN0** [comment]
Not fixed still same.

**Comment by GKN0** [comment]
My problem is solved. Thank you for your help.
