### ISSUE TITLE
xash3d Not Launching

### ISSUE THREAD

**Issue by GKN0** [FWGS/xash3d-fwgs#822]
cstrike         libSDL2-2.0.so.0  libvgui_support.so  valve    xash3d
engine_i486.so  libsteam_api.so   libxashmenu.so      vgui.so  xash3d.sh
root@ubuntu:/opt/server#
root@ubuntu:/opt/server# chmod +x xash3d
root@ubuntu:/opt/server# ./xash3d
-bash: ./xash3d: No such file or directory

I'm making a mistake somewhere, I couldn't fix it.

**Comment by AruMoon** [comment]
> cstrike libSDL2-2.0.so.0 libvgui_support.so valve xash3d engine_i486.so libsteam_api.so libxashmenu.so vgui.so xash3d.sh root@ubuntu:/opt/server# root@ubuntu:/opt/server# chmod +x xash3d root@ubuntu:/opt/server# ./xash3d -bash: ./xash3d: No such file or directory
> 
> I'm making a mistake somewhere, I couldn't fix it.

Did you install 32-bit libraries?
