### ISSUE TITLE
Вечная первая загрузка кастомной карты

### ISSUE THREAD

**Issue by CaptainCyzorg** [FWGS/xash3d-fwgs#829]
OS: Linux x86_64 что на клиенте, что на сервере
Клиент и сервер собраны из последних исходников, 64 битная версия движка
Лог клиента: https://nekobin.com/lareqoximo
Лог сервера: https://nekobin.com/mesomafoxu
![image](https://user-images.githubusercontent.com/103460183/162830557-d0e26b40-a937-4c78-b995-7e2387990339.png)
Ошибка возникает на любом сервере FastDL (проблема не с ним?), файлы на сервере и FastDL идентичны
После перезапуска клиента зайти на сервер можно (так как карты уже скачались)
На чужих серверах с этим же клиентом такой проблемы не возникает, все карты нормально скачиваются

**Comment by mittorn** [comment]
Что-то с счётчиками не так. Окончание скачивания определятся по количеству скачанных файлов. Возможно, код поддержки fastdl был плохо протестирован на новых серверах - ведь весь мультиплеер до сих пор на старом протоколе

**Comment by Vladislav4KZ** [comment]
Тоже сталкивался с этой проблемой. Количество оставшихся файлов в счётчике не меняется, даже когда всё скачалось.

Зайти на сервер можно только с третьего раза (если не перезапускать игру), так как первый раз качаются файлы с вечной загрузкой в конце (всё уже скачалось, а счётчик не исчезает и секунды продолжают идти).

Во второй раз ксаш опять пытается что-то скачать, когда уже всё скачано, зависая на надписи в консоли
```
Verifying and downloading resources
```

И только в третий раз уже можно подключиться к серверу.

**Comment by SNMetamorph** [comment]
Странно. У меня всё нормально качается на последнем билде. Может дело в конфиге?
![изображение](https://user-images.githubusercontent.com/25657591/206716175-7966d321-2bdf-4119-8ad1-1794466d4bae.png)

**Comment by Vladislav4KZ** [comment]
@SNMetamorph эта проблема воспроизводится ТОЛЬКО на серверах запущенных на новом движке. Которые к тому же имеют FastDL для скачивания ресурсов.

Я не замечал что прямая загрузка с серверов была вечной.

**Comment by SNMetamorph** [comment]
Нашел в чем причина зависания
