### ISSUE TITLE
Мерцают лучи в мультиплеере.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#831]

**Comment by a1batross** [comment]
Они кстати могли и после фикса WorldToScreen поломаться, попробуй откатиться на тройку коммитов раньше.

**Comment by unnamed9** [comment]
@a1batross Извините, я нуб в использовании git, как я могу это сделать?

**Comment by a1batross** [comment]
git checkout HEAD~N, где N число коммитов на которое ты хочешь откатиться назад.

git checkout master вернет на ветку master.

**Comment by unnamed9** [comment]
@a1batross Проверил, откатившись до этого коммита:
https://github.com/FWGS/xash3d-fwgs/commit/81c4acab663353ce48f9baad7bdaf74884c32850
Лучи всё-ещё мерцают.

**Comment by SNMetamorph** [comment]
Я так понимаю это на старом сервере? Если так, то возможно что дело в различии реализации дельты в новом и старом движке.

**Comment by unnamed9** [comment]
@SNMetamorph Да, проверял на старом сервере, ибо проверить на новом сервере не представляется возможным.

**Comment by Vladislav4KZ** [comment]
Заметил такой баг в Team Fortress Classic, карта ravelin, сервер "[FWGS] TFC 1.5 +BOTS!", который запущен на новом движке.
![ravelin_0002](https://user-images.githubusercontent.com/22411953/167420593-56628f91-b67a-4b2d-baaa-f0b848eca748.png)

Раньше я такого бага не видел

**Comment by unnamed9** [comment]
@Vladislav4KZ
https://github.com/FWGS/xash3d-fwgs/issues/832

**Comment by Vladislav4KZ** [comment]
> @Vladislav4KZ Хотел сказать то, что тот issue и этот issue, который ты тут доложил одинаковы и что логично было-бы отправить скриншот с информацией в тот самый issue, который я указал.

А зачем собственно создавать два одинаковых issue? Когда мог скинуть видео сюда. Я написал сюда, так как здесь было обсуждение этого бага, чтобы было понятно к чему я скинул скриншот.

**Comment by a1batross** [comment]
Fixed in 76d0608e

(not sure though)
