### ISSUE TITLE
Неправильный рендер лучей в мультиплеере.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#832]
Например, на TDM Vanilla DM есть надпись TDM у входа в бункер, сделанный из лучей, но на данный момент эта надпись выглядит вот так.

https://user-images.githubusercontent.com/96422615/163171371-b99a6e48-8dfc-415c-9ad7-3f1767a3f872.mp4

**Comment by SNMetamorph** [comment]
Да, тоже на этот баг натыкался еще давно

**Comment by a1batross** [comment]
Fixed in 76d0608e
