### ISSUE TITLE
Создание API для реализации кастомного GUI со стороны клиента

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#833]
Всё, что требуется из функционала:
- отображение/скрытие курсора (также опционально изменение стиля)
- ввод символов с клавиатуры в кодировке UTF-8
- чтение/запись буфера обмена

Также стоит вопрос: стоит это делать каким-то отдельным API, или же возможно это реализовать как расширение функционала Mobility API?

**Comment by SNMetamorph** [comment]
@a1batross @mittorn

**Comment by mittorn** [comment]
In fact mobility API is extenstion to client api. Maybe it is named wrongly

**Comment by SNMetamorph** [comment]
#836
