### ISSUE TITLE
[MOD: Counter-Strike] Краш игры с ботами

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#834]
Я писал про эту проблему раньше, была попытка исправить это, issue закрыли, но движок всё равно крашится.

**Любая версия Counter-Strike которая запускается на Xash3D FWGS 0.20.1** + PODBot'оподобные боты: YaPB, E[POD]Bot, и т.д.

Когда начинается раунд (время заморозки истекает, боты начинают двигаться) появляется ошибка:
```
assert failed at D:\a\xash3d-fwgs\xash3d-fwgs\engine\server\sv_game.c:4176
```

**Comment by Vladislav4KZ** [comment]
С YaPB ботами разобрался, сделал фикс механизма обнаружения ксаша в коде самого бота, и они теперь работают исправно.

На старом движке я пробовал запускать даже более старые версии YaPB и они там работали (на новом движке, они конечно же вызывали краш, как и новый YaPB 4.x).
Хотя, может попозже проверю чтобы убедиться, что это действительно так.

**Comment by a1batross** [comment]
Я буквально вчера пытался отлаживать YaPB и не заметил ошибку с ассертом.

**Comment by Vladislav4KZ** [comment]
А вот что с остальными ботами делать? PODBot 2.5 в Counter-Strike 1.5 на старом движке точно работал.

**Comment by a1batross** [comment]
Так и пусть висит открытым. Я чуть позже проверю. Оно небось виндовое. =/

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/4c02c255065e28938af35a2f1930495c090fdfdd
