### ISSUE TITLE
BSPGuy and "Bad Normal for Plane" Error Messages

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#835]
The story with this error is that whilst I am editing some of the Life's End maps for example, in order to crossover content from Half-Life: Absolute Zero, with XASH 3D FWGS occasionally causes plane errors on the map I've edited, which caused the game to automatically disconnect, and when I try to type in the same map with this issue, it crashes the whole game.

![Untitled](https://user-images.githubusercontent.com/83011225/164183222-140663b7-9128-4da4-84f7-ec08c3cbd33a.png)
[New WinRAR ZIP archive.zip](https://github.com/FWGS/xash3d-fwgs/files/8519619/New.WinRAR.ZIP.archive.zip)

**Comment by mittorn** [comment]
Пожалуйста, купите лицензию! WinRAR -не бесплатная программа. По окончании 40-дневного испытательного периода вы должны либо купить лицензию на программу, либо отказаться от дальнейшего использования.

**Comment by ToxicHolyGrenade** [comment]
При всем уважении, какое это имеет отношение к проблеме?

**Comment by a1batross** [comment]
BSPGuy похоже генерирует некорректный BSP.

plane у face превышает максимум numplanes, а такого быть не должно -- как поверхность может ссылаться на plane которого нет?

**Comment by ToxicHolyGrenade** [comment]
That's something that's beyond my intuition, and something that needs to be investigated.

**Comment by ToxicHolyGrenade** [comment]
Это то, что выходит за рамки моей интуиции, и это необходимо исследовать.

**Comment by a1batross** [comment]
Sorry, I thought you know Russian. :)

The bug is somewhere in bspguy but we definitely should not crash on invalid BSPs, so let's keep it open.

**Comment by ToxicHolyGrenade** [comment]
Понимаете, чего я не понимаю, так это того, что если обычный движок XASH3D не может дать сбой из-за плохих нормальных ошибок для плоскостей, то почему это происходит с XASH3D FWGS?

**Comment by mittorn** [comment]
Original xash3d crashes with it too, maybe you are using outdated version which has old bsp loader?

**Comment by ToxicHolyGrenade** [comment]
What? Is the same error message showing up like I've shown above?

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/pull/842
