### ISSUE TITLE
libxash.so: /usr/local/lib/xash3d/libxash.so: undefined symbol: SDL_GL_ResetAttributes

### ISSUE THREAD

**Issue by systemdfan** [FWGS/xash3d-fwgs#837]
I have successfully installed xash3d from [this aur repo](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xash3d-fwgs-git) and completed half life 1. Then I have switched game to hl opposing force, xash restarted and crashed with this error: `Xash Error: Unable to load the libxash.so: /usr/local/lib/xash3d/libxash.so: undefined symbol: SDL_GL_ResetAttributes` I found out [this issue](https://github.com/FWGS/xash3d-fwgs/issues/180), but I have completed hl1 without any problems and this error displays only when I'm switching the game. Version info: v49/0.20 (linux-i386 build 2574). ldd output:
```
[systemdfan@systemd-pc ~]$ ldd /usr/local/lib/xash3d/libxash.so
        linux-gate.so.1 (0xf7edf000)
        libm.so.6 => /usr/lib32/libm.so.6 (0xf6f00000)
        libSDL2-2.0.so.0 => /usr/lib32/libSDL2-2.0.so.0 (0xf6d46000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf6d28000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xf6af8000)
        /usr/lib/ld-linux.so.2 (0xf7ee1000)
```

**Comment by systemdfan** [comment]
> How do you switch to opposing force?
I switch to opposing force from Xash switching menu. 

>you only need opfor folder from Steam version of the game.
I don't know if this is steam version. I think it is steam-rip because it have steam-runtime folder, but I downloaded it from rutracker.

**Comment by a1batross** [comment]
@systemdfan 
at first, we don't support pirated builds.

at second, remove steam-runtime. We don't build against it and there is no reason to do so, because SDL 2.0 ABI is considered as stable, and therefore forward compatible.

**Comment by systemdfan** [comment]
@[a1batross](https://github.com/a1batross) 

>at first, we don't support pirated builds.
But I can't buy it nowadays because of sanctions. 

>at second, remove steam-runtime.
I haven't copied this folder to .xash3d directory.

**Comment by barfin** [comment]
I have a legitimate copy of this game and it gives me the same error
![image](https://user-images.githubusercontent.com/37030489/182040910-633ae9cf-41aa-4a84-86b8-1651d9a96903.png)

**Comment by a1batross** [comment]
@barfin show the output of 
`ldd $(which xash3d)`
and
`ldd /usr/local/lib/xash3d/libxash.so`

**Comment by barfin** [comment]
> @barfin show the output of `ldd $(which xash3d)` and `ldd /usr/local/lib/xash3d/libxash.so`

```
➜  ~  ldd $(which xash3d)
        not a dynamic executable

➜  ~  ldd /usr/local/lib/xash3d/libxash.so
        linux-gate.so.1 (0xf7ed0000)
        libm.so.6 => /usr/lib32/libm.so.6 (0xf7dcc000)
        libSDL2-2.0.so.0 => /usr/lib32/libSDL2-2.0.so.0 (0xf6c3f000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf7da7000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xf6a00000)
        /usr/lib/ld-linux.so.2 (0xf7ed3000)
```

**Comment by barfin** [comment]
btw I can play Half-Life just fine, this crash and error only happens when i try to switch to any other game

**Comment by a1batross** [comment]
Can you tell which version of 32-bit SDL2 you have installed?

**Comment by barfin** [comment]
these are all sdl packages that i have installed on my pc 

```
➜  ~ pacman -Q | grep -i sdl2
lib32-sdl2 2.0.22-1
lib32-sdl2_image 2.6.0-1
lib32-sdl2_mixer 2.6.1-1
lib32-sdl2_ttf 2.20.0-1
sdl2 2.0.22-2
sdl2_gfx 1:1.0.4-2
sdl2_image 2.6.0-2
sdl2_mixer 2.6.1-1
sdl2_net 1:2.0.1-3
sdl2_ttf 2.20.0-1

```

**Comment by a1batross** [comment]
I downloaded the lib32-sdl2 package myself, tried it and wasn't able to reproduce this bug.

**Comment by barfin** [comment]
> I downloaded the lib32-sdl2 package myself, tried it and wasn't able to reproduce this bug.
> 
> 

Are you using nvidia? And Could it be a bug in nvidia's opengl driver?
And Did you compile it using AUR script?

**Comment by a1batross** [comment]
@barfin "btw I don't use Arch" :)

I'm not able to run the PKGBUILD, but it doesn't look suspicious.

I'm on NVIDIA, but that's possibly unrelated. `SDL_GL_ResetAttributes` is a function inside `SDL`, a library we use to minify the differences between platforms. It exists since SDL 2.0.2, and I checked that Arch Linux package of SDL2 has it. It runs perfectly fine on my side, overriding the system library.

**Comment by mittorn** [comment]
It seems, you arenusing SDL2 bundled with goldsource. It is very outdated.

**Comment by barfin** [comment]
the problem was that i copied way too many files
I copied the game data only and now i can play opposing force just fine

**Comment by a1batross** [comment]
remember, it's just one folder

**Comment by Architector4** [comment]
Just had the same issue. I know this issue is closed, but I should mention how I fixed it.

So I'm on Arch, and I naively copied the entirety of the Half-Life folder's contents as Steam distributes it into ~/.xash3d, including `valve` and everything else. It worked with normal Half-Life, but with a mod it gave this error.

What helped is, quite literally, removing all .so files in the root of the folder, i.e. `rm ~/.xash3d/*so`. Suddenly everything works.

Valve really just threw a bunch of .so files in there until it worked lmao

**Comment by a1batross** [comment]
@Architector4 I don't know what to do to prevent people from doing this. 

It literally says: copy one folder. Don't slam everything else: GoldSrc have absolutely different set of DLLs.

Some of them we reimplement from scratch, and they may be very specific to Xash, like `filesystem_stdio` and soon to be `vgui`.

**Comment by Architector4** [comment]
Not complaining, totally my fault; just mentioning a way to fix this in case someone else makes this mistake too and eventually arrives here, like i did lol
