### ISSUE TITLE
Have XASH FWGS Support Animated Titles

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [FWGS/xash3d-fwgs#839]
![HLTitle](https://user-images.githubusercontent.com/83011225/166157233-5c21781c-1dda-45c2-afc3-218c5b60c4f0.png)

Как и оригинальный XASH3D Engine, может ли XASH3D FWGS поддерживать анимированные заголовки?

**Comment by nekonomicon** [comment]
Unfortunately, animated header in avi format and required closedsource cinepak codek.
Windows has simple api `Video for windows` which part of OS, but unix-like OSes has only 3rd-party bloated ffmpeg and gstreamer libraries.
And probably avi support was broken in steam version of Half-Life.
So avi support in Xash3D FWGS under question:
https://github.com/FWGS/xash3d-fwgs/issues/817

**Comment by JDragan** [comment]
Can it be converted to GIF and then loaded as overlay? This way you dont need complicated codecs.

**Comment by nekonomicon** [comment]
It can be converted to .spr.
gif not supported too.

**Comment by a1batross** [comment]
SPR have size limits :)

**Comment by mmillar-bolis** [comment]
What about supporting something like `logo.bmp`, where the logo would be the same dimensions as the `.avi` and placed in the same position within the menu?

This way, modders could take their old `logo.avi` and dump it to a bitmap with:

```
ffmpeg.exe -i .\logo.avi '%04d.bmp'
```

while new mods would only need to include a premade `logo.bmp`. If the engine ever did gain support for `.avi`s, they could simply override the `.bmp` when being sourced.

If one truly insists on the original menu logo, an alternative right now is dumping the `.avi` to a `.bmp` as above, and pasting it into `splash.bmp`, but support for a `logo.bmp` might be a decent compromise.

**Comment by OpenRift412** [comment]
Has any progress on this been made?

**Comment by a1batross** [comment]
Closing in favor of https://github.com/FWGS/xash3d-fwgs/issues/817
