### ISSUE TITLE
Проблемы с мультитачем в xash3d & cs16client 

### ISSUE THREAD

**Issue by FSOCllDRUG** [FWGS/xash3d-fwgs#84]
Здравствуйте, возможно кто-то сталкивался с подобным или же алмины знают решение данной проблемы.
Поставил кеш, который использовался ранее без нареканий, скачал из маркета xash3d & cs16client, во время первой же игры заметил, что игра не воспринимает более 2 нажатий, при попытке превысить "лимит" нажатия полностью сбрасываются.
Для полного понимания проблемы просьба просмотреть прикреплённое видео(извиняюсь за качество, но суть видна).
vk.com/video209996335_456239331
Заранее спасибо!

Аппарат Redmi Note 3 Pro
Havoc 9.0

**Comment by Aimless-Wanderer** [comment]
Сначала проверь в другом софте работоспособность мультитача. У меня такие проблемы были связаны с девайсом/прошивкой. Иногда такое было из-за фичи со скриншотом тремя пальцами, как только вырубал её, все было норм.

**Comment by FSOCllDRUG** [comment]
Спасибо, убрал жест для скриншота, всё стало на место.
Хорошего дня.
