### ISSUE TITLE
Immersive Mode doesn't seem to be working as the Controls Bar still shows

### ISSUE THREAD

**Issue by Fancy2209** [FWGS/xash3d-fwgs#840]
This is on Android 10 by the way 

Gestures Navigation
![aKe2vci.jpg](https://imgur.com/aKe2vci.jpg)
3 Button Navigation
![A5nCtME.jpg](https://imgur.com/A5nCtME.jpg)

**Comment by Velaron** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/223
duplicate again

**Comment by Fancy2209** [comment]
I'm really sorry I didn't see it when searching

**Comment by Velaron** [comment]
np, just close this one
i simply typed immersive into the search bar and it worked
