### ISSUE TITLE
[Android] [GLES2] [PowerVR] Некорректно отображается текстура кнопки

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#843]
Телефон Nokia 2.2
Android 11 R
CPU: MediaTek Helio A22
GPU: PowerVR GE8320

Вот как выглядит кнопка включения лифта в начале главы "Аномальные материалы" на GLES2 рендере:
![Screenshot_20220505-220607](https://user-images.githubusercontent.com/22411953/166967579-55279d12-670e-4770-9838-573d5769c203.png)
![Screenshot_20220505-220607~2](https://user-images.githubusercontent.com/22411953/166967622-0297452c-f0fe-434d-8e63-7a7e48767e40.png)

На GLES1 рендере кнопка выглядит нормально:
![Screenshot_20220505-220710](https://user-images.githubusercontent.com/22411953/166967783-a357accb-5ad4-4132-9101-4c826f548c47.png)

На скриншоте с GLES1 видно, что текстура растянута на всю кнопку, в то время как на скриншоте сделанном во время использования GLES2 рендера, текстура имеет свой оригинальный размер, а на незаполненных местах отрисовывается ещё одна такая же текстура.

На предыдущем телефоне Meizu C9 Pro (GPU: Mali-T820) не видел такого бага даже с GLES2 рендером. Баг может был и на нём, но проверить не могу, телефон сдох.

**Comment by mittorn** [comment]
ДМ сломал npot текстуры же. там вроде опция gl_round_down была для включения ресэмплинга, но не уверен, что она нормально работает:
https://github.com/FWGS/xash3d-fwgs/blob/master/ref_gl/gl_image.c#L577

**Comment by a1batross** [comment]
ref_gles2 is deprecated now.

Users better switch to ref_gles3compat or ref_gl4es.
