### ISSUE TITLE
Windows ARM64/ARM32 build

### ISSUE THREAD

**Issue by stevefan1999-personal** [FWGS/xash3d-fwgs#845]
We could start from the [ARM64EC](https://docs.microsoft.com/en-us/windows/uwp/porting/arm64ec) and progressively change it to native ARM.

**Comment by mittorn** [comment]
I think, we do not need some arm64ec for it to work. Xash3d works perfectly on aarch32/aarch64 in non-windows, but we do not have devices now to test it.
It should work as is if you add windows arm support to build system

**Comment by MoeMod** [comment]
I have tested with old engine on surface pro x. The OpenGL performance is terrible on native arm64(at least on SQ1 chip), so it requires additional works.
Three solutions:
1. just use x86 build. The emulated x86 opengl is better than native arm64 opengl.
2. use a dx to opengl translator like QindieGL and use arm64 dx as backend.
3. make a native dx ref renderer

**Comment by stevefan1999-personal** [comment]
> I think, we do not need some arm64ec for it to work. Xash3d works perfectly on aarch32/aarch64 in non-windows, but we do not have devices now to test it. It should work as is if you add windows arm support to build system

Agreed I used to think the problem is there is no VGUI support in ARM64, unless you mean the reverse engineered one. But then I think using ARM64EC wouldn't help either since you still can't use VGUI in x64

**Comment by a1batross** [comment]
Having ARM64 support for Windows isn't a big issue. If you have a device, you can try compiling a port for it, ask questions and send patches, but in the end, you'll have to maintain a port yourself.
