### ISSUE TITLE
[PC] [Windows] The cursor keeps appearing on the screen while playing.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#855]
The cursor stays on center of the screen while playing in the fullscreen and windowed modes. Tried several compability modes, changed mouse options, still no result. This is keeps happening on some builds, and when the issue occurs I just revert few steps back to older build. The build from late april was actually fine.

**Comment by Vladislav4KZ** [comment]
Fixed in commit: https://github.com/FWGS/xash3d-fwgs/commit/fbdfed84bec30ce5cef28eff6fa16f9aac2774b9
This issue can be closed.
