### ISSUE TITLE
[PC] [Windows] Weird texture bug with OBS.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#856]
If you playing long enough with screen capturing, some texture may become completely black or completely bright with some weird shimmering on them. Also the screen capture will froze and you have to restart the game to get it back to normal state. Unfortunately, I forgot to take a screenshot, so I'll post it here when it occurs again. This also happened on the other ancient build of Xash, not fwgs one.
Also I haven't tested the newly builds with OBS because of the mouse pointer problem I described before.

**Comment by Vladislav4KZ** [comment]
Try to capture screen with the "use an interceptor with protection against cheats" option disabled

**Comment by CortexReaver** [comment]
@Vladislav4KZ Already tried it.

**Comment by a1batross** [comment]
Must be fixed since we migrated to glGenTexture usage.
