### ISSUE TITLE
[PC] [Windows] Mods are crashing in attempt to activate it through "custom game" with this error.

### ISSUE THREAD

**Issue by CortexReaver** [FWGS/xash3d-fwgs#857]
Most of them does and some doesn't.
![29-05-2022 144001](https://user-images.githubusercontent.com/34350690/170866235-7fd9965d-d82b-4178-a86e-dd1a5ed70cff.png)

**Comment by nekonomicon** [comment]
Which mods?

**Comment by CortexReaver** [comment]
Bridge the gap, Destiny, Smart decoy, Hardman, Hour-Glass... Usually most of he mods from www.runthinkshootlive.com in category Half-life 1. Happened only on latest builds of Xash, after I switched back to april builds the mods are running fine... except this bug with shimmering textures that I mentioned before.

**Comment by Vladislav4KZ** [comment]
I have a similar problem on Windows 10, but this problem is in ALL mods. https://github.com/FWGS/xash3d-fwgs/issues/738

Xash3D fails to load OpenGL renderer and it switches to Software and crashes

**Comment by CortexReaver** [comment]
Mods that are working (newest build, 10 hours ago): Solo Operations, scientist slaughterhouse, T2DEF, Destiny

**Comment by Vladislav4KZ** [comment]
@CortexReaver Your mods don't crash when they launch from a shortcut?

**Comment by CortexReaver** [comment]
@Vladislav4KZ [Vladislav4KZ](https://github.com/Vladislav4KZ) Hmm... Yes, they do work through the shortcuts... But it is painful to create shortcuts to all 140 mods that I have by hand :) Also that bug with pointer on screen, so I better stay with an April build.

**Comment by CortexReaver** [comment]
After I changed cl and hl dll's to the newest, error is changed to something about being unable to initialize gl render:
![9-05-2022 181256](https://user-images.githubusercontent.com/34350690/170877032-67762120-1a66-41f9-8e4a-d98a9e511e47.png)

**Comment by Vladislav4KZ** [comment]
> After I changed cl and hl dll's to the newest, error is changed to something about being unable to initialize gl render: ![9-05-2022 181256](https://user-images.githubusercontent.com/34350690/170877032-67762120-1a66-41f9-8e4a-d98a9e511e47.png)

That's what i'm wrote about https://github.com/FWGS/xash3d-fwgs/issues/738

**Comment by Vladislav4KZ** [comment]
So, now you cannot launch any mod from the "Custom game" menu.

**Comment by Vladislav4KZ** [comment]
> Should've been fixed in latest build

No, it's still not fixed

**Comment by Vladislav4KZ** [comment]
Fixed in commit: https://github.com/FWGS/xash3d-fwgs/commit/f467d0c807c6756c73c90a179556cf7dce0ac244

**Comment by Vladislav4KZ** [comment]
It's fixed on latest build. Why is it still in issues?

**Comment by a1batross** [comment]
Right, closing now. Thanks!
