### ISSUE TITLE
Не исчезает курсор во время игры в старых версиях Half-Life/модах или когда квар m_rawinput настроен на 0

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#858]
Скриншот не передаёт этот баг.

Когда играешь, в центре экрана находится курсор. И при движении мышкой, он движется вслед за камерой игрока и снова возвращается в центр.

**Comment by CortexReaver** [comment]
This occurs in original game too. 
Duplicate of #855

**Comment by Vladislav4KZ** [comment]
> This occurs in original game too. Duplicate of #855

@CortexReaver No, I don't have this bug in the original Half-Life. And in other mods too.

**Comment by Vladislav4KZ** [comment]
Maybe you are using an older build of Half-Life?

**Comment by Vladislav4KZ** [comment]
By the way, yes, there is no such bug in the April build of Xash3D FWGS

**Comment by CortexReaver** [comment]
> Maybe you are using an older build of Half-Life?
You mean Xash? Isn't Half-life itself is just a bunch of media files and some game logic scripts, and GUI is a part of the engine?

**Comment by Vladislav4KZ** [comment]
> > Maybe you are using an older build of Half-Life?
> 
> You mean Xash? Isn't Half-life itself is just a bunch of media files and some game logic scripts, and GUI is a part of the engine?

I mean Half-Life, which may have old client.dll and hl.dll

**Comment by Vladislav4KZ** [comment]
> There is some dll's in valve folder, but they can be storing just pictures.

What the hell are you talking about?

**Comment by CortexReaver** [comment]
Sorry, I have no idea how this engine works. What hl build are you using?

**Comment by Vladislav4KZ** [comment]
> Sorry, I have no idea how this engine works. What hl build are you using?

Latest build from Steam
```
Protocol version 48
Exe version 1.1.2.2 (valve)
Exe build: 19:53:27 Aug  3 2020 (8684)
```

**Comment by Vladislav4KZ** [comment]
> The one I using is from some old disk image from 2009 may be. Never used the Steam.

Therefore, the problem is this. In mods, this problem manifests itself which are based on the old HLSDK

**Comment by CortexReaver** [comment]
I've renewed these dlls and now pointer is gone :) I reckoning doing something like this actually, changing these files... Actually, got a backup with NEWER dlls but have to replace them for older versions for some reason. Maybe because I was unable to run older builds of Xash, hmm.

**Comment by mmillar-bolis** [comment]
I am also experiencing this bug with clients in two other mods: 

1. The Decay port by Vyacheslav Dzhura and Denys Zhatov.

2. The Vadavaka Ricochet Community client patch

I do not have this problem with clients built on xash3d-hlsdk. I do not have this problem with Numanoid's decrypted CS 1.5 client, the official Deathmatch Classic, or the Uplink demo.

This problem occurs in the current Xash build `efdf9e3` (2022-05-29).

The previous build I used was `654bac8` (2022-03-19) and this problem was not present.

**Comment by Vladislav4KZ** [comment]
This bug occurs on all mods except based on hlsdk-xash3d and official Valve games (which are the latest version from Steam).

Even older versions of Valve games are affected by this bug.

**Comment by Vladislav4KZ** [comment]
Когда выключаешь Raw mouse input ``m_rawinput 0`` то и последней версии стимовской халфы курсор тоже появляется и не исчезает

When I disabled the Raw mouse input ``m_rawinput 0`` then the cursor also appears and does not disappear in the latest Steam version of Half-Life

**Comment by nekonomicon** [comment]
All an old non-SDL clients are affected because they didn't have raw input support.

**Comment by Vladislav4KZ** [comment]
На библиотеках, скомпилированных с репозитория hlsdk-xash3d такого бага нет даже при ``m_rawinput 0``

**Comment by nekonomicon** [comment]
Да это старый баг.
Скорее всего связан и с SDK, и с движком.
В HLSDK 2.3 и старее нет проверок с m_rawinput, а многие моды были сделаны на HLSDK 2.0-2.1, и его вероятно не было в WON, поэтому там включение/отключение это квара практически никакого эффекта не даст.
У нас в hlsdk-xash3d есть подобные исправления:
https://github.com/ValveSoftware/halflife/pull/1900

**Comment by mmillar-bolis** [comment]
@nekonomicon Thank you very much for the information! Do you know what changed in Xash3d engine after April that makes this bug now appear in certain mods?

Also, and I apologize if this is off topic, but would hldsk-xash3d-decay-pc need to be updated to avoid this bug (perhaps with the newer cl_dll/input_mouse.cpp, etc.)? I have never tried to build the code as it is and I have only been using the old libraries from 2008.

**Comment by nekonomicon** [comment]
> hldsk-xash3d-decay-pc

I didn't recommend to use this branch for a while.
It's unplayable yet.

**Comment by SNMetamorph** [comment]
Should be fixed in https://github.com/FWGS/xash3d-fwgs/commit/fbdfed84bec30ce5cef28eff6fa16f9aac2774b9

**Comment by mmillar-bolis** [comment]
I can confirm that build `fbdfed8` correctly hides the mouse cursor during gameplay with the following mods:

1. The Decay port by Vyacheslav Dzhura and Denys Zhatov.

2. The Vadavaka Ricochet Community client patch

Thank you so much!

**Comment by Vladislav4KZ** [comment]
Исправлено в последнем билде движка.

**Comment by a1batross** [comment]
i.e. that's not linked to SDL2

пн, 30 мая 2022 г., 11:01 Владислав Сухов ***@***.***>:
