### ISSUE TITLE
[MOD: Blue Shift] Невозможно загрузить сохранения/карты/не работает смена карт

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#859]
![Снимок экрана (12)](https://user-images.githubusercontent.com/22411953/170932276-ff0a9c54-4541-4bb8-8712-076ef0a1730e.png)

Ни через консоль, ни через меню, невозможно загрузить сохранение игры.

При загрузке сохранения, появляются такие ошибки в консоли.
```
[2022:05:30|12:39:10] >load save001
[2022:05:30|12:39:10] ^1Error:^7 Mod_LoadPlanes: Lump size 44559 was not a multiple of 20 bytes
[2022:05:30|12:39:10] Mod_LoadWorld: 1 error(s), 0 warning(s)
[2022:05:30|12:39:10] ^1Error:^7 map ba_hazard1 is invalid or not supported
[2022:05:30|12:39:10] ^1Error:^7 Couldn't load save/save001.sav
```

**Comment by Vladislav4KZ** [comment]
Используются игровые библиотеки собранные с репозитория hlsdk-xash3d (ветка bshift): https://github.com/FWGS/hlsdk-xash3d/tree/bshift

**Comment by mmillar-bolis** [comment]
I am also experiencing this bug in Blue Shift. There may be a problem with the [recent changes](https://github.com/FWGS/xash3d-fwgs/commit/771c359ed0c884ebb27c7a3f31d2f0d9e5d25f67) to Blue Shift map detection.

Just as @Vladislav4KZ stated, loading a map through the `map` command or through a game save does not work, but gives a lump size error. This error also happens when reaching the very first map change during gameplay.

When using the `maps *` command, it appears that each map after a chapter change also displays an error. 

This problem occurs in the current Xash3D-FWGS Win32 build efdf9e3 (2022-05-29).

The previous build I used was Xash3D-FWGS Win32 build 654bac8 (2022-03-19) and this problem was not present.

| Example Screenshot |
|:---:|
| ![ba_hazard1_shot0000](https://user-images.githubusercontent.com/62162171/170934325-bd23ab5e-0b82-4fb2-8f5b-1931dab97334.png) |

**Comment by Vladislav4KZ** [comment]
> When using the `maps *` command, it appears that each map after a chapter change also displays an error.
> 
> Example Screenshot
> ![ba_hazard1_shot0000](https://user-images.githubusercontent.com/62162171/170934325-bd23ab5e-0b82-4fb2-8f5b-1931dab97334.png)

When I use the `maps *` command, all maps give an error instead of a chapter name

**Comment by Vladislav4KZ** [comment]
I can only launch the map through the menu. When I run through the console, an error appears.

**Comment by Vladislav4KZ** [comment]
![Снимок экрана (14)](https://user-images.githubusercontent.com/22411953/170939343-825d89c6-4a7f-4fa3-ba08-ff9bfa213c48.png)
![Снимок экрана (15)](https://user-images.githubusercontent.com/22411953/170939378-6cac08d3-9be3-44c8-9742-7ef7ffe4a31b.png)

**Comment by Vladislav4KZ** [comment]
Changelevel doesn't work either

**Comment by a1batross** [comment]
Is it that unlocked nonsense mod? 

Original blue shift worked for me on Linux.

**Comment by Vladislav4KZ** [comment]
> Is it that unlocked nonsense mod?
> 
> Original blue shift worked for me on Linux.

No, original Blue Shift from Steam

**Comment by Vladislav4KZ** [comment]
Some people wrote about this bug in the discord, which is the same on android

**Comment by mmillar-bolis** [comment]
> Is it that unlocked nonsense mod?
> 
> Original blue shift worked for me on Linux.

I am using the WON retail resources with the Blue Shift WON 1.0.0.1 patch. I also have the Steam maps from the latest build `8684` (2020-08-03). I did a binary comparison and determined that both sets of maps are identical. I tested both sets of maps anyway, and they give the same lump error.

I have attached a SHA-1 dump of all the default Blue Shift maps: [bshift-map-hashes.txt](https://github.com/FWGS/xash3d-fwgs/files/8799967/bshift-map-hashes.txt)


Blue Shift: Unlocked used [bspfix](https://valvedev.info/tools/bspfix/) (distributed with the mod as `bshift_bsp_convert.exe`) to convert bshift's map headers to Half-Life's original bsp format.

I did go ahead and test Blue Shift: Unlocked's maps and they do function without lump errors under Blue Shift in Xash3D-FWGS Win32 build `efdf9e3` (2022-05-29):

| Example Screenshot |
|:---:|
| ![bshift_unlocked_maps_shot0000](https://user-images.githubusercontent.com/62162171/171038116-747754eb-3ed3-48c0-a3f7-c05bbda0d1f3.png) |

**Comment by cesarpuig** [comment]
I have the same problem on debian 10 arm32.

**Comment by nekonomicon** [comment]
Changelevel didn't work for me:
```
[02:18:50] Firing: (ba_levelchange1)
[02:18:50] Found: trigger_changelevel, firing (ba_levelchange1)
[02:18:50] CHANGE LEVEL: ba_tram2 tram1_tram2
[02:18:50] Error: Mod_LoadPlanes: Lump size 37717 was not a multiple of 20 bytes
[02:18:50] Mod_LoadWorld: 1 error(s), 0 warning(s)
[02:18:50] Error: changelevel: ba_tram2 is invalid or not supported
```

**Comment by a1batross** [comment]
Probably fixed now?..

**Comment by Vladislav4KZ** [comment]
> Probably fixed now?..

Нет

**Comment by Vladislav4KZ** [comment]
Последний билд в релизах не содержит коммит с исправлением этого бага

**Comment by mmillar-bolis** [comment]
I can confirm that the continuous build of d047dfc does not yet have the fix applied, but I will attempt to build from source this evening and see.

**Comment by Vladislav4KZ** [comment]
Исправлено
