### ISSUE TITLE
[Windows] Отсутствует курсор при включенном touch_emulate 1

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#860]
Когда включаешь тач кнопки, эмуляцию тача и игнор мыши ``touch_emulate 1``, ``touch_enable 1``, ``m_ignore 1``, то курсор не виден, хотя тач кнопки реагируют на нажатия невидимого курсора.

Также, теперь стало не возможным перемещать и растягивать тач кнопки с эмуляцией тача.

Последний билд где эмуляция тача работала нормально это **от 18 декабря 2021 года**

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/2d2523df4a5e748e40842a1e2763bdf8a4c96f6e

**Comment by a1batross** [comment]
Здесь есть ещё проблемы, так как пришлось пожертвовать эмуляцией, чтобы не дергать лишний SetCursorType и видимость мышки.

Его каждый кадр всё равно меняет VGUI.
