### ISSUE TITLE
Error: implicit declaration of function ‘SDLash_InitCursors’

### ISSUE THREAD

**Issue by systemdfan** [FWGS/xash3d-fwgs#862]
Не собирается xash. Выдаётся следующая ошибка: 

`../engine/platform/sdl/sys_sdl.c: In function ‘Platform_Init’:
../engine/platform/sdl/sys_sdl.c:71:2: error: implicit declaration of function ‘SDLash_InitCursors’ [-Werror=implicit-function-declaration]
   71 |  SDLash_InitCursors();
      |  ^~~~~~~~~~~~~~~~~~
../engine/platform/sdl/sys_sdl.c: In function ‘Platform_Shutdown’:
../engine/platform/sdl/sys_sdl.c:76:2: error: implicit declaration of function ‘SDLash_FreeCursors’; did you mean ‘SDL_FreeCursor’? [-Werror=implicit-function-declaration]
   76 |  SDLash_FreeCursors();
      |  ^~~~~~~~~~~~~~~~~~
      |  SDL_FreeCursor
cc1: some warnings being treated as errors`

Насколько я понял, это ошибки связанные с коммитом d1de9e28020cf8e734036a7015c03a0df590489d

**Comment by a1batross** [comment]
Fixed in latest commit
