### ISSUE TITLE
Проверка поддержки макроса _FILE_OFFSET_BITS=64 в waf

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#864]
Текущая проверка макроса _FILE_OFFSET_BITS для поддержки файлов большого размера не является кроссплатформенной и вероятно работает только на Linux.
Как пример FreeBSD не имеет заголовочного файла features.h и [данная проверка](https://github.com/FWGS/xash3d-fwgs/blob/master/wscript#L301=) не работает корректно.

Возможное решение:
https://github.com/libarchive/libarchive/blob/master/build/cmake/CheckFileOffsetBits.c

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/c69ea00e793119131feb114a5f61f8877e9b7fa9
