### ISSUE TITLE
[Android] Сохранение настроек на лету

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#867]
До сих пор не сохраняются настройки до нажатия кнопки `Запустить`, это вызывает у пользователей конфуз.

**Comment by a1batross** [comment]
В смысле?

**Comment by nekonomicon** [comment]
В прямом.
Настройки сделанные в самом лаунчере.

**Comment by a1batross** [comment]
Хм... Странно. Лаунчер сильно не менялся со старого движка.

**Comment by Vladislav4KZ** [comment]
В новом лаунчере Xash3D FWGS от Velaron настройки сохраняются на лету, без запуска игры.
