### ISSUE TITLE
[Android] Динамическая линковка vgui

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#868]
Идея статически влинковывать модули vgui и vgui_support в библиотеку клиента пользовательской модификации выглядит не разумной.
Лучше собирать движок с модулями vgui и vgui_support для Android, а в случае с модами динамически линковать и исключать vgui из пакета.

**Comment by a1batross** [comment]
vgui_support сменил свое назначение с того чтобы быть shim-ом для dll загрузчика на ingameui мода.

Чтобы мод мог притащить, то что ему удобно. Даже если это будет vgui2, движку всё равно.

**Comment by nekonomicon** [comment]
Тогда возможно лучше вынести vgui_support в отдельный репозиторий, затея с копипастом в каждый мод не очень нравится с учетом возможных изменений в нем.

**Comment by a1batross** [comment]
Согласен. Как и vgui-dev пусть лучше будет сабмодуем самого vgui_support, а vgui_support сабмодулем в движок.

Номинально мы все-таки должны уметь VGUI1.

**Comment by a1batross** [comment]
vgui_support is now in standalone repository
