### ISSUE TITLE
Небольшая опечатка при запуске локального сервера

### ISSUE THREAD

**Issue by ro0fy** [FWGS/xash3d-fwgs#872]
Во время запуска локального сервера в консоли выводиться сообщение об IP адресе 127.0.1.1, хотя логично, что сервер запускается на 127.0.0.1(localhost)

**Comment by a1batross** [comment]
За localhost считается всё, что находится в 127.0.0.0/8. 

Иными словами, у вас 16777216 адресов, которые всегда будут вести только к твоему компьютеру.
