### ISSUE TITLE
[MOD: Opposing Force] При игре на локальном сервера слетает mp_timelimit после changelevel

### ISSUE THREAD

**Issue by Velaron** [FWGS/xash3d-fwgs#879]
Из-за чего его выставить вообще невозможно, он просто сбрасывается в 0.

**Comment by a1batross** [comment]
Переоформи репорт как в целом беды с scr

**Comment by Vladislav4KZ** [comment]
Я писал про подобное ранее: https://github.com/FWGS/xash3d-fwgs/issues/509

Ксаш сохраняет квары в listenserver.cfg, и считывает его при каждом запуске сервера. Из-за этого настройки не сохраняются, хоть те которые были изменены через меню, хоть через консоль.

**Comment by Vladislav4KZ** [comment]
Причём когда ксаш впервые запишет квары в listenserver.cfg, он не будет обновлять его в дальнейшем.

**Comment by Vladislav4KZ** [comment]
Закрываю за дубликат.
