### ISSUE TITLE
[MOD: Tyrian Ground Assault] На карте dom_endor_base скайбокс инвертирован по вертикали

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#889]
### Xash3D FWGS 0.20.1 (19 июня 2022 build 2636)
![dom_endor_base_0000_xash](https://user-images.githubusercontent.com/22411953/175274929-c0caf498-694c-4211-9ed8-c569d06f60da.png)
![dom_endor_base_0001_xash](https://user-images.githubusercontent.com/22411953/175274960-08f1ee97-815c-425b-a450-7c902b65f58e.png)
![dom_endor_base_0002_xash](https://user-images.githubusercontent.com/22411953/175275000-b85ac151-a302-4953-998d-418694bf73de.png)

### GoldSource 1.1.2.2 (3 августа 2020 build 8684)
![dom_endor_base0000_goldsrc](https://user-images.githubusercontent.com/22411953/175275626-09578fe8-67f4-41e2-84ef-b2ecc5a76ce9.png)
![dom_endor_base0001_goldsrc](https://user-images.githubusercontent.com/22411953/175275661-0a54b688-e2ae-4af4-b77d-1e4e3f38d9e0.png)
![dom_endor_base0002_goldsrc](https://user-images.githubusercontent.com/22411953/175275724-2c9e35ea-3baa-4c9d-94ca-c7ac1f98fb54.png)

**Comment by Vladislav4KZ** [comment]
Открыв текстуру неба в фотошопе я увидел что она тоже инвертирована по вертикали
![Снимок экрана 2022-06-23 165330](https://user-images.githubusercontent.com/22411953/175283025-df81f0cd-94d6-4d68-b035-99f17bf4c844.png)
При этом в GoldSource скайбокс отображается иначе.


Хотя текстуры у остальных скайбоксов не инвертированы, и отображаются нормально как на GoldSource так и на Xash3D FWGS

**Comment by nekonomicon** [comment]
Как-то связано с этим кодом:
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/imagelib/img_tga.c#L130=
https://github.com/FWGS/xash3d-fwgs/blob/master/ref_gl/gl_image.c#L1530
https://github.com/FWGS/xash3d-fwgs/blob/master/common/render_api.h#L83

**Comment by nekonomicon** [comment]
https://github.com/FWGS/xash3d-fwgs/pull/890

**Comment by Vladislav4KZ** [comment]
> #890

Никаких изменений в скайбоксе не произошло, зато теперь сломался фон в главном меню
![Screenshot_20220624-143751](https://user-images.githubusercontent.com/22411953/175499242-64c6aa6a-a52d-443f-b9d2-56a1ffbda628.png)

**Comment by Vladislav4KZ** [comment]
Вот, если что, этот перевёрнутый скайбокс
[flipped_skybox.zip](https://github.com/FWGS/xash3d-fwgs/files/8975254/flipped_skybox.zip)

**Comment by a1batross** [comment]
@nekonomicon 

У меня возможности протестировать изменения не было? Ты их сам проверяешь?

**Comment by nekonomicon** [comment]
Я сразу не проверил, думал, что кто-нибудь проверит до принятия PR, ну или дождемся Владислава.
В общем, разобрался в чем проблема, но надеюсь изменения проверят.

**Comment by Vladislav4KZ** [comment]
Проверил этот Pull Request: https://github.com/FWGS/xash3d-fwgs/pull/891
Скайбокс и фон в главном меню исправлен
![dom_endor_base_0001](https://user-images.githubusercontent.com/22411953/175523969-f2747ce0-540f-41e1-a7ac-a7404ecb559c.png)
![dom_endor_base_0000](https://user-images.githubusercontent.com/22411953/175523988-1b0da84b-b946-4ec2-bcdc-24cff0161b7f.png)

**Comment by Vladislav4KZ** [comment]
Кстати, теперь детализированные текстуры отображаются нормально, не перевёрнуты как раньше.

Вот пример, в комментариях жаловались на проблемы в ксаше.
https://gamebanana.com/mods/6736
