### ISSUE TITLE
Перевёрнутый значок игры в панели задач

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#893]
![Значок](https://user-images.githubusercontent.com/22411953/175528763-de8347c9-8b82-45b3-863e-94b1ede31364.png)

Значок естественно в TGA формате, а значки в формате ICO ксаш не грузит вообще

**Comment by Vladislav4KZ** [comment]
А хотя, значок ts_logo.ico в моде The Specialists грузится, а в Half-Life game.ico нет. Вместо него значок ксаша

**Comment by a1batross** [comment]
ICO грузятся только на Windows. Хотя почему-то там стоит проверка на 64 бита.

**Comment by a1batross** [comment]
GoldSrc кстати похоже нигде не проверяет атрибуты TGA. Но это не точно.

**Comment by Vladislav4KZ** [comment]
Не, вру, в The Specialists в gameinfo.txt указан значок ts_logo.ico. А самого ts_logo.ico нет, есть ts_logo.tga
И он кстати не перевёрнутый.

**Comment by nekonomicon** [comment]
Для иконок в tga наверно нужно выставлять вот тот самый флаг IL_DONTFLIP_TGA.
В GoldSource по ходу нет проверки bottom-left-ориентации для обычных текстур вообще, а иконки в библиотеке steam и в самой игре загружаются с учетом или без учета ориентации иконки разными алгоритмами.
И еще Windows-версия GoldSource вроде бы загружает иконки только в .ico, linux-версия только в .tga и macos-версия в icns.

**Comment by Vladislav4KZ** [comment]
> И еще Windows-версия GoldSource вроде бы загружает иконки только в .ico,

Не, у меня GoldSource грузит и иконки в .tga, в .ico не грузит наверно то что стоит 64-битная винда

**Comment by Vladislav4KZ** [comment]
Поставил последний билд ксаша. Перевёрнутые tha значки пофиксились, а .ico всё ещё не работают

**Comment by a1batross** [comment]
Отревертил в то состояние, которое было.
