### ISSUE TITLE
Перевёрнутый текст баннеров и кнопки сворачивания [_] и закрытия [X] игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#894]
![Перевёрнутые кнопки](https://user-images.githubusercontent.com/22411953/175767614-083ce428-1f91-4afd-aa07-1c400ea257c1.png)
![Снимок экрана (21)](https://user-images.githubusercontent.com/22411953/175767615-f3086560-e488-4d6c-b3eb-aba9068bd8b0.png)

Картинки с текстом кнопками в меню я конвертировал с BMP в TGA так как ксаш не грузит текстурки кнопок и заголовков (баннеров) в формате  bmp

**Comment by Vladislav4KZ** [comment]
В Half-Life такой проблемы нет. Картинки из меню я пересохранял в фотошопе в tga, там они отображаются как положено, да и в ксаше раньше тоже. Теперь они перевёрнуты.

**Comment by Vladislav4KZ** [comment]
![Снимок экрана (25)](https://user-images.githubusercontent.com/22411953/175768398-33218dc9-c04c-4e57-9da9-6659a22b4ae9.png)

**Comment by nekonomicon** [comment]
Надо проверить переворачивается ли в стиме содержимое resource/background.
И наверно выставить соответствующий флаг для всех элементов меню в tga.
Либо иначе из рассчета на старое поведение форсить флаг только для всех игровых текстур, но не иконок и меню.

**Comment by nekonomicon** [comment]
> так как ксаш не грузит текстурки кнопок и заголовков (баннеров) в формате bmp

Надо наверно отдельную issue завести если еще нет.

**Comment by Vladislav4KZ** [comment]
> Надо наверно отдельную issue завести если еще нет.

Я про это уже больше года назад написал https://github.com/FWGS/mainui_cpp/issues/49

**Comment by Vladislav4KZ** [comment]
А, ну я там писал ещё что .tga картинки имеют более высокий приоритет чем .bmp, даже если .tga картинки хранятся в папке Half-Life а не в папке мода

**Comment by a1batross** [comment]
> Надо проверить переворачивается ли в стиме содержимое resource/background в зависимости от ориентации. И наверно выставить соответствующий флаг для всех элементов меню в tga. Либо иначе из рассчета на старое поведение форсить флаг только для всех игровых текстур, но не иконок и меню.

надо просто выпиливать переворачивание

**Comment by nekonomicon** [comment]
Ну я подозреваю, что изначально дядя Миша добавил ту проверку для стимовских бэкграундов, а текстуры в модах ему не удалось проверить.

**Comment by a1batross** [comment]
Да, по спецификации тарги оно должно быть, но судя по LoadTGA оно как-то игнорируется. :)

**Comment by a1batross** [comment]
Есть альтернативное предложение -- инвертировать флаг.

По умолчанию игнорировать, но вообще иметь возможность и переворачивать.

**Comment by nekonomicon** [comment]
Ну так я и так инвертировал действие флага.
Вот в инвертированном состоянии его нужно форсить для иконок и won'овских менюшек видать.
А в старом для стимовских бэкграундов и текстур на картах.
Думаю в любом случае выставление флага для текстур лучше оставить на откуп пользователя.

**Comment by a1batross** [comment]
Нет.

Нужно сделать так, чтобы работало всегда. 

А не чтобы ломалось там, где этого не просили.

**Comment by a1batross** [comment]
Отревертил в то состояние, которое было.
