### ISSUE TITLE
Haiku port

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#9]

**Comment by Vladislav4KZ** [comment]
[#478](https://github.com/FWGS/xash3d-fwgs/pull/478)

**Comment by a1batross** [comment]
Can be closed I guess. 

Hey @exstrim401 wouldn't you mind maintaining Haiku port? See Documentation/ports.md.

**Comment by oooo-ps** [comment]
Guys, is there any installation guide or just official build for this OS?

**Comment by a1batross** [comment]
There isn't, you have to build it from the source code yourself. Follow build instructions for other platforms from README.md, they should be similar.

If you figure out the exact steps, we can add them to README.md.

**Comment by oooo-ps** [comment]
Okay, just found [this video](https://www.reddit.com/r/opensourcegames/comments/ra4lan/playing_halflife_on_haiku_using_a_foss_halflife/) and it looks like package is available in repository; maybe unofficial so.

**Comment by a1batross** [comment]
It's definitely unofficial, we don't publish engine in any repository for now. The only real official place is GitHub Releases page, if it's not there, then it's not ours.

But engine is available publicly, you're free to do whatever you want.

**Comment by oooo-ps** [comment]
Well, I made following steps:

``` bash
pkgman install libsdl2_devel freetype_devel opus_devel bzip2_devel libvorbis_devel opusfile_devel libogg_devel
./waf configure
./waf build
```
and got this error:
``` bash
[388/457] Processing engine/common/whereami.c
../engine/common/whereami.c:860:2: error: #error unsupported platform
  860 | #error unsupported platform
      |  ^~~~~
```

Currently, I'm running Haiku 64 bit, so changed config to `-8`:
``` bash
./waf configure -8
```

I believe that's unexpected condition in `whereami.c:860:2` - ~could somebody please check this file?~ untested yet but should work by PR #2459

Now I have next issue:
``` bash
[451/457] Processing engine/client/soundlib/snd_ogg_vorbis.c
../engine/client/soundlib/snd_ogg_vorbis.c:50:9: error: initialization of 'int (*)(void *, ogg_int64_t,  int)' {aka 'int (*)(void *, long long int,  int)'} from incompatible pointer type 'int (*)(void *, int64_t,  int)' {aka 'int (*)(void *, long int,  int)'} [-Werror=incompatible-pointer-types]
   50 |         OggFilestream_Seek,
      |         ^~~~~~~~~~~~~~~~~~
../engine/client/soundlib/snd_ogg_vorbis.c:50:9: note: (near initialization for 'ov_callbacks_membuf.seek_func')
../engine/client/soundlib/snd_ogg_vorbis.c:57:9: error: initialization of 'int (*)(void *, ogg_int64_t,  int)' {aka 'int (*)(void *, long long int,  int)'} from incompatible pointer type 'int (*)(void *, int64_t,  int)' {aka 'int (*)(void *, long int,  int)'} [-Werror=incompatible-pointer-types]
   57 |         FS_SeekOggVorbis,
      |         ^~~~~~~~~~~~~~~~
../engine/client/soundlib/snd_ogg_vorbis.c:57:9: note: (near initialization for 'ov_callbacks_fs.seek_func')
cc1: some warnings being treated as errors
```
UPD. I temporarily cast following entries to `(void *)`:
* `FS_SeekOggVorbis` -> `(void *) FS_SeekOggVorbis`
* `OggFilestream_Seek` -> `(void *) OggFilestream_Seek`

So now it works, with the [hlsdk-portable](https://github.com/FWGS/hlsdk-portable) components of course.. I'll check `ogg`/`vorbis` later, to resolve those types properly.

Also, wrote this [guide](https://devzone.org.ua/post/rozvidka-boyem-xash3d-fwgs-half-life-v-haiku-os).
