### ISSUE TITLE
Некорректно отображаются 8-битные bmp превьюшки для настроек гаммы и яркости

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#901]
# Project Timeless
![Снимок экрана (32)](https://user-images.githubusercontent.com/22411953/175784291-92df9eaf-8b27-481d-a57f-686b18c3756f.png)

# Desert Crisis
![Снимок экрана (34)](https://user-images.githubusercontent.com/22411953/175784308-0bbd7e13-4a6a-4170-8f94-487884a05de8.png)

В модах где используется 24-битный gamma.bmp, он отображается нормально.

**Comment by a1batross** [comment]
Можешь их приложить?

**Comment by Vladislav4KZ** [comment]
> Можешь их приложить?

[broken_gamma_preview.zip](https://github.com/FWGS/xash3d-fwgs/files/8986092/broken_gamma_preview.zip)

**Comment by Vladislav4KZ** [comment]
Если несколько раз менять карту и зайти в настройки Video options, движок крашнется с ошибкой:
```
[2022:06:28|22:31:56] Sys_Crash: address 0511FEE9, code C0000005
 0 0511FEE9(???)
 1 6BE51883(nvoglv32.DLL)
 2 6C065818 DrvPresentBuffers (nvoglv32.DLL)
 3 6B8CED80(nvoglv32.DLL)
 4 6C06557D DrvPresentBuffers (nvoglv32.DLL)
 5 6B8B1A61(nvoglv32.DLL)
 6 6B8B1CA4(nvoglv32.DLL)
 7 6B8B272C(nvoglv32.DLL)
 8 6B8D9F41(nvoglv32.DLL)
 9 6B8DA185(nvoglv32.DLL)
 10 6BE5637D(nvoglv32.DLL)
 11 6B816647(nvoglv32.DLL)
 12 6BEDD8A5(nvoglv32.DLL)
 13 6BEDD1FE(nvoglv32.DLL)
 14 6B98E990(nvoglv32.DLL)
 15 6D43380C GL_TextureImageRAW (D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_image.c:1092:50) (ref_gl.dll)
 16 6D43466A GL_UploadTexture (D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_image.c:1271:47) (ref_gl.dll)
 17 6D4318EF GL_ProcessTexture (D:\a\xash3d-fwgs\xash3d-fwgs\ref_gl\gl_image.c:1913:13) (ref_gl.dll)
 18 6F5C02F6 GL_ProcessTexture (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\cl_gameui.c:1091:29) (xash.dll)
 19 6B67160D CMenuVidOptions::GetConfig (C:\Users\Administrator\source\repos\xash3d-fwgs\mainui\menus\VideoOptions.cpp:86:0) (menu.dl(menu.dl(m(meHost_WriteGLConfig()
[2022:06:28|22:31:56] Host_WriteConfig()
[2022:06:28|22:31:56] Master server list not changed
[2022:06:28|22:31:56] Sys_DestroyConsole: Exiting!
[2022:06:28|22:31:56] Sys_FreeLibrary: Unloading xash.dll
```
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/9003016/engine.log)

**Comment by a1batross** [comment]
Исправил в меню.

Но ишшую попрошу не закрывать, так как правильное исправление этой ошибки -- внесение поддержки палитр без 256 цветов (в данном случае палитра из 255 цветов) в ImageLib.

Выстрелить может и в любом другом моде, если по какой-то причине нужно хранить "оригинал" изображения для дальнейшей обработки -- изображения декалей или плеермоделей.

**Comment by 0x4E69676874466F78** [comment]
@a1batross да, если подложить текстуру png с палитрой то движок отказывается грузить. Это при том что в самой халфе в вадах текстуры с палитрой :)

**Comment by nekonomicon** [comment]
Потому что поддержку индексированных png с палитрой никто не добавлял.
Пока только полноцветные поддерживаются.

**Comment by a1batross** [comment]
Эту issue можно закрывать. Рендерер раскрывает индексированные текстуры в полноцветные, если таковые находит.
