### ISSUE TITLE
Проверка существующих префиксов gamedll.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash3d-fwgs#902]
Некоторые моды, например Tyrian, уже имеют библиотеки с префиксом вида `_i686`, `_i386`, `_amd64`.
Проблема заключается в том, что на экзотических платформах движок пытается загружать библиотеки с именами вида `TYRIAN_i386_linux_arm64` или `TYRIAN_i386_freebsd_i386`, если не редактировать `liblist.gam`.
Возможно также стоит на x86 linux пытаться загружать библиотеки с префиксом `_i386` и без, независимо от значения `gamedll_linux`, если еще нет.

**Comment by a1batross** [comment]
Fixed in eb0459a0 and ca3b0e62
