### ISSUE TITLE
[MOD: Headcrab Frenzy] Не работает сияние монтировки при подборе поверапов

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#905]
# Xash3D FWGS 0.20.1
![weapon_glow_xash](https://user-images.githubusercontent.com/22411953/175807371-e26377a7-ea59-43bb-bd96-f3371a57bebe.png)

# GoldSource
![weapon_glow_goldsource](https://user-images.githubusercontent.com/22411953/175807436-2f9afa3c-edec-4b33-80c8-0d44cb725a62.png)

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/904

Это один и тот же баг, на самом деле, потому что вывернуло не только монтировку, но и glowshell эффект. Как я ненавижу этот righthand...

**Comment by Vladislav4KZ** [comment]
Этот баг больше не воспроизводится.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3211
Тип сборки: win32-i386
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/40041e30eb0dd93b6484c2b0057b21e3b70c15e3
Ветка: master
