### ISSUE TITLE
[MOD: Ricochet] Нет звука прыжка по платформам

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#910]
Видео для наглядной демонстрации не удалось записать, но во время записи почему-то вообще в рикошете на ксаше пропали все звуки кроме шагов, и мигали стрелочки на платформах.

**Comment by Vladislav4KZ** [comment]
Когда прописал в консоли ``cl_lw 0`` звук появился.

**Comment by Vladislav4KZ** [comment]
Также нет крика от падения, звука рикошета, возвращения дисков.

В WON версии Ricochet звук прыжка работает и при ``cl_lw 1``

**Comment by a1batross** [comment]
Какая-то чертовщина. Стоит только залезть под отладчиком и звуки ходьбы есть.

До остальных пока ещё не дошёл.

**Comment by Vladislav4KZ** [comment]
Баг не воспроизводится на последнем билде движка.

**Comment by Vladislav4KZ** [comment]
Возможно связано с исправлением этого бага:
https://github.com/FWGS/xash3d-fwgs/issues/472
