### ISSUE TITLE
Blue Shift crashes on startup with the following error message:

### ISSUE THREAD

**Issue by Cuthalion44** [FWGS/xash3d-fwgs#915]
Sys Crash: address OFB2C569, code C0000005 O OFB2C569 V_CalcRefdef (client.dll) 1 OFB2C1CF V_CalcRefdef (client.dll) 2 OFB321D6 V_CalcRefdef (client.dll) 3 OFB061A7 HUD ChatinputPosition (client.dll) 4 OFB71EAB V_CalcRefdef (client.dll) 5 76386739 BaseThreadlnitThunk (KERNEL32.DLL) 6 773A8FBD REIGetFullPathName_UEx (ntdll.dll) 7 773D9133 RtCaptureContext (ntdll.dll)

**Comment by Vladislav4KZ** [comment]
Original Blue Shift libraries aren't supported yet. You need to install this https://github.com/FWGS/hlsdk-xash3d/suites/7015281578/artifacts/275509783

**Comment by a1batross** [comment]
We know about missing VGUI2 support.

**Comment by gabberhead** [comment]
i tried to use the xash3d, the newest build, after a long time again. and i also get this error message. is this error not fixed yet?

**Comment by TheKingFireS** [comment]
> i tried to use the xash3d, the newest build, after a long time again. and i also get this error message. is this error not fixed yet? i usead the newest downloads from steam for half life, opossing force and blu shift. but only blue shift have this problem.

Already fixed maps issues, but only problem is client dlls. Replace it with FWGS's bshift client dlls.

**Comment by gabberhead** [comment]
sorry for asking, but where to find them? i look already a bit, but didnt find it :)

**Comment by TheKingFireS** [comment]
> sorry for asking, but where to find them? i look already a bit, but didnt find it :)

https://github.com/FWGS/hlsdk-portable/actions/runs/4127449618

**Comment by gabberhead** [comment]
thanx worked :)
