### ISSUE TITLE
I replaced Blue Shift's .dll files with the ones from the hlsdk-xash3d repository, but the maps still aren't supported.

### ISSUE THREAD

**Issue by Cuthalion44** [FWGS/xash3d-fwgs#917]
Does anyone have the converted .bsp files?

**Comment by a1batross** [comment]
You don't need to convert them. It's our bug and wait for it to be fixed.

вт, 5 июл. 2022 г., 00:09 Cuthalion44 ***@***.***>:

**Comment by mmillar-bolis** [comment]
Duplicate of #859.
