### ISSUE TITLE
Move RunEvents to InputFrame

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#92]
This could potentially unfreeze application from OS point of view if something was written to console. There is already a solution for Win32 located in Sys_SendKeyEvents function.

But is this safe to peek SDL events and process them? Unlike Sys_SendKeyEvents, Platform_RunEvents clears the event queue.

**Comment by mittorn** [comment]
Original win32 engine has callback that called when dispatching events. Is it called from Sys_SendKeyEvents?

**Comment by a1batross** [comment]
@mittorn well... maybe? 

Because IN_WndProc is a callback that was passed to WinAPI. It must be somewhere called from main loop then. 

I need to try build Xash with debuginfo and set breakpoint to IN_WndProc.

**Comment by mittorn** [comment]
It is called from DispatchMessage or something similar, i do not remember exactly, it was when i used winapi directly from python

**Comment by a1batross** [comment]
I don't remember what was this about. 

Let's close it.
