### ISSUE TITLE
Music isn't playing

### ISSUE THREAD

**Issue by arcanechocolate** [FWGS/xash3d-fwgs#920]
Everything is working wonders except for the fact that music simply refuses to play. Volume levels are fine.
I've completed the game without music (from a previous save file), but also started a new game, loaded c1a0 and grabbed the suit. Nothing plays except for the suit voice.

I'll dump my config file here down below.

//=======================================================================
//			Copyright XashXT Group 2022 ©
//			config.cfg - archive of cvars
//=======================================================================
unbindall
bind TAB "+showscores"
bind ENTER "+attack"
bind ESCAPE "cancelselect"
bind SPACE "+jump"
bind ' "+moveup"
bind + "sizeup"
bind , "+moveleft"
bind - "sizedown"
bind . "+moveright"
bind / "+movedown"
bind 1 "weapon_crowbar"
bind 2 "weapon_9mmhandgun"
bind 3 "weapon_9mmAR"
bind 4 "weapon_shotgun"
bind 5 "weapon_handgrenade"
bind SEMICOLON "+mlook"
bind = "sizeup"
bind [ "invprev"
bind ] "invnext"
bind ` "toggleconsole"
bind a "+moveleft"
bind c "weapon_gauss"
bind d "+moveright"
bind e "+use"
bind f "impulse 100"
bind q "weapon_357"
bind r "+reload"
bind s "+back"
bind t "impulse 201"
bind u "messagemode2"
bind v "+moveup"
bind w "+forward"
bind x "weapon_rpg"
bind y "messagemode"
bind z "weapon_crossbow"
bind ~ "toggleconsole"
bind UPARROW "+forward"
bind DOWNARROW "+back"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
bind ALT "+strafe"
bind CTRL "+duck"
bind SHIFT "+speed"
bind F5 "snapshot"
bind F6 "save quick"
bind F7 "load quick"
bind F10 "quit prompt"
bind INS "+klook"
bind PGDN "+lookdown"
bind PGUP "+lookup"
bind END "centerview"
bind MWHEELDOWN "+jump"
bind MWHEELUP "weapon_satchel"
bind MOUSE1 "+attack"
bind MOUSE2 "+attack2"
bind MOUSE3 "weapon_snark"
bind MOUSE4 "weapon_egon"
bind MOUSE5 "weapon_hornetgun"
bind PAUSE "pause"
MP3Volume "0.800000"
allow_levelshots "0"
ambient_fade "1000"
ambient_level "0.3"
bottomcolor "6"
brightness "0.750000"
cl_allow_download "1"
cl_allow_upload "1"
cl_backspeed "400"
cl_bmodelinterp "1"
cl_clockreset "0.1"
cl_cmdbackup "2"
cl_cmdrate "30"
cl_dlmax "128"
cl_download_ingame "1"
cl_envshot_size "256"
cl_fixtimerate "7.5"
cl_forwardspeed "400"
cl_himodels "0.000000"
cl_lc "1"
cl_lightstyle_lerping "0"
cl_logocolor "orange"
cl_logofile "lambda"
cl_lw "1"
cl_nopred "0"
cl_nosmooth "0"
cl_righthand "0"
cl_showerror "0"
cl_showevents "0"
cl_showfps "2"
cl_smoothtime "0"
cl_test_bandwidth "1"
cl_updaterate "20"
cl_vsmoothing "0.05"
cmd_scripting "0"
con_fontsize "1"
con_mapfilter "1"
con_notifytime "3"
crosshair "1"
direct "1"
dsp_off "0"
ex_interp "0.1"
fps_max "72"
gamma "2.500000"
gl_anisotropy "1"
gl_check_errors "1"
gl_clear "0"
gl_detailscale "4.0"
gl_emboss_scale "0"
gl_finish "0"
gl_keeptjunctions "1"
gl_lightmap_nearest "0"
gl_msaa "1"
gl_nosort "0"
gl_polyoffset "0.1"
gl_texture_lodbias "-1"
gl_texture_nearest "1"
gl_vsync "1"
gl_wireframe "0"
hpk_maxsize "0"
hud_capturemouse "1"
hud_centerid "0"
hud_classautokill "1"
hud_draw "1"
hud_fastswitch "1"
hud_scale "0"
hud_takesshots "0"
joystick "0.000000"
lastdemo ""
lightgamma "1"
lookspring "0"
lookstrafe "0"
m_filter "0"
m_forward "1"
m_pitch "0.022000"
m_side "0.8"
m_yaw "0.022"
model "gordon"
mp_decals "300"
name "Player"
net_graph "0"
net_graphheight "64"
net_graphpos "1"
net_graphsolid "1"
net_graphwidth "192"
net_scale "5"
net_speeds "0"
r_adjust_fov "1"
r_decals "4096"
r_detailtextures "1"
r_drawentities "1"
r_dynamic "1"
r_lighting_ambient "0.3"
r_lighting_extended "1"
r_lighting_modulate "0.6"
r_showtree "0"
r_speeds "0"
r_sprite_lerping "1"
r_sprite_lighting "1"
r_studio_sort_textures "0"
r_studiocache "1"
r_traceglow "1"
rate "3500.000000"
room_hires "2"
s_combine_channels "0"
s_cull "0"
s_lerping "1"
s_phs "0"
s_show "0"
scr_conspeed "600"
sensitivity "3"
suitvolume "0.250000"
sv_aim "0"
sv_allow_PhysX "1"
sv_background_freeze "1"
sv_check_errors "0"
sv_precache_meshes "1"
sv_reconnect_limit "3"
sv_rollangle "0"
sv_validate_changelevel "1"
topcolor "30"
ui_precache "0"
ui_showmodels "0"
vgui_colorstrings "0"
viewsize "120"
voice_modenable "1.000000"
volume "0.020000"
+mlook
+jlook
exec userconfig.cfg

Also, the .wavs are in valve/media folder. Build is 49/0.99 (4344).

**Comment by nekonomicon** [comment]
All good, but we don't support original xash3d.
And the latest xash3d build was 4529.

**Comment by arcanechocolate** [comment]
I'm sorry @nekonomicon.
I have now updated my files on a fresh folder install of your current 4529 build.
The issue persists. I'm using the WON version of Half-Life. Curiously enough, my Steam version of Opposing Force does play music.

**Comment by nekonomicon** [comment]
> We are not XashXT group.

We don't support Xash3D.
There source code of this engine fork named Xash3D FWGS.

**Comment by a1batross** [comment]
Seems to be discussed on Discord already.

Closing as resolved.
