### ISSUE TITLE
Move Android port back to SDL2

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#922]
Guess there isn't many people to take care of Android code today. It has a lot of bugs both on engine side and Java side.

So we can make maintenance cheaper for us by disabling Android-specific code and instead use whatever SDL2 allows us to do. Anyway, we haven't really tried how newer SDL works on Android.

**Comment by SNMetamorph** [comment]
I agree with that decision, because there are too many headache for developers

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/1112
