### ISSUE TITLE
Баг: при надписи загрузка чёрный экран, ещё конда я делаю сейф через меню и хочу заново сделать такой же сейф то старый сейф переписывается новым

### ISSUE THREAD

**Issue by GDMHL** [FWGS/xash3d-fwgs#927]

**Comment by Vladislav4KZ** [comment]
Дубликат: https://github.com/FWGS/xash3d-fwgs/issues/641 и https://github.com/FWGS/mainui_cpp/issues/59

И кстати, баг с перезаписыванием нового сохранения случается только в русской локализации. На английском языке ксаш сохраняет игру с названием save001, save002 и т.д. но когда выбран русский язык, то игра сохраняется только с названием "Новое"

**Comment by Vladislav4KZ** [comment]
Так что в случае второго бага, пока сохраняй через консоль `save название сохранения на английском`, включи английский язык написав в консоли или в mainui.cfg `ui_language english` или вообще удали русификатор.

**Comment by a1batross** [comment]
Баг с сохранениями пофикшен в https://github.com/FWGS/mainui_cpp/commit/97fcbf8979f22d774b1cc01cb5553743592d39d0

Пока не знаю что создает баг с черным экраном, но лучше отслеживать его в #641
