### ISSUE TITLE
Implement borderless windowed mode

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#928]

**Comment by a1batross** [comment]
@nekonomicon not everybody runs tiling WMs or even *nixes.

I'm trying to understand what's the point of it. When I'm gaming, I usually pick bordered window mode and very rarely full screen. Never used borderless mode though.

**Comment by Velaron** [comment]
No, exclusive fullscreen is still awfully slow and often doesn't even work or crash the game. Most games say they use "fullscreen", but are actually borderless.

**Comment by a1batross** [comment]
Isn't that's what SDL2 does for us?

We use it to set video mode, but when no video mode switching is done, isn't it practically just borderless window?

**Comment by AshleighTheCutie** [comment]
I will say, that I find borderless full screen to actually give a slight performance boost in specific hardware configurations; namely anything with nVidia or AMD GPUs rendering through an iGPU. I'm not sure why, but I tend to get at least 5 additional FPS, but typically even more.

And besides (famous last words incoming), would it be that hard to implement?

**Comment by Velaron** [comment]
Also exclusive fullscreen sucks when using non-native resolution, as Windows decides to resize every single window.

**Comment by a1batross** [comment]
Done.
