### ISSUE TITLE
xashbox does not full run on xash0.20

### ISSUE THREAD

**Issue by dragonxash** [FWGS/xash3d-fwgs#93]
update 0.20 xashbox only have move and direction button，What is the reason?

**Comment by dragonxash** [comment]
http://img02.sogoucdn.com/app/a/100520146/1ab5159acbf766cf5e4546f3ad2adf32

**Comment by mittorn** [comment]
Yes, scripting and dynamic cvars still not exist in new engine

**Comment by nekonomicon** [comment]
May be closed?
