### ISSUE TITLE
Camera moves when I walk

### ISSUE THREAD

**Issue by bitchboy42069** [FWGS/xash3d-fwgs#934]
Using a gamepad, whenever I walk the camera moves too, in whatever direction I move in

**Comment by a1batross** [comment]
Can you describe this in detail?

**Comment by bitchboy42069** [comment]
When I walk forward the camera moves up, when I walk backwards the camera moves down etc

**Comment by a1batross** [comment]
@bitchboy42069 look up into gamepad settings, and try to rebind the joysticks axes.

If you're on Android, it probably cannot be fixed, due to how gamepads are working on Android.

**Comment by bitchboy42069** [comment]
I tried rebinding the Axes and it doesn’t affect anything, also I am on PC

**Comment by a1batross** [comment]
Try running Xash with `-sdl_joy_old_api`.

There are two APIs available in SDL2, but both sucks and very unreliable.

As last resort, Steam somehow affects how gamepads work, you can try to add Xash as third party game on Steam.

**Comment by bitchboy42069** [comment]
I am running it through steam, and I tried that api and now the stick just moves the camera instead of moving me

**Comment by bitchboy42069** [comment]
Update, the left stick moves the camera even if I turn off gamepad support

**Comment by a1batross** [comment]
Oh... I guess it's trying to be just a keyboard or mouse?

**Comment by a1batross** [comment]
Does it work in other games, preferably first-person shooters?

**Comment by bitchboy42069** [comment]
Yeah, I also fixed the problem by just making the left stick to WASD
