### ISSUE TITLE
Add headbob and viewroll?

### ISSUE THREAD

**Issue by Arbiterz** [FWGS/xash3d-fwgs#936]
How do you add head roll and viewroll to xash3d? There are mods for it for Half-Life but they don't seem to work with Xash3D. The mods are client.dll which I know the xash3d client.dll is different from just the default steam version.

**Comment by Arbiterz** [comment]
Think this one doesn't have viewroll
https://www.moddb.com/games/half-life/addons/viewbobbing-re-implemented
This one I have test on Half-Life Steam has both viewroll and headbob
https://github.com/Admer456/halflife-adm-tutorials/releases/tag/v1.0

**Comment by a1batross** [comment]
Can you explain what's not working here? You can get rollangle with sv_rollangle cvar already. Viewbob is completely on client.dll side, engine doesn't matter here. (unless we broke something)

**Comment by nekonomicon** [comment]
Really IDK why need to have such functionality into engine and on server-side.
DMC already has `cl_rollangle` and `cl_rollspeed` cvars and some mods like HL: Urbicide and Zombie-X too.
I think we can move such functionality to `hlsdk-portable`.

**Comment by a1batross** [comment]
@nekonomicon rollangle and rollspeed are movevars.

In Xash3D you have access to ALL movevars as just cvars.
