### ISSUE TITLE
[MOD: Opposing Force] После взрыва вертолёта osprey, солдат не произносит фразу из drill/intro03.wav

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#940]
### GoldSource
https://www.youtube.com/watch?v=vYt4ccQHoYo

### Xash3D FWGS
https://www.youtube.com/watch?v=T0mceXkpSe8

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d-fwgs/commit/8293bc91d4e2e4b57914f18efa29a27ffb7e5abf
