### ISSUE TITLE
[Windows] Когда запущен мод с ярлыка без аргумента -dev невозможно сменить игру

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#941]
При попытке смены мода просто перезапускается текущий.

А когда мод запущен с аргументом -dev тогда можно переключиться на другой мод.

**Comment by Vladislav4KZ** [comment]
Опять ложный баг репорт, дело даже не в этом. Просто ярлык с Oppsoing Force содержал строку ``-console +game gearbox`` и из-за этого была эта проблема. Точнее из-за аргумента ``+game``.

**Comment by a1batross** [comment]
+game надо тоже переписывать в execve коде.

**Comment by a1batross** [comment]
Хотя постой. +game это какая-то бессмыслица.

Да, командой можно сменить игру, в консоли вбив game gearbox например. Но тут ты до старта игры меняешь игру. По идее движок от такого должен в бесконечный цикл перейти.
