### ISSUE TITLE
Doesn't work on linux-armv8_32hf

### ISSUE THREAD

**Issue by cesarpuig** [FWGS/xash3d-fwgs#942]
Hello, When starting it on linux-armv8_32hf, I get the following error.

`Parameters: 
Executing: SDL_VIDEO_KMSDRM_CRTCID=87 SDL_VIDEO_KMSDRM_MODEID=5 pushd /home/pi/RetroPie/roms/ports/xash3d-fwgs/; SDL_VIDEO_KMSDRM_CRTCID=87 SDL_VIDEO_KMSDRM_MODEID=5  LD_LIBRARY_PATH=/opt/retropie/ports/xash3d-fwgs /opt/retropie/ports/xash3d-fwgs/xash3d -game "valve" -clientlib cl_dlls/client.so -dll dlls/hl.so; SDL_VIDEO_KMSDRM_CRTCID=87 SDL_VIDEO_KMSDRM_MODEID=5  popd
~/RetroPie/roms/ports/xash3d-fwgs ~
Ver: Xash3D FWGS 0.20 (build 2677-55a29e6, linux-armv8_32hf)
Crash: signal 11 errno 0 with code -6 at 0xaa6 (nil)
~`

If I can do some testing or give you more information to try to fix it, please let me know.

Thank you

**Comment by nekonomicon** [comment]
Probably, you need to compile native client and server libraries from `FWGS/hlsdk-portable` repository.
And you don't need to use additional flags like `-game` and `-clientlib`.
Also, try to run engine with `-dev 2 -log` flags to get log.

**Comment by a1batross** [comment]
wtf is this command line.

You never need provide `-clientlib` or `-dll` options.

Who packaged this for retropie?

**Comment by cesarpuig** [comment]
Hello @nekonomicon @a1batross.

First of all, thank you for answering and secondly, you will forgive me, but my computer knowledge is scarce. This error has started happening to me recently.

> Probably, you need to compile native client and server libraries from FWGS/hlsdk-portable repository.

Yes, I am compiling the native clients and the server libraries. If by that you mean files client.so and hl.so

> And you don't need to use additional flags like -game and -clientlib.

> You never need provide -clientlib or -dll options.

I use the -game flag to launch hl, bshift, or gearbox. In the image you can see the structure of my installation folder, 
I don't know if it's the right way

![Files](https://user-images.githubusercontent.com/30637939/182157446-65680bf5-2ea8-412d-b15d-c80942ccbcf5.png)

In recent builds, if I didn't specify -clientlib or -dll options, I got an error and couldn't run it

> Also, try to run engine with -dev 2 -log flags to get log.

I get the following [Log](https://pastebin.com/PCHbxZpt)

Thanks again

**Comment by a1batross** [comment]
You're on 55a29e6 commit, but you don't have filesystem_stdio.so in this folder.

**Comment by cesarpuig** [comment]
> You're on https://github.com/FWGS/xash3d-fwgs/commit/55a29e6e6bdc0e861f5e585745a1e7b52a290602 commit, but you don't have filesystem_stdio.so in this folder.


> Switch to latest commit from master, and use ./waf install --destdir=path to install all the needed files.

Solved, it has been to install the file system_stdio.so and it already works.

I used a custom script to install it in retropie and it was skipping that file because I didn't know it was needed.


Thanks
