### ISSUE TITLE
[Android] Не может найти библиотеку filesystem_stdio

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#945]
![Screenshot_20220801-171627](https://user-images.githubusercontent.com/22411953/182137759-aae29e22-83a8-457a-bdee-2449b6334f16.png)

**Comment by SNMetamorph** [comment]
А это точно самый последний билд движка?

**Comment by a1batross** [comment]
Последний, просто Android, как и Windows, я не фиксил.

Сейчас Android и занимаюсь

**Comment by Vladislav4KZ** [comment]
> А это точно самый последний билд движка?

Прям только что скачал. Разве есть другие старые билды для Android с filesystem_stdio?

**Comment by Vladislav4KZ** [comment]
Исправлено в последней сборке движка.
