### ISSUE TITLE
`XASH_COLORIZE_CONSOLE` breaks the correct output of zeros

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [FWGS/xash3d-fwgs#949]
Как минимум это затрагивает Linux (тестировалось только в нём, машина @5FB5).
На r_show_devices с `XASH_COLORIZE_CONSOLE` вывод такой:
![r_show1](https://user-images.githubusercontent.com/4449851/183081634-437c1319-d27e-4769-9f38-88341973c65c.png)
0000 превратилось в 0

На r_show_devices без `XASH_COLORIZE_CONSOLE` вывод такой:
![r_show2](https://user-images.githubusercontent.com/4449851/183081647-b035d718-33d5-4c38-b227-093b3fde5aa9.png)
Стало как должно быть.
```patch
diff --git a/engine/common/sys_con.c b/engine/common/sys_con.c
index 1f29cb8..eb9add1 100644
--- a/engine/common/sys_con.c
+++ b/engine/common/sys_con.c
@@ -19,7 +19,7 @@ GNU General Public License for more details.
 #endif
 
 #if !XASH_WIN32 && !XASH_MOBILE_PLATFORM
-#define XASH_COLORIZE_CONSOLE
+//#define XASH_COLORIZE_CONSOLE
 // use with caution, running engine in Qt Creator may cause a freeze in read() call
 // I was never encountered this bug anywhere else, so still enable by default
 // #define XASH_USE_SELECT 1

```

**Comment by 0x4E69676874466F78** [comment]
(выше патч не решение а для теста)

**Comment by a1batross** [comment]
Это воспроизводится на последнем мастере? У нас уже переписан вывод цветного текста. Между прочим он даже стал быстрее :)

cc @w23 надо бы вас ребейзнуть :)

**Comment by 0x4E69676874466F78** [comment]
@a1batross сделай пожалуйста нам пуллреквест.

**Comment by a1batross** [comment]
Похоже, воспроизводится и на мастере. :(

**Comment by a1batross** [comment]
Соврал. На мастере работает всё прекрасно.
