### ISSUE TITLE
Android версия 

### ISSUE THREAD

**Issue by futats00** [FWGS/xash3d-fwgs#95]
Та в принципе появился, дошел до чейлжлевела, ивю вот. 
Конечно после окончания загрузки все встает на свои места. Короче такое только во время загрузки происходит, ну вы поняли
![Screenshot_2019-12-03-13-05-05](https://user-images.githubusercontent.com/58468155/70045760-b3624280-15d5-11ea-9f5c-75f00a0507a0.png)

**Comment by Vladislav4KZ** [comment]
gl_clear 1 в консоли напиши

**Comment by futats00** [comment]
> gl_clear 1 в консоли напиши

Это кстати не помогло. А еще благодаря сворачиваниям я нашел еще баги: музыка играет только в меню(или паузе, как хотите называйте), и вот еще обнажил свое управление(не я сам, а оно само), и интерфейс стал белым. Я вообще молчу о том что в игре интерфейс желтый. Я думаю это как-то взаимосвязано, что желтый интерфейс, а при сворачивании все становися белым, и то что было прозрачным тоже становится белым, и даже цвета иконок управления брасываются до белого.
![Screenshot_2019-12-03-14-19-45](https://user-images.githubusercontent.com/58468155/70047739-ab0c0680-15d9-11ea-9b7d-44570ec591f9.png)
![Screenshot_2019-12-03-14-19-29](https://user-images.githubusercontent.com/58468155/70047478-30db8200-15d9-11ea-8071-38dbdbe69179.png)

**Comment by futats00** [comment]
> > gl_clear 1 в консоли напиши
> 
> Это кстати не помогло. А еще благодаря сворачиваниям я нашел еще баги: музыка играет только в меню(или паузе, как хотите называйте), и вот еще обнажил свое управление(не я сам, а оно само), и интерфейс стал белым. Я вообще молчу о том что в игре интерфейс желтый. Я думаю это как-то взаимосвязано, что желтый интерфейс, а при сворачивании все становися белым, и то что было прозрачным тоже становится белым, и даже цвета иконок управления брасываются до белого.
> ![Screenshot_2019-12-03-14-19-45](https://user-images.githubusercontent.com/58468155/70047739-ab0c0680-15d9-11ea-9b7d-44570ec591f9.png)
> ![Screenshot_2019-12-03-14-19-29](https://user-images.githubusercontent.com/58468155/70047478-30db8200-15d9-11ea-8071-38dbdbe69179.png)

![Screenshot_2019-12-03-14-36-49](https://user-images.githubusercontent.com/58468155/70048042-6b91ea00-15da-11ea-95d1-149eecb40d93.png)
А еще в том же багоном состоянии со сворачиваниями, когда я нажал на кнопку выхода все стало белым, при нажатии аппаратной виртуальной кнопки 'назад' я отменил белый экран и вернулся обратно. При повторе тоже самое происходит

**Comment by a1batross** [comment]
Что за девайс и версия?

**Comment by futats00** [comment]
Я закрыл ишу потому что как только я жалуюсь, я либо уже не могу повторить баг, либо баг возможно появляется по другой причине, либо я не могу выяснить от чего происходит. Отложил про ишу и забыл. Все беда в том что я поспешил репортить.
Девайс Sony Xperia ZL C6503 Android 5.0.2 13го года. Да, старенький, есть только gles1 судя по всему. Когда я пытался повторить тот баг то у меня просто не то с текстурами не то с освещением проблема была, но после чейнджлевела все лечится. Когда сворачиваешь игру во время перехода на другую локацию. Когда впервый раз это случилось у меня было то что сверху описывал. Баг не особо мешающий, но все же баг. Повторить я смог только один раз и лечится касанием экрана. Надеюсь я щас не создал проблем

**Comment by nekonomicon** [comment]
Даже если баг плавающий закрывать issue не стоит. Факт в том, что он есть.

**Comment by a1batross** [comment]
@futats00 gles2 есть во всех устройствах с самых ранних версий Android

**Comment by lewa-j** [comment]
В этой соньке Adreno 320, он умеет даже GLES 3.0

**Comment by mittorn** [comment]
wes_init и nanogl_initточно не вызввается повторно после сворачивания?
