### ISSUE TITLE
При cl_test_bandwidth 1, к новым серверам подключается только с 3-ей попытки.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#952]
При cl_test_bandwidth 1, к новым серверам удаётся подключиться только с 3-ей попытки, пока не сработает "hi-speed connection is failed".
Временное решение проблемы - cl_test_bandwidth 0.
Проверял на сервере "kekbin's server [Modded] [PC Support]".

**Comment by a1batross** [comment]
Так и должно быть. Он пытается подключиться без фрагментации.
