### ISSUE TITLE
На новых серверах ботов засчитывает за реальных игроков.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#961]
В качестве примера - сервер "Test Server XASH3D FWGS v0.20.1", на данный момент показывается 12 игроков в сервер-барузере, хотя на деле эти 12 игроков - только ParaBot боты.
Бага нету на старых серверах, по типу Rats DM, боты там не засчитваются как реальные игроки.

**Comment by nekonomicon** [comment]
Так это вроде нормальное поведение для GoldSrc и у ботов есть настройка, чтобы покидать сервер когда на него заходят реальные игроки.
На самом деле было бы не плохо отображать в меню кол-во реальных игроков и ботов через раздельные индикаторы.

**Comment by unnamed9** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/6ef76fe6656f22b2a73a8ad48611f0378f76d9f4.

**Comment by nekonomicon** [comment]
Я считаю, что эту issue рано закрывать потому что:
> это нормальное поведение для GoldSrc и у ботов есть настройка, чтобы покидать сервер когда на него заходят реальные игроки.

Были люди недовольные новым поведением потому что тут работает обратный эффект:
Большинство игроков принциально не подключается к пустующим серверам, а при наличии ботов есть "иллюзия" наличия игроков и хоть какой-то противник.
C данным исправлением с большой вероятностью сервера будут пустовать.
Либо нужен какой-то маркер, что на сервере присутствуют боты, либо нужно иметь возможность возвращать старое поведение через `bugcomp`.

**Comment by Elinsrc** [comment]
Можно сделать наверное чтото типо квара.

**Comment by lewa-j** [comment]
Согласен что нужен индикатор ботов. Но их ни в коем случае нельзя показывать как игроков. Правильным решением будет два индикатора. Как в vgui2
![изображение](https://user-images.githubusercontent.com/5416122/184534442-59009dae-4ef1-4871-9ed8-0df3b9a41a20.png)

**Comment by a1batross** [comment]
Я согласен, что о ботах выдавать информацию необходимо. Но соответствующее расширение для `info` его хорошо бы вынести в отдельную задачу. Как и для UI для него.

К слову `TSource Engine Query` подсчитывает их.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/962
