### ISSUE TITLE
OpenGL Error: GL_INVALID_OPERATION (at ../ref_gl/gl_rmain.c:814 message flooding engine.log and console output

### ISSUE THREAD

**Issue by Kelvfimer** [FWGS/xash3d-fwgs#967]
Hello

[Problem Description]

When starting the game console output and engine.log is full of [OpenGL Error: GL_INVALID_OPERATION (at ../ref_gl/gl_rmain.c:814) message every time

[Environment and peripherals]

I'm using odroid n2+ with latest emuelec, latest version of the engine and a xbox 360 pad.

Linux EMUELEC 4.9.269 https://github.com/FWGS/xash3d-fwgs/pull/1 SMP PREEMPT Tue Aug 9 12:11:07 CDT 2022 aarch64 GNU/Linux

[Launch command]

I execute the game as follows ./xash3d -ref gles2 -nowriteconfig -console &> /emuelec/logs/xash3d.log (For this test I added -dev 2 and -log flags)

[Steps to repro]
1. Start a new game.
2 Play for one minute.
3. Check console output of engine.log (if dev and logs flags are enabled). It will be full of  [OpenGL Error: GL_INVALID_OPERATION (at ../ref_gl/gl_rmain.c:814) 

[Logs are attached]
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/9356372/engine.log)

**Comment by a1batross** [comment]
ref_gles2 is deprecated now.

Users better switch to ref_gles3compat or ref_gl4es.
