### ISSUE TITLE
Не отображается анимированный значок и табличка с никнеймом игрока в модах когда он использует голосовой чат

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#968]
![lambda_bunker_0001.png](https://user-images.githubusercontent.com/22411953/185300189-37ea7660-2f4c-411f-95d5-bb92ae843cdb.png)![lambda_bunker_0002.png](https://user-images.githubusercontent.com/22411953/185300218-88c560e2-5cee-4329-bc71-6b2363e13116.png)

**Comment by Vladislav4KZ** [comment]
Когда используешь голосовой чат на своём локальном сервере, то этот анимированный значок в таблице остаётся у тебя самого

**Comment by Vladislav4KZ** [comment]
В Team Fortress Classic, и других модах (в Sven Coop ещё заметил) что, после использования голосового чата с voice_loopback 1 не исчезает табличка с никнеймом игрока в правой части экрана
![2fort_0005.png](https://user-images.githubusercontent.com/22411953/185304755-8f309194-0d00-4417-8e50-9060a756ef09.png)

**Comment by Vladislav4KZ** [comment]
Из-за этого коммита: https://github.com/FWGS/xash3d-fwgs/commit/74707551ae47f2bd980545f18db365d3e7b8882f в модах при использовании голосового чата, не отображается анимированный значок в таблице счёта и табличка с ником игрока.

Проверено в Team Fortress Classic, Sven Coop, The Specialists. Этому багу наверняка подвержены все моды, так как даже последние Steam версии игр от Valve, такие как TFC имеют этот баг. (Blue Shift не в счёт, он синглплеерный, а Opposing Force не поддерживает голосовой чат).

**Comment by SNMetamorph** [comment]
Причём в стимовской хл всё работает. Предлагаю попробовать voice_clientdebug 1 и посмотреть, что выводиться, и сравнить с голдсурсом

**Comment by Vladislav4KZ** [comment]
> Причём в стимовской хл всё работает. Предлагаю попробовать voice_clientdebug 1 и посмотреть, что выводиться, и сравнить с голдсурсом

**GoldSource**
```
CVoiceStatus::UpdateSpeakerStatus: ent -1 talking = 1
CVoiceStatus::UpdateSpeakerStatus: ent -2 talking = 1
CVoiceStatus::UpdateSpeakerStatus: ent 5 talking = 1
CVoiceStatus::UpdateServerState: no change
```

**Xash3D FWGS 0.20.1**
```
CVoiceStatus::UpdateSpeakerStatus: ent -1 talking = 1
CVoiceStatus::UpdateSpeakerStatus: ent -2 talking = 1
CVoiceStatus::UpdateServerState: no change
```

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/3c682507e7764b73864006dd386ca854d06c783f
