### ISSUE TITLE
При воспроизведении voice_input.wav в голосовом чате (voice_inputfromfile 1) слышен замедленный трескающийся звук

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#969]

**Comment by Velaron** [comment]
Я вроде как запилил поддержку только конкретного формата, звуки из обычной хл например хорошо играются

**Comment by Vladislav4KZ** [comment]
> звуки из обычной хл например хорошо играются 

Вот именно что тестил на звуках из хл, они и трещат

**Comment by SNMetamorph** [comment]
А ты тестил на мобиле? Просто по идее обычный войс тоже может трещать, я разобрался в чем причина

**Comment by Vladislav4KZ** [comment]
> А ты тестил на мобиле?

Нет, тестил на компьютере. При попытке воспроизведения voice_input.wav на мобиле, движок крашится

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/2f5f5ef0a6cceddb6f54703b0cfbeeabce99498d
