### ISSUE TITLE
Краш при попытке выполнить команду voice_codecinfo

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#974]
Проверял на обновлённом сервере "Test Server XASH3D FWGS v0.20.1".
![image](https://user-images.githubusercontent.com/96422615/185445514-34a6c8f6-5993-4469-994a-015fd67b4953.png)

**Comment by Vladislav4KZ** [comment]
У меня на андроиде так было, на винде не крашит

**Comment by unnamed9** [comment]
Исправлено в последних коммитах
