### ISSUE TITLE
mdldec: implement support for decompiling models with bone weights

### ISSUE THREAD

**Issue by SNMetamorph** [FWGS/xash3d-fwgs#978]
[Crowbar](https://github.com/ZeqMacaw/Crowbar) decompiling tool can be used as reference for this

**Comment by nekonomicon** [comment]
Can you attach model for tests?

**Comment by SNMetamorph** [comment]
Yes, it's there
https://disk.yandex.ru/d/IxbJrQaNJS8Fbw

**Comment by nekonomicon** [comment]
Implemented in https://github.com/FWGS/xash3d-fwgs/commit/c551aefd77b72993328225d600b6160e55648b1e.
So must be closed.
