### ISSUE TITLE
Support xashxt

### ISSUE THREAD

**Issue by Accorsi66** [FWGS/xash3d-fwgs#98]
Asking if supports entities like env_sky, fog, mirror, etc.
If not do you guys are planning on supporting?

**Comment by nekonomicon** [comment]
What do you mean?

**Comment by SNMetamorph** [comment]
I planned to create fork of XashXT, which will be include all features from last version of XashXT and will work with Xash FWGS.

**Comment by nekonomicon** [comment]
XashXT work with Xash3D FWGS.
I do not understand issue author.

**Comment by a1batross** [comment]
At this time it may not, since I made multirenderer support.

Maybe some engine-side fixes may be required.

**Comment by mittorn** [comment]
Maybe make linux port first? It will be easier to debug it

**Comment by Accorsi66** [comment]
> XashXT work with Xash3D FWGS.
> I do not understand issue author.
It's not a issue just a question....

> At this time it may not, since I made multirenderer support.
> Some engine-side fixes may be required.
Ok, thanks gonna close now.

**Comment by a1batross** [comment]
Why closing tho? =/

**Comment by Accorsi66** [comment]
> Why closing tho? =/

It was just a question, but if you have plans to support it would be awesome.

**Comment by a1batross** [comment]
Yes we do. :)

**Comment by a1batross** [comment]
Original XashXT must work too, but recommended way to use XashXT with our fork is to migrate to [PrimeXT](https://github.com/SNMetamorph/PrimeXT) by @SNMetamorph
