### ISSUE TITLE
Когда воспроизводишь voice_input.wav со стерео звуком в голосовом чате, он проигрывается с пониженным тоном и замедленной скоростью

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#982]

**Comment by SNMetamorph** [comment]
Похоже на то, что функция Sound_Resample не делает ресемплинг до 48 kHz если у входящего набора данных частота сэмплирования 44.1 kHz

**Comment by Vladislav4KZ** [comment]
Со стерео звуком в 16 бит 48 кГц то же самое.

Моно звук 16 бит 48 кГц нормально воспроизводится, только после отключения голосового чата движок крашится из-за этого звука.

**Comment by Vladislav4KZ** [comment]
Лог с крашем при воспроизведении звука 16 бит 48 кГц
[engine.log](https://github.com/FWGS/xash3d-fwgs/files/9387301/engine.log)

Краш происходит только с длительными звуками, например музыкой после отключения голосового чата.

**Comment by Vladislav4KZ** [comment]
Дело оказывается не в частоте, а в стерео звуке. Моно звук в 44,1 кГц нормально воспроизводится.

**Comment by Vladislav4KZ** [comment]
Повторно воспроизвёл музыку в 16 бит 48 кГц, теперь не крашнуло. Проверял на локальном сервере.

**Comment by Vladislav4KZ** [comment]
На сервере в интернете проверил, тоже теперь не крашит игру.

**Comment by a1batross** [comment]
Не хочется только ради таких саундборд-подобных развлечений втаскивать в движок поддержку стерео WAV. Тем более движок всё равно не работает со стерео звуками.

Поэтому такие WAV файлы надо отсекать.

По личному опыту, 16 бит 44100 проигралось замечательно, без видимых искажений.

**Comment by a1batross** [comment]
Но я ещё буду пробовать подключать Opus Custom Encoder/Decoder чтобы не кодировать в 48000, который всё равно не поддерживается движком.

И только если это не сработает -- писать ресемплер, и я даже не знаю как %)

**Comment by Vladislav4KZ** [comment]
Краш воспроизводится, только когда повторно воспроизводишь звук в 16 бит 48 кГц. С первого раза краша нет.

Со звуком в 16 бит 44,1 кГц игра не крашится вообще. Хоть несколько раз включай.

**Comment by a1batross** [comment]
Проверь с последним коммитом.

**Comment by Vladislav4KZ** [comment]
> Проверь с последним коммитом.

Баг всё ещё воспроизводится.

**Comment by Vladislav4KZ** [comment]
Тут я подозреваю, что при воспроизведении стерео трека в голосовом чате, его частота дискретизации делится на 2.

Например, аудиофайл с частотой 44100 Гц звучит как 22050 Гц без ресемплинга.

Можно сравнить звук, воспроизводимый в голосовом чате ксаша, и в Audacity, открыв там этот аудиофайл, и сменив частоту на ту, которая в два раза ниже исходной (не частоту проекта, а там где название файла -> Частота дискретизации -> Частота в Гц)

![Снимок экрана 2024-07-14 225616.png](https://github.com/user-attachments/assets/fd420cdc-8ae5-4619-add2-22fbbab86fd0)

И звучать оно будет точно так же.

**Comment by a1batross** [comment]
@Vladislav4KZ спасибо за разбор, два года назад я не догадался как сделать всё проще. Возможно, сначала надо было переписать конверсию между форматами в soundlib. :)

Запушил ветку stereo-mono-stereo, там можно проверить как работает конверсия. Локально под рукой был трек длиной 3 минуты 40 секунд, который после перекодирования в S16LE 44100 wav файл, в ксаше на x86 сконвертился за 5-10 миллисекунд.

Пингану ещё @SNMetamorph

Изменения только на клиентской стороне, можно проверить на моём сервере в халфе.

**Comment by Vladislav4KZ** [comment]
Установил ксаш собранный из ветки stereo-mono-stereo, коммит: https://github.com/FWGS/xash3d-fwgs/commit/c7e566f43dbdc9158e9cf5b29c939b4dcde7fd73

При воспроизведении стерео аудиофайла в голосовом чате его скорость и тональность больше не меняется.
Звучит так, как и должно звучать (но только в моно формате).

**Comment by a1batross** [comment]
Ну да, голос передается пока что передается только в mono, поэтому только конверсия.

Надо будет тщательно проверить конверсию между разными форматами, частотой дискретизации и теперь количеством каналов, а то я там нарефакторил кода, и после можно будет замержить.

**Comment by SNMetamorph** [comment]
> Ну да, голос передается пока что передается только в mono, поэтому только конверсия.

Я думаю, его имеет смысл только в моно передавать. А к этому еще можно добавить опциональную фичу, чтобы источник звука был привязан к позиции говорящего игрока. Для некоторых гейммодов это было бы полезно весьма

**Comment by a1batross** [comment]
@SNMetamorph верно. Заведёшь ишшую, чтобы не забыть?

**Comment by SNMetamorph** [comment]
> @SNMetamorph верно. Заведёшь ишшую, чтобы не забыть?

Да, без проблем.
