### ISSUE TITLE
[Linux] Трещит звук в голосовом чате

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#983]
Когда со мной на сервере играли игроки на линуксе, у них трещал звук

У пользователей Windows такой проблемы нет.

**Comment by Vladislav4KZ** [comment]
На Android при проигрывании voice_input.wav в голосовом чате звук прерывистый.

net_speeds:
Updaterate: 10 min, 24 cur, 30 max

В net_graph choke доходит до 12

**Comment by Vladislav4KZ** [comment]
Если что, я тестил войсчат подключенным к интернет серверу на мобильной 4G сети

**Comment by Vladislav4KZ** [comment]
На локальном сервере на Android с этим проблем нет.

Там Updaterate: 10 min, 60 cur, 72 max
И в net_graph нет choke (choke: 0)

**Comment by Vladislav4KZ** [comment]
cl_updaterate на Android почему-то был настроен на 20 (и это кстати, дефолтное значение ксаша)

**Comment by Vladislav4KZ** [comment]
Настроил cl_updaterate на 101, без войсчата на сервере показывает Updaterate: 10 min, 50-60 cur, 72 max

А когда включаю войсчат, то Updaterate: 10 min, 10-40 cur, 72 max

Звук бывает то нормальный, то прерывистый.

**Comment by Vladislav4KZ** [comment]
И choke теперь стал доходить до 60 при включенном голосовом чате с cl_updaterate 101

**Comment by SNMetamorph** [comment]
Choke повышается по двум причинам: либо у клиента выставлен низкий rate, либо у сервера выставлен низкий sv_maxrate

**Comment by SNMetamorph** [comment]
Для правильной работы войсчата нужно, чтобы cl_updaterate был хотя бы 40, rate или sv_maxrate был хотя бы 30000

**Comment by Elinsrc** [comment]
насервере стоит стандартный sv_maxrate , тоесть на 50000

**Comment by Vladislav4KZ** [comment]
> Choke повышается по двум причинам: либо у клиента выставлен низкий rate, либо у сервера выставлен низкий sv_maxrate

Да, у меня на андроиде стоит очень низкий rate: 2500

**Comment by Vladislav4KZ** [comment]
> насервере стоит стандартный sv_maxrate , тоесть на 50000

Я заходил на сервер от hype "0.20 engine test"

**Comment by Vladislav4KZ** [comment]
Поставил rate 25000, зашёл на сервер Elin'а

Звук более-менее нормальный и Updaterate 40-48 cur.

**Comment by Vladislav4KZ** [comment]
Зашёл опять на сервер от hype, там Updaterate 50-60 cur, но звук прерывистый

**Comment by Vladislav4KZ** [comment]
К сведению, сервер от Elin называется "Test Server Xash3D FWGS 0.20.1"
Сервер от hype "0.20 engine test"

**Comment by Vladislav4KZ** [comment]
> У пользователей Windows такой проблемы нет.

У игроков с Android тоже такой проблемы нет. Позавчера, играя на сервере слышал что они воспроизводили музыку в голосовом чате, и она не трещала.

**Comment by Vladislav4KZ** [comment]
Этот багрепорт я писал 2 года назад, когда у hype были проблемы с голосовым чатом.

Сейчас не знаю как обстоят с этим дела, если проблема всё ещё осталась, пусть он сам откроет issue.

Я сам ни разу не проверял голосовой чат на линуксе.

**Comment by a1batross** [comment]
Там есть проблемы, но они не должны быть связаны конкретно с линуксом или виндой.
