### ISSUE TITLE
Не слышно других игроков, использующие войс-чат.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#984]
При подключении к серверу так-же пишется.
"VoiceCapture_Init: error creating capture device (WASAPI can't find requested audio endpoint: Element not found.)"

**Comment by a1batross** [comment]
У тебя микрофон в системе есть?

**Comment by unnamed9** [comment]
@a1batross Нету.

**Comment by a1batross** [comment]
Ну если винда не дает устройство, значит и микрофона нет %)

А так, слышать других ты должен.

**Comment by unnamed9** [comment]
Исправили в коммите https://github.com/FWGS/xash3d-fwgs/commit/0b5067891240b3dd87a5c81c6408932b11c52630.
