### ISSUE TITLE
Краш, при попытке зайти на обновлённый Cringe DM.

### ISSUE THREAD

**Issue by unnamed9** [FWGS/xash3d-fwgs#989]
![image](https://user-images.githubusercontent.com/96422615/185784017-3187db0a-328a-4abf-a18d-ce30e654331c.png)

**Comment by unnamed9** [comment]
Судя по разговору с @Vladislav4KZ, крашится из-за этого звука.
https://elinserver.ru/fastdl/sound/bbox/music8.mp3

**Comment by Vladislav4KZ** [comment]
На Android кстати такой проблемы нет. Зашёл на указанный сервер с телефона, и движок не крашнулся. Только заметил зависание при подключении на несколько секунд (подключалось дольше чем обычно).

**Comment by Vladislav4KZ** [comment]
Зависает оно конкретно на моменте ресемплинга музыки.

![Screenshot_20220821-202249.png](https://user-images.githubusercontent.com/22411953/185796648-168e95c0-8037-4dab-8260-1865b325a04f.png)

Ошибка из-за неудачного подключения к серверу появилась из-за сворачивания игры, а так с этим проблем нет.

**Comment by a1batross** [comment]
Зависание не так страшно. Sound_Process медленный.

Скрин со стектрейсом прям гениально обрезан, как раз у номера строчки. :)

**Comment by Vladislav4KZ** [comment]
> Скрин со стектрейсом прям гениально обрезан, как раз у номера строчки. :)

У меня есть копия с лога
```
Sys_Crash: address 6F899B43, code C0000005
Exception: D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\soundlib\snd_utils.c:209:5
PC: D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\soundlib\snd_utils.c:209:5
 0 6F899B43 Sound_ResampleInternal (D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\soundlib\snd_utils.c:209:5) (xash.dll)
 1 6F8998CE Sound_Process (D:\a\xash3d-fwgs\xash3d-fwgs\engine\common\soundlib\snd_utils.c:256:17) (xash.dll)
 2 6F937243 S_LoadSound (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\s_load.c:161:10) (xash.dll)
 3 6F937313 S_RegisterSound (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\s_load.c:353:15) (xash.dll)
 4 6F9022E6 CL_ParseLegacyServerMessage (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\cl_parse.c:3062:76) (xash.dll)
 5 6F8FB101 CL_ReadNetMessage (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\cl_main.c:2264:0) (xash.dll)
 6 6F8FB33A CL_ReadPackets (D:\a\xash3d-fwgs\xash3d-fwgs\engine\client\cl_main.c:2315:0) (xash.dll)
 7 6F8FCFA0 Host_ClientFrame(xash.dll)
 8 6F84C744 Host_Frame(xash.dll)
 9 6F8((n()Host_WriteGLConfig()
```

**Comment by Vladislav4KZ** [comment]
Исправлено в коммите: https://github.com/FWGS/xash3d-fwgs/commit/f435a81c97f9f01986c69f7461d9dbc48691466d
