### ISSUE TITLE
[MOD: OpenAG] Исчезает курсор в меню после отключения от сервера или сворачивания-разворачивания игры

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#996]
Проблема устраняется открытием и закрытием консоли.

**Comment by Vladislav4KZ** [comment]
У меня установлен OpenAG клиент в Half-Life https://github.com/YaLTeR/OpenAG

**Comment by a1batross** [comment]
Во всех ишшуях касательно minimize/maximize ты полноэкранный режим используешь?

**Comment by Vladislav4KZ** [comment]
Этот баг также воспроизводится в оконном режиме.

**Comment by Vladislav4KZ** [comment]
Баг с исчезновением курсора при отключении от сервера (введя в консоль команду ``disconnect``) также воспроизводится в оконном режиме.

**Comment by Vladislav4KZ** [comment]
Баг с исчезновением курсора проявляется и при смене разрешения экрана, как в полноэкранном так и в оконном режиме.

**Comment by Vladislav4KZ** [comment]
@a1batross проблема с исчезновением курсора при вводе в консоль команды ``disconnect`` с клиентом OpenAG ещё актуальна.

Исчез только баг с исчезновением курсора после восстановления свёрнутой игры.
