### ISSUE TITLE
К голосовому чату применяется эффект реверберации

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#998]
Перемещаясь по карте, можно услышать эхо от звука из голосового чата.

**Comment by Vladislav4KZ** [comment]
На GoldSource конечно же такое не происходит.

**Comment by a1batross** [comment]
Probably should rewrite mixer first, since it... uhh... not the part I would like to modify or work with.

Ask Uncle Mike why he was so lazy while implementing a sound mixer.
