### ISSUE TITLE
Не отображаются уведомления в правом верхнем углу экрана

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/xash3d-fwgs#999]
![2fort_0000.png](https://user-images.githubusercontent.com/22411953/186139808-c7194a61-0d12-48d6-b502-744e3063ec42.png)
**Скриншот сделан на Xash3D FWGS 0.19.2**

Эти уведомления работают только в WON версии Half-Life и Xash3D FWGS 0.19.2

Там обычно пишется что какой-то игрок зашёл в какую-то команду, зашёл за наблюдателей и т.д.

В Steam версии Half-Life и Xash3D FWGS 0.20.1 они не отображаются.
Они отображаются только в левом верхнем краю экрана, когда включён режим разработчика ``developer 1``

**Comment by tear-vyps** [comment]
Это и есть ConsolePrint, можно вернуть ему этот механизм с уведомлениями? Сейчас он не работает

**Comment by a1batross** [comment]
Я его на всякий сверю с hw.dll из WON, и если там так и есть, то верну обратно.

**Comment by a1batross** [comment]
Fixed in 7341a6b0

**Comment by Vladislav4KZ** [comment]
@a1batross Эти уведомления сё ещё не работают на последнем коммите.

**Comment by Vladislav4KZ** [comment]
Теперь работает на последнем коммите:
https://github.com/FWGS/xash3d-fwgs/commit/3e9f2df2bf20177834db74e07b1b712ebd77d286
